### ISSUE TITLE
感觉播放的操作逻辑不连贯

### ISSUE THREAD

**Issue by springhack** [lhc70000/iina#1]
当然这可能是我的个人感觉：

> 默认设置下减速，加速，播放/暂停三个按钮的逻辑不是很连贯。
> 1. 当减速或加速之后，暂停&播放，速度回归正常；
> 2. 当加速时，想稍微减缓速度，点击减速则直接变为减速，反之亦然；
> 3. 当减速加速的时候，想跳回默认速度，只能按照 1 的方法。

**Comment by lhc70000** [comment]
这是 QuickTime 的默认行为，而 IINA 试图和系统 App 保持一致。如果需求很大，会考虑修改。

**Comment by lhc70000** [comment]
已在 0.0.7 中优化此逻辑。
