### ISSUE TITLE
Support watch later | 退出后继续进度

### ISSUE THREAD

**Issue by morphinewan** [lhc70000/iina#10]
mpv配置文件里面设置了选项
`save-position-on-quit=yes`

使用mpv命令行本身，继续播放这个功能是可用的。

然后使用IINA默认无法实现这个功能。

尝试使用高级功能里面的额外mpv选项，手动添加参数，没有效果

指定使用配置目录，也没有效果。

<img width="592" alt="2017-01-05 07 55 46" src="https://cloud.githubusercontent.com/assets/458887/21663619/651b0d0e-d31c-11e6-84e4-07ba93dd9e08.png">

**Comment by morphinewan** [comment]
@droid-Q 使用绝对路径，会假死，程序完全没反应，必须强退才行，这里面还是有bug

**Comment by droid-Q** [comment]
@morphinewan 我测试后并没有假死，watch_later目录是正常写入了，但好像读取还有问题。只能再看看。

**Comment by morphinewan** [comment]
再次试验，使用快捷Q退出后，再次打开文件，播放进度能够恢复。但是按Q退出时，程序会crash。

Application Specific Information:
Assertion failed: (!ctx->initialized), function free_ctx, file ../video/out/vo_opengl_cb.c, line 113.

**Comment by lhc70000** [comment]
目前 IINA 使用 `load-file` 命令打开文件，似乎它不支持 mpv 的 watch_later。可能只有命令行传入文件打开的时候才会恢复进度？

待确认，有发现我会随时 update。

---

Now IINA opens file by calling `load-file` command, which seems does not support mpv's watch_later feature. I'll try to dig for more information.

**Comment by androidcn** [comment]
尽快支持这个功能,不然无法作为主力Player

**Comment by lhc70000** [comment]
@androidcn 我可能需要问下 mpv。0.0.2 很快会发布；此功能会在 0.0.3 中支持。

毕竟 Alpha，不太建议日常使用，还请多多理解。

**Comment by xu-cheng** [comment]
@lhc70000 我大概定为到这个bug的源头，但不知如何修复。

mpv的`save-position-on-quit`功能只会在mpv接受QUIT command的情况下才会生效。而且iina中，退出时会先清空Window的GLContext，再发送QUIT command。这样的结果是mpv会因为GLContext回收而退出，所以`save-position-on-quit`不会起效。

使用如下的diff，就可以解决如上问题。实际测试可以成功存储和读取 watch_later。但是这会导致iina退出时报告segment fault，所有我也不知道如何完美修复这个问题。

```diff
diff --git a/iina/PlayerCore.swift b/iina/PlayerCore.swift
index 631bf6b..0ceb81a 100644
--- a/iina/PlayerCore.swift
+++ b/iina/PlayerCore.swift
@@ -82,13 +82,13 @@ class PlayerCore: NSObject {
   func terminateMPV(sendQuit: Bool = true) {
     guard !isMpvTerminated else { return }
     syncPlayTimeTimer?.invalidate()
+    if sendQuit {
+      mpvController.mpvQuit()
+    }
     if mainWindow.isWindowLoaded {
       mainWindow.videoView.uninit()
       mainWindow.videoView.clearGLContext()
     }
-    if sendQuit {
-      mpvController.mpvQuit()
-    }
     isMpvTerminated = true
   }
 ```

**Comment by lhc70000** [comment]
@xu-cheng 
我其实之前就试过（第一个版本发布之前的设置中还有此选项，也定义了 `watch_later` 文件夹的位置），但是当时发现不工作才在发布前去掉了。

当时我是在退出前执行 `quit-watch-later` 命令来写入 watch_later 信息，而且确认文件夹中有写入；但是打开文件时无法继续进度，所以猜测使用 `load-file` 打开文件（现在 IINA 的行为）时，是不会继续进度的（只有命令行中传入的文件名才有作用）。

如果您测试的 `load-file` 命令可以恢复进度，那就很好办了。

**Comment by xu-cheng** [comment]
@lhc70000 使用我上面的diff，不需要手动执行`quit-watch-later` 或 `load-file`命令就可以完成读写watch_later的功能。但是会在退出时包括：
```
Application Specific Information:
Performing @selector(terminate:) from sender NSMenuItem 0x6180000bbf60
Assertion failed: (h->canary == CANARY), function ta_dbg_check_header, file ../ta/ta.c, line 333.
```

**Comment by lhc70000** [comment]
感谢！让我试一下。

**Comment by tony1016** [comment]
关注这个问题，不能发展成VLC💔
