### ISSUE TITLE
Adding Picture in Picture Support

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#100]
I'd like to start working on Picture in Picture support for iina (even though it requires PIP.framework, which is private, we could link to it); is this something that you have on the roadmap?

**Comment by lhc70000** [comment]
It's not in my plan but will be awesome if you could add PIP support.

However there are too much changes needed to be done these days, so I suggest starting this feature later, like after v0.0.2.

**Comment by saagarjha** [comment]
#165.
