### ISSUE TITLE
About different Keyboard layout

### ISSUE THREAD

**Issue by VonFry** [lhc70000/iina#1000]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12-build37

**Expected behavior:**
My layout is `programmer dvorak` which is different the default keyboard layout named `qwerty`.

For example: default playlist-next shortcut is `>`. We can click `S-.` with `QWERTY` layout, but this cannot do on `dvorak`. I must click the same physical key on my keyboard which is `S-v`.

**Actual behavior:**

This problom also happends on some input tools ( i.e. 清歌输入法 ). They use the layout which user used. But we want to use a layout forced configure with them. 

Now, we want to use a layout with our keyboard instead of a forced one. When using different layout, here is a different thinking in our mind.

**Comment by lhc70000** [comment]
Duplicate with #191, #759.

**Comment by VonFry** [comment]
All right. Sorry about send it again.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
