### ISSUE TITLE
Popcorn Time x IINA

### ISSUE THREAD

**Issue by MichelDrucker** [lhc70000/iina#1001]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Feature**

Hi,
since IINA is based on mpv I was wondering if there was a simple way to have it work as an external player on Popcorn Time ?

Thank you very much !

**Comment by saagarjha** [comment]
Offhand, couldn't you point IINA at the partially downloaded file that Popcorn Time would generate?

**Comment by MichelDrucker** [comment]
That's what i'm currently doing but was wondering about a direct connection *à la* mpv ! I modified the ext-player.js but it doesn't open the stream on its own...

**Comment by kjyv** [comment]
Add this to ext-player.js with a recent version of IINA:
```
        'IINA': {
            type: 'mpv',
            cmd: '/Contents/MacOS/iina-cli',
            subswitch: '--mpv-sub-file=',
            fs: '--mpv-fs'
        },
```

**Comment by MichelDrucker** [comment]
Works like a charm!
Thanks a lot.

**Comment by inflation** [comment]
The problem seems to be solved. Feel free to reopen it @MichelDrucker
