### ISSUE TITLE
option to have settings show in a floating window instead of panel

### ISSUE THREAD

**Issue by negativeions** [lhc70000/iina#1006]
- macOS 10.12.6
- IINA 0.0.12

In some cases it would be more helpful to have a separate floating window for settings/AV controls instead of a pullout panel... as per this comment:
https://www.reddit.com/r/apple/comments/6ls4hs/vlc_alternative_iina_is_so_much_better_try_it_out/djwfbyp/

**Comment by saagarjha** [comment]
Duplicate of #809.
