### ISSUE TITLE
开启时显示一个选择文件窗口

### ISSUE THREAD

**Issue by megabitsenmzq** [lhc70000/iina#101]
就像是 
![2017-01-08 12 03 25](https://cloud.githubusercontent.com/assets/5499507/21747211/881dc758-d59a-11e6-913e-b36fb31daf5d.png)
macOS 这些系统 App 一样

**Comment by lhc70000** [comment]
Thank you for feedback.

Duplicate with #13.

---

与 #13 重复。

**Comment by lhc70000** [comment]
Close as fixed in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).
