### ISSUE TITLE
scrolling with on-screen controller when paused doesn't stay paused once specific frame is selected

### ISSUE THREAD

**Issue by whirk** [lhc70000/iina#1010]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 Build 37

**Expected behavior:**

click and drag on-screen controller when video is paused to seek to a specific frame in the movie and then stay paused after specific frame in on-screen controller is selected.

**Current Behavior:**

when a video is paused, and then you seek through to a specific frame with the on-screen controller the video will autoplay after a location/frame is chosen instead of staying paused..

i have my scroll vertically to preference set to seek and it functions properly when using scroll controls by not auto-playing after seeking but not when using the on-screen controller..

**Comment by lhc70000** [comment]
Should be the same problem as #877, which has been fixed by #973 in develop branch.
