### ISSUE TITLE
Undesired behavior when entered full screen in PIP

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#1013]
**Steps to reproduce**

- Open a video.
- Enter PIP first.
- Enter full screen.
- The PIP window only displays a small portion of the video.

cc @saagarjha 

Should we disable full screen when PIP is active?

**Comment by saagarjha** [comment]
I think the best thing to do is to exit PIP and enter fullscreen. That's what Safari does.

**Comment by lhc70000** [comment]
Sounds better. Are you going to implement it?

**Comment by saagarjha** [comment]
Sure.

**Comment by saagarjha** [comment]
#1014.
