### ISSUE TITLE
Feature request: setting default windows size.

### ISSUE THREAD

**Issue by kennazeng** [lhc70000/iina#1015]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

need a new feature, set default windows size in setting, like default is 1x, 1.5x, 2x.

**Comment by JohnClay** [comment]
This would be great, especially if there were an option to have it scale to "Fit to screen".

**Comment by HeRoKaNe** [comment]
I was just about to post about the same thing. An option to globally open all files scalled "Fit to screen" would be great.
