### ISSUE TITLE
Window title does not fade away in youtube stream

### ISSUE THREAD

**Issue by klendrop** [lhc70000/iina#1018]
**System and IINA version:**

- macOS 10.11
- IINA 0.0.12

**Expected behavior:**
After not using the controls or moving the mouse pointer outside the window, the window title should fade away like the rest of the UI. Like it does when playing a video file.

**Actual behavior:**
The title stays visible.
Example: http://imgur.com/a/ex57d

**Comment by lhc70000** [comment]
Fixed in develop.

**Comment by klendrop** [comment]
thank you
