### ISSUE TITLE
建议：能使用人工智能做到自动翻译，我觉着付费也未尝不可

### ISSUE THREAD

**Issue by howenx** [lhc70000/iina#1022]
建议：能使用人工智能做到视频播放时自动翻译，我觉着付费也未尝不可

**Comment by ztxgeol** [comment]
don't be an asshole.

**Comment by Rdxer** [comment]
人工智能? 我只要实时翻译管他智能不智能 参考 youtobe 🤤  提供翻译服务,按翻译时长收费也不是不可以 🤤

**Comment by gonejack** [comment]
活在梦里，这样的投入，翻译一次要收费一百万

**Comment by howenx** [comment]
@ztxgeol your family all are  asshole

**Comment by howenx** [comment]
@gonejack 给50万我可以搞定
