### ISSUE TITLE
Remote documents' titles don't fade away

### ISSUE THREAD

**Issue by tellowkrinkle** [lhc70000/iina#1026]
**System and IINA version:**

- macOS 10.13 Beta 17A360a
- IINA 0.0.12

**Expected behavior:**
When you mouse off the window, the titlebar and title will fade away

**Actual behavior:**
When you mouse off the window, the titlebar fades away, but the text doesn't fade with it.

**Steps to reproduce:**
- Quit IINA (If you open a remote URL after opening and closing a local URL, IINA doesn't update the "currently open file" parameter so the window acts like a local file)
- Open IINA and open a Youtube URL or use a browser extension to do the same thing
- Move the mouse off the window

- [x] MPV does not have this problem.
- [x] IINA < 0.0.12 does not have this problem.

**How often does this happen?**
Every time the above steps are followed

**Screenshot (Look at the top center):**
<img width="960" alt="titlefadebug" src="https://user-images.githubusercontent.com/3315070/30305518-f244af9c-9738-11e7-977d-03a2744366cc.png">

**Comment by mikerathbun** [comment]
I verified this on the current 0.0.12 released version and you are right. I then tried this on a build based off of the Develop branch and the issue is not there. So when the next version is released you shouldn't have that problem anymore.

**Comment by alejx** [comment]
Thanks for reporting this. This issue still exists based on my test on develop branch.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
