### ISSUE TITLE
trackpad experience issues

### ISSUE THREAD

**Issue by bearcolin** [lhc70000/iina#1027]
**two-finger scrolling speed is too fast on short video clips**

I don't know what speed it will be on long video clips, like a movie or something, I was just playing my 10 seconds short videos, and the two finger scrolling speed is too fast, very easy to **jump to the next clip, that was very annoying**, because I was not meant to jump it, and I couldn't make it jump back.

The native QuickTime Player doing scrolling very well, it feels very smooth and controllable.

Please consider that, thanks.

**Comment by lhc70000** [comment]
It's a technical constraint. You can expect a better experience especially for short videos by using exact (or auto) seek in `Preferences > Control`.
