### ISSUE TITLE
can not play mp3 audio

### ISSUE THREAD

**Issue by henng** [lhc70000/iina#103]
"Frame buffer check failed" when open mp3 audio files.

![](https://ww1.sinaimg.cn/large/006tKfTcgw1fbj7380mupj311e0j875t.jpg)

**Comment by lhc70000** [comment]
Currently IINA only supports media with "video stream", even an album cover image in mp3 file.

We'll try to fix it as soon as possible.

**Comment by arkon** [comment]
This occurred when opening a FLAC file without an album cover too. I assume it's the same issue,

**Comment by lhc70000** [comment]
Close due to fixed in [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3).
