### ISSUE TITLE
Single Click on Progress Bar Causes Unexpected Pause / Resume Behavior

### ISSUE THREAD

**Issue by genmao** [lhc70000/iina#1036]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 Build 37

**Expected behavior:**

When clicking on progress bar to preview or find specific point of a video, the player stream should only move to that point, and maintain current status (pause / playing). 
**Actual behavior:**
When clicking, the player will resume -> pause -> resume -> pause....

**Comment by alejx** [comment]
Duplicate of #877, fixed in #973.
