### ISSUE TITLE
iina影响系统CAPS健中英文切换

### ISSUE THREAD

**Issue by zh-chen** [lhc70000/iina#1037]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Actual behavior:**
打开iina会使得系统的CAPS键无法切换中英文，但是在激活iina窗口的时候又是正常的。退出iina，CAPS键功能又恢复正常。

**How often does this happen?**
everytime

**Comment by gonejack** [comment]
我觉得IINA键盘方面还有个坑就是和物理布局绑定了，导致用其他布局比如我用Colemak英文布局的，就经常按错键。快捷键还有大小写区分也没有明显提示，设置看到截图快捷键是S，我的Colemak键盘是按d，结果无效，再加上Shift，还是无效，摸索半天才知道要用QWERTY布局的大写S。

**Comment by lhc70000** [comment]
@zh-chen Duplicated. It's a mpv bug.
@gonejack Duplicated. We'll fix it before 0.1.0

See #898 for the current plan.
