### ISSUE TITLE
希望有音视频转码剪辑合并转GIF功能

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#1044]
希望有转码，音频视频合并剪辑功能

现在在网上下载的flv经常是
```
ffmpeg -i in.flv -c -copy -copyts out.mp4
```
直接拿出视频流不经转码直接封进mp4，之后再用QuickTime播放器掐头去尾做剪接。或者右键视频文件，Encode Selected Audio Files将视频转音频。有些八仙过海各显神通的样子，做个事情用到各种工具，如果IINA把这些都集成了就爽了，因为有成功的例子，Windows下的QQ影音，这些方面做得很好用，可以借鉴下。

**Comment by Cantar4** [comment]
is there a translation somewhere ?

**Comment by lhc70000** [comment]
@Cantar4 He's suggesting simple video editing functionalities.

@gonejack 
目前不在计划内，我们希望先加强播放有关的功能。
They are not in current plan. We want to spare more effort on playback related features.

**Comment by gonejack** [comment]
@Cantar4 I suggest some simple editing functions like trim or Clips concating,

**Comment by bofeiw** [comment]
@lhc70000 希望集成一个转gif的功能，每次转gif都去网络找在线gif转换器比较麻烦，两年过去了，考虑一下吗？

**Comment by HarukaMa** [comment]
@bofeiw IINA 是播放器，应该不会考虑输出和转换功能。今后可能可以通过插件系统实现。
