### ISSUE TITLE
请问播放置顶的命令是什么？想要自定义开关置顶的快捷键 在图形界面中没找到

### ISSUE THREAD

**Issue by Sev73n** [lhc70000/iina#1045]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
请使用最新版。
![44dfec44-8bc1-4178-b87e-99dab1740651](https://user-images.githubusercontent.com/8478049/30701959-36d5189e-9f1e-11e7-8f5b-d92be54536ca.png)

**Comment by Sev73n** [comment]
哇 居然有二级菜单 希望下次在有二级菜单的选项后加点标注

**Comment by lhc70000** [comment]
@Sev73n 有道理。
