### ISSUE TITLE
XYZ to rgb color space distortion in DCP’s J2K images 

### ISSUE THREAD

**Issue by Cantar4** [lhc70000/iina#1046]
seen as a magenta color cast

**Comment by HarukaMa** [comment]
I've confirmed that some specific format of JPEG2000 images are incorrectly rendered. However we rely on mpv to do the decoding and couldn't do anything on that at the moment. I'd suggest reporting this issue to mpv.

**Comment by saagarjha** [comment]
@Cantar4 Psst…If you press Space when taking a screenshot, it lets you select a window to take a screenshot of so you don't have other stuff in it.

**Comment by Cantar4** [comment]
in this case, with [shift  command  4], I purposedly selected the screen bar
over the picts to be sure there is no mis-interpretation  ;-)

**Comment by Cantar4** [comment]
@HarukaMa,  Niklas Haasn (mdv) made a thorough analysis of the issue, 
https://github.com/mpv-player/mpv/issues/4925
it appears his proposition about the white point selection should be preferably offered 
to users on your side...

Here attached, a link to a light (5MB) seven jpeg2000 images mxf container
[j2c_24d9f1b0-2492-4b88-8524-582a42775cff.mxf.zip](https://github.com/lhc70000/iina/files/1336054/j2c_24d9f1b0-2492-4b88-8524-582a42775cff.mxf.zip)
