### ISSUE TITLE
On Screen Controller Moving Around Randomly.

### ISSUE THREAD

**Issue by thekoc** [lhc70000/iina#1047]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**
The floating control bar shouldn't move around randomly.

**Steps to reproduce:**
![](https://ws4.sinaimg.cn/large/006tNc79gy1fjx442wp16g31hc0sw1kx.gif)
https://ws4.sinaimg.cn/large/006tNc79gy1fjx442wp16g31hc0sw1kx.gif

Open a video, set the controller to "Floating". Click on the left side of the controller, then move cursor to the right of it, click, then move back to left and click again. Repeat the steps below.

It's no just happening on 10.13, but also happening on 10.12.* before I upgraded.

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by lhc70000** [comment]
Cannot reproduce on develop branch, so perhaps it's fixed. Please test again after IINA 0.0.13 released.

**Comment by thekoc** [comment]
@lhc70000 
I find that only if you use IINA.app while running [EuDic](https://www.eudic.net/eudic/mac_dictionary.aspx) can this problem be reproduced.

Any ideas?

**Comment by inflation** [comment]
@thekoc Eudic may use some hack to support reading from the screen. Can you try to disable that feature and see if anything improves?

**Comment by thekoc** [comment]
@inflation 
I disabled all screen reading features in Eudic but the problem still remains.
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fkhmkinrqvj30yk114wju.jpg)

Also someone [said](https://www.v2ex.com/t/397543#reply0) this problem exist even if the Eudic has been closed.

**Comment by inflation** [comment]
I'm suspecting that the '鼠標取詞輔助工具' is using the Accessibility Tool to do that. Can you disable that as well?

**Comment by thekoc** [comment]
@inflation 
I never enabled that...

I tried to disable all accessibility but the problem still exist.
![](https://ws4.sinaimg.cn/large/006tKfTcgy1fkhnqshz35j317c122q7i.jpg)

I installed the Mac App Store version of Eudic and unchecked all checkbox in Accessibility Panel but as long as the Eudic is running the controller will move around randomly.

**Comment by zhoujs12** [comment]
I also have this problem, but I don’t have Eudic App.

**Comment by xjkdev** [comment]
I experience this problem too. After disable bettertouchtool for iina, this problem vanished. Maybe it does have relation with accessibility tools.

**Comment by lhc70000** [comment]
Yes, it should be related to some third party apps.
