### ISSUE TITLE
Can't play next video automatically 

### ISSUE THREAD

**Issue by yangyu** [lhc70000/iina#1048]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.11

It can in old versions but not in new version. 

**Expected behavior:**
Automatically play next video 

For example:

I have files : xxx.s01e01....mkv 
xxx.s01e02.....mkv 

I want they can be played by sequence. 

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Please firstly upgrade to 0.0.12.

**Comment by yangyu** [comment]
It seems ok when I upgrade to 0.0.12. Thank you very much.
