### ISSUE TITLE
Hardware H265 decoder not used on High Sierra

### ISSUE THREAD

**Issue by m1h4** [lhc70000/iina#1054]
IINA is not using Apple's optimized/hardware accelerated built-in H.265 decoder on High Sierra. Tried with the public version 0.0.2 and latest develop build at 76dca381f2efddfba34f7617cce541599cf9bf2d.

**Comment by lhc70000** [comment]
IINA is based mpv, which uses FFmpeg for decoding.

FFmpeg just added HEVC hwdec several hours ago, so we can expect it being available once mpv released a new version with the new FFmpeg.

**Comment by m1h4** [comment]
Makes sense, thanks for the info!

**Comment by plivox** [comment]
Works for me with these options in mpv:

```
brew upgrade ffmpeg --HEAD
brew install --build-from-source mpv
```

(+) Video --vid=1 (*) (hevc 3840x2160 23.976fps) = 11,7 CPU used !

**Comment by adriel** [comment]
Just a heads up, the latest update 0.0.14 has the new ffmpeg and supports hardware decoding H265! (and it works amazingly, thank you dev/s and ffmpeg team!)
https://github.com/lhc70000/iina/releases/tag/v0.0.14
