### ISSUE TITLE
Plesase add system wide format binding and pls increase max valume limit

### ISSUE THREAD

**Issue by r0ysue** [lhc70000/iina#1055]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 Build 34

**Expected behavior:**

**Actual behavior:**

**_1.Please add system wide format binding 

In China ,all of the media player trying to change default media player for the whole system users ... I have to get this feature to earn the control back

2.pls increase max volume limit

Some movies have very low volume voltage , even in maximum volume cannot hear them well , hope IINA can get 200% or 300% volume so that we can hear them well ._**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
> Please add system wide format binding

Help > Set IINA as the Default App

>  increase max volume limit

You can set it in Preferences > Codec. It only works for keyboard shortcuts now, but the next version will solve the problem completely.
