### ISSUE TITLE
How to enable Picture-in-Picture mode ?

### ISSUE THREAD

**Issue by RoberMac** [lhc70000/iina#1057]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.11

**Comment by saagarjha** [comment]
You can find it under the Video menu as "Enter Picture in Picture", or use the shortcut for it (⌃⌘P).

**Comment by RoberMac** [comment]
It works, thanks @saagarjha ! @lhc70000 Maybe put it to the Screen Controller ?

**Comment by alejx** [comment]
@RoberMac Please follow [this thread](https://github.com/lhc70000/iina/issues/352) for this request.
