### ISSUE TITLE
任务栏→音频→音量+-10%选项，实际上是5%

### ISSUE THREAD

**Issue by APE1980s** [lhc70000/iina#106]
如题，点击之后是以5%为单位来调节的。
<img width="149" alt="75435608-6922-4583-a128-16a21f94733e" src="https://cloud.githubusercontent.com/assets/24986701/21748883/f70cdfe4-d5d3-11e6-8e56-2f1bb728a381.png">

**Comment by lhc70000** [comment]
Already fixed in develop branch. Please wait for next release.

**Comment by APE1980s** [comment]
Thank you!
