### ISSUE TITLE
Cannot read .m3u/.m3u8(playlist file)

### ISSUE THREAD

**Issue by receyuki** [lhc70000/iina#1060]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12 build 40 (only happens in build 40)

**Expected behavior:**

add filelist in m3u to playlist in iina (build 37 is working correctly)

**Actual behavior:**

<img width="532" alt="2017-09-30 10 37 25" src="https://user-images.githubusercontent.com/28808141/31045859-24d5132e-a630-11e7-82e2-09744cde9da3.png">
Error
(错误)<br>
Nothing to open.
(没有可打开的文件。)<br><br>

**Steps to reproduce:**

file→open a .m3u/.m3u8 file
or double click a .m3u/.m3u8 file

**Comment by alejx** [comment]
Fixed in 26d4ca18cf8451911ce3d0394436d64a43dd34cc.

**Comment by JPH78** [comment]
the enclosed .m3u file does not produces a PlayList
in IINA 1.0.0 build 00
Works perfectly in VLC :)))

[Free liste de lecture.m3u.zip](https://github.com/iina/iina/files/2719776/Free.liste.de.lecture.m3u.zip)
<img width="649" alt="error" src="https://user-images.githubusercontent.com/46306207/50578341-2d73cf80-0e39-11e9-964d-924a3d60b0b5.png">

**Comment by JPH78** [comment]
in IINA 1.0.0  build 100...

**Comment by fullflash** [comment]
yes even with lates version m3u playlist files not working.  1.2.0 Build 129
