### ISSUE TITLE
Too hot / high CPU usage

### ISSUE THREAD

**Issue by Yamidaisuki** [lhc70000/iina#107]
RMBP 2015核显，感觉挺烧的

**Comment by lhc70000** [comment]
Duplicate with #51, #65

**Comment by Yamidaisuki** [comment]
发现播放时较为正常，但是一旦视频暂停，就会开始烧

**Comment by lhc70000** [comment]
All discovered problems should have been fixed in v0.0.2.

If similar problem is still persistent, please test the media with mpv to make sure that it's not about mpv and decoding.

---

0.0.2 应该解决了大部分问题，如果发热仍然存在，请先用 mpv 测试相同文件并转移至 #51。

先关闭此 issue。

**Comment by lhc70000** [comment]
0.0.4 _should_ fixed high CPU usage problem. Please test if there's any improvement.

If the problem persists, please reopen this issue.
