### ISSUE TITLE
Tab doesn't work on Open URL dialog

### ISSUE THREAD

**Issue by RyanWangGit** [lhc70000/iina#1071]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**
Tab should be working on Open URL dialog to transfer focus from URL edit box to username/password edit box. 

**Actual behavior:**
Nothing happened when <kbd>tab</kbd> is pressed.

**Steps to reproduce:**
Open up `Open URL` dialog and press <kbd>tab</kbd>.

- [x] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
Fixed in develop branch.
