### ISSUE TITLE
Support mpv's OSC / OSC settings

### ISSUE THREAD

**Issue by IAMJ** [lhc70000/iina#108]
![01](https://cloud.githubusercontent.com/assets/2928760/21749697/dd371070-d5de-11e6-918d-21c119db7388.png)

`seekbarstyle=bar`

**Comment by lhc70000** [comment]
IINA doesn't use mpv's on screen controller, so OSC related options may not work currently.

We'll take a look at it later.

**Comment by lhc70000** [comment]
Added in 0.0.8.
