### ISSUE TITLE
Feature Request: Auto-pause on deselect

### ISSUE THREAD

**Issue by Thearyaskumar** [lhc70000/iina#1080]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**
Often times I swipe away from a video to do something else, then return to it afterwards. It would be nice to have an option in settings to automatically pause when the application is deselected (or not visible on screen), and, if it was paused because of a deselection, automatically resume when visible once again.

An analogy for those with AirPods - When the video is no longer visible, if the setting is enabled it should perform behavior similar to that of removing an aitpod from an ear while watching a video on an iPhone.

**Actual Behavior**
It doesn't do the above

**Comment by alejx** [comment]
Implemented via ac5d35e2160560c3d6786831cb170a6c7c0466b0.
