### ISSUE TITLE
播放视频时卡顿，求教如何解决

### ISSUE THREAD

**Issue by alwaysgoodtime** [lhc70000/iina#1082]
我的系统是版本10.13 mac high sierra，播放视频时会有卡顿现象，想问一下开发者，是什么原因导致的此种情况，电脑的内存不够？还是我没有对播放器进行正确的设置？
另外，iina播放器很漂亮，很好用，谢谢大佬。

**Comment by J-Liu** [comment]
你点击一下电池，确定一下是不是iina耗电很大，然后尝试codecs里面改一下设置。
如果你是黑果，那么，不是无解也不会有人关心的。

**Comment by lhc70000** [comment]
很可能是没有开硬解。如果是 HEVC，硬解支持很快就有；如果不是，请确认你打开了硬件解码（默认打开）。基本上你开了硬解但实际没硬解（这一点可以在 ⌘I 的检查器里看到）的情况，都是因为硬件不支持。

**Comment by sukai-cheng** [comment]
我也是有这个问题

**Comment by sukai-cheng** [comment]
8K 60bps播放卡顿
