### ISSUE TITLE
Subtitles stopped rendering on v0.0.12

### ISSUE THREAD

**Issue by darkscarf1234** [lhc70000/iina#1083]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**

Showing subtitles when selected. v0.0.12 stopped showing subtitles on one of my macs

**Actual behavior:**

IINA v0.0.12 stopped showing subtitles on one of my Macbook Pros. Neither the embedded, nor the external subtitles show on the screen. v0.0.12 works well and shows subtitles on another macbook pro (late 2009 - el capitan) Logs seem not to have any info on why they are not rendering

Is there anyway this can be fixed or at least the source of the problem traced?

Thanks,
darkscarf1234

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Does the solution in #757 work?

**Comment by darkscarf1234** [comment]
Removing the files in the watch_later folder did the trick, thanks for the lightning fas answer!
