### ISSUE TITLE
If it is a full screen, press enter and put the recovery function like pressing esc

### ISSUE THREAD

**Issue by snz2** [lhc70000/iina#1084]
- macOS 10.13
- IINA 0.0.12

If it is a full screen, press enter and put the recovery function like pressing esc.
thanks:)

**Comment by lhc70000** [comment]
You can set it manually: 

Duplicate the default configuration and change it to "Cycle fullscreeen"

![71b428cb-db57-41f4-a4f7-cbed7f3d4e53](https://user-images.githubusercontent.com/8478049/31670481-499fd9de-b38a-11e7-9d39-9f9b1f17231e.png)
