### ISSUE TITLE
macOS 10.13 High Sierra Verifying issue

### ISSUE THREAD

**Issue by kxxc** [lhc70000/iina#1086]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

The large files(1gb up), got the issue that have to Verifying every time when open the videos.

see also here
[https://forums.macrumors.com/threads/“verifying”-upon-opening-every-file.2065395/](https://forums.macrumors.com/threads/“verifying”-upon-opening-every-file.2065395/)

**Comment by herozhang** [comment]
same issue

**Comment by shengyang998** [comment]
Same issue if you use mpv.app downloaded from here: [OS X builds by stolendata](https://mpv.io/installation/).
My currently workaround is to use shell command `mpv [path_to_file]` to open.

**Comment by moon0326** [comment]
This fixed it for me. Run the following command and reboot.

```
defaults write com.apple.LaunchServices LSQuarantine -bool NO
```

**Comment by TempSpas** [comment]
That command turns off the quarantine entirely though, does it not? That isn't a solution the problem so much as a band-aid that compromises on security. Are we pretty much at Apple's mercy here to fix this issue?

**Comment by HarukaMa** [comment]
@TempSpas I think the last statement is true as this behavior is not controllable by applications and all other players suffer from this as well. It seems that file association is broken system-wide at the moment.

**Comment by shengyang998** [comment]
In addition, run `sudo xattr -rd com.apple.quarantine *` in the user directory solved the problem permanently here. So don't need to change the system-wide service setting. 

thanks to @AirPort [here](https://github.com/mpv-player/mpv/issues/4966#issuecomment-334993519)

**Comment by smokybroom** [comment]
Im having the same issue on 15.4, and I dont really want to run sudo xattr -rd com.apple.quarantine *. Surely there is a fix to this now?
