### ISSUE TITLE
IINA should not redefine system wide shortcuts eg Cmd-C

### ISSUE THREAD

**Issue by juanalexei** [lhc70000/iina#1087]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**
Cmd-C should copy or do nothing, redefining widely accepted shortcuts is discouraged by Apple:

https://developer.apple.com/macos/human-interface-guidelines/user-interaction/keyboard/

In general, don’t override standard keyboard shortcuts. Users shouldn’t become confused because the shortcuts they know work differently in your app. Only in very rare cases does it make sense to redefine a common shortcut. For example, if people spend a significant amount of time in your app, it might make sense to redefine a standard shortcut that isn’t applicable to your app. Another option might be to let the user choose their own keyboard shortcuts.

**Actual behavior:**
Cmd-C opens the chapter view
Cmd-S opens the control panel
Cmd-P opens the playlist panel instead of the print panel
Cmd-A opens the control panel instead of selecting all playlist items

**Comment by lhc70000** [comment]
1. Edit menu makes little sense in this specific App, where all operations are focused on video playback. If ⌘C can be interpreted as "copy current frame as image", which is still not intuitive at all IMHO, how about ⌘A or ⌘V?
2. According to HIG, all ⌘- commands are reserved as common shortcuts. If we try to stick strictly with it, which I think is unwise, we can only define key shortcuts with Control or Option modified.
3. In IINA, shortcuts related to text editing, such as ⌘C, ⌘V, ⌘A and ⌘Z are available in almost all input fields. Not for editable tables yet, but we're going to add support for them as soon as possible.

**Comment by juanalexei** [comment]
If the copy paste shortcuts work for text entries and tables (playlist editing), it should not do something else completely different in the rest of the app.

Apple is ambiguous about what is a 'Standard keyboard shortcut', I do agree. But IINA should not redefine the usage of at least the most common ones.

My personal experience as a new user of IINA is that the shortcuts are misleading.

**Comment by alejx** [comment]
Edit menu is needed so that we can copy or paste in the preferences window.

**Comment by alejx** [comment]
Fixed via 9c6b896.
