### ISSUE TITLE
I hope that SWF file would be supported in the future!~~

### ISSUE THREAD

**Issue by ForDre** [lhc70000/iina#1089]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
IINA uses mpv for playing videos, so it'll have to be supported by mpv before we can add support for this.

**Comment by ForDre** [comment]
thanks!

**Comment by lhc70000** [comment]
SWF files are not strictly videos. I don't think mpv are going to add serious support for it, so my suggestion would be converting your swf files to other formats.
