### ISSUE TITLE
Will there be a version for Linux users?

### ISSUE THREAD

**Issue by JulianLai** [lhc70000/iina#109]

**Comment by skmlcd** [comment]
Why tough? This program is specifically written for MacOS. On Linux we already have lots of very similar programs like: Baka-mplayer, bomi, GNOME MPV, SMPlayer...

**Comment by lhc70000** [comment]
No. IINA is written in Swift and for macOS only. If we were going to support Linux, it won't be another _version_ but another _project_.

**Comment by JulianLai** [comment]
@skmlcd Some of them are useless, I'd rather use the default MPV GUI, some of them are out of date.

**Comment by OvermindDL1** [comment]
I'm curious what the Swift issue is?  Swift works fine on linux (I'm running a swift program right now actually)...  Is the language really insufficient for multiplatform programming even though it runs on multiple platforms?

**Comment by HarukaMa** [comment]
@OvermindDL1 It's the UI part that effectively preventing that.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 It's the UI part that effectively preventing that.

Are they using a proprietary API instead of Qt or something of that form?  If so then what does the proprietary API gain over Qt for the usages of the program or that of which cannot be easily switched on based on the platform?

**Comment by inflation** [comment]
@OvermindDL1 you are welcome to start a Qt frontend for mpv and I'm gladly to contribute. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OvermindDL1** [comment]
@inflation Don't really have the time for it 'at the moment', but I'm curious, I generally use VLC (either itself or some GUI on top of it, or via cli to stream to a chromecast) as my player, havn't really used mpv, how do those two backends compare?

**Comment by HarukaMa** [comment]
@OvermindDL1 This topic should not be discussed here as this is the *issue tracker* for IINA. Please find another place to do that/
