### ISSUE TITLE
How to set default volume?

### ISSUE THREAD

**Issue by mosinite** [lhc70000/iina#1093]
Every time I open iina, the volume stays at 55, where can I change this setting?

**System and IINA version:**

- macOS 10.13
- IINA 0.0.12 build 37

**Comment by JohnClay** [comment]
Enable advanced settings, and add name "volume" with value at whatever you'd like the volume to be set at (i.e. 80, 90, etc).

**Comment by mosinite** [comment]
@JohnClay Thank you!

**Comment by lhc70000** [comment]
Added in 0.0.13.
