### ISSUE TITLE
Can I get a setting opinion of default window position?

### ISSUE THREAD

**Issue by J-Liu** [lhc70000/iina#1095]
I wanna make IINA window at the upper left corner by default.

**Comment by lhc70000** [comment]
Please refer to #760.

**Comment by J-Liu** [comment]
<img width="176" alt="screen shot 2017-10-16 at 6 36 52 am" src="https://user-images.githubusercontent.com/1065112/31590019-71286a06-b23c-11e7-83f9-2cf396b78ce2.png">
The window will be the lower left corner, is there anything wrong?

**Comment by lhc70000** [comment]
The screen coordinate starts from left bottom corner. Please use `0:100%` for your case.

**Comment by J-Liu** [comment]
Thx, it is all right now.
