### ISSUE TITLE
Play remote video via URL from command line by calling IINA executable

### ISSUE THREAD

**Issue by JayBrown** [lhc70000/iina#1097]
**System and IINA version:**

- macOS 10.11.6 (meant for all supported macOS versions)
- IINA 0.0.12

**Expected behavior:**
Feature request: launch IINA & play a remote video via URL from the command line, e.g. with

`/Applications/IINA.app/Contents/MacOS/IINA "https://www.youtube.com/watch?v=<YouTubeVideoID>"`

incl. link-shortened URLs like

`/Applications/IINA.app/Contents/MacOS/IINA "https://youtu.be/<YouTubeVideoID>"`

This actually works with VLC & mpv.

- [x] MPV does not have this problem.

**Comment by AllanLRH** [comment]
Related, albeit not exactly the same: I believe that MPV takes a `--playlist=<playlist>` argument, and it would be nice if IINA could do the same. Ideally the playlist could also contain URLS, and could be a plain text file, like this:

```
https://www.youtube.com/watch?v=GePTPzN_Nzs
https://www.youtube.com/watch?v=lYLyM4yKofk
https://www.youtube.com/watch?v=RME_ura87io&t=369s
https://www.youtube.com/watch?v=jdgg0uDhrOs
https://www.youtube.com/watch?v=E8ebTX-npDc&t=18s

```

**Comment by Jarvvski** [comment]
Yes this would be nice!

**Comment by lhc70000** [comment]
IINA ships with a bundled CLI since 0.0.15:

https://github.com/lhc70000/iina/releases/tag/v0.0.15

**Comment by Jarvvski** [comment]
Shouldn’t it be on the website though for easy access?

**Comment by lhc70000** [comment]
Yes, it should be. I'm working on a new website for 1.0 release and will add proper instructions in it.

**Comment by AllanLRH** [comment]
Would be nice if `iina-cli --help` would list the mpv-options, seeing as they are almost the only ones supported? At least, that seems to be the case on my computer:

```
(py36) ❯ /Applications/IINA.app/Contents/MacOS/iina-cli --help
Usage: iina-cli [arguments] [files] [-- mpv_option [...]]

Arguments:
--mpv-*:
        All mpv options are supported here, except those starting with "--no-".
        Example: --mpv-volume=20 --mpv-resume-playback=no
--separate-windows | -w:
        Open all files in separate windows.
--help | -h:
        Print this message.

MPV Option:
Raw mpv options without --mpv- prefix. All mpv options are supported here.
Example: --volume=20 --no-resume-playback

You may also pipe to stdin directly.
```

**Comment by lhc70000** [comment]
@AllanLRH There're too many of them. Please check out their [documentation](https://mpv.io/manual/stable/#options).

**Comment by AllanLRH** [comment]
At first I thought "how bad can it be?"… very bad apparently, that documentation page is humongous! I can see why it would be a bad idea including them in the `--help`-call, but I think that it would be a good idea if the `--help`-call included a link to the documentation similar to this:

```
Due to the massive amount of options offered though the MVP interface, they aren't included in this message, but can be viewed here: https://mpv.io/manual/stable/#options
```

**Comment by AllanLRH** [comment]
Thanks for the tip, but it doesn't seem to work on my machine... how do you open the playlist?

This is my playlist, saved as _playlist.m3u_:
```
#EXTM3U
#EXTINF:0,Channel 1
https://www.youtube.com/watch?v=rZlshXJydgQ
#EXTINF:0,Channel 2
https://www.youtube.com/watch?v=wE2-jepEZ7k
#EXTINF:0,Channel 3
https://www.youtube.com/watch?v=j41vVlwFJrE
#EXTINF:0,Channel 4
https://www.youtube.com/watch?v=ZRIPqa9asrU
#EXTINF:0,Channel 5
https://www.youtube.com/watch?v=E1nx4ReTgps
```

**Comment by pugson** [comment]
@AllanLRH By pointing to the _playlist.m3u_ file. Looks like I can't open your playlist either. However, I am able to open a playlist with different videos:

```
#EXTM3U
#EXTINF:0,Channel 1
https://www.youtube.com/watch?v=k0MPgKG8oh4
#EXTINF:0,Channel 2
https://www.youtube.com/watch?v=qzj4gHuH2LA
```

Here's my IINA version just in case:
![pixelsnap 2018-05-23 at 3 48 57 pm](https://user-images.githubusercontent.com/6843656/40428582-e630353e-5ea0-11e8-9c73-b2e0d41727f5.png)

**Comment by samundra** [comment]
Those who have landed here so far. 

We can also use `youtube-dl` to stream and pipe `stdin` and play in `iina`. 

sample usage:

```
youtube-dl https://www.youtube.com/watch?v=HgtRAbE1nBM -o - | iina --stdin
```

## Explanation

- `youtube-dl -o {url} -` : streams video into stdin that can be piped to iina
- `iina --stdin`
  - tells iina cli that we are going to pipe video streams.
  - rest will be taken care by iina 

## Versions in use

Youtube-dl version: 2019.05.20
IINA version: 1.0.2 Build 105, mpv 0.29.1

**Comment by iexa** [comment]
or `open -a iina --args [youtube-url]` from any command line without any cli or youtube-dl install. works fine.

**Comment by colanfab** [comment]
Using Safari why if I use iina://"my video.mp4" the app starts but video won't start ?
Is there a way to pass the file path ?

**Comment by temberature** [comment]
> Using Safari why if I use iina://"my video.mp4" the app starts but video won't start ? Is there a way to pass the file path ?

iina://weblink?url={encoed url}
seems just support online video.
