### ISSUE TITLE
'MASPreferences/MASPreferencesViewController.h' file not found

### ISSUE THREAD

**Issue by textproofreading** [lhc70000/iina#11]
hi, all

When I begin compile the project under xcode 8 , it shows below error messages:

/Users/xxxx/programming/swift3/iina/iina/iina-Bridging-Header.h:6:9: error: 'MASPreferences/MASPreferencesViewController.h' file not found
#import <MASPreferences/MASPreferencesViewController.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/xxxx/programming/swift3/iina/iina/iina-Bridging-Header.h'

How can I fix this ?

thanks

**Comment by lhc70000** [comment]
Hi, did you have cocoapods installed and run `pod install` before building?

Also, please open the `.xcworkspace` project instead of the `xcodeproj` file.

**Comment by halfelf** [comment]
Face this error too. And open `.xcworkspace` indeed solves this.
