### ISSUE TITLE
Can not choose external subtitle when iina "float on top"

### ISSUE THREAD

**Issue by ApolloZhu** [lhc70000/iina#1104]
**System and IINA version:**

- macOS 10.13.1 Beta (17B35a)
- IINA 0.0.12 Build 37

**Expected behavior:**

Can choose a subtitle file through `NSOpenPanel` even if the window level for *iina* is `.iinaFloating`

**Actual behavior:**

The NSOpenPanel gets hidden behind *iina*.

**Steps to reproduce:**

1. Video > Float on Top
2. Subtitles > Load External Subtitle...

**How often does this happen?**

Always

**Comment by lhc70000** [comment]
Thanks, fixed in develop branch.
