### ISSUE TITLE
ESC does not exit legacy full screen

### ISSUE THREAD

**Issue by JohnClay** [lhc70000/iina#1107]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.13

**Expected behavior:**
When set as a keyboard shortcut, ESC should be able to exit legacy full screen

**Actual behavior:**
When set as a keyboard shortcut, you cannot exit legacy full screen by pressing ESC.

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
It's a known issue, seems like a system constrain so we need to do more research.

**Comment by alejx** [comment]
Duplicate of #1107.

**Comment by prohtex** [comment]
Seems like this still exists in .15 build 60

**Comment by lhc70000** [comment]
@prohtex build 60 doesn't contain this fix, but the next version will. It'll be released in several days.
