### ISSUE TITLE
Ass subtitle isn't displayed correctly

### ISSUE THREAD

**Issue by xingcoo** [lhc70000/iina#1108]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.13

**Expected behavior:**
[https://imgur.com/a/Vf2SC](https://imgur.com/a/Vf2SC)

**Actual behavior:**
[https://imgur.com/a/r89nI](https://imgur.com/a/r89nI)

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
The screenshot is from The.Big.Bang.Theory.S11E03 1:13 using subtitle [The.Big.Bang.Theory.S11E03.720p.HDTV.X264-DIMENSION.简体&英文.ass](http://www.zimuzu.tv/subtitle/53724)

- [ ] MPV does not have this problem.

**How often does this happen?**
Everytime

**Comment by lhc70000** [comment]
It's rendered by mpv so please open an issue for them: https://github.com/mpv-player/mpv/issues.
