### ISSUE TITLE
Media keys don't work with IINA v0.0.13

### ISSUE THREAD

**Issue by JBey4you** [lhc70000/iina#1110]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.13

**Expected behavior:**

Use media keys (F7, F8, F9) to control IINA to pause and more.

**Actual behavior:**

Nothing happens.

**Steps to reproduce:**

Open a media.
Click on the media keys on the keyboard
Nothing happens

**How often does this happen?**

Always since v0.0.13

**Comment by lhc70000** [comment]
Cannot reproduce. Have you double checked that it's enabled in Preferences > Key bindings?

**Comment by JBey4you** [comment]
Yes. Already tried, nothing happens. I also tried to do a clean install of IINA, the issue remains.

To be sure, I also installed IINA 0.0.12 and with this version the media keys work for me. The problem only exists in 0.0.13.

If that can help, I have a iMac Retina (on macOS High Sierra) and Apple’s Magic Keyboard.

**Comment by JBey4you** [comment]
I tried to uninstall completely IINA, reboot and then reinstall. It looks like it's fixed now. Now sure what was the problem, especially since it worked again with v0.0.12 without reboot.
