### ISSUE TITLE
Does not support apple WWDC videos subtitle

### ISSUE THREAD

**Issue by shaobaili3** [lhc70000/iina#1111]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12 Build 37

If you play streaming or downloaded video from apple WWDC(https://developer.apple.com/videos/play/wwdc2017/402/), the subtitle cannot display correctly, like the screenshot:
<img width="516" alt="screen shot 2017-10-16 at 1 48 27 pm" src="https://user-images.githubusercontent.com/13693801/31593166-ba13e038-b278-11e7-9509-a5ba204150d4.png">

**Comment by lhc70000** [comment]
Duplicate with #391, #518, #644, etc.
