### ISSUE TITLE
The window turns gray in fullscreen

### ISSUE THREAD

**Issue by lyliutwo** [lhc70000/iina#1115]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.13

**Expected behavior:**
The whole window sometimes turns gray in fullscreen. Especially when I touch the progress bar, the window will definitely turn gray. The audio is OK.
If I quit from fullscreen, everything back to normal.

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by hassanshamim** [comment]
I'm seeing this as well - just started occurring with the latest update.

Is there any sane way to downgrade the version temporarily?  I installed with Homebrew.

**Comment by lhc70000** [comment]
@hassanshamim https://dl.iina.io/IINA.v0.0.12-build37.dmg

**Comment by lhc70000** [comment]
Hi @lyliutwo @hassanshamim, Could you please test this build https://drive.google.com/file/d/0B7tEU25gz8nhVExoOEhsM21wb1U?

**Comment by lhc70000** [comment]
Fixed in [0.0.14](https://github.com/lhc70000/iina/releases/tag/v0.0.14).
