### ISSUE TITLE
How can I capture a key binding of `MBTN_RIGHT `

### ISSUE THREAD

**Issue by J-Liu** [lhc70000/iina#1121]
I wanna make `MBTN_RIGHT` ignored, but when I `+` a key binding, it can not capture `two fingers click at the same time`.
May you please tell me how can I make `MBTN_RIGHT` `ignore` instead of `cycle pause`?
I do wanna use a `input.conf` file, thank you.

**Comment by lhc70000** [comment]
It's not controlled by input.conf. Please set it in Preferences > Control instead.
