### ISSUE TITLE
Glitches when playing 4K HEVC

### ISSUE THREAD

**Issue by oskarkrawczyk** [lhc70000/iina#1123]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**

<img width="764" alt="screen shot 2017-10-17 at 22 14 50" src="https://user-images.githubusercontent.com/34213/31687142-b807ae76-b388-11e7-984a-55789b0929b6.png">

**Actual behavior (v0.0.13):**

<img width="842" alt="screen shot 2017-10-17 at 22 03 25" src="https://user-images.githubusercontent.com/34213/31687171-c5e0305e-b388-11e7-8d61-94b079bb7e03.png">

**Video info**

Codec: hevc (HEVC (High Efficiency Video Coding))
Size: 3840×2160

**Comment by lhc70000** [comment]
- How about 0.0.14.1?
- Are you using hardware decoding?
- Please make sure that mpv doesn't have the same issue (with same FFmpeg version).

**Comment by oskarkrawczyk** [comment]
1. Same
2. Disabling Hardware decoding solves the issue
3. 4k MPV?

Do you reckon it's safe to leave hardware decoding off by default?

**Comment by lhc70000** [comment]
Most users won't even touch the pref panel after installation. Hardware decoding provides superior user experience at the most time, so I think it's better to make it enabled by default.

**Comment by oskarkrawczyk** [comment]
Understood. If there's any more info you need me to provide, please let me know.

Also, the specific video I was testing, the filename can be found here: https://pastebin.com/ccqcbhFF

**Comment by HarukaMa** [comment]
It seems that HW decoding would do bad things on high-bitrate videos regardless the format, but I have not tested if they are really related.

Maybe we can try to automatically disable it on videos with high enough bitrate... but this needs multiple tests on different devices.

**Comment by pxia** [comment]
This is a known ffmpeg bug, there is a [mpv bug](https://github.com/mpv-player/mpv/issues/4736) for this.

**Comment by dr1llc4t** [comment]
Apparently it is a bug. I'm also encountered this problem with IINA and MPV

**Comment by HarukaMa** [comment]
Note that this is a generic hwdec bug and is not only appearing on HEVC videos. You can try with some BDMV or other videos with high enough bitrate to test it.

Also, if you can confirm that this issue is also appearing on MPV and/or FFmpeg, then reporting this issue to them would help solve this issue sooner.

**Comment by dr1llc4t** [comment]
In my case, bitrate has nothing to do with this issue.I played a 4K hevc video with 392Mbs bitrate and it worked fine. 

Also, when play a video with this issue, it starts with hardware decoding and begins glitching, a short time later it automatically switched to software decoding and stop glitching.

**Comment by pxia** [comment]
This is a small file for the glitches to show: [hevc_sample_short.mp4.zip](https://github.com/mpv-player/mpv/files/1348695/hevc_sample_short.mp4.zip).

**Comment by tmm1** [comment]
I just fixed this bug on ffmpeg master.
