### ISSUE TITLE
The theme cannot change

### ISSUE THREAD

**Issue by cashlu** [lhc70000/iina#1125]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**
Change the theme to others from default "Dark".

**Actual behavior:**
Change the theme to "Light", then restart the App, the theme will restore to dafault "Dark".

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Cannot reproduce. Does restart/reinstall work?

**Comment by cashlu** [comment]
reinstall the app and the problem was fixed.
