### ISSUE TITLE
switching back to normal mode from Music mode

### ISSUE THREAD

**Issue by alashow** [lhc70000/iina#1126]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Actual behavior:**
When playing a video file, and you switch to music mode, there is no way going back to normal/video mode (it's disabled on menu).

**Expected behavior:**
There should be a way to switch back to normal/video mode.
Users definitely should be able to get back to video mode if it's a video, but what if user doesn't want to use music mode when playing mp3's?

**Steps to reproduce:**
Open a video file.
Enter Music Mode.

**How often does this happen?**
Every time

**Comment by lhc70000** [comment]
@alashow Just ⌘W to close the mini player window.

**Comment by alashow** [comment]
It works. But it isn't very intuitive, is it?

**Comment by BasO** [comment]
I'd like to add to this that it's also unexpected behaviour to have the music continue in 'normal mode' by closing the music mode window. Expected behaviour would be to simply close the window and stop playing (like with video files).
