### ISSUE TITLE
[Regression] Error on opening file with irregular extname

### ISSUE THREAD

**Issue by holymonson** [lhc70000/iina#1129]
**System and IINA version:**

- macOS 10.13.1 Beta (17B25c)
- IINA 0.0.13

**Expected behavior:**

While opening a file named `abc.mp4v`, it raises an error alert _没有可打开的文件。_. If changing the filename to `abc.mp4`, it can be opened successfully.

P.S.: On IINA 0.0.12, `abc.mp4v` can be opened successfully.

**Comment by lhc70000** [comment]
Fixed in 0.0.14.1.
