### ISSUE TITLE
additional MPV options not working

### ISSUE THREAD

**Issue by oferJo** [lhc70000/iina#1134]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**
opening a new video file with the window size limited to 60% of the screen and positioned 10 pixels away from the top and left border of screen

**Actual behavior:**
the video opens at actual size and positioned where it was previously.
![screen shot 2017-10-19 at 0 09 07](https://user-images.githubusercontent.com/17050521/31743056-640e68ac-b462-11e7-9de5-6cb50cf58839.png)

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
- `autofit` is not supported yet.
- Please try restarting IINA.
