### ISSUE TITLE
White line under filename bar

### ISSUE THREAD

**Issue by TopoR** [lhc70000/iina#1135]
Minor issue, but with new update there is white border under pop-up bar with filename. Screenshots attached. Previous version of this bar looks prettier, imo.

**System and IINA version:**
- macOS 10.12.6
- IINA 0.0.14 build 47

![screen shot 2017-10-19 at 01 01 30](https://user-images.githubusercontent.com/4129779/31745098-3ba7ebe2-b46a-11e7-9f47-71d7f343ac4a.png)
![screen shot 2017-10-19 at 01 02 29](https://user-images.githubusercontent.com/4129779/31745099-3bc33168-b46a-11e7-9466-8cecefdb092f.png)

**Comment by JohnClay** [comment]
I don't disagree, but it was an intentional design choice:

https://www.iina.io/release-note/0.0.13.html

**Comment by TopoR** [comment]
Ah, I see. Well, I'm sure I'll get used to it :)
