### ISSUE TITLE
Opening a YouTube video overrides currently opened files

### ISSUE THREAD

**Issue by JohnClay** [lhc70000/iina#1136]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**
When using the browser extension to open a YouTube video, IINA should open the stream in a new window.

**Actual behavior:**
IINA opens the stream within the front-most existing video file, essentially closing it.

**Steps to reproduce:**
- Install browser extension
- Open one or more video files in IINA
- Load video page, click extension and load into IINA

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
This issue has been fixed in #1935.
