### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by NewsGuyTor** [lhc70000/iina#1139]
With the latest Firefox being so much better/faster than Chrome, I think the extension should be added to the Firefox extension store too. 

As far as I could see the extension should be extremely simple to port to Firefox, it can already load without any changes (but installing it requires technical skill IINA shouldn't require).

**Comment by CarlosEvo** [comment]
Actually I think I made it into Firefox using [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) and it works like a charm. I just don't know how to share it, but I think you all can make it.

**Comment by gagarine** [comment]
It's fixed in 1.0.0-RC https://addons.mozilla.org/en-US/firefox/addon/open-in-iina-x/

![screenshot 2018-12-09 at 17 16 14](https://user-images.githubusercontent.com/164074/49699817-2fe65f00-fbd6-11e8-9c92-977a92f7e90a.png)
