### ISSUE TITLE
IINA periodically forgets settings

### ISSUE THREAD

**Issue by Arve** [lhc70000/iina#1140]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14 build 47

**Expected behavior:**

For IINA to correctly retain the following two settings/preferences on restart

* Always float on top while playing
* On Screen Controller: Bottom
* Use left / right button for: Previous/Next media

**Actual behavior:**

IINA periodically forgets the settings from above, instead reverting to the following settings:

* Unchecking float on top
* Resets OSC to floating
* Left right button becomes "Speed"

**Steps to reproduce:**

This started happening with IINA 0.0.13, but only after updating to 10.13 and updating the file system to APFS - it happens seemingly randomly without rhyme or reason, and purging local APFS does not seem to affect it.

- [x] MPV does not have this problem.

**How often does this happen?**

Periodically - it does not happen on every restart of IINA or every day, but beyond that it's hard to say something specific about which frequency this happens with.

**Comment by TempSpas** [comment]
#1049
