### ISSUE TITLE
IINA opens a new window when closing a audio file playback.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#1143]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**
Open a audio file with IINA. IINA starts playing back. Then close the play back window with the "x" button on the top left of the window, IINA stops playing .

**Actual behavior:**
After clicking on the "x" button, a new window pops up, and IINA continues playing.

**Steps to reproduce:**
See the screen recording [here](http://d.pr/v/PgRuVR+).

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
This is closely related to #1126.

**Comment by lhc70000** [comment]
It's intended, but I think we can add an option like "when closed mini player window: switch back to normal mode or stop playback".

**Comment by oscar-c** [comment]
I don't think this makes a lot of sense, to me at least.

Frist, when I open a audio file, the normal play back window shows up only to be replaced by the mini player windows at the next moment. If the normal playback window is never intended to be used for audio files, why flash it out in the first place?

Second, in most users' conceptual model, clicking the "x" button a window means the window should disappear and playback will stop. This is true throuhout most of the video players. The close button of IINA's mini player window fails both expectation.
I don't think it's a good idea to overload the fuction of the close button on a mini player window. If there's need to exit mini player mode, have button dedicated to it. Just don't abuse the close button.

**Comment by lhc70000** [comment]
iTunes has exactly the same behavior though, and I’m used to it. I designed this feature based on my habit and intuition.

**Comment by oscar-c** [comment]
There's a difference, though. For iTunes, user explicitly enters mini player mode. For IINA the mini player is the main playback window.
