### ISSUE TITLE
Continuous fast forward crash

### ISSUE THREAD

**Issue by aTreey** [lhc70000/iina#1145]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by aTreey** [comment]
。。

**Comment by saagarjha** [comment]
I'm going to go out on a limb here and say that you're probably experiencing #1116.

**Comment by lhc70000** [comment]
Closing due to duplication.
