### ISSUE TITLE
Playlist pane obscures on-screen controller when controller is at the bottom

### ISSUE THREAD

**Issue by jeanlain** [lhc70000/iina#1146]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

Reproduce:
Choose to show the on-screen controller at the bottom
Click the playlist button on the controller.
**Expected behavior:**
The controls should remain visible (i.e., the playlist pane should not reach the bottom of the window).

**Actual behavior:**
The playlist pane obscures parts of the controls. In fact, the playlist button is not masked by the trash button so you may empty the playlist instead of closing it (d'oh!).

**Comment by oscar-c** [comment]
Possible duplication with #844

**Comment by jeanlain** [comment]
Ha yes, dup.
