### ISSUE TITLE
0.0.14 no longer plays from .rar files 

### ISSUE THREAD

**Issue by Jimmni** [lhc70000/iina#1149]
When opening a .rar file with IINA, it would always play in the past. Now it says "Nothing to play."

**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.14

**Expected behavior:**

Opening a .rar file will result in the movie playing (if it is possible).

**Actual behavior:**

A pop-up saying "Nothing to play" appears.

**Comment by lhc70000** [comment]
Fixed in 0.0.14.1.
