### ISSUE TITLE
Some preliminary investigation results on crashes happened in 0.0.13/14

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#1150]
- **The crash only occurs on some specific device models.** According to a survey in the Telegram group, 60% of users didn't encounter the crash at all, but the remaining reports that it occurs frequently.
- **It crashed at different function calls in different threads.** All logs contain similar error info, but they locate in **different** threads and positions (main thread, mpv thread, IINA controller queue), even having different exception type.
  - Most crashes are found in `syncUI` and `displayOSD` (MPVController:527-531), so I found some volunteers and sent them test builds of:
    - Adding an extra lock surrounding `syncUI`: Still crash, but _seems to be_ less frequent.
    - Commenting out `syncUI`: Still crash when calling `displayOSD`, _seems to be_ less frequent. However according to the reports, it crashes at `preventSleep`, which is a new and totally unrelated function. Interesting.
    - Commenting out `displayOSD`: Still crash in `syncUI`.
    - Commenting out both `syncUI` and `displayOSD`: No crash observed so far.
  - However, it doesn't explain why there are crashes in mpv core thread.
- **All crash happen in `malloc`,** and are of the same error type "Invalid pointer dequeued from free list".
- **It only occurs in release builds.** Several users with Xcode installed built IINA on their own machine, and found that there's no crash in debug builds. Release builds simply have the same issue.
  - (How about debug builds built on my machine? Need more tests)
- Xcode 9.1 beta: (Still crash, need more tests)

So as far as I can tell, the crash is caused by, or at least related to the compiler; and there even already exists a similar issue in Swift bug reporter: https://bugs.swift.org/browse/SR-5068.

Current plan for the next step:
- Try different build configurations (optimization level)
- Find out a way to reduce occurrence of the crash
- Review related code for possible memory management issues

Helps are needed and welcomed.

**Comment by lhc70000** [comment]
Update: disabling Swift whole module optimization does the trick.

@saagarjha Should we file a radar or report it to Swift?

**Comment by saagarjha** [comment]
I'm of the feeling that we're relying on undefined behavior that the compiler is changing between compilation modes. Could you try a build with Address Sanitizer, Undefined Behavior Sanitizer, and malloc scribble turned on?

**Comment by lhc70000** [comment]
@saagarjha Seems that it always crashes at [this line](https://github.com/lhc70000/iina/commit/ea3164cbec785c903390764a2cacc3b1800809fb#diff-bf2d0064b899cc359affec4330165bf4L937), saying "deallocating freed memory". This commit fixed the crash reportedly, but I still think it should be an compiler issue, as we did nothing wrong here.

**Comment by saagarjha** [comment]
`didSet` is not called in an initializer, but I don't see why we need a new method for sanity checking the time.

**Comment by lhc70000** [comment]
`info.videoPosition?.second = time` won't call `didSet` every time so we need to call it explicitly. Is there a better solution?

Actually what I concern the most is, is there any problem with `info.videoPosition = VideoTime(time)`? If not, maybe we need to report it to Swift.
