### ISSUE TITLE
Can't switch to app in secondary display while full screen mode

### ISSUE THREAD

**Issue by pighair** [lhc70000/iina#1151]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14 Build 47

**Expected behavior:**

Selected app appears when I change app by pressing Cmd+Tab while IINA is in full screen mode.

**Actual behavior:**

Nothing happens when I choose other app only in secondary display by pressing Cmd+Tab, if I turn on "Black out other monitors while in full screen" option. I can see the app switcher but selected app does not have focus or visibility.

**Steps to reproduce:**

1. Prepare multiple displays.
2. Put some app other than IINA in secondary display. Be sure that the app does not have any window in primary display.
3. Turn on "Black out other monitors while in full screen" option in IINA preference.
4. Play any video in primary dispay.
5. Change to the app in secondary display by pressing Cmd+Tab.
6. You can see that IINA still blacks out the app.

**How often does this happen?**

Always.

**Comment by lhc70000** [comment]
Fixed in 0.0.14.1.
