### ISSUE TITLE
Secondary display keeps blacked out after quitting full screen mode

### ISSUE THREAD

**Issue by pighair** [lhc70000/iina#1152]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14 build 47

**Expected behavior:**

Secondary display gets back from blacked out when I quit full screen mode of IINA by pressing ESC.

**Actual behavior:**

Secondary display keeps blacked out after quitting full screen mode until I exit IINA. Closing video window does not end black out.

**Steps to reproduce:**

1. Turn on "Black out other monitors while in full screen" option in preference.
2. Play any video.
3. Get into full screen mode. Secondary display blacks out.
4. Quit full screen mode by pressing ESC.
5. Secondary display does not quit black-out status.

**How often does this happen?**

Always.

**Comment by alejx** [comment]
We didn't change anything from last release, so I kind of suspect swift 4 changed some of its ,mechanism that I didn't notice. And maybe your previous issue (#1151) is also related to this. I'm trying to fix it.

**Comment by lhc70000** [comment]
Fixed in 0.0.14.1.
