### ISSUE TITLE
v0.0.14 keeps crashing on macOS 10.13 if forward/rewind too quickly.

### ISSUE THREAD

**Issue by ugoa** [lhc70000/iina#1154]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

I just upgraded IINA from version 12 to latest 14 on High Sierra, but it keeps crashing when I forward/rewind too much or too quickly. the attachment is the problem report. Thanks.

**Steps to reproduce:**
Open a mkv file
move forward/backward quickly.
[iina.log](https://github.com/lhc70000/iina/files/1404726/iina.log)

**How often does this happen?**
Everytime

**Comment by shengdie** [comment]
same problem.

**Comment by TempSpas** [comment]
#1116, #1150

**Comment by lhc70000** [comment]
Closing due to duplication.
