### ISSUE TITLE
[Feature request] force touch in forward/rewind buttons.

### ISSUE THREAD

**Issue by xjkdev** [lhc70000/iina#1155]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14

**Expected behavior:**
If I choose the forward/rewind function for left/right buttons, I will lost force touch in left/right buttons. Can I combine force touch with forward/rewind function on left/right buttons? By the way, in quicktime player, force touch left/right will be quick rewind and quick forword, instead of speed changing.
Thank you for developing this wonderful program.

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

**How often does this happen?**

**Comment by incrediblejustin** [comment]
i got the same problem too

**Comment by lhc70000** [comment]
Rewinding (reverse playback) is not supported by mpv, so basically there's no possible solution. Sorry for that.

**Comment by xjkdev** [comment]
Can we make force touching  on left/right be the same like two finger moving left/right in touchpad? It's not fast rewind or forward. Forgive me for i may not express it in english.
能不能让force touch前进、后退的效果像是双指在触摸板上移动一样？那样不是快进和快退，而是高频率的前进、后退这样的。 @lhc70000
