### ISSUE TITLE
Setting going back to default

### ISSUE THREAD

**Issue by kxxc** [lhc70000/iina#1162]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14 build 47

**Expected behavior:**

**Actual behavior:**

Setting going back to default

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
several times

**Comment by TempSpas** [comment]
#1049

**Comment by kxxc** [comment]
@TempSpas thanks, so 0.012 and 0.014 both got this issue

**Comment by lhc70000** [comment]
Closing due to duplication.
