### ISSUE TITLE
A Little stuck when jumping forward and backward. 

### ISSUE THREAD

**Issue by shengyang998** [lhc70000/iina#1163]
**System and IINA version:**
- macOS 10.13
- IINA 0.0.14(build 47)

**Expected behavior:**
When you hold on the key `.` or `,`, the video should play forward or backward smoothly (as mpv did). 
When you hit `→` or `←` the video should jump forward or backward very quickly (as mpv did), but not now in IINA. 

**Actual behavior:**
You can test it by yourself by holding `.` or `,` or hitting  `→` or `←` and compare it with MPV, it seems a little stuck in IINA when using `,` `.` `→` or `←`.
Well actually, I can't be sure if it is a feature or a bug. But if it's a feature, it makes no sense for me. 

**key binding**
![2017-10-24 09 34 02](https://user-images.githubusercontent.com/4907178/31921024-6bbb80d0-b89f-11e7-948e-f0d6ad16e705.png)
![2017-10-24 09 34 36](https://user-images.githubusercontent.com/4907178/31921025-6bef62d8-b89f-11e7-99f8-a63c664fa53e.png)

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
Reverted the default key binding for arrow keys to keyframe seek in 0.0.14.1. Please check for updates.

For `,` and `.` keys, they are actually "prev/next frame **and pause**", which is the only command mpv provides, and should behave the same as mpv. So I'm not sure if mpv could really play the video "forward or backward smoothly" while holding these keys, as it will definitely pause the video on every press.

**Comment by shengyang998** [comment]
Thanks, @lhc70000 
As to `,` and `.`, well, if you hold down `,` or `.` in mpv, you'll see. 
Anyway, I hope this feature could be added, for a better user experience. 
I don't know if I can help 😅
