### ISSUE TITLE
Disabled Apple Remote support?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [lhc70000/iina#1166]
_WHY?_

I can't be the only one who still uses one to control video players from my couch.

I checked the prefs and the option to use Apple Remote is **still there.**

Even with the option unchecked many functions of IINA are still controlled by Apple Remote.
The only difference seems to be what happens when you press the big center button and the black buttons on the left/right sides of it.

**With the option unabled:**
The center button does nothing.
The buttons above/below it control volume up/down.
The bottom right button controls pause/play AND opens iTunes (even though iTunes is **not** paired with any remotes).

**With the option enabled:**
The center button pauses/plays and the side buttons are back/forward.
The buttons above/below it control volume up/down.
The bottom right button ALSO controls pause/play, making it redundant.

- OS X 10.12.6
- IINA 0.0.14.1

**Comment by lhc70000** [comment]
> WHY?

It improves stability. We've found some crashes related to it.

I just disabled it **by default**. Please enable it again if you need, and it will function exactly the same as before.
