### ISSUE TITLE
Incompatible with Moom?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [lhc70000/iina#1167]
I use Moom to quickly and easily maximize windows from the green button.
When I hover over the green maximize button on a window, a tiny menu appears which offers options for changing the size to fullscreen, or making it **half-size** on the left, right, top or bottom of the screen.

But when I use it on IINA, the player only resizes to the "Fit to Screen" (⌘+3) option.
So I'm still forced to use shortcuts (pardon me - _keybindings_) to make the player fullscreen.

IINA doesn't respond as it should to Moom's other commands either:
The left-side option resizes IINA to the top-left _quarter_ of the screen.
The right-side option resizes IINA to the top-right _quarter_ of the screen.
The top-half option resizes IINA to a bit larger than the top-left _quarter_ of the screen.
The bottom-half option resizes IINA to a bit larger than the bottom-left _quarter_ of the screen.

- OS X 10.12.6
- IINA 0.0.14.1
- Moom 3.2.9

**Comment by inflation** [comment]
I have Moom and just tried it. IINA will maintain the video respect ratio, so it depends on the video content. QuickTime has the same behavior.

**Comment by GitTheHellOutaHere** [comment]
_You're right._

It does function like QT (which I never use).

Perhaps I never noticed it with VLC because I'm so used to using ⌘+F that I may not have even tried using Moom.

Using Moom, VLC _does_ arrange the windows differently using the top-half and bottom-half options than QT/IINA does, but that's not important..

I tried comparing Elmedia Player but Moom doesn't activate at all for it.

Thanks for testing it and your reply.

**Comment by inflation** [comment]
Close due to inactivity.
