### ISSUE TITLE
Aspect ratio change option does not support portrait videos.

### ISSUE THREAD

**Issue by pighair** [lhc70000/iina#1169]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

Video's aspect ratio changes to 3:4, 4:5, 9:16, 10:16 and etc for portrait mode video.

**Actual behavior:**

Video's aspect ratio changes to 4:3, 5:4, 16:9, 16:10 and etc for portrait mode video and it results squeezed video playback.

**Steps to reproduce:**

1. Play some video of which width is smaller than height.
2. Change aspect ratio using menu or default keyboard shortcut ⇧A.

**How often does this happen?**

Always.

**Comment by lhc70000** [comment]
What if I really want 4:3 rather than 3:4?

IINA allows you inputting any arbitrary aspect ratio in the side bar, BTW.

**Comment by pighair** [comment]
I didn't know the arbitrary aspect ratio. It seems to be able to resolve various situation. Thanks for the info.
