### ISSUE TITLE
Legacy Full Screen with IINA frontmost application makes the dock and menubar disappear on the other monitor..

### ISSUE THREAD

**Issue by whirk** [lhc70000/iina#1170]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

thanks for adding Legacy Full Screen support! I don't know if this is a bug but when IINA is in Legacy Full Screen Mode and is the frontmost application the Dock and Menubar on the other monitor disappear.. 

in my opinion at least it would be nice if nothing changes on the 2nd monitor when IINA is the frontmost application.

**Comment by lhc70000** [comment]
Related to #1106.

Does any other app with legacy full screen, for example VLC, has the same issue?

**Comment by whirk** [comment]
no. VLC 2.2.6 (the latest version, just downloaded) does not cause anything on the other screen to disappear when it is the frontmost application.
