### ISSUE TITLE
brew cask install iina download failed

### ISSUE THREAD

**Issue by wimvogt** [lhc70000/iina#1173]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

Download failed on Cask 'iina' with message: Download failed: https://dl-portal.iina.io/IINA.v0.0.14-build47.dmg

**Comment by lhc70000** [comment]
It redirects to http://mirrors.tuna.tsinghua.edu.cn for China IP addresses. Please make sure you have access to TUNA's mirror, or running the command with a non-China IP.

See https://lhc70000.github.io/iina/zh-cn/ for other download options.
