### ISSUE TITLE
播放720p mp4文件有卡顿现象

### ISSUE THREAD

**Issue by ydoupo** [lhc70000/iina#1174]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Please fill the template and provide more details. Thank you.
