### ISSUE TITLE
IINA not play video from WebTorrent Desktop client

### ISSUE THREAD

**Issue by KPOCAB4EG** [lhc70000/iina#1176]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

Playing video after click on Play buttom in [WebTorrent Desktop](https://webtorrent.io/) client

**Actual behavior:**

IINA say "Can not open file or stream" (translate from Russian - "Не удается открыть файл или поток"). _In VLC all working fine_. And _working fine in IINA when play file from Finder_ (file not full loaded, ~1-3%)

Here is the process video https://vimeo.com/239928688

**Steps to reproduce:**

1. Start loading torrent file (with a video file) in [WebTorrent Desktop](https://webtorrent.io/) client
2. After 1%+ loaded click Play buttom and click to video player name (IINA; change in setting WebTorrent)

**How often does this happen?**

Always

**Comment by inflation** [comment]
If you just open the half downloaded file it would play smoothly. The issue is WebTorrent Desktop doesn't provide correct URL, you could report the issue to them.

**Comment by KPOCAB4EG** [comment]
In IINA **0.0.15** all work fine, big thanks!
