### ISSUE TITLE
Opening new file resizes currently open video windows

### ISSUE THREAD

**Issue by TempSpas** [lhc70000/iina#1178]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

When opening a new video file, current video windows should remain unaffected.

**Actual behavior:**

Often when opening a new file while other files are currently open, the windows of the open files will resize themselves, shrinking themselves down.

**Steps to reproduce:**

1. Open a video file.
2. Press Command-3 to fit the file to the screen.
3. Open a new video file.
4. Observe that the first file has shrunk itself down and no longer fits to the screen.

**How often does this happen?**

More often than not.

**Comment by alexandre-zia-movile** [comment]
This is the most annoying thing I've ever seen in a media player, it would be just awesome if it does not resize the window, just fit the new video in the already existent window size.

**Comment by TempSpas** [comment]
I've observed that this issue is back in 0.0.15 Build 64.
