### ISSUE TITLE
SVP compatibility

### ISSUE THREAD

**Issue by asoksevil** [lhc70000/iina#118]
Is it compatible? http://www.svp-team.com

**Comment by lhc70000** [comment]
We are busily fixing bugs these days, but will have a check later.

**Comment by HarukaMa** [comment]
Preliminary tests show that this is theoretically possible, but we still have some blocking issues which prevent it from working now. Stay tuned.

**Comment by asoksevil** [comment]
Thanks! Appreciate the effort!

**Comment by asoksevil** [comment]
Any updates on this? How to do you install it?

**Comment by HarukaMa** [comment]
@asoksevil See [the wiki page](https://github.com/lhc70000/iina/wiki/Use-SVP-with-IINA) for the instructions.

**Comment by asoksevil** [comment]
@HarukaMa Thank you, awesome news!

**Comment by asoksevil** [comment]
@HarukaMa I have recently gotten a new MacBook Pro 2017 and just followed all the steps on the wiki page but it doesn't seem to work. Whenever I open a video file with IINA directly (double click to open) it won't pop up SVP OSD saying that it has been activated, I need to right click and click on open with SVP, which in turn it opens MPV and I can see that Hardware Monitor from SVP is showing  a number on SVP Index, otherwise with IINA is NA.

It is also very obvious to see whether SVP is running because on mpv the CPU usage is quite high, the SVP index shows as 1-2 while on IINA, the CPU usage is low and there's no SVP Index.

Do you know what could be happening?

Thanks!

**Comment by lhc70000** [comment]
@HarukaMa Any update?

**Comment by asoksevil** [comment]
What's the latest on this for 2022? Can we just follow this guide? https://www.svp-team.com/wiki/SVP:IINA

**Comment by asoksevil** [comment]
@HarukaMa @lhc70000

**Comment by abadire** [comment]
The guide above doesn't work for me:(

**Comment by asoksevil** [comment]
@HarukaMa @lhc70000 

Thanks!
