### ISSUE TITLE
Could not load the `srt` file under the same folder with the same name 

### ISSUE THREAD

**Issue by Songhuitang** [lhc70000/iina#1182]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**
`Load the srt file automatically with the same name.`

**Actual behavior:**

`Even though, I can see the subtitle from  the right side bar, but just could not see them on the video screen. The same as online search function --> After clicking the online search button, I could see a lot of the SRT file in the list, but just could not load them into the screen after selected them.`

```
Note: The `ASS` file is working.
```

**How often does this happen?**
All the srt file even including the online search srt file.

Appreciate it if you can fix this soon.

辛苦了，伙计们。

**Comment by Songhuitang** [comment]
```
Somehow I changed the config to load subtitle using `Auto` instead of `UTF-8`.

Now it's working.
```

- Now I have another quick question that how could I find the audio & video information detail? (Like the `TAB` keys function for *PotPlayer* in Windows )🤣

- Do we have the feature that the audio with specified keyword like `CHS`,`ENG` keeps high priorities to be loaded?

**Comment by lhc70000** [comment]
> Now I have another quick question that how could I find the audio & video information detail?

⌘I

> Do we have the feature that the audio with specified keyword like CHS,ENG keeps high priorities to be loaded?

No for now.
