### ISSUE TITLE
可以用IINA看斗鱼的直播吗，我用优酷可以的，但是斗鱼不行。该如何设置呢

### ISSUE THREAD

**Issue by zhjlty** [lhc70000/iina#1183]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by HarukaMa** [comment]
Duplicate of #1147.
