### ISSUE TITLE
IINA 0.0.14.1 - forgets all settings after restart

### ISSUE THREAD

**Issue by sofaelite** [lhc70000/iina#1184]
Latest IINA 0.0.14.1, still forgets all its settings after a restart

- macOS 10.13 (High Sierra APFS File System)
- IINA 0.0.14.1

this also happens on my other system which runs 10.13.1 (newest Public Beta5)

**How often does this happen?**

always after restart, all settings are back to default (music mode, history etc.)

**Comment by TempSpas** [comment]
#1049
