### ISSUE TITLE
Should IINA go into production?

### ISSUE THREAD

**Issue by holymonson** [lhc70000/iina#1185]
Congrats!!
IINA is stable now and becomes many users' default player. Is it the right time to bump version to **v1.0.0**? The last one v0.0.14.1 seems a little odd. see http://semver.org/

**Comment by saagarjha** [comment]
We had an issue with crashes; see #1116. 0.14.1 was a hotfix.

**Comment by holymonson** [comment]
> We had an issue with crashes; see #1116. 0.14.1 was a hotfix.

@saagarjha And you must admit the version is so long that you left out a leading **0**. ^_^
