### ISSUE TITLE
youtube-dl问题- -

### ISSUE THREAD

**Issue by maqiqing** [lhc70000/iina#1187]
英语不好就不用英文了，最近用inna播放器直接播放熊猫tv的直播，貌似只会有1个主播(随机的？)是可以打开url steam流？
不是很懂，我觉得是这个youtube-dl问题= = 不知道怎么设置，douyu貌似也不支持打开url，bilibili是可以的 acfun也是不可以啊。。是我哪里没有设置吗

**Comment by alejx** [comment]
看起来不像是我们的问题. 熊猫 TV 理论上 youtuble-dl 是支持的, acfun 不支持. 可以的话, 发 issue 给上游吧.
