### ISSUE TITLE
Drag URL does not work

### ISSUE THREAD

**Issue by chaoli46** [lhc70000/iina#1189]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.13/0.0.14

**Expected behavior:**

Drag a link to iina, then start steaming

**Actual behavior:**

Drag the link to iina, but it does not started steaming, and it does nothing.

**Steps to reproduce:**

- Select a link (e.g. `http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=gogoucc&prgid=55353101&ref=main&c1=&lot=cate_01_2`) and drag it to iina
- It happens on 0.0.13/14, and 0.0.12 works well.

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by alejx** [comment]
I test on 0.0.12 it shows same result as latest release. The log says

> 2017-11-11 23:03:11.783996-0600 IINA[37039:10307251] MPV log: [ytdl_hook] warn: youtube-dl failed, trying to play URL directly ... 

> 2017-11-11 23:03:12.471506-0600 IINA[37039:10307251] MPV log: [cplayer] error: Failed to recognize file format.

This link may be not recognized by youtube-dl.

**Comment by chaoli46** [comment]
The link have been outadated. Please try `http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=gogoucc&prgid=55325785&categid=33448001&page=10&ref=ch&lot=cthum2_1_2`

This link have the same issue on 0.0.13/14, but works on 0.0.12. I tried the link by youtube-dl. It always works well.

```
$ youtube-dl "http://jp.channel.pandora.tv/channel/video.ptv?ch_userid=gogoucc&prgid=55325785&categid=33448001&page=10&ref=ch&lot=cthum2_1_2"
[pandora.tv] 55325785: Downloading JSON metadata
[pandora.tv] 55325785: Downloading JSON metadata
[pandora.tv] 55325785: Downloading JSON metadata
[pandora.tv] 55325785: Downloading JSON metadata
[download] Destination: abc.flv
[download]   0.4% of 259.19MiB at  1.13MiB/s ETA 03:49
```

**Comment by alejx** [comment]
Do you mean drag the link onto the app icon? I've probably seen the problem.

**Comment by chaoli46** [comment]
Yes, drag the link to the app icon.

**Comment by alejx** [comment]
Thanks for reporting this, I've fixed it on develop branch.
