### ISSUE TITLE
video still skipping

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1192]
iina 0.0.14.1 b55
macos 10.12.6

Video still skips once in a while for certain videos. No clue why. When I change an option in preferences and go back to the video typically it will skip but then continue henceforth. Also I think it reset my video equalizer settings. Does not happen in mpv 0.27 or latest VLC. Also, Just noticed the file is HEVC. 2015 MBP so no hardware support. In any case works fine in mpv/vlc. Thanks.

**Comment by jerkstore369** [comment]
Disabling automatic graphics switching solves this. My display settings are set to "looks like 1920x1200". Lot of things chug unless AGS is disabled. Solved.

**Comment by inflation** [comment]
I'm closing it since it seems to be solved.
