### ISSUE TITLE
when I use iina , the caps Lock isn't working. 

### ISSUE THREAD

**Issue by spitz1jwq** [lhc70000/iina#1193]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
Already fixed on develop branch, will be closed on next release.
