### ISSUE TITLE
快进功能问题

### ISSUE THREAD

**Issue by xhp281** [lhc70000/iina#1194]
app 非常好用，但是快进功能有一点小瑕疵，能不能提供快进1.5  1.6 1.7 1.8 1.9 功能，快进两倍的时候基本是听不清的，没有什么实在意义。

**Comment by xhp281** [comment]
我找到了，如何关闭这个 issue 啊

**Comment by wao1201** [comment]
@xhp281 回复框右下角选择“回复并关闭”

**Comment by xhp281** [comment]
@sophmore8 右下角设置图标点一下就出来了。
