### ISSUE TITLE
Drag and drop subtitle file | 字幕文件拖拽

### ISSUE THREAD

**Issue by trusbe** [lhc70000/iina#12]
希望支持字幕文件拖拽到播放器中。

**Comment by lhc70000** [comment]
看来需求很大，下一版本会添加。

---

Will be added in next version.

**Comment by lhc70000** [comment]
Added by #78.

**Comment by lhc70000** [comment]
Close as fixed in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).

**Comment by JavenLiuu** [comment]
字幕拖拽功能在1.3.3 Build 138 失效，macOS 13.4.

**Comment by ansonhorse** [comment]
我以为一直都不支持呢，原来17年就添加这功能了？
主要是我用这么久，也没发现这功能是正常的。就是拖动srt文件到播放界面，并没有把字幕添加到视频。
系统: macOS 13.5
IINA: 1.3.5 Build 141

Debug级别的日志也没有任何信息。
