### ISSUE TITLE
How to revert to the default settings？

### ISSUE THREAD

**Issue by foisonocean** [lhc70000/iina#1201]

**Comment by foisonocean** [comment]
Can anyone help ?

**Comment by xjbeta** [comment]
Delete this file `~/Library/Preferences/com.colliderli.iina.plist`.

**Comment by foisonocean** [comment]
@xjbeta After delete the config file, the subtitle style settings is still customized.

**Comment by lhc70000** [comment]
If deleting the plist file doesn't work, please try running `defaults delete com.colliderli.iina` in terminal.

**Comment by foisonocean** [comment]
@lhc70000 This works, thanks
