### ISSUE TITLE
Color Banding On Rendered Frames

### ISSUE THREAD

**Issue by sovon** [lhc70000/iina#1204]
**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.14.1

**Expected behavior:**
For high bitrate streams it shouldn't produce colour banding.

**Actual behavior:**
Produces color banding and over saturated colours for all high bitrate UHD remux that we tried. Examples:

![iina5](https://user-images.githubusercontent.com/18725800/32518922-10dc0ca0-c431-11e7-8d3b-8b2ec771784f.jpeg)
<img width="1440" alt="iina6" src="https://user-images.githubusercontent.com/18725800/32518936-19766022-c431-11e7-8079-57ef7071e263.png">
<img width="1440" alt="iina7" src="https://user-images.githubusercontent.com/18725800/32518940-1c509e02-c431-11e7-9c0d-abd2f7c6b7c8.png">

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

Open any UHD Remux available in rutracker (Life of Pi, Logan, Deadpool etc.)

- [x] MPV does not have this problem.
Checked against the latest 0.27.0. Didn't seem to have hw acceleration but still there was no color banding and the colours are right(not over saturated).

**How often does this happen?**
Every time.

**Comment by latelan** [comment]
Is that the same problem ? 
![2551510118154_ pic_hd](https://user-images.githubusercontent.com/4263137/32532692-03f7e454-c487-11e7-994e-53a2faa293ae.jpg)

**Comment by sovonhalder** [comment]
No.

In my images on post above, look at the sky and light beams. There are visible color banding.
However what you posted, this is another thing that I noticed. In fact in Planet Earth II DDR UHD rip, the entire screen fill with colord blobs (artifacts?)  just like the upper portion of your image.

I'll open a separate issue for that.

**Comment by sovon** [comment]
I checked this (Logan UHD remux HEVC) in mpv today. And it's weird. Same problem.

By default with --hwdec=no, it uses 350% cpu for software decode and the image quality is top notch.

But using hardware acceleration with --hwdec=videotoolbox, the cpu rests at around 30% but these same banding is there.

This is the issue with quality degradation with hwdec due to API limitations I suppose, as mentioned in the mpv manual: https://mpv.io/manual/master/#options-hwdec

**Comment by sovon** [comment]
Guys from #mpv and free node told me that this is due to the API restrictions - that VideoToolbox supports 8 bit video and since I'm trying to play a 10 bit stream it causes the color banding and other similar video degradation.
