### ISSUE TITLE
播放在线视频中断

### ISSUE THREAD

**Issue by f2sky** [lhc70000/iina#1205]
- macOS 10.11.6
- IINA 0.0.14.1

播放在线视频，例如优酷视频，基本上一个长视频都只能播放一段，然后显示缓冲中，不能继续播放。

**Comment by inflation** [comment]
有可能与你的网络环境有关，刚刚试了一个3个小时的YouTube视频，没有问题。

**Comment by f2sky** [comment]
我又重新尝试了播放，不管是直接复制链接用功能菜单中的“打开URL…”打开，还是安装 chrome 浏览器插件，不管是优酷视频还是 YouTube 视频，都报错“无法打开文件或流”。

之前还能播一小段优酷视频的，现在一点都不能播了，不知道什么原因……

可以从哪些方面进行排查呢？

**Comment by inflation** [comment]
建议直接通过`youtube-dl`命令下载你的链接，看看log。

**Comment by lhc70000** [comment]
如果有更新信息，请 reopen。
