### ISSUE TITLE
video seek when hovering on timeline bar

### ISSUE THREAD

**Issue by SchwiftyLife** [lhc70000/iina#121]
hi @lhc70000 
it would be very useful to have the option to seek trough video with hovering on the timeline to show a little video preview of that time like on youtube .
it would be so much time saving than the usual forward and then backward.
something like this image :
![thumbnailed-progress-bar-in-potplayer](https://cloud.githubusercontent.com/assets/16489849/21773006/aaed4584-d6a2-11e6-86b0-50c315eff90a.jpg)
thanks

**Comment by alejx** [comment]
Fixed by #753
