### ISSUE TITLE
Incorrect size (video cannot show full content)

### ISSUE THREAD

**Issue by HParis** [lhc70000/iina#1221]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1 Build 55

**Expected behavior:**

Here's what is should look. 
![Imgur](https://i.imgur.com/Iyb671K.png)

**Steps to reproduce:**

Just play the demo video I provided with IINA.

**How often does this happen?**

Always.

**Attachment**

Download the video from:  https://i.imgur.com/MGlSmZ6.mp4

**Comment by lhc70000** [comment]
The sample video seems to be compressed by imgur…… Could you provide the original file?

**Comment by HParis** [comment]
@lhc70000 Sorry. This is the original file: https://drive.google.com/open?id=1SZfpy7N1P65PJkM15DzkBnTV-TX1jT3f

**Comment by atomicsaiko** [comment]
Resolution is 1920 x 453px. It is not a nice vertical resolution to play with as it is not mod16 compliant. Closest would be 448px (28 * 16). Could it be IINA internally crops if resolution is not mod16 compliant or some other rule?

**Comment by HParis** [comment]
The Crop rule is default: none.

**Comment by alejx** [comment]
See #1603 (?)

**Comment by alejx** [comment]
Reopen if I'm wrong
