### ISSUE TITLE
can't run pod install

### ISSUE THREAD

**Issue by jaybenjaminlee** [lhc70000/iina#1222]
When run pod install

Analyzing dependencies
Pre-downloading: `GRMustache.swift` from `https://github.com/saagarjha/GRMustache.swift.git`, commit `efe20d10edc7af2ab9d60a42e94e1142cdef6535`

[!] Error installing GRMustache.swift
[!] Failed to download 'GRMustache.swift'

**Comment by WEAINE** [comment]
same issue

**Comment by saagarjha** [comment]
Sorry, it seems like I rebased that commit out of existence. Could you try a `pod update GRMustache.swift` while you wait for #819?

**Comment by jaybenjaminlee** [comment]
Thx

**Comment by ultratiem** [comment]
This is still happening and has not been fixed. Installed HomeBrew clean and pulled the latest build of IINA only to have the same error. Just FYI.

**Comment by alejx** [comment]
@ultratiem That should not happen, could you post the error message you got?
