### ISSUE TITLE
无法用双指拖动来调节视频进度(CANNOT use two finger movement to choose the time)

### ISSUE THREAD

**Issue by KashingLiu** [lhc70000/iina#1226]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**
When I use two finger to move the proceed of the video, when I move left, the video will go back(eg. from 4:03 to 3:20).

**Actual behavior:**
But when I move left, the video is end.(eg. from 4:03 to 5:00, and the whole video is 5:00), and when I use my mouse choose the proceed, it isn't exactly. (eg. when I choose to move to 3:30, the video turns to about 3:45)

- Crash report:
```
NO REPORT!
```

- MPV log:
```
NO LOG!
```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
默认使用的是关键帧查找，所以虽然设置的是 5 秒，但如果你的上一个关键帧在 30 秒之前，就会直接跳到 30 秒前。在偏好设置里使用精确查找可以避免这个问题，但是对于大文件会卡顿。可以试试「自动」，它会根据查找耗时自动选择是用关键帧还是精确查找，但这也不是个好方法。
