### ISSUE TITLE
MacOS10.13.1，每次打开，之前的所有设置都会失效，不知道别人有没有这个bug？

### ISSUE THREAD

**Issue by qixingchong** [lhc70000/iina#1228]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by qutongming** [comment]
macOS 10.13
IINA 0.0.14.1
我用的与你一样版本，也是一样系统版本，没有遇到你的情况

**Comment by gythialy** [comment]
me too

**Comment by qixingchong** [comment]
@qutongming 基本上是，打开一个分辨率大的视频，然后关掉软件进程，再打开一个分辨率小的视频，之前的设置就全部重置了。。。

**Comment by lhc70000** [comment]
据说 10.13.2 已经修复了此 bug，请升级系统。
