### ISSUE TITLE
IINA 是否支持投屏到智能电视？

### ISSUE THREAD

**Issue by f2sky** [lhc70000/iina#1229]
Mac 上安装 IINA 播放器，如何将播放的视频投屏到智能电视上？

和 MacBook 的版本有关系吗？

**Comment by inflation** [comment]
现在没有这个功能

**Comment by bladering** [comment]
有计划直接在播放器中增加airplay功能吗？mac上builtin的屏幕镜像功能可以用，但是影响电脑本身的使用。

**Comment by inflation** [comment]
Apple 没有关于 AirPlay 的相关文档，除了标准格式以外的不是很好解决，只能等苹果的进一步动作了。如果需要的话还是转码后用 QuickTime 播放。

**Comment by bladering** [comment]
用下来感觉很好，尤其喜欢能查找下载字幕的功能，👍👍

**Comment by dream5788** [comment]
那为什么爱奇艺可以，现在也不可以了。

**Comment by finscn** [comment]
> 那为什么爱奇艺可以，现在也不可以了。

但是 优酷mac版一直可以 (兼容 乐播投屏)
