### ISSUE TITLE
Does not show the covers of the audio files initially, only shows up after pausing.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#123]
I tried for mp3, alac. They all have the same issue. I suggest it is a common issue for all kind of audio files.

**Comment by lhc70000** [comment]
(add reference to #103)

**Comment by lhc70000** [comment]
Maybe mpv only passes one frame to us so it becomes black when flushed buffer...

**Comment by lhc70000** [comment]
Does this still happen in current version?

**Comment by alejx** [comment]
Fixed. Close.
