### ISSUE TITLE
Extension for safari can't be installed.

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#1230]
I tried several times, download the Open_In_IINA.safariextz, drag it to Safari and get the same result that nothing happening, the extension was not installed.

- macOS 10.13
- IINA 0.0.14.1
- Safari 11.0.1

**Comment by lhc70000** [comment]
Please try the solution in #637 first.

**Comment by gonejack** [comment]
Click the Trust button in confirm dialog with keyboard works, thank you!

And Apple sucks.
