### ISSUE TITLE
蓝光文件的播放

### ISSUE THREAD

**Issue by zym013579** [lhc70000/iina#1233]
如果还没有支持播放光盘文件，那么请当我什么都没说。。

尝试着打开了一个蓝光光盘文件，然后画面就这样了，下面的进度条也不对。
（还有播放光盘文件时应该屏蔽快捷键，要不然没办法控制
![2017-11-18 1 22 08](https://user-images.githubusercontent.com/18380161/32977232-27c71802-cc64-11e7-8791-cef2633adf92.png)

**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.14.1

**Comment by HarukaMa** [comment]
@zym013579 呃，这个 iso 里面就是标准蓝光盘结构？（bdmv 文件夹）

**Comment by zym013579** [comment]
@HarukaMa 看目录结构应该是没问题的，win下的播放器也能播放

**Comment by nutinshell** [comment]
似乎也有同样的问题，打开 bdmv 文件，播放顺序是错误的。望能增进。

**Comment by czhu** [comment]
同样问题。进度条不可用。
