### ISSUE TITLE
Minor Audio Playlist Display Bug

### ISSUE THREAD

**Issue by MuseofMoose** [lhc70000/iina#1241]
**System and IINA version:**
- macOS 10.12.6
- IINA 0.0.14.1

**Expected behavior:**
The playlist panel should mark the song that is currently playing.

**Actual behavior:**
![iina music playstli bug](https://user-images.githubusercontent.com/10477895/33151364-a3ad1f68-cf8c-11e7-960a-3a0653068dcf.gif)

Note how if I skip songs while the playlist viewer is collapsed and then open the playlist viewer, the arrow pointing to the "current song" is incorrect. If I click the playlist button again, however, it updates and moves to the correct song.

**Steps to reproduce:**
Add music playlist, collapse playlist viewer, skip to next song, open playlist viewer. The arrow denoting the currently playing song should be pointing to the incorrect song.

**How often does this happen?**
Every time.

**Comment by alejx** [comment]
See a55b58773de757b653152465e2063f232bf95d6c.
