### ISSUE TITLE
Subtitles time change stay after opening a new file

### ISSUE THREAD

**Issue by irrelevantspechack** [lhc70000/iina#1247]
**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.14.1 Build 55

**Expected behavior:**

when opening a new movie file while viewing one by bringing the new movie file you want to open on the actual movie windows, new subtitles are detected (or manually added), and the "subtitle delay" you changed to match the timeframe of the movie you precedently watched reset. 

**Actual behavior:**

subtitle delay you change manually doesn't reset when viewing a new video.

**Steps to reproduce:**

open a movie, load subtitle, change the delay of subtitles (ZX shortcut, forward or backward doesn't matter), then open a new movie file with subtitles automatically (doesn't matter if you add them apparently) detected. The delay will not reset.

**How often does this happen?**

all the time. looks like it also happen as long as you don't quit and restart iina

**Comment by lhc70000** [comment]
@irrelevantspechack Please try setting reset-on-next-file to sub-delay for "Additional MPV Options" in Preferences > Advanced.
