### ISSUE TITLE
Showing current cache size

### ISSUE THREAD

**Issue by hotpxl** [lhc70000/iina#1248]
**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.14.1 Build 55 (prebuilt binary)

**Expected behavior:**
In mpv, there is a indicator of cache size under progress bar (like https://i.warosu.org/data/g/img/0462/73/1422333401878.jpg , but mine looks different). Since I often stream from NAS, I think a feature like this would prove to be very useful.

**Comment by dreness** [comment]
You can also see cache state via the info window by naming the mpv properties to observe.

<img width="458" alt="cache-inspection" src="https://user-images.githubusercontent.com/5242016/33235773-e431f74c-d1f4-11e7-9da7-faed7684a8ae.png">

**Comment by hotpxl** [comment]
Thanks. That solves my problem. It even show the speed I'm reading :)
