### ISSUE TITLE
21:9显示器不能填充屏幕

### ISSUE THREAD

**Issue by zhanghedr** [lhc70000/iina#1249]
System and IINA version:

macOS 10.13.1
IINA 0.0.14.1
显示器：21:9 34寸曲面屏

尝试了给出的几种长宽比设置和各种自定义都不能填充屏幕，主要是宽/高不能拉满，这部电影在windows 10播放器下是可以填充全屏幕的，想问下IINA对于21:9宽屏显示器有没有填充屏幕的简单选项或者设置长宽比，非常感谢这么好用的播放器！

**Comment by Caffeine19** [comment]
你好，我同样也好奇是否有这样的一个功能，即便在16:9的屏幕下，因为我打开了侧边的程序坞，应用的界面同样也不能铺满剩余的屏幕空间。到目前为止我仍然没有在设置里找到解决这个问题的方法。因为这个原因，我转向使用恒星播放器，但是今晚我发现他的内存占用很大（1G左右），所以我又转向了iina
