### ISSUE TITLE
希望能调整快进/后退的步长

### ISSUE THREAD

**Issue by MJRT** [lhc70000/iina#1251]
现在默认是5s，调整时会错过部分内容，希望能自定义

**Comment by lhc70000** [comment]
@MJRT 请在偏好设置>快捷键中调整。

**Comment by MJRT** [comment]
@lhc70000 试了下，可以改，但我这边0.0.14.1 Build 55 版本中音乐模式的快进和视频模式的快捷键不一样，音乐模式只能按command+ ->快进5s ， 视频模式符合配置预期

**Comment by lhc70000** [comment]
音乐模式下一版会支持所有快捷键。
