### ISSUE TITLE
Slow UHD ProRes HQ422 (59,94 fps) decoding

### ISSUE THREAD

**Issue by atomicsaiko** [lhc70000/iina#1256]
IINA is unable to play UHD ProRes HQ422 59,94 fps MOV files smoothly. Quicktime Player X is. Hardware decoding is out of the question for intermediate post-production formats. It appears the software decoder for ProRes in MacOS is quite efficient. Is IINA using a different software decoder to decode ProRes codec?

I have a MacBook Pro 13" (2017)

Samples [here](https://www.harmonicinc.com/4k-demo-footage-download/).

- macOS 10.13.1
- IINA 0.0.14.1

**Comment by lhc70000** [comment]
IINA uses [mpv](https://github.com/mpv-player/mpv/) for decoding. Please consider reporting this issue to them.

**Comment by inflation** [comment]
@atomicsaiko You maybe know that ProRes is a private file format. Even though Apple has a white paper illustrating how the format encoding the image, unofficial implementations may suffer performance drop. Unfortunately, FFmpeg, which used by mpv, is one of those(especially mentioned in the white paper). So you probably should stick with Apple this time. 

BTW, is there any specific reasons you want to check those intermediate format in IINA?
