### ISSUE TITLE
播放界面（控制器）建议使用响应式布局

### ISSUE THREAD

**Issue by uedvincent** [lhc70000/iina#1257]
播放手机录屏的视频时，界面显示存在不完善的地方。建议使用响应式布局，就像 Quicktime 一样～
<img width="281" alt="image" src="https://user-images.githubusercontent.com/21360118/33427285-c7a8baf2-d5ff-11e7-8317-7ee466019841.png">

**Comment by alejx** [comment]
f21c3113929a5a6ecddc191e9e6abe7bf921287c 防止了窗口缩到很小, 现在应该不会出现控制条被截断的情况了.
