### ISSUE TITLE
缩放窗口时，某些情况下会不加载设置。

### ISSUE THREAD

**Issue by dlnicky** [lhc70000/iina#1259]
**System and IINA version:**
- macOS 10.13
- IINA 0.0.14.1

情况说明：
新打开视频时自动全屏窗口，当双击播放器缩小窗口时，在某些情况下会不加载播放器设定，恢复到初始设定。

可能重现过程：
- 在播放时，强制关闭播放器，再次打开时，复现的可能性大。
- 长时间暂停后，再次播放，也会有机率再现这个问题。

重新打开播放器，会恢复设定的状态，不会使用初始化设定。
此问题在0.012版本之后多个版本中出现过。

以下是我的设定：
<img width="810" alt="2017-12-02 14 43 52" src="https://user-images.githubusercontent.com/3337633/33512311-2ddeab98-d771-11e7-8695-18fe94984563.png">
<img width="704" alt="2017-12-02 14 44 05" src="https://user-images.githubusercontent.com/3337633/33512312-3192f460-d771-11e7-8e38-d0f52a25895b.png">
<img width="612" alt="2017-12-02 14 44 14" src="https://user-images.githubusercontent.com/3337633/33512316-3463fb6c-d771-11e7-9c2a-6ec323e6ff6a.png">

以下是打开视频，自动全屏窗口状态，注意OSD控制条状态。
<img width="1440" alt="2017-12-02 15 07 18" src="https://user-images.githubusercontent.com/3337633/33512376-941660bc-d772-11e7-84d2-e32fcccf3506.png">

以下是在全屏状态，变成窗口状态时出现的问题，注意OSD控制条状态。
<img width="1072" alt="2017-12-02 14 54 50" src="https://user-images.githubusercontent.com/3337633/33512377-9d4d7d5a-d772-11e7-9882-f5b40c7f0b76.png">

以下为出现问题的LOG。
[2017-12-2-14-38-10_TuwyMu.log](https://github.com/lhc70000/iina/files/1523597/2017-12-2-14-38-10_TuwyMu.log)

**Comment by lhc70000** [comment]
据说 10.13.2 已经修复了此 bug，请升级系统。
