### ISSUE TITLE
Subtitle can't sync real time

### ISSUE THREAD

**Issue by GUOBAODACAI** [lhc70000/iina#1263]
I am a subtitle translator and using IINA while working. And as I edit the  subtile in SRT , I kept drag  the edited and saved SRT  to the video ,but the subtitle  shows on the video is still the before  edit one , I had to reopen  this video then drag new  SRT to it to see how it shows.
Please sync subtitle  real time .Thank you .

**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Should be fixed in 46e5fa7
