### ISSUE TITLE
Weird border around playback controls and play/pause HUD

### ISSUE THREAD

**Issue by jacobgelman** [lhc70000/iina#1267]
**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.14.1

When playing back a video in picture-in-picture mode, a strange border appears around the playback controls and play/pause HUD in the main window:

<img width="771" alt="screenshot" src="https://user-images.githubusercontent.com/3182119/33747217-96617836-db76-11e7-99be-eb23e34cd322.png">

**Steps to reproduce:**
- Open a video
- Enter picture-in-picture playback mode

**How often does this happen?**
Every time

**Comment by saagarjha** [comment]
I believe this is similar to #350. I think this is an issue with Cocoa, but I don't think I've gotten around to filing a radar for it yet.
