### ISSUE TITLE
对弹幕的支持还不佳

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#1268]
之前提议支持B站的XML格式弹幕文件，作者建议我考虑使用转换脚本把XML转为ASS字幕文件，但转化出来的字幕文件是IINA是不支持自定义字幕样式的，要么忽略样式，要么使用字幕文件自己的样式。

而且似乎缺少了PotPlayer里
![image](https://user-images.githubusercontent.com/2720676/33794532-dcef46b4-dd08-11e7-8c61-4ca8d95092b1.png)的这种设置，ASS字幕除了样式丑的问题以外卡顿严重。

**Comment by inflation** [comment]
libass对于ass文件要求很严格，具体要求请参照其文档。如果还有问题，请直接向libass反应。

**Comment by gonejack** [comment]
估计大部分用户和我一样并不知道IINA用了什么三方库，而且如果觉得我提的问题不合理，请直接说不支持或者无法处理。

不要把问题和提问者踢向第三方库，毕竟提问者不清楚你怎么使用第三方库。

**Comment by inflation** [comment]
好的，无能为力。
