### ISSUE TITLE
"Always on top" not saved and no window buttons

### ISSUE THREAD

**Issue by JohnSinclair111** [lhc70000/iina#127]
If "always on top" is switched on, the settings isn't saved (should so). Also, if its checked the window buttons (green, yellow, red) aren't working anymore (and have no mouse over).

**Comment by lhc70000** [comment]
> "Always on top" not saved

Duplicate with #113.

> no window buttons

Already fixed in master branch, please wait for next release (v0.0.2).
Duplicate with #15.

**Comment by androidcn** [comment]
Do not use Always on Top ,just use "**on Top while playing**"...

**Comment by lhc70000** [comment]
@androidcn 

however the window appears only while playing... :P

Now changed to "Float on top".

**Comment by lhc70000** [comment]
> if its checked the window buttons (green, yellow, red) aren't working anymore (and have no mouse over).

Fixed in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).

**Comment by lhc70000** [comment]
Close due to fixed in [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3).
