### ISSUE TITLE
two problems when playing video from youtube by Chrome extension

### ISSUE THREAD

**Issue by msongz** [lhc70000/iina#1272]
**System and IINA version:**

- macOS 10.12
- IINA 0.0.14.1

**Expected behavior:**

1.when jump forward , it won't re-cache the frames

2.video would not frozen

**Actual behavior:**

1.when jump forward , it re-cache the frames

2.when play youtube video , some times video was frozen , but audio keeps playing

**How often does this happen?**

each time jump the timeline

**Comment by inflation** [comment]
Can you provide any logs? I tried several times but never encountered the issues.

**Comment by lhc70000** [comment]
This issue has been closed due to inactivity. Please reopen if you have could provide more info.
