### ISSUE TITLE
Feature Request - Dear iina team, any plans for support of Live TV Streams?

### ISSUE THREAD

**Issue by swatchion** [lhc70000/iina#1276]
Live Stream is more and more popular on internet, and people doesn't have to download the video files, simply add a http live stream link, and here the show get played. It's a faster and up to date way.

Just curious if this feature will be planned, btw inna player is already perfect enough in my point of view. 

Thanks for excellent work sincerely.

**Comment by inflation** [comment]
IINA does have the feature. `File > Open URL in New Window...` or ⇧⌘O for the shortcut.

**Comment by swatchion** [comment]
Thank you for the advise.
