### ISSUE TITLE
Youtube subtitles all look the same in the subtitle list

### ISSUE THREAD

**Issue by tellowkrinkle** [lhc70000/iina#1277]
I know in previous versions of IINA, the language of each subtitle was displayed next to the subtitle name, but that seems to have been removed in one of the more recent builds.  This is usually fine, but with YouTube, there is no all the names are the same so you can no longer tell them apart.  I think it would make sense to enable names on any subtitle file whose name is the same as another subtitle file in the list.

**System and IINA version:**

- macOS 10.13.2（17C88）
- IINA 0.0.14.1

**Expected behavior:**
You can figure out which subtitle is which language when playing youtube videos

**Actual behavior:**
Every single subtitle is labeled `vtt` with nothing else after it
<img width="70" alt="Subtitle List Screenshot" src="https://user-images.githubusercontent.com/3315070/34074858-c7f2ae98-e27d-11e7-838c-6b59add53cb0.png">

**Steps to reproduce:**
- Play a YouTube video that has subtitles through IINA
- Open the subtitle picker from the gear button

**How often does this happen?**
Every time

**Comment by inflation** [comment]
Hmm... We're assuming the language identifier like 'eng' in ISO639_2, but sometimes YouTube would returns 'en', so we don't recognize it. We may need to consider ISO639_1 as well.

**Comment by inflation** [comment]
Should be solved by 76c568f
