### ISSUE TITLE
[Feature Request] Add shortcut for Pause/Resume

### ISSUE THREAD

**Issue by hiberabyss** [lhc70000/iina#1279]
Is it possible to add shortcut like `Space` for Pause/Resume?

Thanks!

**Comment by inflation** [comment]
Isn't that default? 

Or you could bound `SPACE` for `cycle Pause` under Key Bindings.

**Comment by hiberabyss** [comment]
Seems the key bindings did not work in music mode.

IINA Version: 0.0.14.1 Build 55

**Comment by lhc70000** [comment]
It has been fixed in develop branch.

**Comment by jerkstore369** [comment]
Where can one download the latest develop branch?

**Comment by inflation** [comment]
@jerkstore369 Normally there wouldn't be a compiled version. You can always build from the develop branch.
