### ISSUE TITLE
Support for opening URL (and file) in current window

### ISSUE THREAD

**Issue by krokofant** [lhc70000/iina#1281]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Current behavior:**
![image](https://user-images.githubusercontent.com/5908498/34168650-59177674-e4e5-11e7-8f77-0e1682c0b8a7.png)

**Desired behavior:**
That there be an option to open file or URL in current window.

Files can be dropped into the current window but URLs does not seem to be able to be played in the current window.

URLs does not seem to be able to be added to the playlist either.

**Comment by krokofant** [comment]
I did find the option "Always open media in a new window" but that seems to remove support for multiple windows.

**Comment by alejx** [comment]
You can try to press <kbd>alt</kbd> in file menu, and you'll see the alternative option.

**Comment by krokofant** [comment]
Amazing!
