### ISSUE TITLE
电视节目进入广告时间的过场就会重置时间线

### ISSUE THREAD

**Issue by androidcn** [lhc70000/iina#1284]
这些电视的进入广告时间就会把时间线 重置到0

http://www.66ys.tv/dsj2/20171107/35923.htm

**Comment by inflation** [comment]
请试试直接使用 youtube-dl 能否下载？

**Comment by androidcn** [comment]
我都是直接下载到NAS 进行INNA播放

**Comment by inflation** [comment]
那么请提供播放时的log
