### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by olafchou** [lhc70000/iina#1286]
I want a shortcut to speed up the movie 
<img width="350" alt="2017-12-23 23 34 10" src="https://user-images.githubusercontent.com/19890798/34320645-e1a3656e-e839-11e7-9bc8-ad6a02ae52ba.png">

**Comment by inflation** [comment]
You can set a keyboard shortcut
<img width="715" alt="screen shot 2017-12-25 at 6 22 40 am" src="https://user-images.githubusercontent.com/2375962/34329454-093d5c6c-e93c-11e7-83f7-98584578acd6.png">

**Comment by olafchou** [comment]
you know ,maybe I will speed 1.2 ,1.1 1.3 , one shortcut can only set one speed is not enough ,i want one shortcut can speed many ,like cmd+→ or cmd+← .

**Comment by lhc70000** [comment]
@olafchou You can also increase or multiply a property: 
![08f32288-fa1c-4c10-b38b-dd0962270961](https://user-images.githubusercontent.com/8478049/34903418-14d10f62-f86c-11e7-9575-1faba2b8eb45.png)
