### ISSUE TITLE
<Feature Request> 功能建议

### ISSUE THREAD

**Issue by VoidXia** [lhc70000/iina#1287]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

希望能够增加一个类似Movist的在右上角灰色显示当前时间和剩余播放时间的选项

**Comment by inflation** [comment]
Duplicate as #179

**Comment by inflation** [comment]
Duplicate of #179

**Comment by lhc70000** [comment]
这个需要一直显示，还是只在移动鼠标之后显示？

**Comment by VoidXia** [comment]
诶都可以的吧……Movist是一直显示的...
