### ISSUE TITLE
issue of Trad. Chinese translate

### ISSUE THREAD

**Issue by abc1236762** [lhc70000/iina#1291]
- macOS 10.13
- IINA 0.0.14.1

IINA in Trad. Chinese, "Screen" is "熒幕", but its not correct at Taiwan.
I don' t know that other locals that use Trad. Chinese would translate english "screen" to "熒幕" or
 "螢幕", but is "螢幕" at Taiwan.

Please use correspond translations to different locals that use Trad. Chinese.

**Comment by alejx** [comment]
We are currently using zh-Hant only, so we are not distinguishing zh-Hant-HK and zh-Hant-TW. If you knows zh-TW well and want to help us to improve it, we are willing to distinguish them.

**Comment by abc1236762** [comment]
Other strings of Chinese translate are not any problems with different locals that use Trad. Chinese. Only found that "熒幕" is, and I think "螢幕" is more often seen and used then "熒幕" in all locals that use Trad. Chinese.

**Comment by abc1236762** [comment]
For example, not only Taiwan but also Hong Kong Apple offical website also use "螢幕" to express english "screen", not "熒幕".

reference:
"Screen Repair" => "螢幕維修"
https://support.apple.com/en-us/iphone/repair/screen-damage
https://support.apple.com/zh-hk/iphone/repair/screen-damage
"entirely screen" => "全螢幕"
https://www.apple.com/iphone-x/
https://www.apple.com/tw/iphone-x/
... and more.

**Comment by alejx** [comment]
I get your point, then it would probably a typo. I’ll fix them shortly.
