### ISSUE TITLE
希望增加一个3D播放功能

### ISSUE THREAD

**Issue by wahsunlyu** [lhc70000/iina#1299]
我在Mac上没有找到一款合适的3D播放器,而IINA播放器很棒,希望后续可以增加播放3D视频的功能

**Comment by Miigon** [comment]
你指的是Virtual reality还是播放3D格式内容？

**Comment by wahsunlyu** [comment]
普通格式的视频文件播放成3D模式，就像Windows下的暴风影音那样的
