### ISSUE TITLE
Add an initial interface | 增加初始界面

### ISSUE THREAD

**Issue by trusbe** [lhc70000/iina#13]

**Comment by lhc70000** [comment]
目前 IINA 试图和 macOS 自带 App（即 QuickTime） 做到契合，所以暂时不考虑初始界面。如果需要的人很多，会在后续版本中加入可选的初始界面。

---

Currently IINA tries to have similar behavior as original Apps in macOS (like QuickTime). I'll consider adding a initial window in later version if many users have such demand.

**Comment by saagarjha** [comment]
@lhc70000 QuickTime opens an initial window, at least on my computer.
