### ISSUE TITLE
Screen go sleep while playing | 视频播放的电脑依然会休眠

### ISSUE THREAD

**Issue by lm2343635** [lhc70000/iina#130]
如题，视频播放电脑应该不休眠的吧。

**Comment by lhc70000** [comment]
此问题已经在 `master` 分支中修复，请等待 v0.0.2 版本。

如果你想先试用测试版，请给我发邮件、加入 QQ 群 `142730636` 或 Telegram group。

与 #4, #74 重复。

---

Duplicate with #4, #74

**Comment by lhc70000** [comment]
Close as fixed in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).
