### ISSUE TITLE
不支持的外部字幕

### ISSUE THREAD

**Issue by VoidXia** [lhc70000/iina#1301]
当点击查找在线字幕时出现
显示不支持的外部字幕
加载字幕失败
<img width="953" alt="2018-01-01 11 40 52" src="https://user-images.githubusercontent.com/9496124/34465463-e0cc0af0-eee8-11e7-93e4-f8638434edaf.png">

**Comment by VoidXia** [comment]
顺便zimuzu.tv的字幕质量似乎也不错，希望能够加入字幕自动下载的列表当中

**Comment by inflation** [comment]
这个提示说明字幕文件不规范。

zimuzu.tv 暂时没有发现 API 接口。
