### ISSUE TITLE
Playing Two Music will cause two player to play 

### ISSUE THREAD

**Issue by bloggervista** [lhc70000/iina#1302]
Suppose i am opening one song and if i try to open another song they will both open so i cannot listen to anyone in which every user expect it latest to play. 

I checked option and i don't think it should be expected right?

**Comment by lhc70000** [comment]
@bloggervista You should uncheck the "always open media in new window" option in Pref - General.

**Comment by bloggervista** [comment]
@ihc70000

Thanks didn't thought about it :) . I guess by default it should be unchecked.
