### ISSUE TITLE
使用蓝牙耳机时，音频输出有问题

### ISSUE THREAD

**Issue by Livingston2018** [lhc70000/iina#1310]
- macOS 10.10
- IINA 0.0.14.1

使用Airpods等蓝牙设备时，播放视频如果快进或者快退，音频部分的输出将出现不连续的现象，直至完全没有声音。视频部分还能够正常播放。

使用自带的quicktime player，无论如何快进快退，均不会出现上述现象。

**Comment by sSAidenSs** [comment]
遇到的问题和你一样

**Comment by NominationP** [comment]
同问

**Comment by l8higher** [comment]
＋1，使用蓝牙设备输出时，暂停播放快进都会卡顿，非常影响体验。
