### ISSUE TITLE
Playback position is not stored when switching to next file in playlist only on quitting

### ISSUE THREAD

**Issue by snipem** [lhc70000/iina#1317]
When playing files through a playlist their position is not stored when switching between files. Only the file last open before closing IINA will be restored and saved at the correct position.

When closing the files individually (Hit q for each file) and the correct positions are restored even by playing them through a playlist.

**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.14.1 Build 55

**Expected behavior:**

1. Play file 1 to minute 1:00
2. Switch over to file 2 by clicking the file in the playlist
3. Play file 2 to minute 1:00
4. Switch over to file 3 by clicking the file in the playlist
5. Play file 3 to minute 1:00
6. Quit

Reopen  IINA:

1. File 1 plays from minute 1:00
2. File 2 plays from minute 1:00
3. File 3 plays from minute 1:00

**Actual behavior:**

1. Play file 1 to minute 1:00
2. Switch over to file 2 by clicking the file in the playlist
3. Play file 2 to minute 1:00
4. Switch over to file 3 by clicking the file in the playlist
5. Play file 3 to minute 1:00
6. Quit

Reopen IINA:

1. File 1 plays from minute **0**:00
2. File 2 plays from minute **0**:00
3. File 3 plays from minute 1:00

Only the position of file 3 is stored upon next open of the file. File 1 and 2 play from the beginning.

**Comment by lhc70000** [comment]
That's mpv's behavior. When you switch to another video manually, it assumes that you are done with that video.

It's not ideal in my point of view too. I'll try to improve it in later versions.

**Comment by snipem** [comment]
@lhc70000 Do you know of any mpv configuration setting to achieve the desired behavior? This would be perfectly fine.

**Comment by snipem** [comment]
https://github.com/mpv-player/mpv/issues/4581 This comment might be something. Still, it won't help me when I'm clicking on something.
