### ISSUE TITLE
 Can't switch input method use caps-lock | 使用期间无法使用大写锁定键切换输入法

### ISSUE THREAD

**Issue by ChengLuffy** [lhc70000/iina#132]
In macOS 10.12, user can change the system input method by Caps-lock.
But when iina is open, it doesn't work.

**Comment by lhc70000** [comment]
IINA now captures *all key input* and passes them to mpv to be compatible with mpv's `input.conf`. We are not willing to change this behavior, however there has to be some workaround.

Please see #114.
