### ISSUE TITLE
使用过程过遇到的问题

### ISSUE THREAD

**Issue by Chynayu** [lhc70000/iina#1320]
系统和IINA版本：

macOS 10.13.2
IINA 0.0.14.1

1.通过插件打开网页视频后播放一小会儿后出现卡画面的情况，但是还在继续播放声音
![image](https://user-images.githubusercontent.com/35174792/34642521-4813c594-f34f-11e7-89f5-8024ce61820a.png)
之前版本没有出现这种问题，我才更新了新的版本出现了这个问题

  2.有无法打开文件或流
![image](https://user-images.githubusercontent.com/35174792/34642561-acbf4090-f34f-11e7-9c38-e4dcbbad7924.png)
之前版本出现过这种问题，不知道是不是无法破解
  
3.连接播放过程中不太流畅，会间歇性卡顿缓冲，但在网页播放没有这种情况

**Comment by lhc70000** [comment]
1. 可尝试禁用硬件解码
2/3. 暂时没有办法

**Comment by zyztorch** [comment]
播放控制总是会自动弹出，但是我没有移动鼠标，怎么解决呢？
