### ISSUE TITLE
Will the subtitle of online searches be saved locally?

### ISSUE THREAD

**Issue by Wanguy** [lhc70000/iina#1324]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Question:**
I load subtitle from online searches when I play a video, will it be saved as a file? If it does, Where can I find it?

**Comment by lhc70000** [comment]
`Subtitles - Save Downloaded Subtitle` will save the current selected subtitle to the video folder.

**Comment by Wanguy** [comment]
Oh, I never notice that. Thanks very much.
