### ISSUE TITLE
The video plays at the top, not at all times

### ISSUE THREAD

**Issue by faying** [lhc70000/iina#133]
The video plays at the top, not at all times, when I pause the video, it should be cancel the top.
And sometimes the CMD+W close windows does not work

**Comment by faying** [comment]
Another problem, there is no need always use dGPU to codec, otherwise the battery will lose quickly. Maybe a option is need on the settings

**Comment by lhc70000** [comment]
> there is no need always use dGPU to codec
Duplicate with #18, fixed in`master` branch. Please wait for next release.

> when I pause the video, it should be cancel the top. And sometimes the CMD+W close windows does not work
Got it.

**Comment by neesonqk** [comment]
@faying I cannot reproduce the incidental closure issue of pressing CMD+W, I suspect that you floated the player which made it seemed to be in focus, while it wasn't the first responder as CMD+W was hit by the time.

**Comment by lhc70000** [comment]
@neesonqk It does happen occasionally and I believe it's the same reason of #35. For some users it even happens **every time**. I'll try some fix later.
