### ISSUE TITLE
Is it possible to make the window smaller

### ISSUE THREAD

**Issue by Mushr0000m** [lhc70000/iina#1330]
**System and IINA version:**
- macOS 10.13.2
- IINA 0.0.14.1

Is it possible to make the window very small ? I like to play a video on a corner of my macbook but in normal mode I can't make it tiny because of the controllers so there some min width. In PIP mode, there is a gap from the edge of the screen (a gap), I can't put the PIP collapse to the edge of my screen. Is there a way to achieve this small video window ?

Thanks for this player.

**Comment by saagarjha** [comment]
If you're trying to get rid of the gap, if you hold down <kbd>Command</kbd> while dragging the PIP window you can move it anywhere, including right up to the edge of the screen.

**Comment by Mushr0000m** [comment]
Yep it's working, thanks !
