### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1331]
I paused the movie to check out some things online (firefox 57). An hour or so later I get back to the movie, the subtitles suddenly aren't showing. I quit iina with the intention of restarting it, it crashes.

https://pastebin.com/GSdmxR4Q

thanks.

**Comment by lhc70000** [comment]
Sorry but I can't do more research on this without reproducing it. If it happens again or there's a way to reproduce, please reopen this issue.
