### ISSUE TITLE
Ghost dock image beneath pinned Controller in fullscreen mode

### ISSUE THREAD

**Issue by prohtex** [lhc70000/iina#1336]
![img_0759](https://user-images.githubusercontent.com/12946938/34814942-5e44fcd0-f664-11e7-9827-02c6ce9e46b4.JPG)

**Comment by lhc70000** [comment]
It should be a macOS bug.

**Comment by prohtex** [comment]
I was wondering if it would be possible to add a preference to set Controller to Bottom in window mode, but Floating in fullscreen mode. Seems this would be a workaround and a good feature to have anyway.
