### ISSUE TITLE
Feels like add a welcome window will make it better

### ISSUE THREAD

**Issue by GeerX** [lhc70000/iina#134]
lllllllove your app, but it seems that a welcome window will be more user-friendly~

**Comment by lhc70000** [comment]
Duplicate with #13 

Will be fixed by #117

**Comment by lhc70000** [comment]
You can now add an initial open file window by enabling "Preference-General-Behavior" in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).
