### ISSUE TITLE
提议: 改建用户设置的模式

### ISSUE THREAD

**Issue by SLboat** [lhc70000/iina#1343]
我看到现在的用户设置是重写了一个基类,然后用大量的rawvalue,set这类配合,而我提议用以下这个简单的扩展库来完全的改写.

https://github.com/radex/SwiftyUserDefaults

**Comment by lhc70000** [comment]
@SLboat 似乎它还不支持 Swift 4，我会过一段时间再考虑。

**Comment by SLboat** [comment]
@lhc70000 嗯,它非常兼容swift4的,它实际的代码也就一整段儿,实现的非常简单,范类扩展,但是让整个设置的读写变得非常自然,优雅了.

**Comment by SLboat** [comment]
我习惯用它集成设置类操作,这个插件的作者真是个精明人,那种方式免去了和类型打交道.甚至能够操作一些自定义的类型:

`//扩展支持解包类
extension UserDefaults{
    //下标方法声明
    subscript(key: DefaultsKey<NSPrintInfo?>) -> NSPrintInfo? {
        get { return unarchive(key) }
        set { archive(key, newValue) }
    }
}`

**Comment by SLboat** [comment]
贴的代码太丑了,不懂怎么markdown代码,抱歉.

这个case可以关闭了,感谢老兄及时回复,祝你编码愉快.
