### ISSUE TITLE
mediaplayer框架在10.11不兼容

### ISSUE THREAD

**Issue by SLboat** [lhc70000/iina#1345]
当前master引入了很好的mediaplayer框架,但是导致10.12前系统会直接崩溃无法开启,因为它们没有这个框架.

/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0)

**Comment by lhc70000** [comment]
Thanks for reporting, this is a critical issue.

**Comment by SLboat** [comment]
![slboat-mac-screen 2018-01-12 0 31 58](https://user-images.githubusercontent.com/4231376/34835522-05f072f4-f730-11e7-8363-da97907a3a1c.jpg)
可以这样简易解决
