### ISSUE TITLE
HW Decode - HEVC Main10

### ISSUE THREAD

**Issue by viritt** [lhc70000/iina#1359]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15/0.0.14.1

**Expected behavior:**

With the new MacBook Pros I believe HW decode of Main10 profiles for HEVC should be possible.
I am referring to the ones with dedicated graphics card, for example the Radeon Pro 460 which should support this functionality.

**Actual behavior:**
The latest two versions that support HVEC hardware decode, do not hardware decode when playing Main10 profile.

**Comment by inflation** [comment]
Unfortunately no. Even if your graphics card has the ability, Apple does not provide the option to use it. And I believe only 2017 MacBook Pros can hardware decode HEVC Main10 for now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
