### ISSUE TITLE
播放时候调节系统亮度,会卡顿

### ISSUE THREAD

**Issue by SLboat** [lhc70000/iina#1360]
播放视频-调节亮度-观察到明显的短暂卡顿.

**Comment by Miigon** [comment]
* 是否播放任何视频都会存在这个卡顿？
* 请附上你的机器型号、系统版本、软件版本。

**Comment by SLboat** [comment]
MC207 老款小白,播放mp4文件,10.13系统

From SLboat

**Comment by SLboat** [comment]
我感觉会不会主窗口透明视图太多了,blur效果,只有一个总的不行吗?

From SLboat

**Comment by Miigon** [comment]
应该是因为亮度调节图标背景的blur特效附加在视频画面上导致卡顿。
这个问题可能没办法解决，因为机器性能不足，并且附带的GeForce 9400M图形卡可能有兼容性问题。

`系统偏好设置 - 辅助功能 - 显示器 - 减少透明度`这个选项也许对你有帮助。

**Comment by SLboat** [comment]
好的 谢谢老哥
