### ISSUE TITLE
希望窗口缩放时可以支持『上下补黑边』的模式

### ISSUE THREAD

**Issue by finscn** [lhc70000/iina#1361]
大多数播放器都是支持的. 类似这样: 

![image](https://user-images.githubusercontent.com/288367/34913895-32a2f9f6-f943-11e7-85d1-7a073d4df0f3.png)

这么做的好处有两个:
1 , 可以把字幕移动到黑色区域
2, 执行进度调节 音量调节等操作时 也不会挡住画面.

但是目前 IINA只有全屏时才可以. 

我之前提过一个类似的PR: https://github.com/lhc70000/iina/issues/1158 , 
但是可能我英文太烂, 作者没理解, 所以在这里用中文和截图再详细解释一下. 

谢谢了

**Comment by lhc70000** [comment]
我在考虑加入类似的功能。

**Comment by rukkora** [comment]
I want this feature
Please add in next update.

**Comment by finscn** [comment]
@lhc70000 有什么进展吗? 关于这个需求.
我再举个具体例子:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/288367/193495690-e717769b-58e1-4703-8fcb-2609c147de66.png">

哪怕不支持复杂的缩放, 至少希望能支持类似上图这种 "窗口可以任意大小, 但是视频保持等比例 且完整(不被剪裁) 的模式.
这个真的非常有用. 尤其是在希望 "即使显示控制栏也不要遮挡字幕" 时.

**Comment by ZWenzzzz** [comment]
![截屏2023-06-20 01 53 34](https://github.com/iina/iina/assets/15025795/3831c411-c2e6-4b95-a230-118898a9baba)
我发现了这个问题，34寸带鱼屏显示器播放21:9的视屏时，也无法全屏，缩放也无法全屏？！
