### ISSUE TITLE
Videos open at half size

### ISSUE THREAD

**Issue by prohtex** [lhc70000/iina#1364]
I have IINA set as follows, but about 30% of the time, videos open at half size.

<img width="807" alt="screen shot 2018-01-14 at 1 43 36 am" src="https://user-images.githubusercontent.com/12946938/34914683-59172264-f8cc-11e7-8319-8e12a0ef068d.png">

I am on 10.12.6 with IINA .15 build 62

System info:
https://pastebin.com/raw/jet7WbgQ

**Comment by lhc70000** [comment]
It may be the same issue with #1335, i.e. some problem related to User Defaults.

If you are not able to upgrade your Mac to 10.13, I need your help to try a debug build in order to gather more information.

**Comment by prohtex** [comment]
Ok, I am happy to try to debug

**Comment by prohtex** [comment]
I am still having this issue. Very often when a video opens, it opens at half size and the controls do not skip as expected, but rather change speed. I'm not sure what to do.
