### ISSUE TITLE
Feature Request: Turn off backlit keyboard when playing movie

### ISSUE THREAD

**Issue by S-UP** [lhc70000/iina#1367]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

I would suggest disabling the backlit keyboard completely when a moving is playing (e.g. after a minute or so) to have a completely black keyboard. Makes it nicer to watch a movie.

**Comment by saagarjha** [comment]
Similarly to #1368, I don't think this should be part of IINA. It's probably for the best if your video player doesn't muck around with IOKit device drivers, particularly ones that are private.

**Comment by vosatom** [comment]
VLC 3.0 now supports keyboard backlight dimming when turned to fullscreen mode.

**Comment by saagarjha** [comment]
A brief glance [shows](https://github.com/videolan/vlc/blob/master/modules/gui/macosx/VLCKeyboardBacklightControl.m) that they're messing around with IOKit. I'm not sure I'm comfortable with my video player doing this.
