### ISSUE TITLE
TouchBar progress indicator and playing time not updating when playing music

### ISSUE THREAD

**Issue by whoinoi** [lhc70000/iina#1369]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15 Build 64

**Expected behavior:**

The progess indicator and the playing time should represent the position of the song, similarly to how they do when playing video.

**Actual behavior:**

It's not doing it. It's stuck wherever the song was when IINA started playing it (i.e. usually at 0:00 (see also screenshot), if the song has not started playing somewhere in the middle because you left off there earlier).

Scrubing on the TouchBar to change the position works fine. It's just that the progress doesn't update.

Example: That's how it looks when IINA is playing music
<img width="1085" alt="pic" src="https://user-images.githubusercontent.com/10744641/34920900-a413d38a-f97a-11e7-8000-1a6cb67e347d.png">

**Steps to reproduce:**

I tried various mp3 and m4a tracks. All show the same issue.

- [x] MPV does not have this problem.

**How often does this happen?**

Consistently. Every time.

**Comment by ErikMinekus** [comment]
This only happens in Music Mode.
