### ISSUE TITLE
不知道ass字幕能不能做到样式不变的情况下自定义字体

### ISSUE THREAD

**Issue by cv0cv0** [lhc70000/iina#1371]
有的字幕字体不如人意。

**Comment by liweihao5253** [comment]
勾上忽略所有ass样式，然后把覆盖等级调成force，然后选择自己喜欢的字体和颜色吧

**Comment by cv0cv0** [comment]
这样设置了，但是并不是我设置的字体。

发自我的 iPhone

**Comment by cv0cv0** [comment]
@liweihao5253 拉到最左边可以设置字体，但是样式不生效了，中间用的还是字幕的字体，只是颜色不生效了。

**Comment by inflation** [comment]
直接修改 ass  文件，替换字体名称就可以了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cv0cv0** [comment]
如果是内置的就不行了。

发自我的 iPhone
