### ISSUE TITLE
Step forward/backward now wildly inconsistent

### ISSUE THREAD

**Issue by TempSpas** [lhc70000/iina#1372]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15 Build 64

**Expected behavior:**

Pressing the left/right arrow keys should step backward/forward 5 seconds respectively.

**Actual behavior:**

The amount of seconds stepped through is wildly inconsistent.

- MPV log:
```

```

**Steps to reproduce:**

1. Pause the video and jump to a "neutral" point in the video. For example, 12:00.
2. Press the left arrow key. Expect **11:55**. Instead, receive **11:53**.
3. From here, press the right arrow key. Expect **11:58**. Instead, receive **12:03**.

- [x] MPV does not have this problem.

**How often does this happen?**

This happens with every video I open.

**Comment by lhc70000** [comment]
Please edit the key binding and choose exact seek:

![9c3541c0-b064-488a-9f2d-fd7acfe02631](https://user-images.githubusercontent.com/8478049/34937139-a8c1271c-fa1e-11e7-8aa5-d4f39f0b449b.png)

**Comment by TempSpas** [comment]
<img width="284" alt="screen shot 2018-01-15 at 12 10 29 pm" src="https://user-images.githubusercontent.com/3801275/34954089-1c2d0ee6-f9ed-11e7-9bed-ebc704eee961.png">

Isn't that what they are set to already?

**Comment by TempSpas** [comment]
I removed those from the configuration screen and re-added them, and so far it seems to be working as intended. But I'd like to stress that the settings I added are identical to the way they were, and it was bugged.

**Comment by Nes-si** [comment]
Why the exact seek is not default? What are the cases where the inconsistent seek may be useful?
It's really annoying if the seek has variable value. And I haven't solution until I've gone to Github issues and found this.

**Comment by inflation** [comment]
@Nes-si The default behavior is seeking key frames. Precise seeking needs to decode the frames from your current  position to the target. Please check the mpv’s manual for more explanation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anilnatha** [comment]
I have been experiencing this issue on my machine as well.  On my computer, when hitting the left or right arrow, IINA moves in 1 minute increments, not 5 second increments as described in the menu for the keyboard shortcuts.

Another important issue is that when the playhead is advanced using these shortcuts, IINA is rounding the next starting point to the minute.  For example, If the playhead is at the 14 or 36 second mark and I press the right arrow key, it will start playing at the 1 minute mark when it should have started playing at the 19 second or 41 second mark respectively.

MacOS version: 10.14.6
IINA: 1.0.7 Build 119

**Comment by lhc70000** [comment]
@anilnatha Please open a new issue so that we can track it. The major problem is that exact seeking can be slow for large files. Maybe we can test if users are OK with it in the next beta version.

**Comment by anilnatha** [comment]
@lhc70000 I will take the action of creating the new issue so it can be tracked later today. I want to test this functionality on my home computer to provide more evidence. I originally this on my work computer.

**Comment by anilnatha** [comment]
@lhc70000 Also, thank you for the quick reply!

**Comment by minhaj6** [comment]
I was facing the exact same problem on windows and this solved my issue (adding the line to input.conf file). Thanks. 

> Please edit the key binding and choose exact seek:
> 
> ![9c3541c0-b064-488a-9f2d-fd7acfe02631](https://user-images.githubusercontent.com/8478049/34937139-a8c1271c-fa1e-11e7-8aa5-d4f39f0b449b.png)
