### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by oskarkrawczyk** [lhc70000/iina#1374]
After updating to `0.15 (64)`:

<img width="451" alt="screen shot 2018-01-15 at 22 25 41" src="https://user-images.githubusercontent.com/34213/34962215-1752e4d0-fa43-11e7-839f-4ffa25343ce9.png">

**Comment by megadr01d** [comment]
This is a common bug in OS X. Try holding <kbd>Option</kbd>, right click on the Finder icon in the Dock and Relaunch. Alternatively, try to logout/reboot or recopy IINA back from the disk image.
