### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by hefangcheng** [lhc70000/iina#1376]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.15

每次打开视频弹出
![image](https://thumbnail10.baidupcs.com/thumbnail/273303c6ad20746abb61a2982b029336?fid=352879694-250528-1107553250071141&time=1516089600&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-xzsblYusVy7J9TdGGlP3SnuBq0g%3d&expires=8h&chkbd=0&chkv=0&dp-logid=363829048644742045&dp-callid=0&size=c1920_u1080&quality=90&vuk=352879694&ft=image)

**Comment by lhc70000** [comment]
@hefangcheng 尝试清除字体间距的设置？

**Comment by hefangcheng** [comment]
谢谢可以了 @lhc70000
