### ISSUE TITLE
Use monospaced fonts for timepos

### ISSUE THREAD

**Issue by SLboat** [lhc70000/iina#1377]
否则它会一直变动滚动条位置-Mac 10.13,中文
![image](https://user-images.githubusercontent.com/4231376/34993971-02b6c544-fb0d-11e7-8e80-95386649d892.png)

**Comment by SLboat** [comment]
Arial不错

**Comment by HarukaMa** [comment]
@SLboat Mac 哪来 Arial……

**Comment by SLboat** [comment]
Mac OS X was the first Mac OS version to include Arial; it was not included in classic Mac OS. The operating system ships with Arial, Arial Black, Arial Narrow, and Arial Rounded MT. However, the default Mac OS X font for sans-serif/Swiss generic font family is Helvetica. The bundling of Arial with Windows and Mac OS X has contributed to it being one of the most widely distributed and used typefaces in the world.

**Comment by SLboat** [comment]
osx开始有的

**Comment by ErikMinekus** [comment]
This was fixed in #1777 and can be closed.
