### ISSUE TITLE
Playback Speed increments too large in recent update?

### ISSUE THREAD

**Issue by mahye82** [lhc70000/iina#1378]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

In previous versions of IINA, I could modify the playback speed fairly precisely with the [ and ] buttons. This is no longer the case, and the most I can do is change speed in large increments using the CMD + [ and CMD + ] buttons. 

**Actual behavior:**

I'd love to see the ability to modify playback speed in smaller steps again.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Current key bindings (as shown in the menu):

<kbd>⌘</kbd><kbd>[</kbd> 0.5x speed
<kbd>⌘</kbd><kbd>]</kbd> 2x speed
<kbd>⌥</kbd><kbd>⌘</kbd><kbd>[</kbd> 0.9091x speed
<kbd>⌥</kbd><kbd>⌘</kbd><kbd>[</kbd> 1.1x speed

Edit them in Preferences if you need.

**Comment by grr** [comment]
The fine-grained control is missing from the menubar. It only shows the options for 0.5x and 2x.

**Comment by marcelbrueckner** [comment]
The default key bindings don't work very well in v0.0.15 build 68.

In order to press the <kbd>[</kbd> or <kbd>]</kbd> keys on macOS you have to press the option button anyway. So the OS can't distinguish between <kbd>⌥</kbd><kbd>⌘</kbd><kbd>[</kbd> and <kbd>⌘</kbd><kbd>[</kbd>.
