### ISSUE TITLE
Black out other monitors in full screen

### ISSUE THREAD

**Issue by stevewillows** [lhc70000/iina#138]
The option to go full screen without blacking out other monitors would be ideal for those of us who do not have independent spaces. 

VLC has this by default.

**Comment by NexusSix** [comment]
Going to Fullscreen still blacks out the other monitor even if preferences option is unchecked.  

Sierra 10.12.3
iina build 29
MacBook Pro (15-inch, Mid 2010) 
NVIDIA GeForce GT 330M 512 MB
Intel HD Graphics 288 MB
mini-display to hdmi
