### ISSUE TITLE
字幕不能从shooter.cn下载

### ISSUE THREAD

**Issue by Zer0xPoint** [lhc70000/iina#1380]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by woyin** [comment]
I have the same problem.

**Comment by lili21** [comment]
http://shooter.cn/

> 射手网不在提供字幕的检索与下载
