### ISSUE TITLE
"Show remaining time" settings toggle doesn't seem to do anything

### ISSUE THREAD

**Issue by GigabitEthernet** [lhc70000/iina#1381]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.15

**Expected behavior:**

Time remaining of content should be shown on On Screen Controller if toggle is ticked, not shown if it is unticked.

**Actual behavior:**

Time remaining is always shown, regardless of toggle.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

Always.

**Comment by lhc70000** [comment]
I can't reproduce this in the latest version. Do you mean the time label in music mode?
