### ISSUE TITLE
播放时画面和声音卡死

### ISSUE THREAD

**Issue by YJMike116** [lhc70000/iina#1382]
我的IINA之前功能一切正常，后来突然有一天开始，打开任何视频、音频文件，都会卡死在某一帧（不仅画面卡死，连声音都是无限循环那一帧的声音，非常鬼畜。具体情形请参见附件中的录屏）。我试过卸载重装，也没起到效果，网上也没找到解决方案，故在此提问。

[IINA播放卡死.zip](https://github.com/lhc70000/iina/files/1639891/IINA.zip)

**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by lhc70000** [comment]
@YJMike116 请附上测试视频。

**Comment by YJMike116** [comment]
@lhc70000  测试视频？不是我附件里的那个录屏吗？我不太懂哦。。

**Comment by lhc70000** [comment]
@YJMike116 你试图播放的那个视频

**Comment by YJMike116** [comment]
@lhc70000 那个视频太大了，传不上来。不过其实我现在播放所有格式的视频和音频都是一样的症状，包括刚才那个录屏文件本身。

**Comment by lhc70000** [comment]
@YJMike116 请
- 尝试在终端里运行 defaults delete com.colliderli.iina
- 尝试删除 ~/Library/Application\ Support/com.colliderli.iina/watch_later 文件夹

**Comment by YJMike116** [comment]
@lhc70000 第一个我已经运行了，但似乎没有反应。
<img width="590" alt="2018-01-18 01 23 19" src="https://user-images.githubusercontent.com/35536317/35056964-68f17098-fbee-11e7-8e7f-521a99aee48e.png">

**Comment by YJMike116** [comment]
第二个，我在Application Support文件夹里没有找到那个子文件夹。。。
<img width="775" alt="2018-01-18 01 24 38" src="https://user-images.githubusercontent.com/35536317/35056980-7b5c9d66-fbee-11e7-851f-39d282b40359.png">

**Comment by YJMike116** [comment]
@lhc70000 第二个，我在Application Support文件夹里没有找到那个子文件夹。。。
<img width="775" alt="2018-01-18 01 24 38" src="https://user-images.githubusercontent.com/35536317/35057011-9b572a96-fbee-11e7-8d2c-8569cf63f667.png">

**Comment by YJMike116** [comment]
@lhc70000 现在问题仍然没有解决。

**Comment by lhc70000** [comment]
@YJMike116 请确认进入的是 ~/Library 即 /User/<username>/Library 而不是 `/Library`。

如果删掉后仍然不行，可以尝试直接删掉 com.colliderli.iina 这个文件夹

**Comment by YJMike116** [comment]
@lhc70000 解决了。万分感谢！

**Comment by fengchenxiujisd** [comment]
> @YJMike116 请
> 
> * 尝试在终端里运行 defaults delete com.colliderli.iina
> * 尝试删除 ~/Library/Application\ Support/com.colliderli.iina/watch_later 文件夹

非常感谢.

**Comment by mcleolee** [comment]
非常感谢！！！解决了许久没有解决的问题
