### ISSUE TITLE
In music mode the window can't be minimized

### ISSUE THREAD

**Issue by fabiospampinato** [lhc70000/iina#1384]
- macOS 10.13.3
- IINA 0.0.15 Build 64

I love music mode, but I can't minimize IINA's window when in this mode, the option under `Window -> Minimize` is grayed out. This completely ruins the experience for me, I don't want IINA always floating around if I'm listening some music.

**Comment by lhc70000** [comment]
Well, you can't minimize an iTunes mini player either. How about Command+H to hide the window?

**Comment by fabiospampinato** [comment]
I didn't think about that 🤔, thanks for the suggestion.

Although I still think that unless there's some particular reason behind this limitation there should be an option for minimizing it, I'm just not used to hiding windows I guess.

**Comment by inflation** [comment]
@fabiospampinato From my suspecting, what you want is closing the window but not quitting the program. iTunes and Spotify support this. Maybe we should add it too? @lhc70000

**Comment by fabiospampinato** [comment]
@inflation I don't really care about _closing_ the window, I just don't want it floating around. A `cmd+h` would hide it, but that hides all of IINA's windows, so it's not exactly the same thing as minimizing it. Also, I never actually think if a window can be minimized or not, I always try to minimize them, and this breaks my workflow a little bit.

**Comment by ldexterldesign** [comment]
Why is this issue closed?

Hope to hear back

Cheers

**Comment by AntonNarkevich** [comment]
This is the reason why I stopped using the app.
It's uncomfortable to switch from mouse to keyboard to simply minimize the window.
And btw this is a primary usecase: play music, hide the window, work on something else.

**Comment by ldexterldesign** [comment]
FYI

I started using MPV and never looked back 🤷

Sorry to bring negative news but hope it helps

Regards
