### ISSUE TITLE
字幕使用某些中文字体会显示成乱码

### ISSUE THREAD

**Issue by liweihao5253** [lhc70000/iina#1391]
System and IINA version:

- macOS 10.13.2
- IINA 0.0.15

当ASS字幕文件中含有用宋体显示的字体样式时，或者是在IINA的设置中把字体设置成宋体-简或华文宋体时，IINA会以乱码的形式显示出来，如图所示：
![2018-01-18 8 32 41](https://user-images.githubusercontent.com/35565160/35099037-7ce26d0c-fc91-11e7-8ead-2004143ca16b.png)
这是在MPV中的正确的显示效果：
![2018-01-18 8 31 59](https://user-images.githubusercontent.com/35565160/35099081-a21fbf8e-fc91-11e7-8287-8cf99884dc39.png)
经过测试
1.无论什么字幕文件，在IINA设置中选择宋体-简或者华文宋体都会显示成乱码；
2.不采用IINA的设置，而使用ass文件内部的设置，无论是“STSong”、还是“宋体-简”、“华文宋体”同样会显示成乱码。
3.其他系统字体均未发现有此问题。
总而言之就是无论通过什么途径、无论采用何种编码方式（UTF-8,UTF-16,GBK都试过了）一旦IINA采用系统自带的华文宋体和宋体-简，都会乱码。而其他的播放器则均不会出现此情况，所以应该不是我的字符集有问题。

希望作者能早日解决，谢谢！

**Comment by lhc70000** [comment]
Duplicate of #436.
