### ISSUE TITLE
Max volume constraint not work for keyboard shortcuts

### ISSUE THREAD

**Issue by w1874** [lhc70000/iina#1393]
虽然在设置中设置了最大音量100，但音量还会不断增加。
看了一下代码，问题貌似出现在Controllers-->PlayerCore.swift-->462行代码

**Comment by Miigon** [comment]
请更清晰地描述你的问题。

<img width="612" alt="2018-01-19 9 48 23" src="https://user-images.githubusercontent.com/16161991/35153770-d401f054-fd62-11e7-82e3-0c8cf7503f29.png">
如果你指的是此处的最大音量的话，此处设置的最大音量只是限制了拖动音量调节滑块的最大音量，并不限制你继续使用上方向键来增加音量。
<img width="110" alt="2018-01-19 9 52 31" src="https://user-images.githubusercontent.com/16161991/35153854-11c570a0-fd63-11e7-8898-8e5bab11c5c2.png">

**Comment by w1874** [comment]
明白了  可能跟我的使用习惯有关吧  总是时不时的按 上方向键  音量也就不断增加了。不好意思😅

**Comment by lhc70000** [comment]
@w1874 不，这个应该跟随设定的，可以算 bug 了。我下一版会改。

**Comment by Miigon** [comment]
!!我居然一直以为是feature

**Comment by damengilland** [comment]
Glad to see so many active users reporting bugs.

![jan-20-2018 23-45-25](https://user-images.githubusercontent.com/1106778/35183527-07e275fe-fe3c-11e7-8ca1-c87925656d9c.gif)
