### ISSUE TITLE
Player doesn't display tags for some of the URLs feeded.

### ISSUE THREAD

**Issue by ptkovsky** [lhc70000/iina#1395]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
Tags are expected to be displayed instantly after playback is started.

**Actual behavior:**
Sometimes, when reading some URLs, player UI refuses to display tags. It can show them sometime afterwards though.

- MPV log:
While it doesn't show the tags in the UI in the case of the first URL listed, it shows them being read correctly here. Maybe this is youtube-dl or other type of issue?
```
[i][display-tags] File tags:
[i][display-tags]  icy-title: blah blah the title goes here
```

**Steps to reproduce:**
Try to open https://somafm.com/spacestation130.pls or http://ice1.somafm.com/spacestation-128-mp3. Tags are not displayed. It can show up once sometime afterwards. Now open, for example, http://185.72.246.9:8000/stream.mp3. Tags are visible here.

- [x] MPV does not have this problem.

**How often does this happen?**
Happens pretty much regularly for me. At least in the above-mentioned cases.

**Comment by ptkovsky** [comment]
Looks like it still doesn't work as of https://github.com/lhc70000/iina/commit/c2ac5de037dc643cac7c7f95f39218124e068a1f. Do you need logs or some other help?

**Comment by lhc70000** [comment]
@ptkovsky Could you provide a url for test?

**Comment by ptkovsky** [comment]
Pretty much any Soma if you ask me, try this for example: http://ice1.somafm.com/spacestation-128-mp3. I've listed it in the opening post.

**Comment by lhc70000** [comment]
![6720cc1b-85b4-4d9e-8d4f-30d8cae4c23b](https://user-images.githubusercontent.com/8478049/35453747-4c2bcc8c-0306-11e8-9ebb-de6c29b7c057.png)

This is what it looks like in my local build.

**Comment by lhc70000** [comment]
You're right, I forgot to update music mode. Thanks for the reminder :)

**Comment by ptkovsky** [comment]
Sure, no problem. Thank you for fixes and fast answers.

**Comment by lhc70000** [comment]
Updated.

**Comment by ptkovsky** [comment]
Fine, works now.
