### ISSUE TITLE
M3U or PLS playlist song title doesn't refresh

### ISSUE THREAD

**Issue by DmitryZemlyuk** [lhc70000/iina#1402]
System and IINA version:
macOS 10.13.2
IINA 0.0.15

Expected behavior:
M3U or PLS playlist(online radio): tiltle on music mode refresh after next song start playing (we can see actual song title).

Actual behavior:
M3U or PLS playlist(online radio): tiltle on music mode doesn't refresh after playing next song (we can't see actual song title).
If we need see actual song title - need to switch to video mode and return to music mode again.

Steps to reproduce:
1. Download playlist https://api.friezy.ru/playlists/m3u/RR128.m3u
2. Open this playlist in IINA
3. Playing any song station - song title doesn't show. If we need to see actual song title - need to switch to video mode and return to music mode again.

**Comment by ptkovsky** [comment]
#1395

**Comment by ptkovsky** [comment]
https://github.com/lhc70000/iina/issues/1395.

**Comment by ptkovsky** [comment]
Also described here: #1395.

**Comment by lhc70000** [comment]
Please follow up at #1395.
