### ISSUE TITLE
1080p video cropping bug

### ISSUE THREAD

**Issue by nashisan** [lhc70000/iina#1403]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.13 or above

**Expected behavior:**
Full resolution playing.

**Actual behavior:**
In version 0.0.13 or above, the bottom 8 lines are cropped when playing a 1920x1080p mp4 video.
Using version 0.0.12, this problem doesn't occur.

Here are mediainfo:
General
Complete name                            : a.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/iso6/avc1/mp41/isom/iso2)
File size                                : 127 MiB
Duration                                 : 4 min 26 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 989 kb/s
Encoded date                             : UTC 2016-05-19 02:38:10
Tagged date                              : UTC 2016-05-19 02:38:10
Writing application                      : Lavf56.40.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 4 min 26 s
Bit rate                                 : 3 792 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.974 FPS
Maximum frame rate                       : 23.981 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.076
Stream size                              : 120 MiB (95%)
Encoded date                             : UTC 2016-05-19 02:38:10
Tagged date                              : UTC 2016-05-19 02:38:10
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 4 min 26 s
Bit rate mode                            : Variable
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 6.10 MiB (5%)
Language                                 : English
Encoded date                             : UTC 2016-05-19 02:38:10
Tagged date                              : UTC 2016-05-19 02:38:10

Sorry, I don't use mpv.

**How often does this happen?**
Every time.

**Comment by NickSharf** [comment]
Confirm that. If I play any video in 1920x1080 it crops 8px from bottom. Attached IINA inspector screen.
![2018-01-22 11 11 06](https://user-images.githubusercontent.com/18418641/35210913-27ea67ce-ff65-11e7-9c3e-d5aeb062821d.png)

**Comment by Miigon** [comment]
Confirmed. 
<img width="458" alt="2018-01-24 4 22 00" src="https://user-images.githubusercontent.com/16161991/35324272-351fdfba-012b-11e8-87c9-3f0635ba21d2.png">
And if I turn off hardware decoding, The problem doesn't exist.
<img width="458" alt="2018-01-24 4 22 17" src="https://user-images.githubusercontent.com/16161991/35324295-4d55484a-012b-11e8-9f99-ec01370ef247.png">
And I've tested the same video with mpv.
It seems that mpv also have this problem because the height of video is equal to IINA's. (hardware decoding enabled)

**Comment by deepsweet** [comment]
My case, mediainfo:

```
Width                                    : 896 pixels
Height                                   : 504 pixels
Display aspect ratio                     : 16:9
```

I can see the height difference between "default" and "16:9" aspect ratio, IINA inspector shows the wrong "896×496". But it's totally fine with disabled hardware decoder, and also there is no difference in VLC between "default" and "16:9" ratios.
