### ISSUE TITLE
通过URL方式播放报错

### ISSUE THREAD

**Issue by f2sky** [lhc70000/iina#1407]
1、IINA 版本：最新 0.0.15
2、OS X 系统：10.11.6
https://ws1.sinaimg.cn/large/006tNc79ly1fnptc8pam1j30zk0m8gmm.jpg

播放在线视频网站情况如下：
1、YouTube、腾讯视频、哔哩哔哩：报错
https://ws4.sinaimg.cn/large/006tNc79ly1fnptb9q5gjj30w20icmy1.jpg

2、爱奇艺：可以播放，但是清晰度不高，而且严重卡顿
3、优酷：正常播放超清，且不卡顿

如果有问题，那应该都不能播放，但是目前的情况是，优酷可以正常播放，但是主流视频网站都有问题，这种情况如下排查？（没有自定义 youtube-dl 路径）

**Comment by inflation** [comment]
查看 log 的 youtube-dl 部分可以看到链接情况。或者直接运行 youtube-dl 看看有什么问题。
