### ISSUE TITLE
On screen controller does not disappear while fullscreen if mouse does not move.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#141]
Reproduce: Use Ctrl+Cmd+F to get into fullscreen and keep the mouse still, then the on screen controller will not disappear.

**Comment by konradbnet** [comment]
Same thing when switching workspaces.

**Comment by alejx** [comment]
I found it will not disappear only if the mouse is still. Only by moving the mouse can trigger `showUIAndUpdateTimer` to setup a timer.
