### ISSUE TITLE
Browser plugin not working: macOS doesn’t recognize Internet addresses starting with “iina:”

### ISSUE THREAD

**Issue by pobyv** [lhc70000/iina#1411]
Browser plugin not working.

**System and IINA version:**

Brand new MacBook

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

IINA opens

**Actual behavior:**

Safari output: `macOS doesn’t recognize Internet addresses starting with “iina:”`

**Steps to reproduce:**

Buy MacBook, install macOS 10.13.2, install IINA 0.0.15, install IINA Safari Plugin, open any website, hit plugin button

**How often does this happen?**

Every time

**Comment by lhc70000** [comment]
Have you launched IINA for at least one time?

**Comment by pobyv** [comment]
Yes, many times. I also rebooted the Mac.

**Comment by pobyv** [comment]
Re-installing IINA did the trick. Whatever…

Thank you for your support and the work on this wonderful video player!
