### ISSUE TITLE
Setting default app not working

### ISSUE THREAD

**Issue by pobyv** [lhc70000/iina#1412]
Setting IINA as default movie player is not working.

**System and IINA version:**

Brand new MacBook

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

Double-clicking video file plays the file in IINA

**Actual behavior for mkv files:**

Finder output: `There is no application set to open the document “movie.mkv”`

**Actual behavior for mp4 files:**

QuickTimePlayer plays the file

**Steps to reproduce:**

Buy MacBook, install macOS 10.13.2, install IINA 0.0.15, select mkv or mp4 in Finder, hit Cmd-I, select IINA.app in “Open with:” “Other”, click ”Change All…”, double-click mkv or mp4

**How often does this happen?**

Every time

**Comment by lhc70000** [comment]
It's not IINA's problem.

IINA provides a function to set itself as the default player for most media types in the Help menu, perhaps you can have a try on that.

**Comment by lhc70000** [comment]
Have you installed IINA in your /Applications folder?

If so, there should be something wrong with your macOS.

**Comment by pobyv** [comment]
Yes, I downloaded the compiled version of IINA from https://lhc70000.github.io/iina/ (not Homebrew) and copied it to the /Applications folder on a brand new freshly installed High Sierra. As it is untouched I would wonder what is wrong with my macOS.

**Comment by pobyv** [comment]
Re-installing IINA did the trick. Whatever…

Thank you for your support and the work on this wonderful video player!
