### ISSUE TITLE
Feature request: Always Start Video in 'Fit to Screen'

### ISSUE THREAD

**Issue by Demasterpl** [lhc70000/iina#1413]
I have not seen this option but this is can be very useful when playing a series of videos in a folder, especially with different video resolutions and aspect ratios.

Right now the video size and playback size ALWAYS resets when opening up the next file or even the first file when the application launches. Therefore I ALWAYS have to set "Fit to Screen" for every video I play.

It gets very annoying after awhile :(

**Comment by lhc70000** [comment]
> Right now the video size and playback size ALWAYS resets when opening up the next file or even the first file when the application launches.

This should not happen. If you are on macOS 10.13.1 or lower, please upgrade your system since it's a macOS bug.

**Comment by Demasterpl** [comment]
I am using 10.13.2, Sorry I did not make that clear beforehand.

I can try doing a full reinstall, but right now if the resolution or aspect ratio is different from the current video it always resizes itself :(

**Comment by Demasterpl** [comment]
This no longer seems to be an issue with the preference of UI -> Window (Section) -> "Resize the window to fit video size". Thank you!
