### ISSUE TITLE
About function "Always Top"

### ISSUE THREAD

**Issue by TIL-MICE** [lhc70000/iina#1414]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- MPV log:
```
NONE
```
Hi, I really like this player, but i want it can always on Top whatever paused or playing. not just while playing, cause sometimes i need pause to see the content on the video, but my screen ... So Could you please add this function, it may more helpful.
i know it's not that difficult for you right? 

By the way , you say " Please use English, if possible" , actually, i wanna use Chinese...cry

At last ,Thanks a lot !

**Comment by saagarjha** [comment]
Have you tried picture-in-picture? You can access it by pressing <kbd>⇧</kbd>+<kbd>⌘</kbd>+<kbd>P</kbd>, or from the Video menu.

> By the way , you say " Please use English, if possible" , actually, i wanna use Chinese...cry

You're welcome to use Chinese, but please add English as well so I can understand you ;)

**Comment by TIL-MICE** [comment]
yes ,i tried picture-in-picture, but it just 1/4 of my screen, and can't bigger anymore, i need 1/2 or 2/3, then i can write sth properly, i use it to coding while i'm watching video(about coding),So if it just 1/4,i can't see clearly, cause code is too small... i hope you can understand,Thanks
this is screen capture
![image](https://user-images.githubusercontent.com/20478881/35317616-8b97ed9c-0112-11e8-9ebe-e974b32f008e.png)

**Comment by saagarjha** [comment]
How about the setting "Always float on top while playing" under the UI section of Preferences?

**Comment by TIL-MICE** [comment]
i'm sorry maybe it not enough, you know, sometimes need pause to coding ,  that why i give this issue,  i gauss "always on top while playing" and "always on top while paused" are similar way, so if it not that difficult you can add this, let user choose what they want will be a good way，On Windows most Video player will give this option , Maybe it's more easy to realize on Win Platform

For me IINA is perfect, simple, beauty. except this. i tried "mySIMBL + Afloat",but it will make Finder crash, and i know the people need this function not just me, if IINA can make it, it will be more perfect.

Thanks.

that's different, 
![image](https://user-images.githubusercontent.com/20478881/35325066-a30fd834-012d-11e8-8d9b-eb6948673526.png)
...you don't wanna see working/learning like this...  cry...
![image](https://user-images.githubusercontent.com/20478881/35325080-af0246a4-012d-11e8-8c27-dfbb58a718e8.png)

**Comment by saagarjha** [comment]
> i'm sorry maybe it not enough, you know, sometimes need pause to coding , that why i give this issue, i guess "always on top while playing" and "always on top while paused" are similar way

So what function are you looking for that IINA does not currently provide?

> i tried "mySIMBL + Afloat",but it will make Finder crash

Not for me…
<img width="301" alt="screen shot 2018-01-24 at 19 14 54" src="https://user-images.githubusercontent.com/13786931/35369081-381d72c6-013b-11e8-991a-5b342eb36ba2.png">

**Comment by TIL-MICE** [comment]
Need Always Top while paused.

maybe, just Not now, i used for one month, then  finder permanently "not responding"  just like that: https://github.com/millenomi/afloat/issues/20

if you know how to solve it ,you can tel me, and last time i solved it by reinstalled my MacOS

**Comment by saagarjha** [comment]
> Need Always Top while paused.

Just curious, why would you want this? You want to *hide* the window when it's playing but see it when it's paused?

> maybe, just Not now, i used for one month, then finder permanently "not responding" just like that

What was Finder doing when this occurred?

**Comment by TIL-MICE** [comment]
sorry , i forget to check my E-mail, 
maybe you are not understand 😅 ,i just want Always Top, whatever it's playing or paused.
not 
` hide the window when it's playing but see it when it's paused`
and the second question...
i forgot. cause it occurred while i'm login. and whatever you do, like shutdown / restart / restart Finder .etc ,it's just No response, Not just Finder and is Every App you have installed is “No response”.
Delete Afloat it will be ok. but can't use it anymore... when you try to open this plugin again, this problem will recurrent.. 
😕
