### ISSUE TITLE
建议通过快捷键调整播放速度的步长调整为0.1X

### ISSUE THREAD

**Issue by gontthias** [lhc70000/iina#1419]
com+] 快捷键直接将速度由1X变为了2X，非常不方便使用，因为正常看视频，速度在1.2-1.5X，再快就听不清了。建议将加快播放速度的步长由2倍变为增加0.1X。
而通过com+v 来调节速度操作上太慢，不方便。
请接受此建议。

**Comment by lhc70000** [comment]
- option+cmd+] 是 1.1x
- 你可以在偏好设置中自定义快捷键

**Comment by gontthias** [comment]
感谢解答，研究了下，快捷键确实有很多套预设的方案，功能非常强大。

**Comment by linzhiqun** [comment]
可以在“偏好设置”里面设置调整快捷键。
偏好设置->快捷键->复制配置文件->选中复制的配置文件调整相应的键位和命令。
建议将加速、减速命令修改为：add speed 0.1  和 add speed -0.1 。
与之对应的快捷键设置为单键 “[” 和 “]”。
这两单键没有被其他快捷键占用，且单键会比组合键更方便使用。

**Comment by IITII** [comment]
虽然通过设置达到了想要的结果，但是还是想提议：
* 如果可以的话，将默认的 `Meta + [`, `Meta + ]` 快捷键的加速和减速效果设置为 `+0.1`, `-0.1`（或者 ±0.2）。因为这样的话更符合一般人的加减速要求。
* 现在版本（IINA 1.1.2 Build 128）的默认值是 `x2`, `x0.5`, 播放速度变动非常大（指数级别），并不符合一般人的播放速度要求。因为大部分人都希望软件开箱即用，而不是设置一堆东西(麻烦 + 学习成本)。这样的话导致部分用户觉得 _软件/播放速度的调整的这部分功能_ 不好用。进而导致部分用户流失。

**Comment by LittleNewton** [comment]
IINA的快捷键在哪里启用呢？我复制了一个自带的配置文件，但是没找到对应的启用入口。
