### ISSUE TITLE
Progress bar does not start from 0.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#142]
<img width="117" alt="screen shot 2017-01-11 at 4 00 46 pm" src="https://cloud.githubusercontent.com/assets/20237141/21871485/3ee5bed6-d817-11e6-955f-d39e1c8de50e.png">
Put the mouse close enough to the left point of the progress bar, then you will see something like '0:0-1'.

**Comment by saagarjha** [comment]
This issue also happens when scrubbing using a "horizontal scroll" guesture.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
