### ISSUE TITLE
please support m3u8

### ISSUE THREAD

**Issue by yingxincui** [lhc70000/iina#1420]
please support m3u8
thanks！

**Comment by lhc70000** [comment]
Doesn't it already support m3u8?

**Comment by yingxincui** [comment]
try this https://bi.xunleimp4.com/files/51/list.m3u8

**Comment by lhc70000** [comment]
![967693e5-8c26-4296-8fa1-730af6650b5a](https://user-images.githubusercontent.com/8478049/35382712-0a06bb2a-01fb-11e8-95ba-03c3948987dd.png)

Is there any problem?

**Comment by blaqkr** [comment]
why are you sharing **porn** in here?

**Comment by lhc70000** [comment]
@blaqkr What the heck, I'm not aware of that……

@yingxincui Closing, as it plays the url with no problem.

**Comment by blaqkr** [comment]
@lhc70000 that playlist is a porn video, and it's against the rules

> **Sexually obscene content** - Basically, don't post pornography...
