### ISSUE TITLE
打开在线视频观看，再浏览网页，发现网页卡顿

### ISSUE THREAD

**Issue by qiuzhu** [lhc70000/iina#1421]
再Chrome 下，在线播放视频后，同时浏览网页，发现网页浏览很卡，滚动鼠标看网页内容，明显卡顿，不知道是不是个例。

**Comment by lhc70000** [comment]
@qiuzhu 这和 iina 没有关系。

**Comment by qiuzhu** [comment]
谢谢回复，难道是因为我是黑苹果的原因？我是在inna中打开YouTube的视频，同时浏览网页，发现网页滚动鼠标卡顿，同时看见Chrome里面的视频也开始卡，关闭inna在线播放后，就好了，不知道是什么原因

**Comment by inflation** [comment]
可能显卡驱动调用 OpenGL 出了问题

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
