### ISSUE TITLE
Show Album Art in "now playing" Notification widget 

### ISSUE THREAD

**Issue by fabi94music** [lhc70000/iina#1426]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Expected behavior:**

Show album art of songs in the now playing notification centre widget. 

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
every time

**Comment by lhc70000** [comment]
Duplicated with #1397.
