### ISSUE TITLE
Some German Localisation Flaws

### ISSUE THREAD

**Issue by ksaerdna** [lhc70000/iina#1427]
In "Preferences/General":

- "Wiedergabe wenn ..." must be "Wiedergabe, wenn ..." (twice in the dialogue)
- "Dateien im gleichen Ordner ..." must be "Dateien im selben Ordner ..."

Note that "the same" is either "das gleiche" (a similar specimen of same type) oder "dasselbe" (the very same specimen, i.e. there is only one object) in German. Note also that in low level German many people cannot distinguish, if they e.g. have two cars of the same type or share one car with somebody else.

In main menu:

- "Nach Updates suchen" should be "Nach Aktualisierungen suchen" or better "Nach neuer Version suchen" or "Auf neue Version prüfen". In best case this should match the dialogue "Preferences/General", where the update check interval can be configured. Here the German translation „Auf Aktualisierungen prüfen“ is very nice.

Note that "Updates" is low level German and typical Microsoft slang ("download updates" becomes "Updates downloden" in Windows, which is really ugly).

**Comment by lhc70000** [comment]
Thanks, you can open a pull request directly, or I can help you do the commit. But before that, perhaps you need to discuss it with German translators: @J-rg and @sgoehre.

**Comment by sgoehre** [comment]
He is right and those strings are among the things I want to fix before the next release. I didn’t get around to it yet, however. I’ll add it do my to-do list. :-) Do I have a deadline?

Offtopic
=======
Just a quick note to Andreas: You are right - just your explanations aren’t entirely. 😉 

What you mean is slang or informal German. There’s no such thing as low level German except in foreign language acquisition.

The use of the loanword „Update“, however, is something entirely different. That’s called mixing and is a totally normal process (and happened before in the German language, especially with Latin and French). The word has been part in the German lexis for over 20 years now (since 1996 to be exact, according to the Duden). So it’s become an official (technical) term and is widely used. However, in the Apple world your suggested translation is more common and should as such be adopted.

**Comment by J-rg** [comment]
Great job spotting those errors. One objection though: I wouldn’t consider „Update“ to be low register, it’s merely an Anglicism. Apple changed terminology a while ago and now uses „Updates“ in both App Store and System Preferences, so I think we should go with consistency here.

**Comment by sgoehre** [comment]
Ughh. J-rg is right. While „Aktualisierungen“ seems to be used by most apps, Apple doesn’t anymore. My bad.

**Comment by ksaerdna** [comment]
Just for fun:

 

 

English:


 

Visit the download page and download the downloads, watch the download and finally find the downloads in your download folder.

 

DUDEN:

 

Besuche die Downloadseite und downloade die Downloads, überwache den Download und finde final die Downloads in Deinen Downloads.

 

Me:

 

Besuchen Sie die Seite mit den angebotenen Dateien, laden Sie sie herunter, und beobachten Sie den Ladefortschritt, bis die Dateien schließlich im "Download"-Ordner auf Ihrem Rechner liegen.

 

:-)

 

 

By the way: DUDEN, the „Microsoft” among German dictionaries, are just commercial books, they do not set any official standard, and they include a lot of grammatical idiocy, nonsense and unnecessary self invented words or variants for whatever reasons. As quasi-monopolist they also sell spelling check programs causing people to write DUDEN dialect instead of what formerly has been standard. And last not least, books like these must always be political correct, therefore they use euphemisms like "colloquial", while "slang" or "used by lower educated people" would be the more honest phrasing.

 

The excessive usage of redundant anglicisms (and also of the German genitive case) is such a "slang", especially used by managers and marketing, for swagger and simulating cosmopolitanism and competence, while in fact these people are losing control over their native language. And finally: The English of Denglish speaking Germans is usually awful either.  :-)

**Comment by whoinoi** [comment]
On that note, there are still two untranslated parts:

1. When opening a stream (like a YT URL):

<img width="707" alt="a" src="https://user-images.githubusercontent.com/10744641/34954744-e0b16a58-fa21-11e7-9188-7be2a6951bf8.png">

2. The loading window of a stream

<img width="1072" alt="b" src="https://user-images.githubusercontent.com/10744641/34954706-c4789244-fa21-11e7-903b-0a0bceef9dca.png">

**Comment by ksaerdna** [comment]
The German string "Benutze unsere ..." is too long and gets truncated.

Maybe abbreviate it like "Internetseite über unsere Browser-Erweiterung öffnen" or "Website über unsere ..."

Note that in fact "Seite" is a wrong translation of "site". Correct would be "Ort". So maybe "Website" could be left in English.

 

Maybe it's not good style to concatenate English "Browser" with German "Erweiterung".

Better separate it with a hyphen ("-").

When reading those "mixed words", the pronunciation must suddenly change inside the word,

and "Browserer" might be read as English, followed by a sudden "weiterung".

 

The waiting animation in the stream window could be translated as "Stream wird geöffnet...". Note that there is a perfectly matching word for "Stream" in German („Video-Datenstrom“), but that is not commonly used and might look strange. Any other opinions?


 

 


Gesendet: Freitag, 02. Februar 2018 um 23:17 Uhr
Von: whoinoi <notifications@github.com>
An: lhc70000/iina <iina@noreply.github.com>
Cc: ksaerdna <Andreas.Kromke@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [lhc70000/iina] Some German Localisation Flaws (#1427)


On that note, there are still two untranslated parts:


	When opening a stream (like a YT URL):





	The loading window of a stream

**Comment by whoinoi** [comment]
@ksaerdna I like your suggestions in general.

But maybe I should add that it isn't neccessary to be so rigid and strict about the tranlsations. You seem to invest a lot of time in something that isn't that important... For example really no German cares wheter one writes "selbe" or "gleiche". If you're translating some bigger software like an operating system or so then its maybe worth thinking about the exact way of saying something. But for this project I think it suffices if the translation deliveres the correct meaning to the user which it does already (except for the cutoff and missing parts obviously), since it was translated by a German native.

**Comment by J-rg** [comment]
> Note that in fact "Seite" is a wrong translation of "site". Correct would be "Ort". So maybe "Website" could be left in English.

Not quite right. It's a perfectly correct translation of "web**page**".
Personally, I wouldn't change the expression, as I think "Website" mostly refers to the web presence as a whole, not to an individual page. 

The clipping can easily be dealt with by changing some constraints in the corresponding .xib file, there's more than enough white space:
![openurl](https://user-images.githubusercontent.com/4042863/35784396-4b52fa5c-0a17-11e8-9f2c-99f2583ff2a2.png)

Btw, I already made the "Open stream…" string and some other missing strings localiseable a while ago: [link](https://github.com/J-rg/iina/commit/2d05ed9711216002fc80aa0e99d98d56aaedc60e).
If desired, I could rebase the branch and open a pull request.

**Comment by J-rg** [comment]
> Note that in fact "Seite" is a wrong translation of "site". Correct would be "Ort". So maybe "Website" could be left in English.

Not quite right. It's a perfectly correct translation of "web**page**".
Personally, I wouldn't change the expression, as I think "Website" mostly refers to the web presence as a whole, not to an individual page. 

The clipping can easily be dealt with by changing some constraints in the corresponding .xib file, there's more than enough white space:
![openurl](https://user-images.githubusercontent.com/4042863/35784396-4b52fa5c-0a17-11e8-9f2c-99f2583ff2a2.png)

Btw, I already made the "Open stream…" string and some other missing strings localisable a while ago: [link](https://github.com/J-rg/iina/commits/localization). If desired, I could rebase the branch and open a pull request.

**Comment by ksaerdna** [comment]
>Not quite right. It's a perfectly correct translation of "webpage".

 

You are right, I was wrong. I did not think about that.

 

> The clipping can easily be dealt with by changing some constraints in the corresponding .xib file, there's more than enough white space:
 

great

 

> Personally, I wouldn't change the expression, as I think "Website" mostly refers to the web presence as a whole, not to an individual page.

 

Yes, I agree, I was totally wrong in this context.

**Comment by ksaerdna** [comment]
>For example really no German cares wheter one writes "selbe" or "gleiche".

 

Really no one? So people who do cannot be Germans in your opinion? How can you know?

For examples just refer to:

 

 


http://www.spiegel.de/kultur/zwiebelfisch/zwiebelfisch-abc-dasselbe-das-gleiche-a-311593.html

http://www.selbe-gleiche.de/

http://www.giga.de/extra/ratgeber/specials/dasselbe-das-gleiche-definition-unterschied-beispiele-und-eselsbruecken/

https://deutsch.lingolia.com/de/wortschatz/verwechselbar/derselbe-gleiche

https://praxistipps.chip.de/das-gleiche-oder-dasselbe-wo-liegt-der-unterschied_95839

https://german.stackexchange.com/questions/33395/das-gleiche-oder-dasselbe

 

This is my favourite link, a very good video („Die Sendung mit der Maus”), especially for children:

https://www.youtube.com/watch?v=hePMxBhJK3E

**Comment by fabi94music** [comment]
![bildschirmfoto 2018-03-21 um 12 22 18](https://user-images.githubusercontent.com/29753374/37707178-87dbea34-2d02-11e8-8a48-8775a458a058.jpg)
I think it shouldn't say <Leer>. The English version says <None> so a better translation would be "<Keine>"

**Comment by sgoehre** [comment]
@fabi94music, could you please elaborate? I think parts of your sentence is missing and I don’t know what I’m supposed to see here.

**Comment by fabi94music** [comment]
@sgoehre sorry, I corrected that :)

**Comment by sgoehre** [comment]
@fabi94music makes sense now. Thanks! :)

Let’s see what @J-rg has to say about it but I think you’re right.

**Comment by fabi94music** [comment]
@sgoehre @J-rg 
The same applies to the video tracks and subtitles.

**Comment by alejx** [comment]
Can I close this?

**Comment by sgoehre** [comment]
Last time I checked, not everything mentioned here was fixed yet. I’ll check again today and let you know.
