### ISSUE TITLE
怎么设置音频规格化？

### ISSUE THREAD

**Issue by cv0cv0** [lhc70000/iina#1428]
看电影要么声音太小，要么太大。一惊一乍。potplayer这个功能默认是开启的。IINA找了一圈没找到在哪设置。

**Comment by lhc70000** [comment]
添加音频滤镜 `loudnorm` 试试？

**Comment by cv0cv0** [comment]
@lhc70000 让填写滤镜名和滤镜字符串。

**Comment by lhc70000** [comment]
@cv0cv0 滤镜名 `loudnorm`，字符串为空

**Comment by cv0cv0** [comment]
@lhc70000 请检查你的参数格式。

**Comment by lhc70000** [comment]
我发现这个 bug 还没修……估计没人试着加过音频滤镜……

感谢提醒。

**Comment by lhc70000** [comment]
@cv0cv0 请问你可以上 Google Drive 么？平常使用什么文件分享工具？

**Comment by cv0cv0** [comment]
@lhc70000 可以。

**Comment by lhc70000** [comment]
@cv0cv0 这个 build 应该可以了。

https://drive.google.com/file/d/1bEW4CDwIkJ4N2tyGrF_jyuw3rMfMp9Gk/view?usp=sharing

**Comment by cv0cv0** [comment]
@lhc70000 Thank you.

**Comment by cv0cv0** [comment]
@lhc70000 可以了，并且生效了。非常感谢。
