### ISSUE TITLE
(snow) crash

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1429]
https://pastebin.com/r1N6Lyc8

I had a video paused for a while, minimized. Closed the macbook lid, next day, open it and I see iina has quit unexpectedly. Thanks.

**Comment by inflation** [comment]
You just hit by a bug of the system, since the log shows no evidence of IINA causing it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
