### ISSUE TITLE
How to adjust subtitles font style?

### ISSUE THREAD

**Issue by jet10000** [lhc70000/iina#143]
How to adjust subtitles font style?

**Comment by lhc70000** [comment]
1. You may open subtitle settings panel from "Subtitles->Quick Settings Panel" (Cmd+S). There's a "Font..." button under "Text Style".

2. In preference, you can also set the subtitle styles in "Subtitles".

3. In the settings panel, if the "Font..." button is disabled at runtime, it means that your current subtitle is image (like some DVDs) or have built-in styles (like ASS). You can force override ASS styles by enabling "Ignore all ASS styles".
