### ISSUE TITLE
Could you please register to Mac App Store?

### ISSUE THREAD

**Issue by laelbe** [lhc70000/iina#1434]
Recently, I discovered this software.

I can't use this software before. Because I don't know that this APP exists.
Many people like me need this software!
Many users can easily find this APP if it is in Mac App Store!

**Comment by saagarjha** [comment]
The App Store and GPL are fundamentally incompatible, which means that as it currently stands IINA cannot be on the App Store. See #420 for more details.

**Comment by lhc70000** [comment]
@saagarjha Actually, recently I'm considering the possibility of releasing a MAS version especially when there's still no response from Apple for the recent license violation case after three weeks.

To do so, we have two options:

- I, after getting permission of all existing and future contributors, prepare a MAS version and release the source code of the MAS version under a special license that is compatible with the MAS. No other usage of the code under this license is permitted. I prefer this option.
- Changing the license of IINA from GPL to a looser one. This will also need an agreement from all contributors.

cc @alejx @HarukaMa @inflation

**Comment by HarukaMa** [comment]
@lhc70000 I'd prefer dual license.

**Comment by saagarjha** [comment]
I would also prefer a dual license, but doing something like this can be tricky: you'd need to get permission from *all* contributors, and make new contributors give up the rights to their code with some sort of CLA. If this is the route we want to go down, we'll need to be very careful about it.

**Comment by PCheezo** [comment]
MAS isnt worth it

**Comment by saagarjha** [comment]
Why do you think so?

**Comment by laelbe** [comment]
AppStore
1) AppStore -> search "IINA"
2) IINA -> download -> open

Github
1) Google -> type "github"
2) Github -> type "iina" -> Search
3) IINA -> find "release" button
4) Release -> find recent "dmg" -> Save to Desktop
5) Click downloaded file -> When window open, Drag APP icon to APP Folder.
6) Open Launchpad, Find IINA, Click

I believe, over 90% of Mac users are not familiar with github.
They don't know how to download APP. (The download button in the frontpage of the github project makes user to download the master branch source code.)
The Mac App Store version is needed for this people.

If this APP is such development kit, it's okay to stay in Github. 
But IINA is general purpose media player.

**Comment by lhc70000** [comment]
You can download IINA from its website (the first result when you search IINA in Google; and we'll move to iina.io shortly). But anyway, it's better to have a MAS version, although we must cut some features off in the MAS version (for example, Picture-in-Picturem, as It's a private API).

**Comment by xu-cheng** [comment]
Just FYI. A MAS version of the IINA will require compatible licences for all the dependencies. Specially, you will have to build mpv with `--enable-lgpl` flag. [Ref: <https://github.com/mpv-player/mpv#license>].  In this case, some functions of the mpv may be missing.

**Comment by jerkstore369** [comment]
ya, screw the App store. I don't really think it's necessary.

**Comment by megadr01d** [comment]
> They don't know how to download APP

> You can download IINA from its website

Exactly. For decades we have been searching software in a search engine, go to the developers website, check the description and screenshots, find the download tab/button and download it.
App stores were created to dumbify and control both  users and developers.

Also, like any other Mac app, you only need to download it once and then update it through the app itself.

https://lhc70000.github.io/iina/

**Comment by saagarjha** [comment]
> For decades we have been searching software in a search engine or app directory like MacUpdate, go to the developers website, check the description and screenshots, find the download tab/button and download it.

You're ignoring the fact that a significant portion of users today have *never* had to do this, ever. They might not have even used a computer before, so such a process would be challenging for them to follow. I'm not disagreeing that the Mac App Store isn't a pain to support, but I think we should put a version of IINA on it, not only to prevent people from downloading knockoff versions, but also to serve people who (by choice, or because they don't want to install random software from the internet) use the App Store for installing their software.

**Comment by whoinoi** [comment]
Software can be burried in MAS too. The key to success is not MAS, but to get IINA known. VLC isn't on the MAS either and is successful. MAS will only give you more headaches and restrictions. Don't go down that path, please!

If you want to get IINA known, you could try to get some major Mac news sites to write an article about you. I think that would help the most, and that's actually also the way I found IINA back then.

**Comment by saagarjha** [comment]
The purpose of putting it on the App Store isn't to provide better advertising or increasing the reach of IINA; rather, it's to provide a pathway for less technical users to obtain a valid copy rather than being scammed by one of these clones. Don't worry, we wont be "dumbing down" the non-Mac App Store version; we'll just disable features for those builds so it passes App Store review.

**Comment by fabi94music** [comment]
So will there be a MAS version or did you decide not to consider releasing on ?

**Comment by inflation** [comment]
>So will there be a MAS version or did you decide not to consider releasing on ?

@fabi94music Our code is currently under GPL. An old FSF [post](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement) points out there is a conflict between Apple’s term and GPL’s statement. We need to sort those things out before putting on MAS. However, we are not dropping the idea and may return to it when the project is more stable. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cseelus** [comment]
Thanks for the detailed answers on the problems of releasing to the MAS. And above all, thanks for this great piece of software, I'm really in awe about the nice implementation and that even things like Force Touch are supported.

I'm a developer and consider myself to be an adept computer user, but it was more of a coincidence to find an article about IINA on the website of a German news outlet, when I searched for a VLC alternative.

I think despite all the downsides the App Store has, it is still a fast way to discover new Apps, I guess for many not so savvy Users the one and only way nowadays.
For me its also useful to have most of my important apps there, ready to install from the "Purchased" page, for example when I install a new machine from scratch. Of course its also great to have all those apps up to date automatically and not having to worry about malware.

Not being present in the App Store might also invite shady people from taking IINAs source and releasing a copycat version there.

**Comment by bigplayer-ai** [comment]
Hey,
any updates on this? can you make IINA App Store application? Many users prefer sand boxed applications...
