### ISSUE TITLE
online subtitle provider shooter.cn seems obsolete

### ISSUE THREAD

**Issue by cubefoo** [lhc70000/iina#1448]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Online Subtitles:**
Download subtitles from: Shooter.cn

The provider shooter.cn seems obsolete.
Here's a quote from their website (via google translate from chinese):

> Shooter Network will no longer provide subtitles search and download

**Comment by lhc70000** [comment]
Duplicated with #1380
