### ISSUE TITLE
symlink  location

### ISSUE THREAD

**Issue by Mike-BITW** [lhc70000/iina#1449]
Possible error in the latest release notes. The correct command to create a symlink on MacOS (10.3.x) is probably:

**ln -s /Applications/IINA.app/Contents/MacOS/iina-cli  /usr/local/bin/iina**

**Comment by lhc70000** [comment]
You can link it to anywhere as long as it's in your `PATH`. `~/bin` is just a personal preference.

**Comment by Mike-BITW** [comment]
Understood.  I was just suggesting the location Apple guidelines seem to recommend. Since "~/bin" doesn't exist by default, it might trip some users.

**Comment by inflation** [comment]
Beware if you’re using Homebrew, it is not recommended to put you own programs in `/usr/local/bin`. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HarukaMa** [comment]
@inflation Is cask able to symlink it then?

**Comment by inflation** [comment]
@HarukaMa Yes, Atom seems creating a symlink. But I’m not sure if that considered as “controlled” by homebrew. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mike-BITW** [comment]
No problems here at all when using /usr/bin for symlinks (whether coming from homebrew, cask, or anything else).  In fact, that directory is almost entirely symlinks and makes life easier if you have it ahead of /usr/bin in your (short!) PATH.

**Comment by HarukaMa** [comment]
@Mike-BITW I think /usr/bin is protected by SIP though...

**Comment by Mike-BITW** [comment]
No clue, I never use SIP.  Manzana Libre! ;)

**Comment by saagarjha** [comment]
> Beware if you’re using Homebrew, it is not recommended to put you own programs in `/usr/local/bin`.

Why not? Homebrew doesn't own this directory, does it?

**Comment by inflation** [comment]
@saagarjha Well, you can do whatever you want to the folder, if you don’t mind manually managing links (and ugly warnings from `brew doctor` 😉). The recommended way on the FAQs is put it under your folder in `/usr/local/Cellar` and `brew link` it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saagarjha** [comment]
You're free to add things to `/usr/local/bin` and `brew doctor` will not complain about it. It's `/usr/local/lib` that you need to care about.
