### ISSUE TITLE
Automatically generate subtitles

### ISSUE THREAD

**Issue by yingxincui** [lhc70000/iina#1453]
Automatically generate subtitles
Use voice to text technology, you can also add translation。
like youtube did

<img src='https://wx3.sinaimg.cn/mw690/8a50c142gy1fo4hf4wlhwj208q05mmz8.jpg'>

can use some api
https://github.com/agermanidis/autosub

**Comment by yingxincui** [comment]
fyi
https://github.com/agermanidis/autosub

**Comment by saagarjha** [comment]
Parsing speech is a difficult problem, and is significantly out of the scope of IINA.

**Comment by saagarjha** [comment]
The project your posted relies on the Google Cloud Speech API, which unfortunately costs money to use.

**Comment by sidneys** [comment]
@yingxincui 

You can already watch the YouTube subtitles and automated closed captions within IINA, if that's any help – by using this `youtube-dl` configuration:

`format="bestvideo[ext=mp4]+bestaudio[ext=m4a]/22/18",sub-lang="en,fr",write-sub=,write-auto-sub=,convert-subs="srt",embed-subs=`

Just replace `en,fr`with languages of your choice.

**Comment by Willian-Zhang** [comment]
might be a good time to review this feature request, Chrome [just *](https://blog.google/products/chrome/live-caption-chrome/) did add [on-device transcription capability](https://support.google.com/chrome/answer/10538231?hl=en).

AFAIK, It wouldn't be very resource consuming on a device with dedicated AI accl device or GPU (All Apple Silicon Macs). Please do check out TTS section in [here](https://github.com/alexsosn/iOS_ML#tts) if new to ML.

**Comment by ebraminio** [comment]
Might be possible to take advantage of the brand-new FFmpeg Whisper filter for IINA https://news.ycombinator.com/item?id=44886647
