### ISSUE TITLE
Added playlist always sorts to alphabetical

### ISSUE THREAD

**Issue by Verloc100** [lhc70000/iina#1457]
**System and IINA version:**

System and IINA version:

macOS 10.13.3
IINA 0.0.15 build 68, mpv 0.27.0
Actual behavior:

Currently, when dragging to IINA playlist or window, it automatically re-sorts to alphabetical order.

Expected behavior:

Previously the order of the playlist that was added was maintained. This is logical, as you can always re-sort to alphabetical before adding, if that is what you require. I sometimes prefer the playlist to be sorted by size, date etc. It seems the option to do this has been lost since the move from 0.0.14

**Comment by inflation** [comment]
We sort the playlist in order to solve some other issues. You can save your manually sorted playlist to a file and open that instead. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Verloc100** [comment]
Are there any plans to revert to the previous behaviour once these issues are solved? Re-sorting to alphabetical would seem to defeat the whole purpose of a playlist (one in the order that you choose!).

**Comment by Verloc100** [comment]
No answer? Should I make a Feature Request? 

Version 0.0.14 is the last version where the playlist behaviour worked correctly.
