### ISSUE TITLE
Touch Bar can't customized the function to each button

### ISSUE THREAD

**Issue by GUOBAODACAI** [lhc70000/iina#1458]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
New versions after 0.0.14.1 can't use the "that two double triangle buttons with the pause button in middle" to seek forward of back. They can only play the next or forward video. I can't customize them. please fix it

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
- It's not "Touch Bar".
- This setting is now moved to Preferences - UI.
