### ISSUE TITLE
Background color of Exit Fullscreen button in Touch Bar does not match other buttons

### ISSUE THREAD

**Issue by ErikMinekus** [lhc70000/iina#1464]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 build 68

**Expected behavior:**
The background color of the Exit Fullscreen button should match the other buttons.

**Actual behavior:**
The background color of the Exit Fullscreen button is ```rgb(68,68,68)```, while the other buttons are ```rgb(54,54,54)```:

![](https://puu.sh/zjnwy/0409fb8509.png)

**Steps to reproduce:**
Open a video, enter fullscreen and look at the Touch Bar.

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
This is a system API (replace the esc button with a custom touch bar item) and I believe that it's a system default behavior.

**Comment by ErikMinekus** [comment]
That's strange, as the default esc button does have the correct color.

**Comment by lhc70000** [comment]
@ErikMinekus Quick Time also has the same behavior.
