### ISSUE TITLE
Open URL from Youtube can't choose quality, default is 4K?Best?

### ISSUE THREAD

**Issue by shankesgk2** [lhc70000/iina#1465]
### Open URL from Youtube can't choose quality, default is 4K?Best?
- macOS 10.12.6
- IINA 0.0.15
![2018-02-09 12 16 53-min](https://user-images.githubusercontent.com/8123290/35984503-8b1378a4-0d2f-11e8-8d80-0edeed87e2ac.png)

**Comment by inflation** [comment]
Yes, `youtube-dl` in `mpv` chooses the best video quality by default. You can modify the behavior by proving additional options to it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
