### ISSUE TITLE
xviD Playback freezes

### ISSUE THREAD

**Issue by DV1X3R** [lhc70000/iina#1471]
- Macbook Pro 2017
- macOS 10.13.2
- IINA 0.0.15

Video playback for every .avi file encoded with xviD codec periodically (once per 1-2 minutes) freezes for 1 second. Audio playback is fine.
Everything seems to be normal with h264 .mkv files.
However, I can not reproduce this issue with INNA 0.0.14

Video files specification: 
AVI; XviD build 65 + 1447 kbps avg; 23.976 fps; 720x304;
AVI; XviD build 50 + 1729 kbps avg; 23.976 fps; 704x384; # #

**Comment by inflation** [comment]
Do you have logs while you playing the video?

**Comment by dxSir** [comment]
@inflation Yes.
[1687.531][v][vo/opengl-cb] mpv_opengl_cb_report_flip() not being called.
[1687.733][v][vo/opengl-cb] mpv_opengl_cb_draw() not being called or stuck.
This records appears during the freeze.

**Comment by atomicsaiko** [comment]
@dxsir Does the problem also arise with the Hardware Decoder set to 'Disabled' in settings?

**Comment by lhc70000** [comment]
I think it's an upstream (mpv) issue.
