### ISSUE TITLE
Uncompressed 5.1 audio output from IINA to AV reciever

### ISSUE THREAD

**Issue by Darksock** [lhc70000/iina#1472]
Hello!

I’m using macbook pro 2017, latest iina and onkyo tx-nr545. Is there any option in player to output audio via hdmi to reciever without any program iina decoding?

I had this option in powerdvd on windows but can’t see it in iina on mac so audio is processing by mac instead of audio reciever.

**Comment by inflation** [comment]
What do you mean by that? Which one do you want: decompressed 5.1-channel output, or compressed audio data stream?

**Comment by Darksock** [comment]
I need uncompressed 5.1 audio stream that will be processed by reciever.

**Comment by inflation** [comment]
Then you can try to add an option in `Advanced` settings:

`--audio-channels=7.1,5.1,stereo`  (from mpv [manual](mpv.io/manual/stable/#options-audio-channels))

**Comment by Darksock** [comment]
I tried the way you suggested but it hasn't helped - av receiver hasn't shown type of audio Dolby or DTS on its display, that happens when audio transfers without decoding and its processing via receiver

**Comment by inflation** [comment]
@Darksock MPV has its own DTS-HD lossless decoder, and normally you don't need to change it. But if you insist, check the option [`--audio-spdif`](https://mpv.io/manual/stable/#options-audio-spdif).

**Comment by shutdownow** [comment]
I got the same problem, my AV Receiver connected from my MacBook HDMI output. No matter I does the setting --audio-spdif or not, AV Receiver always show "PCM stereo", which I hope it would be "DTS". I tried audio output settings from Preference->Codec->S/PDIF output, but same result is what I got.

anyway, thanks for the developers working, IINA is my main video player now :)

**Comment by alecrobertson13** [comment]
@inflation Following your steps in advanced settings does not resolve this issue, DTS HD and Dolby TrueHD tracks are still outputted as stereo PCM via HDMI.

**Comment by macdavis** [comment]
@Darksock @shutdownow @alecrobertson13 

If you're trying to bitstream AC3, E-AC3 and DTS, try adding `coreaudio-spdif-hack=yes` in the advanced settings.

If you're trying to bitstream Dolby TrueHD and DTS-HD, then there is no way because macOS itself doesn't support it.

**Comment by itxprs** [comment]
oh yeah!! finally in works! thanx for coreaudio-spdif-hack=yes !!!

**Comment by lightgm** [comment]
> oh yeah!! finally in works! thanx for coreaudio-spdif-hack=yes !!!

So excited that' the first time I know someone did it!
Can you explain that with more details?how to set 'coreaudio-spdif-hack=yes'??

**Comment by gigabit2** [comment]
Worth mentioning that on macOS by default HDMI uses stereo audio, so all audio will be downmixed to stereo.

If you go into "Audio MIDI Setup" you can setup your speakers. 8 channel is what you want, then you can set what surround sound system you have.

If you do this, any audio will be sent as surround sound, if the audio is encoded as such - IINA will decode it and send it as such, with no quality loss (to the best of my knowledge).

The exception is Dolby TrueHD, which there is no decoder for. This always gets decoded as Dolby Digital.

**Comment by a4840639** [comment]
@alecrobertson1 The claim that there is no Dolby TrueHD is not true. Dolby TrueHD is just Dolby MLP rebranded and libavcodec has a MLP decoder even before BluRay was a thing (probably developed for DVD-Audio in the first).

However, it is true that object based audio encoding like Atmos and DTS-X cannot be played back this way. (There may be a way because Atmos (DD+) decoded into LPCM does work with many apple devices like iPad and Apple TV)
