### ISSUE TITLE
Feature request: Add DLAN or Samba support

### ISSUE THREAD

**Issue by ForeverOpp** [lhc70000/iina#1476]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Expected behavior:**

**Actual behavior: Add DLAN or Samba support, users can watch their videos which were saved in NAS or Router.**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Currently it's not in the plan. Please mount the files in Finder first.
