### ISSUE TITLE
Feature Request: buffer the video played from external HDD locally

### ISSUE THREAD

**Issue by willx8** [lhc70000/iina#1479]
External HDDs are common for storing videos, especially for Macbook users.

When playing videos from external HDDs, which are usually long (e.g. movies), the user may want to unplug the external HDD, like when s/he wants to move from desk to bed to continue a movie. In order to watch the rest of the movie, the user has to awkwardly move the external HDD with Macbook.

Ideally, the user should be allowed to unplug the external HDD, just as s/he can unplug the battery charger.

A new feature/plugin can be introduced. When such feature is enabled, when playing a video from external HDD, IINA would copy the video file in the background to a local disk buffer. When the copy is finished, IINA would play the local file. So the external HDD can be smoothly unplugged. The local buffer's size can be set by the user.

**Comment by inflation** [comment]
Then why wouldn’t you just copy the movie and delete it after you done? Buffering is mainly for network usage. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atomicsaiko** [comment]
The proposed solution is not efficient. What if you decide to unplug the external HDD while your proposed background copy has not finished? You need IINA/OS also to keep track at which bit to resume file copy to local storage?

This is simply a case of inconvenience with the physical external HDD attached to a Macbook when the user wants to move to another location. Like @inflation said, copying the file to local storage yourself manually and deleting it aftwards is the most logical option. Or if possible simply get yourself shared storage that you could access on the local network with NAS and for which your Wifi has enough bandwidth to stream the data to the Macbook.

**Comment by lhc70000** [comment]
I think it's not going to happen unless mpv decides to implement such a feature.
