### ISSUE TITLE
Audio volume boost (similar to VLC) not working any more

### ISSUE THREAD

**Issue by nightmare28** [lhc70000/iina#1488]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
in older versions an audio boost was possible up to 160% or more. Latest version has maybe killed this...

**Actual behavior:**
only maximum of 100% possible

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by reejosamuel** [comment]
What happened to this issue? I still don't see volume boost, is there something I'm missing

**Comment by lhc70000** [comment]
Preference - Codec - Audio - Maximum Volume.

This feature exists from 0.0.1 :)
