### ISSUE TITLE
Entering macOS split screen by long pressing on the + button hides the window buttons

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#149]
Steps to reproduce:

Have two windows open. One iina and another.
Play a video. Long press the + button and in split screen, select the other window.
Move the cursor to the top of the screen so that the window title appears.
There are no maximize / minimize buttons.

Keep up the good work!

**Comment by lhc70000** [comment]
Thanks. We'll have a check.

**Comment by lhc70000** [comment]
Sorry that I still cannot reproduce this problem. Could you upload a screenshot to show how "there are no maximize / minimize buttons"?

**Comment by LeoNatan** [comment]
As far as I know, this was fixed with #90. I haven't tested the develop branch yet. If the above steps do not reproduce, it is fixed.

**Comment by lhc70000** [comment]
OK. Let's close this issue.
