### ISSUE TITLE
Bottom On Screen Controller - settings cover access to buttons

### ISSUE THREAD

**Issue by waveman777** [lhc70000/iina#1494]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Unwanted behavior:**

When On Screen Controller is on the bottom, when a setting "cog" or "playlist" is being clicked, settings slide from the right, so all opens properly, but all bottom buttons are being covered and when you open "options" for example, you cannot clicl the "cog" again to hide it, as the button is covered with settings window. Actually all bottom-right buttons are covered. The only way to hide is either via shortcut or top menu. 

Also, it would be nice to have a wide version of a floating controller, like in "mplayerX", it would help with navigating.

**Comment by saagarjha** [comment]
Thanks for reporting these, however, we're already tracking these with #42 and #1396.
