### ISSUE TITLE
Can't load DisplayCAL 3D Lut Cube file

### ISSUE THREAD

**Issue by DavidEscalante** [lhc70000/iina#1495]
**System and IINA version:**
- macOS 10.12.6 (16G29)
- IINA 0.0.15 Build 68

**Expected behavior:**
IINA load and display video using LUT (.cube) file

**Actual behavior:**
"ERROR: Error occured when setting filters. Please check your parameter format."

**Steps to reproduce:**
Drag .cube file into to 3D Lut File box, click Add

**How often does this happen?**
Each time

[XR342CK 3D LUT.zip](https://github.com/lhc70000/iina/files/1729297/XR342CK.3D.LUT.zip)

**Comment by bodayw** [comment]
Neither mpv nor IINA support loading external 3D LUT files AFAIK.

If you want color managed video, use the ``--icc-profile`` option in mpv, as you can add it in IINA under Preferences - Advanced. This way a 3D LUT will be generated internally after loading the icc profile and color conversion will be performed accordingly.

IINA might be able to automatically detect and load the icc profile in the future, but right now this is the only way to enable color management in IINA.

**Comment by lhc70000** [comment]
@DavidEscalante Does your file path contain any special character? How about dragging the file into the video window directly?

Please also provide mpv log (enable in pref-advanced) for further investigation.

**Comment by DavidEscalante** [comment]
@bodayw Well, there is this option in Video Filters and its listed in change log, but not even with the --icc-profile under advance options works, it doesn't shows any error but it doesn't load the profile either.

@lhc70000  It does nothing when I drag the .cube file directly to the window, not even an error message.  Here is the Log file: https://cl.ly/3S1V2e1I3q1h/2018-2-16-12-43-22_2Rskd1.log

I attached my LUT file in the post if you want to try it.

**Comment by bodayw** [comment]
@DavidEscalante You're right, I wasn't aware of that in video filters. But ``--icc-profile`` should work...just in case, are you giving the path to your icc profile (.icc) or the 3D LUT file (.cube) to that option?

**Comment by inflation** [comment]
@DavidEscalante The error is from `ffmpeg`, which says your 3D LUT file is too large.
