### ISSUE TITLE
能否增加查看码率选项？

### ISSUE THREAD

**Issue by 3Lzm** [lhc70000/iina#1496]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
@3Lzm ⌘I 检查器
