### ISSUE TITLE
Keep windows on top while playing | 窗口置顶

### ISSUE THREAD

**Issue by androidcn** [lhc70000/iina#15]
请加入[播放的时候在最前面]Keep windows on top While playing

**Comment by lhc70000** [comment]
菜单的`视频->窗口置顶` 应该有效。是不是该把它放到别处？

以及，好像有人说这个功能有 bug，请测试。

---

It could be done by `Video -> Always on Top` in menu.

Please suggest if this menu item should be moved to somewhere else, and test whether this feature works normally.

**Comment by androidcn** [comment]
有个Bug 就是 Always on top 后,再按Menu的话.画面会挡住Menu..这样不科学

**Comment by lhc70000** [comment]
@androidcn 常亮的话不行啊，没有窗口的时候应该是不亮的吧...

**Comment by lhc70000** [comment]
Got some reports saying standard buttons (traffic light) not work after enabling always on top. Need to be confirmed.

**Comment by androidcn** [comment]
可以借鉴 MplayerX
它是放在 
Preferences - General

**Comment by lhc70000** [comment]
Since all bugs related to floating on top have been fixed, this issue will be closed automatically after merging to master, most likely in tomorrow.

For "adding an option for keeping window always on top in preference", let move to another issue #113.

---

由于此 issue 内的所有 bug 已被修复，此 issue 将会在被 merge 到 master 时自动关闭。关于在偏好设置中添加置顶选项，请移步至 #113。

**Comment by JohnSinclair111** [comment]
+1

**Comment by wayone** [comment]
我认为：所有的功能在“偏好设置”都应该能找到。

**Comment by wayone** [comment]
窗口置顶，应该属于“窗口”这个选项里

**Comment by wayone** [comment]
“是否置顶”真的需要经常来回修改，直接在播放控制条上添加按钮，就比较方便了。

**Comment by wayone** [comment]
> 菜单的`视频->窗口置顶` 应该有效。是不是该把它放到别处？
> 
> 以及，好像有人说这个功能有 bug，请测试。
> 
> It could be done by `Video -> Always on Top` in menu.
> 
> Please suggest if this menu item should be moved to somewhere else, and test whether this feature works normally.

窗口置顶是有  bug，有时候会失效。不清楚复现步骤。
