### ISSUE TITLE
Allow disabling action for horizontal and / or vertical scroll

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#150]
Right now, it is only possible to change the seek type for horizontal scroll. However, I often find it preferable to disable actions for horizontal / vertical scrolls in order to prevent accidental scrolls on the touchpad.

**Comment by LeoNatan** [comment]
Any news on this?

**Comment by LeoNatan** [comment]
@lhc70000 I see that seek mode is currently tied to vertical scroll mode. I don't think this is the right way to do it. There should be two different settings, one for seek mode and one for scroll. Working on a PR.

**Comment by megadr01d** [comment]
Sorry guys, just adding original reference: https://github.com/lhc70000/iina/issues/7
Too many duplicates!

**Comment by mshick** [comment]
I absolutely agree. I've brushed the trackpad many times and ended up at the end of a movie. Would love an option here.

**Comment by LeoNatan** [comment]
@lhc70000 Thanks!
