### ISSUE TITLE
5.1 audio Playback not possible

### ISSUE THREAD

**Issue by farbefreak** [lhc70000/iina#1508]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
Play 5.1 audio

**Actual behavior:**
does not play 5.1 audio wenn selected to play, im using a application called soundflower that generates a 64 channel wide virtual Audio cable that acts like a normal audio output device.
In VLC the 5.1./7.1 soundtracks play just fine with sound flower as output device, in IINA i can't get it to work. It only plays on the first 2 channels in stereo.
In Audio MIDI config the output device is set as 5.1.
IINA is great however, its the only player that make it possible to play 4k on my mac!
Thanks for the effort!
 

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
See #1472

**Comment by farbefreak** [comment]
Hello,
i have tryed the mentioned options, 
audiochannels 5.1 /7.1 / 6 
not working only output on 2 channels
audiochanels auto
not working only 2 channels
--audio-exclusive=yes
--ad-lavc-downmix=no

nothing gives me 5.1 channel audio

however its also not working in MPV

the output is not spdif ist 6 channel analog audio output that im trying to get working

**Comment by atomicsaiko** [comment]
Once you ended your post with the output is not S/PDIF I got confused. It is clear you need 5.1 output from IINA and then send to the virtual audio output device. I haven't used Soundflower myself, but I don't think it advertises decoding of proprietary formats from Dolby or DTS for which you would need to bitstream the audio bitstream unmodified to a real receiver.

Thus you would need to send uncompressed audio decoded from the source file. Regardless of which audio codec is used. Are you sure that your source file has 5.1 channel coded audio stream? Please  provide an MediaInfo output.

Below setting which you tried should be sufficient to get the desired output. Do you hear 'downmixed' stereo output or only Left and Right without audio vocals mixed in from the Center channel? This could give us a clue. Assuming that your source 5.1 channel is encoded according to the common LRCLfeLsRs layout.

``--audio-channels 5.1

And are you also sure the Soundflower virtual audio device is set as the default audio output device in settings?

**Comment by farbefreak** [comment]
Thanks for your help.

Yes I’m shure that the file is DTS5.1 
Or 6ch.
I use that soundflower thing to modifie the audio through audio hijack pro.
I use it to correct my frequency response of my speakers.
Soundflower is the standard audio device in system control on Mac.
And in Audi midi setup i set soundflower for the standard channel layout.

All I can hear is stereo downmix, rear channels are mixed into the left/right stereo channels.

On OS X soundflower acts like a 64ch soundcard with analog line output.

I need IINA to output the decoded sound, like it is outputing to a 6ch soundcard that is purely analog.
The channellayout is not important because I can reroute the channels in audio hijack pro.

I think IINA is detecting the soundflower device as an 2ch output device and forces downmixing.

I have used audio-channels=help on MPV, it Shows my output as: 
„coreaudio/soundflowerengine:1 (Soundflower 64ch)“

Audio codec in the file is: 
Format: s32p
Codec: dca (DCA (DTS Coherent Acustics))
Driver: coreaudio
Channels: 5.1 (side)
Bitrate: 2.22Mbps

Thanks for your time! 
Best regards

**Comment by inflation** [comment]
IINA does nothing beyond passing the stream to `mpv` so I suggest you ask them about the issue. Another thing is trying to play the video under `mpv -v` and looking for tag `[coreaudio]`, if anything goes wrong, it may be a macOS issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by farbefreak** [comment]
Hey,

Thank you, that has helped me a lot!

Verbose mode displays a useful massage:
MPV does not understand a Output device with more than 16 Channels and automaticly disables 6ch output mode and falls back to 2Ch stereo downmixing.

I solved the issue by changing the channel numbers in Soundflower to only show 16 channels

IINA and MPV now plays in 6Ch mode!

Thanks for the help.
Best regards

**Comment by epalzeolithe** [comment]
Here's the solution on mac

--coreaudio-spdif-hack=<yes|no>

it hacks macos driver to enable audio passthrough spdif

**Comment by pratikroythebest** [comment]
> Here's the solution on mac
> 
> --coreaudio-spdif-hack=<yes|no>
> 
> it hacks macos driver to enable audio passthrough spdif

How to execute it?

**Comment by dioxine** [comment]
<img width="820" alt="Screenshot 2024-02-17 at 02 49 51" src="https://github.com/iina/iina/assets/9818235/41acd6f4-a1b5-4bbe-98e2-d65f75ee4219">
