### ISSUE TITLE
Feature Request: Advanced subtitles synchronization

### ISSUE THREAD

**Issue by vosatom** [lhc70000/iina#1509]
**System and IINA version:**

- macOS 10.13.1
- IINA 0.0.15

**Expected behavior:**
Some subtitles may have different timing than audio in movie. IINA has option to delay subtitles by setting exact time, but it is hard to figure it out.
I would suggest VLC-like feature for subtitles synchronization as described on https://wiki.videolan.org/VLC_HowTo/Adjust_subtitle_delay/#Advance_Synchronisation

**Comment by saagarjha** [comment]
Does #1460 describe the feature you're looking for?

**Comment by vosatom** [comment]
Might be the similar feature.
Next time I will do better research.
