### ISSUE TITLE
Crash when playing .mp3 files

### ISSUE THREAD

**Issue by chenrylee** [lhc70000/iina#151]
I tried to use IINA as a audio player, but it crashed.
I clicked File - Open, and selected a .mp3 file, then I received the error box:

Error
Fatal error: Frame buffer check failed
The application will exit now.

**Comment by lhc70000** [comment]
IINA does not support audio files (i.e. media without "video stream") currently. It works when playing a mp3 with album cover.

Hopefully we'll fix it in next version.

**Comment by henng** [comment]
duplicate with #103

**Comment by lhc70000** [comment]
Close due to duplication.
