### ISSUE TITLE
Select more the one file from playlist

### ISSUE THREAD

**Issue by siamak01** [lhc70000/iina#1514]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
 
If two or more windows open, I can move files from playlist of one to the other to rearrange/edit my playlist. Wish could select more than one file at time. Either directly from playlist and/or using right click to select all.

**Comment by alejx** [comment]
You can either use Shift key or Control key to select multiple rows in playlist.

**Comment by siamak01** [comment]
Great. Thanks.
