### ISSUE TITLE
Ability To Set On Screen Display To Not Show At All

### ISSUE THREAD

**Issue by rockstarinlife** [lhc70000/iina#1518]
Love the video player so much better than VLC player I have been using. Right now the only thing I see keeping me from being able to use this for my trainings is the ability to hide the on screen display in the left top corner of the video when in fullscreen. It shows the time and tiny scrubber even when I set it to 0 for a quick sec. The lowest number I can set the text is 5 for font. It would be a perfect player if I can just set it to 0 and it wont even show up. Or a setting that says hide and check that box.

I made this short 1 min video explaining:
https://www.useloom.com/share/6bbecc0e95434440af0028f44a574373

**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Comment by rockstarinlife** [comment]
Also do you have a donate button anywhere we can support this project?

**Comment by siamak01** [comment]
I watched your video and tried to duplicate it. Mine does not show anything at upper left corner! Only upper right corner if Display time and battery is shown is checked! I prefer it to be visible if time is set to more than 0.

**Comment by lhc70000** [comment]
Should be the same issue as #641, which is in the plan.

We'll accept donation when a 1.0 stable release is available; thanks for your support!
