### ISSUE TITLE
[Feature Request] Get the player active on all desktops. 

### ISSUE THREAD

**Issue by stephanepiriou** [lhc70000/iina#1519]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Expected behavior:**
It would be nice to have an option for the player to be activated on all desktops, allowing to watch a video while switching from a desktop to another, for example for a working session. 

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
Does picture in picture mode do what you want?

**Comment by QuattroGam3r** [comment]
This already works if you right click iina in the Dock, go to options and assign All Desktops.

**Comment by rien333** [comment]
@QuattroGam3r  cool trick, but only kinda works. The downside of that solution is that the setting will be across the whole app, so for any new instances as well. Per window visibility is def possible under macOS though, look at [Helium](https://github.com/JadenGeller/Helium) for example.

**Comment by stephanepiriou** [comment]
> Does picture in picture mode do what you want?

That's it. The same functionnality than picture in picture in Safari.

**Comment by saagarjha** [comment]
Glad to see you're satisfied, then.
