### ISSUE TITLE
Not clearing recent files in main window

### ISSUE THREAD

**Issue by nrlquaker** [lhc70000/iina#1522]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 build 69

**Expected behavior:**
After clearing recent menu recent files should be cleared in main window as well (below "Open URL...").

**Actual behavior:**
After clearing recent menu recent files are still there in main window (below "Open URL...").

**Steps to reproduce:**
File -> Open Recent -> Clear Menu

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
Reopening the main window should work in the latest beta version.
