### ISSUE TITLE
Bug report: ASS subtitles behaves different with different frame-rates

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#1525]
ASS subtitles containing move effects always being choppy rendered on IINA. 

I guess this choppy is related to the video frame-rates and start a test: raise a 30fps video to 60fps by handbrake for mac, replay with the same ass file.

The choppy disappears.
(though there are still a small bug that could still choppy some time but with pause and replay could fix it)

So, I think this is a bug comes from IINA || libass, which render the \{move} effects in the frame rate same as video, instead of higher like 60fps.

If this bug could be fix, then the problems of using ASS as danmaku all solved.

- test case: https://www.dropbox.com/sh/9hot7ll920fu5qi/AAC5SSnrdlvOfJ3DL-iYNr5ma?dl=0
- macOS 10.13.2
- IINA 0.0.15

**Comment by lhc70000** [comment]
Please report this issue to mpv since that's how mpv renders subtitles.
