### ISSUE TITLE
显示ass字幕异常

### ISSUE THREAD

**Issue by njj0803** [lhc70000/iina#1528]
- macOS 10.13.3
- IINA 0.0.15

显示有些ass字幕时，会出现两遍字幕，和mpv一样，是否可以设置，还是显示问题，
![jietu20180225-171322](https://user-images.githubusercontent.com/10919983/36639815-578dc21e-1a4f-11e8-90d0-1eaea35abbd8.jpg)

**Comment by lhc70000** [comment]
如果 mpv 有同样的问题，请报告给 mpv。
