### ISSUE TITLE
[Concept] Add E-GPU Support .

### ISSUE THREAD

**Issue by Co2333** [lhc70000/iina#1532]
![qq20180303-045556](https://user-images.githubusercontent.com/25259084/36922680-b4d17364-1ea3-11e8-8880-c99f98168439.png)

You know what, it's like ppt when watching something. It's not good.
Maybe add metal/opengl/opencl/cuda support?
System : 10.13.3 (17D102)

有些时候看片就像是ppt😂家丑不外扬

**Comment by saagarjha** [comment]
Just to satisfy my curiosity, is that actually a Mac Mini? I was under the impression that Thunderbolt 3 ports were required for eGPU support, so I'm not quite sure how you got that to work.

**Comment by AngryKiller** [comment]
No, there are a few Thunderbolt (2) PCIe enclosures on the market, like the Akitio Thunder 2

**Comment by Co2333** [comment]
![qq20180303-052924](https://user-images.githubusercontent.com/25259084/36922708-dae7f938-1ea3-11e8-915c-0dce4579f7a8.png)
@AngryKiller  @saagarjha

**Comment by lhc70000** [comment]
You should report this issue to mpv.
