### ISSUE TITLE
5.1声道的视频光有图像，没有声音。

### ISSUE THREAD

**Issue by zxl777** [lhc70000/iina#1533]
下载种子 
magnet:?xt=urn:btih:cfe8c8730caf55190e12f3984cfe6a61514c690a&dn=Modern+Family+S02+Season+2+720p+5.1Ch+BluRay+ReEnc-DeeJayAhmed&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

这个视频用MPV播放正常。

**Comment by lhc70000** [comment]
- 请确定静音和音量设置没有问题。
- 请确定选择了正确的音轨（而不是「无」）。
- IINA 现在使用 mpv 0.27.0，请确定使用的是同一个版本。

**Comment by alejx** [comment]
可能相关的 issue: #1508, #1472
