### ISSUE TITLE
On screen controller & subtitle are not centre

### ISSUE THREAD

**Issue by lawsyau** [lhc70000/iina#1534]
![screen shot 2018-03-03 at 11 08 25 pm](https://user-images.githubusercontent.com/36912044/36935868-20ef917c-1f38-11e8-8962-2a957bd2a162.png)
On screen controller & subtitle are not centre,

i have tried cleaning cache, restart the app, the on screen controller is position a bit right, as well as the subtitle, at first i didn't notice that

**Comment by lhc70000** [comment]
You can drag the on screen controller to anywhere.

For the subtitle, it may related to your settings, or the subtitle file itself. Please report this to mpv if you found other players render the same subtitle at the center.
