### ISSUE TITLE
Using keyboard media controls does not work

### ISSUE THREAD

**Issue by fwzmhmd** [lhc70000/iina#1536]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 b68

**Expected behavior:**
So using the keyboard media controls doesn't work, In previous versions of IINA it would work, this version somehow doesn't.

**Actual behavior:**
N/A

- Crash report:
```
N/A
```

- MPV log:
```
N/A
```

**Steps to reproduce:**
N/A

- [x] MPV does not have this problem.

**How often does this happen?**
N/A

**Comment by saagarjha** [comment]
Notification Center has a handy “Now playing” widget that tells you what the media keys control. Do you see IINA there?

**Comment by minusf** [comment]
i confirm that his is the case with 0.15, "Use system media control" under preferences is enabled. funny thing is `mpv` does handle them even from the terminal :D
