### ISSUE TITLE
Support danmaku | 可以考虑支持AB站XML格式的弹幕吗

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#154]
弹幕文件也算是字幕文件的一种了，有时候就想收藏下那些火过的A站B站视频。

前两年中大一哥们撸了个BiliLocal，但Windows Only。

**Comment by orzFly** [comment]
https://github.com/m13253/danmaku2ass (GPLv3)

**Comment by lhc70000** [comment]
Why not [bilibili for mac](http://bilimac.eqoe.cn)?

---

bilibili mac 客户端是更早的项目了，那就不必重复劳动；而且我觉得一个通用播放器加上弹幕还是有点奇怪的。

**Comment by lhc70000** [comment]
IINA 的目标是通用播放器，所以不打算支持弹幕。你可以用 bilibili for mac 播放带弹幕的本地视频，或者用楼上推荐的转换至 ass 工具。

**Comment by otakustay** [comment]
补充一下，当前iina在使用弹幕上的主要问题是原本就需要外挂字幕的视频无法和弹幕转的`.ass`文件一起使用，iina不支持同时显示2个特效字幕，因此将其中一个`.ass`文件作为副字幕的话会丢失掉特效（变成顶部居中白色字体）

如果iina可以支持主副字幕均解析ass特效的话，是可以作为一个通用播放器很好的支持弹幕播放的，也可以使用我的[danmaku-to-ass](https://github.com/otakustay/danmaku-to-ass)库做精细配置的弹幕转ass

**Comment by lhc70000** [comment]
@otakustay IINA 使用 mpv 解码，不支持两个 ass 应该是 mpv 的限制……

转 ass 的功能应该可以以后写 lua 脚本当插件实现，但是集成到播放器里还是不会考虑。

**Comment by otakustay** [comment]
我觉得转ass这些事都是比较容易做的，不能2个ass特效同时播放才是最头疼的，当前我的解决方案都是先把字幕用ffmpeg直接写进视频里，然后再外挂弹幕……

**Comment by CaiPeterCai** [comment]
@otakustay 还不如直接把两个ass合一个，全选复制粘贴而已

**Comment by gonejack** [comment]
弹幕转成 ASS 最大的问题是不流畅，貌似还无解。

其他字体设置之类的还能自己手动去调整。
