### ISSUE TITLE
the latest version 0.0.15 cant loading subtitle suddenly

### ISSUE THREAD

**Issue by aguaguagua** [lhc70000/iina#1540]
the latest version 0.0.15 cant loading subtitle suddenly

**Comment by inflation** [comment]
If you mean online subtitle searching, see #1530.

**Comment by aguaguagua** [comment]
its the external subtitle.ass and srt arent available

**Comment by lhc70000** [comment]
What do you mean by "aren't available"? Is there any error when loading the subtitle? Or the subtitles are loaded successfully but aren't displayed (If so, please check #757)?
