### ISSUE TITLE
视频缩略图缓存问题

### ISSUE THREAD

**Issue by ishowshao** [lhc70000/iina#1543]
如果有两个同名的文件比如都是 1.mov ，先播放第一个1.mov时在进度条看缩略图之后，打开第二个1.mov时，缩略图是上一个视频的缩略图，必现

**Comment by inflation** [comment]
See #1058 and it's fixed by #1202.

**Comment by ishowshao** [comment]
最新版 15build68没修复

**Comment by inflation** [comment]
@ishowshao I just merged the PR so it is in `develop` branch. Should be appeared in the next release.
