### ISSUE TITLE
使用手势进行放大全屏时，全屏会超出屏幕的最大宽

### ISSUE THREAD

**Issue by github-2013** [lhc70000/iina#1545]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
设计如此，macOS 一般不限制窗口的宽度。
