### ISSUE TITLE
Localization for 1.0.0 beta1

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#1551]
fr @superzazu
it @cgand
de @J-rg @shorshe
zh-Hant @LEOYoon-Tsaw (I'll use OpenCC if you are busy)
ko @darkbrow
ru @euf @imKota
ja @matsune
tr @eminhaqi
nl @dionvl
pl -
es @Aikyuichi
uk @sevenfourk
sk @Marvin99com
da @thkir

Dear translators, please update the translation if possible. This is a beta release, so the update of translation is not mandatory.

From this version, missing strings in `Localizable.strings` will be appended to the file using default English translation, with a `FIXME` comment. Please pay attention to them. **If you are using the translation utility, please download the latest release ([0.1.3](https://github.com/iina/iina-translation-utility/releases/tag/0.1.3)) before starting.**

**Comment by imKota** [comment]
@lhc70000, no problem :3

**Comment by Greenek** [comment]
I can update Polish translation if Patryk is no longer available.

**Comment by lhc70000** [comment]
Hi @Greenek, that would be great!

**Comment by pradorocchi** [comment]
I will review and update pt-br

**Comment by LEOYoon-Tsaw** [comment]
Sorry for the delay, I'm primarily using English now, and I think that using OpenCC for trad Chinese is quite viable.
