### ISSUE TITLE
前置窗口疑问

### ISSUE THREAD

**Issue by nonowine** [lhc70000/iina#1559]
我记得之前使用的时候 是默认没有前置窗口的 后来好像是不知道怎么就设置成了播放时永远在最前 请问一下能不能增加一个手动的 设置/取消“窗口在最前”的功能呢？
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Comment by msongz** [comment]
快捷键里可以设置
不过我想加一个意见是，开关前置的状态可以在左上角显示
例如 继续/暂停 这样

**Comment by lhc70000** [comment]
@nonowine 「视频」菜单里
