### ISSUE TITLE
播放的时候会有设置的问题

### ISSUE THREAD

**Issue by PromiseNev** [lhc70000/iina#1562]
- macOS 10.13.2
- IINA 0.0.15

播放视频的时候,比如我第一个视频是1.3倍速,接着看其他视频我恢复了播放速度,然后关闭APP,第二天再看,或者其他时候再看,会经常1.3倍,而不是原来的速度 这个bug很糟心.

**Comment by lhc70000** [comment]
- 默认切换文件时会保持尽可能多的设置。如果你想把播放速度除外，可以在偏好设置-高级中的额外 mpv 选项中添加一行， key 为 `reset-on-next-file`，value 为 `speed`。
- 退出文件时（仅限关闭窗口，退出 App 等操作，手动切换文件等不会），会记录下来当前文件生效的所有选项。

这是 mpv 的行为，IINA 暂时无法改进。很难说是 bug，但确实可能有不好的用户体验。将来可能会设计一些解决方案。
