### ISSUE TITLE
视频播放加速的倍数问题？？？？能否还原0.0.14 版功能？

### ISSUE THREAD

**Issue by zhuamaodeyu** [lhc70000/iina#1564]
不知道是出于什么原因的考虑，去除了 0.0.14 的 "]"与"[" 快捷键来操作视频播放速度的，现在改为 只能 2 倍加速，确实有点不是很方便了，有些视频正常播放时间较长，所以一般会加速播放， 但是2倍后又太快，听不清楚了，不知能能否还原14 版本的操作   ？？？？？     

**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Comment by lhc70000** [comment]
- ⌥⌘[，或
- 自行添加 [ 的快捷键

**Comment by gMan1990** [comment]
哈哈，我以为速度是+0.1，+0.1，-0.1, -0.1这样，原来是乘~
