### ISSUE TITLE
播放列表功能功能建议

### ISSUE THREAD

**Issue by neverzyw** [lhc70000/iina#1566]
系统信息：
- macOS 10.13.2
- IINA 0.0.15

功能建议：
- 建议提升播放列表功能，增加播放列表保存、另存为、编辑等功能，类似potplayer
- 建议增加在线视频播放列表功能，能够在播放列表中切换不同在线视频
- 建议增加直播视频播放列表功能

**Comment by inflation** [comment]
1. 可以保存播放列表，打开后调整再保存也是可以的。
2,3 都是支持的。
