### ISSUE TITLE
No available items showing under Customize On Screen Controller - Beta

### ISSUE THREAD

**Issue by baranduins** [lhc70000/iina#1568]
**System and IINA version:**

- macOS 10.10.5
- IINA 1.0.0-beta1 Build 70

**Actual behavior:**

Just updated to the Beta and the right side of my on screen controller is now empty, with nothing showing up under the customize button.

![screen shot 2018-03-21 at 20 35 09](https://user-images.githubusercontent.com/37637575/37736420-c7666a30-2d48-11e8-91a4-1b8ce2591289.png)

**Comment by lhc70000** [comment]
This is quite weird. Could you try reinstalling the app? It can be downloaded from https://dl.iina.io/IINA.v1.0.0-beta1-build71.dmg.

**Comment by baranduins** [comment]
Just tried reinstalling from there, no change.

**Comment by lhc70000** [comment]
What's the output of `defaults read com.colliderli.iina controlBarToolbarButtons` in terminal?

Is there any error log in Console.app when you open this panel?

**Comment by baranduins** [comment]
Terminal outputs:

```
(
    2,
    1,
    0
)
```

Console is showing these errors for IINA when I open and close the panel: 

> 21/03/2018 21:50:12.007 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9503ca3110 H:[NSButton:0x7f9503c7a540'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503bee390 h=--& v=--& H:[NSButton:0x7f9503c7a540'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9503ca3110 H:[NSButton:0x7f9503c7a540'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.008 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9503c84670 V:[NSButton:0x7f9503c7a540'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503995d30 h=--& v=--& V:[NSButton:0x7f9503c7a540'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9503c84670 V:[NSButton:0x7f9503c7a540'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.008 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9503a40b50 H:[NSButton:0x7f9503c5daa0'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503b8e810 h=--& v=--& H:[NSButton:0x7f9503c5daa0'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9503a40b50 H:[NSButton:0x7f9503c5daa0'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.009 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9503c7c9a0 V:[NSButton:0x7f9503c5daa0'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503937550 h=--& v=--& V:[NSButton:0x7f9503c5daa0'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9503c7c9a0 V:[NSButton:0x7f9503c5daa0'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.009 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9503c78510 H:[NSButton:0x7f9503c04510'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503a4d940 h=--& v=--& H:[NSButton:0x7f9503c04510'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9503c78510 H:[NSButton:0x7f9503c04510'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.010 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f950142bd20 V:[NSButton:0x7f9503c04510'Button'(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503a599b0 h=--& v=--& V:[NSButton:0x7f9503c04510'Button'(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f950142bd20 V:[NSButton:0x7f9503c04510'Button'(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.012 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f95017266e0 H:[NSImageView:0x7f95017cd380(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503ca6770 h=--& v=--& H:[NSImageView:0x7f95017cd380(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f95017266e0 H:[NSImageView:0x7f95017cd380(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.012 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f95017cadd0 V:[NSImageView:0x7f95017cd380(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503ca6810 h=--& v=--& V:[NSImageView:0x7f95017cd380(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f95017cadd0 V:[NSImageView:0x7f95017cd380(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.013 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f95017cba70 H:[NSImageView:0x7f95017d0130(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503c2e340 h=--& v=--& H:[NSImageView:0x7f95017d0130(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f95017cba70 H:[NSImageView:0x7f95017d0130(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.013 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f9501772b30 V:[NSImageView:0x7f95017d0130(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503c35670 h=--& v=--& V:[NSImageView:0x7f95017d0130(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f9501772b30 V:[NSImageView:0x7f95017d0130(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.014 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f95017ca9f0 H:[NSImageView:0x7f950177e960(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503c2eb70 h=--& v=--& H:[NSImageView:0x7f950177e960(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f95017ca9f0 H:[NSImageView:0x7f950177e960(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
> 21/03/2018 21:50:12.014 IINA[31671]: Unable to simultaneously satisfy constraints:
> (
>     "<NSLayoutConstraint:0x7f95017bb230 V:[NSImageView:0x7f950177e960(24)]>",
>     "<NSAutoresizingMaskLayoutConstraint:0x7f9503c2ec10 h=--& v=--& V:[NSImageView:0x7f950177e960(0)]>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x7f95017bb230 V:[NSImageView:0x7f950177e960(24)]>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
>

**Comment by lhc70000** [comment]
Could you test if this build works for you? https://drive.google.com/file/d/1HsbKodDuq7raRtKivO2CUUh3b6hPzylo/view?usp=sharing

**Comment by baranduins** [comment]
The buttons are now showing up in the on screen controller, but still nothing under the customize button, and the same errors from Console when I click it.
