### ISSUE TITLE
will final v1.0 use mpv 0.28.2?

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1575]
surprised 1.0b didnt use it

**Comment by lhc70000** [comment]
The mpv libraries that IINA uses is built from Homebrew. Search mpv in Homebrew's repo for more discussions: https://github.com/Homebrew/homebrew-core/issues?utf8=✓&q=mpv

We will definitely update mpv in the 1.0.0 (non-beta) release, but not now - there will be several more beta releases before that.
