### ISSUE TITLE
关于内置双字幕的位置调整功能需求？

### ISSUE THREAD

**Issue by MaverickChan** [lhc70000/iina#1578]
系统信息：
    macOS 10.10.5
    IINA 0.0.15build68

功能建议：
     内置的字幕，可以同时以字幕、副字幕显示，但是会重叠，不知道是否能够实现调整字幕位置的功能（也      
     就是说，双字幕，不重叠）？谢谢作者的软件～

**Comment by lhc70000** [comment]
mpv 不支持带格式的副字幕，也不打算实现。暂时没有办法。
