### ISSUE TITLE
malfunctioned advanced option will prevent app starting up

### ISSUE THREAD

**Issue by xu-cheng** [lhc70000/iina#158]
If you have a malfunctioned option defined in "Additional MPV options", the app will report an alert message following with exiting immediately.

This unfortunately causes the app unusable, as there is no way you can remove the malfunctioned option without opening app. The only choice is to manually delete the preference file in the disk.

**Comment by HarukaMa** [comment]
Maybe we should add a failsafe mode and detect if mpv is crashed on startup

**Comment by xu-cheng** [comment]
The simplest solution is that, after the alert message, the app should just ignore the incorrect option and stay open.

**Comment by lhc70000** [comment]
@xu-cheng 

It should not happen since I noticed this problem before and current code is 
```swift
if status < 0 {
  Utility.showAlert(message: "Error setting option --\(op[0])=\(op[1]) with return value \(status). Pleaase check your settings.")
}
```

It does not exit.

If it quits then there must be some critical problem (not caused by user).

**Comment by xu-cheng** [comment]
After some test, this bug seems to only happen if I choose the option "Quit when no window opened"
