### ISSUE TITLE
Title bar 2px border is a little bit too distractive

### ISSUE THREAD

**Issue by chinnnki** [lhc70000/iina#1584]
**System and IINA version:**

- macOS 10.13.4 Beta
- IINA 1.0.0 beta 1 (71)

**Expected behavior:**

**QuickTime Player** integrates an autohidden title bar with a 2px border at the upper and lower edges, which is gradient in color (two colors) and nearly unnoticeable; **mpv 0.28.0 (HEAD-965ba23)** integrates an autohidden solid title bar without upper or lower borders.

Both have a modern and compact look.

**Actual behavior:**

**IINA**'s title bar is somehow a bit odd. It has a 2px border only at the lower edge, which appears to be solid light gray. This makes the UI less compact and sometimes draws the user's attention away from the image. Also it's inconsistent with the borderless OSC.

**Suggestion**

The border to be removed.

**Attachment**

![2018-03-27 16 57 03](https://user-images.githubusercontent.com/12984268/37954198-fa7cfb14-31df-11e8-9b43-6660804aa810.png)

**Comment by lhc70000** [comment]
Already fixed in current develop branch.
