### ISSUE TITLE
Timeline mouse hover shows wrong preview thumbnails

### ISSUE THREAD

**Issue by YourMJK** [lhc70000/iina#1588]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15

**Expected behavior:**

Mouse hover over timeline shows preview thumbnails of the current video according to mouse position on the timeline.

**Actual behavior:**

Mouse hover over timeline shows preview thumbnails of a completely different video which was once opened with IINA and had the same filename/path.
Demonstration: https://youtu.be/-oe4WgHmUfs

**Steps to reproduce:**

No general way to reproduce found yet. It happens when I open any file named "title00.mkv" located in a specific directory. 

**How often does this happen?**

Always.

**Comment by lhc70000** [comment]
This should already been fixed in 1.0.0 beta 1.

**Comment by YourMJK** [comment]
You are right, I just checked.
