### ISSUE TITLE
iina player did't quit after playback

### ISSUE THREAD

**Issue by hoc9bee** [lhc70000/iina#1589]
iina : 0.0.15
osx : 10.12.6

checked the option : Quit after all windows are closed
but iina didn't quit after playback.

**Comment by lhc70000** [comment]
You also need to uncheck "keep window open after playback".

**Comment by hoc9bee** [comment]
Yes, also uncheck the option.

Please check my current setting attached.

Thanks a lot

On 29 Mar 2018, 00:36 +0800, Collider LI <notifications@github.com>, wrote:

You also need to uncheck "keep window open after playback".
