### ISSUE TITLE
播放器原来设置是2倍速，暂停之后继续播放，就变成了1倍速

### ISSUE THREAD

**Issue by FishHappiness** [lhc70000/iina#1591]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
无法重现，请提供操作步骤。

**Comment by FishHappiness** [comment]
这个是我原来的播放速度为:2x
![image](https://user-images.githubusercontent.com/24503771/38068178-608aab1e-3342-11e8-8e70-1d5871849007.png)
现在我暂停了一下
![image](https://user-images.githubusercontent.com/24503771/38068185-680a213a-3342-11e8-8845-368aa308a05f.png)
现在我又继续播放，变成了1x
![image](https://user-images.githubusercontent.com/24503771/38068189-6f62527c-3342-11e8-9c19-f555ca2e2e3b.png)
如果需要2x，还需要重新设置。
![image](https://user-images.githubusercontent.com/24503771/38068269-d48308ea-3342-11e8-9d55-05b3b918fb2c.png)

**Comment by lhc70000** [comment]
这是正常行为，请使用快捷键（⌘]）或者侧边栏调整播放速度。这两个按钮只是临时快进/快退时使用的。
