### ISSUE TITLE
4x倍数播放时，音频听不清，有点乱码的感觉（ps其他软件4x能够听清）

### ISSUE THREAD

**Issue by uuzz** [lhc70000/iina#1592]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
请向 mpv 反馈此问题。
