### ISSUE TITLE
IINA consistently crashes when two apps that were full screen and in split view, are restored from the split view state

### ISSUE THREAD

**Issue by mahye82** [lhc70000/iina#1598]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 Build 68

**Expected behavior:**
In macOS, two apps can be maximized at the same time to create a split screen effect.

When you leave the split screen, the app that was clicked should be restored out of a maximized state. 

[Apple support article describing how to do this](https://support.apple.com/kb/PH25072?locale=en_US)

**Actual behavior:**
IINA crashes when attempting to restore out of the full screen, split view state.

**Comment by alejx** [comment]
Should be fixed by #1608, or I'll try to fix it after #1608 is merged.
