### ISSUE TITLE
Support Force Touch

### ISSUE THREAD

**Issue by JasonSi** [lhc70000/iina#16]
试用了一下 界面非常好看

跟bug修复比起来这个新增功能应该显得无关紧要 不过还是期待

比如Force Touch快进快退 像QuickTime一样

**Comment by lhc70000** [comment]
Force Touch 支持在计划中。

请帮忙想一想 Force Touch 还能有哪些交互能用到。

---

It's in my plan. 

Also please suggest more use cases for Force Touch.

**Comment by JasonSi** [comment]
Sorry for opening an issue with Chinese.

Besides the fast-forward button,  I'll try to give some ideas.

- Force Click screen to generate a screenshot
- I don't know whether this is possible to Force Click a word in subtitles to pop up a dictionary. 

Maybe useless, just for reference.
By the way, I just found it had supported the TouchBar! Good job!

**Comment by sn0wyfall** [comment]
@lhc70000 Maybe force touch could be set as a trigger for an option that you could choose. For example, you could set it to take a screenshot or play/pause (just like you can with double clicking)

**Comment by g1084164986** [comment]
@lhc70000 Force Touch to display video information is an option as well. I think Force Touch can pop up a list contains some advanced function as default is a better choice.

**Comment by saagarjha** [comment]
@lhc70000 I've got Force Touch working on my branch, among other things: https://github.com/saagarjha/iina
Should I open a pull request?

**Comment by lhc70000** [comment]
@saagarjha Awesome, please open a PR.

**Comment by saagarjha** [comment]
Done.

**Comment by SchwiftyLife** [comment]
@lhc70000 force touch could open a popup window to show some options like :
1- screenshot
2- as @JasonSi said to define a word in subtitle
3- video info
4- choosing audio
5- choosing subtitle
3- custom actions ...
