### ISSUE TITLE
Provide option to keep subtitle the same size regardless of window zoom

### ISSUE THREAD

**Issue by wzxu** [lhc70000/iina#161]
Currently the subtitle font size gets zoomed with window size, which IMO is not desirable, but is default behavior, so I think an option would be nice. In mpv I believe it's done by setting sub-scale-by-window=no.

**Comment by lhc70000** [comment]
You can set `sub-scale-by-window=no` as extra mpv option in `Preference -> Advanced`, as a workaround currently.

We'll consider adding this option in next version since it has been requested more than once.

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
