### ISSUE TITLE
Fast forward 5 second goes bad

### ISSUE THREAD

**Issue by splitgrace** [lhc70000/iina#1612]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
> Fast forward 5 second goes well.

**Actual behavior:**
> When I pressing the fast forward button, the fast forward often is 26 seconds.Hope you will fix the bug.

- Crash report:
```
Null.
```

- MPV log:
```
Null.
```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
> Always

**Comment by TempSpas** [comment]
Might be related to #1372. Have you tried remapping it?

**Comment by splitgrace** [comment]
Thanks, it's OK.

**Comment by saagarjha** [comment]
Do let us know if you need anything else!
