### ISSUE TITLE
When closing the player window for an mp3 file, another window appears

### ISSUE THREAD

**Issue by Smons** [lhc70000/iina#1613]
When listening a local mp3 file, a normal player window appears with the title and controls.

However, if I click on the "Close window" button, the window disappears but another larger fully-black window appears on my main screen and the music continues. Only when I also close the new window, the music stops.

**System and IINA version:**

IINA 0.0.14.1 Build 55 (mpv 0.27.0)
macOS 10.12.6 (16G29)

**Expected behavior:**
When closing the window playing the mp3 file, the window should close without any other window being displayed AND the mp3 file should stop

**Comment by ErikMinekus** [comment]
Update to 0.0.15 or 1.0.0-beta1. Music Mode has been redesigned so that the "Close window" button actually closes the window, instead of switching back to regular mode.
