### ISSUE TITLE
可否让兼容下Homepod,现在播放视频后音频有延迟情况

### ISSUE THREAD

**Issue by tudi1909** [lhc70000/iina#1615]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**
最近在使用Homepod,使用系统自带的QuickTime音频无延迟,很正常,可否让支持下Homepod,解决下延迟问题,感谢有这么好的软件,辛苦了!

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by fuzhuo** [comment]
-[AVAudioSession outputLatency]
这个API可以得到当前音频的输出延迟，只要把视频delay一下就同步了。libmpv应该传一个 --audio-delay 的参数就行了不知道可不可以弄成负的…

**Comment by tudi1909** [comment]
感觉很神奇,普通用户可以操作么,还是只能开发者去调试?

**Comment by darren** [comment]
问题就这么解决了？

**Comment by ghuiii** [comment]
问题没解决吧，目前依然有这个问题啊

**Comment by zfan** [comment]
感觉不会解决了，都2年多了，iina没有针对HomePod的延迟问题给出升级方案

**Comment by kankankankankankan** [comment]
感谢 @qiudaomao 说出的方法，只不过没在这里说，大概方式是上面音频可以设置延迟 2s即可 同步

就是需要你手工设置有些麻烦，有个快捷键或者自动识别更好些！

**Comment by PhilipMok-cc** [comment]
#1853
