### ISSUE TITLE
key combo for fullscreen

### ISSUE THREAD

**Issue by tillepille** [lhc70000/iina#162]
the common keys to toggle the window fullscreen is **ctrl**+cmd+f

But in IINA its currently **fn**+cmd+f 

in my opinion it would be more consistent do stay with ctrl+...

**Comment by lhc70000** [comment]
It's quite weird... 
![e6e6cfe3-61a4-4443-a031-38205c713d96](https://cloud.githubusercontent.com/assets/8478049/21952893/40d5c1f2-da63-11e6-8c33-a6345b284ae4.png)

May I ask which language/keyboard are you using?

**Comment by tillepille** [comment]
Nevermind on 0.0.2 its correct.
