### ISSUE TITLE
Full Keyboard Access breaks usage of spacebar

### ISSUE THREAD

**Issue by euf** [lhc70000/iina#1624]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta1 (71)

**Expected behavior:**

After opening a video file from Finder, IINA should pause it on spacebar — regardless of system "Full Keyboard Access" feature.

**Actual behavior:**

When "Full Keyboard Access" feature is turned on is System Preferences (see pic.1), opening a video file from Finder makes IINA to put focus on "Picture in Picture" button (see pic.2), so spacebar toggles PiP mode instead of play/pause. 

![macos-sierra-system-preferences-keyboard-shortcuts-mission-control](https://user-images.githubusercontent.com/11754264/38673247-7411d8ca-3e59-11e8-9711-daa93459fe2f.png)

![2018-04-12 13 52 13](https://user-images.githubusercontent.com/11754264/38673267-815868e6-3e59-11e8-9ab1-4ed163b44eb2.png)

It's worth noting that after some clicks inside IINA window the focus moves somewhere and everything works correctly. 

**Steps to reproduce:**

1. Activate "Full Keyboard Access" in the System Preferences or by pressing <kbd>Control</kbd> + <kbd>F7</kbd>.
2. Open a Finder window and double-click a video file to open it.
3. When IINA launches and starts playing video, press <kbd>spacebar</kbd>.
4. See PiP toggling instead of play/pause.

- [x] MPV does not have this problem.

**How often does this happen?**

Every time.

**Comment by mrelwood** [comment]
This is quite a bothersome issue. It was introduced by an update (beta) about a month ago. I didn't realise it is related to the "Full Keyboard Access".

I hope this gets fixed soon.

**Comment by ErikMinekus** [comment]
@saagarjha #1657 fixes the issue for the main window, but not for Music Mode. In Music Mode the mute button is focused by default, so pressing the spacebar just toggles mute.

**Comment by alejx** [comment]
@ErikMinekus Fixed by ae76b9b
