### ISSUE TITLE
Need an option to close "adjust progress bar with two finger scroll"

### ISSUE THREAD

**Issue by ryanxci** [lhc70000/iina#1625]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**
- Need an option to close "adjust progress bar with two finger scroll"

**Actual behavior:**
This function may be triggered when I want to switch the screen，so I want disable that feature.

**Comment by ErikMinekus** [comment]
Go to Preferences > Control and set “Scroll horizontally to:” to None.

**Comment by ErikMinekus** [comment]
As I explained above this is already possible, so I think this can be closed.
