### ISSUE TITLE
Setting -> Video -> Speed -> Slider

### ISSUE THREAD

**Issue by hadeneh** [lhc70000/iina#1627]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 beta 1 Build 71

**Feature Request:**

**Actual behavior:**
In video Setting, in speed section, when moving the slider the key values doesn't make sense. why is it as follows: 1, 1.189, 1.414, 1.682, 2?????

**Expected behavior:**
The keys should either jump by 0.1 or at most 0.2.
This could be fixed and it gives more power to the user.

**Comment by saagarjha** [comment]
The slider follows an exponential scale, so each of those tick marks is actually 2<sup>0</sup>, 2<sup>1/4</sup>, 2<sup>1/2</sup>, 2<sup>3/4</sup>, 2<sup>1</sup>.

**Comment by hadeneh** [comment]
Thanks
But as a user I would prefer the small and predictable jumps as I explained above.

**Comment by saagarjha** [comment]
This would make it difficult to access commonly the labelled speeds. 0.25x is simply unrepresentable, and 16x would be beyond the range of the slider.

**Comment by vilinskyy** [comment]
@saagarjha hey, does this make the sound better while playback? I noticed, that when I speed up the video on Youtube (from Safari) or any other site (Coursera, Wistia) it speeds up and "destroying" sound, like making it high and less-hearable.

But whenever I use IINA's speeding up, it feels cozy even on 1.414! What's the trick? I want to learn!

**Comment by saagarjha** [comment]
No idea, the increments were chosen purely to make the slider "make sense" (in a certain sense) rather than for sound during playback. I'm sure IINA sounds just as good at 1.5x (which you can enter manually into the text field next to the slider); you're going to have to ask the mpv folks how they're doing this since we just delegate this off to their API.
