### ISSUE TITLE
Language selection for subtitle

### ISSUE THREAD

**Issue by pighair** [lhc70000/iina#1628]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta1 build 71

**Expected behavior:**
User can choose language of one subtitle file with smi extension, and IINA displays subtitles in the language only.

**Actual behavior:**
IINA does not have feature to select language of one subtitle file, and displays all subtitles.

**Steps to reproduce:**
Try attached smi subtitle. It contains 4 sets of subtitles. There are 4 classes for 4 different subtitle; .KRCC, .KOR, .ENCC, and .ENG. These classes are defined under <style> tag.
<SYNC> tag indicates timing information in milliseconds by having attribute start, and it can contain <P> tag with attribute class which distinguish language. IINA displays every line without considering class information.

**How often does this happen?**
Always.
[Iron Man 2 2010 3Li BluRay 720p.smi.zip](https://github.com/lhc70000/iina/files/1914085/Iron.Man.2.2010.3Li.BluRay.720p.smi.zip)

**Comment by lhc70000** [comment]
smi support is crappy in FFmpeg/mpv, and seems that no one is going to do something. Sorry but the best solution for now would be converting your subtitle to ass/srt.
