### ISSUE TITLE
Should I turn on Use physical resolution on retina screen?

### ISSUE THREAD

**Issue by kirbyzhou** [lhc70000/iina#1630]
(questions) Should I turn on physical resolution on retina screen?

If i watch a 4k-video without "physical resolution on retina screen", what is the behavior of IINA?
downscale to 1080p, then upscale to 2160p to show?

**Comment by lhc70000** [comment]
It won't perform any upscale or downscale of the video. This option only affects the window size (1x, 2x, etc), and the video is always rendered using physical pixel size.

**Comment by kirbyzhou** [comment]
I suggest the Window Size should be chosen more intelligent.
For example, play 4K / 1080p in the same Windows Size.
