### ISSUE TITLE
Cannot play LG_Colors-of-Journey-HDR with hardware decoder.

### ISSUE THREAD

**Issue by kirbyzhou** [lhc70000/iina#1632]
http://demo-uhd3d.com/files/uhd4k/LG_Colors-of-Journey-HDR.mp4

iMac (Retina 5K, 27-inch, 2017)

IINA-1.0.0-beta1

![image](https://user-images.githubusercontent.com/3401630/38880365-1abcd444-4298-11e8-911c-845cd0f9f242.jpeg)

VLC can play it with hw-decoder.

**Comment by lhc70000** [comment]
Please report to mpv if still having this issue.
