### ISSUE TITLE
Video size

### ISSUE THREAD

**Issue by CherryGo** [lhc70000/iina#1634]
**System and IINA version:**

- macOS 10.13.2
- IINA 1.0 beta1 build71

**Expected behavior:**
Video window size to actual size on external display.
 
**Actual behavior:**
When I choose use physical resolution on Retina displays. window will size to video size but on external display witch is in scaled resolution.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Sorry but I can't quite understand what do you mean. If you believe that it's a bug and it still happens in 1.0.0 beta 4, please provide a more detailed explanation with examples.
