### ISSUE TITLE
Please consider saving resources (CPU, etc.) while using IINA so Macs won't be too hot

### ISSUE THREAD

**Issue by AndyChen2005121** [lhc70000/iina#1641]
**System and IINA version:**

- macOS 10.12.6
- IINA 1.0.0-beta1 Build 71

**Expected behavior:**
Save CPU, memory and so forth so Macs won't be too hot while watching videos. Consider using something like 'Energy Saving Mode'.

**Actual behavior:** My MacBook Pro becomes **very, very hot almost all the time** when I use IINA to watch videos. the CPU temp goes high, sometimes even higher than 90℃ -- so I have to use a powerful fan to cool it down.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.
(not sure)

**How often does this happen?**
Every time.

**Comment by maaaarc** [comment]
1.0 beta has this problem. My cpu usage is 100% even when i'm not playing video. I installed 0.0.15 and problem solved.

**Comment by lhc70000** [comment]
Moved to #1724.

tl;dr This may be fixed in beta 2.
