### ISSUE TITLE
welcome window doesn't always update to latest video played

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1643]
Just now when I clicked on the IINA dock icon, welcome window popped up but it didn't show the last video I played. I had to find it in finder, started playing it then quit IINA shortly after. I did this a couple of time and then finally the welcome window updated with two new entries at the top. It must have initially missed the last two video I played. Weird.

IINA 1.0 beta1 (72)
osx 12.6

EDIT: Never mind, the welcome window updates after a quit/restart. Would be nice if it updated while running. Thanks.

**Comment by lhc70000** [comment]
Already fixed in the latest develop branch.
