### ISSUE TITLE
A video filter for removing/decreasing banding in videos that have it, like what VLC has (feature request)

### ISSUE THREAD

**Issue by MaxPower85** [lhc70000/iina#1645]
It would be nice to have a video filter to remove/decrease banding in videos that have it, like what VLC has under Window > Vide Effects... > Basic > Banding removal

Since VLC is open source, maybe you could examine it to see how does VLC manage to smoothen-out gradients and decrease banding in real-time without consuming too much resources.

VLC's filter for removing/decreasing banding seems to work pretty good even when playing 4k HEVC videos on an older 15" MBP Retina that doesn't have hardware acceleration for HEVC... I mean, the playback still seems pretty smooth even when that filter is on... and it doesn't seem to decrease the quality of videos that don't have banding... it only seems to improve visual quality when it's on... I didn't yet notice any downsides of keeping that filter on in VLC... it would be awesome if IINA could have something similar too.

**Comment by bodayw** [comment]
mpv (therefore IINA) already has it for a long time:

https://mpv.io/manual/master/#options-deband

**Comment by bodayw** [comment]
I have never tried to play around with deband parameters on my own, but on a general note, there will never be one good setting that's good for all. Stronger debanding will end up killing find details on the original image.

And I think it makes more sense to suggest this to mpv developers to improve their deband filter, and then IINA can use it. Since ``--deband=yes`` is included in mpv's ``--profile=gpu-hq``, it would be good for IINA to add the whole profile in the Settings altogether, as suggested in #587.

Either way, I am not sure activating debanding by default is a good idea for compatibility reasons, especially given that IINA enables hardware decoding by default.

**Comment by MaxPower85** [comment]
Well, IINA can use ffmpeg filters too... and gradfun is included with ffmpeg... and video playback for 4k HEVC videos with it seems much smoother than with mpv's deband filter on a Mac without hardware acceleration for HEVC... and for 4k H.264 videos gradfun filter seems a lot less demanding too on my Mac (Activity Monitor shows that CPU usage with with gradfun enabled was around 31% and about 295% with mpv's deband filter, for the same video).

BTW... I did some more testing with mpv's deband filter on it's default settings... and it seems to me that if you are dealing with low-bitrate online videos in lower resolution (like 720p) with more severe blocky artifacts, that it can make banding and blocky artifacts in those videos less noticeable than when you are using just gradfun with "1.4:16" settings... and if you combine it with gradfun, you can improve upon that also.

Here is some video that I found on YouTube to test it with, where deband filter seemed better... https://www.youtube.com/watch?v=UeDi1ezEIts

But FFmpeg's gradfun seems to me like it's better for Full HD and 4k videos with higher bitrate that just have the usual banding as a result of using 8-bit colors for gradients without film-grain.

For example... you can test it with this: https://www.youtube.com/watch?v=rWAp7E6OLok

Also... I didn't mean that de-banding should be enabled by default... I just meant that it would be good for that filter to be included with those settings on the filter list, so an average user could easily enable it for some average video if he wants, without having to spend much time reading some documentation and trying out different settings.

As I mentioned, I tested it with different parameters and on different videos and I was trying to find some settings that seemed close enough to VLC's de-banding options, which seem to work really well.

It seemed to mostly just smoothen-out the "bands" of very similar shades in backgrounds to resolve issues with usual banding that some average video might have (like if someone created gradients on a computer and didn't include any film-grain on those gradients before encoding the video with some average encoding settings which use 8-bit colors), but it doesn't seem to blur-out fine details which clearly don't resemble 8-bit banding.

For gradfun filter, "1.4:16" value means "1.4" for strength with "16" for radius... documentation says that strength can range from .51 to 64... and that radius can be from 8 to 32... so 1.4 for strength with 16 for radius isn't very strong... and it doesn't seem like it's affecting areas with details witch don't resemble the usual 8-bit banding... 

These are the video filters I've added (I don't enable them all, as it can be seen... but when I need some, I can enable it with one click)

![screen shot 2018-04-28 at 5 58 16 am](https://user-images.githubusercontent.com/37249460/39391783-5a40e3c6-4aa9-11e8-9112-bdbaa36948c3.jpg)

Using gradfun with "1.4:16" settings seems to me like it's the most optimal settings for most videos... 

Increasing the radius to 24 (so, using "1.4:24") can be useful if some videos have banding with wider bands/rings and there are still somewhat noticeable bands/rings from banding on the backgrounds when using just "1.4:16"... and decreasing the radius to 8 (so, using "1.4:8") would be OK if you only need it for videos that have some sort of banding with very narrow bands/rings... but usually, setting the radius to 16 seems like the most optimal settings in my opinion.

Changing the strength to .8 (point 8, so something like ".8:16") usually seems to give good results too... and it maybe useful if some videos have details in the background that don't stand out much and their shades are very similar to the shade of the background, so maybe you might want to decrease the de-banding strength a bit if those details are getting softened.

Increasing the strength to 2.8 (so something like "2.8:16") might be good for some videos that have banding where there is a somewhat bigger difference in color between the neighboring bands/rings, but for most videos it seems better to set strength to "1.4" because it looks like that with "2.8" some colors on darker backgrounds are getting a bit more noticeable "glow-like" effects few pixels around them (I guess it wouldn't be very noticeable, especially from a distance and it seems like a very faint "glow", but still someone might want to avoid some glow like that getting noticeable).

If someone wants to check that details which are clearly distinct from the background aren't getting lost with some de-banding settings, here are some 4k videos with lots of tiny details... 4k videos that really look like they were actually recorded in 4k and not just upscaled...

YouTube's encoding seems to introduce some banding and somewhat noticeable blocky artifacts, so it's a good way to test the de-banding filters with some of these: 

https://www.youtube.com/watch?v=yzlOUHE01eg
https://www.youtube.com/watch?v=2gEFIz2uFlE
https://www.youtube.com/watch?v=RXQ4JPxSrsI
https://www.youtube.com/watch?v=VF0cZYWCv1M
https://www.youtube.com/watch?v=CXzWoaESyJM

And sample footage from cameras like Sony Alpha A7S or A7S II would also be good if some wants videos with lots of fine details.

**Comment by tuqueque** [comment]
Thank you VERY MUCH, @MaxPower85 for your tips... I was looking on the web for a nice ffmpeg filter to remove/cover banding in video playback and I stumbled upon this discussion. It works great!
