### ISSUE TITLE
Preferred language text field (NSTokenField) causes the app unresponsive

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#1647]
**System and IINA version:**

- macOS 10.13.5 beta
- IINA dev

**Steps to reproduce:**
- Open preferences, Subtitle tab
- Enter a letter in "Preferred language" text field, and remove suggestion suffix, i.e. leave a "a" in the text field.
- Deactivate the preference window.

**Actual behavior:**

The app is unresponsive. Main thread is blocked.

**Other Information:**
After the preference window is deactivated, the system calls `tokenField(_:representedObjectForEditing:)` and `tokenField(_:displayStringForRepresentedObject:)` over and over again, so that main thread is blocked.

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
Isn't it a Cocoa bug?
