### ISSUE TITLE
两个屏幕时，全屏播放，一个屏幕黑屏。

### ISSUE THREAD

**Issue by xirwajim** [lhc70000/iina#1648]
**System and IINA version:**

- macOS 10.13.4
- IINA v1.0.0-beta1

**Expected behavior:**

两个屏幕时，作为独立显示用，全屏播放，一个是全屏，另一个屏幕黑屏。无法一个看电影，另一个做别的事儿。别的播放器正常。

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
@xirwajim 请检查你是否开启了「全屏播放时使其他显示器黑屏」的选项。

**Comment by xirwajim** [comment]
@lhc70000 嗯嗯，确实选中了这个，我没注意这个。还以为 bug 呢。。
