### ISSUE TITLE
The interval of speed increasing can set as 0.5X. From 1.5X,2X,4X. 1.5 times speed is the best for studying speed

### ISSUE THREAD

**Issue by Yanzlllll** [lhc70000/iina#1649]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Same as #1644
