### ISSUE TITLE
Can you make the scroll-to-seek speed more like QuickTime? Right now, even on minimum settings it seems way too fast for videos that are a few minutes long

### ISSUE THREAD

**Issue by MaxPower85** [lhc70000/iina#1651]
If you open a video that's a few minutes long in IINA and you scroll to seek, even moving your fingers like 1 or 2 cm relatively quickly can result to skipping to the next video and even almost skipping that 2nd video too, even on minimum sensitivity settings... 

I'm aware that the speed is kind of similar to seeking in VLC, but that seems way too fast for a Mac trackpad that can scroll fast with faster movement.

Seeking so fast when scrolling seems like it was designed primarily for some mouse with a scroll-wheel that doesn't distinguish between slower or faster scrolling and just scrolls in steps one line at the time for one scroll-wheel step (for one of those "click" sounds that it makes as it turns)... or for some older Windows laptop that emulated the scroll-wheel when scrolling... and a mouse with a scroll-wheel can often take lots and lots of turns just to scroll to the end of some longer web page.

But on a Mac trackpad, fast movement can scroll much faster than slower movement... one longer swipe with two fingers on a Mac, if done fast, can scroll all the way to the end of some longer web page, while slower moves can scroll very slowly... and, for example, in QuickTime with a long and fast scroll movement a user can skip to the end of the video, if that's what he wants, but with a short and quick movements it doesn't skip to the end.

It would be good if medium seek sensitivity in IINA was more like that in QuickTime.

And VLC is a multi-platform app, so I guess it's understandable if something in it was primarily optimized for what some average Windows users may have wanted.

BTW... I also think that it would be good if seeking stopped when it reaches the end of the video, so it wouldn't continue to seek into the next video and skip it too if someone scrolled too fast to play the next video, but ended up skipping it.

**Comment by lhc70000** [comment]
The reason is that by default it uses key frame seek, so it depends on how many key frames the video has: If it as a key frame every 10 seconds, then you'll jump at least 10 seconds each time.

Using exact seek (Pref - Control) will make this better, but it'll consume lots of CPU when you scrubbing in very large files.

IINA is based on mpv, which is also a cross-platform player (although it's better than VLC in my opinion). Currently there's no decoder can provide a smooth experience as QuickTime's.

**Comment by lhc70000** [comment]
QuickTime seeks literally frame-by-frame (including key and non-key), so of course it will be “slower” and smoother. As I mentioned above, the only solution in IINA is to use exact seek, which can mimic this behavior, but not perfectly.

**Comment by saagarjha** [comment]
@lhc70000 Could we modify the seeking speed to match the number of keyframes we have? If we have very few keyframes, we could purposefully just require more scrolling to get to the next keyframe.

**Comment by qacizar** [comment]
Still super sensitive scrolling, how to fix it?

**Comment by ManasDas555** [comment]
Seeking too fast.. Any way to slow down ? on large and small length videos it feel way too speed up. I am used to QT seeking. exact seeking stutter , is there a way to buffer few seconds on the ram so the seeking can be smooth like butter and still be fast?
