### ISSUE TITLE
Selecting “<None>” in OSC’s subtitles menu has no effect

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#1653]
I have configured my OSC’s right buttons to include the “Choose subtitle track” button. That button pops a menu (as opposed to the right pane). Selecting a subtitle there works, however selecting “None” as the subtitle has no effect.

<img width="524" alt="screen shot 2018-04-28 at 12 18 13" src="https://user-images.githubusercontent.com/2270433/39394750-51598328-4ade-11e8-8fa0-79c0ef3334a8.png">

**Comment by alejx** [comment]
This is not a bug, but a design issue. <None> here is not to disable subtitle track. Entries above the separator is embedded and matched external subtitles; things below that are alternative extenal subtitle files. If you have unmatched subtitle files (e.g. you are watching ep1, and subtitle of ep2 also in the same folder, it would be a unmatched file), they will show up here. <None> means there's no unmatched file.

**Comment by LeoNatan** [comment]
In that case, why is the same <None> label used as the other menu, where it means no subtitle? There should be a much clearer distinction, such as a disabled “No unmatched subtitles” menu item, and “None” which means no subtitles.

**Comment by LeoNatan** [comment]
I’d say that’s a serious UX antipattern, bordering the level of a bug.

**Comment by alejx** [comment]
I agree with you. I will try to make it clear.
