### ISSUE TITLE
[Feature Request]Shortcut to increase/decrease subtitle size.

### ISSUE THREAD

**Issue by cool8jay** [lhc70000/iina#1659]
**Feature Request**

Shortcut to scale up/down subtitle.

For example, ⌘⇧+ and ⌘⇧-.

Thanks.

**Comment by lhc70000** [comment]
![image_2018-04-30_01-31-46](https://user-images.githubusercontent.com/8478049/39416936-56e73e4c-4c83-11e8-9be3-777c5af8ffdf.png)
You can add them in Preferences :)
