### ISSUE TITLE
Support more online subtitle source

### ISSUE THREAD

**Issue by basavaraj1995** [lhc70000/iina#166]
player does not support external subtitle and it always download unknow language subtitle from online

**Comment by lhc70000** [comment]
> player does not support external subtitle

- The easiest way to load an external subtitle is by drag & drop a subtitle file into window.
- You may also load external title from menu (Subtitles->Load external Subtitle) or quick panel (Cmd+S-> Load external Subtitle).
- In Preference -> Subtitles, There's also an option, allowing IINA auto loading all subtitles in same folder.

> it always download unknown language subtitle from online

- Please see the change log (and Preference -> Subtitles), it only support `shooter.cn`  in this version. It **should not** download online subtitles unless you chose this action from menu or pressed the shortcut keys. If it downloads "automatically" without your permission, please update me here.

**Comment by basavaraj1995** [comment]
And always it downloads other language subtitle and y not English subtitles?

**Comment by lhc70000** [comment]
@basavaraj1995 

> it only support shooter.cn in this version. 

Which is a Chinese website. I'm so sorry for that, please refer to the change log: We would like to support `opensubtitles`, however their API is rather complicated and requires some registration stuff, so it will be added later in 0.0.3.

**Comment by lhc70000** [comment]
OpenSubtitles support has been added in 0.0.7.

**Comment by basavaraj1995** [comment]
Thank you..
