### ISSUE TITLE
version 0.0.15 doesn't display the subtitle even though the subtitle panel shows it has already loaded the correct one

### ISSUE THREAD

**Issue by pipi607** [lhc70000/iina#1663]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Please check if it's the same issue as #757.
