### ISSUE TITLE
[UI Enhancement] Remove numerical volume indicator in music mode

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#1664]
**Introduction**
The current volume controls in MiniPlayer is kind of counterintuitive. When I want to adjust volume, I firstly go to the speaker icon. However, in the current design, clicking on the speaker icon will toggle mute/unmute. In my opinion, it is a little bit weird to have a mute button in music mode. Why do we want to mute music? We can simply pause it when needed.

**Proposal**
I suggest that remove the numerical volume indicator and show the popover volume slider when the user clicks on the speaker icon.

iTunes volume icon below
![image](https://user-images.githubusercontent.com/20237141/39605201-fef743b6-4ef4-11e8-8477-c964062fa172.png)

**Comment by saagarjha** [comment]
I think we should reconsider how we handle volume. Why do we have separate mute and volume controls? When the volume reaches 0%, we should mute automatically, which matches how macOS works.
