### ISSUE TITLE
Duration stops at 10:18 minutes

### ISSUE THREAD

**Issue by marcotini** [lhc70000/iina#1670]
- macOS 10.13.4
- IINA 0.0.15.1

Duration stops at 10:18 minutes even if it lasts longer than 1 hour.

<img width="805" alt="screen shot 2018-05-05 at 10 52 46" src="https://user-images.githubusercontent.com/3670558/39661533-4e520e96-5053-11e8-80ff-627f0c18db2c.png">
<img width="458" alt="screen shot 2018-05-05 at 10 58 29" src="https://user-images.githubusercontent.com/3670558/39661534-4e6c0e0e-5053-11e8-8dd3-c185a81fc6f5.png">

**Comment by alejx** [comment]
This issue should be related to mpv.
