### ISSUE TITLE
IINA thinks txt file is a subtitle???

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1675]
If I have a txt file in the same folder as video, IINA pops an error message before playing that external file format not supported. Wierd. It's just a txt file with info about the video file. If I change the txt file to .nfo or something, no error message.

**Comment by alejx** [comment]
I don't like it either. Here's previous discussion on txt format subtitles: https://github.com/lhc70000/iina/issues/635

**Comment by bodayw** [comment]
mpv removed auto-loading .txt as subtitles since 0.24.0.

There was another debate: mpv-player/mpv#4144.

**Comment by jerkstore369** [comment]
I've never even run into a .txt subtitle file. Who uses these? Are they popular in europe or something? Anyone releasing subtitles in txt format should have their hard drives erased 😛

**Comment by LeoNatan** [comment]
Often these .txt subtitles are just .sub files with the wrong extension. I'm glad to see cooler heads prevailed and .txt support was removed.
