### ISSUE TITLE
brew cask install 提示文件不对。

### ISSUE THREAD

**Issue by user-evan-chen** [lhc70000/iina#1686]
似乎 brew cask 记录的值和下载下来的文件的值不一致，所以无法完成安装。请检查。

**Comment by alejx** [comment]
用 cask 下下来是哪个版本?

**Comment by alejx** [comment]
Fixed by https://github.com/caskroom/homebrew-cask/commit/15c7d19c20c612a2358f0f735f0b4d112ed9d48c .
Closed.

**Comment by alejx** [comment]
@user-evan-chen 更新一下 cask 再试试, 应该可以了
