### ISSUE TITLE
IINA got worse picture than QuickTimePlayer

### ISSUE THREAD

**Issue by DanteAndroid** [lhc70000/iina#1687]
- macOS 10.10.3
- IINA 0.0.15.1

QTP：
![image](https://user-images.githubusercontent.com/10005563/39794256-ff79ddea-537b-11e8-8c11-f56d1fafd6f8.png)
IINA：
![image](https://user-images.githubusercontent.com/10005563/39794311-46b10daa-537c-11e8-9d49-bc1cdf28240a.png)
**Please click to view full image**, I think the gap is quite obvious. Did I expect too much?

Besides, I think the title of IINA is barely readable.
![image](https://user-images.githubusercontent.com/10005563/39794379-998469d2-537c-11e8-845e-7d12a0640f1b.png)

**Comment by alejx** [comment]
Base on the image you provided, I suspect you are not using the latest version of IINA. Please upgrade to the latest one and test whether the issues still exist.

**Comment by DanteAndroid** [comment]
@alejx Well the versions I provided above is correct. 
![image](https://user-images.githubusercontent.com/10005563/39794588-a47651ce-537d-11e8-9746-a67911df7103.png)
FIY, I use Hackintosh, don't know if that concerns

**Comment by alejx** [comment]
Mackintosh might be a problem, the welcome window in your image seems bad too. I cannot reproduce the issue that filename label is white.

**Comment by lhc70000** [comment]
Please upgrade to a newer macOS version as IINA 1.0 will drop support for macOS 10.10.

The video quality issue should be an upstream (mpv) problem.
