### ISSUE TITLE
Accessibility Feature Request: Overdrive Audio Gain / Level Up to 250%

### ISSUE THREAD

**Issue by adamlogan** [lhc70000/iina#1689]
**System and IINA version:**
- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
I'm hard of hearing and I really need to be able to overdrive the volume to be able to hear media at perceptual hearing-abled people equivalent sound levels. I suggest allowing for overdriving up to 250%.

**Actual behavior:**
IINA does not allow overdriving at all, once you reach 100%, that's it. I typically overdrive normal decibel audio to 130%, sometimes to 200% if the media is quiet. 250% gives us a bit of headroom.

For those wondering, I use in-ear headphones, Bose wired Soundsport to be specific, as it resembles wearing hearing aids sans the inconvenience of charging batteries and syncing Bluetooth.

**Comment by alejx** [comment]
IINA could change maximum volume.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/20237141/39853195-585c320e-53e6-11e8-8d7e-3c6e46210e86.png">
You can make the maximum volume up to 1000.
