### ISSUE TITLE
Resume playback

### ISSUE THREAD

**Issue by scalene-jl** [lhc70000/iina#169]
It would be wonderful if iina should be able to resume playback at a later invocation.
Maybe with a bookmark plist file in ~/Library/Application Support ?

**Comment by megadr01d** [comment]
Please search the issues before posting. Duplicate of https://github.com/lhc70000/iina/issues/128.

**Comment by lhc70000** [comment]
Also duplicate with #10.

**Comment by lhc70000** [comment]
Close due to duplication.
