### ISSUE TITLE
Items remained on main UI after clear menu

### ISSUE THREAD

**Issue by hao-lh** [lhc70000/iina#1698]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.15.1

**Expected behavior:**
Open recent was cleared out
Items on main UI were cleared out

**Actual behavior:**
When I clicked Clear Menu via File -> Open Recent, items would be cleared out in open recent, however, items remained on main UI as following:

![](https://i.loli.net/2018/05/14/5af98bde600f2.jpg)

**Steps to reproduce:**
File -> Open Recent -> Clear Menu

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
You have to restart iina to refresh the welcome window. #1696 fixed it and will be available in 1.0.0 beta 2.
