### ISSUE TITLE
Wired Resolution when open wmv.

### ISSUE THREAD

**Issue by Co2333** [lhc70000/iina#1699]
- macOS 10.13.3 (17D47)
- IINA newest beta.

Expected behavior:
Open normnally.

Actual behavior:
See photo pls. It just too big and out of screen.

![qq20180514-213157](https://user-images.githubusercontent.com/25259084/40000523-979d5cc8-57be-11e8-8ea3-ddf1b374f61d.png)

Steps to reproduce:Open the file.

I dont't know if MPV does not have this problem.

How often does this happen?
Every time.

**Comment by lhc70000** [comment]
Does it happen only for some specific files? If so, please better share it with us.
