### ISSUE TITLE
Audio track keeps choosing 'None'

### ISSUE THREAD

**Issue by element515** [lhc70000/iina#1700]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
Play audio track

**Actual behavior:**
Defaults to 'None' and refuses to change.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
The audio track keeps preventing me from choosing anything but None. Only way I have found to fix this is to delete the 'audio filter' that is created. This only fixes the issue for one video. Never had this problem before. 

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Did you create the audio filter? Maybe it failed so that we could not apply it. Do you have the log when it occurred?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NaeBrains** [comment]
I am having exactly the same problem. I've gone back to an earlier version of IINA until there is a fix.

**Comment by lhc70000** [comment]
I’m almost sure that it’s caused by unrecognized audio filters. Please check Audio Menu - Audio Filters and remove them if there’s any.
