### ISSUE TITLE
Can apply rotation to subtitles?

### ISSUE THREAD

**Issue by zcjbak** [lhc70000/iina#1702]
**Actual behavior:**
IINA is a cool player in macOS and I'm using it as my main player, it meet all I need until today I bought a SONY mini projector, that I can only mount it with a bottom-up position on my bed. To watch videos I did a rotation under menu Video but it went like this.
![1526339313201](https://user-images.githubusercontent.com/39283139/40028025-937f4be2-5791-11e8-99dd-37dae2f626ad.jpg)

and it should be this way
![westworld s02e04 720p web h264-deflate-0001](https://user-images.githubusercontent.com/39283139/40028301-e94ab6fa-5792-11e8-891f-e7541a379215.png)

Well, I know I can change the direction lay down without touch anything, but also think subtitle is a part of the video playing back, they should go the same way.

**Comment by inflation** [comment]
Can you rotate the display instead?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zcjbak** [comment]
> Can you rotate the display in system settings instead?
As I said, I can rotate the display or myself, but subtitles should always be the same direction as picture.
