### ISSUE TITLE
Crash reports OS X 10.11.6

### ISSUE THREAD

**Issue by megadr01d** [lhc70000/iina#171]
Some crash reports. I haven't been able to test IINA yet because it crashes with every single movie I try to open.

[iina-crash-report.zip](https://github.com/lhc70000/iina/files/706036/iina-crash-report.zip)

**Comment by lhc70000** [comment]
It's a crash from mpv rather than IINA, and we never heard this.

I cannot figure out the actual problem at once, but according to the log it crashed when mpv tries to find external subtitles. Maybe you can disable auto loading subtitles (in Preference -> Subtitles) and try a file without any subtitles in same folder.

We'll update here on any discovery.

**Comment by megadr01d** [comment]
Thanks for the follow-up but unfortunately, no luck.
I tried it with auto loading disabled and all subtitles in the same folder, and it always crashes on all local movies with or without subtitles, both in the internal and external HD, and even on a [remote stream](http://techslides.com/demos/sample-videos/small.mp4) (File > Open URL).

The window shows up for a second (all black, with the controller, doesn't load the movie) and IINA quits.

I don't need to install any extra components, right?

[iina-crash-report-auto-sub-disabled.zip](https://github.com/lhc70000/iina/files/706177/iina-crash-report-auto-sub-disabled.zip)

**Comment by lhc70000** [comment]
> I don't need to install any extra components, right?

Yes, theoretically. 

Do you have mpv installed and does mpv works well?

**Comment by megadr01d** [comment]
I didn't have mpv installed. I installed it with `brew install mpv` and it works just fine with all movies, with or without subtitles. IINA still fails.
Anyway, thanks and no hurry, I'll keep an eye on further developments.

**Comment by megadr01d** [comment]
Closing this one. 0.0.4 build7 fixed this issue. No more crashes so far. Wow, seeing it in action for the first time, what a beaut.
