### ISSUE TITLE
内容被窗口裁切

### ISSUE THREAD

**Issue by uedvincent** [lhc70000/iina#1713]
播放视频时右边内容被窗口裁切掉一部分，使用内建的预览并未出现此问题。
![image](https://user-images.githubusercontent.com/21360118/40227519-5711af5a-5ac1-11e8-8ec6-797b6ff93161.png)

- macOS 10.13.4
- IINA 1.0.0-beta1 Build 71

**Comment by alejx** [comment]
有可能是硬解的问题, 请尝试关掉硬解, 看看有没有恢复正常.

**Comment by uedvincent** [comment]
@alejx 关掉硬解确实好了，不过硬解还是很有必要使用的啊，这个有办法修复么？

**Comment by alejx** [comment]
Duplicate of #1603.
