### ISSUE TITLE
Subtitle stays on screen for too long

### ISSUE THREAD

**Issue by whoinoi** [lhc70000/iina#1716]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

When you switch subtitles on during a part where there should be no subtitle line then there should be no text on the screen.

**Actual behavior:**

Say I have a movie with conversational parts and non-conversational parts and one subtitle A. During a conversation I switch from no subtitles to A and then back to empty. When the conversation is over I switch again to A. Then A shows the text from when it was turned off the last time during the conversation. The text stays there until a new conversation starts, so until A gets updated with new text. The time stamps at which A displays the new text are correct but during the break of conversation it shows the last text continuously for however long this break of conversation lasts.

This hasn't been there before in IINA and is only since recently like that.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

I set myself the keyboard shortcut U for switching through subtitles. Then during a conversation I can press U quickly to turn the subtitle on and back of. Try this with a movie and you'll experience the bug I described above.

- [ ] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
This should be related to mpv. I think you’d better report this issue to them.

**Comment by whoinoi** [comment]
@lhc70000 They responded and said it doesn't appear to be a mpv problem. Can you check your IINA again? I can provide a screencast of IINA if necessary.

**Comment by inflation** [comment]
The subtitle is handled by internal mpv totally. You need to provide more info like logs or your subtitles for any of us to know what happened. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoinoi** [comment]
@inflation Alright, here are the logs and the sample file for the sequence that is shown in the screencast.

Logs: [mpv.log](https://github.com/mpv-player/mpv/files/2108093/mpv.log), 
[iina.log](https://github.com/lhc70000/iina/files/2108104/iina.log)

Sample file: [sample.mkv](https://mega.nz/#!T7ZRBSBZ!NmTe5taGGnLjJOmOZc01xjXplWrBTpHtVmwPO-LUba8)
(see min. 43:30)

I also submitted this to mpv in the linked issue above.

**Comment by alejx** [comment]
It seems that mpv team can reproduce this issue, closed for now.
