### ISSUE TITLE
启动视频后，声音抖动，语速慢

### ISSUE THREAD

**Issue by tjzhaomengyi** [lhc70000/iina#1723]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
检查下播放速度是不是 1 倍。

**Comment by tjzhaomengyi** [comment]
囧了..果然是。不知道是不是手抖怎么弄得，卸了几次还是一样，有的视频能正常，有的还是这个问题，原来是碰了倍速，启动视频竟然不是默认1X速度。没问题了，多谢多谢
