### ISSUE TITLE
avast found an virus in iina-cli

### ISSUE THREAD

**Issue by Patrik-svobodik** [lhc70000/iina#1728]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
No viruses
**Actual behavior:**
Avast says it is MacOS:BitCoinMiner-AS [Trj]

WTF is going on there? I really like this player, it is the best I have ever used, but idk if this is a false positive but I am partially scared, YES, my Mac was infected and the same thing happened with a lot of other apps but I fixed them, but this is a different file, everything other was libswiftDispatch.dylib infected, but this is different

**Comment by inflation** [comment]
`libswiftDispatch.dylib` is a system provided library. It should be a false positive.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lhc70000** [comment]
First of all, IINA is an open source software, which means that there's very little change for us developers to inject malicious code without being discovered. If you don't trust it, you can even build it by yourself. You can find the source code for iina-cli [here](https://github.com/lhc70000/iina/blob/develop/iina-cli/main.swift). It's only a hundred lines of code, imports nothing but the system library, and doesn't make any network request. Please feel free to examine if there's `BitCoinMiner` in it.

However, **open-source also means that anyone can release a binary with modified code**. If you download IINA from anywhere other than
- GitHub release;
- Official website or Homebrew cask;
- In-App Update for Apps downloaded from above sources;

Please notify me and re-download from one of the sources listed above.

I tried some online scanning tool:

iina-cli in 1.0.0 beta 1:
> https://www.virustotal.com/#/file/78f38fb707fce1504abd14874c74ea526df0add44a0b4faa694a17de287018ee/detection

iina-cli in 0.0.15.1:
> https://www.virustotal.com/#/file/0ac83cde875e5a083471a4f91b343c9ddc9ead00ab2ba152a34dd762affc21c1/detection

There's no report of detection; and you can also compare them with the binary on your own computer. Please pay attention to the "Signature info":

![dce20b00-07f4-45a5-9259-eab5b97d6a2a](https://user-images.githubusercontent.com/8478049/40581847-3ecf6664-6195-11e8-8a7b-fcdcd97e8b33.png)

**This binary should be signed using my developer certificate, and you should be able to find my team identifier (67CQ77V27R) and my name here.**

**Comment by Patrik-svobodik** [comment]
Ok, i will trust you, but it is still weird, how could system library be infected w/ SIP on?

**Comment by lhc70000** [comment]
`libswiftDispatch.dylib` is only copied from the system during compiling. It's then _packed into_ the app bundle because not all macOS have this lib. So attackers, for example, can replace the original lib with a modified one (but still named `libswiftDispatch.dylib`) and release a cracked app bundle for download.

**Comment by saagarjha** [comment]
> not all macOS have this lib

I believe every version of macOS that IINA runs on has a version of the Swift runtime. However, of course, it's not binary compatible with the one that IINA expects, which is why it ships with its own copy.
