### ISSUE TITLE
Issues with Resume option in welcome window

### ISSUE THREAD

**Issue by ErikMinekus** [lhc70000/iina#1730]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta2

**Issues:**

1. The new Resume option in the welcome window ignores the "Resume last playback position" preference. The last played file is always resumed, and there is no way to play it from the beginning.
2. When opening a different file from the same directory as the last played file, and then skipping to the last played file, it sometimes resumes, and sometimes plays from the beginning.
3. After clicking File > Open Recent > Clear Menu, the last played file is still visible in the welcome window.
4. After playing a file, closing the window, and re-opening the welcome window, the last played file is [displayed twice](https://puu.sh/AulRt/14b618cc74.png). Both options resume playback.

I think this feature solves a problem that doesn't exist. If the "Resume last playback position" preference is checked, all files should resume. If it's unchecked, none of the files should resume. A separate Resume option for the last played file has a lot of edge cases, which complicate the code.

**Comment by lhc70000** [comment]
Does "Resume last playback position" work for you in earlier versions? I just checked the code and found that, astonishingly, this option is not linked to mpv at all, which means that mpv will always resume every file regardless of whether you checked this option.

**Comment by lhc70000** [comment]
1. This should not happen. All files shares the same option.
2. That's how mpv handles resuming. The watch_later file is deleted once you switched to other files in the playlist.
3. This window can display entries either in playback history or recent menu, so the last played file is saved independently.
4. It's a bug.

**Comment by ErikMinekus** [comment]
Yes, "Resume last playback position" works as I expect in earlier versions. If checked, all files are resumed. If unchecked, all files are played from the beginning.

**Comment by ErikMinekus** [comment]
1. I did see https://github.com/lhc70000/iina/commit/0a1038ab77d22f49718d174ab7877290e5757a32, which hides the new Resume option if "Record recent files" is unchecked. But I wish it was also hidden if "Resume last playback position" is unchecked.
2. It doesn't seem to work correctly in IINA then. I can freely switch between files in the playlist, and it will always resume the file that was considered the last played file when the window was opened. All other files are played from the beginning.
3. I understand, so the last played file should be cleared if the playlist history / recent menu is empty.

**Comment by ErikMinekus** [comment]
It's been fixed, so I'm closing this. I think #1772 can be closed as well.
