### ISSUE TITLE
Buffering seems to have been broken

### ISSUE THREAD

**Issue by alayliercan** [lhc70000/iina#1732]
**System and IINA version:**

- macOS 10.12.6
- IINA 1.0.0-beta2 (80)

**Expected behavior:**
No momentary frozen pictures during playbacks over a NAS device.
No constant buffering dialogs showing up during remotely hosted file playbacks.

**Actual behavior:**

I have a Synology NAS where keep some TV shows and films. I had been watching those video files without any issues with IINA 1.0.0-beta1(71) up until I updated to new release IINA 1.0.0-beta2 (80).
Same video files, same configuration but with this version of IINA the picture gets frozen for about 2 or 3 seconds randomly during playback while the audio continues naturally. And it happens multiple times during playing a video that is roughly 30 minutes long.

I guess the culprit might be this new buffering algorithm which you seem to have implemented. Here's why I think so:

I have a dedicated server that has a high speed connection by which I download films, create M3U playlist files and watch them remotely by using IINA. Again, up until recently I had been watching them without any issues with IINA 1.0.0-beta1(71). However right now whenever I skip forward or backward 10s or 60s I see this new half transparent buffering dialog showing up on the middle of the screen, and it takes moments for a video to resume playing. I had never had this issue in the past while using beta1(71), not even after doing multiple huge 300s skip forwards.
I even managed to find the old installation image and downgraded to 1.0.0 beta1(71) just to test same playlist file. No waiting time between skips whatsoever.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
For frozen picture issue, try watching a 30min or longer video file with 1280x720 dimensions over a NAS via cable connection.
For buffering issue, just play a full hd video by using IINA's Open URL feature.

- [x] MPV does not have this problem.

The release notes for beta2(80) does not say that you have updated MPV and the thing were working just fine with beta1(71) so I assume it's got nothing to do with MPV.

**How often does this happen?**
Frozen picture issue happens randomly 3 or 4 times during a 30min long video.
Unnecessary buffering happens all the time.

**Comment by lhc70000** [comment]
> The release notes for beta2(80) does not say that you have updated MPV and the thing were working just fine with beta1(71) so I assume it's got nothing to do with MPV.

Actually there is: https://github.com/lhc70000/iina/releases/tag/v1.0.0-beta2

> Update to mpv 0.28.2 with FFmpeg HEAD.

**Comment by alayliercan** [comment]
You're absolutely right. Sorry for that!
I just downloaded latest version of MPV to see if it's root of the issue and sadly it seems to have this same momentary frozen picture issue. I guess until they fix it it's beta1(71) for me then.
