### ISSUE TITLE
iina 播放列表无法正常显示m3u视频流频道名称

### ISSUE THREAD

**Issue by neverzyw** [lhc70000/iina#1733]
今天更新最新beta版本后，发现标准的m3u播放列表无法正常读取频道名称，全部显示为播放链接。上一个beta版本还是可以正常读取前面的频道名称的。

m3u播放列表内容格式为：
#EXTM3U
#EXTINF:0,广东卫视
http://XXXX/XXXX.smil
#EXTINF:0,广东珠江
http://XXXX/XXXX.smil

**Comment by alejx** [comment]
Duplicate of #1735.
