### ISSUE TITLE
Show quick settings panel shortcut

### ISSUE THREAD

**Issue by Pbearpbear** [lhc70000/iina#1736]
Iina is just great!  I've been using it as my main video player for some time now.

Just one question.  
Up until build 0.0.14.1 the shortcut key for "show quick settings panel" was broken down into three sections; command+S for subtitles, command+V for video, and command+A for audio.  It seems in the latest builds I can only add one shortcut for all three and then click my way around.  Is there a workaround?

Thanks in advance.

**Comment by saagarjha** [comment]
This seems to work for me; have you tried going into the "Key Bindings" section of Preferences and setting up shortcuts for `@iina video-panel`, `@iina audio-panel`, and `@iina sub-panel`?

**Comment by Pbearpbear** [comment]
Thanks saagarjha!
It worked perfectly!  Now I can keep up with the updates.
Thanks again!

**Comment by saagarjha** [comment]
No problem.
