### ISSUE TITLE
How's the battery usage vs VLC

### ISSUE THREAD

**Issue by theonlygusti** [lhc70000/iina#1738]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

# Is this app any good for battery life?

If I use this instead of VLC, will my battery last longer or shorter?

**Comment by ultratiem** [comment]
It's actually trivial to tell. Set up a simple experiment. Turn off any apps that automatically check for updates. Reboot to clear everything and make sure nothing else loads at start up. Make sure your battery is fully charged to reduce math. 

Next open any video file with VLC. The longer the better so you can get some time. Let it play, say for 3 hours. Make note of your battery life. Recharge back up to 100%. Next open the exact same video file with IINA and run it for the exact same 3 hours.

Then compare the two. There will be some error, but it'll be good enough to get a baseline. Come back and let us know the results ;)

**Comment by theonlygusti** [comment]
Is it possible to optimise IINA any further for battery life?

**Comment by inflation** [comment]
@theonlygusti As I said, use hardware decodable codecs. For a modern Mac, 8-bit H264 is a safe bet.

**Comment by theonlygusti** [comment]
@inflation it looks like I can't choose the codec? I just get Auto/Disabled

**Comment by inflation** [comment]
@theonlygusti You can't "choose" codec when you are playing the video. You can first check if IINA is hardware decoding by press <kbd>Cmd</kbd>+<kbd>i</kbd> to show the "Inspector" window. 
![image](https://user-images.githubusercontent.com/2375962/40869905-ac1417dc-65f1-11e8-8bb6-fe9775245e03.png)
If there is a "Hw Decoder", then it is using hardware. If no, you need to convert your file first.
