### ISSUE TITLE
IINA 1.0.0-beta2 project no longer buildable on macOS Sierra

### ISSUE THREAD

**Issue by Kadigan** [lhc70000/iina#1739]
The latest version is coded against Swift 4.1 available in Xcode 9.3+. However, macOS 10.12 is compatible with Xcode up to version 9.2, which only supports Swift 4.0.

Attempting to build IINA on Xcode 9.2 results in:

`Value of type 'IteratorSequence<NSFastEnumerationIterator>' has no member 'compactMap'`

**System and IINA version:**

- macOS 10.12.6
- IINA 1.0.0-beta2-2d2e0e8

**What can be done:**

a) possibly - use a shim, like https://gist.github.com/BasThomas/d03e138a9bb098d347c52ca7d6870a45 (unfortunately, I have no clue where to put that), or

b) clearly indicate that Xcode 9.3 (and hence macOS 10.13.2 High Sierra) is a **prerequisite** to building IINA on the Wiki pages.

Apparently there's a way to make Xcode 9.3 work on macOS Sierra, but it's a hack so I'm not including it here.

**Comment by lhc70000** [comment]
> clearly indicate that Xcode 9.3 (and hence macOS 10.13.2 High Sierra) is a prerequisite to building IINA on the Wiki pages.

Updated, thanks.

**Comment by Kadigan** [comment]
For the record, the "make Xcode 9.3 work on macOS Sierra" _hack_ - while hacky - _does actually work_, so I ended up happy in the end. It's still a hack, and shouldn't be recommended to anyone.

Thanks!
