### ISSUE TITLE
Add an open panel when click app icon in dock and no video is loaded.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#174]
Like other apple apps.

**Comment by LeoNatan** [comment]
This already exists in the options.

**Comment by alejx** [comment]
@LeoNatan Sorry about that, the current title is what I mean.

**Comment by Miigon** [comment]
This already exists.
You can find it here:
```
Preference -> General -> Behavior -> Open a choose file panel after starting
```
@alejx You may actually mean a "Welcome Panel" which has a "Open Video" button,a "Recent Video" list and so on.

**Comment by alejx** [comment]
@Miigon Nope. I mean when the app is running
<img width="43" alt="screen shot 2017-01-14 at 8 09 02 pm" src="https://cloud.githubusercontent.com/assets/20237141/21959710/5a4cfc54-da95-11e6-87c2-4a1d58b8442a.png">
and no video is playing, click on the app icon in the dock, it should be a open penal. The setting in preference only controls the behavior when the app first starts.
Sorry again about my bad English..

**Comment by lhc70000** [comment]
Do we really need this? or, does Apple's apps have the same behavior?

**Comment by Miigon** [comment]
@lhc70000
Terminal.app does.

**Comment by HarukaMa** [comment]
I suppose Preview.app also does this?

iPhone$B$+$iAw?.(B

H29/01/15 16:37$B!"(BMiigon <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by tzhao11** [comment]
@lhc70000 Quicktime does this.

**Comment by lhc70000** [comment]
Nice, let's do this.

(Don't know why they never showed any "open file" window on my mac)

**Comment by tzhao11** [comment]
@lhc70000 BTW IINA menu items like <kbd>About IINA</kbd> and <kbd>Preferences...</kbd>  are greyed out when the open file window is present, while in Apple Apps (I tested Pages) they're always available.

**Comment by LeoNatan** [comment]
No, they are not.

Safari:

![screen shot 2017-01-15 at 11 11 37](https://cloud.githubusercontent.com/assets/2270433/21961487/7364b08c-db13-11e6-8757-10a3d9d40ca5.png)

**Comment by Miigon** [comment]
Why not simply merge my pull-request if there is nothing wrong in it?

**Comment by lhc70000** [comment]
@Miigon 
Sorry for that, I'm a little bit busy T T. I'll review and merge remaining PR now. (also for your translation one)

**Comment by Miigon** [comment]
Okay. You really do a good job in this awesome player.

**Comment by alejx** [comment]
@LeoNatan I agree with @tzhao11 . Safari is not document-based application (I think), however IINA certainly is. Other system document-based apps like TextEdit 
<img width="723" alt="screen shot 2017-01-15 at 8 56 24 am" src="https://cloud.githubusercontent.com/assets/20237141/21963467/ff24c660-db00-11e6-8963-c3a9c4fd7d07.png">
and QuickTime Player
<img width="714" alt="screen shot 2017-01-15 at 8 56 54 am" src="https://cloud.githubusercontent.com/assets/20237141/21963468/0a68b31a-db01-11e6-984d-793165c99fe0.png">
and Preview
<img width="714" alt="screen shot 2017-01-15 at 9 01 12 am" src="https://cloud.githubusercontent.com/assets/20237141/21963474/35f229b2-db01-11e6-90b5-e366800c95a8.png">
can do them.

**Comment by lhc70000** [comment]
@alejx IINA is not document based......

**Comment by LeoNatan** [comment]
@lhc70000 Speaking of document based, on macOS Sierra, there is a `Window -> Show Tab Bar` when the player is in full screen. Do you want me to open a new issue for this?

**Comment by saagarjha** [comment]
@lhc70000 I was meaning to speak to you about that. IINA can certainly be a document based application (see [here](https://developer.apple.com/reference/appkit/nsdocumentcontroller)):

> You can use various NSDocumentController methods to get a list of the current documents, get the current document (which is the document whose window is currently key), get documents based on a given filename or window, and find out about a document’s extension, type, display name, and document class.

If we assume a "document" to be a video file, we get all of these for free, as well an Open dialog, Recent Items, etc.)

**Comment by Miigon** [comment]
IINA **can** and **should** be a document-based application

**Comment by alejx** [comment]
@saagarjha Open an issue about that. I strongly agree with you.

**Comment by saagarjha** [comment]
#187.

**Comment by Miigon** [comment]
#176

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
