### ISSUE TITLE
[Feature Request] Ignore "Resume last playback position" if the video has already ended

### ISSUE THREAD

**Issue by ultratiem** [lhc70000/iina#1740]
IINA has a feature to resume a video from the last playback position. This is great for resuming playback on a movie that you had to stop before it concluded.

However, the feature also applies to videos that have finished completely. Which is not desirable given you have to manually start the movie from the beginning.

IINA should ignore this setting while loading a video that has 0 time remaining and should start from the beginning whether the setting is enabled or not.

**Comment by inflation** [comment]
The "resume on playback" feature is handled by mpv totally. It would be better to report to them so we can both improve on this.
