### ISSUE TITLE
Speed controls

### ISSUE THREAD

**Issue by tomwolsky** [lhc70000/iina#1743]
Really need to have some speed controls. 2x forward and ½ backwards is not useable. Really need JKL functionality for play backward at various speeds, pause, and play foreword at various speeds. 

- macOS 10.13.6
- IINA 1b2build80

**Expected behavior:**

Proper speed control is essential for a player.

**Comment by inflation** [comment]
![image](https://user-images.githubusercontent.com/2375962/40811310-ae8a0132-64fe-11e8-95f2-0c5b97a6810f.png)
You can set anything you like here. 

And please search for existing issues before bringing on new ones. Thank you.

**Comment by tomwolsky** [comment]
Apologies. Would it be possible to set L to 1x, LL to 2x, LLL to 4x, and LLLL to 8x? Similarly for J in reverse?

**Comment by inflation** [comment]
Currently there is no way to have key sequence except "modifiers + key". But you can set the key to increase speed or the other way. 
![image](https://user-images.githubusercontent.com/2375962/40816485-43084c4e-651b-11e8-8f47-634e03fc8927.png)

**Comment by tomwolsky** [comment]
Thank you.

**Comment by inflation** [comment]
Seem solved. Reopen if you have any other questions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomwolsky** [comment]
Sorry no. The speed controls for real-time Rick and rolling of video in the player just aren’t there. Need to be able to fast forward, fast back, and switch back and forth between the two or normal forward with the keyboard. Try JKL in the QT player to see how this is used in most video applications.

**Comment by lhc70000** [comment]
See #656. IINA doesn't support reverse playback.
