### ISSUE TITLE
Step through frames

### ISSUE THREAD

**Issue by tomwolsky** [lhc70000/iina#1744]
Really need to have step through function, keys to move forward or backward frame by frame. Traditionally in video applications this has been left and right arrows, up and down are beginning and end. 

- macOS 10.13.6
- IINA 1b2build80

**Comment by inflation** [comment]
The default keybinding for that is `,` and `.`. You can modify that in settings.

**Comment by lhc70000** [comment]
You can check it out in Preferences - Key bindings. By default (in “IINA” scheme), it’s Option+Left/Right. 

Tip: you’ll find more actions in the menus when opening them while pressing option key.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jorijnsmit** [comment]
Would it make sense to include these in the `Playback` menu, together with `Step Forward 5s` and `Step Backward 5s`?

**Comment by lhc70000** [comment]
@jorijnsmit They are visible when you press and hold the option button.  It's macOS's mechanism. They won't be hidden if you assign them shortcuts that don't contain the option key.

**Comment by jorijnsmit** [comment]
But they don't have shortcuts that contain the option key, since they are bound to `,` and `.` by default, right?

**Comment by lhc70000** [comment]
In the "IINA Default" configuration, the primary key bindings are option+left/right, and `,` `.` only exist for mpv compatibility. You can duplicate the default config and delete the first two bindings manually.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/8478049/99683392-43391f00-2abb-11eb-92ce-94fdedb54ab0.png">

**Comment by hugepower** [comment]
```lua
local timer = nil
local interval = 0.5  -- Adjust interval time (seconds), set to advance one frame every 0.5 seconds / 调整间隔时间（秒），此处设置为每 0.5 秒前进一帧
local original_volume = nil

-- Enable or disable frame-stepping forward / 启用或停用逐帧前进
function toggle_frame_step()
    if timer then
        mp.msg.info("Stopping frame-step")  -- 停止逐帧
        timer:kill()
        timer = nil
        mp.set_property("volume", original_volume or "100")  -- Restore volume / 恢复音量
        mp.set_property("pause", "no")  -- Resume normal playback / 恢复正常播放
    else
        mp.msg.info("Starting frame-step")  -- 启动逐帧
        original_volume = mp.get_property("volume")  -- Save current volume / 保存当前音量
        mp.set_property("volume", "0")  -- Mute / 静音
        mp.set_property("pause", "yes")  -- Pause video, enter frame-stepping mode / 暂停视频，进入逐帧模式
        timer = mp.add_periodic_timer(interval, function()
            mp.command("frame-step")  -- Advance one frame / 前进一帧
        end)
    end
end

mp.add_key_binding("k", "toggle-frame-step", toggle_frame_step)  -- Bind key to toggle frame-stepping / 绑定键以启用/停用逐帧前进
```

This script adds an automatic frame-stepping feature to MPV, which can be toggled on and off by pressing the `k` key. When activated, the video will advance one frame every 0.5 seconds until the key is pressed again to stop. The script mutes the audio and pauses the video while frame-stepping is active, and restores them when stopped. To use this script in IINA, follow these steps:

1. **Save the Script**: Save the script as a `.lua` file, such as `auto_frame_step.lua`.
2. **Locate the IINA Scripts Folder**: Open IINA, go to the menu bar, and select `IINA` > `Preferences` > `Advanced` > `Open Config Folder`. This will open the folder where you can place the script.
3. **Move the Script**: In the folder that opens, create a directory named `scripts` if it doesn’t exist, and move your `.lua` script into this folder.
4. **Bind the Key in IINA**: Go to `IINA` > `Preferences` > `Key Bindings`, and add a new binding. Set the key (e.g., `k`) and in the command input, type `script-binding toggle-frame-step` to bind the key to this script.
5. **Restart IINA**: Restart IINA for the script and key binding to take effect. Once done, you can press `k` to toggle automatic frame-stepping while watching a video.
