### ISSUE TITLE
Lengthen the controller

### ISSUE THREAD

**Issue by tomwolsky** [lhc70000/iina#1748]
Like the icons on the scrubber bar in the controller. For a long video, the icons skip through very quickly. It would be very handy if the controller could be stretched out and lengthened, giving more area for display of the icons if needed.  

- macOS 10.13.4
- IINA 1b2build80

**Comment by inflation** [comment]
Can you provide any screenshots so we can better understanding the problem?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomwolsky** [comment]
<img width="487" alt="screensnapz003" src="https://user-images.githubusercontent.com/18217685/40857777-cb239aee-65a1-11e8-98fc-ab9978b753b7.png">

This is the whole length of a feature film. If the controller could be stretched out, the width of the screen for instance, more icons in the scrubber bar would be visible, making it easier to navigate.

**Comment by inflation** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/2375962/40861143-fedfe6da-65b5-11e8-898d-0239e2f75ff6.png">
You can set the layout.

**Comment by tomwolsky** [comment]
Beautiful. Thank you very much. Didn't realize bottom was full screen width.
