### ISSUE TITLE
Wish to provide an option to save online subtitles with video files in the same location 

### ISSUE THREAD

**Issue by liuhui0803** [lhc70000/iina#175]
By this way, sharing the folder contains video files or transfer them into another machine or media player device, will also use the downloaded subtitles directly

**Comment by silic0ns0ul** [comment]
+1
I utilized the download subtitle feature today and have no idea if it saved the subtitle and if so where it saved it.

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

**Comment by mrelwood** [comment]
This feature does not seem to be present in the latest 0.0.15 build 64 on macOS 10.13.2. I would love for it to be though!
