### ISSUE TITLE
shuffle playlist keyboard shortcut

### ISSUE THREAD

**Issue by danleyzberg** [lhc70000/iina#1750]
**System and IINA version:**
- macOS 10.13.4
- IINA 1.0.0-beta2 Build 80

**Expected behavior:**

**Actual behavior:**
Would love a keyboard shortcut to shuffle the playlist. On VLC, it's CTRL+Z.

**Comment by lhc70000** [comment]
You can add a key binding and set its action to `playlist-shuffle`. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danleyzberg** [comment]
Right, thanks!

Hey, do you have a donate link set up somewhere? I'd be happy to send you $10.

**Comment by kklot** [comment]
on Mac Mojave, I duplicated the IINA default shortcut, add `playlist-shuffle` shortcut, but it does not work. I added another key `@iina delete-current-file` and this one works. Tried remove and add again with different key but did not work as well.
