### ISSUE TITLE
Cannot Play Sound of MP3 File and Some MP4 FIle

### ISSUE THREAD

**Issue by godlikeanyone** [lhc70000/iina#1756]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 beta 2 build 80

**Expected behavior:**
It should play the sound of my MP3 file but it cannot play the file. Also it doesn't work for some MP4 movie.

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Every time when I open an MP3 file

**Comment by lhc70000** [comment]
I think it's an upstream (mpv) issue. Please report to them with log.
