### ISSUE TITLE
mkv crashes

### ISSUE THREAD

**Issue by siamak01** [lhc70000/iina#1757]
audio files that converted with ffmpeg 4 from aiff to mka crashes same files will play with mpv

**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta2 build 80

**Expected behavior:**

- Crash report:
```
[IINA_2018-06-02-213146_Macs-MacBook-Pro.log](https://github.com/lhc70000/iina/files/2065656/IINA_2018-06-02-213146_Macs-MacBook-Pro.log)

```

**How often does this happen?**
always

**Comment by inflation** [comment]
It seems an ffmpeg lib crashed. Which mpv version have you tested? Can you provide the sample?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by siamak01** [comment]
mpv 0.28.2
