### ISSUE TITLE
Audio-delay adjustment is much too coarse.

### ISSUE THREAD

**Issue by Stokestack** [lhc70000/iina#1758]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.00 beta 2

**Expected behavior:**
I can adjust audio delay in frames or at least tenths of a second.

**Actual behavior:**
I can only adjust audio in half-second increments, which is much too coarse to be useful.

**Comment by alejx** [comment]
You can type any number you like into the text field next to the slider.

**Comment by Stokestack** [comment]
Thanks, but it shows up as a menu item on my system, not a slider.

**Comment by lhc70000** [comment]
![acec9478-90a2-4a7c-9896-df7871e7823a](https://user-images.githubusercontent.com/8478049/41450070-e0475d74-7097-11e8-9a35-874c1608668e.png)

**Comment by Tronic** [comment]
This really needs to be fixed. Half-a-second adjustments are quite useless, as differences greater than 150 ms are already very disturbing. I would suggest 0.1 second increments, as at that level it becomes hard to percept which way it needs to be adjusted.

**Comment by Stokestack** [comment]
I agree, but someone closed this with no explanation (and an unexplained screen shot).

**Comment by Tronic** [comment]
Better make a pull request. Fork the project on Github, change the value in your fork, click button on Github to send your changes back to this project. Care to do that?

**Comment by HarukaMa** [comment]
Have any of you tried to type the desired value directly into the textbox on the right of the slider?

**Comment by Tronic** [comment]
@HarukaMa That was the third thing I did, after finding out that I cannot adjust it by (1) sliding or (2) clicking. The fourth thing was googling and ending up here.

Being able to type in numbers to a field is not a solution here because *finding* the desired value requires trial and error, and then typing in numbers becomes tedious.

**Comment by HarukaMa** [comment]
That is actually what's needed for a proper feature request tbh...
