### ISSUE TITLE
Playback History shows times instead of dates

### ISSUE THREAD

**Issue by AthirnEleidan** [lhc70000/iina#1759]
**System and IINA version:**

- macOS 10.13.5
- IINA 1.0.0-beta2 Build 80

**Expected behavior:**
The history items should be grouped by date when they've been played, with corresponding dates shown in the grouping headers. 

**Actual behavior:**
Instead of dates the history items are being grouped by time which is shown in the grouping headers.

<img width="671" alt="screenshot 2018-06-03 10 47 11" src="https://user-images.githubusercontent.com/36358174/40884387-7e110810-671b-11e8-8763-c224afbbadc4.png">

**Comment by lhc70000** [comment]
It must be a regression.

**Comment by lhc70000** [comment]
Fixed.
