### ISSUE TITLE
Updating for macOS 10.14 Mojave/Swift 4.2/Xcode 10

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#1765]
I just wanted to create an issue to track progress towards having a first-class experience on macOS Mojave. I think the tentpole feature here is supporting dark mode, so we'll have to revisit how we manage theming and ensure that it matches what Apple wants us to do. Also, I think we should consider adding an option in Preferences to match the current system theme.

**Comment by h0n3yc4k3** [comment]
I can't install add-on "open in inna" in safari. There error "Safari no longer supports the unsafe extension “Open in IINA”." (before update it was installed, but after updating to Mojave this addon was deleted)

**Comment by saagarjha** [comment]
macOS Mojave does not allow the loading of developer-signed .safariextz files other than those originating from the Safari Extensions Gallery. As IINA does not satisfy those requirements, Safari will refuse to load it. We'll have to migrate to an app extension to make this work.

**Comment by alejx** [comment]
Only `darkAqua` is added into NSAppearance.Name, so now we have `aqua`, `darkAqua`, `vibrantLight` and `vibrantDark`. `aqua` was the default for every controls prior Mojave, and we used `vibrantLight` and `vibrantDark` in IINA. 

I have a few suggestion on how we deal with appearance in Mojave.

1. Currently we have some views do not support light theme (PlaylistView, QuickSettingView and the mini player); we should let them support light theme.
2. Though we have dark, ultra dark, light and medium light options for users to choose from, I think they are not necessary and a little bit complicated. My suggestion is to keep dark and light themes only, and always use `aqua + vibrantLight` or `darkAqua + vibrantDark`.
3. It's also an option to remove the appearance setting from our preferences completely and always respect to the global system setting.

**Comment by alejx** [comment]
> I don't think I quite understand the difference between the four themes we have currently, so take that as a vote for simplification there. What are the differences between them?

Codewise, those four are all `NSVisualEffectView.Material`; and `ultraDark` looks a little bit more opaque than `dark`, so does `light` and `mediumLight`. QuickTime seems using different material for its titlebar and OSC. I think we should hand pick which material we want to use for different part instead of make them all options and let users choose.

> I think this might look out of place as compared to QuickTime. Personally, I use both a dark and light system UI based on the time of day, but I will probably keep IINA set to a dark theme for consistency.

Indeed, I'm also aware of this.

**Comment by alejx** [comment]
I think it's also a good chance to drop OS X 10.11 support when we officially support macOS 10.14.

**Comment by saagarjha** [comment]
Hmm, why are we dropping 10.11 support? Is there anything that Sierra offers that dropping El Capitan support would help use with?

**Comment by alejx** [comment]
@saagarjha That was a typo, sorry about that!

**Comment by saagarjha** [comment]
Preliminary support is now on the mojave branch with a68c8bb176ac6eb5d06ccda276e6b6b87c31dfc4. This has three themes: dark, light, and system, which act as I've previously described. Mojave users, please test the themes to see if they work. Those on previous versions, please use this app as normal and let me know if something is broken (I'm sure there is, because I've deleted a lot of the old theming code). And for your enjoyment, here are some screenshots:

<img width="738" alt="screen shot 2018-06-15 at 03 44 49" src="https://user-images.githubusercontent.com/13786931/41464238-7693bb6e-704e-11e8-8c0f-f4acfa5cc63e.png">
<img width="730" alt="screen shot 2018-06-15 at 03 45 51" src="https://user-images.githubusercontent.com/13786931/41464282-9b64e094-704e-11e8-8dd1-0f35c28e01de.png">
<img width="730" alt="screen shot 2018-06-15 at 03 46 10" src="https://user-images.githubusercontent.com/13786931/41464297-a6599c56-704e-11e8-8c79-d07215e07197.png">
<img width="785" alt="screen shot 2018-06-15 at 03 46 22" src="https://user-images.githubusercontent.com/13786931/41464306-adc8068a-704e-11e8-9e9c-dd0e5d191837.png">
<img width="738" alt="screen shot 2018-06-15 at 03 56 57" src="https://user-images.githubusercontent.com/13786931/41464730-29a7d130-7050-11e8-9553-9cd68a1f5c1e.png">
<img width="730" alt="screen shot 2018-06-15 at 03 58 07" src="https://user-images.githubusercontent.com/13786931/41464776-53fc02e4-7050-11e8-8f12-39c658f439a1.png">
<img width="730" alt="screen shot 2018-06-15 at 03 58 30" src="https://user-images.githubusercontent.com/13786931/41464789-5f3c5730-7050-11e8-939f-fe9d0faeb344.png">
<img width="785" alt="screen shot 2018-06-15 at 03 58 52" src="https://user-images.githubusercontent.com/13786931/41464798-6e51b814-7050-11e8-8916-8dc02792f13f.png">

**Comment by lhc70000** [comment]
I think we should use the "Dark" theme by default. Does QuickTime also have a light theme in Mojave?

**Comment by saagarjha** [comment]
> I think we should use the "Dark" theme by default.

That's the current plan, yes.

> Does QuickTime also have a light theme in Mojave?

Not that I'm aware of.

**Comment by saagarjha** [comment]
@lhc70000 By the way, I think we should also consider applying the theme to the "About" window. Maybe it's time to give it a second look, layout-wise?

**Comment by lhc70000** [comment]
Actually I'm planning to revise the UI in the next beta (especially the preferences panel) and we can put them together. What are your suggestions on the layout of the about window?

> I just checked, and it's still using the deprecated NSAppearance.Name.vibrantDark 🙄

Just a little bit curious: How did you check this?

**Comment by saagarjha** [comment]
> What are your suggestions on the layout of the about window?

I always thought it was a bit tall. Here's a very rough idea for making it a bit shorter, but feel free to abandon it completely:

<img width="461" alt="screen shot 2018-06-15 at 05 18 32" src="https://user-images.githubusercontent.com/13786931/41467977-3e4e64de-705d-11e8-913a-e869cf95f217.png">

Also, there's a lot of space around that "Credits" button.

> How did you check this?

I disassembled `-[MGDocument makeWindowControllers]` in Hopper.
