### ISSUE TITLE
How to add/subtract video playback speed instead of multiply?

### ISSUE THREAD

**Issue by aeon3** [lhc70000/iina#1766]
Hello!

I just downloaded IINA and I found it 100% the best macos media playback so far! I'm very excited. However, here is my issue:

**System and IINA version:**

- macOS 10.13.5
- IINA 0.0.15.1

**Expected behavior:**

Option to set a shortcut for adding or subtracting video playback speed in increments of 0.1.

**Actual behavior:**

Only option to set or multiple video speed playback.

Hope you guys can help me out finding how to accomplish that.

Best!

**Comment by lhc70000** [comment]
![6c04871f-70e0-4491-ae79-4b283dff4b65](https://user-images.githubusercontent.com/8478049/40956067-c48f5bc4-68c0-11e8-81a5-b777f504bbb3.png)

**Comment by aeon3** [comment]
Thank you! This is the best app ever :)
