### ISSUE TITLE
Video playback in IINA affects Photoshop's performance.

### ISSUE THREAD

**Issue by aeon3** [lhc70000/iina#1769]
I'm looking for a way to make IINA less intensive on my macbook's GPU/CPU. I noticed it makes Photoshop lag.

**System and IINA version:**

- macOS 10.13.5
- IINA 0.0.15.1

**Expected behavior:**

IINA shouldn't affect my computer's performance as much as it's doing right now.

**Actual behavior:**

I launch both Photoshop and IINA. While there's a video playing, it noticeably affects Photoshop's performance, especially brushstrokes. Lag is obvious. As soon as I pause the video, even without leaving Photoshop's window, it goes back to normal, no lag. Play the video, lag is back.

**How often does this happen?**

Every time.

Any suggestions on what I could try to make IINA as light as possible on my system's resources?

**Comment by inflation** [comment]
If you are using hardware acceleration in both programs, there might be a chance that they would affect each other. Try to disable one and see the result.

**Comment by aeon3** [comment]
Great advice @inflation .

I was able to fix it by reducing the number of threads IINA uses to the minimum of 1 (while keeping the hardware decoder to auto) and by changing Photoshop's GPU usage from "Advanced" to "Basic".

Cheers :)

**Comment by inflation** [comment]
Good to know it solved. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
