### ISSUE TITLE
Error when press § key when play video

### ISSUE THREAD

**Issue by rohmanhm** [lhc70000/iina#177]
Got this error when press `esc` key when play video.

![image](https://cloud.githubusercontent.com/assets/7524911/21960064/b21edafa-db0e-11e6-8ec1-6f07e72fa2a3.png)

**Comment by lhc70000** [comment]
Sorry that I cannot reproduce this problem. May I ask which keyboard layout are you using?

**Comment by lhc70000** [comment]
Does it still happen in [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3)?

**Comment by rohmanhm** [comment]
Sorry, I think I make a mistakes. The error is not when press the `esc` key. But when I pressed the `§` key on my old mac.

**Comment by rohmanhm** [comment]
This is the key
![image](https://cloud.githubusercontent.com/assets/7524911/22176105/42e43a6e-e035-11e6-9d08-52e867d5fef4.png)

**Comment by lhc70000** [comment]
Thanks, got it.

**Comment by alejx** [comment]
Duplicate with #191 .

**Comment by saagarjha** [comment]
@alejx That issue came after this one…

**Comment by alejx** [comment]
@saagarjha I know, but I kept the more general one.
