### ISSUE TITLE
Videos won't start from the beginning anymore

### ISSUE THREAD

**Issue by mo4ya2000** [lhc70000/iina#1772]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 beta 2 build 80

**Expected behavior:**
Unchecking "resume last playback position" should restart the video from the beginning.

**Actual behavior"
Video starts wherever I left off viewing or closed the video out of.

**Comment by chrikop** [comment]
Happens with audio files as well. "resume last playback position" is unchecked

**Comment by lhc70000** [comment]
See #1730.

It's a bug and has been fixed in develop branch.
