### ISSUE TITLE
Support SOCKS proxy

### ISSUE THREAD

**Issue by elvinchan** [lhc70000/iina#1786]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
Youtube-dl already supported SOCKS proxy since 218187016 (https://github.com/rg3/youtube-dl/issues/402#issuecomment-218187016) , but IINA not support yet.

I tried to set proxy in youtube-dl custom option, but failed. IINA document declares that proxy setting in custom option will only work when getting the real video address.

SOCKS proxy is really needed especially in China (You might heard about SS :wink:). So please support this, thanks.

**Comment by VSG24** [comment]
I would also like to have this feature in IINA.

**Comment by lhc70000** [comment]
Youtube-dl only gets the real link to the video and iina still needs to use FFmpeg to play it.

With ShadowsocksX-NG you can easily have a exported local HTTP proxy, so I think it's not a critical problem.
