### ISSUE TITLE
A Swift Compiler Error occurs when compiling iina (occurs in framework GRMustache)

### ISSUE THREAD

**Issue by yujingbin** [lhc70000/iina#1788]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15.1
(built from commit 4a98bca4341e753c9705d88f43700212410d26d4)

- Error Message:
```
iina/Pods/GRMustache.swift/Sources/Foundation.swift:295:24: Value of type 'IteratorSequence<NSFastEnumerationIterator>' has no member 'compactMap'
```

**Steps to reproduce:**
clone the repo, run ```pod install```, then compile it in iina.xcworkspace

**Comment by saagarjha** [comment]
Are you using the latest version of Xcode?

**Comment by yujingbin** [comment]
@saagarjha yes

**Comment by saagarjha** [comment]
Well, `IteratorSequence` should have `compactMap` on it [going all the way back to Xcode 9.3](https://developer.apple.com/documentation/swift/iteratorsequence/2950829-compactmap), so could you attach the full output from the build so we can see what's going wrong?

**Comment by yujingbin** [comment]
Here is the screenshot

![image](https://user-images.githubusercontent.com/5325955/41327742-2e7a21d6-6ef7-11e8-961e-1cbb47a5447a.png)

**Comment by alejx** [comment]
Could you double check you Xcode version? This is really weird.

**Comment by yujingbin** [comment]
@alejx @saagarjha  I'm sooooo sorry... My Xcode version is 9.1 not 9.3...
Sorry to disturb
So sorry about that....
