### ISSUE TITLE
How to open a video file in fullscreen mode in terminal

### ISSUE THREAD

**Issue by mpco** [lhc70000/iina#1789]
**System and IINA version:**

- macOS 10.13.5
- IINA 0.0.15.1 build 69

I run the command in terminal : `iina --mpv-fs --mpv-resume-playback=no xxx.mp4`

But it didn't work in fullscreen mode.
What arguments should I use?

**Comment by inflation** [comment]
I don’t believe `fs` mpv options has any effect.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lhc70000** [comment]
This is possible in 1.0.0 beta 4.
