### ISSUE TITLE
When restarted it doesn't open in last state

### ISSUE THREAD

**Issue by theonlygusti** [lhc70000/iina#1790]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

When re-opening, e.g. after a restart, it will be the same as when it was closed.

Should be playing the same video, and have the same videos "up next" (I will often open multiple files at a time with this).

**Actual behavior:**

Shows a list of files I _have_ played, but doesn't retain memory of what it should be playing next.

**Steps to reproduce:**

1. Select multiple video files in finder.
2. Open with IINA
3. Quit while watching the second file
4. Restart IINA
5. Only the first two files are shown, the rest have disappeared.

- [x] MPV does not have this problem.

**How often does this happen?**
100% of the time

**Comment by inflation** [comment]
You can save it as a playlist. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theonlygusti** [comment]
@inflation so you think it's logical to open in a different state to the one it closed in?

I think that doesn't flow with the rest of macOS.

**Comment by alejx** [comment]
I guess you are complaining about the welcome window. What you see in the welcome window is your playback history. IINA only record what you have played. Currently we do not support "restore previous state" function.

**Comment by theonlygusti** [comment]
> Yes, take a look of QuickTime Player. Video players are not very similar to other kinds of programs.
> 
> Sent with [GitHawk](http://githawk.com)

QuickTime Player.app actually opens in the same state as it was closed in. If there were any windows open when it was quitted, it reopens those (even at the same timestamp).

If there were no windows open when it was last quitted, then it starts up with a file browser "Open" dialog.
