### ISSUE TITLE
可否让用户自己来切换高性能GPU

### ISSUE THREAD

**Issue by feijie999** [lhc70000/iina#1791]
这是我在mac上体验过最好的播放器，cpu占用非常低，画面显示比我使用过的所有播放器都鲜艳，非常棒。
我比较喜欢播放4K蓝光（*.ts、*.MKV）这类型的视频，这些视频大多数的大小在50GB左右，使用IINA播放这些视频大多数都是非常流畅的，CPU维持在60%左右，但是有些视频会暂用更高的CPU或出现丢帧的情况，这让我不得不切换Blu-ray播放器来播放这些视频。
Blu-ray播放器会自动切换到高性能GPU，所以画面非常流畅而且减少了Macbook的发热，如果IINA能让用户自己来主动切换或者根据画面掉帧或CPU使用率来自动切换那就太好了。

**Comment by inflation** [comment]
你可以使用gfxCardStatus进行手动切换，或者通过mpv选项降低渲染质量。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
