### ISSUE TITLE
SUP subtitle cannot play with correct timeline

### ISSUE THREAD

**Issue by huangjun604** [lhc70000/iina#1793]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

The `SUP` subtitle should be loaded correctly.

**Actual behavior:**

The `SUP` subtitle will load earlier, it will get rid of the blank at the beginning and play the first line at 0:0:0. Therefore, the subtitle does not synchronize with the video.

This issue happened when updated from 0.0.15 to 0.0.15.1. The version before 0.0.15 works correctly.

**How often does this happen?**

Everytime

**Comment by alejx** [comment]
Please try this in mpv and then report here or directly to mpv.

**Comment by huangjun604** [comment]
Thanks for replying @alejx . I just tested on `mpv`. Yes, it doesn't work on `mpv` as well since 0.28.0. Version 0.27.0 works as expected.
