### ISSUE TITLE
Where to lookup for IINA downloaded subtitles

### ISSUE THREAD

**Issue by wcwxyz** [lhc70000/iina#1798]
IINA does a wonderful job playing movies. I find it's awesome to online download a matching subtitle for specific a movie. I'd like to find where these subtitles go, and copy them to the same directory along with the movie. How can I do that?

Thanks for your great work.

**System and IINA version:**

- macOS 10.13.5
- IINA 1.0.0-beta2

**Expected behavior:**

All downloaded subtitles are in the same directory as the video

**Actual behavior:**

Not sure where to lookup for these downloaded subtitles.

**Comment by alayliercan** [comment]
@wcwxyz 
Pick a matching subtitle by using `Find Online Subtitles...`, and then click on `Subtitles > Save Downloaded Subtitle` menu item to save that subtitle into same directory as the movie.

**Comment by wcwxyz** [comment]
@alayliercan Thanks. I see that now.
