### ISSUE TITLE
Force using discrete GPU when playing | 强制使用独显

### ISSUE THREAD

**Issue by xuhaoyang** [lhc70000/iina#18]
打开程序未播放可以使用集显，开始播放视频时就会强制切换到独显。    
![img](http://ww4.sinaimg.cn/large/6af1db27gw1fbfp00lwg0j20by0fu40g.jpg)

目前试出来的就是空格键和command+，会出现新打开程序后 快捷功能失效，窗口是在active的，失效可以用其他不失效的按键恢复？比如空格暂停，按一次p键就恢复了     
![img](http://ww3.sinaimg.cn/large/6af1db27gw1fbfp5hkv1aj21i00rqaia.jpg)

**Comment by lhc70000** [comment]
两个不同问题请最好不要放在同一个 issue 里（这次就先这样）。

两个问题都有待研究，感谢提供详细信息。
