### ISSUE TITLE
Cannot use Cmd+C/Cmd+V in preference window

### ISSUE THREAD

**Issue by tzhao11** [lhc70000/iina#180]
<kbd>command</kbd>+<kbd>C</kbd> and <kbd>command</kbd>+<kbd>V</kbd> don't work in the preference window. For now to copy/paste you need to use the context menu.

**Comment by HarukaMa** [comment]
The global shortcut keys for copy and pasting is missing.

They also don't work in open URL and open window - cmd+shift+g.

**Comment by lhc70000** [comment]
By default text fields does not support shortcuts. We need to implement them manually (listen and interpret key events).

**Comment by alejx** [comment]
Cannot use command+option+shift+3/4 to capture. Maybe we should find a better way to change the current key event handling.

**Comment by lhc70000** [comment]
@alejx It's a different problem.
