### ISSUE TITLE
How to clean the whole play history?

### ISSUE THREAD

**Issue by ITGrocery** [lhc70000/iina#1802]
In this application, I only find the clean menu button ,how cal I clean the whole play history?
![qq20180623-105128](https://user-images.githubusercontent.com/10252344/41805067-7f5d7550-76d4-11e8-8404-0309cdc4b705.png)

**Comment by ErikMinekus** [comment]
See https://github.com/lhc70000/iina/issues/924#issuecomment-318798169.
