### ISSUE TITLE
播放速度(Speed) 为什么只能0.5, 1.0或者2.0呢? 

### ISSUE THREAD

**Issue by hepengju** [lhc70000/iina#1804]
在观看视频教程的时候,直接以1.0的速度观看,感觉太慢了. 2.0的速度有些快.
一般都是1.5,1.6的速度观看. 查找许久, 没有看到以0.1为单位增加播放速度的选项.
技术上应该没有问题, 还希望可以加入此功能.

**Comment by Chandler-Lu** [comment]
![wx20180625-115730](https://user-images.githubusercontent.com/18322610/41829719-f6196942-786e-11e8-8c46-05a8694a9ff8.png)
没有问题呐

**Comment by hepengju** [comment]
@Chandler-Lu 原来在这里调节, 非常感谢.
