### ISSUE TITLE
srt display position wrong

### ISSUE THREAD

**Issue by msongz** [lhc70000/iina#1809]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

![image](https://user-images.githubusercontent.com/2059694/42012603-afb86dae-7acb-11e8-82e2-4c83d28ad720.png)

**srt content:**

1
00:00:00,000 --> 00:00:00,441
sdad

2
00:00:00,850 --> 00:00:04,658
sdad

3
00:00:01,200 --> 00:00:05,083
sdad

4
00:00:02,016 --> 00:00:02,458
s<i>dad</i>daddadwdwdsdawwdewea

5
00:00:03,066 --> 00:00:03,508
sdad

6
00:00:04,425 --> 00:00:05,150
hddh“

**Comment by alejx** [comment]
Cannot reproduce. Please check your subtitles settings of IINA.

**Comment by msongz** [comment]
@alejx sorry, which setting affects the subtitle position?

**Comment by alejx** [comment]
I've never played with these settings but I guess
![image](https://user-images.githubusercontent.com/20237141/42221930-5a8bd58e-7f06-11e8-830b-1a994a2125c3.png)
these settings will control the position.

**Comment by msongz** [comment]
@alejx thanks! that works! I change the align:X to center and the subtitle position back to center. maybe I change the setting by accident

**Comment by alejx** [comment]
Good to see that!
