### ISSUE TITLE
功能：能否增加QuickTime全套快捷键

### ISSUE THREAD

**Issue by bashang03** [lhc70000/iina#1810]
- macOS 10.13.4
- IINA 0.0.15.1

能否在下次更新的时候增加QuickTime全套快捷键，尤其是J往回播放（双击两倍向后速度、三击四倍……）、K停止&速度恢复正常、L往前播放（双击两倍向前速度、三击四倍……）、JK慢速王会播放、KL慢速往前播放

想要做视频截图收集镜头的时候特别方便

多谢大佬

**Comment by lhc70000** [comment]
技术原因无法倒放。

See #470
