### ISSUE TITLE
adjusting contrast doesn't work correctly

### ISSUE THREAD

**Issue by jerkstore369** [lhc70000/iina#1817]
I don't think adjusting contrast in the equalizer settings works correctly. The more I adjust it the deeper blacks should get and the brighter light colors should get. For me, it's more like a toned down gamma setting. Please fix this. Even with contrast set high, it still looks too washed out. I need the blacks deeper. I calibrated my screen once sometime after I got the machine that's about it. Shouldn't make a difference, it's a stock macbook pro 2015. Thanks.

- macOS 10.12.6
- IINA beta1 build 72

**Comment by alejx** [comment]
I tested different contrast in IINA and mpv side by side, IINA shows exactly the same image as mpv's. You can try one in mpv, using key 1 and 2 to adjust contrast.

**Comment by alejx** [comment]
You may want to report to mpv then.
