### ISSUE TITLE
File icons | 建议增加文件类型图标

### ISSUE THREAD

**Issue by HelloHeym** [lhc70000/iina#182]
不然的话，好多文件如果设置了iina默认打开，图标显示是空白的

**Comment by lhc70000** [comment]
Duplicate with #36.

**Comment by Miigon** [comment]
提issue请尽量使用英文，这是对社区的一种尊重，谢谢
当然我就假设你英语不是很好，用中文回复了
我记得macOS设置默认打开方式后会用一个文件内画着app的图标的形式显示图标

当然，现在IINA还很不成熟稳定，可能存在崩溃或耗电等问题，不建议设置成默认播放器及日常作为主播放器使用

**Comment by lhc70000** [comment]
Close due to duplication.
