### ISSUE TITLE
App keeps crashing while playing .m4v videos after the last update

### ISSUE THREAD

**Issue by mattiaz9** [lhc70000/iina#1829]
The app crashes precisely at 1:54 min of every video I play. They are all m4v type videos.
Other formats like .avi doesn't seem to have the same problem.

This is the message I receive:
Process:               IINA [6806]
Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.0.0-beta2 (80)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [6806]
User ID:               501

Date/Time:             2018-07-12 20:03:54.291 +0200
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12

Time Awake Since Boot: 41000 seconds

System Integrity Protection: enabled

Crashed Thread:        6  Dispatch queue: com.colliderli.iina.mpvgl

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

**Comment by mattiaz9** [comment]
It's something to do with subtitles because that's the time when they start. If I disable them the app won't crash

**Comment by inflation** [comment]
Can you provide the full crash report?

**Comment by mattiaz9** [comment]
[crash report.txt](https://github.com/lhc70000/iina/files/2189876/crash.report.txt)

**Comment by inflation** [comment]
This is the same issue with #1660 and #1734.
