### ISSUE TITLE
some force touch optimize suggestions

### ISSUE THREAD

**Issue by xjkdev** [lhc70000/iina#184]
when force touch fast forward or back forward and then, when i lift my finger, the speed won't change to normal speed, which is different from the behavior of quicktime.
i think it's quite disturbing. please add a setting about it if it is not bothering you, thank you.

**Comment by lhc70000** [comment]
@saagarjha Could you take a look at this?

**Comment by saagarjha** [comment]
@xjkdev That's odd, I can't seem to replicate this on my machine. Is this a consistent issue or did this just happen once?

**Comment by xjkdev** [comment]
It happens every time. i am using v0.0.2 build 3.

**Comment by saagarjha** [comment]
Ahh, I see what you mean now. It appears that QuickTime treats a "hold and release" as similar to Force Touch, and thus resets it after. I'll see what I can do.

**Comment by saagarjha** [comment]
@xjkdev Should be a part of #165.
