### ISSUE TITLE
Playlist 可否显示视频时长

### ISSUE THREAD

**Issue by lxyer** [lhc70000/iina#1841]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
如果你愿意尝试测试版，请在偏好设置里选上「接收 beta 版本更新」。此功能在 1.0.0 beta2 中已经加入。
