### ISSUE TITLE
1.0.0 beta 2 cannot open .rar files

### ISSUE THREAD

**Issue by Jimmni** [lhc70000/iina#1843]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0 beta 2

**Expected behavior:**

In previous versions, opening a RAR file would play the media contained within, where possible.

**Actual behavior:**

When opening a RAR file, IINA beta 2 opens and immediately closes without playing the file. The same files can be played with 0.0.15 build 68 without issue.

**Comment by lhc70000** [comment]
May be related to https://github.com/mpv-player/mpv/issues/5759.
