### ISSUE TITLE
IINA does not switch to music mode when playing music from a URL

### ISSUE THREAD

**Issue by ErikMinekus** [lhc70000/iina#1852]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta2

**Expected behavior:**
It would be nice if IINA switched to music mode when playing music or podcasts from a URL.

**Actual behavior:**
IINA doesn't switch to music mode, because the ```checkCurrentMediaIsAudio``` function explicitly returns ```.notAudio``` for URLs. I didn't see an explanation in the commit messages for why this is the case, and when I comment the guard it seems to work as expected.

**Steps to reproduce:**
1. Open a URL, for example http://9to5mac.com/wp-content/uploads/sites/6/2018/07/9to5Mac-Daily-07-20-2018.mp3.

**How often does this happen?**
Always

**Comment by alejx** [comment]
You are welcomed to make a pull request on this issue!
