### ISSUE TITLE
Few command line suggestions

### ISSUE THREAD

**Issue by MuntashirAkon** [lhc70000/iina#1856]
Personally, I like to work on s/w automation. As part of a private project, I've used VLC before, but I moved to IINA ever since its command line version is introduced. It has done a great job by supporting all the mpv commands. But it has some limitations and needs some new features.

**Limitations/Suggestions**
- `iina-cli` is used as a launcher of IINA, ie. `iina-cli` closes immediately after IINA is opened (as an immediate as well as separate process). This isn't a good idea. The `iina-cli` should run _as long as_ IINA is running. (It would be even better if `IINA` binary could directly be run with options like VLC does, but it might be too much overhead). My current workaround to this problem is: at first I get the process id of `iina-cli` and then add 1 to it to get the process id of `IINA`.
- Since it's not possible to tell from outside the IINA if a media is done playing, it's not possible to exit IINA on right time. It would be better if there were an option (like `--keep-open`) to exit IINA immediately after a media is done playing. (My current workaround is to use `ffmpeg` to get the duration and then sleep for that duration).
- There should be an option to open media directly to PiP mode.

Thanks for this awesome player.

**Comment by lhc70000** [comment]
Implemented in #1935.

**Comment by MuntashirAkon** [comment]
I'd like to keep this issue open until I test it on my own.

**Comment by MuntashirAkon** [comment]
Feature#2 has not been implemented (as of 1.0.0-beta4 build 92). In #1935, @lhc70000  added `--keep-running` and `--pip` which are the feature#1 and the feature#3 respectively. I'm making it more elaborate:
> There should be a command line option to keep the player running as long as the media is running. IINA will exit automatically when the media is _done playing_ and/or when the user closes the window.

**NOTES:**
1. *Done playing* means if the media has a specific duration, the media is played to the last seconds.
2. If the user closes the window where the specified media is playing, IINA will exit immediately.
