### ISSUE TITLE
Consider adding flexible speed controls

### ISSUE THREAD

**Issue by sproutsibm** [lhc70000/iina#1858]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1 build 69

**Expected behavior:**
I'd like to request additional options for speeding up (or slowing down) a video replay.  If a variable slider is not possible, then by adding additional specific speeds such as 1.25, 1.5, 1.75.  I find this handy for when I need to keep "half an ear" on a presentation for a specific topic/comment/etc.  1.1 doesn't help too much, and 2x is too fast.

**Actual behavior:**
Speed -> 1.1
![image](https://user-images.githubusercontent.com/19862589/43085342-c8242ada-8e68-11e8-9a1b-2b04d82babb3.png)

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
- If you press the same shortcut again, it will go up to 4x, 8x, etc. You can customize everything in Preferences - Key Bindings.
- A slider and even an input box for arbitrary speed value is available in the video sidebar.
