### ISSUE TITLE
Abnormal behavior in the audio/subtitle track selector user interface

### ISSUE THREAD

**Issue by bzq2810** [lhc70000/iina#1860]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta3 Build 85

**Actual behavior:**
The attached video shows the abnormal behavior in the audio/subtitle track selector user interface.
[bug.mov.zip](https://github.com/lhc70000/iina/files/2224210/bug.mov.zip)

- Crash report:
```
N/A
```

- MPV log:
```
N/A
```

**Steps to reproduce:**
See the attached video.

- [x] MPV does not have this problem.
Note: MPV only can select the next/previous track, not the exact one.

**How often does this happen?**
Very high.

**Comment by alejx** [comment]
> Note: MPV only can select the next/previous track, not the exact one.

This is not true. `mpv` (or `libmpv`) gives us the ability to select any arbitrary loaded track.

**Comment by bzq2810** [comment]
This bug has been fixed in the latest version. So, I close this issue.
