### ISSUE TITLE
Bindings for media keys don't work

### ISSUE THREAD

**Issue by bjornorri** [lhc70000/iina#1864]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta3 Build 86

**Expected behavior:**

I would like to change the behaviour of the media keys (and ultimately headphone controls). I go to Preferences -> Key Bindings and duplicate the default IINA profile. I change the action for e.g. PLAY and restart IINA.

IINA should now perform the new action when I hit the PLAY media key (located at F8).

**Actual behavior:**

IINA does not perform the new action and the default action seems to be preserved.

**Comment by lhc70000** [comment]
@bjornorri Please try disabling “use system media control”. By default IINA uses system’s media player framework instead of mpv’s media key handling mechanism.

**Comment by bjornorri** [comment]
I see, thanks for the clarification. Now it seems like the media keys are not intercepted by IINA and the system e.g. just opens iTunes when I press the play media key. But I guess that's another issue, thanks!
