### ISSUE TITLE
"Resume last playback position" is not working when quitting player by hotkey such as "Esc"

### ISSUE THREAD

**Issue by sh2sg** [lhc70000/iina#1866]
- macOS 10.13.6
- IINA 1.0.0 beta 3

"Resume last playback position" is not working when quitting player by hotkey such as "Esc"

1. duplicate "Movist" key binding
2. add "Esc" key binding and assign Action "Quit"
3. double click any video file to launch IINA and start playing
4. press Esc to quit
5. double click the same video file, it starts playing from beginning 

Expected result:
 5. it starts playing from where it quits.

The same issue has been reported in beta 2 (https://github.com/lhc70000/iina/issues/1752), unfortunately it is not fixed in beta 3.

**Comment by ErikMinekus** [comment]
This seems more due to the fact that mpv has a separate ```quit-watch-later``` action, which saves the playback progress before quitting. I believe IINA just passes these actions directly to mpv, so the ```quit``` action will always quit without saving progress, regardless of IINA's preferences.

**Comment by lhc70000** [comment]
I just pushed a commit that adds back binding for `save-position-on-quit`, which seems to be a more neat solution.

**Comment by sh2sg** [comment]
thank you for the quick response, looking forward to the new beta.
