### ISSUE TITLE
Migrate to NSDocumentController

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#187]
As I outlined in #174:

> IINA can certainly be a document based application (see [here](https://developer.apple.com/reference/appkit/nsdocumentcontroller)):
>> You can use various NSDocumentController methods to get a list of the current documents, get the current document (which is the document whose window is currently key), get documents based on a given filename or window, and find out about a document’s extension, type, display name, and document class.

> If we assume a "document" to be a video file, we get all of these for free, as well an Open dialog, Recent Items, etc.)

we should make a move to `NSDocumentController` to manage videos. Each controller should manage its own `NSDocument`, `NSWindow`, and `VideoView`/`PlayerCore` (to fix #79).

**Comment by lhc70000** [comment]
Just one concern: now PlayerCore is singleton, so definitely there will be some changes at design level.
