### ISSUE TITLE
Progress bar inconsistency when playing live streams

### ISSUE THREAD

**Issue by roviavas** [lhc70000/iina#1871]
One of the best features I love about mpv is that it caches live streams and make them seekable.
It also downloads and caches new chunks continuously even when the playback is paused.
When first played a live stream with IINA I thought that this features was dropped because the progress bar always shows either 00:00 or 00:01.
But after a few tries I found that the features still works. It is just the IINA's GUI not showing the actual progress.
https://i.snag.gy/JzgqVC.jpg
Don't know if you intended to make it work like regular players (live streams not cached and not seekable) or not, but I hope that you just fix the display of the progress bar and keep it the way mpv works.

**System and IINA version:**
- macOS 10.11.6
- IINA 1.0.0 Beta3

**Expected behavior:**
The progress bar should be consistent with the actual playback progress when playing live streams.

**Actual behavior:**
The progress bar always shows the length as either 00:00 or 00:01.
As a result, the current position is also incorrect.

**Steps to reproduce:**
1. Open any live stream (Twitch, YouTube, etc.)
2. Show mpv's OSD for progress (press shift-O)
3. Pause or seek backward to see how OSD changes

p.s. mpv's OSC progress bar is consistent with OSD when playing live streams.

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
1.0.0 beta 4 should already fixed it.
