### ISSUE TITLE
all exterior subtitles displaying issues

### ISSUE THREAD

**Issue by zsmjoe** [lhc70000/iina#1873]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0 beta-3

**Expected behavior:**
wish to add an external  subtitle

**Actual behavior:**
the subtitle is not shown.

- MPV log:
```
[mpv.log](https://github.com/lhc70000/iina/files/2237372/mpv.log)

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
for every exterior subtitle
I have checked all the similar issues and none of the approaches works for me

**Comment by lhc70000** [comment]
There seems to be nothing wrong in your log.

Please share the subtitle file with us if you still have this problem.
