### ISSUE TITLE
[Feature Request] Support acestreams

### ISSUE THREAD

**Issue by mahye82** [lhc70000/iina#1875]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1

**Actual behavior:**

An acestream is a stream broadcast via p2p networking. It's particularly popular for people who want to watch sports online. The only Mac app that could run acestreams straight out of the box (i.e. without any other configuration) was discovered to have a major security flaw - as a result, sports streamers on Mac have dumped that app en masse. 

It would be great if IINA could fill this gap in the market and provide support for acestreams instead. I'm sure it would cause many thousands of new users to flock to this app.

**Comment by inflation** [comment]
You can check [this](https://github.com/jonian/acestream-launcher) out and use `iina-cli` as the media player. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
