### ISSUE TITLE
快捷键调整视频播放速度，可以粒度更细些吗，感谢。

### ISSUE THREAD

**Issue by fanchaoo** [lhc70000/iina#1877]
现在调速的跨度有点大，从1倍速按 “command+]” 直接跳到了2倍速。在视频播放过程中经常会不断调速，用鼠标点击右边设置按钮感觉不是很方便，

**Comment by gitabtion** [comment]
option + command + ]

**Comment by lhc70000** [comment]
- 快捷键 option+cmd+[ 或 ] 可调节 1.1 倍，菜单里按住 option 可以看到。
- 「视频」侧边栏中不仅可以拖动滑条调整速度，还可以输入任意速度。
- 所有快捷键都可以在偏好设置里自己编辑。

**Comment by mbybtjh** [comment]
可以自己写命令add speed 0.1，就会逐级增加0.1倍，减速是哪个单词我还没试出来，不过不常用！

**Comment by mbybtjh** [comment]
我好笨啊，刚想到了 add speed -0.1就是递减嘛，哈哈哈
