### ISSUE TITLE
keyboard media controls don't work

### ISSUE THREAD

**Issue by BriceChaponneau** [lhc70000/iina#1880]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1 Beta 69

**Expected behavior:**
When i use keyboard media controls, nothing append.
Play, next, previous... Do you know why ?

**Comment by lhc70000** [comment]
Please [search "media key"](https://github.com/lhc70000/iina/issues?utf8=✓&q=media+key) first and see if previous discussions are helpful.
