### ISSUE TITLE
Suggestion: Auto show playlist

### ISSUE THREAD

**Issue by BriceChaponneau** [lhc70000/iina#1881]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1

**Expected behavior:**
It would be nice to have the list of songs automatically displayed when loading a music or playlist with audio extensions.

**Comment by lhc70000** [comment]
Do you mean showing the playlist by default in music mode?

**Comment by BriceChaponneau** [comment]
Absolutely

**Comment by lhc70000** [comment]
In the next release, IINA will remember settings like whether showing the playlist in music mode (#1930). This should be a solution to your problem.
