### ISSUE TITLE
Key binding to take a screenshot

### ISSUE THREAD

**Issue by sla** [lhc70000/iina#1882]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta3

**Feature request:**
Would like to be able to assign key combination for taking a screenshot. Latest build does not have this feature or it is not obvious (at least to me). Key bindings have changed, I used to take screenshots using the command+Shift+S, now it opens the subtitle panel.

**Comment by alejx** [comment]
Command+shift+s now is used to open subtitle panel, we are going to revise screenshot shortcut to cmd+s. Please wait our next release.

**Comment by sla** [comment]
Thank you!
