### ISSUE TITLE
[Feature Request] forward by frame

### ISSUE THREAD

**Issue by randomatom** [lhc70000/iina#1889]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
It's ⌥→ in the default key binding scheme. You can find more alternative menu items when pressing the Option key.

**Comment by randomatom** [comment]
thx!
