### ISSUE TITLE
Audio device selection support

### ISSUE THREAD

**Issue by tigertoes** [lhc70000/iina#189]
I have a TV plugged in via HDMI, and independently of the output setting in the operating system's sound settings I want to be able to set which device is outputting audio. Currently this is supported in other players (VLC under Audio → Audio Device, MPlayer OS X under Preferences → Audio → Output Device).

I understand this might be a little difficult as currently you would have to fetch all the devices before updating the `audio-device` property (see also: mpv-player/mpv#2398).

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

**Comment by tigertoes** [comment]
Thanks!
