### ISSUE TITLE
How to make it ALWAYS ON TOP by CLI

### ISSUE THREAD

**Issue by MrGlaucus** [lhc70000/iina#1891]
How to make the window always on top while playing, i tried --ontop option but it seemed more like "show front at start". i also tried --ontop-level=window, still didn't work.
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
always on top

**Actual behavior:**
on top at start

**Comment by lhc70000** [comment]
`ontop` and `fullscreen` are added in #1935.

**Comment by MrGlaucus** [comment]
Thank you so much
