### ISSUE TITLE
IP Camera Streaming

### ISSUE THREAD

**Issue by weatherguyto** [lhc70000/iina#1894]
Is it possible to stream video from a IP Axis Camera(M5014). I have tried it without any luck.

http://IP:Port/axis-cgi/mjpg/video.cgi?

http://User:Password@192.168.1.60:port/

Etc.

Thank you,
-William

**Comment by inflation** [comment]
Do you know which protocol and what format your stream use?

**Comment by weatherguyto** [comment]
Thanks for the reply,

I'm using TCP for the protocol and MPEG video format that is streaming.

Thank you,
-William
