### ISSUE TITLE
Crash when attempting to play a specific MKV file

### ISSUE THREAD

**Issue by TempSpas** [lhc70000/iina#1898]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1

**Expected behavior:**

File plays normally.

**Actual behavior:**

File crashes IINA.

- Crash report:

[IINA_2018-08-06-121602.txt](https://github.com/lhc70000/iina/files/2264855/IINA_2018-08-06-121602.txt)

- MPV log:

[2018-8-6-23-23-4_99oSuC.txt](https://github.com/lhc70000/iina/files/2264861/2018-8-6-23-23-4_99oSuC.txt)

**Steps to reproduce:**

Double click file to open. Observe crash.

- [x] MPV does not have this problem.

I tested the file on MPV 0.29.0 and the crash did not occur.

**How often does this happen?**

Every time the specific file is opened.

**Comment by inflation** [comment]
Can you try it with 1.0.0-beta3? That build uses latest `mpv`.

**Comment by TempSpas** [comment]
1.0.0-beta3 crashes as well. Here's the crash log:

[betalog.txt](https://github.com/lhc70000/iina/files/2266645/betalog.txt)

**Comment by inflation** [comment]
It's an FFmpeg bug. We use `sws_getContext` in order to do color conversion which calls the crashed function `sws_setColorspaceDetails` eventually.

Could you provide the sample file and report to them about the issue? In the mean time, you can try to disable the thumbnail preview.

**Comment by TempSpas** [comment]
The full file is about 6GB, so I'm not sure if I could give you the whole thing. I trimmed the first minute of the video with ffmpeg that you can test [here](https://send.firefox.com/download/4969937c47/#i0mXKXEN3CEta5U3xdFU4g). For some reason the trimmed minute is really choppy on VLC (the full file plays fine), but it still causes the crash on IINA, so it should still be relevant for testing.

And yeah, disabling the thumbnail previews allows the file to play just fine.
