### ISSUE TITLE
Duplicate Customize Control Strip menu item

### ISSUE THREAD

**Issue by tzhao11** [lhc70000/iina#190]
There are 2 identical <kbd>IINA</kbd>><kbd>Customize Control Strip...</kbd> menu items.

**Comment by lhc70000** [comment]
I cannot reproduce. This menu item is not controlled by IINA and such problem may result from system bugs.

If this problem persists (like after rebooting) and all other App , please provide more information like system version and machine model.

**Comment by tzhao11** [comment]
<img width="254" alt="2017-01-16 23 54 56" src="https://cloud.githubusercontent.com/assets/6540380/22009456/f8561a02-dc48-11e6-97f2-60c240edf50a.png">

These menu items only appear in IINA and I'm not sure why. As far as I know normally you could only configure control strip from system preferences. I'm on Late 2016 15-inch MacBook Pro (MacBookPro13,3) running macOS 10.12.2 (16C67).
