### ISSUE TITLE
[Bug] Float on top feature broken

### ISSUE THREAD

**Issue by StevenSeiden** [lhc70000/iina#1903]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta 3 (build 86)

**Expected behavior:**
When "Float on Top" is checked, clicking on other windows won't hide the current IINA window.

**Actual behavior:**

When "Float on Top" is checked, clicking on another window hides the IINA window behind the clicked window.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
- Check "Float on Top" in the menu bar.
- Click on a window that's in the background.
- The window may cover the IINA window.

- [x] MPV does not have this problem.

**How often does this happen?**

This happens about half of the time I try to have the window float on top.

**Comment by lhc70000** [comment]
Cannot reproduce this issue. Please provide more info such as the mpv log.

You can add "ontop" to Inspector(⌘I) - Status - Watch and check whether it's "yes".
