### ISSUE TITLE
Brakets not showing in UTF-8 encoded files

### ISSUE THREAD

**Issue by AhmedShaalan** [lhc70000/iina#1906]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
reading this sentence as
ما هو صواب؟
سأساعدك يا (بيلي)

**Actual behavior:**
https://ibb.co/ijozmU

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
Create an .srt with unicode of utf-8
add brackets to it.
and play it

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
I'm not familiar with Arabic but it seems to be an Unicode problem. I suggest reporting it to `mpv`.

**Comment by pbevins0213** [comment]
I'm experiencing same problem
any updates?

**Comment by mohmd1429** [comment]
I'm experiencing same problem
any updates?

**Comment by HarukaMa** [comment]
@mohmd1429 Can confirm mpv has same issue. Please report it to mpv instead.
