### ISSUE TITLE
请问能否增加视频统计信息这个选项

### ISSUE THREAD

**Issue by coldeve** [lhc70000/iina#1909]
很多播放器都有这个功能，可以看视频内的实时信息。
还有最好能看到cpu，gpu性能参数，mac自带的资源管理器没有gpu使用情况
谢谢啦

**Comment by inflation** [comment]
视频统计信息可以通过在视频内<kbd>⌘I</kbd>打开，更详细的还可以调用内置的脚本，比如添加快捷键：
![image](https://user-images.githubusercontent.com/2375962/43993331-9ced4964-9d59-11e8-9b0a-1955f2b448e2.png)

至于硬件占用信息，建议通过更专业的软件如iStat Menus来查看。
