### ISSUE TITLE
IINA and  muxed subtitles!

### ISSUE THREAD

**Issue by ExclusiveIINA** [lhc70000/iina#1910]
IINA cannot load normal subtitles automatically like .srt or .sub with the same name like the video. This issue appear only on videos that have muxed subtitle, on .mkv videos. On unmuxed .mkv videos the subtitles are working auto without issues. 

So, please make something to load auto the subtitle beside video no matter what is a video with muxed subtitles or not. I know i can put it manually and it works, but i want on .mkv videos with muxed subtitles to load auto the subtitles beside movie not to put it manually.

**Comment by lhc70000** [comment]
Cannot reproduce this issue. IINA should auto load external subtitles regardless of whether internal subtitles exist.

**Comment by lhc70000** [comment]
#816
