### ISSUE TITLE
Settings Page Dark Mode for Mojave

### ISSUE THREAD

**Issue by Shawzborne** [lhc70000/iina#1912]
Hi IINA Dev Team,

Can you please add dark mode to the settings page to match the dark theme? 

Thank-you,

Shawn

**Comment by lhc70000** [comment]
Full dark mode support is now under development at [mojave](https://github.com/lhc70000/iina/tree/mojave) branch and we are planning to ship it in 1.0.0 beta4. Stay tuned!
