### ISSUE TITLE
Play HEVC Videos with blue frames flicking

### ISSUE THREAD

**Issue by junzhli** [lhc70000/iina#1914]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1 Build 69

**Expected behavior:**

Play H.265 (HEVC) videos perfectly and smoothly using HW Decoder (VideoToolbox API)

**Actual behavior:**

Playing videos with blue frames flicking all the time
Like this [GIF](https://imgur.com/0ivKxuP)

- Crash report:
```

```

- MPV log:
  - [Pastebin](https://pastebin.com/HiJxxvr6)

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

Always

**Comment by inflation** [comment]
Duplicate with #1695. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
