### ISSUE TITLE
可不可以加入对bilibili弹幕的支持？

### ISSUE THREAD

**Issue by kirning** [lhc70000/iina#1916]
比如输入bilibili的视频地址链接，就可以在当前视频上显示该视频的弹幕，因为现在b站的动漫和谐太厉害了，但是自己另外下载的又没有弹幕，觉得有点可惜，望作者大人可以考虑一下

**Comment by xjbeta** [comment]
#154

**Comment by AndyChen2005121** [comment]
mpv应该不支持吧？
