### ISSUE TITLE
Feature Request: Integration of multimedia buttons (Apple Keyboard)

### ISSUE THREAD

**Issue by stefan1983** [lhc70000/iina#1918]
Feature Request:

Please use the multimedia buttons of the apple keyboard (F7 - F12):
![image](https://user-images.githubusercontent.com/8542806/44270841-da5a0100-a238-11e8-96d2-bd13ab8347ff.png)

Other music players have these features already (f.e. VOX):
![image](https://user-images.githubusercontent.com/8542806/44270793-c3b3aa00-a238-11e8-8d6a-d86668d0f748.png)

**Comment by xjbeta** [comment]
Preferences - Key Bindings - Use system media control

**Comment by stefan1983** [comment]
Ok, somehow did the setting of VOX music player setting in the system settings overrule the setting in IINA (picture 2 above). After deactivation it now works as fine. 

Thanks!

**Comment by alejx** [comment]
@stefan1983 It was VOX hijacks whole system media control. IINA tries to abide by the law, act like iTunes and other system media apps. So we are not going to capture media controls from apps like VOX.
