### ISSUE TITLE
Disable playlist

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [lhc70000/iina#1923]
This annoyance seems to have started fairly recently - like maybe two updates back.
I’ve been through the prefs and can’t find anything I may have changed that caused it.

I do not use playlists in video players and NEVER want to the playlist pane to slide over what I’m watching. It happens when the player window is double-clicked.

And especially annoying is that when double-clicked, the window also resizes from fullscreen to not fullscreen (the dang playlist is still visible). And when double-clicked again the window returns to fullscreen (with the playlist visible).

Why does a double-click make the window resize _and_ the playlist appear?!

IINA 0.0.15.1
OS X 10.12.6

**Comment by alejx** [comment]
I highly suspect you are using PopClip (or other similar utility app), in where you configure double click to paste. PopClip will send <kbd>⌘P</kbd> to IINA. In IINA 0.0.15.1, <kbd>⌘P</kbd> still means show playlist. We have changed this from <kbd>⌘P</kbd> to <kbd>⌘⇧P</kbd> in 1.0.0 beta 3.

**Comment by GitTheHellOutaHere** [comment]
I am indeed using PopClip, however it does not copy on double-click and there are no settings to make it do so.

A double-click merely activates its popup menu from where you can choose the next action.

I changed IINA’s double-click action to **None**.
Now the playlist doesn’t appear but the window still switches from fullscreen to not fullscreen and back.

**Comment by alejx** [comment]
> I changed IINA’s double-click action to None.
Now the playlist doesn’t appear but the window still switches from fullscreen to not fullscreen and back.

That's indeed a bug. Hopefully I'll fix it soon.
