### ISSUE TITLE
Where are the additional themes?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [lhc70000/iina#1924]
This page says there are four themes. https://lhc70000.github.io/iina/features/

![iina1](https://user-images.githubusercontent.com/15519219/44307704-06ba6e00-a35c-11e8-9c62-1f84f50c87af.png)

**WHERE?**

This page says there are only light and dark themes. https://github.com/lhc70000/iina/wiki/Feature-List

![iina2](https://user-images.githubusercontent.com/15519219/44307705-0fab3f80-a35c-11e8-8e1b-3754612ee6b9.png)

**I’m already aware of and using the dark theme. Where and what are the other two?**

**Comment by lhc70000** [comment]
The current website is pretty obsolete, which basically changed nothing from v0.0.1 (and yes, I don't have enough time to update it). You can change the theme in Preferences - General - Appearance (0.0.15 or 1.0.0 beta2) or Preferences - UI - Appearance (1.0.0 beta3).

In the next beta which will add support for Mojave, IINA will only have two themes (light and dark mode).
