### ISSUE TITLE
[Feature Request] Reading HTTP username & password from System Keychain

### ISSUE THREAD

**Issue by lfVictor** [lhc70000/iina#1928]
- macOS Version: 10.13.6 (17G65)
- IINA Version: 1.0.0-beta3 Build 86.

Recently, I usually watch videos which are on my WebDAV disk. But I have to type username and password each time, It's terrible.

How about making IINA read my username and password from the keychain automatically?

**Comment by lhc70000** [comment]
See #1901. This issue will be closed due to duplication.

This feature has been implemented in #1934.
