### ISSUE TITLE
Auto hide time for OSC | 控制面板停留时间过长

### ISSUE THREAD

**Issue by SaneBow** [lhc70000/iina#193]
很多时候控制面板一直不自动隐藏，或者很长时间才隐藏。希望可以缩短这个时间。

**Comment by lhc70000** [comment]
你可以在 `控制面板->UI->On Screen Controller` 中设定这个时间。当前中文翻译还不是太全面，0.0.3 会添加完整的多语言支持。

---

You can set this value in `Preference->UI->On Screen Controller`.

**Comment by alejx** [comment]
@SaneBow 第一个问题在#141里面提出过。
---
@SaneBow Your first issue have been raised by #141

**Comment by SaneBow** [comment]
谢谢
