### ISSUE TITLE
Cannot remember the last playback position.

### ISSUE THREAD

**Issue by cv0cv0** [lhc70000/iina#1933]
Cannot remember the last playback position.
记不住上次播放位置。

**System and IINA version:**

- macOS 10.14 beta
- IINA beta3 build86

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
只有在视频播放途中退出程序才会记录播放进度。

如果你认为有 bug，请给出重现方法。

**Comment by cv0cv0** [comment]
明白了，我是看到中途又打开其它视频了。

发自我的 iPhone
