### ISSUE TITLE
PIP not close when closing the main window

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#1937]
**System and IINA version:**

- macOS 10.14
- IINA develop

**Expected behavior:**

As shown in code, PIP should close when the main window is closed.

**Actual behavior:**

PIP does not close and remain a black window.

**Steps to reproduce:**

- Open a video
- Enter PIP mode
- Close the main window

**How often does this happen?**

Every time.

**Some investigations:**

When we want PIP window close, we call `exitPIP()` in the code and we use `pip.dismiss(pipVideo)` to close PIP. However, `pip.dismiss(pipVideo)` seems to do nothing. Moreover, `exitPIP()` is not a function in `PIPViewControllerDelegate`, so when PIP window is closed by the system, this function will not be called.

I found `- (void)animateDismissalOfViewController:(id)arg1 fromViewController:(id)arg2;` in `PIPViewController` in @steve228uk 's [hack](https://github.com/steve228uk/PiPHack/blob/master/PiPHack/PIP/PIPViewController.h). It can actually close the window, but with animation, which is very awkward. 

I'm not sure whether this used to be work, but it seems PIP framework does not provide a public method to close a PIP window according to other's hack. This issue might not finally be resolved.

**Comment by saagarjha** [comment]
Interestingly, this was a bug introduced by updating our version of Swift. Fixed by 658c11ba4e9491d8a2c1759b55c794a87bb3be6b.
