### ISSUE TITLE
Localization for 1.0.0 Beta 4

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#1947]
- [x] fr @superzazu
- [x] it @cgand
- [x] de @J-rg @shorshe 
- [x] ko @darkbrow
- [ ] ru @euf @imKota @Semty
- [x] ja @matsune
- [ ] tr @eminhaqi
- [ ] nl @ErikMinekus
- [ ] pl @Greenek
- [ ] es @Aikyuichi
- [ ] uk -
- [x] sk @Marvin99com
- [ ] da @thkir
- [ ] pt-BR @pradorocchi
- [x] en -
- [x] zh-Hans -
- [x] zh-Hant -

Dear translators, please update the translation if possible. If your translation is not submitted by the next Friday (Sep 7), English translations will be used for new strings by default.

If you are no longer able to provide new translations, please also kindly leave a message here.

Thanks a lot.

**It's recommended to use the IINA translation utility. Please download the latest release ([0.1.4](https://github.com/iina/iina-translation-utility/releases/tag/0.1.4)) before starting.**

**Comment by sevenfourk** [comment]
Hi @lhc70000, I'm sorry I don't have time to work on translations.  Can you please pass translation to un-assigned, someone might pick it up.  I've edited wiki to remove myself from there.  Thanks.  If anything needed further needed from my side, please let me know.

**Comment by MarcSteven** [comment]
@lhc70000  I think we can help to do the Chinese translation  if you agree.

**Comment by alejx** [comment]
@MarcSteven Sure thing! You are welcome to contribute zh-Hant localization. Currently we are using OpenCC to handle zh-Hant localization, which is somehow inaccurate.

**Comment by imKota** [comment]
@lhc70000 Already in the process of updating the translation.

**Comment by imKota** [comment]
@lhc70000 Done
https://github.com/lhc70000/iina/pull/1987
