### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by xhaythemx** [lhc70000/iina#1958]
I haven't seen anyone mention this, but IINA is a horrendous name.  The skill of the software developers seems to often be inversely correlated with their ability to market the software.  If they want this to become popular, they need a name that's somewhat meaningful, easy to pronounce, and memorable.  Not just some acronym that no non-techie will ever understand.  Example:  VLC - bad name also.  Plex - much better.

**Comment by inflation** [comment]
Well, the name is not from English. And please open issues about the software itself next time. You can discuss other concerns in email or telegram groups. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thoran** [comment]
Finnish from my investigations, but perhaps a mention of how the name came to be might be helpful?
