### ISSUE TITLE
Switching subtitle activates secondary subtitle instead

### ISSUE THREAD

**Issue by LEMONed** [lhc70000/iina#196]
IINA 0.0.2 build 3 doesn't replace the primary subtitle when you switch subtitle **from the menu bar**, it activates the secondary subtitle instead.

Happens with both external subs and built-in subs.

**Comment by lhc70000** [comment]
Confirmed that it does happen occasionally, thanks a lot for feedback!

**Comment by lhc70000** [comment]
Should have been fixed in `develop`.
