### ISSUE TITLE
Video always on top although the option for it is unchecked

### ISSUE THREAD

**Issue by bisherbas** [lhc70000/iina#1961]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1 Builg 69

**Expected behavior:**
When I launch another app or click on another window behind the video, IINA window should disappear.

**Actual behavior:**
Video is always on top although the option in the settings is unchecked. Regardless of video playing or paused, the video window is always on top of other windows on desktop. No matter what.

- [x] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by bisherbas** [comment]
![image](https://user-images.githubusercontent.com/42714627/45157701-e5f17580-b1af-11e8-8bba-a6a626557850.png)

**Comment by lhc70000** [comment]
You can toggle floating on top from the menu (or ⌃⌘T in the default key binding scheme). I think you might accidentally triggered it and the status is saved together with the playback progress, so every time when you open it again, it still floats on top.

**Comment by bisherbas** [comment]
Thanks but that option has been unchecked all the time. This behaviour is intermittent so I don't know how to prove it.
