### ISSUE TITLE
[Feature Request] Open .torrent files and stream

### ISSUE THREAD

**Issue by flavioharaujo** [lhc70000/iina#1963]
- macOS 10.13.6 (17G65)
- IINA 0.0.15.1

**Feature Request:**

Would be greate if we can open .torrent files or URLs and stream from iina.

**Comment by lhc70000** [comment]
Such a feature is unlikely to be integrated into IINA, but maybe you can use some other clients like https://www.webtorrent.io and set IINA as the external player (#388).

**Comment by cedricloneux** [comment]
why not?
