### ISSUE TITLE
是否支持1.2或1.5倍速播放？

### ISSUE THREAD

**Issue by Awezome** [lhc70000/iina#1964]
目前看只支持2倍速播放视频，是否支持1.2或1.5倍速播放？多谢。

**Comment by lhc70000** [comment]
- 快捷键 option+cmd+[ 或 ] 可调节 1.1 倍，菜单里按住 option 可以看到。
- 「视频」侧边栏中不仅可以拖动滑条调整速度，还可以输入任意速度。
- 所有快捷键都可以在偏好设置里自己编辑。

**Comment by Awezome** [comment]
多谢，找到了。
