### ISSUE TITLE
[CRASH] Music-Mode fails constantly in IINA 1.0.0 Beta4

### ISSUE THREAD

**Issue by GraOrigin** [lhc70000/iina#1969]
- macOS 10.12.6
- IINA 1.0.0 Beta4

- Crash report:

[MacOS Crash Report](https://paste.ee/p/rYY4L)

[IINA log](https://paste.ee/p/gBt7I)

[mpv log](https://paste.ee/p/rhWrg)

**Steps to reproduce:**
open any mp3 file in MacOS 10.12.6  -- it happens always.

Hope this helps - all the best guys!

**Comment by lhc70000** [comment]
Thanks for reporting. Seems that it's a 10.12 exclusive crash and we're finding solutions.

Should be related to 203b6d0.

**Comment by lhc70000** [comment]
Fixed via 43e2af9. Since it's a severe problem, I will release a new build ASAP.

**Comment by lhc70000** [comment]
@GraOrigin Could you test out this build and see if the crash has been fixed?

http://dl.iina.io/IINA.v1.0.0-beta4-build91.dmg

**Comment by GraOrigin** [comment]
@lhc70000 wow that was quick - thank you so much!
Music mode does work now without crashing with the provided version.

Sunny greetings from Bavaria
