### ISSUE TITLE
一个特殊的问题

### ISSUE THREAD

**Issue by 1158114251** [lhc70000/iina#197]
播放器做的非常漂亮，但是我在官网浏览的时候却发现了一张非常漂亮的图片，特地来问问这张图片是哪个视频的截图？就是一个带着白色帽子，前面放的一台示波器的这张图片。很炫，很科技

**Comment by lhc70000** [comment]
其实这种问题你可以给我发邮件之类^ ^||

视频名字叫做 CYMATICS: Science Vs. Music，YouTube 上可以搜索到，B站 av1717013。
