### ISSUE TITLE
'Pause'-Option (when opening file) value is ignored

### ISSUE THREAD

**Issue by GraOrigin** [lhc70000/iina#1974]
- macOS 10.12.6
- IINA 1.0.0 beta4 build 92

**Expected behavior:**
When 'Pause'-option (under 'when opening file') is unchecked, video/audio should start playing.

**Actual behavior:**
There's a regulating misfunction in the option "Pause" (when opening file).
When unchecked, video stops nevertheless - same as audio in music-mode..

**Comment by lhc70000** [comment]
> When unchecked, video stops nevertheless

Does it stop immediately or stop when you open it again? If the latter is your case, maybe it's caused by settings saved together with playback progress for this video. Please try unpause the video before quitting the player and test again.

**Comment by GraOrigin** [comment]
@lhc70000 
when opening a new video-file, IINA opens a window immediately in paused-state -- even though this option is unchecked (in settings under 'general' -> 'when opening file')

**Comment by GraOrigin** [comment]
@lhc70000 Update:

I noticed following;
when a IINA instance was closed while playing a file, next time opening the file it would start playback right away. When paused while closing the window, it would stay paused next time opening.
So it seems like these states are being saved individually on a file-to-file basis, and the global setting is ignored...

**Comment by lhc70000** [comment]
@GraOrigin Yes, this is the normal behavior of mpv. That global setting only controls whether to pause the video but not unpause.

**Comment by GraOrigin** [comment]
well then this issue can be closed I guess..
