### ISSUE TITLE
Can iina play 4k 60fps HEVC videos?

### ISSUE THREAD

**Issue by fwzmhmd** [lhc70000/iina#1980]
**System and IINA version:**

- macOS 10.13.6
- IINA 0.0.15.1 build 69

**Expected behavior:**
Run smoothly 😃 

**Actual behavior:**

Lots of stuttering, pausing and lagging.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
Import 4k 60fps videos from iPhone x in the Photos app

- [x] MPV does not have this problem.

**How often does this happen?**

When playing 4k 60fps videos recorded on iPhone X

**Comment by AuroraWright** [comment]
Which Mac do you have? Anything that's not a 2016 model or newer will have issues with HEVC 8 bit video, and anything that's not a 2017 model or newer will have issues with HEVC 10 bit video, on macOS. Sadly Apple's hardware accelerated HEVC decoding (used by ffmpeg, and in turn by IINA) does *not* support decoding on the GPU but only on the CPU (and only the latest Intel CPUs decode HEVC). You need to resort to Windows (bootcamp) to play those videos using your GPU (assuming you have a decent one).
