### ISSUE TITLE
volume up to 200

### ISSUE THREAD

**Issue by Nami2** [lhc70000/iina#1983]
in IINA v0.0.14.1 I can volume up to 200 using cmd + ⬆️

but in 1.0.0 I can't use cmd + ⬆️ to volume up to 200, 100 is max

- macOS 10.13.4
- IINA 1.0.0-beta2

**Comment by lhc70000** [comment]
@Nami2 Set the limit in Preferences - Video/Audio.

**Comment by Nami2** [comment]
😅 Thank you so much
