### ISSUE TITLE
Can the IINA play mp3 format music?

### ISSUE THREAD

**Issue by FengchiCrazy** [lhc70000/iina#199]
I open a mp3 format music with IINA. But I got an Fatal Error:

Fatal error: Frame buffer check failed 
The application will exit now.

But I can use QuickTime Player open the mp3 music correctly.

Could you please tell me why?

**Comment by lhc70000** [comment]
IINA currently doesn't support media without video stream (album covers in audio files are treated as video stream). We're going to fix this in next version.

Duplicate with #103.

**Comment by lhc70000** [comment]
Close due to duplication.
