### ISSUE TITLE
Request : Add an option to increase buffer size

### ISSUE THREAD

**Issue by irrelevantspechack** [lhc70000/iina#1993]
Hello,

I'm watching movies with IINA that are stored on my NAS which is connected to my laptop via Wifi.
I don't know why, I have enough wifi bandwidth but it always feel better to watch the movie when stored directly on my internal SSD.

I guess increasing the buffer size could worth the try, I have some unused GB of RAM anyway that could be used for a larger buffer. 

Maybe this service should not be used as a forum, sorry if it's the case, can you give me a link were i can talk about this without the need of the message being an exact "Request" or "Issue".

Thanks for the good work

**Comment by inflation** [comment]
We have a Telegram Group for discussion. You can check it on README.md. As for the question, you can change buffer size in `Preference > Network`, but I doubt that it would make any difference. The difficult buffer size is 150MB. The bottleneck is more likely at your network protocol. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
