### ISSUE TITLE
1.0.0 Beta Rendering the wrong color contrast and saturation with HDR blu-ray file.

### ISSUE THREAD

**Issue by skymaze** [lhc70000/iina#1994]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 Beta4

**Expected behavior:**
Using 0.0.15.1
<img width="1440" alt="2018-09-21 10 11 55" src="https://user-images.githubusercontent.com/4241798/45856392-db75d500-bd86-11e8-99e8-28d18648c2f6.png">

**Actual behavior:**
Using 1.0.0 Beta4
<img width="1440" alt="2018-09-21 10 09 12" src="https://user-images.githubusercontent.com/4241798/45856413-eb8db480-bd86-11e8-9730-671c5d28dfa1.png">

**Steps to reproduce:**
Just play a HDR BDMV file.

For your reference, Potplayer on windows has similar problem, but it provide a HDR SMPTE ST 2084 auto correct to correct the color.

**Comment by inflation** [comment]
Can you provide any log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sylar88889** [comment]
it's not a problem or bug since the HDR file is  using a ST2084 (PQ) curve . it is more like a log curve. that's why you got a sort of grey image because the curve(OETF) behind is not the normal Rec709 video which is using gamma 2.4.

**Comment by kirbyzhou** [comment]
What about Sony_4K_HDR_Camp.mp4?
ed2k://|file|Sony_4K_HDR_Camp.mp4|1204810814|34e179d04b765ff13a4d8894f7e29b58|h=hwb3sunxdinaxkel4tzis3wqf4dzuxhk|/

The sun and the fire seems be abnormal

**Comment by skymaze** [comment]
[iina.log](https://github.com/lhc70000/iina/files/2413755/iina.log)
[mpv.log](https://github.com/lhc70000/iina/files/2413756/mpv.log)

Here are the logs.

 @sylar88889 But v0.0.15 works well.And I didn't change any settings. The only difference is the iina version.

**Comment by inflation** [comment]
@skymaze There are internal mpv updates between the two version, so maybe they handled it differently. Can you manually set `icc-profile` like there #1673 and see if anything changed?

@kirbyzhou See #1673 and #888

**Comment by Hentaisubuta** [comment]
I met the same problem with beta 4.
it seems something wrong with the gamut remapping from BT2020 to BT709.
My assumption:
step 1:4K HDR file-BT2020 to BT709(will be done by default but does not work with beta4)
step 2:BT709 to target gamut by the setting"target-prim=xxx"(icc-profile=auto absolutely does not work with any iina version I have tried)

**Comment by Hentaisubuta** [comment]
![default](https://user-images.githubusercontent.com/43686278/46233388-f529a480-c3a4-11e8-8b2c-c7e86262969b.png)
only set icc-profile=auto  oversaturated
![default](https://user-images.githubusercontent.com/43686278/46233414-15596380-c3a5-11e8-8a90-7a08f06dd185.png)
set target-prim=adobe to override icc-profile setting

**Comment by inflation** [comment]
@Hentaisubuta `icc-profile=auto` is not working due to libmpv limitation. You should manually set it to your current profile or wait for next version (as fixed in #2006). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hentaisubuta** [comment]
![default](https://user-images.githubusercontent.com/43686278/46233591-d7a90a80-c3a5-11e8-8e72-533b904b8bb3.png)
beta4 with mpv 0.29
![default](https://user-images.githubusercontent.com/43686278/46233743-63bb3200-c3a6-11e8-9dc9-234b0fd4db59.png)
beta3 with mpv 0.28.2

Is mpv the reason why iina beta4 lost default converting from BT2020 to BT709?
icc-profile and target-prim setting did not affect this issue.

> @skymaze There are internal mpv updates between the two version, so maybe they handled it differently. Can you manually set `icc-profile` like there #1673 and see if anything changed?
> 
> @kirbyzhou See #1673 and #888

**Comment by inflation** [comment]
@Hentaisubuta `target-prim/trc` only works when no ICC profiles provided. So if you manually set the `icc-profile` and still get the same result, you should report it to mpv. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hentaisubuta** [comment]
> @Hentaisubuta `target-prim/trc` only works when no ICC profiles provided. So if you manually set the `icc-profile` and still get the same result, you should report it to mpv.
> 
> Sent with [GitHawk](http://githawk.com)

yeah, i just want to let you know that I have same issue with skymaze and icc-profile won't affect result.
Thank you for your advise. :)
