### ISSUE TITLE
在进行SVP设置中，删除了三个mpv运行库的文件后应用崩溃

### ISSUE THREAD

**Issue by AlexanderShang** [lhc70000/iina#1997]
按照安装SVP的步骤后，在删除mpv运行库后，应用无法正常打开视频并报错，貌似是无法调用homebrew安装的mpv运行库，请问怎么解决？

**Comment by lhc70000** [comment]
1.0.0 Beta 4 必须使用 0.29 以上的 mpv。

如果有其他问题，建议先贴上来崩溃日志。

**Comment by AlexanderShang** [comment]
了解，那安装0.29的mpv还是按照之前的代码吗？

**Comment by lhc70000** [comment]
是，wiki 上写的东西应该没问题。

**Comment by AlexanderShang** [comment]
但是它显示的是“mpv 0.28.2 is already installed and up-to-date”，0.28.2说是最新的

**Comment by lhc70000** [comment]
因为 brew 有一些问题，还没更新 0.29，可以加上 `--HEAD` 来从 master 安装

**Comment by AlexanderShang** [comment]
在代码后面吗？（对brew不太熟悉，抱歉）

**Comment by lhc70000** [comment]
@AlexanderShang brew install mpv --HEAD --with-uchardet --with-libbluray --with-vapoursynth

**Comment by AlexanderShang** [comment]
哦，好的，非常感谢🙏🙏

**Comment by AlexanderShang** [comment]
@lhc70000 很抱歉再打扰您，但是代码完成以后开启SVP后无法提高帧数，是不是需要设置一些其他的东西？

**Comment by AlexanderShang** [comment]
@lhc70000 “mpv HEAD-6eb59fe is already installed and up-to-date”，这个mpv版本是您所说的0.29.0版本吗？

**Comment by lhc70000** [comment]
> 代码完成以后开启SVP后无法提高帧数，是不是需要设置一些其他的东西？

我不清楚，没有用过 SVP，cc @HarukaMa 

> “mpv HEAD-6eb59fe is already installed and up-to-date”，这个mpv版本是您所说的0.29.0版本吗？

是的

**Comment by AlexanderShang** [comment]
有关SVP的问题我可以咨询他吗？ @lhc70000

**Comment by HarukaMa** [comment]
@AlexanderShang 播放视频时 svp 控制应用里能否看到统计信息？

**Comment by AlexanderShang** [comment]
SVP高帧率指数一直是不可用，其他指数正常 @HarukaMa

**Comment by HarukaMa** [comment]
@AlexanderShang 能否提供一下打开视频时 iina 的日志？

**Comment by AlexanderShang** [comment]
请等一下 @HarukaMa

**Comment by AlexanderShang** [comment]
[mpv.log](https://github.com/lhc70000/iina/files/2407882/mpv.log)

**Comment by AlexanderShang** [comment]
[iina.log](https://github.com/lhc70000/iina/files/2407891/iina.log)

**Comment by AlexanderShang** [comment]
请问是这两个吗？ @HarukaMa

**Comment by HarukaMa** [comment]
@AlexanderShang 是这两个，看上去哪里有些问题，我先在本地试试新版

**Comment by inflation** [comment]
@AlexanderShang 把硬解关了试试

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlexanderShang** [comment]
@inflation 是关掉SVP的硬件加速还是IINA的硬解？

**Comment by inflation** [comment]
@AlexanderShang IINA的

**Comment by inflation** [comment]
@AlexanderShang 这个问题最好再跟mpv反馈，是bug

**Comment by AlexanderShang** [comment]
好的，谢谢您！ @inflation

**Comment by 0u0u0** [comment]
这个问题困扰我很久。
建议将更新 mpv 的部分加入到 wiki。
