### ISSUE TITLE
Unable to find online subtitles

### ISSUE THREAD

**Issue by jediyoda36** [lhc70000/iina#1998]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**
There is always "No online subtitles find" for every movie.

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
Can I take a look at your Online Subtitles settings?

**Comment by jediyoda36** [comment]
![image](https://user-images.githubusercontent.com/13287220/45922921-b11b3900-bea6-11e8-952c-7d8bd6374337.png)

**Comment by jediyoda36** [comment]
> Can I take a look at your Online Subtitles settings?

![image](https://user-images.githubusercontent.com/13287220/45922926-c42e0900-bea6-11e8-8ec2-dd322438d04f.png)

**Comment by alejx** [comment]
shooter.cn has been not functional for years. Please try other source to download subtitles.

**Comment by jediyoda36** [comment]
ok, thanks.
it just works weeks ago.

**Comment by alejx** [comment]
@jediyoda36 Oh really? I haven't used it before so I can only guess based on their website.

**Comment by jediyoda36** [comment]
> @jediyoda36 Oh really? I haven't used it before so I can only guess based on their website.

Yes, their website was closed for years, but iina can still fetch the subtitles until weeks ago.

Maybe they shut down their servers recently.

Anyway, thanks for reply.
