### ISSUE TITLE
[功能优化]倍速播放递增后无法递减，反之亦然

### ISSUE THREAD

**Issue by wzshare** [lhc70000/iina#20]
设置倍速时，如果加速，2倍，4倍后按减速直接跳为-2倍，-4倍，体验不好，希望改进为可以2倍，4倍，2倍，1倍这样的功能；反之亦然。

**Comment by lhc70000** [comment]
和 #1  应该是一样的问题。

这是 QuickTime 的默认操作，如果需求很高的话会考虑修改。谢谢反馈

---

Duplicate with #1

**Comment by alejx** [comment]
See #1 .
