### ISSUE TITLE
IINA can't play JPEG2000 MXF file smoothly

### ISSUE THREAD

**Issue by sylar88889** [lhc70000/iina#2001]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0.beta4(92)

**Expected behavior:**

**Actual behavior:**
i just played a JPEG2000 encoded mxf file . it's a HD 25p HDR video ,  The IINA could decode it . but can't  play it smoothly. 

- Crash report:
```

```

- MPV log:
```


```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
it happened every time

**Comment by lhc70000** [comment]
Are you sure that mpv 0.29 can play the same file smoothly? If so, please provide the mpv log; or if mpv can't, please report to them.

**Comment by lhc70000** [comment]
@sylar88889 Download from their official build: https://laboratory.stolendata.net/~djinn/mpv_osx/

Or if you are using homebrew, the formula is not up to date for some reason. You can add --HEAD when installing to install the master version.

**Comment by sylar88889** [comment]
Thanks for your info. I just tested with MPV v0.29. I got same result with IINA player. It could be decoded but can’t play smoothly.




| |
Sylar Ma
邮箱：mmzsh126@126.com
|

Signature is customized by Netease Mail Master

On 09/24/2018 15:29, Collider LI wrote:

@sylar88889 Download from their official build: https://laboratory.stolendata.net/~djinn/mpv_osx/

Or if you are using homebrew, the formula is not up to date for some reason. You can add --HEAD when installing to install the master version.

**Comment by sylar88889** [comment]
So is this a bug or the performance of my laptop is not high enough ? i don's think is not a performance problem of the host machine. i tested it on a very high configuration Mac Pro . i got same result

**Comment by lhc70000** [comment]
Please report to mpv, with your log and sample video.
