### ISSUE TITLE
video lagging 

### ISSUE THREAD

**Issue by skku-hacker** [lhc70000/iina#2003]
**System and IINA version:**
macOS 10.13.6
0.0.15.1 Build 69

**Expected behavior:**
Lagging when watching the video.

**How often does this happen?**
Every 5-15 min

**Sample Video:**
magnet:?xt=urn:btih:627222b96e63aac907ca9a74513b2ffe571a2038

**Comment by inflation** [comment]
Thank you for the report. However, we don't have the effort to manually check every environment. Please attach the log and fill in the issue template.
