### ISSUE TITLE
Feature suggestion: 360 video support

### ISSUE THREAD

**Issue by edrozenberg** [lhc70000/iina#2009]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0 beta 4

**Expected behavior:**

**Actual behavior:**

Currently 360 video (videos filmed with 360 degree video cameras) are not properly supported by IINA. Such videos currently appear as a flattened wide and tall video in IINA showing all filmed points of view at the same time, and it is not possible for the user to pan around the view with the mouse.

Currently VLC 3.x supports this - as a result it's not super important for IINA to support, but it would be nice to have this support for sure in IINA as well in the future.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Thank you for the feedback. Please report to mpv and once they implement the feature we can use it too. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edrozenberg** [comment]
Thanks. I do see an open issue at mpv with comments from 2015-2017. Maybe something will happen there. They mention possibly merging some shading code to handle equirectangular projections (common case for 360 video). https://github.com/mpv-player/mpv/issues/2280
