### ISSUE TITLE
Safari 浏览器不再支持不安全的扩展。

### ISSUE THREAD

**Issue by anyforever** [lhc70000/iina#2010]
“Open in IINA”不再受支持。您可以在 App Store 或 Safari 浏览器扩展库中查找经过 Apple 审核的更新扩展

**System and IINA version:**

- macOS 10.14
- IINA 1.0

**Comment by inflation** [comment]
Duplicate with #1988 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
