### ISSUE TITLE
4K HEVC HW Decode Issue

### ISSUE THREAD

**Issue by jackwangshanghai** [lhc70000/iina#2011]
**System and IINA version:**

macOS 10.14
IINA 0.0.15 build 69

**Expected behavior:**
4K HEVC Playback Normally

**Actual behavior:**

If turn on hardware decode, the video is still playing but the blue frame blinking sound like decode problem and stop after serval seconds and resume again. The problem both occur in HW decode set to Auto and Auto(Copy), No issue with Disable.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
It's a known issue #1695. Please upgrade to the latest beta version. Thank you.
