### ISSUE TITLE
Setting file not work

### ISSUE THREAD

**Issue by shenguanjiejie** [lhc70000/iina#2019]
- macOS 10.14.0
- IINA 1.0.0.beta4 build92

![image](https://user-images.githubusercontent.com/9425605/46448990-3b736f00-c7bc-11e8-8bae-0fa5b5d2011b.png)

I edit this value 5 -> 2 , And restarted iina, Nothing changed.

**Comment by shenguanjiejie** [comment]
I got it, Cause That CheckBox.
![image](https://user-images.githubusercontent.com/9425605/46449299-dae53180-c7bd-11e8-93c2-b3c72699ee09.png)

**Comment by shenguanjiejie** [comment]
![image](https://user-images.githubusercontent.com/9425605/46710231-981dd080-cc79-11e8-956c-3a1a2079ab7c.png)

I click → button,It will seek 50s. Why?

**Comment by lhc70000** [comment]
The menu item now only binds to key shortcuts that seek for 5-10 seconds. Setting it to 2 will work, but it will not be displayed in the menu.

> I click → button,It will seek 50s. Why?

https://github.com/lhc70000/iina/wiki/FAQ#why-the-seeking-time-is-not-precise-when-pressing-arrow-keys
