### ISSUE TITLE
[REQUEST] 希望提供更多的播放速度档位.

### ISSUE THREAD

**Issue by finscn** [lhc70000/iina#2020]
- macOS 10.14
- IINA 1.0 beta4

现在只有 2倍和 0.5倍.  希望提供类似 1.2 1.25 1.5  等档位. 
现在很多电影在 1.2倍模式下播放是完全没有违和感的, 还能节省时间. 
延禧攻略我就是在 1.25倍下看完的.

所以希望IINA能够提供更多的变速档位.

**Comment by lhc70000** [comment]
- 快捷键 option+cmd+[ 或 ] 可调节 1.1 倍，菜单里按住 option 可以看到。
- 「视频」侧边栏中不仅可以拖动滑条调整速度，还可以输入任意速度。
- 所有快捷键都可以在偏好设置里自己编辑。
