### ISSUE TITLE
PotPlayer中的书签功能不知道从原理上iina可不可能实现

### ISSUE THREAD

**Issue by iAPPOpen** [lhc70000/iina#2025]
说实话觉得PotPlayer实在是全平台最强视频播放器，没有之一，一直觉得macOS上的视频播放器都很烂，iina是第一个让我觉得可以与PotPlayer一战的播放器，居然还是macOS平台的，好赞，毕竟是新出不久的播放器功能上现在已经很棒了，如果能够加入PotPlayer的书签功能就可以完全抛弃PotPlayer转投iina的怀抱了，被PotPlayer的书签功能养出了看视频会在自己喜欢人的地方做书签方便以后会看方便，用久了觉得挺实用，还可以添加书签标题记录看法观点之类的文字，这个书签文件还可以单文件存储，感觉很赞，请问iina从可行性上讲可不可能实现这种功能

**Comment by lhc70000** [comment]
Duplicate of #681
