### ISSUE TITLE
SWF格式还是无法播放。不知道以后会更新吗？

### ISSUE THREAD

**Issue by lclown** [lhc70000/iina#2026]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Duplicate with #1089.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
