### ISSUE TITLE
Can't remove filter with multiple parameters

### ISSUE THREAD

**Issue by duncannah** [lhc70000/iina#2032]
**System and IINA version:**

- macOS 10.14.0
- IINA 1.0.0-beta4

**Expected behavior:**

Selecting an active filter with multiple parameters and clicking on the remove button should remove the filter.

**Actual behavior:**

A "removed filter" message shows up, yet the filter stays and it's still active.

**Steps to reproduce:**

- Add a filter with multiple parameters (example: audio MPV filter scaletempo=stride=28:overlap=.9:search=25)
- Select the filter
- Click the minus button

- [x] MPV does not have this problem. (no option to change filters on playback)

**Comment by lhc70000** [comment]
Thanks for reporting! Fixed in develop branch.
