### ISSUE TITLE
[Feature Request] Hope to adjust the offsets of subtitle and sub-subtitle separately

### ISSUE THREAD

**Issue by sn20110327** [lhc70000/iina#2034]
**System and IINA version:**

- macOS 10.14
- IINA 1.0.0-beta4 Build 92

**Expected behavior:**
Hope to adjust the offsets of subtitle and sub-subtitle separately, thanks.
希望可以分别调整字幕与副字幕的延迟。
该需求是在观看一小语种电影时遇到的，只有两个相应的字幕文件，一中一英，其中中文的翻译不完整，英文虽完整但是看不够顺，想同时显示两种字幕但时间轴之间有几秒的时间差。
这种时候，可以分别调整两个字幕的延迟就很实用了。
作者辛苦了，十分感谢。

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
The secondary subtitle is not configurable at all because mpv didn't implement it.
