### ISSUE TITLE
Youtube Video has No Sound

### ISSUE THREAD

**Issue by lewisxy** [lhc70000/iina#2036]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta4 Build 92

**Expected behavior:**
When I enter the link of YouTube in the `open URL`, it should play the video as it is from the YouTube Website.

**Actual behavior:**
The video has no sound (the sound adjusting bar is gray (unadjustable) compare to normal video and the audio tab in the setting for this video said `None`, but there is sound when I play this video on the Youtube Website.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
Try to use [this](https://www.youtube.com/watch?v=qRNuyIflhLs) link in `open URL`.

- [ ] MPV does not have this problem.

**How often does this happen?**
So far only for this video

**Comment by alejx** [comment]
You should probably report this to mpv or youtuble-dl, I've tried it in mpv and it does not have sound either.
