### ISSUE TITLE
Feature Request: Keyboard shortcut to switch audio device

### ISSUE THREAD

**Issue by YourMJK** [lhc70000/iina#2041]
**System and IINA version:**

- macOS 10.14
- IINA 1.0.0-beta4 Build 92

**Feature Request:**

When creating new keyboard shortcuts, there should also be an action to set/switch the audio output device.
Often when you start playback of a video and the sound is not coming from your headphones or receiver you want to quickly switch to the next audio device, without having to navigate with the mouse through the menu.

**Comment by lhc70000** [comment]
You can enter the mpv command manually. Please refer to https://github.com/mpv-player/mpv/issues/2398.
