### ISSUE TITLE
mkv video bottom part could not show

### ISSUE THREAD

**Issue by zhisays** [lhc70000/iina#2049]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Could you try disabling hardware decoding?
