### ISSUE TITLE
Cover art disappears when switching between video mode and music mode

### ISSUE THREAD

**Issue by ErikMinekus** [lhc70000/iina#2057]
**System and IINA version:**

- macOS 10.14.1
- IINA latest commit (ab2c206)

**Expected behavior:**
The cover art should stay visible when switching between video mode and music mode.

**Actual behavior:**
The cover art disappears. Pausing the song makes it appear again. This does not happen on 1.0.0-beta4 build 92, so it must have broken recently.

**Steps to reproduce:**
- Open an audio file.
- Switch between music mode and video mode.

**How often does this happen?**
Always

**Comment by alejx** [comment]
Caused by 1b39cc775be28d0eff00df5aa1497b710451b20a and c25ef55781676d0407ea0a754dc16432859c9cc8. You can also reproduce this by toggling pip mode when the media is paused.
