### ISSUE TITLE
Feature Request: realtime waifu2x support / other upscale support

### ISSUE THREAD

**Issue by Willian-Zhang** [lhc70000/iina#2059]
This would be a very game-changing and nice-to-have feature.

#### Problem and Discussions:
- GPU or NPU required for any device support such feature, as "realtime" requires such.
    - Both modern iOS Devices and Android devices are equipped Neural Processing Engine, it wouldn't be surprise, next gen. desktops will too.
- Support for AMD GPU
    - `Waifu2x` is based on Torch7, which needs more investigation on if supports AMD GPUs, Read more on:
        - [Caffe and Torch7 ported to AMD GPUs, MXnet WIP](https://streamhpc.com/blog/2017-05-15/caffe-torch7-mxnet-ported-amd-gpus/)
        - [ROCm](https://rocm.github.io/dl.html)
- Model Compression for Mobile Devices
- Upscaling speed estimation 

More on [waifu2x](https://github.com/nagadomi/waifu2x)

_Although Mobile Support is not goal of IINA, I think Neural Network Processing might be a common plugin/usage in future media players, thus a good discussion to start here._

**Comment by inflation** [comment]
ROCm doesn’t support macOS and in the foreseeable future it won’t. If you’d like to have neutral network upscaling algorithms, please report to mpv. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pk2413** [comment]
How to activate npu in android?
