### ISSUE TITLE
关于快进按钮的建议

### ISSUE THREAD

**Issue by niudiewei** [lhc70000/iina#2065]
- macOS 
- IINA 

<h3>快进按钮和快退按钮不够人性化</h3>
<p>快进速度一次2x不能接受，考虑一下更小的值。</p>
<p>按下快进键之后按快退键设置成减小快进的速度</p>
<p>如果不明白我想表达的内容，试用一下IOS的"nplay"软件，能改成它这种快进和快退的样子就行的</p>
谢谢🙏

**Comment by lhc70000** [comment]
- 快捷键 option+cmd+[ 或 ] 可调节 1.1 倍，菜单里按住 option 可以看到。
- 「视频」侧边栏中不仅可以拖动滑条调整速度，还可以输入任意速度。
- 所有快捷键都可以在偏好设置里自己编辑。

**Comment by niudiewei** [comment]
多谢
