### ISSUE TITLE
Last Played History?

### ISSUE THREAD

**Issue by sandlst** [lhc70000/iina#207]
Hi, I'm enjoying the program automatically creating playlists with all the files in the folder, but I have an issue; namely when I watch lots of videos from the same folder I don't know which one I stopped on when I close the program and open it later.

I can see in the recently opened list what the first video I opened was, but obviously this doesn't reflect the last video watched in the session if multiple videos are watched via a playlist.

I'm not really sure if it would be better to have a separate history list in addition to the recently opened list somewhere or just have an option to update that recently opened entry with the last file that started playing when the player was closed / another file was manually opened, or even something completely different.

**Comment by lhc70000** [comment]
Good suggestion.

**Comment by sandlst** [comment]
I noticed today that with the "Resume last Playback" option checked you can drag an entire folder to the icon to open all media files inside as a playlist; later if you drag the entire folder again it will pick up on the playlist video you left off on automatically.  It also puts the entire folder in the recently opened items so resuming is quick and easy.

I feel like this pretty much removes the need for anything else like a history list etc.

There are a few issues I've discovered playing around with doing this but I'll open them separately.

**Comment by excelwang** [comment]
Making distinctions between "history list" and "recently opened list"  will confuse users. Laterally, the "recently opened list" should consist of latest video files played in the previous play session, no matter the file is manually opened or automatically opened by a playlist.
