### ISSUE TITLE
在播放过程中崩溃

### ISSUE THREAD

**Issue by haibeichina** [lhc70000/iina#2071]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>
<pre>

</pre>
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>
<pre>

</pre>
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by haibeichina** [comment]
在播放过程中，设置->通用->强调色 会崩溃

**Comment by lhc70000** [comment]
@haibeichina 未能重现。请提供崩溃日志。
