### ISSUE TITLE
Severe UI problems on 10.13 due to cc9e5689948e77a29607bd4a2e1db26e90817134

### ISSUE THREAD

**Issue by AuroraWright** [lhc70000/iina#2074]
**System and IINA version:**

- macOS  10.13.6
- IINA  Latest release/1.0.0 commit (https://github.com/lhc70000/iina/commit/518ed22d0877967aa2ca6aa3a6fb6f475c13d53d)

**Expected behavior:**
UI is displayed properly.

**Actual behavior:**
It's hard to describe, but the overlay menu (with the play/pause buttons, etc) and any other overlays just show weird colored edges instead of the actual UI. See image: https://imgur.com/a/WvmnsAy
This does not happen on 10.14, so it seems to be 10.13-only (and possibly lower versions as well).
This commit seems to be the culprit: https://github.com/lhc70000/iina/commit/cc9e5689948e77a29607bd4a2e1db26e90817134

<details>
<summary><b>Crash report:</b></summary>
<pre>

</pre>
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>
<pre>

</pre>
</details>

<br>

**Steps to reproduce:**
Open any file with IINA.

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by alejx** [comment]
@saagarjha Could you take a look at this?

**Comment by saagarjha** [comment]
Sure, let me grab a copy of High Sierra and spin up a VM to test this out. AFAIK the API I used should work in High Sierra, but there might be a change in Mojave that makes it work differently. In the case that this doesn't work, I'll add the old implementation back conditionally in the else block of `#available(macOS 10.13, *)`.

**Comment by saagarjha** [comment]
Ok, so apparently VirtualBox doesn't really do graphics well, so it's basically useless for testing IINA on earlier versions of macOS. I'll look into creating a High Sierra partition to investigate further, but until then I've conditionally reverted this change for 10.13 and below in bac77a692710e766e4d4c843d92f78f5981308cc. @AuroraWright, please let me know if this solves the issue for you.
