### ISSUE TITLE
Error: Cannot open file or stream

### ISSUE THREAD

**Issue by raptorrr** [lhc70000/iina#2075]
**System and IINA version:**
- macOS 
OS X El Capitan Version 10.11.6
- IINA 
0.0.15 Build 68

I just downloaded IINA and when I try to play youtube/dailymotion video links through the Open URL option, it gives me the error: cannot open file or stream.

**Comment by lhc70000** [comment]
@raptorrr Please refer to the “Use your own binary” section in https://github.com/lhc70000/iina/wiki/Use-youtube-dl-with-IINA
