### ISSUE TITLE
[Consistency Issue / suggestion] concerning Volume-Icon-Indicator

### ISSUE THREAD

**Issue by GraOrigin** [lhc70000/iina#2076]
**System and IINA version:**

- macOS 10.14.1
- IINA 1.0.0 beta4 Build 92

**Expected behavior:**
Whether in Video-Mode or Music-Mode, IINA should have a consistent Icon-Behavior

**Actual behavior:**
In Video-Mode the Volume-Icon is clearly crossed out when mute.
In Music-Mode there is no indication when mute, icon stays the same throughout

Looking forward to 1.0 stable - great work so far guys

**Comment by alejx** [comment]
Fixed in release branch.
