### ISSUE TITLE
Build failed with lastest source code

### ISSUE THREAD

**Issue by gavin1818** [lhc70000/iina#2078]
**System and IINA version:**

- macOS 10.13.6
- IINA develop branch lasted commit id: 5eb40a3e19a46e368874caa15967897aa833d1cc
- XCode 9.4.1

**Expected behavior:**
build successful in Xcode

**Actual behavior:**
build failed with multiple errors message

<img width="270" alt="screen shot 2018-11-11 at 3 36 13 pm" src="https://user-images.githubusercontent.com/7432529/48380108-668a9180-e68b-11e8-82e2-ab8ffa93fcda.png">

**Comment by gavin1818** [comment]
New to Mac os development, any clue is appreciated. Thanks

**Comment by inflation** [comment]
You need Xcode 10 to support new Swift features. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
