### ISSUE TITLE
暂停的逻辑：暂停之后，打开新文件和切入下一个文件是否可以不暂停？

### ISSUE THREAD

**Issue by smart-z** [lhc70000/iina#2080]
目前点了暂停，打开新文件和切下一个文件都还是暂停，之前不是这样的；
按习惯来说，打开新的和切下一个都准备播放，已经包含了“播放”这样的操作，之前是这样；

不知道可不可以还原以前或者有这样的设置？感觉之前的是符合习惯的。现在看视频看到一部分，切下一个和开新的老得再按一次播放，还挺烦得。

**Comment by alejx** [comment]
已经在 dev/release 分支修复，请等待下一个版本。

**Comment by smart-z** [comment]
nice
