### ISSUE TITLE
1.0.0beta4在macos10.14.1中快进不是按秒快进,按一下快进好几分钟,自定义快进一秒也没用直接快进好几分钟

### ISSUE THREAD

**Issue by GeneralZMX** [lhc70000/iina#2082]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
1. 参考 https://github.com/lhc70000/iina/wiki/常见问题#为什么按左右键跳转的时间不精确
2. 可能你的文件或 mpv 出现问题。这种情况请附上 mpv 日志并最好直接向 mpv 报告。
