### ISSUE TITLE
h.264 10bit 不能硬解 1080p

### ISSUE THREAD

**Issue by GTGraphics3** [lhc70000/iina#2084]
**System and IINA version:**

- macOS <10.14.1 (18B75)>
- IINA <1.0.0-beta4 Build92>

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

h.264 8bit  Hevc 8bit 10bit 都可以正常硬解

**Comment by inflation** [comment]
Apple不支持H264 10bit硬解。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
