### ISSUE TITLE
Open multiple media simultaneously | 支持多开

### ISSUE THREAD

**Issue by dumo** [lhc70000/iina#209]
希望能够像QuickTime或者Movist一样支持运行多个实例，一次打开多个视频文件，但不知道实现有多复杂……

**Comment by Miigon** [comment]
目前IINA封装的负责播放的playercore是单实例的，这就意味着多个视频无法被同时播放
前段时间有过关于改写为Document-based应用的讨论，每个视频作为一个文档被打开，即可以打开多个视频
**但是**这样的改进会需要修改大量现存架构，特别是需要多视频的类抽象（目前都糅合在playercore里）
#187

**Comment by megadr01d** [comment]
Adding duplicate reference so it's easy to close all when implemented: https://github.com/lhc70000/iina/issues/79

**Comment by lhc70000** [comment]
Close due to duplication.
