### ISSUE TITLE
In version 0.0.15, When play a video with multiple audio tracks, after change the audio track, the voice will disappear. But if I close the app and reopen the app the voice works well. Please fix the bug.

### ISSUE THREAD

**Issue by BugTan** [lhc70000/iina#2094]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
I'm afraid that it's a mpv issue. Please wait for the 1.0 release and see if it has been fixed.
