### ISSUE TITLE
bar in IINA 1.0.0-beta 4

### ISSUE THREAD

**Issue by Hamadstore** [lhc70000/iina#2099]
IINA 1.0.0-beta 4 [Screenshot](https://raw.githubusercontent.com/Hamadstore/mikasa-san.github.io/master/Screen%20Shot%202018-11-29%20at%207.14.52.png)

IINA 1.0.0-beta 3 [Screenshot](https://raw.githubusercontent.com/Hamadstore/mikasa-san.github.io/master/Screen%20Shot%202018-11-29%20at%207.16.04.png)

Something not normal in the bar in IINA 1.0.0-beta 4

- macOS 10.12.5
- IINA 1.0.0-beta 4

**Comment by alejx** [comment]
I tried to fix the issue but I cannot access to a Mac with OS X 10.11 or 10.12. Could you please help me to test this build on your machine? Thanks.
https://drive.google.com/open?id=1TrX0ZYvOx-jxOHZNn60aX_3z6kyQJQP8
