### ISSUE TITLE
Enhancement on inspector | 检查器

### ISSUE THREAD

**Issue by satellitemx** [lhc70000/iina#21]
使用 CMD + i 打开的视频检查器中，视频、音频的比特率均以 bps 的单位显示。希望 IINA 能够自动判断数字大小，并以 Kbps / Mbps 的方式显示，这样会更加直观。

同时，发现有较多视频 IINA 无法读取其视频流码率，显示 Error。
![IINA](https://ww4.sinaimg.cn/large/006y8lVagw1fbfqktwedzj30c20coq3p.jpg)
![FFmpeg](https://ww2.sinaimg.cn/large/006y8lVagw1fbfqmfxn1rj30l60gddj2.jpg)

**Comment by lhc70000** [comment]
感谢反馈。当前检查器还十分简陋，后续版本中会不断改进。

也请在此提出检查器的更多建议，比如该显示哪些信息。

---

Currently inspector is just barely useable and may lack some necessary information. It should be updated in future versions.

Please suggest more enhancements on inspector.

**Comment by megadr01d** [comment]
- FPS (Video)
- File size (Video and Audio)
- Number of audio tracks (Audio)
- "Subtitle" section below "Audio" when subtitles are embedded (.mkv, .mp4) with relevant information like language

**Comment by lhc70000** [comment]
Please check out the new inspector in 0.0.6.
