### ISSUE TITLE
播放视频的时候操作菜单中的章节条目会导致播放器崩溃

### ISSUE THREAD

**Issue by iAPPOpen** [lhc70000/iina#2108]
如题

**Comment by lhc70000** [comment]
请提供崩溃日志。

你可以在「控制台.app」左侧的 User Reports 中找到。

**Comment by iAPPOpen** [comment]
> 请提供崩溃日志。
> 
> 你可以在「控制台.app」左侧的 User Reports 中找到。

你的机器上不能重现吗

**Comment by HarukaMa** [comment]
>请提供崩溃日志。

**Comment by lhc70000** [comment]
@iAPPOpen 不能

**Comment by iAPPOpen** [comment]
没有发现有日志，可能这个不是崩溃吧，弹出了一个对话框，内容如下：

「严重错误：mpv API error: "error running command", Return value: -12. 
程序将立刻结束。」

点击确定按钮后iina退出

**Comment by lhc70000** [comment]
@iAPPOpen 如果你愿意继续找原因，可以提供
- IINA 版本和系统版本
- 出错时的 iina 和 mpv 日志（偏好设置-高级里开启）

**Comment by iAPPOpen** [comment]
IINA：1.0.0-rc（95）
macOS：10.14.2 beta（18C52a）
其他不会操作，我看看再说

**Comment by iAPPOpen** [comment]
忘了说，播放的视频是没有章节的

**Comment by lhc70000** [comment]
已在 f1a6000 修复，感谢。
