### ISSUE TITLE
Error dialogue not dismissable, cannot exit application once it pops up.

### ISSUE THREAD

**Issue by jbwl** [lhc70000/iina#211]
I tried using the "Find online subtitles" function. It said "3 subtitles found". Then an error dialogue popped up (see screenshot). I cannot dismiss this dialogue in any way (The button does not respond to clicks, keyboard navigation does not seem to work). The application keeps on playing the video file, with no way to access its UI anymore (because the dialogue is in the foreground). Only "force quit" lets me leave the Application at that point.

The secondary problem being of course that the found subtitles were not downloaded to the video file folder.

![error](https://cloud.githubusercontent.com/assets/2697194/22098528/0775c7e6-de27-11e6-8aa7-8d6ecb025404.jpeg

**Comment by lhc70000** [comment]
Does this happen every time?

> found subtitles were not downloaded to the video file folder

Saving them without permission could confuse user, but I'll definitely add some options for it in the coming versions.

**Comment by jbwl** [comment]
Yes, the app says for instance, "found 3 subtitles", but nothing is downloaded. Every time for the same video file.

**Comment by jbwl** [comment]
For the same video file, this error is not occurring anymore with version  0.0.3 Build 4
