### ISSUE TITLE
Chrome extension: IINA app does not exit when window is closed

### ISSUE THREAD

**Issue by plashenkov** [lhc70000/iina#2110]
**System and IINA version:**
- macOS 10.14.1
- IINA 1.0.0-RC build 95

**Expected behavior:**
When opening IINA via Chrome extension, after closing IINA window, IINA app should be closed as well (the corresponding setting is ON).

**Actual behavior:**
If IINA is opened with Chrome extension, closing IINA window does not affect IINA app. It still stays in Dock as a running app.

**How often does this happen?**
Every time when IINA opened via Chrome extension.

**Comment by alejx** [comment]
Thank you very much!
