### ISSUE TITLE
[Feature Request] Option/Command to close current video/forward player window

### ISSUE THREAD

**Issue by mwinkw** [lhc70000/iina#2112]
macOS 10.14.1
IINA 0.0.15.1 Build 69

**Expected behavior:**

A (key bindable) option to close the current video container. 

**Actual behavior:**

Currently there's only an action to Quit. 
This quits the entire application.
To close the current video container, one needs to select the Red X in the top left corner of the window.

**Comment by lhc70000** [comment]
@mwinkw How about cmd+w?

**Comment by mwinkw** [comment]
> @mwinkw How about cmd+w?

Yeah I forgot about that... coming from base mpv I'm just used to hitting Q to quit.
