### ISSUE TITLE
Feature reuqest: Suport MPV Encoding

### ISSUE THREAD

**Issue by gagarine** [lhc70000/iina#2114]
MVP let you (re)encode video file in other format:

```
mpv infile -o outfile [-of outfileformat] [-ofopts formatoptions] [-orawts] \
  [(any other mpv options)] \
  -ovc outvideocodec [-ovcopts outvideocodecoptions] \
  -oac outaudiocodec [-oacopts outaudiocodecoptions]
```
See https://github.com/mpv-player/mpv/blob/master/DOCS/encoding.rst

Would be nice to have an interface to access this features. Like a "save as..." or ""export as..." menu and a dialog box to chose some presset using the MPV device targets features:

> mpv infile -o outfile.mp4 -profile enc-to-iphone-5

And perhaps some major format like VP8, H254, H265 keeping the source resolution.

**Comment by inflation** [comment]
Please use other specific tools for that purpose. Thank you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lhc70000** [comment]
- IINA is compiled without encoding libraries to reduce binary size.
- The mpv encoding feature is primitive and it sometimes produces undesired output.
- It's hard to call this feature from client API. 

 Please use FFmpeg for encoding or a FFmpeg GUI if needed.
