### ISSUE TITLE
Resize the video when side pannel is open (no overlay)

### ISSUE THREAD

**Issue by gagarine** [lhc70000/iina#2115]
The side panel open on top of the video:
![screenshot 2018-12-08 at 20 40 48](https://user-images.githubusercontent.com/164074/49689975-c577e500-fb29-11e8-9f4b-2b1356177ab8.png)
![screenshot 2018-12-08 at 20 40 40](https://user-images.githubusercontent.com/164074/49689976-c741a880-fb29-11e8-9d8f-e0627ca812b5.png)

The problem was discussed their #42 but I propose another solution. We can resize the video and keep the control on top:

![image](https://user-images.githubusercontent.com/164074/49690054-fb699900-fb2a-11e8-9041-ad08beaf8fc6.png)
A big advantage, you can then close the side panel by clicking on the same button.

Another option, also resize the control (i like it less because more things are moving):

![image](https://user-images.githubusercontent.com/164074/49690070-3cfa4400-fb2b-11e8-8c86-0cfec77fa837.png)

**Comment by lhc70000** [comment]
Please continue the discussion in #42 rather than creating a new issue.
