### ISSUE TITLE
Full screen option in Video menu is not sync with player state

### ISSUE THREAD

**Issue by Gisonrg** [lhc70000/iina#212]
Hi, 

if I enter the full screen with the hotkey (such as press `F`), the "Enter full screen" in the View menu should now become "Exit full screen", but currently it will remains to be "Enter full screen" even though I am already in full screen. As you can see in the screenshot (I am in full screen mode).

![screen shot 2017-01-19 at 8 06 22 pm](https://cloud.githubusercontent.com/assets/4332224/22106260/e430b5b4-de82-11e6-8616-0d8e65dcc6a0.png)

Also, if I enter the full screen by choosing the menu option, but exit full screen with `ESC`, the display text remains to be "Exit full screen" even though I have exited full screen. As in the screenshot (I have exited full screen)

![screen shot 2017-01-19 at 7 57 32 pm](https://cloud.githubusercontent.com/assets/4332224/22106301/11500324-de83-11e6-9931-cf46340945b9.png)
 
Tested on OS X Sierra 12.2, IINA 0.02 Build 3.

I guess need to check the state of the player in order to display the text properly, regardless how I enter the full screen :)

**Comment by alejx** [comment]
I noticed that both `Video` and `Window` menu has `Exit Full Screen` menu item. Whereas the one in `Video` has its hotkey on it. The one in `Window` is synced with the window correctly (maybe because it is implemented by NSWindowControllerDelegate by default). Thus I suggest remove `Exit Full Screen` in `Video`, bind the hotkey onto the one in `Window`.
I also think `Float on Top` should be a property of window but not video.

**Comment by Gisonrg** [comment]
@alejx Actually I believe put the `Full Screen` in Video/View menu other than `Window` is (kind of) the standard in OS X. You may refer to Preview.app/Mail.app or Chrome or MPlayerX, they all put `Full Screen` under `View` menu instead of `Window`. 
Therefore I suggest to go with the (probably) industrial standard and remove the `Full Screen` from `Window` and fix the one in `Video` (or even rename it to `View`? :P).

**Comment by alejx** [comment]
@Gisonrg You are right. I inspect QuickTime, `Full Screen` and `Float on Top` are in `View` menu. And by default, there doesn't exist `Full Screen` in `Window`.
![image_2017-01-19_10-03-41](https://cloud.githubusercontent.com/assets/20237141/22114378/dafaa292-de2e-11e6-8b27-f16664fbf2bb.png)
