### ISSUE TITLE
iina 使用感受

### ISSUE THREAD

**Issue by tonyank** [lhc70000/iina#2135]
使用了一下 iina，发现几个现象：
1、mac 下的体验没有 Windows 下如丝般地顺滑，有些地方很卡顿。
2、iina 没有老爸 mpv 顺滑小巧，希望快默认捷键沿袭 mpv。
3、1.0.0 RC 版比 0.0.15.1 版要顺滑一些，推荐安装 RC+ 版。
希望再接再厉。LOL

**Comment by inflation** [comment]
This is not a forum. Please don't spam it. 

For the second question, you can set the keyboard shortcut to mpv in Preference. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
