### ISSUE TITLE
[Feature Request]Delete files without checking if trash exists

### ISSUE THREAD

**Issue by hstdt** [lhc70000/iina#2137]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.1.0-rc build 95

**Expected behavior:**

When I deleting files from smb/afp volume, it always failed for no trash. In this case, can IINA delete files without checking(or adding an option in setting)?

![image](https://user-images.githubusercontent.com/10215098/50372806-23b7c400-0610-11e9-813b-40dbf622e797.png)

**Comment by lhc70000** [comment]
You can add a new key binding and set the action to "Detele current file directly without moving to trash".
![4e11a90b-2ee6-4820-afb5-3d326eb369f5](https://user-images.githubusercontent.com/8478049/50372966-c07b6100-0612-11e9-85eb-01b9ce16396f.png)

**Comment by hstdt** [comment]
@lhc70000  Thanks!
