### ISSUE TITLE
Fast Forward does not reset to 1x speed when pausing with spacebar

### ISSUE THREAD

**Issue by chrikop** [lhc70000/iina#214]
**Steps to reproduce**
Play a music or video file, click on the fast forward button, then pause with spacebar. When continuing playback (either through spacebar or clicking on the play button) playback continues at the last selected (increased) speed but the speed indicator next to the fast forward button is gone. 

**Expected behaviour**
When pausing it should reset to 1x speed. If you pause by clicking on the pause button it does reset to 1x speed.

**Comment by lhc70000** [comment]
All key bindings are achieved through mpv's input system, and seems that it's not possible to run two mpv commands (`pause` and `set speed 1`) on one key press.

Maybe the best solution is setting speed to 1x on pause regardless of how it was triggered.

**Comment by ewoks** [comment]
@chrikop why expected is to reset speed to default? In my opinion it should continue playing with configured speed, not reset to 1x. Can you explain and clarify this please? Maybe I misunderstood the point.

**Comment by chrikop** [comment]
@ewoks I based my expectations on the fact that when pausing a video by clicking on the pause button it resets to 1x (and the indicator next to the forward button vanishes). When pausing by hitting space the indicator vanishes as well, which I think shows that the intended behaviour is indeed to reset to 1x when pausing.
In my opinion it makes more sense to reset to 1x when pausing, not to continue with the accelerated/decreased speed. Consider this situation: You fast forward through a video until you found the spot you want to watch with normal speed again. What do you do to stop FF? Currently there is no button to reset to 1x (except pause), so you would have to click the fast foward button multiple times until you have reached 1x again. But, since this takes a little time and you were playing at speed > 1, you are now a few seconds past the spot where you wanted to watch in 1x again and you have to rewind.
The way it is currently implemented you can save yourself the hassle and just pause the video, it automatically resets to 1x and you're good to go. Seems like a better solution to me.
