### ISSUE TITLE
Add Next/Previous buttons

### ISSUE THREAD

**Issue by chrikop** [lhc70000/iina#215]
Currently there is no possibility to skip to the next/previous file in the playlist other than to open the playlist and click on the file you want to play.
In VLC they look like this:
<img width="261" alt="vlc" src="https://cloud.githubusercontent.com/assets/9819843/22110838/7f96ace6-de5d-11e6-91aa-fbc726a0b254.png">

**Comment by megadr01d** [comment]
I prefer to use hotkeys for everything but, *only as a suggestion*, to keep the controller simple as it is and using the OS X way of providing alternative commands without clutter, holding the <kbd>⌥</kbd> (Option) key could turn the rewind/forward buttons into previous/next buttons.

**Comment by neesonqk** [comment]
@chrikop There actually is such a feature to config the left right buttons into previous/next media.

![image](https://cloud.githubusercontent.com/assets/7279067/22131802/aeffb930-def0-11e6-8c27-530cdc7970d5.png)


@lhc70000 What if we change the left-right buttons' icon accordingly to its configuration? which will make less confusion I suppose...

**Comment by neesonqk** [comment]
Adding two more extra icons doesn't seem to be the best choice, makes the control bar redundant.

**Comment by lhc70000** [comment]
@megadr01d @neesonqk good suggestion! I'll consider adding it in 0.0.4.

**Comment by neesonqk** [comment]
@DrabWeb 

I wrote an implementation of this feature, however, the icons for Previous/Next Video looks a bit blurry and incorrect size, if you could help to doctor a proper version will be a great plus since I have no idea about how to produce icon at all XD.

![image](https://cloud.githubusercontent.com/assets/7279067/22491437/5dc1537c-e85e-11e6-8473-67bca2c5c80c.png)

**Comment by saagarjha** [comment]
I believe @DrabWeb is using PDF vector icons. Maybe he'd be able to put them here?

**Comment by DrabWeb** [comment]
The icon PDFs are all in https://github.com/lhc70000/iina/tree/master/iina/Assets.xcassets
@neesonqk I could put some icons together tomorrow if you want

**Comment by neesonqk** [comment]
@DrabWeb Yes please, I realized there are actually many icons in Assets already, but the two icons I want are absent XD, like the above screenshot I took, I'd like a pair of mirror icon which indicates Next/Previous video. 

Just right like this: 
![image](https://cloud.githubusercontent.com/assets/7279067/22493985/99a4111c-e86e-11e6-82a4-6b67673d0854.png)

Many thanks.

**Comment by DrabWeb** [comment]
![screen shot 2017-01-31 at 11 23 45 pm](https://cloud.githubusercontent.com/assets/6215387/22494258/6962fcfa-e80c-11e6-8ca1-845ddfe8cd62.png)

Actually had some time right now, how does this look @neesonqk ?

**Comment by neesonqk** [comment]
Looks great, how do you pass over to me?

**Comment by DrabWeb** [comment]
[next.pdf](https://github.com/lhc70000/iina/files/743801/next.pdf)
[previous.pdf](https://github.com/lhc70000/iina/files/743802/previous.pdf)

**Comment by kalensky** [comment]
Hi, I'm using a TV remote control and I need to map the remote's buttons to keybord shortcuts.
Is it possible to add some shortucts for Next/Previous?
Thank you!

**Comment by lhc70000** [comment]
@kalensky Just add a new key binding and choose "Next media" from the drop down menu.

To add new keybindings, you need to duplicate a default keybinding config in Preferences.

**Comment by kalensky** [comment]
@lhc70000 Thanks for quick answer, I didn't know about this feature!
