### ISSUE TITLE
On Screen Controller and pointer don't disappear automatically

### ISSUE THREAD

**Issue by okla** [lhc70000/iina#216]
For example, when moving from one space to another space occupied by player window in full screen mode, OSC and pointer appear but don't disappear automatically until the pointer is moved.

**Comment by alejx** [comment]
Duplicate with #141 , fixed in #170 .

**Comment by lhc70000** [comment]
Close due to fixed in [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3).
