### ISSUE TITLE
Suggestions on OSC

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#217]
> I prefer shortcut keys myself, but anyway, I'm not sure why we haven't yet changed the volume bar paradigm and make it circular. Not only fits the size of the other icons (and UI symmetry), but it's also easy to control with a trackpad/mouse.
> 
> I think it's way easier to click anywhere on a round icon and move up/down to turn the volume up/down than to aim at a thin bar or small knob. Sometimes it's so badly implemented that moving a bit up or down while we're moving left or right (while holding left click), will take the pointer out of the slider bar, losing focus.
> 
> Example Volume Icon
> 
> ![qjhae](https://cloud.githubusercontent.com/assets/9649385/21933348/f5ed7656-d99c-11e6-8abf-a47659c0a9d0.png)
> 
> Example Volume Icon and Mute Icon in one (clicking once would mute/unmute, clicking and holding + moving up/down would change volume)
> 
> ![minimal_slider_widget___volumes](https://cloud.githubusercontent.com/assets/9649385/21933351/fb86126c-d99c-11e6-8ffa-cd26d41b03b9.png)
> 
> Another suggestion is to make the playlist icon thicker, with only 3 horizontal lines instead of 4. Currently, it seems out of place with the other icons, too thin. Not sure why it has to be similar to QT, Apple not always makes the best decisions in UI design, we're just conditioned to think they do.
> 
> Finally, I would like that IINA remembers where I dragged the OSC the last time, between launches. In Movist, I usually drag it to the top of the player so it doesn't cover my subtitles and I hate to position it every time I launch the app.

from #97

**Comment by LeoNatan** [comment]
This is not a standard UI element in macOS.
Personally, I think it's has a bad UX overall when using a mouse or trackpad.

**Comment by megadr01d** [comment]
@lhc70000 You can close this one. I wasn't aware the discussion had already developed in the pull request so I was late for the party. As far as I've seen, circular bars are only used in mobile devices anyway, don't need to keep this open as it was just a low-priority suggestion to the original thread.
