### ISSUE TITLE
fwd/next keyboard shortcuts for playlist items

### ISSUE THREAD

**Issue by Helmi** [lhc70000/iina#219]
I'm using iina to playback live streams from a local TV server. All tv stations are contained in a playlist file. Beeing able to switch between stations with the keyboard would be great. Something like ⌘+↑ and ⌘+↓ or something similar would be great.

**Comment by lhc70000** [comment]
If the list is just a (mpv) playlist, you may use media keys to switch between items. In default key binding (`IINA Default`), `<` and `>` are also set to previous and next item in playlist.

Alternatively you can set a custom key binding by yourself. Just open Preference > Keybindings and add a new line with action `playlist-prev` and ``playlist-next`.
