### ISSUE TITLE
Move check for updates menu bar option

### ISSUE THREAD

**Issue by funkenstrahlen** [lhc70000/iina#221]
Most apps do have the `Check for updates` menu bar option in the dropdown right under the app's name. Currently this app shows it under Help. Maybe you should consider moving it so it can be found more easily by users.

**Comment by lhc70000** [comment]
Thanks for suggestion, and, it has been added to [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3).

You opened this issue right before releasing 0.0.3 so I fixed it as it's a simple task 😉.
