### ISSUE TITLE
Incorrect rendering resolution when opening file in full screen

### ISSUE THREAD

**Issue by Daniel09MM** [lhc70000/iina#224]
Downloaded subtitles look fuzzy on my MacBook Pro's 13'inch with retina display. 
I trying changing letter fonts, size and so on but the problem remains. 

<img width="1440" alt="screen shot 2017-01-21 at 16 30 16" src="https://cloud.githubusercontent.com/assets/25267127/22175919/048b1c9e-dff7-11e6-965b-c5ea7f756705.png">

**Comment by lhc70000** [comment]
Have you tried exiting and entering fullscreen again?

**Comment by Daniel09MM** [comment]
It worked. Thank you 👍

**Comment by lhc70000** [comment]
Then it should be a bug.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
