### ISSUE TITLE
"Always float on top while playing" breaks window management

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#225]
When "Always float on top while playing" is enabled, the maximize button turns into zoom ("+"), and window management is broken. For instance, it does not appear when trying to enter split screen.

The current implementation of "float on top" is broken.

See the video here for reproduction:
https://youtu.be/z6mzCPa-Mxs

**Comment by lhc70000** [comment]
I'm aware of this problem too since last version, but no solution found.

If you have any idea about the window ordering mechanism, please update me, thanks.

---

Problem statement: Full screen button turns to zoom button (+) when setting `window.level` to a larger value.

**Comment by LeoNatan** [comment]
I will take a look soon. Thanks.

I don't think this is an enhancement. It's a bug.

**Comment by LeoNatan** [comment]
@lhc70000 Found a fix. Will submit a PR now.

**Comment by LeoNatan** [comment]
Fixed in PR
