### ISSUE TITLE
Zoom window by touchpad pinch gesture | 触控板双指缩放

### ISSUE THREAD

**Issue by shule1987** [lhc70000/iina#23]
你好,我非常喜欢您写的这个应用,我本身也是一个UI,UE设计师, 我认为您设计的这个软件很好看,也很好用
双指缩放功能我是在mplayerX上用到的, 我觉得这个功能非常有用, 希望您可以加上这个功能,万分感谢

**Comment by lhc70000** [comment]
我开发过程中想过做这个（包括双指旋转），不过当时有点问题就注释掉了。

一旦有精力，我会在后续版本中实现它。

**Comment by alejx** [comment]
See #464 .
