### ISSUE TITLE
crash when right click a video and then choose "open with IINA.app"

### ISSUE THREAD

**Issue by xpsair** [lhc70000/iina#231]
macOS 10.12.1
crash when right click a video and open with IINA.app
<img width="1005" alt="screen shot 2017-01-21 at 9 18 53 pm" src="https://cloud.githubusercontent.com/assets/3363680/22179372/8afa4c64-e01f-11e6-9beb-54336cb6310e.png">

**Comment by lhc70000** [comment]
You are still using **0.0.1**.

The latest version is **0.0.3**, which can be found in [github release](https://github.com/lhc70000/iina/releases) or on [website](https://lhc70000.github.io/iina/).

**Comment by xpsair** [comment]
yeah, the new version fixes this crash problem 👍

**Comment by lhc70000** [comment]
Nice.
