### ISSUE TITLE
set playing video on top window, but when paused, it's still on top window

### ISSUE THREAD

**Issue by frozenthrone** [lhc70000/iina#234]

**Comment by lhc70000** [comment]
It's intended currently.

We'll add an option for not floating on top when paused later.

**Comment by xu-cheng** [comment]
@lhc70000, I think you should implement such feature by syncing with mpv's `ontop` property. If so, for advanced users who have [this lua script](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ontop-playback.lua), they will have this feature as same as one in native mpv.

You may notice I have suggested, in many place, to have iina syncing with mpv more closely through `mpv_read/set/observe_property` (maybe done inside `PlayerCore.swift` in async fashion as mentioned by you). My thought is that iina should have a better user interface than the original mpv, but keeping all the advance features (such as lua scripts) at the same time.

**Comment by alejx** [comment]
See #496 & #604 .
