### ISSUE TITLE
Open Playlist from URL as CLI parameter

### ISSUE THREAD

**Issue by Helmi** [lhc70000/iina#235]
When opening iina from the Command line it would be great to be able to pass a URL of a playlist or file to open.

In VLC this works by just adding this URL as a first parameter, so something like

`/Applications/IINA.app/Contents/MacOS/IINA http://url.to/playlist.m3u `

would be great.

**Comment by saagarjha** [comment]
I was actually thinking of adding a separate command line tool. What do you think, @lhc70000?

**Comment by lhc70000** [comment]
@saagarjha  Yes definitely a command line tool would be nice.

Slightly duplicate with #58.

**Comment by alejx** [comment]
Close due to duplication.
