### ISSUE TITLE
Display sleeps when playing video | 播放视频时仍会进入屏幕睡眠状态

### ISSUE THREAD

**Issue by avalanchesiqi** [lhc70000/iina#237]
MBP, macOS Sierra 10.12.2.
When playing a video, my display will go to sleep mode when no action taken in certain time (say 5 mins). IINA is still working with sound, just sleeping screen.

**Comment by Windywind** [comment]
Same issue, Screen goes dark first, have to touch the trackpad or do sth. else.

**Comment by lhc70000** [comment]
I cannot reproduce this in 0.0.3.

This should be a problem fixed in 0.0.2. Are you using the latest version?

**Comment by avalanchesiqi** [comment]
switch to the latest 0.0.3, problem fixed.

**Comment by Windywind** [comment]
Yes, I was using 001version, and now updated and fixed.

**Comment by kjstart** [comment]
I am using 0.0.5 right now, it comes again.
