### ISSUE TITLE
Window have light background in light theme

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#238]
Should always be black.

**Comment by tpict** [comment]
I see grey (rather than black) letterboxes with any theme as of 0.0.3

**Comment by LeoNatan** [comment]
Do you mean the title bar?
This was added by #90.

**Comment by tpict** [comment]
No, this is regarding letterboxes when watching full-screen video:

![screen shot 2017-01-24 at 19 42 32](https://cloud.githubusercontent.com/assets/12588098/22263751/696435ce-e26d-11e6-884f-15c6f0d45835.png)
0.0.2

![screen shot 2017-01-24 at 19 43 08](https://cloud.githubusercontent.com/assets/12588098/22263755/6dea524a-e26d-11e6-98f0-a140388bd147.png)
0.0.3 (dark theme)

![screen shot 2017-01-24 at 19 43 15](https://cloud.githubusercontent.com/assets/12588098/22263760/72c9cbba-e26d-11e6-9283-440e066cba44.png)
0.0.3 (light theme)

**Comment by LeoNatan** [comment]
Hmmm I see. Yeah, not good.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
