### ISSUE TITLE
Crash after searching online subtitles | 查找在线字幕后闪退

### ISSUE THREAD

**Issue by jediyoda36** [lhc70000/iina#239]
- 新版本(0.0.3)查找在线字幕之后闪退

**Comment by lhc70000** [comment]
- 请说明是在什么情况下出现
- 请说明是否总是发生，能否重现
- 请说明是否只对某一视频发生（如果是的话，请提供视频文件名等信息）
- 如果是崩溃，请附上系统报告

---

I need more information like system crash report.

**Comment by jediyoda36** [comment]
- 点击加载在线字幕之后立即闪退
- 只对“[克洛伊].Chloe.2009.BluRay.720p.DTS.x264-CHD.mkv”这个视频发生

**Comment by jediyoda36** [comment]
- 手头可测试的视频不多，明天白天再测试几个

**Comment by jediyoda36** [comment]
文件名问题，已解决

**Comment by lhc70000** [comment]
😂 能告诉我具体是什么问题么

**Comment by jediyoda36** [comment]
文件名前的“[克洛伊].”删掉就不崩溃了😂

**Comment by mcknight0219** [comment]
这问题还是存在啊，你能附上你的字幕文件吗？

**Comment by lhc70000** [comment]
It happens when filename contains non-ASCII characters. Fixed in develop branch.
