### ISSUE TITLE
Support multiple screen | 多屏幕支持

### ISSUE THREAD

**Issue by xshwy** [lhc70000/iina#24]
双屏的时候，在2号屏幕看视频，用command + 0 / 1 / 2 设置视频大小的时候，视频会自动调回主屏幕。

系统：macOS 10.12.1
主屏：mac本机, Retina, 15-inch
副屏：DELL U2414H

**Comment by lhc70000** [comment]
感谢反馈，有更新会在这里 update。

**Comment by halblooline** [comment]
mac外接显示器，播放窗口没法从一个屏幕拖动到另外一个屏幕，不论是直接拖动还是从多任务窗口拖动都不行，强行拖会闪退，OSX 10.11.6 (15G1212)

**Comment by lhc70000** [comment]
@halblooline 闪退时能否生成错误报告并发上来？
