### ISSUE TITLE
Show localized font name

### ISSUE THREAD

**Issue by kuzmailer** [lhc70000/iina#242]
如图，字体库里的中文字体全部显示不出来
![image](https://cloud.githubusercontent.com/assets/16309612/22200137/d211f726-e198-11e6-8ae1-1793d1262054.png)

**Comment by lhc70000** [comment]
它们现在是以**英文名**显示的。

后续版本中会考虑支持本地化的字体名。

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
