### ISSUE TITLE
Window disappears after restoring from minimized to dock

### ISSUE THREAD

**Issue by LEMONed** [lhc70000/iina#246]
To reproduce:

1. Active "Always float on top while playing" (which requires a restart).
2. Click the yellow dot to minimize IINA to dock.
3. Click on the dock icon to restore IINA window.
4. IINA window restores then disappears instantly. There's no way to call out the window again.

With "Always float on top while playing" disabled, window restores just fine.

IINA 0.0.3 b4

**Comment by lhc70000** [comment]
Has been fixed in develop by #226.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
