### ISSUE TITLE
High energy usage when paused

### ISSUE THREAD

**Issue by gvilty** [lhc70000/iina#249]
IINA v0.0.3 b4
macOS Sierra 10.12.2
MacBook Pro 15" (late 2013) with Intel Iris Pro

Reproduction steps:
1. open a video
2. pause
3. look at Activity Monitor's Energy tab
4. IINA still uses lots of resources (about half of what it's using when playing the video)

**Comment by lhc70000** [comment]
Duplicate with #51, #107.

It's probably due to current rendering mechanism, and we are planning to revamp it in 0.0.4. BTW "about half of what it's using when playing the video" is quite valuable information, thanks.

**Comment by lhc70000** [comment]
0.0.4 _should_ fixed high CPU usage problem. Please test if there's any improvement.

If the problem persists, please reopen this issue.
