### ISSUE TITLE
about the UI and the progress bar

### ISSUE THREAD

**Issue by hintheshell** [lhc70000/iina#251]
1. when the mouse enter the red area(maybe 25% above the bottom), show the progress bar
![](http://spicery.d.pr/jTBh.jpg)
2. no titlebar
3. I don't think a quicktime style progress bar is easy to use , most time we use shortcut to control and get the information , so a huge progress bar is bulky , and maybe you can beautify the current progress bar , and make it at the bottom like my screenshots , it will not block subtitles(maybe a little)
## 主观意图：遮挡画面字幕的部件越少越好越小越好越简洁越好。
1. 当鼠标进入底部20%左右区域 出现进度条比较好
2. 不要上边的title bar （做成可选）
3. 类似QuickTime的进度条 感觉太臃肿了 容易遮挡字幕和画面 基本上都是快捷键操作 呼出进度条再鼠标操作费时费力 还容易遮挡 进度条贴在底部是最好的 
4. 鼠标放在进度条上时显示当前时间戳  
![](http://spicery.d.pr/9nQO.jpg)

**Comment by LeoNatan** [comment]
I don't like this UX at all.

**Comment by hintheshell** [comment]
OK. Everyone has its own taste. Perhaps it can become an optional feature.

**Comment by alejx** [comment]
Why do you choose IINA instead of using MPV directly?
