### ISSUE TITLE
Adjustable play-list panel width

### ISSUE THREAD

**Issue by SaneBow** [lhc70000/iina#253]
Currently there seems to be no way to adjust panel width of play-list. Sometimes I got long file names and couldn't manage to display full file names. This is inconvenient  e.g. when I was watching TV series, since information in filenames like episodes were hidden.

**Comment by Miigon** [comment]
@lhc70000 This can be fixed if we add auto-layout for playlist panel and quicksettings panel.

**Comment by Miigon** [comment]
This can be fixed if we add auto-layout for QuickSettings panel and Playlist panel
(A commit in #165 has added auto-layout for `MainWindowController.xib`)

**Comment by saagarjha** [comment]
@Miigon I'm not the one who added AutoLayout; you can thank @DrabWeb with that in pull #90. I just improved the constraints (but I'd be happy to add AutoLayout to the playlist panel in a commit).

**Comment by Miigon** [comment]
@saagarjha awesome!

**Comment by saagarjha** [comment]
@lhc70000 Check #165, which adds AutoLayout. Dragging is coming soon, but you can change the size in `SideBarViewType` from 360 to something greater and see if it lays out the views correctly.

**Comment by alejx** [comment]
Fixed in develop. See #673 .

**Comment by jrz** [comment]
Please reopen, it's not fixed.
