### ISSUE TITLE
Duplicate Apps In Mac’s Right Click “Open With” Menu

### ISSUE THREAD

**Issue by Revod** [lhc70000/iina#256]
![screen shot 2017-01-24 at 12 19 39 pm](https://cloud.githubusercontent.com/assets/10109689/22255919/67f3bb9e-e22f-11e6-9e9c-bc4ec92e4d33.png)

In every update I have that problem I need to run
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
```

and Relaunch Finder while Pressing Alt and click on "Relaunch" this is a macOS Sierra Bug or problem with the app?

**Comment by saagarjha** [comment]
I'm not seeing this; are you keeping multiple versions of the app somewhere?

**Comment by Revod** [comment]
No, just saw the update popup, download from here, extract it and then move to /Applications/ and Replace the old one

**Comment by Miigon** [comment]
Maybe you need to delete the old one before move the new one to `/Applications/`?

**Comment by lhc70000** [comment]
Run the following line in terminal to resolve this:
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"
```

([source](http://osxdaily.com/2013/01/22/fix-open-with-menu-mac-os-x/))

**Comment by lhc70000** [comment]
A better solution:

1. Open a video by a version you'd like to delete.
2. Cmd+Left click the dock icon. It will bring you to the location of the `.app` file.
3. Delete it.

**Comment by Revod** [comment]
I use the command to fix but I will try with the new update (I'm downloading rn) and test if appear again that duplicate version

**Comment by freedani** [comment]
I think it may not an IINA problem. Same problems would appear with Atom/VSCode etc. which is not downloaded from MAS.

**Comment by Revod** [comment]
yeah, but I dont saw more the problem, actually I update without problem, download the new release, replace the old and done, and work fine
