### ISSUE TITLE
Add title for TextFields.

### ISSUE THREAD

**Issue by Miigon** [lhc70000/iina#257]
The titles of TextFields are mostly "Text Cell"
```
/* Class = "NSTextFieldCell"; title = "Text Cell"; ObjectID = "GXH-iA-cJP"; */
 "GXH-iA-cJP.title" = "Text Cell";
```
Only add titles for them can make IINA work properly with VoiceOver.

**Comment by lhc70000** [comment]
Most of such cases are placeholders in table view, and the cells will be filled by real data at run time.

**Comment by lhc70000** [comment]
Does it actually affects VoiceOver?

**Comment by Miigon** [comment]
Yes,and when I seleted TextField for inputting custom speed,it just say "TextField".

**Comment by lhc70000** [comment]
Oh I thought you were talking about the text cells in tables. 

Nice suggestion.
