### ISSUE TITLE
Inconsistent File -> Open Compared to Dragging Items Onto Icon

### ISSUE THREAD

**Issue by sandlst** [lhc70000/iina#258]
Hi, currently you can drag a folder containing video files to the IINA icon when it is open to add all video files to a playlist automatically.  You can also drag multiple files selected at the same time (via shift clicking) to the icon and it will do the same thing.

Trying to open a file via File -> Open however only allows you to open a single file, and also does not allow you to select a directory.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
