### ISSUE TITLE
Search and download online subtitles | 自动搜索下载线上字幕

### ISSUE THREAD

**Issue by poorfish** [lhc70000/iina#27]
简洁漂亮的界面！感谢！
但自动加载线上字幕一直是我无法弃用SPlayer的原因，我知道这个不仅仅是个技术问题，但有没有可能呢？

**Comment by guoyf** [comment]
mpv有自动下载字幕的脚本可以用。

**Comment by lhc70000** [comment]
和 #3 重复。

由于用户需求很大，下一个版本会加入。

---

Duplicate with #3 .

Should be added in next version due to large user demand.
