### ISSUE TITLE
mpv_opengl_cb_report_flip should probably be called inside the DisplayLink callback

### ISSUE THREAD

**Issue by pigoz** [lhc70000/iina#28]
Hi!

I was checking out your rendering code, and I noticed you call `mpv_opengl_cb_report_flip` inside `drawFrame` (1). I think it would be better to call it inside `drawVideo`after the `flushBuffer`took place.

During normal operation (24p on 60hz display) it should make little difference, but calling the function when the flip actually happened will help with options like `--video-sync=display-resample` (2) to work correctly.

(1): https://github.com/lhc70000/iina/blob/master/iina/VideoView.swift#L285
(2): https://mpv.io/manual/master/#options-video-sync

**Comment by lhc70000** [comment]
Wow, didn't expected a mpv contributor will be interested in this project. Thank you very much!

It should be fixed in next version.

**Comment by lhc70000** [comment]
Sorry that a push to `master` closed this issue automatically (now switched to `develop` branch for development).

Please review and reopen the issue if need. Thanks.

**Comment by pigoz** [comment]
LGTM! Thanks 👍
