### ISSUE TITLE
Display remaining time when clicking on duration label

### ISSUE THREAD

**Issue by metacosm** [lhc70000/iina#283]
Clicking on the duration label (rightLabel) in the control bar should cycle between remaining time and duration, similar to what Quicktime Player (and others) do.

**Comment by metacosm** [comment]
This issue should be closed now, no?

**Comment by lhc70000** [comment]
I'll close it after releasing v0.0.4, in 10 minutes.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
