### ISSUE TITLE
History record

### ISSUE THREAD

**Issue by nileibin** [lhc70000/iina#286]
The current version can only show the files directly open before. When watching TV series, I usually use fast forward to the next episode. However these episodes cannot be found in the history, and I cannot know the last episode I watch in this case.

It will be very helpful if this player can records the files played recently, not just opened recently.

**Comment by lhc70000** [comment]
Thanks for feedback. It's in our plan.

**Comment by Rockergmail** [comment]
also clean the history record needed ! For AV

**Comment by alejx** [comment]
Fixed in develop. See #595 .
