### ISSUE TITLE
Prevent sleep only when a video is playing

### ISSUE THREAD

**Issue by mshick** [lhc70000/iina#287]
The current behavior has IINA preventing system sleep whenever it is open with a video loaded. VLC, on the other hand, only prevents sleep when the video is playing. 

I think the VLC behavior is more natural. The IINA sleep behavior has led me to annoying situations like: I pause a video to talk on the phone, get busy with another task, and return to my computer 30 minutes later to find my battery dead.

**Comment by lhc70000** [comment]
Fixed in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

**Comment by brechtm** [comment]
Could this be made optional? When playing a video on my TV I use a game controller as a remote to control playback. When I pause the video for a couple of minutes, my MacBook goes into sleep, and I have to get up to turn it on and unlock it. Can you imagine the excruciating effort this takes? 😉
