### ISSUE TITLE
Translations for new features

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#291]
@shilch @Solaarmoon @LEOYoon-Tsaw @darkbrow

Dear translators,

IINA v0.0.4 is ready to release and some new features were added in this version.
Please refer to the following commits to update your translation:

- [SC translation for added features (8d78252)](https://github.com/lhc70000/iina/commit/8d78252f6b5ab947843c8f9710097f51a9308a5d)
- [translation for subtitle downloading (8f8112d)](https://github.com/lhc70000/iina/commit/8f8112dc50c525332d017df22e89c6906883f21e)

**Comment by shilch** [comment]
I'll have a look

**Comment by shilch** [comment]
Done

**Comment by lhc70000** [comment]
@shilch @Solaarmoon @superzazu @metacosm @LEOYoon-Tsaw @darkbrow @cgand

IINA v0.0.5 is about to release.

Please provide translation for recent features:

- `Localizable.strings`: PIP support, playlist menu, etc.
- `MainMenu.xib`: File loop, save playlist, playlist/chapter panel, etc.
- `KeyBinding.strings` (under Views-Preference): See attached screenshots.
- `PrefGeneralViewController.xib`: Playlist related settings
- `PrefNetworkViewController.xib`: Some default values, youtube-dl
- `PrefSubViewController.xib`: ASS override level (no need for "strip"/"force"), sub position
- `PrefAdvancedViewController.xib`: Add "…" at line 30


For key bindings:

![f23360a2-dc93-40d1-9e99-0679866c5371](https://cloud.githubusercontent.com/assets/8478049/22860960/bd4233f6-f147-11e6-9551-69c84a89255c.png)

![bcc9f7f4-dbb7-4605-9dd2-7154d7de12b7](https://cloud.githubusercontent.com/assets/8478049/22860961/c1ab8910-f147-11e6-8e29-02acd2e4aef6.png)

- Strings that start with `cmd.` are commands (data in first column)
- Strings that start with `opt.` are option names (data in "Set"/"Cycle"/"Add"/"Multiply" command)
- Most of other strings are some commonly used ones.

Take seek (which is the most complicated one) as example:

`cmd.seek` `backward|forward` `(value)` `relative|...`
=> Seek backward (value) s

`cmd.seek` `seek-to` `(value)` `absolute|...`
=> Seek to (value) s

Where `seek-to` is just translated to "to" in English. But in other languages, you may need to make adjustment due to different word orders. For example in Chinese, it was actually translated to "Seek, Jump to, (value), s".

**Comment by lhc70000** [comment]
@shilch @Solaarmoon @superzazu @metacosm @LEOYoon-Tsaw @darkbrow @cgand

Hi all, please add translation for the newly added features if you have time.

I created a [Slack](https://slack.com) group for IINA development and also #translation channel for further communication. Please tell me your email (by [sending me email](https://github.com/lhc70000), finding me in Telegram group, etc.) so I can send you invitation.

---

Changed files:

- `Contribution.rtf`: This will show in About window. You are not required to translate the GPL declaration part, but if you want, please try to find a generally accepted translation in your language first; and since **only the English version is effective, please don't delete it**.
- `KeyBinding.strings`: Keys starting with `read.` are for "readable" mpv commands. They use the [Mustache](https://mustache.github.io/mustache.5.html) syntax, but you only need to know that
  - `{{value}}` is embed a value;
  - `{{#condition}} {{/condition}}` means `if` and `endif`.
Please refer the English version as example.
- `KeyRecordView`
- `Localizable.strings`: Deleted English version (fallback to Base).
- `PrefControlViewController`
- `PrefKeyBindingViewController`
- `PrefSubViewController`
-  `SubSelectWindowController`

**Comment by superzazu** [comment]
Forgive me if I'm mistaken, but it seems to me that there's no `read.` keys in [KeyBinding.strings on develop](https://github.com/lhc70000/iina/blob/develop/iina/Base.lproj/KeyBinding.strings) ?

**Comment by lhc70000** [comment]
@superzazu Sorry, my fault. Now updated.

**Comment by metacosm** [comment]
@superzazu are you working on the French translation?

**Comment by superzazu** [comment]
Yes I am, I think I'll have finished by tonight :-)

**Comment by lhc70000** [comment]
@superzazu @metacosm @cgand

Dear translators, could you take a look at new features on `develop` for next release?

**Comment by cgand** [comment]
Which files?

**Comment by lhc70000** [comment]
@cgand 

- `KeyBindings.strings`
- `MainMenu`
- `PrefGeneralViewController`
- `PrefUIViewController`
