### ISSUE TITLE
Resize the playlist

### ISSUE THREAD

**Issue by troyliu0105** [lhc70000/iina#299]
When file name is too long, it's hard to read in playlist...
adding resizing playlist's width feature may help... 😃

**Comment by inflation** [comment]
You can try to hover over the item, it will give you the full name.

**Comment by saagarjha** [comment]
This appears to be a duplicate of #253.

**Comment by troyliu0105** [comment]
@inflation hovering doesn't help... 😭 , nothing appears
my platform: 10.12.3
iina version: 0.0.4

**Comment by troyliu0105** [comment]
i see, those commits may be merged in next version... they havent be merged yet, so it still doesn't work now...
