### ISSUE TITLE
Download online subtitles automatically | 搜索在线字幕

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#3]
from V2EX @886106 @fo2w

**Comment by niklasberglund** [comment]
I just yesterday created a repo with Swift 3 hashing method for OpenSubtitles API. Might be of interest if IINA is going to use opensubtitles.org for automatic subtitles download. https://github.com/niklasberglund/OpenSubtitlesHash.swift

I believe shooter.cn's API is still running if you want better support for Chinese subtitles. Not sure whether opensubtitles.org have as many Chinese subtitles as Shooter.

**Comment by fo2w** [comment]
great work, many thanks

**Comment by zdenektopic** [comment]
👍

**Comment by CatTail** [comment]
Actually it's not so hard, with mpv's lua script, it's easy to download subtitle

```lua
-- default keybinding: b
-- add the following to your input.conf to change the default keybinding:
-- keyname script_binding auto_load_subs
local utils = require 'mp.utils'
function load_sub_fn()
    subl = "/usr/local/bin/subliminal" -- use 'which subliminal' to find the path 
    local path = mp.get_property("path")
    path = string.sub(path, 0, -2 - string.len(get_extension(path)))
    mp.msg.info("Searching subtitle")
    mp.osd_message("Searching subtitle")
    t = {}
    mp.msg.warn(path)
    t.args = {subl, "download", "-l", "zh", "--", path}
    res = utils.subprocess(t)
    if res.status == 0 then
        mp.commandv("rescan_external_files", "reselect") 
        mp.msg.info("Subtitle download succeeded")
        mp.osd_message("Subtitle download succeeded")
    else
        mp.msg.warn("Subtitle download failed")
        mp.osd_message("Subtitle download failed")
    end
end

function get_extension(path)
    return string.match(path, "%.([^%.]+)$" )
end
 
mp.add_key_binding("b", "auto_load_subs", load_sub_fn)
```

**Comment by lhc70000** [comment]
Searching for subtitles from `shooter.cn` is supported in 0.0.2.
This issue will be closed once `opensubtitles` or any other global subtitle site is supported.

@CatTail 
It's totally fine for a experienced mpv user to use such script. However I think some normal user don't know how to install `subliminal` or how to enable mpv's OSD.

**Comment by megadr01d** [comment]
Suggestion: SubtitleSeeker. It's a search engine that indexes [multiple sub websites](http://www.subtitleseeker.com/Subtitle-Stats). Their [API](http://api.subtitleseeker.com/) seems pretty simple but I'm not sure how to implement it in Swift.

**Comment by niklasberglund** [comment]
@megadr01d seems like it isn't possible to search by hash with SubtitleSeeker's API(http://api.subtitleseeker.com/About/Api-Search/). That's a big advantage of OpenSubtitles and Shooter.
