### ISSUE TITLE
0.0.4 crashes on launch

### ISSUE THREAD

**Issue by shila77** [lhc70000/iina#300]

**Comment by lowercaseman** [comment]
Can confirm. Running macOS 10.2.4 beta 1 (16E144f)
Can provide logs

**Comment by inflation** [comment]
@lowercaseman Any logs are appreciated.

**Comment by lowercaseman** [comment]
[iina.4.macOS12.2.4.beta.1.lowercaseguy.logs.txt](https://github.com/lhc70000/iina/files/740792/iina.4.macOS12.2.4.beta.1.lowercaseguy.logs.txt)

**Comment by inflation** [comment]
I believe this problem is caused because the `libvapoursynth.dylib` is not compiled to support the beta system. But I can't reproduce in my environment. Maybe we can exclude this library until we figure out what's going wrong? @lhc70000

**Comment by shila77** [comment]
I'm not using the beta. Crashes also on 12.2.4. No problem running 0.0.3.

**Comment by lhc70000** [comment]
I compiled a binary without `vapoursynth` and replaced current release with the fixed one.

Please download from release again and have a test.

([direct link](https://github.com/lhc70000/iina/releases/download/v0.0.4/IINA.v0.0.4.zip))

**Comment by megadr01d** [comment]
> I compiled a binary without vapoursynth and replaced current release with the fixed one.

0.0.4 also crashes on launch for me (without opening a movie), on OS X 10.11.6 El Capitan. Previous versions crashed when opening movies only. Will try the updated binary when I get home and report back.

**Comment by shila77** [comment]
0.0.4 build 7 working fine

**Comment by megadr01d** [comment]
@lhc70000 Great work! Not only 0.0.4b7 is launching correctly but also opens movies just fine without crashing for the first time, on my system. Somehow it fixed issue https://github.com/lhc70000/iina/issues/171 so closing that one.

**Comment by lhc70000** [comment]
Does the new binary work?

**Comment by megadr01d** [comment]
> Does the new binary work?

We said "yes"!

**Comment by lhc70000** [comment]
@megadr01d  lol nice
