### ISSUE TITLE
Auto update (and install)

### ISSUE THREAD

**Issue by Hanchor** [lhc70000/iina#302]
Could you please add the **automatic update** feature? or the **update check** feature which may let us upgrade IINA within the program? 

It would be a little inconvenient if I have to install the app every time I found there is a new release.

Thanks a lot!

**Comment by saagarjha** [comment]
If you use homebrew-cask, IINA is available there (which reminds me, @lhc70000, could you update the cask?)

**Comment by nlohmann** [comment]
I second this request - especially since IINA keeps reminding to update with every start.

**Comment by saagarjha** [comment]
@nlohmann I believe a fix for your issue was implemented in b468afe.

**Comment by rmaes4** [comment]
Please add automatic updates. It is very cumbersome to have to re download and manually install updates.
