### ISSUE TITLE
Invisible button in MainWindowController.xib

### ISSUE THREAD

**Issue by Miigon** [lhc70000/iina#306]
There is an invisible button in MainWindowController.xib
I don't know the position but there is one.

**Comment by saagarjha** [comment]
Yep, I saw it too. It didn't appear to be hooked up to anything either, so I removed it in my fork. @lhc70000 is there any reason it's there?

**Comment by lhc70000** [comment]
Seems that it was added (accidentally) by @DrabWeb in [8aabc22](https://github.com/lhc70000/iina/commit/8aabc227c9307c397ec3113c68ed8e4163896c6a).

I'll delete it.
