### ISSUE TITLE
Preferences cannot be effective when something be changed. | 偏好设置不能立即生效

### ISSUE THREAD

**Issue by freedani** [lhc70000/iina#309]
0.0.4 Build 7
When I changed the value of Preferenced->UI->播放控制->自动隐藏 to 2 s (default is 5 s), it doesn't be effective until I click other tab like 通用 or 解码。I wish change the effective time or create a new confirm button.

当我修改 偏好设置->UI->播放控制->自动隐藏的值时，直接点击关闭偏好设置的窗口，修改不能立即生效，直到我点击其他的页面如通用或解码，修改才能生效。希望能够更改生效时间或者增加一个确认按钮。

**Comment by lhc70000** [comment]
Please press enter or click other text field after editing to **commit** your changes.

It's a standard behavior in macOS.
