### ISSUE TITLE
Right click open one file actually open other file

### ISSUE THREAD

**Issue by qinyuhang** [lhc70000/iina#311]
**System and IINA version:**

- macOS 10.12.4 Beta (16E144f)
- IINA 0.0.4

**Expected hehavior:**

Open the file drag into the icon or right clicked file "open with IINA"

**Actual behavior:**

Open other file

**Steps to reproduce:**

In a folder stored lots of mkv, mp4, mp3, AAC file, right click open one mp3 file, it jump to other mp3 file. I have upload the 2 mp3 file here in a zip file. (In this case right click open `Nara - Nara - E.S. Posthumus.mp3` will actually open `Sound Of Silence.mp3`)

**How often does this happen?**

Every time

**My prediction**

I think it is maybe IINA cannot open the first file, then it jump directly to next file.
[归档.zip](https://github.com/lhc70000/iina/files/746745/default.zip)

**Comment by qinyuhang** [comment]
Further add:
The file skipped can be find in `File->recently opened`, but cannot find in the playlist

**Comment by lhc70000** [comment]
Please wait for 0.0.5 and test whether the problem is solved.

**Comment by qinyuhang** [comment]
Ok, thank U!
