### ISSUE TITLE
sha256 checksum errors

### ISSUE THREAD

**Issue by QYQSDTC** [lhc70000/iina#312]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**
<img width="997" alt="2017-02-02 11 14 52" src="https://cloud.githubusercontent.com/assets/15608306/22535956/5f43f55c-e939-11e6-9e1b-549724a42046.png">

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by HarukaMa** [comment]
@QYQSDTC This may due to the change of 0.0.4 binary and brew cask has not updated to reflect it.

**Comment by lhc70000** [comment]
https://github.com/caskroom/homebrew-cask/pull/29741

**Comment by lhc70000** [comment]
Fixed.
