### ISSUE TITLE
[Feature Request] QuickTime-like title bar behavior

### ISSUE THREAD

**Issue by tzhao11** [lhc70000/iina#315]
- Right click on filename:
<img width="410" alt="2017-02-02 18 19 14" src="https://cloud.githubusercontent.com/assets/6540380/22574394/334aefce-e974-11e6-8d2f-6e3d5e9017d9.png">

- Click on arrow:
<img width="600" alt="2017-02-02 18 18 58" src="https://cloud.githubusercontent.com/assets/6540380/22574398/3603272c-e974-11e6-933e-bf6999d34135.png">

- File icon can be dragged.

**Comment by alejx** [comment]
This feature may be related to #187 .

**Comment by lhc70000** [comment]
@alejx However we're using custom view for titlebar.

**Comment by saagarjha** [comment]
@lhc70000 If we need to use a custom view, we'll need to add a [`documentIconButton`](https://developer.apple.com/reference/appkit/nswindowbutton/1419136-documenticonbutton) and set [`representedURL`](https://developer.apple.com/reference/appkit/nswindow/1419066-representedurl) for the titlebar.

**Comment by alejx** [comment]
See #366 .
