### ISSUE TITLE
Add URL Bookmarks

### ISSUE THREAD

**Issue by lizhangqu** [lhc70000/iina#317]
Every time I want to open the url,I should copy and paste the URL. Could you add a feature like bookmarks?Then I can direct open the URL from bookmarks next time.

**Comment by lhc70000** [comment]
May be related to #286 #207

**Comment by LarsStegman** [comment]
:+1 I would also like to see this, as I listen to radio streams.

**Comment by LarsStegman** [comment]
Has this been implemented, if so with what pr ?
