### ISSUE TITLE
Preference issues

### ISSUE THREAD

**Issue by thmd** [lhc70000/iina#319]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**
1. Changing preference should apply as soon as possible.
2. Keybinding should apply without requiring restart of the player.
3. Meta+Up/Down cannot be configured. By default it increases volume and thats limited to max volume of 100 even if the max volume is set to higher. I tried adding custom keymap for Meta+Up it still is limited to 100.

4. In the template it says 'Expected hehavior' and not behavior.

**Actual behavior:**
1. If I'm correct preferences seems to be applied when preference window is closed or tab is switched. If I put the player window on top with the current preference tab open I think it should be applied even at that point. Basically as soon as the current tab is not in focus.

2. Right now it seems I need to restart the player to see keybinding change (or keybinding template change) to take affect. This makes experimenting with keybinding and figuring out if something is working much difficult.

3. I found all this when trying to use > 100 volume for a low-volume video. I actually didn't understand how this worked before in other player (couldn't make it work). I thought the volume slider still would go to 100 but the base volume would be amplified. Your @lhc70000 comment helped me understand that the volume goes 100+. Two problem remained, the default keymapping for my IINA installation (I didn't reconfigure it) was mvp so UP wasn't working for volume. I found Cmd/Meta+UP by experiment and it still was limited to 100. I then added custom keybinding and it still was limited to 100. I am now able to push volume over 100 by either using '0' on MPV keybinding or using UP in IINA default keybinding. I believe all the volume keyboard shortcut should allow 100+, the feature is better if its documented, not everyone would be an MPV expert and will know that there are multiple shortcuts for volume behaving differently and that the base volume is not amplified (which I guess allow for better sound quality when its not needed). 

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

Every time.

**Comment by lhc70000** [comment]
> Changing preference should apply as soon as possible.

It's a macOS default behavior that, the values in text fields does not take effect until you **commit** the change, either by pressing <kbd>Return</kbd> key or change focus to other input controls.

> Keybinding should apply without requiring restart of the player.

There does exist a _few_ options that requires a restart, including key bindings. I'm not sure whether mpv supports changing key bindings during runtime, so let me have a try first.

> Meta+Up/Down cannot be configured

It's because currently they are bound to menu actions and therefore take precedence over mpv key bindings. So please use <kbd>↑</kbd> <kbd>↓</kbd> now for changing volume and I'll consider removing this shortcut. Also refer to #114.

Starting from 0.0.2, "IINA Default" should be the default key binding. It may remain at "MPV Default" if you installed IINA before 0.0.2. Sorry for the inconvenience.

**Comment by thmd** [comment]
> It's a macOS default behavior that, the values in text fields does not take effect until you commit the change, either by pressing Return key or change focus to other input controls. 

When you move focus from preference to play window, shouldn't that commit the preference then? It doesn't seem like thats happening.

> There does exist a few options that requires a restart, including key bindings. I'm not sure whether mpv supports changing key bindings during runtime, so let me have a try first.

Thanks for looking it up. Of course if mpv can't do it will be difficult. A very bad one would be to detect changes in binding and if it has changed restart the player at the old position. But lets hope that mpv supports such a change.

> It's because currently they are bound to menu actions and therefore take precedence over mpv key bindings. So please use ↑ ↓ now for changing volume and I'll consider removing this shortcut. Also refer to #114.

I read the whole gesture not going over 100 by default for fear of accidental change. But why wouldn't the menu item go the configured highest volume? Its after all configurable and the change shows up in OSD so people won't miss it.

Btw. thanks a lot for such a fabulous project. I have been waiting for MPV based player for such a long time now. I am very used to instant seeking of smplayer (from my linux days) and MPV. The last position reminder and the high quality playback. Its been a huge problem after my switch to OSX. Its also very impressive how active you have been in development and address a lot of these smaller pain points that everyone have. Looking forward to this turning into an even more fabulous player.

**Comment by lhc70000** [comment]
> When you move focus from preference to play window, shouldn't that commit the preference then? It doesn't seem like thats happening.

It does happen. Here's a method to check whether it's committed: type some random characters in a numeric input field, and it will alert you the input is invalid on commit. Changing focus to other window does not work as the "local" focus in preference panel is not changed. 

I recommend pressing enter to commit changes.

> But why wouldn't the menu item go the configured highest volume?

It's just because... I forgot it. It'll be fixed in 0.0.5.

> Btw. thanks a lot for such a fabulous project.

Thanks for your support too. We are working together to make this project more awesome.

**Comment by thmd** [comment]
> It does happen. Here's a method to check whether it's committed: type some random characters in a numeric input field, and it will alert you the input is invalid on commit. Changing focus to other window does not work as the "local" focus in preference panel is not changed.

As a programmer its clear to me now why its behaving the way it is and moving forward I can use enter to apply my changes. But is this a well known behavior for most users or will most people expect the change to apply on window change (from preference to video). What do you think?
