### ISSUE TITLE
Main and secondary subtitle overlap | 主字幕和副字幕重叠

### ISSUE THREAD

**Issue by carterbao** [lhc70000/iina#32]
同时打开主字幕与副字幕（比如需要同时使用中英字幕），两个字幕会重叠，无法调整位置

**Comment by lhc70000** [comment]
有可能是 mpv 设置的问题，待我稍后研究。

**Comment by LeoNatan** [comment]
Perhaps the secondary subtitles option should be disabled for now? It has no reason to exist if both languages appear in the same spot.

**Comment by lhc70000** [comment]
It should be a mpv problem and you can open an issue for mpv with your subtitles attached. 

Close for now.
