### ISSUE TITLE
Crash when 'Open with...' menu

### ISSUE THREAD

**Issue by yoyokko** [lhc70000/iina#322]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.3 (4)

**Expected hehavior:**
Open the movie file without crashing

**Actual behavior:**
Crashed.

**Steps to reproduce:**
1. Right click movie file
2. Open with
3. Select IINA

**How often does this happen?**
Every first time after a wake up or restart.
[iina_crash.txt](https://github.com/lhc70000/iina/files/750873/iina_crash.txt)

**Comment by lhc70000** [comment]
It's a known bug.

(Although 0.0.4 didn't solve it, it's recommended to keep update with the latest version. Please download it from github release.)
