### ISSUE TITLE
[zh-tw Localization] change 啓 into 啟.

### ISSUE THREAD

**Issue by ShikiSuen** [lhc70000/iina#324]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4 Build 7

**Expected hehavior:**

The entire traditional Chinese localization is expected not to use those ideographs not common in contemporary written Traditional Chinese Mandarin. 啓 is more common in contemporary written Cantonese (in HK), while 啟 is more common in Taiwan (a mandarin-speaking region).

**Actual behavior:**

<img width="235" alt="2017-02-03 10 54 21" src="https://cloud.githubusercontent.com/assets/3164826/22602114/249f0f24-e9ff-11e6-9818-fcf47e317497.png">

**Steps to reproduce:**

(see screenshot above.)

**How often does this happen?**

Static.

**Comment by ShikiSuen** [comment]
N.B.: I know there is an exception that 啓 is used in official Red Alert 2 tradiitonal Chinese language pack. However, 啓 is still much less common than 啟 in Taiwan.

**Comment by lhc70000** [comment]
1. The current Traditional Chinese translation uses locale `zh-Hant` and doesn't specify detailed region. I just tested that QuickTime translated this into "打開" for `zh-Hant`, `zh-Hant-TW` and `zh-Hant-HK`, so perhaps using "打開" will be better?

2. Current TC localization was done by @LEOYoon-Tsaw, however seems that he is not keeping the translation updated recently. If you think there should be any improvement, **please feel free to make changes and open pull requests**. It'll be great if you could also add some missing translations for newly added features (see #291). 

If there's any other wording difference between regions, the ideal solution is to maintain two copies of translation, both `HK` and `TW`, but I'm afraid that it would bring too much workload. As I'm not a professional, maybe you can discuss with the original translator first.

**Comment by ShikiSuen** [comment]
@lhc70000 「開啟」is from Microsoft Traditional Chinese translation practice, FYI. For some reason I personally do not suggest respect everthing Apple did on their Traditional Chinese localization work, except those did literarily better than what Microsoft did.

**Comment by LEOYoon-Tsaw** [comment]
I didn't realised this variant problem when I did the translation, probably 「打開」 should be a more common choice here and avoid the problem. Thanks!
