### ISSUE TITLE
Swift Complier Warning from Xcode 8.3 beta

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#326]
**System and IINA version:**

- macOS 10.12.4 beta (16E144f)
- Xcode 8.3 beta (8W109m)
- IINA latest develop

**Expected hehavior:**

N/A

**Actual behavior:**

In code
```
Utility.log("Unknown aspect in menuChangeAspect(): \(sender.representedObject)")
```
in MainWindowMenuActions.swift, new Xcode gives a warning says that 
> String interpolation produces a debug description for an optional value; did you mean to make this explicit?

Possible solutions that Xcode generated to fix this warning:
```
Utility.log("Unknown aspect in menuChangeAspect(): \(String(describing: sender.representedObject))")
```
or
```
Utility.log("Unknown aspect in menuChangeAspect(): \(sender.representedObject ?? <#default value#>)")
```

**Steps to reproduce:**

Use beta Xcode.

**How often does this happen?**

N/A

**Comment by saagarjha** [comment]
#165. @lhc70000 please check to see if this was what you wanted.
