### ISSUE TITLE
order on play-list wrong

### ISSUE THREAD

**Issue by Chen-Hu** [lhc70000/iina#327]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**
after the video file "09_xxxxx" should be "10_xxxxx"

**Actual behavior:**
after the video file "09_xxxxx" is  "100_xxxx" and after is "10_xxxxx"
<img width="240" alt="2017-02-03 09 15 14" src="https://cloud.githubusercontent.com/assets/6964498/22614981/161c1330-eac6-11e6-937d-cdc279e347ad.png">

**How often does this happen?**
Every time.
When you got 100 video to play-list.

**Comment by BubuYo** [comment]
![image](https://cloud.githubusercontent.com/assets/18184162/25078815/36ffd01a-2369-11e7-9f67-5d8797d8bc3f.png)
same as you

**Comment by saagarjha** [comment]
IINA uses string comparison for its sorting order. Add leading zeros to your numbers to to get the behavior your want.

**Comment by KizzyCode** [comment]
> Add leading zeros to your numbers to to get the behavior your want.

But this is only a workaround, isn't it?
Other macOS-software like Finder, iTunes etc. sorts and names the files "naturally" (without leading zeroes) and I think IINA should use the macOS-standard-behaviour.

**Comment by saagarjha** [comment]
Ahh, I didn't realize Finder did this. I'm guessing it's extracting numbers from the filenames and using that to sort; we'll look into adding this to IINA.

**Comment by gengjiawen** [comment]
This is called natural sort. I am not familiar with swift. But I find this http://stackoverflow.com/a/31210070/1713757. Hope it helps.

**Comment by lhc70000** [comment]
Now we just use the <code>[autoload.lua](https://github.com/lhc70000/iina/blob/develop/iina/scripts/autoload.lua)</code> script provided by mpv which is causing multiple issues including this one. It's definitely going to be replaced by our implementation.

I'm a little bit busy these days, but will work on playback history and this issue once have time, hopefully before next release.

**Comment by lhc70000** [comment]
Fixed in 0.0.10.
