### ISSUE TITLE
"Error setting extra mpv option" at start. the error code is "-5"

### ISSUE THREAD

**Issue by vincentzlt** [lhc70000/iina#329]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**

no alert at beginning

**Actual behavior:**

error message:
无法设置选项 --= （返回值 -5）。 请在「设置>高级」中检查你的额外 mpv 选项。

**Steps to reproduce:**

every time when iina starts.

**How often does this happen?**

every time

**Comment by lhc70000** [comment]
@vincentzlt There is an empty row in your extra option settings. Please delete it.

**Comment by vincentzlt** [comment]
Thanks!

It is solved.

**Comment by alejx** [comment]
Maybe we can check the syntax of the extra settings.

**Comment by kingjane** [comment]
I get the similar problem.
each time i open iina,an error message: "alert.extra_option.error" appears.
could you help me?

**Comment by lhc70000** [comment]
@kingjane 

Sorry for late reply. It seems to be a localization issue. Which language are you using?

BTW this indicates that you have some invalid mpv options in Preference > Advanced.

**Comment by kingjane** [comment]
@lhc70000 
I use chinese. This is my configuration.
Actually, i don't  know how to config mpv.Maybe i did some mistaken operation before.
![2017-04-27 5 43 58](https://cloud.githubusercontent.com/assets/7594252/25477726/20f7c326-2b71-11e7-8251-30bf305878b2.png)

**Comment by kingjane** [comment]
Thanks, it's solved.
There is an empty row that i didn't notice .
