### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by darlanmendonca** [lhc70000/iina#33]
what you think to do a contributing file?

is an amazing project, can be helpful

**Comment by lhc70000** [comment]
Thanks for suggestion! Definitely I'm going to draft one once I have time.

**Comment by darlanmendonca** [comment]
can be helpful, one thing that I suppose be important, language

I see many issues in chinese, and is very hard to me :D, I'm brazlian, we speak portuguese

Maybe be more easy around you sure, use the local language, but can be a bad choice to globally contributes, and your project is awesome!!

**Comment by darlanmendonca** [comment]
type the targets of your project, if you can, we can help to do a contributing guideline

**Comment by lhc70000** [comment]
Thanks a lot. I've noticed the language problem and now I've changed most of their names. Are they seem OK for you now?

Let me draft a simple CONTRIBUTING file now before going to sleep. Too tired today...

**Comment by darlanmendonca** [comment]
:D sure, when you can

about the renaming, looks good, but I believe in contributing  files being more important in priority, to turn more scalable/easy to future, legacy always be a problem, still more according to the size

**Comment by lhc70000** [comment]
I've added a contributing file. Do you have any suggestions?

**Comment by darlanmendonca** [comment]
cool!!

maybe add the language, e.g.

```
## Issues

- When raising a issue, please use English
```

**Comment by darlanmendonca** [comment]
fix the double 'or or' on line 7, 'stupid logic or or design'

**Comment by darlanmendonca** [comment]
looks good, all

more things, just with the time I guess
you probaly will found things that difficult the productivity or comunication, so contributing file is useful to help communicate patterns between contributors
