### ISSUE TITLE
Don't reset speed and menu bar position with pause video

### ISSUE THREAD

**Issue by androidcn** [lhc70000/iina#332]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment]
Seems that we need a option for this: some other users want always resetting speed to normal, see #214.

**Comment by enagorny** [comment]
I think #214 is slightly different. 
But here is another when user change playback speed (either by hotkey or by changing it in config sidebar) and then press pause speed is reset to 1x. And config sidebar still shows that speed is changed. 
Also It doesn't change value when I change speed from keyboard and sidebar config visible

<img width="1329" alt="the girl on the train 2016 bdrip 1080p exkinoray mkv 2017-02-10 18-57-08" src="https://cloud.githubusercontent.com/assets/1202150/22835847/d1586cc4-efc2-11e6-8db5-a71befdf999f.png">

**Comment by lhc70000** [comment]
from #403
> but now that I think about it I believe that this is a bug. @lhc70000 the speed should only be reset when fast-forwarding; when the user manually sets the speed using Settings panel it should stick even after pausing.
