### ISSUE TITLE
Don't show OSC and title bar on Cmd+Tab

### ISSUE THREAD

**Issue by pickx** [lhc70000/iina#333]
When IINA Is not focused and receives focus by Cmd+Tab, the OSC and title bar are shown, this is different from Quicktime's behavior (and it is also slightly annoying).

EDIT: I changed from feature request to bug report and explained it better.

**Comment by lhc70000** [comment]
Seems that I cannot reproduce this... Could you provide some detailed information?

**Please use the issue template next time.**

**Comment by okla** [comment]
Looks like it shows OSC and title bar only when the mouse pointer is inside of player's window.
