### ISSUE TITLE
Window size/position options

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#334]
- Fixed window size (at least window width) during runtime
- Set initial window size / position
- Save and restore window size / position

Please suggest more.

**Comment by TofPlay** [comment]
> Fixed window size (at least window width) during runtime
Yes pleaseeee! When I watch some episodes for each episode I have to resize and change the position 😕

Suggestion: We have juste one playlist. But in fact we watch not one series but some. Each series can have season and each season some episode. It's will be good if we can create multiple playlist and subplayist. For each playlist we can associate a cover, a description, etc... Or even better IINA extracts this information directly from the mp4. 😉

**Comment by pryley** [comment]
- Option to keep the video window within the screen bounds when resizing instead of expanding outside of it.

**Comment by mo4ya2000** [comment]
Can I add to this.  I was trying to find an MPV that would force iina to stay open a set x and y coordinate.  Example, i write on my left side of my screen so I need to see the many videos at the right x=1000 y=300 (as example) but unfortunately every time I open a video it opens to the center and I am forced to move it.  Thanks

**Comment by mo4ya2000** [comment]
Can I add to this. I was trying to find an MPV that would force iina to stay open a set x and y coordinate. Example, i write on my left side of my screen so I need to see the many videos at the right x=1000 y=300 (as example) but unfortunately every time I open a video it opens to the center and I am forced to move it. Thanks

**Comment by lhc70000** [comment]
@mo4ya2000 Please check mpv's geometry option (https://mpv.io/manual/stable/#options-geometry). IINA fully supports it.

**Comment by Kadigan** [comment]
I completely support a "Remember player size and position" option.

There is an option that is worded as such "Resize to video size only when opening files manually" -- this option is clearly missing a parent "Resize window to video size". I dislike it when my player resizes the window between videos, even if I load them manually. Please add black bars if need be, and allow me to resize manually if I want to. VLC does this splendidly by showing bars when necessary (when switching between different AR sources) and immediately snapping to video AR upon resize.
