### ISSUE TITLE
Support youtube-dl && you-get.

### ISSUE THREAD

**Issue by foisonocean** [lhc70000/iina#335]
Can I use youtube-dl or you-get to play some online videos ?

**Comment by lhc70000** [comment]
`youtube-dl` support has been added on `develop` branch, and will be available in next release.

**Comment by foisonocean** [comment]
@lhc70000 Any plans for [`you-get`](https://github.com/soimort/you-get) ?

**Comment by lhc70000** [comment]
No as it's not supported by mpv. Is there any reason of using `you-get` instead of `youtube-dl`?

**Comment by foisonocean** [comment]
@lhc70000 
`you-get` has better support for some Chinese sites.
And you can use `you-get -p mpv URL` to use `you-get` in `mpv`.

**Comment by lhc70000** [comment]
`you-get -p mpv URL` doesn't mean mpv "support" you-get... Please check #58 for this.

Anyway, there's too much work if we want to support `you-get`.

If you really need integrated support instead of #58, please reopen the issue.
