### ISSUE TITLE
Pausing by SPACE key works only after pausing by P key.

### ISSUE THREAD

**Issue by okla** [lhc70000/iina#337]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**

Pressing SPACE key pauses/releases video all the time

**Actual behavior:**

Pressing SPACE key pauses/releases video only after using P key

**Steps to reproduce:**

Run IINA, open any video, press SPACE (pausing doesn't work), press P (pausing works), press SPACE (pausing works)

**How often does this happen?**

Always

**Comment by lhc70000** [comment]
Duplicate with #35, etc.

**Comment by lhc70000** [comment]
Should be fixed in 0.0.5.
