### ISSUE TITLE
Crash when multiply playback speed hotkey is pressed

### ISSUE THREAD

**Issue by xiaoken** [lhc70000/iina#338]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.4

**Expected behavior:**

speed up to 1.1x

**Actual behavior:**
Fatal Error: MPV API error: "error when running command", return value: -12.
The application will exit now.

**Steps to reproduce:**
open a video and press the "]" key.
**How often does this happen?**
Always

**Comment by lhc70000** [comment]
Can't reproduce.

Please double check your key binding configuration (should be exactly `multiply speed 1.1`) and try duplicating default ones again.

If the problem persists, please provide:

- mpv log (enabled in "Advanced")
- your input configuration file ("Reveal config file in Finder" in "Key bindings")

**Comment by xiaoken** [comment]
Having Problem reproducing now :( weird

**Comment by xiaoken** [comment]
Tested it on latest build,
Not crashing anymore.

**Comment by xiaoken** [comment]
i saw in the release notes that this was fixed in 0.0.5
"Stop terminating app on MPV command error (like wrong key binding)"
Because i use a JIS keyboard, the keyboard mapping isn't registered correctly and therefore crashing it.
