### ISSUE TITLE
The player won't start playing every time I fresh start the system

### ISSUE THREAD

**Issue by tony1016** [lhc70000/iina#339]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Expected hehavior:**
Login in to the system, then click a media file,then start from the position it stops.

**Actual behavior:**

Login in to the system, then click a media file.IINA start but not playing.Quit and click again,IINA start playing but lost the position it should start.

**Steps to reproduce:**

Just play some files.Quit and Shutdown the system.Login again, click the media file,then like what I said.

**How often does this happen?**

Every time.

**Comment by lhc70000** [comment]
It's a confirmed bug, I'm trying to fix in next release. 

If convenient, I'd like you to test whether it still happen on current `develop` branch. If you're not willing to build by yourself, I can provide a compiled binary.

**Comment by lhc70000** [comment]
Could you try this version and test whether there's any improvement?

[https://drive.google.com/open?id=0B7tEU25gz8nhTGFwNGxNZUJlemc](https://drive.google.com/open?id=0B7tEU25gz8nhTGFwNGxNZUJlemc)

**Comment by tony1016** [comment]
Interesting.After I open the new one,I can't reproduce the scene even with the old one.💔

**Comment by lhc70000** [comment]
You mean it's been fixed or not?

**Comment by tony1016** [comment]
I mean,yeah,it's fixed.But Strange,I can't reproduce the bug  with olde version after use the new version once.

**Comment by mickaphd** [comment]
I have also this problem from the beginning and not fixed in the 0.0.5

**Comment by lhc70000** [comment]
Closed as fixed in 0.0.6
