### ISSUE TITLE
Improve buffer mechanism when play from URL

### ISSUE THREAD

**Issue by alfredcc** [lhc70000/iina#340]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**
Improve buffer mechanism when play from URL.

**Actual behavior:**
not very smoothly when play from URL, always stop loading when play for a while.

**Comment by lhc70000** [comment]
IINA uses mpv for playback and doesn't handle this directly. Perhaps you need some better configuration in network settings, like bigger buffer size.

**Comment by alfredcc** [comment]
I check the [config](https://github.com/mpv-player/mpv/blob/f1436658647aceb7ea58e595439fa6dd5c2cdb97/etc/mpv.conf) in mpv，find out and tested this would be better.
``` swift
    Key.defaultCacheSize: 153600,
    Key.cacheBufferSize: 153600,
    Key.secPrefech: 50,
```
```
# cache settings
#
# Use 150MB input cache by default. The cache is enabled for network streams only.
#cache-default=153600
#
# Use 150MB input cache for everything, even local files.
#cache=153600
#
# Disable the behavior that the player will pause if the cache goes below a
# certain fill size.
#cache-pause=no
#
# Read ahead about 5 seconds of audio and video packets.
#demuxer-readahead-secs=5.0
#
# Raise readahead from demuxer-readahead-secs to this value if a cache is active.
#cache-secs=50.0
```
