### ISSUE TITLE
Wrong rotation for some video in portrait

### ISSUE THREAD

**Issue by androidcn** [lhc70000/iina#342]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4
一些手机拍摄的视频不能自动旋转且手动旋转后有巨大的黑边

**Comment by androidcn** [comment]
![](https://ooo.0o0.ooo/2017/02/07/5899c002dd45a.png)
270 rotation
![](https://ooo.0o0.ooo/2017/02/07/5899c017bee12.png)

**Comment by lhc70000** [comment]
fixed in develop branch.
