### ISSUE TITLE
Crash when open some .mkv files

### ISSUE THREAD

**Issue by SayoMelu** [lhc70000/iina#344]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Expected hehavior:**

Open and play the video

**Actual behavior:**

Crash

**Steps to reproduce:**

Download one .mkv file from [[CASO&amp;SumiSora][Puella_Magi_Madoka_Magica][BDRIP][GB_BIG5].torrent.zip](https://github.com/lhc70000/iina/files/758286/CASO.amp.SumiSora.Puella_Magi_Madoka_Magica.BDRIP.GB_BIG5.torrent.zip)
Then open it.

**How often does this happen?**

Every times.

**Comment by lhc70000** [comment]
It may be a general bug and not related to some files.

If it just quit without any alert, please try this version:

Google Drive: https://drive.google.com/open?id=0B7tEU25gz8nhTGFwNGxNZUJlemc
Baidu: 链接: https://pan.baidu.com/s/1i4U3Ttz 密码: s24j

Otherwise, please upload the crash report generate by system.

**Comment by SayoMelu** [comment]
Actually the app did not crash, it couldn't open this file.
(The "Bilibili" Mac client could open it)

I tried the "Build 8", but it didn't work either!
You can download one of these files and find out where the issue is.

And I don't know how to get the crash report ...

**Comment by lhc70000** [comment]
So it showed an alert "Cannot open file or stream"?

Or it showed nothing and quit suddenly?

**Comment by SayoMelu** [comment]
It showed nothing and quit suddenly.

**Comment by lhc70000** [comment]
Then it should not be a file problem.

If this happens EVERY TIME and you can reproduce it, please enable logging in Preference -> Advanced, and upload the mpv log.

**Comment by SayoMelu** [comment]
However, there's no log file in that folder...

**Comment by SayoMelu** [comment]
Well...I enabled the Advanced settings, then the file could open, and play...

I think this may be a bug.

**Comment by HarukaMa** [comment]
@SayoMelu Please refrain from posting copyrighted materials or any links / torrents point to copyrighted materials.

Well, you know, sometimes you just give a name and we may be able to find it...

**Comment by SayoMelu** [comment]
Ok...
But you may not get the "real" problem file.

**Comment by inflation** [comment]
@SayoMelu You can always provide SHA1 hash of the file.

**Comment by jsfaint** [comment]
I meet this issue too
When open some video file, the player window just disappear immediately.

**Comment by lhc70000** [comment]
@jsfaint It's a known bug (#339).

**Comment by jsfaint** [comment]
@lhc70000 got it, thanks

**Comment by lowercaseman** [comment]
macOS 10.12.4 Beta (16E154a), iina 0.0.4 build 8 from Google Drive does not crash on open for me anymore.

**Comment by lhc70000** [comment]
This should have been fixed in 0.0.6. Please reopen if it persists.
