### ISSUE TITLE
adjust the time period by pressing the left/right arrow key

### ISSUE THREAD

**Issue by maekks** [lhc70000/iina#345]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Expected behavior:**
The default time period for pressing the left/right arrow key to forward/backward is 10 seconds, is there any ways for us to adjust this value?

**Comment by beretboat** [comment]
You could change that in Preference:
<img width="592" alt="screen shot 2017-02-08 at 11 36 03 am" src="https://cloud.githubusercontent.com/assets/4593681/22722533/b6491a0e-edf2-11e6-8c55-ed4b56b81080.png">

**Comment by maekks** [comment]
@beretboat Thanks man!
