### ISSUE TITLE
[Feature request] Add Picture in Picture icon on OSC.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#352]
**System and IINA version:**

- macOS 10.12.4 beta
- IINA Latest develop branch build 9

**Expected behavior:**

![Picture in Picture icon on apple official website](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/mac_apps/itunes/macos-itunes12-5-video-playback-controls.jpg)
This is the default look of Picture in Picture icon in iTunes.

**Actual behavior:**

No icons currently.

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by fabi94music** [comment]
#350 Would be great if the dark corners issue could be fixed as well

**Comment by VSG24** [comment]
I like to have a button in Touch Bar for toggling PiP

**Comment by alejx** [comment]
Closed since it's already fixed.

@VSG24 You can file a new issue about that.

**Comment by sweenish** [comment]
Is this fixed in the beta? I'm on the latest current stable release and still don't see PiP icons on the player window or Touch Bar.

**Comment by lhc70000** [comment]
@sweenish Yes, please enable beta updates or wait for the 1.0 release.
