### ISSUE TITLE
PIP.framework is not available in older systems

### ISSUE THREAD

**Issue by inflation** [lhc70000/iina#354]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.4 Build 9

**Expected behavior:**

Open normally.

**Actual behavior:**

Crash when starting.

**Steps to reproduce:**

Just run it.

**How often does this happen?**

Every time.

```
Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/PIP.framework/Versions/A/PIP
  Referenced from: /Applications/IINA.app/Contents/MacOS/IINA
  Reason: image not found
```

Logging shows that we need to figure out a way to dynamically link with PIP framework or having different targets.
Maybe invite @saagarjha to comment?

**Comment by saagarjha** [comment]
Ahh, it looks like I lost a commit in one of the rebases. I'll get a fix ready ASAP.

**Comment by saagarjha** [comment]
@inflation Please try running [my fork](https://github.com/saagarjha/iina/tree/develop) to see if there are any issues. If not, I'll author a pull request.

**Comment by lhc70000** [comment]
@saagarjha tested, seems that you forgot a line in `updateVideoMenu()`.

**Comment by saagarjha** [comment]
Got it. Would you mind checking again?

**Comment by lhc70000** [comment]
@saagarjha LGTM, please open a PR.
