### ISSUE TITLE
Please think about adding the airplay feature support

### ISSUE THREAD

**Issue by lvhailong** [lhc70000/iina#356]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**
Please think about adding the airplay feature support. Then we can play any video on Mac and stream them to other devices in the same LAN.

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by HarukaMa** [comment]
@lvhailong Please search for duplicate issues before opening a new issue.

**Comment by lvhailong** [comment]
@HarukaMa Yes, I have searched the keyword "airplay" in this repository and just found this:
We couldn’t find any code matching 'airplay'

**Comment by inflation** [comment]
@lvhailong Search for issues, folk.

**Comment by saagarjha** [comment]
Duplicate of #63.

**Comment by alejx** [comment]
Close due to duplication.
