### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by Shadester** [lhc70000/iina#358]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**
Press command f for full screen

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by HarukaMa** [comment]
@Shadester There is already Control-Command-F for full screen. Any reason for a change?

**Comment by lhc70000** [comment]
Ctrl+Cmd+F is the standard shortcut for full screen and we're not going to change it.

However, you are free to add a key binding for Cmd+F:

![e8af6ead-43b0-48ad-89c0-95ac44e15a1c](https://cloud.githubusercontent.com/assets/8478049/22852185/93a175f6-f071-11e6-874c-0716c2c82d9e.png)

**Comment by oskerlau** [comment]
I'm pleased that there's a full-screen shortcut, took me a while to find out, I'm glad I searched the GitHub. Possible to add the shortcut hint (Ctrl + Cmd + F) in the menu Window > Enter Full Screen on the menu bar? That would help many others I guess.
