### ISSUE TITLE
Can't get the playlist of the BD package

### ISSUE THREAD

**Issue by tuihongshiyu** [lhc70000/iina#359]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**

When i open a BD package,i can get the playlist and choose a video from it.

**Actual behavior:**
![qq20170211-194648 2x](https://cloud.githubusercontent.com/assets/14249394/22853507/10ba68ce-f093-11e6-85a1-8ad823381b81.jpg)
After opening the BD package,there was not a playlist but only one video.I can't watch all the other videos.
![qq20170211-195054 2x](https://cloud.githubusercontent.com/assets/14249394/22853522/6e90f788-f093-11e6-83a5-92de08b1392a.jpg)

**Steps to reproduce:**

Just open a BD file.(I could open this file on my mac with other bd player properly.)

**How often does this happen?**

Everytime

**Comment by HarukaMa** [comment]
@tuihongshiyu Are there any entries in "chapter" section?

**Comment by tuihongshiyu** [comment]
@HarukaMa Yes.
![chapter](https://cloud.githubusercontent.com/assets/14249394/22853792/0fd06ace-f09a-11e6-93bf-27462e6ae1c5.jpg)
It's correct for this video.

**Comment by HarukaMa** [comment]
So... there should be more than one m2ts to be played, and the player only plays one?

**Comment by tuihongshiyu** [comment]
@HarukaMa That's right. I also tried opening  one m2ts of them directly and there was something wrong with the image.(only 2~3 seconds though)

**Comment by HarukaMa** [comment]
Some m2ts doesn't contain actual a/v data so we often find the largest files and play them. You may have opened some other files such as pgs subtitles directly...

However it seems that if you directly plays BDMV folder, player will only get the main video sequence. In my case the player indeed only played one video; other specials are not automatically included.

I think libbluray didn't get other videos as they are usually selected by user through bluray menus, but there are no menu support now. Meanwhile I think the only way is to play those m2ts directly...

**Comment by tuihongshiyu** [comment]
Thanks for your help.
