### ISSUE TITLE
Icon for file types | 文件图标

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#36]
If set IINA as default application of some file types (although it's not recommend for current version), corresponding file icons are needed.

**Comment by saagarjha** [comment]
We may also need to bundle a QuickLook generator, since this would disassociate the file with QuickTime's plugin.

**Comment by lhc70000** [comment]
@saagarjha  Yes, see #146

**Comment by mat-u** [comment]
Is it possible to have the source of the IINA icon? Can you add it in the project please?

**Comment by lhc70000** [comment]
@mat-u Isn't it available at [https://github.com/lhc70000/iina/tree/master/iina/Assets.xcassets/AppIcon.appiconset](https://github.com/lhc70000/iina/tree/master/iina/Assets.xcassets/AppIcon.appiconset)?

**Comment by mat-u** [comment]
@lhc70000 It's the bitmap files here (.PNG, flattened). I meant the .PSD or .AI, .SVG (vector document) etc. with all layers, to draw a better icon file types and be more clean. Like mpv SVG's icon provided in their repository.

**Comment by lhc70000** [comment]
@mat-u 

The App icon (only) is not designed by me. I don't think IINA's icon can be represented by SVG, and it seems not to be a good practice to include psd in git repository though... But it's possible to provide the psd at somewhere else.

May I ask why you need the App icon? If you want to design file icon for IINA or start a PR, we may have a discuss in advance.

**Comment by mat-u** [comment]
Ok my bad, after research, I saw icon file types can be generated automatically? Is that right?
I initially thought the issue was for an icon designer.

**Comment by saagarjha** [comment]
@mat-u You mean QuickLook, right? Yes, that's generated using code.

**Comment by megadr01d** [comment]
There's an utility (GUI + CLI) called docerator which can automatically create file type icons, based on the current IINA app icon (or any other icon).

[project](https://code.google.com/archive/p/docerator/)
[downloads + icon examples](https://code.google.com/archive/p/docerator/downloads)
[gui source](https://github.com/sveinbjornt/docerator)

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

Please open new issue for improvement / icon related suggestions.

To get file icons displayed in Finder, you need:

- Set IINA as the default App for this file type
- Perhaps need to run `killall Finder` in terminal, or a system restart
