### ISSUE TITLE
"Show remaining time" option of OSC doesn't persist past restart

### ISSUE THREAD

**Issue by wzxu** [lhc70000/iina#363]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Expected behavior:**

IINA should remember and respect the option

**Actual behavior:**

IINA forgets the user setting after restart

**Steps to reproduce:**

1. Toggle on "Show remaining time"
2. Restart IINA
3. Observe that the total time is showing again despite that "Show remaining time" is still active

**How often does this happen?**

Always

**Comment by lhc70000** [comment]
Confirmed as a bug, and just fixed. Thanks!
