### ISSUE TITLE
Default volume to 100% and/or provide an option

### ISSUE THREAD

**Issue by wzxu** [lhc70000/iina#365]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Expected behavior:**

I'm aware of using advanced mpv option to set default volume.
However, I'm not sure why the default is set to 60%.
For the general users I think it's only logical that new videos start playing with volume at 100%.
At the very least, there should be an easy option. Still I think default to 100% makes more sense.

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment]
Now the initial volume is the last volume you set, i.e. it will keep saving volume when changed.

Setting default volume to 100% is too loud for me (and is a design flaw), personally; but there will be an option in the future.
