### ISSUE TITLE
Touch Bar support enhancement

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#37]
IINA has basic Touch Bar support (can be customized by `Window->Customize Touch Bar`.

Maybe we can add more functionality. 

- Display remaining time
- Refine the slider (maybe like QuickTime)

Please suggest more.

**Comment by ddqp** [comment]
希望有touch bar support

**Comment by lhc70000** [comment]
@ddqp 现在已经有基本的支持了（而且可以在`窗口->自定义Touch Bar`中自定义）

**Comment by ddqp** [comment]
哦，好的，晚上回去看看

**Comment by rx2130** [comment]
I saw the latest release (v0.0.10) supports showing remaining time in Touch Bar. Yet it's still displays current time by default. And there's seems no option to customize the time label in the settings. So how could  we show the remaining time?

**Comment by lhc70000** [comment]
It's synced with the setting for on screen controller (Preference > UI > On Screen Controller).

**Comment by rx2130** [comment]
Thanks! I think it would be nice for Touch Bar to have current time label on the left side of the progress bar and the remaining time label on the right (I don't see how to accomplish in the current Touch Bar settings), such as the QuickTime Player. This kind of user experience is more consistent with Safari fullscreen Touch Bar's display.

**Comment by lhc70000** [comment]
@rx2130 You can open a new issue about this.

**Comment by rx2130** [comment]
Done. #707
