### ISSUE TITLE
Add speed option in menu | 菜单中加入速度调整选项

### ISSUE THREAD

**Issue by banli17** [lhc70000/iina#371]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment]
You can adjust speed in quick settings panel:
![c6d4422e-4a17-4a31-a761-4681c5fa75f5](https://cloud.githubusercontent.com/assets/8478049/22897623/5935050a-f25f-11e6-9e2c-e4848cf4ec2d.png)
