### ISSUE TITLE
Show (V-A-S/P-C) panels toggle it instead of switch from one to other

### ISSUE THREAD

**Issue by cgand** [lhc70000/iina#372]
**System and IINA version:**
- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**
Cmd+A -> Show audio pannel
Cmd+V -> Show/switch to video panel

**Actual behavior:**
Cmd+A -> Show audio pannel
Cmd+V -> Hide audio panel (Instead of switch to video panel)

**Steps to reproduce:**
Press Cmd+A and then press Cmd+V

Same with all other panels Cmd+S or between Cmd+P /Cmd+C for playlist and chapter panel

**How often does this happen?**
Ever

**Comment by alejx** [comment]
Duplicated with #362

**Comment by alejx** [comment]
Close due to the duplication.
