### ISSUE TITLE
Resume playback progress option won't work

### ISSUE THREAD

**Issue by goodman-capu** [lhc70000/iina#373]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**

N/A

**Actual behavior:**

No matter whether I checked this option, the player will resume playback progress

**Steps to reproduce:**

Don't know exactly. I just unchecked the "Resume playback progress" option

**How often does this happen?**

Every time

**Comment by lhc70000** [comment]
@goodman-capu It has been fixed in 0.0.5, which will be released several minutes later.
