### ISSUE TITLE
Problem with Retina screen/iMac 5K?

### ISSUE THREAD

**Issue by JBey4you** [lhc70000/iina#378]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected hehavior:**

VLC open the video with a player 2x times larger than IINA on my 5K iMac.

**Actual behavior:**

Video player in IINA seems "small" on Retina screen. When I double the size of the IINA's player, I get the normal size offered by VLC.

**Steps to reproduce:**

Open any video (resolution doesn't matter) with IINA and VLC side-by-side.

**How often does this happen?**

Everytime

![capture d ecran 2017-02-14 a 03 13 13](https://cloud.githubusercontent.com/assets/7979756/22912181/fe62ceb4-f263-11e6-9bfc-9d910e11fc6f.jpg)
IINA on the left with the default size vs VLC on the right with the default size (here, video is 1280x720p)

![capture d ecran 2017-02-14 a 03 13 42](https://cloud.githubusercontent.com/assets/7979756/22912206/1bcc0196-f264-11e6-8f04-c149ef2be654.jpg)
IINA with the double size (with ⌘+2) on top of VLC with the default size.

Maybe because IINA is not really optimized for Retina screens or the iMac 5K's resolution (5120 x 2880), I don't know. IINA seems really good, hope I will use it as my default player later!

**Comment by lhc70000** [comment]
It's the intended and default behavior.

Please uncheck this option to use logical resolution:

![685f0f22-514e-440a-8974-ce5118ea5846](https://cloud.githubusercontent.com/assets/8478049/22914847/fc78ab38-f2ad-11e6-8f39-1f8fe5fb0174.png)

**Comment by tzhao11** [comment]
I think the wording of this option could be improved. Physical/logical resolution is too technical for average users. Any suggestions?

**Comment by megadr01d** [comment]
@tzhao11 "Physical" and "logical" (HD) are actually the correct/known terms for pixel resolution. The same way you have "physical memory", "virtual memory" or "logic board". Let's better ourselves and stop being such average users, huh?

**Comment by owenzhao** [comment]
I wonder if there is some benefits of this option. For example, it could use point to point for 4k video or some other things.

If there is no benefit, maybe remove this option and make the **UNCHECKED state** as default is a good idea.

**Comment by saagarjha** [comment]
FWIW, QuickTime does that same thing as VLC. I'd think that leaving the option but defaulting it to unchecked is probably the best solution.

**Comment by owenzhao** [comment]
@saagarjha In fact, all other video players did the same thing. And all of them don't have this option. That's why I suggest to remove this option as it seems not very helpful.

**Comment by deseven** [comment]
Actually IINA is the only player which does it right for retina displays.  
All videos should be played in their original resolution, only that way you can play 4k videos on 4k display without rescaling the whole picture.  
In order to act like "all other video players" you can turn this option off by default, but please just don't remove it.
