### ISSUE TITLE
Mode option for url handling

### ISSUE THREAD

**Issue by matthewdias** [lhc70000/iina#379]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.5

**Expected behavior:**

Would be nice to have url params for the url handler for modes to open the video in. For example `iina://weblink?url={url}&mode={fullscreen|pip|windowed}`

**Comment by lhc70000** [comment]
Yes, definitely the url scheme is going to be improved.

**Comment by matthewdias** [comment]
might also want to support youtube-dl via the url scheme

**Comment by lhc70000** [comment]
If you enabled youtube-dl it will work for all urls regardless of how you open them.

**Comment by matthewdias** [comment]
hmm, it doesn't seem to work for me with youtube-dl. i'll do some investigating.

**Comment by matthewdias** [comment]
working now, guess i did something wrong.
