### ISSUE TITLE
UI is not clickable when playback starts in fullscreen mode and update notification is displayed

### ISSUE THREAD

**Issue by phill84** [lhc70000/iina#382]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**
Playback starts in the background
Update notification can be clicked away

**Actual behavior:**
Playback doesn't start automatically
After switching to another desktop and back, playback starts but progressbar doesn't move
Nothing is clickable in the UI, including menu, buttons in notification window and playback control
The only way is to force kill the app

**Steps to reproduce:**
When there is a new version available
1. open a video in windowed mode
2. click away the update notification
3. switch to fullscreen mode and quit
4. open the same video again, which will start in fullscreen mode automatically

**How often does this happen?**
Every time

**Comment by lhc70000** [comment]
Solved in 0.0.11.
