### ISSUE TITLE
IINA will flash back problem.

### ISSUE THREAD

**Issue by zhuziyi1989** [lhc70000/iina#384]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**

When I double-click the mp4 format video, Hopes to be able to start playing video.

**Actual behavior:**

Directly IINA will flash, then disappeared.

**How often does this happen?**

There has been.

**Comment by lhc70000** [comment]
It should be the same problem with #339, #322, #311, and 0.0.4 also have this bug. It's not related to particular files or file types, just IINA itself.

**Please quit IINA completely and try open again when encountered this problem**, and we'll try to fix it as soon as possible.

**Comment by lhc70000** [comment]
Close due to duplication. Please follow up in #377.
