### ISSUE TITLE
Touch Bar Play/Pause Button State Not Change

### ISSUE THREAD

**Issue by Pr-Chen** [lhc70000/iina#387]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.5

**Expected hehavior:**
click Play/Pause button on the screen, the Play/Pause state in Touch Bar should change.

**Actual behavior:**
click Play/Pause button on the screen, the Play/Pause state in Touch Bar not change.

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by darsnack** [comment]
This issue also occurs for me. Just trying to add more data/input/feedback.

**Using:**
- macOS 10.12.4 Beta (16E191a)
- IINA 0.0.6 Build 14
