### ISSUE TITLE
Open streams from WebTorrent

### ISSUE THREAD

**Issue by robertgzr** [lhc70000/iina#388]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected hehavior:**

Set up IINA as the default player in WebTorrent preferences.
IINA starts playing the file on clicking the play button in WebTorrent.

**Actual behavior:**

I get a `Cannot open file or stream!` error

![screenshot](http://i.imgur.com/U58oeAM.jpg)

Using mpv v0.23.0 this works just fine.

**Comment by lhc70000** [comment]
I'm not familiar with WebTorrent, please let me test out first.

**Comment by robertgzr** [comment]
This is how WebTorrent calls external players:
https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/external-player.js

I tried running IINA like this:
`/Applications/IINA.app/Contents/MacOS/IINA <path to currently downloading media>`
and it works just fine.

Not sure what the problem here is...

**Comment by robertgzr** [comment]
I get the same behavior when using IINA as an external player in Kodi using this bit of config in `<kodi-config-dir>/userdata/playercorefactory.xml`:
```xml
<playercorefactory>
 <players>
   <player name="IINA" type="ExternalPlayer" audio="true" video="true">
     <filename>/Applications/IINA.app/Contents/MacOS/iina-cli</filename>
     <args>--fullscreen --mpv-no-autoload-files "{1}"</args>
     <hidexbmc>true</hidexbmc>
     <hideconsole>false</hideconsole>
     <warpcursor>none</warpcursor>
   </player>
 </players>
</playercorefactory>
```
Here it also happens with files from my local disk.

**Comment by fabiospampinato** [comment]
A workaround for this is using [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli). I've added support for IINA recently.

Using it like this should work: `webtorrent download "magnet:..." --iina`

**Comment by lhc70000** [comment]
Now that IINA has a CLI, it should be easier to launch IINA through external applications. More CLI options have been added in 1.0.0 beta4 that will be released soon.
