### ISSUE TITLE
Error when enabling Flip / Mirror

### ISSUE THREAD

**Issue by INTELLECTUALZ** [lhc70000/iina#390]
谢谢大神做了这么人性化的播放器，有一点小问题，如果可以解决那就更厉害了。

对正在播放的视频进行“视频／翻转”里面的操作，就会发生一个弹窗的报错窗口，确认错误弹窗后崩溃退出。
我手头不同格式文件少，MP4报错，flv正常...望大神有空搞一搞。

报错如下：

> ERROR
Fatal error: MPV API error: "error running command", Return value: -12. 
The application will exit now.

**Comment by lhc70000** [comment]
硬件解码不支持此类视频滤镜。

很遗憾并没有解决方法。对需要翻转的视频请在设置中关闭硬件解码。不过下一版中会去掉错误提示，不会强制退出程序。

---

Most video filters are not supported when using hardware decoding. Please switch off hwdec when needed.

**Comment by INTELLECTUALZ** [comment]
哦，明白啦，如果不是 alert 类的提醒就更好了，感谢大神。

**Comment by lhc70000** [comment]
Fixed in 0.0.6.

**Comment by INTELLECTUALZ** [comment]
哇，大神好厉害
