### ISSUE TITLE
.ts格式播放只有声音没有图像

### ISSUE THREAD

**Issue by kuzmailer** [lhc70000/iina#395]
用的是 http://www.w6rz.net/bbb24p_00.zip 的测试视频进行的播放。

**Comment by HarukaMa** [comment]
@kuzmailer I have downloaded the test video and I can play it normally.

![0029-02-15 22 12 19](https://cloud.githubusercontent.com/assets/861659/22976562/9a711f2a-f3ce-11e6-8026-1112255fc32d.png)

It contains a fairly normal video stream (MPEG2 yuv422p), and it shouldn't have any problem...

**Comment by HarukaMa** [comment]
@kuzmailer Also,

**Please use issue template and _provide as much info as possible_ when you open an issue.** Thank you.

**Comment by kuzmailer** [comment]
今天尝试时，没有复现，先关掉issue
