### ISSUE TITLE
update check dialog box button (ok, cancel) is not localized.

### ISSUE THREAD

**Issue by darkbrow** [lhc70000/iina#397]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected hehavior:**

"OK" and "Cancel" Button of update check dialog box displayed in local language. 

**Actual behavior:**

Not localized, and hard-coded now. Just displayed in English.

(N/A for feature requests)

**Steps to reproduce:**

main menu -> check update
(N/A for feature requests)

**How often does this happen?**

always
(N/A for feature requests)

**Comment by lhc70000** [comment]
Let's include it in #295. Also see #301

**Comment by alejx** [comment]
Close due to duplication.
