### ISSUE TITLE
Avoid entering screen saver / sleep when playing | 播放时不进入屏保或睡眠

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#4]
from V2EX burning

**Comment by HarukaMa** [comment]
ref: https://developer.apple.com/library/content/qa/qa1340/_index.html

**Comment by juleq** [comment]
Sleep prevention does not work with 0.0.6 B14 on a Sierra 10.12.4 Beta (16E175b). Is it working on non beta? I could provide logs if that helps.
