### ISSUE TITLE
Can't recognize capitalized file extension

### ISSUE THREAD

**Issue by goodman-capu** [lhc70000/iina#402]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**

Capitalized file extension like video.AVI can show the same file icon like video.avi in Finder

**Actual behavior:**

video.AVI isn't assigned the right file icon

**Comment by lhc70000** [comment]
I don't think IINA is doing anything wrong with document types, and this should not happen.

Did you set IINA as the default player for AVI files and tried restarting Finder?

**Comment by goodman-capu** [comment]
The problem is gone after I restarted Finder :-D
