### ISSUE TITLE
Play speed automatically reset when the video is paused

### ISSUE THREAD

**Issue by awmleer** [lhc70000/iina#403]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Steps to reproduce:**

1. Open a video.
2. Click settings icon and change speed in the panel. (Change to 1.68x, for example)
3. Pause the video.
4. Continue to play the video.
5. Then speed will be reset to 1.0x.

**Expected behavior:**

Speed keeps to be 1.68x (the set value)

**Actual behavior:**

Speed shown in the right panel is still the 1.68x, but actual play speed is reset to 1.0x.

**How often does this happen?**
Always

**Comment by saagarjha** [comment]
Duplicate of #214 and #332, but now that I think about it I believe that this is a bug. @lhc70000 the speed should only be reset when fast-forwarding; when the user manually sets the speed using Settings panel it should stick even after pausing.

**Comment by awmleer** [comment]
Quite sorry about that…I'll close this issue.
