### ISSUE TITLE
高级设置 额外mpv选项错误

### ISSUE THREAD

**Issue by carlchina** [lhc70000/iina#405]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**

偏好设置-高级-启用高级设置-增加一个额外mpv选项-然后直接删除 软件崩溃

**Comment by lhc70000** [comment]
Cannot reproduce. Please upload your crash report.

**Comment by lhc70000** [comment]
Should already been fixed.
