### ISSUE TITLE
Error when the youtube-dl customized parameter is set

### ISSUE THREAD

**Issue by auzeonfung** [lhc70000/iina#406]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5 Build 11

**Expected behavior:**

No error occurs.

**Actual behavior:**

An error message has shown up:

`
Error error setting option (-7) when setting user option ytdl-raw-options.
`

**Steps to reproduce:**

Try setting youtube-dl raw option in **Preferences panel** with parameters below:

`
proxy=127.0.0.1:1087
`

`
proxy=http://127.0.0.1:1087
`

`
proxy=socks://127.0.0.1:1080
`

`
proxy="socks5://127.0.0.1:1080"
`

`
--proxy "socks5://127.0.0.1:1080"
`

**Comment by lhc70000** [comment]
Please see #404.

**Comment by dnivi3** [comment]
Sorry to necro this, but I am receiving the same error upon opening launching iina. I set some custom options for youtube-dl, but they seem to crash the app immediately upon launch. I have uninstalled the app twice and cleaned out any preference files, but it keeps crashing. Is there any way to definitely completely clear the settings?
