### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ltd920678778** [lhc70000/iina#408]
1. The current version and the previous version of the video file when you open the interface will first open for one or two seconds and then the playback interface will automatically shut down, and then click on the video file is not played only can only exit the application and then click on the video file to start playing.
2. In the advanced settings to add mpv configuration path and then exit the app, click on the video file app no response, unlimited chrysanthemum

**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Comment by lhc70000** [comment]
1. Duplicate with #377, etc.
2. Should be something wrong in your mpv config. Would you mind uploading your config file for a check?

**Comment by ltd920678778** [comment]
[mpv.zip](https://github.com/lhc70000/iina/files/785032/mpv.zip)
this is my config file！

**Comment by lhc70000** [comment]
Closing.

If you still have the problem, please make sure your config file doesn't contain any [https://github.com/lhc70000/iina/wiki/MPV-Options-and-Properties#reserved-options](reserved options).
