### ISSUE TITLE
关于ASS特效字幕的问题

### ISSUE THREAD

**Issue by panbofeng** [lhc70000/iina#409]
这里可能是MPV原本就有的一个问题，就是当全屏播放的时候，视频上下两侧会有黑边。有的ASS字幕默认位置设置的是视频下边缘，但是这时候播放器误以为这个下边缘是在屏幕底而不是视频的下方。所以这类ASS字幕就非常贴近屏幕下边缘造成难以阅读，只能缩小视频播放。不知道有没有办法解决，如图。
<img width="1280" alt="2017-02-18 12 19 49" src="https://cloud.githubusercontent.com/assets/7665385/23090274/0ee1b3f8-f5d5-11e6-9ab9-44f553f861ec.png">

**Comment by lhc70000** [comment]
这是「功能」而并非「问题」（见 #43）。

想取消这个功能，请取消 偏好设置>字幕>位置>全屏时显示在黑边；
想调整字幕位置，请在快速设置面板（Cmd+S）中拖动字幕位置的滑条。

> 有的ASS字幕默认位置设置的是视频下边缘

这无疑是字幕制作者的问题。
