### ISSUE TITLE
Link issue in gh page

### ISSUE THREAD

**Issue by HarukaMa** [lhc70000/iina#41]
Just a quick note.

中文语言首页上的“查看界面截图”和“提出你想要的功能”链接炸了（多了一层 `zh-cn/`

**Comment by lhc70000** [comment]
Fixed, please check.

It's a weird problem, should be a bug of [middleman](https://github.com/middleman/middleman).

反正从知乎或者 V2EX 上来的都已经看过截图了是吧（

**Comment by HarukaMa** [comment]
Closing as fixed.
