### ISSUE TITLE
ASS subtitle stop displaying during playback | 字幕失效

### ISSUE THREAD

**Issue by kcookey** [lhc70000/iina#410]
版本:  alpha 0.0.5

场景：ass字幕在某次播放中突然失效，无论重开软件和重启电脑，播放任何剪辑，都无法显示。即便在字幕选项界面可以选择，但无法显示

**Comment by lhc70000** [comment]
此问题是否仅限某一个视频/字幕？

如果可以重现，请在偏好设置中启用 mpv 日志，重现一次此问题，然后上传到这里。

**请使用 issue 模板。**

**Comment by kcookey** [comment]
再次确认，应该不限视频和字幕。
在播放时，多次在字幕选项卡中字体切换时会出现崩溃（重现需要多次随机点击各个字体）。
再次打开后，会出现字幕失效的问题（但是具有偶然性，同时也能用该触发奔溃的方法把失效问题恢复）

不好意思，对github还不太熟悉

**Comment by nileibin** [comment]
Same issue occasionally happened in every version I used (0.0.3+)

**Comment by kcookey** [comment]
还有一种重现的方式是
在播放时某一个视频的时候，再打开另一个视频文件，切换之后可以发现字幕失效

**Comment by NauxLiu** [comment]
@lhc70000  遇到了相同的问题，在观看 The Crown 美剧的时候，前两集字幕正常观看，在看第三集的时候不知道怎么触发了 Bug，表现为导致字幕一直不显示，重启应用或电脑都没办法解决。 包括之前看着没问题的前两集字幕也出不来了，不管是内置字幕或是 ass，srt。

**Comment by lhc70000** [comment]
@kcookey @NauxLiu 

Could you provide the mpv log when this issue happens? You may enable logging in Preference>Advanced.

---

请上传字幕不显示时的 mpv 日志（在偏好设置>高级中启用）。

**Comment by NauxLiu** [comment]
@lhc70000 

[logs.zip](https://github.com/lhc70000/iina/files/788083/logs.zip)

**Comment by lhc70000** [comment]
@NauxLiu  根据 log，文件有可能损坏（很有可能是 mpv 的问题）。如果文件不大，能否考虑把你现在的文件发给我测试呢？

**Comment by lhc70000** [comment]
请说明你在 log 中播放的这几个文件里哪些是字幕无法显示的，还是全部？

**Comment by NauxLiu** [comment]
@lhc70000 
是指播放文件的问题？ 觉得可能性不大，因为同样的文件直接使用 mpv 是能够正常显示字幕的（内置字幕）。 

还有个问题很奇怪，这个 bug 在播放 `The Crown` 这个剧出现后，`The Crown` 的所有剧集都不能显示字幕了。 但是这时候我观看老友记，还能正常显示字幕，后来不知道什么原因又触发了 bug，现在所有老友记也不会显示字幕了（包括之前没问题的剧集）。

**Comment by lhc70000** [comment]
重置以下选项呢？

- 取消勾选覆盖 ASS 样式
- 默认字体改为 `serif`（字体选择框下面可以输入）

**Comment by NauxLiu** [comment]
测试了下，不管用。

**Comment by lhc70000** [comment]
能否尝试删除 iina 的所有配置（设置不会保留）？

1. 复制并发给我 `~/Library/Preferences/com.colliderli.iina.plist`
2. 运行 `default delete com.colliderli.iina`
3. 确定设置恢复默认后再次测试

**Comment by NauxLiu** [comment]
这是  [com.colliderli.iina.plist](https://github.com/lhc70000/iina/files/788169/com.colliderli.iina.plist.zip)

运行 `default delete com.colliderli.iina` 并重启应用之后，发现我设置 `Ignore Ass styles` 等设置并没有被重置？ 然后反复播放了老友记测试字幕出来了，然后测试了 `The Crown` 字幕依然不显示，然后再测试老友记，又不显示了...

**Comment by NauxLiu** [comment]
刚尝试删除了以下文件 

![wechatimg293](https://cloud.githubusercontent.com/assets/9570112/23136897/ebb05a22-f7d9-11e6-9b45-b90f6a197dc3.jpg)

问题解决了，尝试将备份的 `~/Library/Preferences/com.colliderli.iina.plist` 替换回去, 问题没有重现。

下次再出现时我尽量观察下重现条件。

**Comment by lhc70000** [comment]
这个问题很有可能是误触快捷键 `v` 导致的（绑定至 `sub-visibility`）。

0.0.7 中已在默认配置中删除此快捷键。
