### ISSUE TITLE
Bitrate of video/audio steams in inspector

### ISSUE THREAD

**Issue by tomyang001** [lhc70000/iina#411]
System and IINA version:
macOS 10.12.3
IINA 0.0.5

Expected behavior:
The bitrate of video stream showed in inspector isn't converted to kbps. Please fix it. And please add the bitrate of audio stream for the convenience.

**Comment by lhc70000** [comment]
The whole inspector is going to be redesigned.

See #21, #122.

**Comment by lhc70000** [comment]
Please check out the new inspector in 0.0.6.
