### ISSUE TITLE
Window related MPV option don't work

### ISSUE THREAD

**Issue by vincentzlt** [lhc70000/iina#415]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**
upon setting:
geometry    +0-0

the new window should be positioned at the left-down corner.

**Actual behavior:**
nothing happened. The new window still appear at the center of the screen

Crash report:

**Steps to reproduce:**

Just set the additional option to see if it works.

**How often does this happen?**
everytime

**Comment by lhc70000** [comment]
Almost all window related options won't work since IINA uses its own window, and libmpv can't control this. However we have plan to bridge all of them later, like what `fullscreen` behaves now.

**Comment by vincentzlt** [comment]
Hi,

Thanks for the prompt reply.

Looking forward for your update.

**Comment by lhc70000** [comment]
IINA supports `geometry` from v0.0.7.
