### ISSUE TITLE
Keyboard localization problem

### ISSUE THREAD

**Issue by xiaoken** [lhc70000/iina#416]
- macOS 10.11.6
- IINA 0.0.5

When i press ] on the JIS keyboard mac, video play speed doesn't go faster
when i press [, video play speeds up?! while it should actually slow down
When @ key on the JIS keyboard is pressed, the playback slows down.

Clearly, IINA can't tell what type of keyboard i'm using. 
This is true for both keybinding configurations
**How often does this happen?**
Always

**Comment by lhc70000** [comment]
Yes, it's not supported now, see #191.
