### ISSUE TITLE
Support HTTP Authorization

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#417]
User can pass username and password in the format of
```
http://username:password@example.com/
```

It's better to have a GUI for this.

**Comment by sequencer** [comment]
this can cause the chrome plugin doesn't work in pages which already been authorized in browser.
I think use `open iina://username:password@example.com/` will be better.
and if server returns `401` a pop-up should be used to ask user enter the username&password.
meantime, I think the fail return should print the response code to user.
