### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by YorkeSun** [lhc70000/iina#418]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

或许是我的系统还是什么软件造成冲突（我电脑装的各类软件比较多，仅视频播放就有3个，各类编解码软件及视频非编软件都有），我的电脑上有如下问题：
1.每次开机后头一次打开视频文件都会一闪而过需要关闭程序再次打开就正常了，之后关闭程序再次打开并不会有任何异常。
2.最近几天每次打开都会有无法连接更新服务器的提示，但是如果是在提示前就已全屏，那么这个提示窗口的三个按钮均无法点击，此时只能通过强行关闭程序解决。
3.在我的系统中“播放时置顶”这一功能似乎无法启用。
4.我迫切的需要可以在播放时使用快捷键删除正在播放的影片及切换上下影片的功能，可能是我的英文不够好，我没有在快捷键中找到它们。还望指出。

感谢这个程序！MplayerX做到现在都不提供播放列表的问题终于有人可以解决了。我已经将其推荐给一众和我一样从事视频从业人员，并且将会在下学期开学后将其推荐给我所带领的学生团队。

**Comment by lhc70000** [comment]
> 1.每次开机后头一次打开视频文件都会一闪而过需要关闭程序再次打开就正常了，之后关闭程序再次打开并不会有任何异常。

目测已经在 develop 分支修复。

> 2.最近几天每次打开都会有无法连接更新服务器的提示，但是如果是在提示前就已全屏，那么这个提示窗口的三个按钮均无法点击，此时只能通过强行关闭程序解决。

应该是连接 github 有问题了（升级连接的是 github API，一个 IP 每小时 60 次限制），可能是超出了限制（尤其在局域网中）也可能是墙的问题。目前在 alpha 版本问题较多，升级是强制的。如果仍然无法解决，请回复。

> 3.在我的系统中“播放时置顶”这一功能似乎无法启用。

请提供详细的重现步骤。

> 4.我迫切的需要可以在播放时使用快捷键删除正在播放的影片及切换上下影片的功能

删除当前影片这个可能有点麻烦，请问这个需求是什么情况下会有呢？

切换上下影片默认快捷键可以用<kbd>&lt;</kbd>/<kbd>&gt;</kbd>，即<kbd>Shift</kbd>+<kbd>,</kbd>/<kbd>.</kbd>。添加快捷键时选「上一个/下一个视频」即可。

> 感谢这个程序！
谢谢。

**Comment by lhc70000** [comment]
@YorkeSun 

build18 加入了为 iina 自带功能设置快捷键的可能性，包括「删除当前视频」。请等待下个版本。
