### ISSUE TITLE
[Feature request] Automatically play at fullscreen mode

### ISSUE THREAD

**Issue by IvanWoo** [lhc70000/iina#422]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**
Automatically play the paused video when an user switch over from the window mode to the fullscreen mode.

**Comment by megadr01d** [comment]
I agree with this. Movist offers these two options which I'd like to see in IINA, "Automatically play when entering Fullscreen" and "Automatically pause when leaving fullscreen".
