### ISSUE TITLE
Check update show error window.

### ISSUE THREAD

**Issue by HongnianZhang** [lhc70000/iina#424]
Issues: open app show check-update error window. 
Network Status: `I can view github website.`
Version: Both 0.0.4 and 0.0.5
Feature: If network error do not show error window only if user check update manually.

Thanks.

**Comment by lhc70000** [comment]
Currently IINA uses github API to check updates. It has a limitation of 60 request/hr, and may be blocked sometimes, even though you can visit the website. I'm sorry for that, but I don't have much time at this very initial development phase.

We'll use a standalone server for beta versions. You can also join the QQ / Telegram group for stable links (BaiduYun, etc) to new versions.
