### ISSUE TITLE
Play speed input validation

### ISSUE THREAD

**Issue by ewoks** [lhc70000/iina#425]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**

User wants to adjust custom play speed. In Edit field is already written "1.00" so user expect to write "1.33" and that value to be accepted and applied.

**Actual behavior:**

If user tries to write "1.33" or any other decimal value using decimal point (".") it doesn't work. It is necessary to write value using comma "," like "1,33" value to be accepted, despite default value displayed with decimal point. Any future value will be displayed with decimal point as well but newly written value need to be entered using comma instead of point.

Crash report:
There is no crash.

**Steps to reproduce:**
Already described in expected/actual behaviour

**How often does this happen?**
Always

**Comment by saagarjha** [comment]
@ewoks I'm guessing you live in a region with the comma/decimal switched? It looks like I forgot to internationalize the display for the speed slider.
