### ISSUE TITLE
Crash when opening a URL with spaces in it

### ISSUE THREAD

**Issue by ghost** [lhc70000/iina#426]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

IINA plays back files with spaces in them from URLs. This used to work in 0.0.5.

**Actual behavior:**

Crash. It seems to work if you encode the spaces with `%20` though.

Crash report: http://sprunge.us/IaaB

**Steps to reproduce:**

1. Open a URL with at least one space in it, like `https://example.com/test file.mkv`
2. IINA crashes

**How often does this happen?**

Always

**Comment by saagarjha** [comment]
@lhc70000 Creating a `URL` will fail if it is not percent encoded beforehand. Fixed in #429.

**Comment by lhc70000** [comment]
I don't think something like `https://example.com/test file.mkv` is a valid URL though…… I'd probably choose to reject it and show an alert.

If user copied the link from otherwhere with spaces added accidentally, like `http: //example.com/test.mkv`, it will proceed without any alert and just say "cannot open stream", which can make user confused. On the contrast, I can't image a situation of someone releasing a URL without percent encode.

**Comment by oekaki** [comment]
I can imagine a use case where you play video files e.g. from your personal web server

With mpv you can do 
`mpv "http://myserver.com/some file.mkv"` or 
`mpv http://myserver.com/"some file.mkv"`

Maybe IINA could support quoting the URL like that?

**Comment by jpzbkk** [comment]
Having issues with this using the most recent builds.  Using either:
ftp://test:test@test.server.xyz/Test Movie.avi
ftp://test:test@test.server.xyz/Test%20Movie.avi

However works fine for mpv.
