### ISSUE TITLE
Translucent on screen display suggestion | 半透明的总体UI背景

### ISSUE THREAD

**Issue by gonejack** [lhc70000/iina#427]
I think the current UI components with solid background color is not that comfortable, especially when users didn't modify the default time settings about how long those on screen controllers should stay, they could keep on front of movies for quire while thus becoming interferences.

By regular design principle, components for movie players should be inconspicuous and less sheltery.

**Comment by saagarjha** [comment]
Not quite sure what you mean with "current UI components with solid background color". IINA's controls are transparent like QuickTime's, and auto-hide just like most other video players'. Perhaps you could expand a bit more on what you mean?

**Comment by gonejack** [comment]
My mistake, I checked to Reduce transparency in system setting, but after undo that, those components looks still kind of, unsatisfied, perhaps an option for transparent would be nice.

**Comment by lhc70000** [comment]
There's no option for "transparent percentage", since it's system defined style.

Please try restarting your system first, and upload some screenshots to help us figure out what happened.
