### ISSUE TITLE
Move subtitle underneath the movie when black banners appear in full screen mode 全屏有黑边时，字幕在黑边上显示

### ISSUE THREAD

**Issue by halblooline** [lhc70000/iina#43]
全屏以后，如果屏幕在电影画面上下加上黑边，让字幕在下方黑边上显示，从而不遮挡电影画面底部内容。
希望可以加上这个功能

**Comment by lhc70000** [comment]
最近两三个版本可能不会考虑，目前 IINA 的设定是窗口大小跟随视频大小。

不过我觉得这个功能应该有，请耐心等待 :p

**Comment by megadr01d** [comment]
I wouldn't make this automatic but rather an option. In Movist you can choose the subtitles location (movie area or letterbox) and even add spacing to that. Personally, I prefer subtitles on top of the movie be it 16:9 or 4:3.

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).
