### ISSUE TITLE
Crash when quit playing youtube video

### ISSUE THREAD

**Issue by dimitrov-adrian** [lhc70000/iina#433]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6 build 14

**Expected behavior:**

Close normaly

**Actual behavior:**

Crash

**How often does this happen?**

Twice randomly, can't reproduce with steps

[untitled.txt](https://github.com/lhc70000/iina/files/795020/untitled.txt)

**Comment by lhc70000** [comment]
It's a known problem (from 0.0.1). We'll try to find the reason and fix it as soon as possible.

Duplicate with #2

**Comment by alejx** [comment]
See #2 .
