### ISSUE TITLE
mpv option force-window immediate mode revoke fatal error in IINA

### ISSUE THREAD

**Issue by fatestigma** [lhc70000/iina#437]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

If doesn't support option `force-window=immediate`, IINA can ignore it instead of raising an error.

Following is the description of [mpv's option force-window](https://mpv.io/manual/master/#options-force-window).

> --force-window=<yes|no|immediate>
> Create a video output window even if there is no video. This can be useful when pretending that mpv is a GUI application. Currently, the window always has the size 640x480, and is subject to --geometry,  --autofit, and similar options.

**Actual behavior:**

Before IINA 0.06, IINA will just crash without any warning. IINA 0.06 will [prompt an error window with message "Fatal error: MPV API error: 'invalid parameter', Return value: -4"](http://i.imgur.com/Xrn0GHw.png) and exit after clicking "OK". After I disabled my mpv configurations one by one, I found the problem is `force-window=immediate` in my mpv.conf. At the same time, my mpv(version 0.24.0) doesn't have this issue.

- Crash report:

> MPV API error: "invalid parameter", Return value: -4.
> MPV log: [cplayer] fatal: Error opening/initializing the VO window.

```
0   IINA                                0x000000010bb48067 _TTSf4n_d___TTSf1n_cl48_TFIZFC4IINA7Utility5fatalFTSSFT_T__T_A1_U_FT_T__n___TZFC4IINA7Utility5fatalfTSSFT_T__T_ + 183
1   IINA                                0x000000010bc12150 _TTSf4n_d___TFC4IINA13MPVControllerP33_AA8C985EFDB89116DD68AB87EEE66A736chkErrfGSQVs5Int32_T_ + 384
2   IINA                                0x000000010bc079bf _TFC4IINA13MPVController7mpvInitfT_T_ + 19951
3   IINA                                0x000000010bbea6d4 _TFC4IINA10PlayerCore8startMPVfT_T_ + 1476
4   IINA                                0x000000010bb9a60e _TFC4IINA11AppDelegate29applicationDidFinishLaunchingfV10Foundation12NotificationT_ + 430
5   IINA                                0x000000010bb9acaa _TToFC4IINA11AppDelegate29applicationDidFinishLaunchingfV10Foundation12NotificationT_ + 58
6   CoreFoundation                      0x00007fff95ad79fc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
7   CoreFoundation                      0x00007fff95ad78fb _CF
```

**Steps to reproduce:**

1. Enable IINA's advanced settings.
2. Add `force-window=immediate` into mpv.conf
3. Restart IINA.app
4. Boom!

- [x] MPV does not have this problem.

**How often does this happen?**

Every time if `force-window` option uses `immediate` mode.

**Comment by lhc70000** [comment]
Unfortunately I can't find a easy way to avoid this. mpv will load config files during initialization, which is a opaque process for IINA. So setting the option _before_ initialization won't override the config file, and setting it _after_ initialization will be too late.

Seems that the only solution is to remove or comment this line in your config file.
