### ISSUE TITLE
enter key for full screen 希望能够默认支持回车键全屏

### ISSUE THREAD

**Issue by jediyoda36** [lhc70000/iina#44]
给妹子推荐之后只见她每次全屏的时候都要敲一次回车 = =
所以希望默认支持回车键全屏，或者做一个对普通用户友好的快捷键菜单。

---

- Press enter key for fullscreen
- A user friendly key bindings setting interface

**Comment by lhc70000** [comment]
> 对普通用户友好的快捷键菜单
在计划内，不会太晚

但是目前全屏不能在快捷键设置里实现（窗口不是 mpv 自己的），我想想怎么解决。

**Comment by lhc70000** [comment]
0.0.2 已发布，支持通过快捷键全屏。`f` 可以切换全屏；`ENTER` 可以进入全屏，`ESC` 可以退出全屏。

如果你想让 `ENTER` 切换全屏（即可以进入也可以退出） 请在偏好设置的快捷键中复制 IINA Default 的配置，把 ENTER 对应的命令改为 `cycle fullscreen`即可。

---

0.0.2 supports fullscreen command in keybindings: `cycle fullscreen` for toggling fullscreen, `set fullscreen yes/no` for entering/exiting fullscreen.
