### ISSUE TITLE
Can we install it using homebrew?

### ISSUE THREAD

**Issue by lijingjiang** [lhc70000/iina#440]
Firstly, thank you for this awesome software! This issue is just a feature request: Will the iina support homebrew installation?

Thanks.

**Comment by HarukaMa** [comment]
@lijingjiang `brew cask install iina`

**Comment by lijingjiang** [comment]
@HarukaMa Thank you for the reply, but unfortunately it doesn't work in my case

Error: No available Cask for iina
Error: nothing to install

Is there any tap I need to add?

Thank you

**Comment by alejx** [comment]
@lijingjiang Try to update your homebrew and cask first.

**Comment by silic0ns0ul** [comment]
possibly macports as well?
