### ISSUE TITLE
Changing volume with trackpad is too sensitive

### ISSUE THREAD

**Issue by beretboat** [lhc70000/iina#441]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

1.  Decrease the default sensitivity.
2. The sensitivity should respect following configs like mpv do:
AXIS_UP    osd-msg-bar add volume -5
AXIS_DOWN  osd-msg-bar add volume 5

**Actual behavior:**

Changing volume with trackpad is too sensitive, which makes it hard to reach my desired volume.

**Steps to reproduce:**

Scroll vertically with built-in trackpad on Macbook Pro.

**How often does this happen?**

Always

**Comment by alejx** [comment]
#464 has implement the function to change sensitivity of trackpad.
