### ISSUE TITLE
Speed reset to normal when pause | 调节播放速度暂停后播放速度恢复正常

### ISSUE THREAD

**Issue by dinpor** [lhc70000/iina#442]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**
在播放窗口，点击⚙调节播放速度后，此时播放器会根据调节的速度进行播放，当暂停播放再点击播放时，播放器速度恢复正常（1x速度），打开⚙播放速度的设置还是调节后的值。

(N/A for feature requests)

**Comment by lhc70000** [comment]
Duplicate with #332, #403

**Comment by alejx** [comment]
Close due to duplication.
