### ISSUE TITLE
mouse scroll wheel left/right does not video seek correctly during video playback

### ISSUE THREAD

**Issue by silic0ns0ul** [lhc70000/iina#445]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Horizontal video seek is set to "keyframe seek" in the "mouse control" setting. During video playback, scrolling the mouse wheel left/right should video seek back/fwd by keyframes.

**Actual behavior:**
Instead, during video playback, mouse scroll wheel left/right is partially broken. Scrolling right for forward seeking is fine, but scrolling left for backward seeking only goes back 1 previous keyframe from current time point. However, when video is paused, scrolling wheel left/right produces expected back/fwd video seek.

Therefore, this may be an issue with mpv playback itself and not IINA?

**Comment by lhc70000** [comment]
Perhaps it's due to too large keyframe interval in this particular file. I've encountered this problem for some files too, and will take a detailed look later.

**Comment by lhc70000** [comment]
Should already been fixed now.
