### ISSUE TITLE
加入镜像翻转功能

### ISSUE THREAD

**Issue by sherkiuy** [lhc70000/iina#447]
不是旋转，而是左右翻转这样

**Comment by lhc70000** [comment]
「播放」菜单中有水平和垂直翻转。

请注意，开启硬件解码的时候，这类滤镜选项很可能不起作用。

**Comment by 70599** [comment]
可否为画面旋转／翻转设置快捷键？

**Comment by lhc70000** [comment]
@70599 已在 develop 中加入，请等待下一版本。

**Comment by Leroy-X** [comment]
> [@70599](https://github.com/70599) 已在 develop 中加入，请等待下一版本。

请问镜像翻转的快捷键是什么，是否考虑将该功能加入设置侧边栏。镜像功能对瑜伽舞蹈类的教学非常有用
