### ISSUE TITLE
Hangs when mpv.conf contains vo | 使用配置目录导致播放影片卡死

### ISSUE THREAD

**Issue by yangyaofei** [lhc70000/iina#448]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
启用配置目录后播放影片卡死,图标变成mpv图标

**Actual behavior:**
log : 
https://gist.github.com/yangyaofei/06dd7c571ead508a330865b1b27570ff

**Steps to reproduce:**

1 开启高级-> 启用配置目录
2 重启iina
3 打开影片卡死

**How often does this happen?**

认为可能是目录写错了,具体见log的73-75行

```
[ 161.998][v][cplayer] Run command: loadfile, flags=0, args=[/Volumes/TDDOWNLOAD-1/Jackie.2016.第一夫人.720p.Chi_Eng.ZMZ-BD-MP4.mp4, replace, ]

[ 162.011][v][global] config path: 'Jackie.2016.第一夫人.720p.Chi_Eng.ZMZ-BD-MP4.mp4.conf' -/-> '/Users/yangyaofei/.config/mpv/Jackie.2016.第一夫人.720p.Chi_Eng.ZMZ-BD-MP4.mp4.conf'

[ 162.012][v][global] user path: '/Users/yangyaofei/Library/Application Support/com.colliderli.iina/watch_later' -> '/Users/yangyaofei/Library/Application Support/com.colliderli.iina/watch_later'
```
估计是什么地方将变量用错了的样子,将配置文件和播放文件的名字搞混了..

**Comment by lhc70000** [comment]
很可能是你的 mpv.conf 里有 `vo` 的设置。

请尝试注释掉之后那一行再试。此问题下一版本会修复。

---

It will happen when your `mpv.conf` contains settings for `vo` (It's mandatory to be `opengl-cb`). Please try commenting such line as a workaround for current version.

**Comment by yangyaofei** [comment]
确实有vo设置,注释之后问题消失

**Comment by lhc70000** [comment]
Fixed in develop.
