### ISSUE TITLE
Modification to the function play the recent file|修改最近播放文件的功能

### ISSUE THREAD

**Issue by RhodesZ** [lhc70000/iina#449]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

When you watch the soap opera, you want to start at the position where you left the last time. But IINA only records the last file you oened.

刷剧的时候希望能接着看上次离开的地方，但IINA只记录最近打开的文件。例如，我从第一集打开文件，使用播放列表功能看到第10集，但下次打开IINA只记录最近打开文件是第一集，并不能直接跳转到第10集，而是要自己慢慢找。

**Comment by tzm41** [comment]
Hahaha soap opera😂

**Comment by lhc70000** [comment]
Added in 0.0.10.
