### ISSUE TITLE
Request that the playlist not list the files that start off with ._*

### ISSUE THREAD

**Issue by damengilland** [lhc70000/iina#450]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

I shouldn't see these in the playlist.

<img width="295" alt="screen shot 2017-02-28 at 4 15 01 pm" src="https://cloud.githubusercontent.com/assets/1106778/23436769/59e4885e-fdd1-11e6-9ecd-ad7844f6fe95.png">

**Comment by lhc70000** [comment]
Fixed in develop.
