### ISSUE TITLE
Touch Bar Persistence Missing

### ISSUE THREAD

**Issue by StarlightDesign** [lhc70000/iina#451]
I'm not sure if this is a missing feature or an already implemented feature that's bugged, but I'm hoping for persistent Touch Bar controls in the Control Strip once you leave the IINA full screen space. Kind of like what iTunes or Safari does with songs or HTML video, and how you can control them while working in a different app screen.

A great use case and my example of what I'm looking for is seeking while using Picture-in-Picture and working in a different app space.

Is this something that can be implemented or fixed?

**Comment by inflation** [comment]
With a simple search, it supposed to be a private API. Do we want to implement it? @lhc70000

**Comment by lhc70000** [comment]
I think it's OK, anyway IINA has already used private APIs.

**Comment by saagarjha** [comment]
@StarlightDesign Please send screenshots/more detail, as I can't get the controls to show up in the background on my computer for Safari or iTunes.

**Comment by StarlightDesign** [comment]
<img width="1085" alt="touch bar shot 2017-03-22 at 10 15 13 pm" src="https://cloud.githubusercontent.com/assets/8271041/24233084/28de944c-0f4d-11e7-9bab-779f62a8dea2.png">
<img width="1085" alt="touch bar shot 2017-03-22 at 10 15 24 pm" src="https://cloud.githubusercontent.com/assets/8271041/24233083/28ddd980-0f4d-11e7-8916-53ab88f29029.png">

This is how the Touch Bar media persistence shows up on my laptop. Just to elaborate, this is for the new MacBook Pro computers for the Touch Bar specifically. Picture in Picture on Mac doesn't have any controls available in the window, and you have to return to the actual player's space to control it. It would be really handy to access seek controls from the Touch Bar while using a different app altogether.

**Comment by saagarjha** [comment]
@StarlightDesign Thanks for the screenshots. I'm still trying to get it to show up on my computer (which doesn't have a physical Touch Bar); once I can get it working I'll look into how it's implemented.

**Comment by StarlightDesign** [comment]
@saagarjha Many thanks, appreciate the help.

**Comment by alejx** [comment]
@saagarjha @inflation @lhc70000 As far as I'm concerned, this feature is not related with the touch bar. If an application can be controlled by the system media keys, then it will be displayed in the touch bar.

I searched MPV's source code about this, [c39efb9](https://github.com/mpv-player/mpv/commit/c39efb96d1109b7a5960cd17cc4c392c2b93b61b) and [213ad5d](https://github.com/mpv-player/mpv/commit/213ad5d6c41f32cf9086fa377cd6d6df1236bb76) worked on this problem. However, MPV is not shown in the touch bar. MPV subclassed `NSApplication` and simply captures the media keys. I would say this implementation lacks of something.

I also noticed that NeteaseMusic's icon is shown in the touch bar, as well as it can be controlled by media keys well. It uses [SPMediaKeyTap](https://github.com/nevyn/SPMediaKeyTap) indicated by their about window.

```objc
+ (NSArray*)defaultMediaKeyUserBundleIdentifiers;
{
	return [NSArray arrayWithObjects:
		[[NSBundle mainBundle] bundleIdentifier], // your app
		@"com.spotify.client",
		@"com.apple.iTunes",
		@"com.apple.QuickTimePlayerX",
		@"com.apple.quicktimeplayer",
		@"com.apple.iWork.Keynote",
		@"com.apple.iPhoto",
		@"org.videolan.vlc",
		@"com.apple.Aperture",
		@"com.plexsquared.Plex",
		@"com.soundcloud.desktop",
		@"org.niltsh.MPlayerX",
		@"com.ilabs.PandorasHelper",
		@"com.mahasoftware.pandabar",
		@"com.bitcartel.pandorajam",
		@"org.clementine-player.clementine",
		@"fm.last.Last.fm",
		@"fm.last.Scrobbler",
		@"com.beatport.BeatportPro",
		@"com.Timenut.SongKey",
		@"com.macromedia.fireworks", // the tap messes up their mouse input
		@"at.justp.Theremin",
		@"ru.ya.themblsha.YandexMusic",
		@"com.jriver.MediaCenter18",
		@"com.jriver.MediaCenter19",
		@"com.jriver.MediaCenter20",
		@"co.rackit.mate",
		@"com.ttitt.b-music",
		@"com.beardedspice.BeardedSpice",
		@"com.plug.Plug",
		@"com.plug.Plug2",
    @"com.netease.163music",
    		@"org.quodlibet.quodlibet",
		nil
	];
}
```
This piece of code shows applications which are using SPMediaKeyTap to capture system media keys.

> For now, the whitelist is just a hardcoded array in `+[SPMediaKeyTap defaultMediaKeyUserBundleIdentifiers]`. If your app starts using `SPMediaKeyTap`, please mail me your bundle ID, and I'll include it in the canonical repository. This is a bad solution; a better solution would be to use distributed notifications to collaborate in creating this whitelist at runtime. Hopefully someone'll have the time and energy to write this soon.

From README from SPMediaKeyTap.

**Comment by saagarjha** [comment]
From the [associated page](http://overooped.com/post/2593597587/mediakeys):

> Apple has solved this problem internally by having their media key using applications cooperate and resign media key controls to the application that was in the foreground most recently. However, there is no way for third party applications to join this cooperation.

It might be easier to just reverse engineer what Apple is doing, and implement that in IINA. That way we don't have to add SPMediaKeyTap as an external dependency or get it added to their whitelist.

**Comment by alejx** [comment]
I don't think that would easier. The truth is that applications that use `SPMediaKeyTap` work properly as a native macOS media application both on touch bar and media keys; mpv can only handle media keys.

**Comment by saagarjha** [comment]
@alejx I believe you're right. I poked around rcd.app, which I believe handles the media keys, and it appears that it's hardcoded a set of applications that it responds to. We'll have to deal with it ourselves.
