### ISSUE TITLE
I would like to ask the file name suffix is.AAC can use this to open it?|请问文件名后缀是.AAC的可以用这个打开吗?

### ISSUE THREAD

**Issue by JavanTang** [lhc70000/iina#452]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment]
@JavanTang 可以啊
