### ISSUE TITLE
Use gestures to modify the windows size (like MplayerX)

### ISSUE THREAD

**Issue by Hackl0us** [lhc70000/iina#453]
Dear Developer:

I love this app very much, and I'm so happy to see that lots of useful & powerful functions are added into this App to make it become the best video player on macOS.

However, I hope that you can add the **gestures control** function, just like MplayerX. 

- Modifying the windows size conveniently by pinching in/out (to zoom out/in). 
- Swiping up/down (volume up/down)
- Swiping left/right (switch videos)
- other gestures

Thanks for read my words and hope that you can take my suggestions. I believe that IINA could replace the MplayerX eventually.

Looking forward to your reply.
Have a nice day :)

**Comment by lhc70000** [comment]
- Modifying the windows size conveniently by pinching in/out (to zoom out/in): Duplicate with #66, etc.
- Swiping up/down (volume up/down): It's supported already.
- Swiping left/right (switch videos): What do you mean by "switch videos"? (currently, it seeks when scroll left/right)
- other gestures: please suggest more. I personally think most of MplayerX's gestures (like rotation) are not practical at all.

**Comment by alejx** [comment]
See #464 .

**Comment by Hackl0us** [comment]
@lhc70000 @alejx Thanks a lot.
I has joined the Telegram group. And I found that this function has been added into build 15, it works very well.

Thanks again. Now, IINA can completely replace the MPlayerX.
