### ISSUE TITLE
Video can't be piped in from streamlink/livestreamer

### ISSUE THREAD

**Issue by jsoftwareengineering** [lhc70000/iina#456]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

Video piped in from [streamlink](https://github.com/streamlink/streamlink) via the command line should play.

This works with normal mpv. 

**Actual behavior:**

IINA opens, but no video is played. 

**Steps to reproduce:**

1. Install [streamlink](https://github.com/streamlink/streamlink).
     sudo pip install streamlink
2. Create a configuration file for streamlink.
     cd ~/.config
     mkdir streamlink
     touch streamlink/config
3. Add the line to the config file (from within a text editor) that tells streamlink to use IINA.
     player=/Applications/IINA.app/Contents/MacOS/IINA
4. In the terminal type 
     streamlink [[A TWITCH STREAM](https://www.twitch.tv)] best

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
IINA doesn't support launching from terminal (read from stdin) right now.

See #58

**Comment by alejx** [comment]
Close due to duplication.
