### ISSUE TITLE
Display video title when play YouTube video

### ISSUE THREAD

**Issue by avalanchesiqi** [lhc70000/iina#458]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Display YouTube video title in the top bar and playlist instead of showing _watch?v={video_id}_.
Online video path also is not added to "Open Recent" list.

**Actual behavior:**
N/A

**Steps to reproduce:**
N/A

**How often does this happen?**
N/A

![image](https://cloud.githubusercontent.com/assets/3666911/23570179/449ef8c4-00b7-11e7-8010-57a4c2b1d421.png)

**Comment by lhc70000** [comment]
youtube-dl is handled by mpv itself, so it depends on whether mpv's lua script support retrieving video title. Of course IINA can get the title independently, but it seems to be a dirty solution.

**Comment by lhc70000** [comment]
Already fixed in 0.0.12 😋
