### ISSUE TITLE
...

### ISSUE THREAD

**Issue by HarveyAngel** [lhc70000/iina#459]

**Comment by lhc70000** [comment]
@HarveyAngel I can't connect to this website in my browser either. Please confirm that the link is alive.

**Comment by HarukaMa** [comment]
@HarveyAngel Don't expect this kind of link will EVER work; they are for Xunlei to leech from other sources.

**Comment by HarveyAngel** [comment]
If the link don’t work, so be it. The problem is the break down, understand?

**Comment by HarveyAngel** [comment]
The link is for Thunder to download. The problem is IINA break down.在 2017年3月4日，下午7:07，Collider LI <notifications@github.com> 写道：@HarveyAngel I can't connect to this website in my browser either. Please confirm that the link is alive.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lhc70000/iina","title":"lhc70000/iina","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/lhc70000/iina" class="">https://github.com/lhc70000/iina</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lhc70000 in #459: @HarveyAngel I can't connect to this website in my browser either. Please confirm that the link is alive."}],"action":{"name":"View Issue","url":"<a href="https://github.com/lhc70000/iina/issues/459#issuecomment-284144759" class="">https://github.com/lhc70000/iina/issues/459#issuecomment-284144759</a>"}}}

**Comment by HarveyAngel** [comment]
The link is for Thunder to download. The problem is IINA break down.

在 2017年3月4日，下午7:07，Collider LI <notifications@github.com<mailto:notifications@github.com>> 写道：


@HarveyAngel<https://github.com/HarveyAngel> I can't connect to this website in my browser either. Please confirm that the link is alive.

―

**Comment by HarukaMa** [comment]
@HarveyAngel Read the latest edits in webpage.

Please don't reply too many times...

**Comment by HarukaMa** [comment]
@HarveyAngel You know what is "being addressed right now." and "dupe" and "pull requests" right?

**Comment by HarveyAngel** [comment]
@HarukaMa What are you trying to say? I found an issue and I post it. Is there any wrong about that? Yeah the link dose not work, I know that, okay? I post the link is just for reappear the break down. 
If you have problem, just say it.

**Comment by HarukaMa** [comment]
@HarveyAngel I've stated that the issue is being addressed right now in the edit. I've also posted the corresponding duplicate issue and PR that includes proposed fix. 

I'm having the exact question right now: What are you trying to say?

I know your problem that IINA crashed. However your language is considered aggressive.

"..., understand?" This is not right way to say that. You are not commanding anyone. Not mentioning that mystery downvote.

**Comment by HarveyAngel** [comment]
@HarukaMa Sorry for the 'downvote' and aggressive language. I just had a bad day man.

**Comment by HarukaMa** [comment]
@HarveyAngel Never mind, I accidentally pressed enter when typing the first comment so your received email didn't include the edited content. I part of understand that effect.

The URL issue is almost fixed, however the code still need some extra work to ensure it don't mess up the actual URL requested. Should be done soon.

**Comment by HarveyAngel** [comment]
@HarukaMa Oh, Haha, So that is why I misunderstood. Truly sorry bro. By the way, are you one of the developers? If you are then thank you for your great job, IINA is a very great and very elegant player.
