### ISSUE TITLE
Some unexpected behaviour with saving downloaded subtitles.

### ISSUE THREAD

**Issue by freedani** [lhc70000/iina#460]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

Download the choosing subtitle.

**Actual behavior:**

Download the last subtitle.

**Steps to reproduce:**

1. subtitle->find online subtitle.
2. App told me it found several (like 3) subtitles.
3. choosing subtitle->subtitle->1(or 2).
4. clicking on subtitle->saving downloaded subtitle.
5. I get the last subtitle (3) which I would not love to download.

**How often does this happen?**

every movie with multiple online subtitles.

**Comment by lhc70000** [comment]
This should have been fixed. Please reopen if it persists.
