### ISSUE TITLE
Proxy Icon in title bar

### ISSUE THREAD

**Issue by mhampl** [lhc70000/iina#461]
I think this app is very promising. Thanks a lot for the effort.

There is one feature I miss (besides support for the apple remote): Please have a proxy icon in the title bar when a video is open. A right click on it (or the file name next to it) should show a popup menu with the path to the file. I think this is standard in macOS: https://developer.apple.com/library/prerelease/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowAppearanceBehavior.html

After watching a video I want to move the file to another folder. The proxy icon makes it very easy to do that: Either drag the proxy icon to folder or right click on the proxy icon and open the folder that contains the file with a click. I'm not sure if there is another good way to find the file that is currently played in the finder. MPlayerX doesn't have this feature which is a pain (VLC has it, by the way).

**Comment by lhc70000** [comment]
It's implemented in #366, but we still need some more time to get it merged.
