### ISSUE TITLE
The default volume is too small

### ISSUE THREAD

**Issue by shawnchiu96** [lhc70000/iina#463]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

The default volume is too small. Please louder. 

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

-  MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by euf** [comment]
Default volume should be 100%, like any other macOS app.

**Comment by lhc70000** [comment]
There's no "default" volume. It always remembers your last volume value.

**Comment by euf** [comment]
Maybe I am mistaken, but when you install and launch IINA for the first time, volume is not 100%. This is how I understand «default».

**Comment by lhc70000** [comment]
I'm going to add an option to set a forced initial volume each time when opened file. Is it what you want?

**Comment by euf** [comment]
@lhc70000 
I thought that we were talking about first launch, so let us ask the OP, @zhaoxingyuan.
As for me, remembering last volume value is intuitive and there is no need in changing that.

**Comment by zhaoxingyuan** [comment]
Sorry, I mean that when I drag the slider of volume  to 100%, it is still smaller than other video players like Baofeng or iQiyi when I play a same video.

#2 As for me, remembering the last playback speed is also important.

#3 When I pause by the space bar, the video is paused, but the Touch Bar (MacBook Pro 2016) is still shows “playback icon”.

Sorry to my poor English and waiting for a new vision.

Best wishes.

在 2017年3月17日，上午7:59，euf <notifications@github.com<mailto:notifications@github.com>> 写道：


@lhc70000<https://github.com/lhc70000>
I thought that we were talking about first launch, so let us ask the OP, @zhaoxingyuan<https://github.com/zhaoxingyuan>.
As for me, remembering last volume value is intuitive and there is no need in changing that.
