### ISSUE TITLE
Hope can save video extract from youtube-dl

### ISSUE THREAD

**Issue by tenthxx** [lhc70000/iina#465]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

Dear developer, I really like this app and I hope it can have the function which can save video extract from youtube-dl or show it's real url, thanks

**Comment by lhc70000** [comment]
Please check the [wiki](https://github.com/lhc70000/iina/wiki/Use-youtube-dl-with-IINA): I suggest using `youtube-dl` itself to download a video, like

```sh
# install it
brew install youtube-dl

# download video to "funny_video.flv"
youtube-dl -o funny_video.flv "http://some/video"
```
