### ISSUE TITLE
Sometimes the OSC may cover the subtitle

### ISSUE THREAD

**Issue by Hewasshushed** [lhc70000/iina#466]
When i use the original MPV, i can edit 'lua-settings/osc.conf' to set a deadzone, which means i can move the mouse without displaying the OSC.  But IINA doesn't use the mpv-style OSC, so when i play videos, sometimes the OSC will suddenly flash up on the screen and cover the subtitle.

i have tried to move the OSC with mouse manually, but it will go back to the default position when i play next video. 

Of course the iina is the best player i have used on OS X , but i expect the option of OSC deadzone or fixed OSC can be added to the player in the coming version.

Thanks &
Looking forward to your favorable reply.

**Comment by Hewasshushed** [comment]
<img width="800" alt="2017-03-07 3 47 24" src="https://cloud.githubusercontent.com/assets/26228772/23646833/a24ee4d2-034d-11e7-99e3-8e75bdeb75f1.png">
Though it is not a serious problem, it sometimes bothers users.

**Comment by megadr01d** [comment]
Yeah, this is exactly the problem with floating elements/controllers: they block content in the most unexpected situations (like the new browser statusbar trend or the ever dreadful tooltips).

**Comment by Hewasshushed** [comment]
Thanks & Looking forward to the update

**Comment by lhc70000** [comment]
Please leave the issue open as long as it's not solved. Or I may forget it :P

**Comment by Hewasshushed** [comment]
Oh sorry...anyway thx a lot :D

**Comment by alejx** [comment]
Fixed in #554 in develop.

You may try "top" or "bottom" layout for OSC in next version.

**Comment by alejx** [comment]
Added in 0.0.8, have a try!

**Comment by vassudanagunta** [comment]
Unfortunately bottom layout will cover subtitles as well (see #1340), even when the video's aspect ration leaves plenty of vertical screen space to place the controller *below* the video.
