### ISSUE TITLE
Hope the subtitles' settings can be saved.

### ISSUE THREAD

**Issue by Danny05922161** [lhc70000/iina#467]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

Hope the subtitles' settings can be saved. Every time I restart the IINA. 
The setting all come to default. 

IINA is a good player on MacOS.
Thank for all your works.

**Comment by lhc70000** [comment]
@Danny05922161 Please set permanent options in Preference > Subtitles. The settings in sidebar is only for temporary adjustment.
