### ISSUE TITLE
No initial window | 点击 IINA.app 后，不显示任何窗口

### ISSUE THREAD

**Issue by panxiaoan** [lhc70000/iina#468]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

点击 IINA.app 后，dock 中出现 IINA APP 的 图标，菜单栏也显示 IINA 相关菜单，奇怪的是，没有显示任何 IINA 相关的窗口。直接打开视屏文件，能够正常使用。

**Comment by lhc70000** [comment]
@panxiaoan 这是正常行为，现在确实没有。如果你想有个初始的打开文件窗口，请启用「偏好设置 > 通用 > 启动时显示打开文件窗口」

**Comment by alejx** [comment]
I suggest to make initial window default.

**Comment by lhc70000** [comment]
@alejx After having a true initial window
