### ISSUE TITLE
[Feature Request] Adding CMD+F hotkey for fullscreen mode.

### ISSUE THREAD

**Issue by ShikiSuen** [lhc70000/iina#469]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Fullscreen get triggered while pressing CMD+F.

**Actual behavior:**
No responds while pressing CMD+F.

**How often does this happen?**
N/A

**Comment by lhc70000** [comment]
IINA currently uses `Control+Command+F`, which is a "standard" key binding in most macOS Apps. Is there any concerns?

**Comment by saagarjha** [comment]
If you're not happy with the default shortcut, you can change it in System Preferences > Keyboard > Shortcuts > App Shortcuts.

**Comment by ShikiSuen** [comment]
@lhc70000 If this is a "standard", then why QuickTime uses CMD+F?
@saagarjha IINA has built-in hotkey settings. I tried rebinding the hotkey of fullscreen from "f" to "CMD+F" (it shows "META+F") but it doesn't work.This made me posted this feature request here.

**Comment by saagarjha** [comment]
Command-F is commonly associated with "Find…", which QuickTime doesn't support (IINA doesn't appear to either, but that doesn't mean we can't associate it with anything else).

**Comment by lhc70000** [comment]
@ShikiSuen Sorry for the inconvenience. You need to **restart IINA** after changing key bindings (it only loads `input.conf` at launch), which is not documented.

I tried `Meta+F` and it works for me.

**Comment by ShikiSuen** [comment]
@lhc70000 Then I would suggest that IINA could automatically reload `input.conf` in any case that this file changes.

**Comment by lhc70000** [comment]
😞 Just tried but seems that mpv doesn't support changing `input.conf` while running.

I'm going to add help text to alert users about this.
