### ISSUE TITLE
Shouldn't the rewind button be a "roll back" button?

### ISSUE THREAD

**Issue by goodman-capu** [lhc70000/iina#470]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

When hitting the rewind (⏪)button, the video go backward fastly, just like in quicktime

**Actual behavior:**

The video go forward with a speed below 1.0x

**Comment by lhc70000** [comment]
mpv doesn't support reverse playback: https://github.com/mpv-player/mpv/issues/4000

Though it could be mimicked by sending continuous seek commands, but the performance and UX should be terrible.

**Comment by ericswpark** [comment]
Can this issue be re-opened? mpv now supports reverse playback with the following keybind command while playing:

```
KEY cycle-values play-dir - +
```
