### ISSUE TITLE
suggestion on progress bar initial position

### ISSUE THREAD

**Issue by phill84** [lhc70000/iina#471]
When IINA is launched and before playback starts, progress bar is centered and total length is a placeholder with the value 9:99:99.
It'd be more intuitive to place the progress bar at the beginning (left most position) and maybe show -:--:-- as video length.

**Comment by lhc70000** [comment]
It should only happen when it takes long time to load a video, right?

Good suggestion.

**Comment by phill84** [comment]
Indeed this is barely noticeable when playing local video files. However in my case most of my files are stored in NAS, this causes the progress bar to "jump back" to starting position for new files. :)

**Comment by alejx** [comment]
See #471. Will add in next version.
