### ISSUE TITLE
downloaded subtitle could not open. Error, Unsupported external subtitle.

### ISSUE THREAD

**Issue by freedani** [lhc70000/iina#473]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

Download the subtitle from splayer.com and add the subtitle.

**Actual behavior:**
Error, Unsupported external subtitle.

**Steps to reproduce:**

1. Open the video "[生化危机2(国英双语)].Resident.Evil.2004.BluRay.720p.x264.AC3-CMCT.mkv".
2. Click Download Subtitle or open this [subtitle](https://www.shooter.cn/api/subapi.php?fetch=MTQ4OTA2NzU1MXxFZVdndkNmTkpzR3ZBc3IxV041VWNJb0NVdFJYZ2tJbUs5RGdBVGtsVC0wem9QOEk3c083N3FDM3RkMzMxOXVnX2hCdlA2U2tRUlpFdGVmNXNMT3lMTVpBVEpPcEtGM2cxSmM0MFo3WUJVQm9MM2hlT1JPdGtqdFN6RFk2RENOVFZTZTBxZF9MTjk5NGxNUk5kSTBNVnp6RGV3Q2s3djl2STBFd0Jxc2xNYzBWNktkanNxWUo0ZnJoUnZnMlYzZ25OMERaTTBVOXhBPT18Osvk8CY59jNpi97veJrfIQAA9Kdr9w6G-dCK8GmMX1k=&nonce=ote%F8%DB%16%A7an%00%D2%F0Z%1D%0B%B7)

-  MPV does not have this problem. (don't know, I add the subtitle into MPV but no subtitle shown nor an alert)
- [x] MPlayerX does not have this problem.

**How often does this happen?**

Only happen when open some special subtitles.

(N/A for feature requests)

**Comment by lhc70000** [comment]
> MPV does not have this problem. (don't know, I add the subtitle into MPV but no subtitle shown nor an alert)

Yes, because the subtitle file is corrupted (`shooter.cn`'s fault, and I've encountered many times). mpv can't load this subtitle so it displayed nothing, and IINA just alerts you about this.

**Comment by hanfeisun** [comment]
I have encountered this issue many times..

For the "corrupted" subtitle file, VLC player can still load it and display it without any problem, while IINA complains about it and doesn't load. Is it possible to switch to the subtitle loader of VLC?

**Comment by HarukaMa** [comment]
We may need some more samples on this. Could you provide some samples on this kind of subtitles?

**Comment by hanfeisun** [comment]
Attached are two samples of subtitle.  Both can be used in VLC without any issue, but can't be loaded by IINA..
[subtitle.zip](https://github.com/lhc70000/iina/files/1253470/subtitle.zip)

**Comment by lhc70000** [comment]
These are non-standard srt files. Removing the lines started with sequence number "-1" at the start would help.

mpv uses FFmpeg's `libavformat` which seems to be sticked with the standard, and you can also try `ffprobe` to confirm.

VLC uses their own subtitle parser to add extra compatibility, but I don't think it's a good idea.

**Comment by casajake** [comment]
I'm having the same trouble with "error: unsupported external subtitle" on .srt files. I removed the sequence numbers which didn't help. I got the same error. This is for Udemy courses that I've paid for and downloaded using Udeler if that is of any help with diagnosing the problem. As previous posts say, I have no trouble playing the .mp4 files using VLC. Attached is one .srt file.

**Comment by starsyork** [comment]
Exactly same issue with Udemy download subtitle
