### ISSUE TITLE
When IINA is running in the background, the input method fails to switch

### ISSUE THREAD

**Issue by byliu** [lhc70000/iina#477]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Actual behavior:**
当IINA在后台运行时，输入法(中／英，系统自带的简体拼音和ABC输入法)无法通过caps lock按键进行正确的切换，但CTRL+Space可以正常切换

When the IINA running in the background, the input method (Chinese / English, the system comes with simplified Pinyin and ABC input method) can not be correct switched by caps lock, but CTRL+Space can switch input method correctly.

**How often does this happen?**
必现

**Comment by lhc70000** [comment]
Are you sure it happens when IINA is in background? It's still capturing keys when other Apps are active?

**Comment by byliu** [comment]
Yes, when I exit IINA, everything is ok.

**Comment by lhc70000** [comment]
这是 mpv 媒体键功能的 bug。如果你能接受，可以先禁用媒体键。

另见 #636

**Comment by alejx** [comment]
参见 #1063
