### ISSUE TITLE
IINA crops videos from the top-left instead of center

### ISSUE THREAD

**Issue by BasO** [lhc70000/iina#478]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

IINA crops videos from the center

**Actual behavior:**

IINA crops videos from the top-left

**Steps to reproduce:**

Take a regular 16:9 or 4:3 movie
[to see it crop from the top]  Video -> Crop -> 1:1
[to see it crop from the left]  Video -> Crop -> 2.39:1
Notice that it doesn't cut off space from the top and the left.

- [x] MPV does not have this problem.

**How often does this happen?**

Always.

**Comment by lhc70000** [comment]
Most filters **will not work properly** when using **hardware decoding**.

Please disable hardware decoding if you want to use functions like crop, flip, etc.
