### ISSUE TITLE
全屏播放时我这边有遇到自动息屏

### ISSUE THREAD

**Issue by forsail** [lhc70000/iina#481]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment]
Duplicate with #399.

Fixed in develop (not pushed yet).

**Comment by alejx** [comment]
Close due to duplication.
