### ISSUE TITLE
Decimal numbers in subtitle settings get rounded

### ISSUE THREAD

**Issue by oekaki** [lhc70000/iina#482]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

When using decimal numbers for font size, border size or shadow offset they get rounded, for example 2.5 becomes 3. mpv allows floating-point numbers for these settings so using an mpv config in IINA with `sub-border-size=2.5` gives the expected result of a border size of 2.5.

**Comment by lhc70000** [comment]
Fixed in `develop`.
