### ISSUE TITLE
a speed up bug

### ISSUE THREAD

**Issue by hongshu123** [lhc70000/iina#483]
issue:  I speed up the video to 2.0 , and then stop. but it's speed recovery to 1.0. is it a bug ?

**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by saagarjha** [comment]
Yes, this is a bug–check out issues #332, #403, and #442.

**Comment by alejx** [comment]
Close due to duplication.
