### ISSUE TITLE
Trackpad 动量滚动灵敏度体系/体验与 QuickTime 不一致。

### ISSUE THREAD

**Issue by ShikiSuen** [lhc70000/iina#484]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Trackpad 动量滚动灵敏度体系/体验与 QuickTime 不一致。

**Actual behavior:**
我不知道 IINA 目前这样子是太灵敏、还是「无论我双指触动 Trackpad 的初速度如何，IINA 的影片卷动速度始终是这么快」。很多时候我想定位到某个帧、都发现特别费劲，于是不得不用 Quicktime 重新抓图。

**How often does this happen?**
Always.

**Comment by xuhaoyang** [comment]
可以用< >定位

**Comment by lhc70000** [comment]
抱歉，这个基本无法解决……因为 mpv 没有提供逐帧播放的 API。有几个 workaround：

- 可以启用精确查找（Exact Seek）来获得接近 QuickTime 的体验，但是会消耗大量 CPU。
- 可以用键盘上的 <kbd>,</kbd> 和 <kbd>.</kbd> 来前进或者后退一帧，但是前进/后退后会暂停。

**Comment by ShikiSuen** [comment]
就此问题给 mpv 递交 feature request 的话，不知是否可行。

**Comment by lhc70000** [comment]
（当然可行，不过他们愿不愿意做就是另一回事了……）
