### ISSUE TITLE
Constraints Collision 

### ISSUE THREAD

**Issue by inflation** [lhc70000/iina#486]
**System and IINA version:**

- macOS 10.12.4 beta
- IINA 0.0.6 build 15

- Log:
```
2017-03-14 12:17:21.407529-0400 IINA[6393:124808] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSLayoutConstraint:0x60800009ed70 NSScrollView:0x6080001c31b0.trailing == NSView:0x6080001285c0.trailing   (active)>",
    "<NSLayoutConstraint:0x60800009f6d0 H:[NSView:0x6080001285c0]-(0)-|   (active, names: '|':NSClipView:0x1034825d0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x6080002876c0 h=-&- v=-&- H:[NSClipView:0x1034825d0]-(15)-|   (active, names: '|':NSScrollView:0x6080001c31b0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60800009f6d0 H:[NSView:0x6080001285c0]-(0)-|   (active, names: '|':NSClipView:0x1034825d0 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger
```

**Steps to reproduce:**
Build IINA develop at 3004e459ae4b35daeac3c5b792a65c9e077c51c1 and open `Preferences > Subtitles`.

**How often does this happen?**
Every time.

**Comment by saagarjha** [comment]
I can't reproduce this in the latest commit, 3004e459ae4b35daeac3c5b792a65c9e077c51c1. Would you mind trying it out?

**Comment by inflation** [comment]
The latest commit didn't change Preferences, but I give it a try. And it also fails.

**Comment by saagarjha** [comment]
Would you mind running `defaults write com.colliderli.iina NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints 1`in your Terminal and attaching a screenshot of the purple window?

**Comment by inflation** [comment]
![image](https://cloud.githubusercontent.com/assets/2375962/23962961/2e47808c-0986-11e7-8fcb-dcf8f31f0eeb.png)

**Comment by saagarjha** [comment]
This appears to appear when System Preferences > General > Show scroll bars: > Always is selected; the window can't handle any sort of resizing because it doesn't use AutoLayout. @lhc70000 thoughts?

**Comment by inflation** [comment]
If I choose `When scrolling`, the layout will be fine but the log still outputs the same information.

**Comment by lhc70000** [comment]
I tried "Always" but no warnings on my computer.

**Comment by alejx** [comment]
It seems like I don't have this problem anymore.

**Comment by inflation** [comment]
Yes, it seems to be disappeared. But still, we need a nicer way to fold the Subtitle panels.
