### ISSUE TITLE
use sub-second progress bar step size

### ISSUE THREAD

**Issue by Andeling** [lhc70000/iina#49]
The current step size of the progress bar is one second. However, it may not be good enough in the case of short videos with a total duration of only a few seconds. In that case, the indicator jumps too much each time and it is not possible to slide the progress bar to a non-integer time point.

I am working on a fix and will send a pull request after some more testing.

**Comment by lhc70000** [comment]
Thanks a lot!

I'm afraid that currently `VideoTime.swift` only works for integer seconds. So there may be a lot of works to do. Please update here if you have any problem.

**Comment by Andeling** [comment]
Luckily `time-pos` could be get as double with the higher resolution, so the fix was not complicated. I am not familiar with Swift, so I hope I did not break other things with the changes.

**Comment by Andeling** [comment]
Fixed by 63bf466.
