### ISSUE TITLE
Enhancement: Better OSD messages

### ISSUE THREAD

**Issue by adarshv90** [lhc70000/iina#490]
There should be OSD messages for all actions. Currently OSD message appears if there is a volume change. It should also appear for seek (position jumps using shortcuts), track changes (audio & sub), delays (audio & sub), video effects (brightness, contrast etc.), screenshots and any other changes. I should basically be universal

Thank you in advance

**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Comment by alejx** [comment]
See #568 .

**Comment by adarshv90** [comment]
@lhc70000, @alejx 👍
