### ISSUE TITLE
CustomSpeedTextField, CustomAudioDelayTextField and CustomSubtitleDelayTextField do not sync with their indicators when change values from text field

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#492]
**System and IINA version:**

- macOS 10.12.4 dp 6
- IINA 0.0.6

**Expected behavior:**

Textfield should always sync with the indicators.

**Actual behavior:**

Does not sync.

- [x] MPV does not have this problem.

**How often does this happen?**

Every time.

**Comment by saagarjha** [comment]
Please take a look at #430.

**Comment by lhc70000** [comment]
Is this already on `develop`? (please add "Fixed in develop" tag if so)

**Comment by saagarjha** [comment]
No, since you haven't merged #430 yet.

**Comment by alejx** [comment]
See #430 .
