### ISSUE TITLE
如果左右快进的间隔可以调整岂不是狂拽酷炫吊炸天？

### ISSUE THREAD

**Issue by yeeaahhh** [lhc70000/iina#493]
按键盘上下左右键的左键和右键的时候不是可以快进快退一小段，希望这个间隔可以调整

**Comment by lhc70000** [comment]
当然可以调整。

在 `偏好设置 > 快捷键` 中，将 `LEFT` 和 `RIGHT` 对应的命令改为想要的值即可；默认为 `seek 5`，即前进 5 秒。

默认的快捷键配置不能更改，请先点击「复制」来复制一份自己的配置。

如果需要更多设置，可以直接删除 `LEFT` 和 `RIGHT` 对应的行，然后点击加号，添加时会有向导（有中文）：

![ce28aeea-fc08-4cb2-aa07-1d7887b8b0b5](https://cloud.githubusercontent.com/assets/8478049/23985964/b2c7f3ba-0a5c-11e7-8cb0-4fd91973afea.png)

**Comment by sadaharun28** [comment]
怎么选啊(˶‾᷄ ⁻̫ ‾᷅˵)配置文件那里只有4个初始文件，都是锁着的，复制的一个排第五，然后没有什么打勾的位置，一直在那四个下面，也拖不上去..
..我是mac

2018年4月8日(日) 23:20 Collider LI <notifications@github.com>:

**Comment by lhc70000** [comment]
@sadaharun28 这就算选中了

![40ffbb14-1946-4c57-994a-dda14b56ead2](https://user-images.githubusercontent.com/8478049/38468722-8ba5dbce-3b7c-11e8-95e4-d913cdb251c6.png)

**Comment by sadaharun28** [comment]
好的，貌似成功了。但是我觉得默认值左右跳5秒有点长，调整变成3秒、结果眼看着5分35秒跳到5分26秒......但是改成1秒的话真的是就跳1秒.........为什么啊

2018年4月8日(日) 23:31 Collider LI <notifications@github.com>:

**Comment by 1c7** [comment]
### 有同样的疑问
按如上说明，设置成3秒后似乎并没有什么用。跳转的时间依然没有固定。有时候是10秒，有时候是2秒？
![image](https://user-images.githubusercontent.com/1804755/39507579-20eb40a6-4e11-11e8-9137-8aa95055e46e.png)


### 版本：1.0.0-beta1 Build 71

**Comment by lhc70000** [comment]
@1c7 @sadaharun28

默认是关键帧查找，对于比较小的视频会不精确。
如果你要精确的跳转，添加快捷键的时候选择「秒（精确）」。
请注意对于较大的视频，可能会导致跳转时比较卡。

**Comment by 1c7** [comment]
@lhc70000  好，明白了，会尝试。
没理解这个默认关键帧查找是什么意思。设置里写明是"秒"

**Comment by pengyuwei** [comment]
虽然可以设置，但是不管设置成什么数字，永远都是前后跳转30秒，是为什么呢？

**Comment by MrDXY** [comment]
挖坟了，应该得这么整：是relative+exact
<img width="548" alt="image" src="https://github.com/iina/iina/assets/18511096/0fbf0e3c-065a-4031-ab46-bd1d66478da0">
