### ISSUE TITLE
cannot playback multiple video files in separate instances concurrently

### ISSUE THREAD

**Issue by silic0ns0ul** [lhc70000/iina#505]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Expect IINA to launch a separate instance for each video file playing. Example: 1) select a video file for playback, open file launches IINA. 2) select another video to playback, open file should launch another instance of IINA and playback. (for example, to compare two video files)

**Actual behavior:**
Instead, opening another video file replaces the currently playing video file with the new file selection in the original IINA window. (thus cannot compare two video files)

**Comment by lhc70000** [comment]
Please search for existing issues first. Duplicate with #79, #209, etc.
