### ISSUE TITLE
Default screenshot folder should not be capitalized as “ScreenShots”

### ISSUE THREAD

**Issue by xhacker** [lhc70000/iina#506]
**Default screenshot folder should not be capitalized as “ScreenShots”**

*Screenshot* is one single word.

**System and IINA version:**
- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
Default screenshot folder should be called “Screenshots”

**Actual behavior:**
Default screenshot folder is called “Screenshots”
<img width="380" alt="screen shot 2017-03-21 at 4 06 31 pm" src="https://cloud.githubusercontent.com/assets/1051813/24144339/cf7bc89c-0e67-11e7-9392-7f27d6807339.png">

**Comment by alejx** [comment]
Thank you for you feedback. We have fixed it in develop branch. But you may have to migrate the stuff in the old folder into the new one next version.
