### ISSUE TITLE
[Feature request] Skip openings and endings automatically | 建议新功能：电视剧多集自动跳过片首片尾

### ISSUE THREAD

**Issue by JerrickMeng** [lhc70000/iina#510]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

电视剧多集连播时，仍需手动跳过片首片尾，这个功能很多网页上实现了，可能是人工标记的，但是有没有可能让程序扫一遍这些文件，看看那部分片首片尾是公共的，然后自动跳过

**Actual behavior:**

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by saagarjha** [comment]
This would be difficult for IINA to do on its own; it might be easier if you found a third-party script that did this and hooked it up to IINA.

**Comment by alejx** [comment]
应该是很难做到的，如果你发现了哪个本地播放器（最好是开源的）有这个功能，可以告诉我我们。

---

It looks hard to do so. If you find any local player has this function (it's better to be open source), please tell us.

**Comment by shengdie** [comment]
自动几乎是不可能的，手动倒是可以的，可以手动设置要跳过的时间段来实现，win上的PotPlayer有这个功能，可以参考一下。

**Comment by lhc70000** [comment]
我来提个现实点的方案：看一下片头片尾的时长，然后设一个快捷键向后跳转相应的时长。这样看到片头片尾出现时直接按快捷键就行了。

**Comment by lvtao-net** [comment]
如果是按当前列表来做这样的临时设置就很好了！
比如我的列表中电视剧片头1分钟，片尾50秒。 只需要将当前列表的跳过时间设置即可！

却是不知道要如何实现！！！

**Comment by ChaosDeus** [comment]
potplayer已经支持在识别章节的基础上跳过特定名称的章节了，请参考
