### ISSUE TITLE
Changed aspect ratio does not apply to PiP

### ISSUE THREAD

**Issue by blaichch** [lhc70000/iina#511]
**System and IINA version:**

- macOS 10.12.4 Beta (16E192b)
- IINA 0.0.6 Build 14

**Expected behavior:**
When changing the aspect ratio from a video in IINA it should also apply for PiP.
.
**Actual behavior:**
PiP uses the original video aspect ratio instead of the aspect ratio that has been set in IINA.

**Steps to reproduce:**
1. Open a video
2. Change aspect ratio in IINA
3. Open PiP

**How often does this happen?**
Always

![screen shot 2017-03-23 at 23 46 07](https://cloud.githubusercontent.com/assets/12624897/24273725/3ab4f3fa-1024-11e7-95fa-f630004f21f2.png)

**Comment by lhc70000** [comment]
@saagarjha Any progress?

**Comment by saagarjha** [comment]
I think I have a branch locally that has some sort of fix for this…let me see if I can clean it up. I'm not sure if I'm getting the scale correctly, though; how can I query for the value?

**Comment by lhc70000** [comment]
@saagarjha Should be `playerCore.info.displayWidth`.

**Comment by saagarjha** [comment]
I mean getting the scale.

**Comment by lhc70000** [comment]
`playerCore.info.displayWidth` / `playerCore.info.displayHeight`, if you mean the aspect ratio……
