### ISSUE TITLE
Remaining time counts negative in video controls when streaming .m3u

### ISSUE THREAD

**Issue by blaichch** [lhc70000/iina#512]
**System and IINA version:**

- macOS 10.12.4 Beta (16E192b)
- IINA 0.0.6 (Built 14)

**Expected behavior:**
I guess it shouldn't show any remaining time because I was streaming an (endless) .m3u.

**Actual behavior:**
The remaining time is negative (or inverted?).

![screen shot 2017-03-23 at 23 43 52](https://cloud.githubusercontent.com/assets/12624897/24273832/e9712b0c-1024-11e7-9bf8-96ca80dacc32.png)

**Steps to reproduce:**
Open a .m3u file.

**Comment by lhc70000** [comment]
Fixed in `develop`.
