### ISSUE TITLE
Overlapping side bar views

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#513]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.6

**Expected behavior:**

No overlap.

**Actual behavior:**

Overlap:

![screen shot 2017-03-23 at 22 01 17](https://cloud.githubusercontent.com/assets/13786931/24281257/5b751f76-1014-11e7-9d24-1a26a08dc34a.png)

**Steps to reproduce:**

1. Quickly switch between different sidebar views, such as the Quick Setting View (⌘-S) and the Playlist View (⌘-P).

- [x] MPV does not have this problem.

**How often does this happen?**

Sometimes, when you've gotten the timing right.

**Comment by alejx** [comment]
Please test after #439 is merged.

**Comment by lhc70000** [comment]
Reproduced even with #439. However it's not a critical bug so I'm not going to fix it before next release (I've been too busy recently).

But please feel free to fix if you want :D

**Comment by braineo** [comment]
It seems that the animation can be interrupted by another action which results in sidebar status not updating properly.

**Comment by lhc70000** [comment]
@braineo I read your fix. Although it should work, but I think it's not intuitive to call `hideSidebar` when the sidebar is already `.hidden`. Most of the time when `sideBarStatus` is `.hidden`, sidebar is really hidden and there's no need to hide it again.

I think a better solution is to record the animation status of the sidebar, just like what I did to OSD and on screen control. There's a enum:
```swift
enum UIAnimationState {
  case shown, hidden, willShow, willHide
}
```
in `MainWindowController`, and we have `animationState` for titlebar/OSC, and `osdAnimationState` for OSD. Perhaps you can add a `sidebarAnimationState` and do the same thing, and in `settingsButtonAction`, check the animation status like
```swift
if sidebarStatus == .hidden && sidebarAnimationState == .willHide {
  ...
}
```

What's your opinion?

**Comment by braineo** [comment]
@lhc70000 I was looking at CALayer.animation​Keys() to see if I could get status of animation but it returns nil.

If there is already a working pattern, I think it will be good to follow it and make things consistent.

**Comment by lhc70000** [comment]
@braineo So you will continue on fixing this issue?

**Comment by braineo** [comment]
Sure. Let me look into it when I am back home.
