### ISSUE TITLE
Play/pause state is not consistent with Touch Bar

### ISSUE THREAD

**Issue by AuroraWright** [lhc70000/iina#516]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6 (latest develop)

**Expected behavior:**
When you pause or resume a video on the program (with the spacebar, or any other means) the play/pause icon on the Touch Bar should change to match.

**Actual behavior:**
When you pause or resume a video on the program (with the spacebar, or any other means) the TouchBar icon doesn't change.

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**
Play video, pause on the interface. Touch Bar still shows the "pause" icon.
(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**
Always
(N/A for feature requests)

**Comment by alejx** [comment]
Duplicate with #387 .

Please use search before opening an issue.

**Comment by alejx** [comment]
Close due to duplication.
