### ISSUE TITLE
Preferred audio language doesn't save

### ISSUE THREAD

**Issue by AuroraWright** [lhc70000/iina#517]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6 (both build15 and latest develop)

**Expected behavior:**
"Preferred language" for Audio in Codec preferences should be saved and persist restarting the app

**Actual behavior:**
"Preferred language" for audio in Codec preferences isn't saved

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**
Input a language code in the "Preferred language" box, press Enter, restart the app.
(N/A for feature requests)

- [x] MPV does not have this problem.

**How often does this happen?**
Always
(N/A for feature requests)

**Comment by lhc70000** [comment]
Fixed in `develop`.
