### ISSUE TITLE
subtitles rendering error with iTunes U Stanford iOS Dev lecture video

### ISSUE THREAD

**Issue by yy0c** [lhc70000/iina#518]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
subtitles properly rendered

**Actual behavior:**
failed to render subtitles correctly
![example](http://i.imgur.com/FFek9pZ.png "subtitle rendered incorrectly")

**Steps to reproduce:**

MPV does also have this problem.

**How often does this happen?**

everytime

**Comment by saagarjha** [comment]
@lhc70000 Looks like an encoding issue?

**Comment by lhc70000** [comment]
@saagarjha No, it's the same as #391, seems to be a FFmpeg's problem.
