### ISSUE TITLE
Crash when opening URL with Chinese characters | 开带中文的链接会crash

### ISSUE THREAD

**Issue by Steve-luo** [lhc70000/iina#522]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6 (Build 14)

<br>

**Expected behavior:**

- IINA plays the video.

<br>

**Actual behavior:**

- IINA crashes.

- [Crash report (PasteBin)](http://pastebin.com/0mhZbsVF)

<br>

**Steps to reproduce:**

- Click File - Open URL...
- Input a URL with Chinese characters
- Click OK

<br>

**How often does this happen?**

- Every time.

<br>

**My suggestion**

Maybe add an UrlEncode engine to encode all URLs with Chinese characters.
After turning the original URL with Chinese characters into an encoded one, IINA is able to play the video.

**Comment by Steve-luo** [comment]
还想加一句，前几天才发现IINA，现在已经是我最喜欢的播放器了，没有之一。感谢作者的付出，希望以后能进一步完善，期待占领市场的那一天！

**Comment by lhc70000** [comment]
**It won't in 0.0.7** (hopefully will be available tomorrow).

See PR #521

**Comment by Steve-luo** [comment]
@lhc70000 Thanks.
