### ISSUE TITLE
Hope to support real-time switching of audio output channels

### ISSUE THREAD

**Issue by maboloshi** [lhc70000/iina#524]
**System and IINA version:**

- macOS 10.12.4 Beta (16E189a)
- IINA 0.0.6

**Expected behavior:**
Can support similar audio player VOX, support for real-time switching audio output channels and supporting the use of UI switch button

Not the system global settings, only within the app

**Comment by lhc70000** [comment]
What kind of audio channels are you expecting? Like 5.1 or stereo?

中文也可以。

**Comment by maboloshi** [comment]
就是支持选择音频输出的设备
如:
- 内置扬声器
- 数码输出
- 线路输出
-Boom2Device
等 在`系统偏好设置 > 声音 > 输出`

非系统全局

**Comment by lhc70000** [comment]
那这已经有了啊，菜单的 `音频 > 音频设备`
![e87c84c1-e2cf-4772-8ecc-93f63226066f](https://cloud.githubusercontent.com/assets/8478049/24354128/4e99d97e-1323-11e7-85a1-28f66bcace51.png)

**Comment by maboloshi** [comment]
哦 原来如此。非常抱歉，之前没注意到。但是，如果在主机面上添加一个 UI 按钮就更好了。
