### ISSUE TITLE
On Multi-speed playback, the video is not synchronized with the sound.|多倍速播放时音视频不同步。

### ISSUE THREAD

**Issue by mingwiki** [lhc70000/iina#528]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**
video should be synchronized with sound.
无论用几倍速视频应与声音同步。

**Actual behavior:**
The sound and video are still out of sync even after pausing at a constant speed.
即使按暂停后以常速继续播放，声音与视频依然不同步。
(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**
Play video - X32 speed - pause - play (video can not be paused in time, audio has been paused, resulting in asynchronous)
播放视频--X32倍速--暂停--播放（视频无法及时暂停，音频已经暂停，造成不同步）

(N/A for feature requests)

- [ ] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by saagarjha** [comment]
I believe this is an issue with mpv and high-speed playback. If you have Console open, mpv will complain that it can't keep the video and audio in sync.
