### ISSUE TITLE
Please add the support of bluetooth control

### ISSUE THREAD

**Issue by excelwang** [lhc70000/iina#535]
Please add the support of bluetooth control, such as play, pause, volume +, volume -, previous and next.

**Comment by lhc70000** [comment]
What bluetooth controller are you using?

**Comment by excelwang** [comment]
What I used is the _Sony MDR-1000X_ bluetooth headset.

**Comment by alejx** [comment]
I guess bluetooth would call system media key to perform action. If that is true, then this issue is a part of #451 .
