### ISSUE TITLE
给的安装包下载地址经常下载不了，可否也上传到其他地方一份呢，比如说百度网盘之类的

### ISSUE THREAD

**Issue by songtao542** [lhc70000/iina#536]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
[](https://lhc70000.github.io/iina/zh-cn/)
中文官网上会有百度云载点

**Comment by lhc70000** [comment]
https://lhc70000.github.io/iina/zh-cn/

![cbdb3afa-a6f6-469f-82d6-bd828f53859d](https://cloud.githubusercontent.com/assets/8478049/24458401/67c5dd68-14cb-11e7-8089-e235f6ec6d0c.png)

**Comment by AndyChen2005121** [comment]
呃呃，你可以去我们的下载站，有 IINA 的下载链接（满速），不定期更新：hhkx.tk
