### ISSUE TITLE
Pinch gesture should be disabled in fullscreen

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#540]
**System and IINA version:**

- macOS 10.12.5 beta
- IINA 0.0.7

**Expected behavior:**

Video size should not be changed when the gesture is detected in fullscreen

**Actual behavior:**

Video size changes so that window size is no more sync with video size.

**Steps to reproduce:**
- Open a video and go into fullscreen mode.
- Use gesture to try to change the video size.

**How often does this happen?**
Every time.

**Comment by Steve-luo** [comment]
Actually I'd love to have the ability to use pinch gesture in fullscreen to zoom in/out the video. Maybe add as an new feature?
