### ISSUE TITLE
Seeking with arrow keys doesn't work properly

### ISSUE THREAD

**Issue by alashow** [lhc70000/iina#544]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
Seek 5 seconds back/forward when arrow keys clicked (or as defined in keybindings).

**Actual behavior:**
It seeks 10 seconds, or sometimes 6 or just a random number.

**Steps to reproduce:**
Open a video, press left or right arrow keys.

**How often does this happen?**
Always

[MPV log](https://gist.github.com/anonymous/f697285e79fa2f8dd1dfe081fb05ce98)

**Comment by lhc70000** [comment]
By default, relative seeking will seek to the most close keyframe, which is inaccurate, especially when your video file contains very little keyframes (in some cases there's only one key frame in several seconds). Please change your key bindings to "exact" like this:

![e6e95b86-0db9-49f8-ab29-7fb37ae8a086](https://cloud.githubusercontent.com/assets/8478049/24674173/24eb6c1a-19ad-11e7-8de2-6b1732e8fd25.png)

I'm considering making this as default in next version.

**Comment by alashow** [comment]
It seeks exactly n seconds now. I didn't know about that option.

Thanks!

**Comment by zofari** [comment]
> By default, relative seeking will seek to the most close keyframe, which is inaccurate, especially when your video file contains very little keyframes (in some cases there's only one key frame in several seconds). Please change your key bindings to "exact" like this:
> 
> ![e6e95b86-0db9-49f8-ab29-7fb37ae8a086](https://cloud.githubusercontent.com/assets/8478049/24674173/24eb6c1a-19ad-11e7-8de2-6b1732e8fd25.png)
> 
> I'm considering making this as default in next version.

Why is keyframe approach made the default by the way? Normal users like me likely aren't aware of keyframes, and would expect the _exact_ behavior which is more intuitive.
