### ISSUE TITLE
Add Blu-ray / DVD support

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#55]
Support for playing Blu-ray / DVD, from a real disc or ISO image

**Comment by alanzchen** [comment]
https://github.com/mpv-player/mpv/issues/226

mpv seems to have solved this issue?

**Comment by HarukaMa** [comment]
Latest version has libbluray built in, so we can directly open BDMV folder now.

No support for menu and other advanced features though.

**Comment by fabi94music** [comment]
http://macblurayplayer.com/macgo-mac-bluray-menu-player-pro.htm is awesome. 
If only IINA and Blu-Ray Player Pro could be one single app :)

**Comment by ErikMinekus** [comment]
Still can't play DVD ISOs. Tried opening the ISO directly, as well as mounting the ISO and opening the VIDEO_TS folder, both say "error, nothing to open".
