### ISSUE TITLE
How to make the window of iina on the top all the time ?

### ISSUE THREAD

**Issue by livc** [lhc70000/iina#551]

**Comment by lhc70000** [comment]
`Preference > UI > Window > Always float on top while playing`.

It will work for all windows opened later.

**Comment by livc** [comment]
@lhc70000  Thanks，but it seems that there is a bug. When not playing, the window is still float.

**Comment by alejx** [comment]
@livc This is intend to be for now. We will fix it later.
Duplicate with #234 .
