### ISSUE TITLE
Playlist sidebar showing / missing multiple entries

### ISSUE THREAD

**Issue by Windi13** [lhc70000/iina#555]
The sidebar which displays playlists and chapters for the current video, seems to be getting the playlist videos by just taking the videos in the same directory as the original file. However some of those files are missing / are shown multiple times.

<img width="245" alt="screen shot 2017-04-03 at 21 57 39" src="https://cloud.githubusercontent.com/assets/14923550/24629234/99bef520-18b8-11e7-810b-1eaf1f57b35d.png">

**Comment by alejx** [comment]
Can you provide some steps about how did you meet this problem?

**Comment by saagarjha** [comment]
Were you able to resolve the issue?

**Comment by Windi13** [comment]
Tested it extensively. Couldn't reproduce the issue.

**Comment by lhc70000** [comment]
It's one of the various problems caused by mpv's `autoload.lua` (should happen when you change the playlist order and play next file in the playlist). I'll work on a fix asap.
