### ISSUE TITLE
打开IINA的时候，切换输入法

### ISSUE THREAD

**Issue by wangcongyi** [lhc70000/iina#557]
**System and IINA version:**
- macOS 10.12.4（中国大陆）
- IINA 0.0.7

打开IINA  无法顺利的切换中英文

看视频的时候，和朋友们聊天 使用中／英切换的时候，
有时候会切换成大写字母而且顶部状态栏 输入法icon不会变动
关闭IINA程序  icon切换正常；输入法切换正常

**Comment by alejx** [comment]
Duplicate with #477 .
