### ISSUE TITLE
Can't play a 4k video whereas it plays fine with Mplayer

### ISSUE THREAD

**Issue by vincent-inspectionapps** [lhc70000/iina#558]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

**Actual behavior:**
Not playing a 4k video I downliaded from https://vimeo.com/190218296

Tried Mplayer, works fine.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by Steve-luo** [comment]
I downloaded the exact 4K video and IINA works fine. 
![IINA Plays 4K Vimeo Video](https://cloud.githubusercontent.com/assets/8736917/24656942/063b2f70-1977-11e7-90d1-8350866b201c.png)

**Comment by bingo619** [comment]
Weired, it works fine for me now.
