### ISSUE TITLE
Enhance apple remote support

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#56]

**Comment by mhampl** [comment]
This feature is crucial to me. It's the only reason I won't use IINA for now.

**Comment by lhc70000** [comment]
@mhampl 
You may try:
- set `input-appleremote` to `yes` in `Preference > Advanced > Extra mpv options`
- use "MPV Default" key binding configuration.
(both changes require restarting IINA)

Theoretically it should work, but I don't have an apple remote so not able to test.

Please try the above solution, if it not work, I'm going to buy an apple remote tonight for test 😉

**Comment by mhampl** [comment]
Setting `input-appleremote` to `yes` did the trick. Changing the key bindings doesn't seem necessary. Start/stop works, up/down changes the volume and left/right triggers seek.

Excellent, I think I'll use it as my default video player from now on 👍 

There are a few details that I would love to see: VLC displays the elapsed time and total duration of the video when you press the "menu" button on the apple remote. I've now downloaded the latest build of mpv for OS X (by stolendata). mpv does display a progression bar, elapsed time and total duration (can also be triggered by pressing o) when I press the remote's "menu" button. Can you make this work in IINA as well?

Also mpv mutes the video at a long press of the "menu" button. That's very handy as well. 

Something that mpv and IINA don't seem to do: I would expect that if you hold one of the left/right buttons that the video would wind back/forward until the button is released. In mpv and IINA it jumps only once with each button press at the moment. 

But let me say it again: The app looks very promising. Thanks for the quick reply 👍

**Comment by megadr01d** [comment]
> set `input-appleremote` to `yes` in `Preference > Advanced > Extra mpv options`

Is this the Apple Remote support mentioned in the latest v0.0.7 build16 changelog or does it have a separate checkbox?

> mpv does display a progression bar, elapsed time and total duration (can also be triggered by pressing o) when I press the remote's "menu" button. Can you make this work in IINA as well?

> Also mpv mutes the video at a long press of the "menu" button. That's very handy as well.

>  I would expect that if you hold one of the left/right buttons that the video would wind back/forward until the button is released.

In case this enhancement will support remote button options (like the current mouse buttons), and considering buttons can register presses and long presses, here are some more action suggestions for the future:

- Toggle fullscreen
- Previous/next file in folder/playlist
- Previous/next subtitle
- Previous/next audio track

**Comment by lhc70000** [comment]
> Is this the official Apple Remote support mentioned in the latest v0.0.7 build16 changelog or does it have a separate checkbox?

A checkbox had been added under "Key bindings" tab.

> here are some more action suggestions for the future:

Adding these to GUI takes time, but you can set them in key bindings for now (check "show raw value" and change the key/values, or edit the .conf file directly).

All possible key names:
```
AR_PLAY
AR_PLAY_HOLD
AR_CENTER
AR_CENTER_HOLD
AR_NEXT
AR_NEXT_HOLD
AR_PREV
AR_PREV_HOLD
AR_MENU
AR_MENU_HOLD
AR_VUP
AR_VUP_HOLD
AR_VDOWN
AR_VDOWN_HOLD
```

MPV command examples:

- Toggle fullscreen: `cycle fullscreen`
- Previous/next file: `playlist-prev``playlist-next`
- Cycle subtitles: `cycle sub`
- Cycle audio track: `cycle audio`, or `add audio 1`/`add audio -1` for prev/next

**Comment by megadr01d** [comment]
@lhc70000 Thanks for the tips, really appreciate it. I think this is already pretty flexible as it is.
