### ISSUE TITLE
Unable to play online video file.

### ISSUE THREAD

**Issue by tywtyw2002** [lhc70000/iina#560]
v0.0.7 build16

I saw new release IINA update the UI for play online video file. However, it seems to broke something. I unable to play the online video file such as `http://*****/******/%E8%B6%8A%E7%8B%B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mkv`.

![I](https://i.v2ex.co/11ozbI3ml.png)

Tested: This url is able to play by MplayerX and old version IINA (previous release).

**Comment by lhc70000** [comment]
There shouldn't be much difference……

Did you included some spaces in the pasted url accidentally?

**Comment by tywtyw2002** [comment]
Yes, Confirmed this is an issue.

try it

```
# generate 30s video from ffmpeg
$ ffmpeg -f lavfi -i rgbtestsrc -pix_fmt yuv420p -t 30 越狱.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs人人影视.mp4
# start local http server
$ python -m SimpleHTTPServer 8080
```

Open browser, copy video url then paste it to IINA.

**Comment by tywtyw2002** [comment]
The http log shows the problem is the IINA do additional url_encode to the URL.

The url should be `/%E8%B6%8A%E7%8B%B1.Prison.Break`, but IINA's requests is `/%25E8%25B6%258A%25E7%258B%25B1.Prison.Break`.

```
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [05/Apr/2017 11:35:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Apr/2017 11:35:53] code 404, message File not found
127.0.0.1 - - [05/Apr/2017 11:35:53] "HEAD /%25E8%25B6%258A%25E7%258B%25B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%25E4%25BA%25BA%25E4%25BA%25BA%25E5%25BD%25B1%25E8%25A7%2586.mp4 HTTP/1.1" 404 -
127.0.0.1 - - [05/Apr/2017 11:35:53] code 404, message File not found
127.0.0.1 - - [05/Apr/2017 11:35:53] "GET /%25E8%25B6%258A%25E7%258B%25B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%25E4%25BA%25BA%25E4%25BA%25BA%25E5%25BD%25B1%25E8%25A7%2586.mp4 HTTP/1.1" 404 -
127.0.0.1 - - [05/Apr/2017 11:35:53] code 404, message File not found
127.0.0.1 - - [05/Apr/2017 11:35:53] "GET /%25E8%25B6%258A%25E7%258B%25B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%25E4%25BA%25BA%25E4%25BA%25BA%25E5%25BD%25B1%25E8%25A7%2586.mp4 HTTP/1.1" 404 -
127.0.0.1 - - [05/Apr/2017 11:36:25] "GET /%E8%B6%8A%E7%8B%B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [05/Apr/2017 11:36:26] "GET /%E8%B6%8A%E7%8B%B1.Prison.Break.S01E01.Chi_Eng.BDrip.AC3.1024X576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mp4 HTTP/1.1" 200 -
```

**Comment by tywtyw2002** [comment]
I am 90% believe this commit broken the play video from URL.

https://github.com/lhc70000/iina/commit/f886095a60fa4e1e06b322dda7827f8c1efbd5e4

**Comment by saagarjha** [comment]
@tywtyw2002 I'll up that confidence to 95% 😄 
@lhc70000 I really think the best thing to do here is to have the user percent encode the URL themselves, since doing so in a legal way is non-trivial.
