### ISSUE TITLE
Progress bar seek stutters on single click

### ISSUE THREAD

**Issue by lunixbochs** [lhc70000/iina#563]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

Clicking the video progress bar to seek should only seek on mouse down or drag, not on mouse up. A single click without dragging should not seek twice or stutter.

Alternate UX could also solve this, such as the video pausing until mouse release, or thumbnail-based seek-on-release (which wouldn't work well on unbuffered networked content).

**Actual behavior:**

When clicking the progress bar slider to seek a video, it seeks on mouse down, then on mouse up. This will cause a stutter on every click as a few frames are played before the mouse up triggers. If this cannot be reproduced, wait longer between the mouse down and mouse up.

**Comment by saagarjha** [comment]
QuickTime pauses while the mouse button is held down, which I think makes more sense. @lhc70000 What do you think?

**Comment by lhc70000** [comment]
Fixed in 0.0.12.
