### ISSUE TITLE
Continue playing audio-only files after closing player window

### ISSUE THREAD

**Issue by shengdie** [lhc70000/iina#565]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
If the user is playing an audio-only file (music), don't stop or pause after closing player window.

**Actual behavior:**
Will stop if the player window is closed.

**Comment by saagarjha** [comment]
I'd actually argue against this feature, since it makes it impossible to control audio playback after the window is closed. If you want the controls out of the way, just minimize or hide IINA.

**Comment by shengdie** [comment]
You don't always need control when playing music, and you can use Media
buttons to control playback.

2017年4月10日 下午9:11，"Saagar Jha" <notifications@github.com>写道：

**Comment by saagarjha** [comment]
How do you plan to stop playing the music?

**Comment by shengdie** [comment]
So how do you stop when you use iTunes? When listening music, you just need
open the window in the beginning and in the end. You can control the
playback using media buttons. Keeping the window open will obviously use
more system resources, like memory, cpu...
You don't need such feature does not mean others don't need either.

2017-04-11 0:22 GMT-04:00 Saagar Jha <notifications@github.com>:

**Comment by alejx** [comment]
@shengdie  iTunes is a library manager, whereas IINA is a pure media player. You can try QuickTime player for reference. If you are really annoyed at the IINA window, just press cmd+h and the window will hide.
