### ISSUE TITLE
Deprecated API Usage issue

### ISSUE THREAD

**Issue by FyhSky** [lhc70000/iina#567]
Whether app or reference libraries  use deprecated api such as QuickTime or QTKit APIs

**Comment by saagarjha** [comment]
Are you asking if IINA uses deprecated APIs?

**Comment by alejx** [comment]
IINA does not use QTKit although it kind of mimics QuickTime's look.

**Comment by FyhSky** [comment]
I submit app based on inna, but refused by apple.
Reason as follows:

Dear developer,

We have discovered one or more issues with your recent delivery for "xxxxxx". To process your delivery, the following issues must be corrected:

Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

**Comment by lhc70000** [comment]
Please note that you **will violate IINA's GPLv3 license** if you publish any App based on it to Mac AppStore. 

**DON'T DO THIS.**

IINA doesn't use any QT related API, but it uses some private APIs that shouldn't let you pass the review.

**Comment by FyhSky** [comment]
Thank you

**Comment by HarukaMa** [comment]
Beside the issue itself, we are glad that someone would have a project based on IINA. We would like to know more about your project, and may put up a showcase for any projects based on our app.

However, please understand that IINA is not in a stable state right now, and may have some bugs or would even crash on everyday use.

Also please respect the GPLv3 and remember to open source your project as well.

Best wishes.
