### ISSUE TITLE
Better handling OSD

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#569]
There's an old problem existing from 0.0.1: when to display OSD. As currently an OSD will be displayed once the corresponding mpv property changed, IINA actually displays many unneeded OSD messages, like:

A. **"Resume"** on video start
B. **"Contrast: 0"** etc. on video start (the property actually didn't change)
C. **"Pause"** when started seek by scrolling, and **"Resume"** when finished
D. **"Sub switched"** immediately after "Sub downloaded" (and will overwrite "Sub downloaded")

---

The ideal solution should only display "useful" OSD messages. So here's my proposed solution:

1. **Parse user's `input.conf` and handle it manually.** Fixes situation A and C. Now IINA just _sends mpv key events_ to mpv and let mpv handle the key bindings, which leads to at least following problems:

    - IINA will capture all key events including caps lock, so users may fail to switch input method (#477, #132, etc.)
    - There's no way to check whether user run some commands like screenshot, therefore no OSD for them.
    - User must restart the App to make new key bindings work.
    - There's no way to set key bindings for IINA's native features, like entering PIP.

    These can be solved by checking the _corresponding mpv commands_ in advance, handle them and send them directly to mpv. Additionally by extending mpv's syntax, we may support binding keys to IINA's features like
    ```
    #@iina CTRL+META+p set pip yes
    ```

    Shortcomings: 
    - Unable to handle key sequences (like `a-b-c show-text`). Workarounds are possible though.
    - Untidy solution.

2. **Cache more mpv properties, check whether they actually changed on notification**. Fixes situation B. As far as I know mpv doesn't provide old values in the event data, so we must record them.

3. For situation D (and probably C), I can't think of any elegant solution. What I'm planning to do is:
    - When there's no need to display an OSD, record the OSD type or other info and add it into a "temporally muted OSD" queue
    - Before displaying OSD, check whether it's in the queue; if so, doesn't display the OSD and remove the it from the queue
    - If unused, the added info will be cleared automatically after like 100ms.

@saagarjha @HarukaMa @alejx @inflation please leave your options. Any other suggestions are also welcomed.

**Comment by alejx** [comment]
A question about #477 , why IINA captures caps lock even if it is not the key window?

**Comment by saagarjha** [comment]
@lhc70000 Another possible approach is offering to "import" a user's MPV configuation during onboarding.
