### ISSUE TITLE
Running on 10.10.5 failed.

### ISSUE THREAD

**Issue by sola1tmy** [lhc70000/iina#57]
Said in QQ group yesterday, create new issue here as note.
Below is error message.

Process:               IINA [1069]
Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [1069]
User ID:               501

Date/Time:             2017-01-06 20:16:10.803 +0800
OS Version:            Mac OS X 10.10.5 (14F2109)
Report Version:        11
Anonymous UUID:        87CC4512-7FD3-F158-F106-A19F00D3E1FC

Sleep/Wake UUID:       218FDBE8-1640-4FF6-9D7C-F3CCB9279A1C

Time Awake Since Boot: 5700 seconds
Time Since Wake:       2400 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libmpv.1.23.0.dylib
  Referenced from: /Applications/IINA.app/Contents/MacOS/IINA
  Reason: no suitable image found.  Did find:
	/Applications/IINA.app/Contents/MacOS/../Frameworks/libmpv.1.23.0.dylib: code signature invalid for '/Applications/IINA.app/Contents/MacOS/../Frameworks/libmpv.1.23.0.dylib'

	/Applications/IINA.app/Contents/MacOS/../Frameworks/libmpv.1.23.0.dylib: code signature invalid for '/Applications/IINA.app/Contents/MacOS/../Frameworks/libmpv.1.23.0.dylib'

Binary Images:
    0x7fff6cb17000 -     0x7fff6cb4d92f  dyld (353.2.4) <708E385E-50C6-32A3-983C-42E97BEE4346> /usr/lib/dyld

Model: MacBookPro11,2, BootROM MBP112.0138.B18, 4 processors, Intel Core i7, 2 GHz, 8 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f4 17916, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by xowenx** [comment]
i have the same issue on my MacBook Pro running MacOS 10.10.5

**Comment by cloudbring** [comment]
Same here, getting it too on my MBP running Yosemite 10.10.5

**Comment by Miserlou** [comment]
+1

**Comment by HarukaMa** [comment]
This seems like a 10.10.5 specific bug where OS X requires all dylibs to be signed as well. All 10.10.5 users should be affected.

Maybe Apple wanted to mitigate a security issue at that time...

**Comment by lhc70000** [comment]
We will postpone this fix to 0.0.4 due to some unexpected issue.

**Comment by lhc70000** [comment]
0.0.4 should support 10.10 now.
