### ISSUE TITLE
A particular video stops playing at a certain point. No problem with the file as it plays on other players.

### ISSUE THREAD

**Issue by 5amar31** [lhc70000/iina#577]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

Not able to go past 3:35 on this particular video. The video just stops playing & "pauses" at that point & if I click the play button it restarts from 0:00. Even scrolling further than that time doesn't work.
No crash report too.
Details about the file : 
For video -
.mkv extension
x265 HEVC Profile Main 10
Frame rate - 23.97602
Format - Matroska / WebM
Resolution - 1912 X 1072
Encoding SW - libebml v1.3.4 + libmatroska v1.4.5

For Audio -
Codec - AAC
Profile HE-AAC
Sample rate - 48000Hz
5.1 Channel

Just started using this player yesterday so please be polite if I missed something or this is a known issue.

**Comment by saagarjha** [comment]
Could you try using another player, like VLC, and seeing if it has the same behavior? It's possible that your video file is malformed or corrupted.

**Comment by 5amar31** [comment]
Read the title again.

**Comment by lhc70000** [comment]
Although I'm not sure, it should be mpv's problem since IINA doesn't handle the decoding part directly.

Could you try mpv and check whether it works?
