### ISSUE TITLE
Support launching from terminal

### ISSUE THREAD

**Issue by ddqp** [lhc70000/iina#58]
和MPV一样播放流媒体，例如：

you-get -p mpv url

**Comment by lhc70000** [comment]
Good point.

**Comment by Andeling** [comment]
I tried to open through terminal with `open -b com.colliderli.iina <file>` and the application crashed. If `open` is supported, the feature could be implemented with a shell script.

**Comment by tombonez** [comment]
+1 here!

I'd love to use [Livestreamer](http://docs.livestreamer.io/) with IINA, (which already supports MPV).

Hopefully IINA also supports HTTP, RTMP and HLS too.

**Comment by SxDx** [comment]
Are there any news on command line support?

**Comment by ddqp** [comment]
news?

**Comment by alejx** [comment]
See #1181.
