### ISSUE TITLE
IINA cant support .csf video , I want to know whether we can solve it.

### ISSUE THREAD

**Issue by Cong222** [lhc70000/iina#582]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

**Actual behavior:**

- Crash report:
```
IINA cant support .csf video
```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
I couldn't find any info on "csf video". Could you provide a sample file?

**Comment by Cong222** [comment]
I just send an email to your gmail lhc199652@gmail.com with an .csf sample file, check out your gmail.

**Comment by saagarjha** [comment]
If I'm not mistaken, CSF is an [image format](https://en.wikipedia.org/wiki/Content_Sealed_Format), is it not?

**Comment by megadr01d** [comment]
The `csf` is associated with 4 file types (including Content Sealed Format, as @saagarjha points out), none of which is video. Maybe the OP means `asf` (Windows Media Video).

https://fileinfo.com/extension/csf
https://en.wikipedia.org/wiki/Video_file_format
https://en.wikipedia.org/wiki/Comparison_of_video_container_formats

**Comment by lhc70000** [comment]
I did some detailed search…… and it's a private file format developed by a Chinese company more than a decade ago. So IINA, or mpv, will never provide support for it.

Wiki link https://zh.wikipedia.org/wiki/CSF格式 (Chinese only)
