### ISSUE TITLE
Can't change the maximum volume to more than 100% when using scrolling.

### ISSUE THREAD

**Issue by volcbs** [lhc70000/iina#592]
**System and IINA version:**
- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
IINA can reach the maximum volume to more than 100 with scrolling.

**Actual behavior:**
It stopped at 100 when use scrolling. Like this video related https://puu.sh/vvK7V.mov
But it's fine when using keyboard.

- MPV log:
https://puu.sh/vvKrv.log

**Comment by lhc70000** [comment]
It's intended since scrolling could be too sensitive.

**Comment by volcbs** [comment]
Ah is that so?
Thanks for the confirmation

**Comment by HarukaMa** [comment]
@volcbs please don't post long logs in issue body, as they make emails horrible to read through on phones. Try use some paste or file sharing services instead.

**Comment by volcbs** [comment]
@HarukaMa Well yeah, I'm aware of it, so that's why I edited and uploaded it on puush instead.
