### ISSUE TITLE
The version download from brew cask is v003, plz update!

### ISSUE THREAD

**Issue by NathanZhengNaixian** [lhc70000/iina#594]
官网的brewcask 下载的版本是0.03， 请更新

**Comment by lhc70000** [comment]
Please run `brew update` first.

**Comment by NathanZhengNaixian** [comment]
then nothing happen 
![2017-04-27 21 12 42](https://cloud.githubusercontent.com/assets/22364863/25497763/4e40bbcc-2b8e-11e7-8676-474865bddb19.png)

**Comment by lhc70000** [comment]
@NathanZhengNaixian Please be patient. Seems that you haven't run this for a long time so have to wait for a while.

**Comment by alejx** [comment]
@NathanZhengNaixian `brew update` is in progress. However, GitHub has been somehow blocked in China and Homebrew uses GitHub to get updates.

So that you can ether use VPN or socks/http proxy to accelerate the connection.

**Comment by NathanZhengNaixian** [comment]
i not in china, but still thanks, 吗的英文不累吗， 一般要等多久啊

**Comment by alejx** [comment]
不在中国的话你应该是第一次运行 update 吧。放那不用管就行了

**Comment by lhc70000** [comment]
用英文可以方便有同样问题的用户。如果你觉得累就算了 233

**Comment by NathanZhengNaixian** [comment]
好的？作者有两个马甲吗， 回复的好勤啊 _:(´°ω°`」 ∠):_

**Comment by HarukaMa** [comment]
As the issue is quite trivial and due to inactivity I'm closing this.

Please reopen it if you have more questions.

**Comment by herozhang** [comment]
现在brew cask上还是0.10，请升级到0.11

**Comment by Miigon** [comment]
@herozhang 请运行`brew update`，brew cask上已升级0.0.11
