### ISSUE TITLE
click to drag does not work

### ISSUE THREAD

**Issue by lucid-dreams** [lhc70000/iina#599]
Click to drag only works when the player window already has focus, otherwise it just gets focus.
Whereas MPV does not need focus to be dragged.

**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7 and current CVS

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

always, it kind of negates on-top functionality.

**Comment by edrozenberg** [comment]
I see various pull requests linked but as of 1.0.7-beta1 Build 115 this issue still exists. If a window is not active, I cannot drag it by the content area, until I first click to activate the window. So requires 2 clicks to drag an inactive window by the content area.
