### ISSUE TITLE
Allow volume larger than 100% | 允许 100% 以上音量

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#6]
from V2EX @smallaccount

**Comment by LEMONed** [comment]
非常有必要。当前版本播放 DTS 5.1ch 时虽然能自动 downmix 到 2ch（假设系统是 2ch），但应该还是存在一些问题，更别说音量出奇的小。

**Comment by megadr01d** [comment]
400% seems to be a common maximum choice (VLC, Vox, Movist). Useful for MacBook Pros poor speakers.

**Comment by LeoNatan** [comment]
Please add the option to clip the sound level to 100% for those of us that care about sound quality. This should be optional and disabled by default.

**Comment by megadr01d** [comment]
> This should be optional and disabled by default.

If implemented like in other players, it's a question of providing a slider or dropdown menu with options ranging from 100% to whatever%. Of course it's optional and there's no disabled state. It defaults to 100% on IINA's first run and the user can switch to whatever% if desired, in preferences.

**Comment by LeoNatan** [comment]
Since it is impossible to disable gestures, it is very easy to swipe by mistake and go over 100%. On other players, it is possible to disable swipe gestures and this becomes less of a problem. It also kills audio quality. If this is a quality player, let quality be first before gimmicks.

**Comment by megadr01d** [comment]
I agree with your [suggestion](https://github.com/lhc70000/iina/issues/150) about disabling gestures but I don't think you're reading before replying. The **maximum volume percentage is set in Preferences**. If yours is set to 100%, you can never go beyond that, by mistake or not, **unless you allow it in Preferences**.

Being flexible enough to provide a decent volume output for users who can't afford a decent stereo system and studio monitors doesn't mean it's not a quality player.  VLC, Vox and Movist are certainly not ordinary players.

**Comment by lhc70000** [comment]
It's possible to set volume up to 130 using keyboard (up / down arrow key).

And you may set a higher value by adding a `max-volume` extra option, in current version.

**Comment by lhc70000** [comment]
Improved in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

You can set maximum volume in Preference, and use <kbd>↑</kbd> to set volume larger than 100%.

**Comment by Imparium** [comment]
Any update on this?
