### ISSUE TITLE
Disable Automatic Check for Update

### ISSUE THREAD

**Issue by freediverx** [lhc70000/iina#601]
**System and IINA version:**

- macOS 10.12.5 Beta
- IINA 0.0.7

**Expected behavior:**

IINA should use a reliable server to check for software updates, both automatically and on demand. Until such a server is set up (perhaps in beta), it would be nice to disable the automatic software update check that runs every time INNA is launched.

**Actual behavior:**

Every time IINA is launched, it attempts to check for updates. Since IINA currently uses the GitHub API for this purpose, and since the API has a limitation of 60 request/hr, the request is usually blocked, resulting in a dialog box displaying an error message. This is a nuisance that detracts from the user experience and causes confusion for some users.

http://i.imgur.com/3MAY4e7.png

- Crash report:

N/A

**Steps to reproduce:**

N/A. See above.

**How often does this happen?**

Seemingly always.

**Comment by alejx** [comment]
See b468afe. This commit make IINA check for update every 6 hours.
