### ISSUE TITLE
Time goes to minus value when using trackpad rewinding

### ISSUE THREAD

**Issue by goodman-capu** [lhc70000/iina#608]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

The time stops at 00:00 when using trackpad to perform rewind action

**Actual behavior:**

The time flashes and goes to minus value and then stops at zero

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
Rewind the video using trackpad gesture

**How often does this happen?**

Always

**Comment by lhc70000** [comment]
Should be fixed already in develop branch.

**Comment by alejx** [comment]
Fixed in 0.0.8.
