### ISSUE TITLE
附字幕位置调节

### ISSUE THREAD

**Issue by piaomiaoguying** [lhc70000/iina#610]
一般来讲，主字幕和附字幕都是在底部的，放在一起比较方便中英文对照，建议像potplayer那种做成主副字幕都可以自由调节位置的形式

**Comment by lhc70000** [comment]
mpv 不支持副字幕的设定。副字幕只能被显示为纯文本并固定在屏幕上方。

**Comment by colachang** [comment]
如果第二字幕可以固定在屏幕下方，只要主字幕可以調整位置是否就可以了？

**Comment by vlalamoon** [comment]
所以现在副字幕的位置可以调节了吗？朋友们

**Comment by nonusx** [comment]
> potplayer

不能

**Comment by aobo711** [comment]
这种基本的功能就这么随意关了，这认真做播放器的吗？

**Comment by qq99275** [comment]
2025年了，依旧不能，多希望可以把副字幕移动到屏幕下方

**Comment by frank-tseng** [comment]
> 2025年了，依旧不能，多希望可以把副字幕移动到屏幕下方

目前唯一支持第二字幕位置调节的，就只有nplayer，但是他是手机端播放器，好在mac端可以使用手机端端nplayer。

我找了很多年，这是mac ios上唯一一款能实现该功能的软件

**Comment by qq99275** [comment]
mac端有一个movist可以同时选中两个字幕以上，且都在下方

**Comment by frank-tseng** [comment]
> mac端有一个movist可以同时选中两个字幕以上，且都在下方

感谢 大佬，我去试试
