### ISSUE TITLE
Can not change input source by press <caps lock> when iina is workding

### ISSUE THREAD

**Issue by cbdyzj** [lhc70000/iina#615]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by megadr01d** [comment]
Dupe of https://github.com/lhc70000/iina/issues/132 and https://github.com/lhc70000/iina/issues/477.

**Comment by alejx** [comment]
See #477 .
