### ISSUE TITLE
Crash when press "CMD+."

### ISSUE THREAD

**Issue by excelwang** [lhc70000/iina#617]
When "CMD+." are pressed, IINA crashes.

**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Steps to reproduce:**
Case 1:
1. Open a video file
2. Press "CMD+."
Then the IINA exit.

Case 2:
1. Open a video file
2. Open the preferences panel
3. Press "CMD+."
Then the video window is closed, while the preferences panel is still open.

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
It doesn't crash, just closed the video window as the expect behavior.
