### ISSUE TITLE
mpv style shortcuts doesn't work

### ISSUE THREAD

**Issue by troyliu0105** [lhc70000/iina#618]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Steps to reproduce:**
For example, I set some commands like 'q' for 'quit_watch_later'. But it doesn't work.
And previous version just works like a charm

actually after upgrade to 0.0.8, I didn't change any settings.
and here is some configurations:

![2017-05-04 9 03 08](https://cloud.githubusercontent.com/assets/5518286/25704729/3bbc5f04-310d-11e7-947c-1aa2390fbd8e.png)
![2017-05-04 9 12 45](https://cloud.githubusercontent.com/assets/5518286/25705046/72d68db0-310e-11e7-8aab-1e70c337924e.png)
![image](https://cloud.githubusercontent.com/assets/5518286/25705110/ab33fd82-310e-11e7-8de9-64b04d68d52e.png)

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
Seems that the new system cannot handle `{encode} quit 4` properly, and it overrides the above line.

For a workaround, please duplicate the configuration and delete the line `{encode} quit 4` for `q`.

**Comment by troyliu0105** [comment]
@lhc70000 Thanks for reply.
I checked the log, found that iina doesn't load input config at ~/.config/mpv/input.conf
so I just changed the config that iina generated.
And you guys would better directly use text editor to do it...
When I use iina UI to change it, any invalid input will make a endless crash...==

I think it's better to add a shortcuts command checker to avoid crash..  😃

**Comment by lhc70000** [comment]
You may enable the "**Show raw value**" checkbox at right bottom and double click a row to edit the key codes and commands directly; or click the "Reveal in Finder" button and open the file using a text editor.

Could you also show me how to reproduce the crash when editing key bindings?

**Comment by troyliu0105** [comment]
1. checked **Show raw value**
2. input "quit_watch_later" for 'q'
3. enter... and what i inputed just disapper... Try many times, same problem
4. unchecked **Show raw value**, and endless crash happens

Only I can do is directly change shortcut config file to correct and it fixes crash
