### ISSUE TITLE
Behavior after finishing playing the entire video

### ISSUE THREAD

**Issue by csujedihy** [lhc70000/iina#62]
After finish playing the entire video, I cannot re-play it by clicking the play button and the window size remains the same size. TouchBar cannot control the video at this moment as well.

**Comment by Andeling** [comment]
It seems that mpv closed the video after it is finished... Maybe `keep-open=yes` is necessary to pause the video at the last frame. My concern is how to replay from the beginning when space bar is pressed at the end (`eof-reached`).

**Comment by lhc70000** [comment]
This will be fixed in #112 using @Andeling 's suggestion. (Wow, didn't aware that you mentioned `eof-reached` before......)
