### ISSUE TITLE
Open latest played files from the "Open Recent" list

### ISSUE THREAD

**Issue by excelwang** [lhc70000/iina#623]
Literally, the "Open Recent" list should consist of latest played video files, no matter the file is manually opened or automatically opened from a playlist.

**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Expected behavior:**
Open latest played files from the "Open Recent" list.

**Actual behavior:**
Only manually opened files can be selected from the "Open Recent" list.

**Comment by megadr01d** [comment]
Dupe of https://github.com/lhc70000/iina/issues/286 and https://github.com/lhc70000/iina/issues/207 and relevant commit https://github.com/lhc70000/iina/pull/595.
