### ISSUE TITLE
Can not open in macOS 10.12.4 with MacBook Pro 15.

### ISSUE THREAD

**Issue by RJAVA1990** [lhc70000/iina#624]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Expected behavior:**
The software could be opened.

**Actual behavior:**
The software has no response.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Please provide more info, like

- Whether you are using custom mpv config directory
  - If so, please try disabling it
    - If it works, please provide your mpv config file
- MPV log, if possible

**Comment by lhc70000** [comment]
Closing. Please reopen if there's any update.
