### ISSUE TITLE
Lua plugin support

### ISSUE THREAD

**Issue by avdbg** [lhc70000/iina#627]
Just like VLC's plugin system.

**Comment by syslot** [comment]
Do you think python plugin will be more popular?

**Comment by megadr01d** [comment]
See https://github.com/lhc70000/iina/issues/547.
Related: https://github.com/lhc70000/iina/issues/297.

**Comment by avdbg** [comment]
@megadr01d I see, thanks

@syslot Maybe Python is too complicated? I think Lua is enough for plugin.
