### ISSUE TITLE
0.0.8 is slower than 0.0.7 when decoding some videos!

### ISSUE THREAD

**Issue by Ailick** [lhc70000/iina#630]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Performing&Problem**

Playing with IINA 0.0.7 is well(Source:120FPS->Screen:60FPS). Nothing is unhappy! Because the pretty HW-Decoder.

But playing with IINA 0.0.8 same that it just has 48 fps around. Oh......What's happened?
Please fix it.

Thank you!!!

**Test Videos Info (Just A Demo With NO Copyright Protection)**

-File Name:[VCB-S]Toaru Kagaku no Railgun II[NCOP1][2160p][120fps][BDRip][x264_flac].mkv
-Format : Matroska
-Format version : Version 4 / Version 2
-File size : 310 MiB
-Duration : 1mn 32s
-Overall bit rate mode : Variable
-Overall bit rate : 28.2 Mbps
-Encoded date : UTC 2013-08-17 12:21:34
-Writing application : mkvmerge v6.3.0 ('You can't stop me!') built on Jun 28 2013 20:09:41
-Writing library : libebml v1.3.0 + libmatroska v1.4.0
 
Video 
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L5.2
Format settings, CABAC : Yes
Format settings, ReFrames : 8 frames
Codec ID : V_MPEG4/ISO/AVC
Width : 3 840 pixels
Height : 2 160 pixels
Display aspect ratio : 16:9
Frame rate mode : Variable
Original frame rate : 119.880 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Writing library : x264 core 136 r2348+704+51 d1baef6 tMod [8-bit@4:2:0 X86_64]
Encoding settings : cabac=1 / ref=8 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / fade_compensate=0.00 / psy_rd=0.60:0.00 / mixed_ref=1 / me_range=48 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=10 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=infinite / keyint_min=1 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=20.0000 / qcomp=0.70 / qpmin=0:0:0 / qpmax=69:69:69 / qpstep=5 / ip_ratio=1.40 / aq=3:0.80 / aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0
Language : English
Default : Yes
Forced : No
Color range : Limited
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709
 
Audio 
ID : 2
Format : FLAC
Format/Info : Free Lossless Audio Codec
Codec ID : A_FLAC
Duration : 1mn 32s
Bit rate mode : Variable
Channel(s) : 2 channels
Sampling rate : 48.0 KHz
Bit depth : 16 bits
Writing library : libFLAC 1.2.1 (UTC 2007-09-17)
Language : Japanese
Default : Yes
Forced : No
 
**Download Link(If not avilable please tell me)**

https://pan.baidu.com/s/1skIhxKh
Password: *removed* 
(Note:[VCB-S]Toaru Kagaku no Railgun II[NCOP1][Hi10p_2160p][120fps][BDRip][x264_flac].mkv Just For Test SW-Decode Now)

**Comment by Ailick** [comment]
**Password: 9fdy**

**Comment by lhc70000** [comment]
0.0.8 only upgraded mpv to 0.25.0. It should be caused by mpv. Have you tried to compare mpv 0.25 and 0.24?

BTW it still prompts me the password.

**Comment by Ailick** [comment]
Sorry, password is 9fdy .And I will try it by your way.

**Comment by lhc70000** [comment]
Should be caused by mpv.
