### ISSUE TITLE
About UI Layout Transparency

### ISSUE THREAD

**Issue by dingdangnao** [lhc70000/iina#634]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.9

**behavior:**
Changing UI layout to `Bottom` or `Top` the controller Area will lose its transparency when window is  unfocused which looks so wired (`Floating` doesnt have this problem)  dont know whether it's a bug or a feature

![](http://ww4.sinaimg.cn/large/006tNbRwgy1fff9dgrlt7j31kw0lxdk2.jpg)

**Comment by lhc70000** [comment]
@dingdangnao It'll be fixed in next version.
