### ISSUE TITLE
Eastern European encoding (windows-1250) is missing

### ISSUE THREAD

**Issue by tborychowski** [lhc70000/iina#635]
**System and IINA version:**
- macOS 10.12.4
- IINA 0.0.9 (build 21)

**Description**
There are a couple of issues with subtitles:
1. Subtitles with `*.txt` extension (and the exact same name as the movie) don't seem to be loaded automatically (no matter the autoload setting)
2. Eastern European encoding (windows-1250) is missing from the encoding list. There is another Eastern European encoding (windows-1252), which I think is incorrect, as all the other apps in the world have it as `windows-1250`, and not `windows-1252`
3. When I load my `.txt` subtitles with the `windows-1250` encoding - the Polish characters are not encoded correctly. I tried several encoding from the app's list, but none of them makes any difference. (I also tried restarting the app, and reloading the subtitles, with no result).

And thank you for this app. This is the best looking video player for mac ever! 😄

**Comment by alejx** [comment]
I'm curious about the txt format subtitle. Can you upload one?

**Comment by tborychowski** [comment]
Sure, here's one: [sample.txt](https://github.com/lhc70000/iina/files/988188/Stargate.SG-1.1x09.Thor.s.Hammer.txt)

**Comment by alejx** [comment]
I tried in mpv, however it seems like mpv does not consider the txt files as subtitles by default either. It's easy to autoload it as subtitle, but the problem is that there may exist txt files which have the same name as the video are not subtitles. 
Is txt subtitle widely used? If so, we can make a simple detector to detect whether the txt file _seems like_ a subtile file.

**Comment by tborychowski** [comment]
Yes, AFAIK, `.txt` is very popular.  All video players I've used (on windows, linux and mac) supported it. E.g. [VLC](https://wiki.videolan.org/subtitles).

**Comment by lhc70000** [comment]
Added in 0.0.12. `txt` file support is in the plan BTW.

**Comment by tborychowski** [comment]
it works great! thanks!
