### ISSUE TITLE
Error trying to install Safari plugin

### ISSUE THREAD

**Issue by rosch100** [lhc70000/iina#637]
When trying to install the Safari plugin, an error message is displayed "Safari is not able to install this extension".

**System and IINA version:**

- macOS 10.12.5 Beta (16F71b)
- IINA 0.0.9
- Safari 10.1.1

**Comment by lhc70000** [comment]
Have you tried some existing solution like https://discussions.apple.com/thread/7254177?tstart=0?

**Comment by rosch100** [comment]
Thanks. Uninstalling all other extensions did the trick.
> Have you tried some existing solution like https://discussions.apple.com/thread/7254177?tstart=0 <https://discussions.apple.com/thread/7254177?tstart=0>?
>
