### ISSUE TITLE
Chrome extension not working?

### ISSUE THREAD

**Issue by rosch100** [lhc70000/iina#638]
If I want to play a video using the IINA-Extension, nothing happens.
Example: [Example Video](http://www.spiegel.de/video/hamburger-sv-gisdol-zwischen-verzweiflung-und-hoffnung-video-1764837.html)
I push the IINA extension button - no reaction.
I push the IINA extension button with the right mouse button and select "Open in IINA". Now the IINA extensions page opens, not the video.

I did not find any way to play an embedded video.

**System and IINA version:**

- macOS 10.12.5 Beta (16F71b) 
- IINA 0.0.9
- Chrome 59.0.3071.36

**Comment by lhc70000** [comment]
It's equivalent to opening the **webpage URL** in IINA, so please check [whether youtube-dl supports your website](https://rg3.github.io/youtube-dl/supportedsites.html).

The plugin doesn't support embedded video, since usually these videos can't be accessed directly without a browser environment, and that's why youtube-dl exists.

**Comment by rosch100** [comment]
The list shows that youtube-dl supports the website. I also tried vimeo.com and youtube.com.
Same behavior. See attached screencast
![iina chrome extension problem](https://cloud.githubusercontent.com/assets/5745224/25888332/07eb25c2-3566-11e7-836f-2b8eb16fd17b.gif)

**Comment by lhc70000** [comment]
Please click the background page (maybe you need to enable developer settings), and it will pop up a developer tool window.
![85f37370-a5ab-4be6-a885-2ea19c58dc1f](https://cloud.githubusercontent.com/assets/8478049/25888533/26394260-3599-11e7-9f06-b64c7da97c83.png)

Then try to click IINA icon again, and check if there are any error message appears in the "console" tab like this:
![e3a03b23-1258-4c54-bec2-b9eef22b2224](https://cloud.githubusercontent.com/assets/8478049/25888683/ab9be76e-3599-11e7-864e-b979e6bbf631.png)

**Comment by rosch100** [comment]
In the developer tool window, the console shows no messages at all (even in verbose mode).
