### ISSUE TITLE
Reset subtitle delay when a new video starts playing

### ISSUE THREAD

**Issue by LEMONed** [lhc70000/iina#642]
Subtitle delay should be effective during the current playback session only.

**Comment by lhc70000** [comment]
Please add `reset-on-next-file` = `sub-delay` as an additional mpv option.

Reference: https://mpv.io/manual/stable/#options-reset-on-next-file

**Comment by cinan** [comment]
how can i use this option via gui? i don't run iina or mpv from shell

**Comment by lhc70000** [comment]
@cinan Preferences > Advanced
