### ISSUE TITLE
播放内置字幕的视频时乱码

### ISSUE THREAD

**Issue by chen-jingliang** [lhc70000/iina#644]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.9

**Expected behavior:**

**Actual behavior:**
在播放苹果官网下载的 WWDC2016内置字幕视频时，出现乱码，选择了多个中文及英文编码仍出现错误，视频下载地址：https://developer.apple.com/videos/play/design/22/

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
和 #391 #518 是相同问题，此类型字幕各播放器均没有支持，建议用 QuickTime 播放。
