### ISSUE TITLE
Maybe it's a bug that you have already fix it.

### ISSUE THREAD

**Issue by AurevoirXavier** [lhc70000/iina#646]
I saw many issues about "When I pause iina, it still on the top".

I want to make it always on  the top even the video is pause.

I often watch video and take note, so I hope you can add a switch which can control this.

**Comment by nhooyr** [comment]
Click Video and then Picture in Picture.

**Comment by lhc70000** [comment]
IINA behaves like this only when you enabled "always float on top" in preference.

You can disable this option and use `Menu > Float on Top` or control+cmd+T.

**Comment by AurevoirXavier** [comment]
@lhc70000 It works, thanks. But I think if you put it in the UI setting that will be better. (I think just a few people know this...)
