### ISSUE TITLE
DV files in the same folder are not getting added to playlist

### ISSUE THREAD

**Issue by megema** [lhc70000/iina#647]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.9

**Expected behavior:**
Add DV files in the same folder to the playlist if 'Add files in the same folder automatically' option is enabled.

**Actual behavior:**
Only the opened file appears in the playlist.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
1) Enable 'Add files in the same folder automatically' option
2) Open any DV file.

- [ ] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by HarukaMa** [comment]
@megema By "DV file", could you provide the filename examples? (AVCHD or just MP4s?）

**Comment by megema** [comment]
[Here](https://pastebin.com/51neLynJ) is a MediaInfo report.

**Comment by megema** [comment]
Does v0.0.11 contain this fix? Nothing has changed yet.

I also noticed, the MP(E)G files are affected too. I have a folder of videos with multiple file formats (avi, wmv, mpeg, mpg, flv). When I open any file from this folder, all files are getting added to the playlist except for mpg/mpeg files. It's the same when opening a mpg/mpeg file, but it's placed to the end of the playlist.

**Comment by megema** [comment]
v0.0.12 still affected.
