### ISSUE TITLE
Error when set as Default App

### ISSUE THREAD

**Issue by Nes-si** [lhc70000/iina#648]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.9

**Problem:**
I've called Help - Set IINA as Default App, then I've pressed Yes. Next there is an alert:
![iina - set default app](https://cloud.githubusercontent.com/assets/5188972/26019050/586b7968-377b-11e7-8b7d-55025219dfaa.png)
It seems like there are no errors, but the caption is "Error".

**Comment by lrzhuang** [comment]
me too

**Comment by lhc70000** [comment]
The process actually succeed and it's just a localization issue. Already fixed in develop.
