### ISSUE TITLE
Github Publish Authorization Problem

### ISSUE THREAD

**Issue by eminhaqi** [lhc70000/iina#649]
I cannot publish turkish localization.
<img width="994" alt="ekran resmi 2017-05-13 01 38 28" src="https://cloud.githubusercontent.com/assets/18751143/26019303/17cf9c0c-377d-11e7-8525-51a765eb6f53.png">
<img width="994" alt="ekran resmi 2017-05-13 01 38 40" src="https://cloud.githubusercontent.com/assets/18751143/26019305/19e04776-377d-11e7-9abb-93d89791b49b.png">

**Comment by alejx** [comment]
https://github.com/lhc70000/iina/wiki/Translation
You cannot directly push to the main repo. Please fork this repo, then push the commits to your forked repo, and make a pull request on GitHub.

**Comment by eminhaqi** [comment]
Thanks
