### ISSUE TITLE
too hot

### ISSUE THREAD

**Issue by maoyuanquan** [lhc70000/iina#65]
It looks so beautiful, but My Macbook Pr 15 in 2013 was too hot when playing movies.

**Comment by lhc70000** [comment]
Probably duplicate with #51.

Did you open the file from `File - Open` or playlist?

**Comment by lhc70000** [comment]
0.0.4 _should_ fixed high CPU usage problem. Please test if there's any improvement.

If the problem persists, please reopen this issue.
