### ISSUE TITLE
视频播放时耳机只有一边有声音

### ISSUE THREAD

**Issue by gh351135612** [lhc70000/iina#652]
系统：macOS 10.12.2
文件格式：m4v

**Comment by HarukaMa** [comment]
@gh351135612 视频用别的播放器能播？没问题？

**Comment by gh351135612** [comment]
我刚刚在浏览器中用百度云播放了下，耳机也只有一个有声音，估计是视频本身有问题。

**Comment by HarukaMa** [comment]
Closing as invalid.

**Comment by chenyiping1995** [comment]
@HarukaMa 大概是你耳机坏了吧

**Comment by gh351135612** [comment]
没有，我用音乐播放器试了下，应该是视频本身的问题。
