### ISSUE TITLE
加载外挂字幕软件挂掉 无响应

### ISSUE THREAD

**Issue by wolflikai** [lhc70000/iina#655]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
@wolflikai 请提供问题字幕。

**Comment by wolflikai** [comment]
影片：萨利机长.mp4
当选择 字幕 —— 加载外置字幕 弹出Finder 进行选择时默认位置 是文稿  选择其他位置 一点击就无响应了 ！


谢谢开发组！！！ 

原始邮件
发件人:Collider LInotifications@github.com
收件人:lhc70000/iinaiina@noreply.github.com
抄送:wolflikaiwolflikai@163.com; Mentionmention@noreply.github.com
发送时间:2017年5月16日(周二) 20:55
主题:Re: [lhc70000/iina] 加载外挂字幕软件挂掉 无响应 (#655)


@wolflikai 请提供问题字幕。
