### ISSUE TITLE
Keybindings for the J, K, and L keys

### ISSUE THREAD

**Issue by roonieone** [lhc70000/iina#656]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**
Perhaps I'm missing something, but I can't figure out how to use the current keybindings system to set up the `J`, `K`, and `L` keys to be used as they are in Premiere, Final Cut Pro X, QuickTime, etc. where:

- Pressing the `L` key increases the forward speed in multiplication increments for each press
- Pressing the `J` key increases the backwards speed in multiplication increments for each press
- Pressing the `K` key or space bar plays the video at the point the playhead is at at the regular speed

Any insight? If this isn't currently possible, might it be a possible addition? These are shortcuts I use daily in video editing and it would be great to be able to use these shortcuts in IINA too.

**Comment by lhc70000** [comment]
I just finished the wiki page for setting key bindings, please take a look:
https://github.com/lhc70000/iina/wiki/Manage-Key-Bindings

Here's what you should set in IINA's key binding system, assuming you want to multiply the speed by 1.1x for each press.

|Key|Settings in GUI|mpv command|Comment|
|---|---|---|---|
|J|`Multiply` `Speed` by `1.1`|`multiply speed 1.1`||
|K|`Set` `Speed` to `1`|`set speed 1`||
|L|`Multiply` `Speed` by `0.909`|`multiply speed 0.909`|1/1.1 = 0.909|

**Comment by roonieone** [comment]
That works for the most part, except `Multiply` `Speed` by `0.909` just makes the video slow down in forward motion. The way it works in NLEs and QuickTime is reversing through the video at increasing speeds.

To bind the `J` key in IINA the same way it works in NLEs and QuickTime, there would need to be something like `Multiply` `Speed` `Reverse` by `1.1` or `Multiply` `Speed` by `-1.1` (which is technically possible now, but does not produce the desired results).

Also, another through came to mind: it would be great to be able to add multiple actions to one key. For example, I would want `space` to `Set` `Speed` to `1` and also `Cycle` `Pause` in this case.

**Comment by saagarjha** [comment]
IINA doesn't support backwards playback, since [mpv doesn't either](https://github.com/mpv-player/mpv/issues/4000).

**Comment by roonieone** [comment]
Is there a good reason to not consider adding backwards playback support?

**Comment by saagarjha** [comment]
Since IINA uses mpv, it tends to avoid adding playback features itself. Plus, even if we did try to implement it ourselves, apparently backwards playback is difficult to do.
