### ISSUE TITLE
Cropped videos is not center-positioned

### ISSUE THREAD

**Issue by wangcheng678** [lhc70000/iina#657]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

Video should be cropped equally on both sides and center-positioned.

**Actual behavior:**

Only left or bottom side of the video is cropped.

Original Video:
![Original Video](https://cloud.githubusercontent.com/assets/1688764/26143720/abc27634-3b18-11e7-9597-c92b9a3229e6.png)

5:4 Cropped:
![5:4 Cropped](https://cloud.githubusercontent.com/assets/1688764/26143739/bc5d76d8-3b18-11e7-8325-c6bc4481147e.png)

2.21:1 Cropped
![2.21:1 Cropped](https://cloud.githubusercontent.com/assets/1688764/26143757/d8028e6e-3b18-11e7-9953-63f557352581.png)

**Comment by lhc70000** [comment]
Please disable hardware decoding, or use `hwdec=auto-copy` (which will occupy about 2x memory) as an additional mpv option.

**Comment by wangcheng678** [comment]
So this issue is unfixable with default `hwdec` option?

**Comment by lhc70000** [comment]
Yes. In later versions IINA will auto switch to `auto-copy` when user enabled filter related settings.

**Comment by wangcheng678** [comment]
Okay, I get it.
