### ISSUE TITLE
Resizing window with pinch gesture

### ISSUE THREAD

**Issue by oskarkrawczyk** [lhc70000/iina#66]
Movist does this and it's a really awesome feature, no need to look for the drag handle at the corner, just hover over the window and pinch in or out for resizing.

**Comment by lhc70000** [comment]
Seems duplicate with #23.

Some users also want entering fullscreen by pinch gesture. Maybe need to let them choose the behavior.

**Comment by alejx** [comment]
Close due to duplication.
