### ISSUE TITLE
Cannot close window when playback finished

### ISSUE THREAD

**Issue by stevenlordiam** [lhc70000/iina#660]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

Close the window and quit the app when the video is finished playing

**Actual behavior:**

The video is set to "pause" after the playback is finished even the "keep window open when playback finished" option is unchecked. Attached setting screenshot below.

![screen shot 2017-05-17 at 17 56 29](https://cloud.githubusercontent.com/assets/3217051/26178021/2f09f010-3b2a-11e7-9fcf-7103ce832f1b.png)

Any ideas?

**Comment by lhc70000** [comment]
Please follow these steps:

1. Enable "Play next item automatically". (limited by mpv)
2. Enable and disable "Keep window open when playback finished" again. (small bug of IINA)

**Comment by stevenlordiam** [comment]
@lhc70000 It works, thank you!

**Comment by oObelix** [comment]
MacOs 12.6 (21G115)
IINA 1.3.0 Build 132
It looks strange.. Works still only with "Play next item automatically" enabled.

**Comment by patatero** [comment]
macOS Ventura 13.3
IINA 1.3.1 Build 133

This bug still exist. The first link in Google is this Github page and the solution by lhc70000 still works.
