### ISSUE TITLE
在线下载字幕错误

### ISSUE THREAD

**Issue by lightmotion** [lhc70000/iina#661]
System and IINA version:

macOS 10.12.4
IINA 0.0.9

Actual behavior:
在线搜寻字幕后弹出出错对话框：error，不支持的外部字幕。
抱歉我无法提供影片下载link，因为有些正常，有些就会出错，比如  Six.Feet.Under.S03E04.720p.WEB-DL.AVC-iON.mkv。可以看到左上角已经有下载好srt字幕的提示。

同时我建议再增加几个在线字幕搜寻点，射手搜寻新剧有局限了，目前kodi字幕插件除了射手还有sub hd，字幕库，还有zimuzu。

**Comment by lhc70000** [comment]
[https://github.com/lhc70000/iina/wiki/下载在线字幕#无法打开字幕](https://github.com/lhc70000/iina/wiki/下载在线字幕#无法打开字幕)

> 射手网下载的字幕有一定机率是损坏的，此时 IINA 无法加载并会弹出相应提示。这不是 IINA 的问题。

关于其他字幕来源，他们都没有 API，而且目前没有精力，请稍等几个版本。
