### ISSUE TITLE
使用safari插件播放优酷较长视频时只能播放第一段

### ISSUE THREAD

**Issue by ahugeStone** [lhc70000/iina#665]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

**Actual behavior:**
优酷较长的视频会拆成好几段，用you-get配合mpv播放会自动查找下一段，希望iina插件也能实现类似功能

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
可能比较难，因为没有集成 you-get，youtube-dl 没有这个功能。
关于 you-get 的讨论，参见 #58 。
