### ISSUE TITLE
Inspector无法添加或删除Status中Watch的项目

### ISSUE THREAD

**Issue by receyuki** [lhc70000/iina#666]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.9

**Actual behavior:**
在添加多个项目之后原本在Watch列表下的添加和删除按钮消失.
![image](https://cloud.githubusercontent.com/assets/28808141/26265081/e44bb536-3d22-11e7-8465-3d009c1c50ed.png)
![image](https://cloud.githubusercontent.com/assets/28808141/26265150/3350acae-3d23-11e7-9442-5b327610dd47.png)

**Steps to reproduce:**
添加八个Watch项目

- [x] MPV does not have this problem.

**How often does this happen?**
当我添加完第八个项目之后到目前为止依然未出现添加或删除按钮

**Comment by lhc70000** [comment]
Will fix in next version. For now please use `defaults delete com.colliderli.iina watchProperties` to delete all of them.
