### ISSUE TITLE
将IINA设为默认播放器时即使fail为0也会出现error窗口

### ISSUE THREAD

**Issue by receyuki** [lhc70000/iina#667]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.9

**Expected behavior:**
选择将IINA设为默认播放器之后即使所有格式都链接成功.fail数为零却依然显示的是error对话框会让人觉得很奇怪..个人认为可能只是用错了窗口

**Actual behavior:**
![image](https://cloud.githubusercontent.com/assets/28808141/26265758/b3bec52c-3d25-11e7-8d42-036cbdc0a5f5.png)

**Steps to reproduce:**
帮助→将IINA设置为默认播放器...

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
Duplicate with #648
