### ISSUE TITLE
[Feature Request] Overlay the embed (hardcore) subtitles 字幕遮挡

### ISSUE THREAD

**Issue by leeben11** [lhc70000/iina#671]
**System and IINA version:**
macOS 10.12.5 
IINA 0.0.9 build 21

**Expected behavior:**
Overlay the embed (hardcore) subtitles

**How often does this happen?**
EVERYDAY

As you might know, watching American TV show is one of the way to learn English, sometimes we need to blocking the Chinese subtitles to ensure that we still can understanding those conversation.

I read the changelog and try to use the feature subtitle blur, but seems is not about covering or blocking means. Hope you can add a delogo feature can work for embed (hardcore) subtitles.

Reference 
http://ptbsare.org/2014/11/07/英文影片中播放器遮挡字幕/#2016年10月11日更新
https://github.com/b4zz4/mpv-delogo

**Comment by saagarjha** [comment]
So, how exactly does this blur work? Does it apply a blur over a user-defined area, or does it try to guess where subtitles are and blur them?

**Comment by leeben11** [comment]
Yes, you can defined a specific area to blur, like a command line delogo=x:y:w:h:s work for mplayer.
Such as 
480X272        delogo=100:230:320:24:1
624X352        delogo=155:300:350:29:1
720x396         delogo=175:335:350:40:1
![15](https://cloud.githubusercontent.com/assets/22412518/26291594/f736abf4-3ee1-11e7-9cfa-050b7cfbd030.png)
![1113215](https://cloud.githubusercontent.com/assets/22412518/26291637/61033f0c-3ee2-11e7-9072-bf906da0d1a4.png)

**Comment by excelwang** [comment]
The subtitle visibility switcher by press 'v',  a feature of MPV,  is also required.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13. Please use the delogo filter.
