### ISSUE TITLE
[BUG] "Add files in same folder automatically" feature duplicates playlist items

### ISSUE THREAD

**Issue by alayliercan** [lhc70000/iina#672]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

*Add files in same folder automatically* feature should only add video files into the playlist once unless it's a new video file that doesn't already exist on the playlist.

**Actual behavior:**

Re-ordering items on it duplicates video files on playlist. 

**Steps to reproduce:**

1) Enable *Add files in same folder automatically* feature
2) Open up a video file from a directory that's got more than one video file in it
3) Open up the playlist and move currently playing video file to somewhere else in the list.
4) Start playing another video file by clicking on it on playlist.
5) Now you will notice that the video file that you had moved was added into playlist again.

**How often does this happen?**

Every time you re-order playlist items.

**Comment by megadr01d** [comment]
Maybe related to https://github.com/lhc70000/iina/issues/455.

**Comment by alayliercan** [comment]
I don't use shuffle function though. Have you tried to reproduce it?

**Comment by lhc70000** [comment]
It's going to be fixed in next version. See `auto-load` branch and #673.

**Comment by alayliercan** [comment]
Thanks for letting me know. Cheers.

**Comment by alejx** [comment]
Fixed in develop. See #673 .
