### ISSUE TITLE
Create a IINA iOS version, please

### ISSUE THREAD

**Issue by Frankwasser** [lhc70000/iina#674]
I have iPhone 7 Plus and iPad Pro 12.9 here, for testing.

Can you optimized libmpv for iOS? I know this is not easy. But iOS need so a video player in Swift language.

Why? This iOS device supports 10bit playback.

**Comment by HarukaMa** [comment]
@Frankwasser IINA currently relies too much things on macOS, so there won't be iOS version anytime soon. Sorry about that.

**Comment by iTheProMan** [comment]
any ios update sir?

**Comment by bugs181** [comment]
> any ios update sir?

No.

> alejx added the priority: wontfix label on May 24, 2017

It's not going to happen.

**Comment by Crear12** [comment]
I'd say let's expect Apple to release macOS on iPad by not buying any Mac base models.
