### ISSUE TITLE
[Feature Request] Add "Load Online Subtilte" in "Quick Settings Panel"

### ISSUE THREAD

**Issue by theGeorg** [lhc70000/iina#675]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

I would find it beneficial if there was a "Load Online Subtitle" in the "Quick Settings Panel" right under the already existing "Load Subtilte" Button.

<img width="354" alt="screen shot 2017-05-24 at 09 34 08" src="https://cloud.githubusercontent.com/assets/28918358/26391949/124b29c2-4065-11e7-8c0f-250445df2779.png">

**Comment by alejx** [comment]
Added in develop. See #673 .
