### ISSUE TITLE
[Feature Request] Add "Autoload external audio"

### ISSUE THREAD

**Issue by imKota** [lhc70000/iina#676]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.9

**Expected behavior:**

Please add support for autoloading external audio tracks automatically (.mka, .acc, and other).
![1](https://cloud.githubusercontent.com/assets/24241471/26440943/3db8a184-4137-11e7-9082-6629819700a9.png)

**Comment by lhc70000** [comment]
@imKota You can add an extra mpv option audio-file-auto=fuzzy in Preference > Advanced.

**Comment by imKota** [comment]
@lhc70000 Thanks for the answer!
I have another question, how can I help translating the application into Ruusian? I work with xcode for the first time, and I can not figure it out.

**Comment by alexander-ii** [comment]
@lhc70000 Hi. What if external audio files are located in a subfolder?  

![image](https://user-images.githubusercontent.com/25887642/35773125-fa2e4cac-0959-11e8-9ac3-9babf2b81eac.png)  

`audio-file-auto=fuzzy` option seems not working in an expected way. Is there any chance to get an external audio setting tab with more verbose and flexible tuning like as subtitles tab have?

**Comment by JokerQyou** [comment]
I think @alexander-ii 's use case is valid. Some blu-ray image have them separated from the video, in this case audio tracks should be treated just like subtitles: to be able to manually load an audio file, and select a track from it.
