### ISSUE TITLE
Can't display subtitle! 无法显示字幕

### ISSUE THREAD

**Issue by adamzjk** [lhc70000/iina#679]
this issue comes after the update of 0.0.9, IINA can't show subtitle while other player like 暴风影音 could. I'm sure I select the subtitle correctly. This issue seems also happened in version 0.0.7.

**Comment by lhc70000** [comment]
@adamzjk Please check whether you have <kbd>V</kbd> key bound to "subtitle visibility".

**Comment by adamzjk** [comment]
@lhc70000  No, nothing changed when i press the V key; and still no subtitle when i convert back to version 0.0.8; I've tried 3 movies. I'm considering restart my computer.

**Comment by adamzjk** [comment]
mpv can also load subtitle. the video file is fine.

**Comment by lhc70000** [comment]
@adamzjk Please enabe logging in Preference > Advanced, try loading the subtitle, and upload the mpv log together with your subtitle file.

**Comment by adamzjk** [comment]
[Archive.zip](https://github.com/lhc70000/iina/files/1033343/Archive.zip)

This is the log and the subtitled downloaded from internet, IINA could load neither the build-in nor the downloaded subtitle.

**Comment by megadr01d** [comment]
The subtitle file loaded fine here, on 0.0.9 (Chinese subs, right? In Sublime Text they show up like garbled text). Maybe it's dependent on IINA's chosen font.

**Comment by HarukaMa** [comment]
This subtitle file is encoded in BIG5, but ffmpeg won't accept that. Try converting it to UTF8 and try again.
