### ISSUE TITLE
Wider playlist

### ISSUE THREAD

**Issue by shenguanjiejie** [lhc70000/iina#682]
I hope this list be wider, because I can't know the video name quickly if it is to long...thanks
![jietu20170528-105828](https://cloud.githubusercontent.com/assets/9425605/26525796/51f4ab06-4395-11e7-812c-4c706d888300.jpg)

**Comment by alejx** [comment]
Please update IINA to latest version and have a try!

**Comment by shenguanjiejie** [comment]
Perfect! Thanks! 👍
