### ISSUE TITLE
voice setting

### ISSUE THREAD

**Issue by shenguanjiejie** [lhc70000/iina#683]
I set voice to 200, but it will auto change to 100 when the viedo changed.

**Comment by saagarjha** [comment]
@shenguanjiejie Were you able to resolve this issue?

**Comment by shenguanjiejie** [comment]
I'm sorry. It's ok now. so,I'm not sure this is a issue~

**Comment by shenguanjiejie** [comment]
@saagarjha I got the reason today. I have an magic mouse, I set voice to 200, Then I scroll the mouse up, It will turn to 100 at the moment.

**Comment by euf** [comment]
I posted some comments and suggestions on this behavior at #694, please comment and thumbs up if you find my ideas interesting.
