### ISSUE TITLE
[Feature Request] Disabling files that cannot be played automatically when opening a file to play in iina

### ISSUE THREAD

**Issue by yujingbin** [lhc70000/iina#684]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.9

**Expected behavior:**
Letting the open panel automatically disable the files that can't be played by iina

**Actual behavior:**
Not implemented yet.

If the author allows, I can implement this feature and create a pull request

- Crash report:
```
N/A
```

- MPV log:
```
N/A
```

**Steps to reproduce:**
N/A

**How often does this happen?**
N/A

**Comment by yujingbin** [comment]
@lhc70000

**Comment by lhc70000** [comment]
The problem is, even the mpv team doesn't provide such a list - mpv/IINA can play almost all kinds of media files.

**Comment by yujingbin** [comment]
The problem is that some files which isn't filtered by the player is not media files.

**Comment by yujingbin** [comment]
The problem is that some files which aren't filtered by the player is not media files.

**Comment by alejx** [comment]
This issue should be solved in the current develop branch.

**Comment by yujingbin** [comment]
It seems that this problem can be solved by changing the settings. @alejx

**Comment by yujingbin** [comment]
Change the settings of Mac OS@alejx
