### ISSUE TITLE
Update "Picture in Picture" to "picture in picture"

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#687]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.9

**Expected behavior:**
IINA uses "This video is playing in picture in picture", as per [WebKit commit 3d93dbc](https://github.com/WebKit/webkit/commit/3d93dbc4065cf6a6ec044e3ee16cfea921c4bab3).

**Actual behavior:**
IINA still uses "This video is playing in Picture in Picture".

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
Wow! How did you notice that!
I think we should follow them. You can make a pr about that.

**Comment by saagarjha** [comment]
@alejx I noticed that Safari changed its text recently. I'll write a PR for this.
