### ISSUE TITLE
Opened choose file panel makes any other interaction impossible

### ISSUE THREAD

**Issue by euf** [lhc70000/iina#693]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

IINA’s other controls should not be blocked while choose file panel is opened.

**Actual behavior:**

If select file panel is opened, it is impossible to view About, check for update or open settings.

**Steps to reproduce:**

- Launch IINA
- At any moment try «File» → «Open…» from main menu or just press <kbd>⌘</kbd>+<kbd>O</kbd>.
- Look at the «About IINA», «Check Update…» or «Preferences…» items in the main menu, they are grayed out until file selector panel is closed. Shortcut <kbd>⌘</kbd>+<kbd>,</kbd> deosn’t work either.

- [x] MPV does not have this problem.

**How often does this happen?**

Every time choose file dialog is opened.

**Screenshot:**

![2017-05-31 2 11 57](https://cloud.githubusercontent.com/assets/11754264/26608889/a4c0c0e6-45a6-11e7-9b92-88555b232873.png)

**Comment by alejx** [comment]
Actually this has been discussed before, but I still think we need discuss it again.

**Comment by euf** [comment]
I agree that this is low priority problem, but I think it still counts as undesirable behavior.

**Comment by alejx** [comment]
I'm very sure it is controlled by macOS. You can try any other non-document-based app, they just act the same as what IINA acts now.
