### ISSUE TITLE
UPD: even better suggestion on volume control

### ISSUE THREAD

**Issue by euf** [lhc70000/iina#694]
This issue aims to complement #683 bug with a suggestion of possible logic to solve it and also it shares a couple of ideas on why the default volume limit should be pushed up from 130 to 250.

##  Bug report

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Steps to reproduce:** 

- Set with arrow keys volume above 100, e.g. 120.
- Scroll up with touchpad or mouse

**Actual behavior:**
- Volume drops to 100

**Expected behavior:**
- Volume increases

**How often does this happen?**
- This happens every time you try to reproduce it 

# UPD

Following suggestions seem overcomplicated compaired to @megadr01d’s [idea](https://github.com/lhc70000/iina/issues/694#issuecomment-305788591). 

Also see another one [suggestion](https://github.com/lhc70000/iina/issues/694#issuecomment-305927042) below. <s>

##  Suggestion 1

I guess the following logic would be optimal:

- If volume is 100 or lower at the moment, scrolling up allows to reach 100
- If volume is already above 100, scrolling up allows to reach volume-max

This will maintain the strategy of not allowing users to get over volume limit accidentally, but will improve usability for those who already overcame the barrier on purpose using arrow keys.

##  Suggestion 2

By the way, I also suggest increasing rising `volume-max` from 130 to 250 or at least to 200 (as in VLC), because I’ve seen Russian reviews on IINA saying that «the last reason for me to stick with VLC is its volume huge increase feature» — so I had to reply with self-made guide like this. 
![1496146973429936](https://cloud.githubusercontent.com/assets/11754264/26609469/eece680c-45a9-11e7-8b77-2f74a644036d.png)

In fact, it is really hard to find out that volume can be set higher than 100, but it’s okay since it was a design feature to make it less annoying. However, since we believe that now people won’t use it accidentally, we can move default upper limit even higher, because nobody should complain on degrading audio quality if he uses over-100%-volume consciously. 

But why bother at all? First of all, not every user who was not satisfied with 130 limit is ready to google mpv parameters or find a guide picture posted above, so giving more freedom to choose volume for those users is good. Second, psychological effect of supremacy should never be underestimated — if VLC can climb up to 200 out of the box, IINA should do at least the same just «to keep up with Jones» in the eyes of an average user. 

That’s why 250 is better — it looks so great when you find it, that reaching it at least once makes you feel that IINA can do something that other apps can not.

</s>

**Comment by shenguanjiejie** [comment]
Thanks 👍

**Comment by shenguanjiejie** [comment]
sorry,I set the valume-max to 300 yesterday, It worked. but the volume-max auto changed to 130 today, I don't know why. and I set to 300 now , but not worked...

**Comment by megadr01d** [comment]
I think volume control is becoming too complicated for our own good.

- Default (fresh IINA install) should be 100%. You can't go wrong with 100%. 100% is good and pretty and lovely.
- If user wants, he can override this in MPV options to 130, 150, 200, 357, 478 and a half, whatever. This is the **user's choice** so changing the volume to this limit by any of the means available, **can never** be accidental.
- When playing a video, all controls that control volume (menu command, trackpad, mouse, keyboard, joystick) should work to set the volume from 0 to the maximum specified MPV value, if overridden, or to the good and pretty and lovely 100%, if not.

**Comment by saagarjha** [comment]
Another option is having volume-max being set to 100 by default, but adding a slider in Preferences to change it. This way users won't have to go digging through advanced settings to find it.

**Comment by lhc70000** [comment]
@saagarjha There's already an input field in preferences. Do you mean the side panel?

**Comment by saagarjha** [comment]
Hmm, where is it? I can't seem to find it.

**Comment by lhc70000** [comment]
@saagarjha Codec > Volume.

**Comment by saagarjha** [comment]
Thanks. In that case I agree with @megadr01d.

**Comment by euf** [comment]
@megadr01d 
You are right, the logic I offered is overcomplicated. 
I like your solution much more.
@lhc70000 
> Codec > Volume.
Frankly speaking, it is really hard to notice — I used MPV options instead. Seems like many other users didn’t manage to find this setting too. Maybe push it to the top of the window to make more noticeable?
![2017-06-03 1 37 25](https://cloud.githubusercontent.com/assets/11754264/26747597/77ed09ac-47ff-11e7-9de9-7fdca9fb0c6f.png)

**Comment by sadovnychyi** [comment]
It seems like in some cases using above 100% volume could damage your speakers permanently. 

See this reddit thread for some cases (including mine):
https://www.reddit.com/r/apple/comments/6ls4hs/vlc_alternative_iina_is_so_much_better_try_it_out/djwaejm/

This is something I didn't know when I used 400% volume in VLC for a long time. I didn't install VLC on my new laptop at all since it's not possible to disable that feature so I could damage them again with a simple swipe.

So having the max volume at 100% by default seems perfect, but maybe there's should be a warning  about possible damage next to that setting where you change it above 100%? This could save some speakers from dying.

**Comment by R-L-T-Y** [comment]
Is it possible to implement an audio normalizer to solve this issue, like once and for all?
