### ISSUE TITLE
IINA's app bundle version missing on Quick Look preview

### ISSUE THREAD

**Issue by megadr01d** [lhc70000/iina#698]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.9

**Expected behavior:**

IINA's version should be available when you call Quick Look on the app bundle.

**Actual behavior:**

IINA's version is not available when you call Quick Look on the app bundle. It just shows the `NSHumanReadableCopyright` key but not the `CFBundleShortVersionString` key containing the version, although it shows both in the **Get Info** window.

- Crash report:
```
N/A
```

- MPV log:
```
N/A
```

**Steps to reproduce:**

Select IINA.app in your file manager and press <kbd>Space</kbd>.

- ~~[ ] MPV does not have this problem.~~

N/A

**How often does this happen?**

Always.

**Comment by alejx** [comment]
Bad news on this issue. I found that apple does not shows version number less than "0.1.0" in the Quick Look preview for some reason. I set the version number ("Bundle versions string, short" in the plist) to 0.1.0 or greater, clean Xcode cache, then compile a new app, then it works. 
@saagarjha Any thoughts?

**Comment by lhc70000** [comment]
Then it's actually not a big deal since we are going to reach 0.1.0 soon.

**Comment by megadr01d** [comment]
Thanks @alejx and I agree @lhc70000. Closing.

**Comment by saagarjha** [comment]
@megadr01d I'm not getting a version number for any app; how do you get this to show up?

![screen shot 2017-06-03 at 12 17 35](https://cloud.githubusercontent.com/assets/13786931/26756414/a87c94dc-4856-11e7-9bb1-7847c10ecc31.png)

**Comment by megadr01d** [comment]
@saagarjha Huh, that's a given, since Quick Look was introduced in OS X 10.5 (Leopard). If the version is declared in the `Info.plist` file, it shows up in Quick Look.

Example for ChronoSync:

```
<key>CFBundleGetInfoString</key>
<string>Version 4.7.6, Copyright 2002-2017, Econ Technologies, Inc.</string>
...
<key>CFBundleShortVersionString</key>
<string>4.7.6</string>
...
<key>CFBundleVersion</key>
<string>4.7.6</string>
```

![screencap-1496585192242](https://cloud.githubusercontent.com/assets/9649385/26762300/a7859722-4937-11e7-8656-b61742c9d6d3.png)

Some Apple stock apps:

![screencap-1496585235512](https://cloud.githubusercontent.com/assets/9649385/26762306/bb30e72c-4937-11e7-9511-6e4d93558a9d.png)
![screencap-1496585251537](https://cloud.githubusercontent.com/assets/9649385/26762308/bbabf85e-4937-11e7-9ec3-ca4685655508.png)
![screencap-1496585267962](https://cloud.githubusercontent.com/assets/9649385/26762307/bba9b53a-4937-11e7-9625-7c1f2ea3d877.png)

Try running `qlmanage -r` in your terminal, to reset Quick Look. I'm on OS X 10.11, by the way.

**Comment by saagarjha** [comment]
@megadr01d Could you send me a copy of `/System/Library/QuickLook/StandardBundles.qlgenerator/` on your system? I can't get it to show up.

**Comment by megadr01d** [comment]
Sure thing.

[StandardBundles.zip](https://github.com/lhc70000/iina/files/1050399/StandardBundles.zip)

**Comment by megadr01d** [comment]
Another thing, I don't install anything from the App Store, I download all my apps from the developers.
