### ISSUE TITLE
Trackpad or MagicMouse scroll can't change volume above 100.

### ISSUE THREAD

**Issue by darkbrow** [lhc70000/iina#699]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**
Trackpad or Magic Mouse vertical scroll change volume to maximum value specified user preference.

**Actual behavior:**
When changing volume via trackpad or magic mouse, volume does not change above 100.
Even if I specified maximum volume to above 100 (eg. 130) in Preference panel.
However Up and Down arrow keys are worked as expected. They can change volume above 100.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Always

Needs code change setVolume function in PlayerCore.swift file.

original code
```
  func setVolume(_ volume: Double, constrain: Bool = true) {
    let constrainedVolume = volume.constrain(min: 0, max: 100)
```

change to...
```
  func setVolume(_ volume: Double, constrain: Bool = true) {
    let constrainedVolume = volume.constrain(min: 0, max: mpvController.getDouble(MPVOption.Audio.volumeMax))
```

**Comment by chenjau** [comment]
same here, It is also true using a logitech mouse(g303).

**Comment by euf** [comment]
@darkbrow @chenjau 
Initially this was a design feature to allow increasing volume over 100 only with arrow keys.
I posted some comments and suggestions on this behavior at #694, please comment and thumbs up if you find my ideas interesting.

**Comment by chenjau** [comment]
What is the purpose of allowing to change volume over 100 by keyboard only? 
Why not just keep behavior consistently and simple, let users change volume any way they want, as I know, apps like Movist allow user scrolling from 0 to MAX, and I have never encountered problem with that.
