### ISSUE TITLE
Is there any way to stop checking update?

### ISSUE THREAD

**Issue by edwardfhsiao** [lhc70000/iina#700]
**System and IINA version:**

macOS 10.12.4
IINA 0.0.7

**Expected behavior:**

Is there any way to stop checking update?
Each time when I open up iina, it shows the dialog "Update Found", which is kind of annoying.

**Comment by lhc70000** [comment]
Please always use the latest version as IINA is still unstable. Is there any reason staying at 0.0.7?

**Comment by edwardfhsiao** [comment]
Nope, most of the users are lazy. And if there is no option to turn it off might let users think updating is mandatory, users don't like mandatory. It's a huge improvement if IINA can make it configurable.

**Comment by lhc70000** [comment]
It's actually intended for alpha stage. We will make it configurable later in stable release.

For now, I highly recommend you installing v0.0.9 (or 0.0.10 which will be released soon) since previous versions may contain critical bugs.
