### ISSUE TITLE
Touch Bar display current and remaining time together

### ISSUE THREAD

**Issue by rx2130** [lhc70000/iina#707]
I think it would be nice for Touch Bar to have current time label on the left side of the progress bar and the remaining time label on the right (I don't see how to accomplish in the current Touch Bar settings), such as the QuickTime Player. This kind of user experience is more consistent with Safari fullscreen Touch Bar's display.

<img width="755" alt="screen shot 2017-06-05 at 12 45 09 am" src="https://cloud.githubusercontent.com/assets/15068630/26763645/a3fbb2ac-4988-11e7-8931-65f69c8570b3.png">

**Comment by nhooyr** [comment]
I think remaining time should also be shown in the regular player.

<img width="1680" alt="screen shot 2017-07-02 at 2 33 08 am" src="https://user-images.githubusercontent.com/10180857/27767749-cdf36540-5ece-11e7-9061-3d7c6394e42a.png">

**Comment by nhooyr** [comment]
vs how it is in quicktime:

<img width="1680" alt="screen shot 2017-07-02 at 2 34 11 am" src="https://user-images.githubusercontent.com/10180857/27767756-f535fdf2-5ece-11e7-9411-022dfc186b51.png">

On the right, you get the time left, not the total time. It would be nice if we could have both in IINA.

**Comment by lhc70000** [comment]
@nhooyr You can toggle remaining time in `Preference > UI` or by simply clicking the label.

**Comment by nhooyr** [comment]
Perfect, sorry for the noise!
