### ISSUE TITLE
[Feature request] keep window inside screen bounds on pinch-to-resize

### ISSUE THREAD

**Issue by pryley** [lhc70000/iina#708]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.10

**Expected behavior:**

When you resize Movist with the pinch-to-zoom gesture, the window stays within the screen bounds where possible. It would be nice to see IINA provide this feature.

**Comment by megadr01d** [comment]
> When you resize Movist with the pinch-to-zoom gesture, the window stays within the screen bounds where possible.

I think this is possible because of the **Resize Center** option in Movist, right?

![Movist](http://i.imgur.com/ZFHG9.png)

Maybe you could add this suggestion to https://github.com/lhc70000/iina/issues/334.

**Comment by pryley** [comment]
> I think this is possible because of the Resize Center option in Movist, right?

No, regardless of the chosen "Resize Center" option in Movist, the video window still stays within the screen bounds when resizing instead of expanding outside of it.
