### ISSUE TITLE
Something wrong when using an external displayer

### ISSUE THREAD

**Issue by iHandle** [lhc70000/iina#709]
I connect an external displayer to my macbook.When I use iina with full screen mode at one of my displayer, another one would displayer nothing but a black screen.

**Comment by alejx** [comment]
你可以在设置里面取消勾选“全屏播放时使其他屏幕黑屏这个选项”。当前版本这个选项默认开启，我们会在下一个版本默认取消这个选项。

**Comment by NexusSix** [comment]
same problem here.  black screen on second monitor.  doesn't matter whether that option is checked or unchecked in preferences.

**Comment by alejx** [comment]
@NexusSix Can you provide more information?

**Comment by NexusSix** [comment]
iina 0.0.11 build 29 / mpv 0.25.0
sierra 10.12.3 
macbook pro 15 inch / mid 2010

I am connecting to a second monitor via mini display to hdmi adapter . 
I am not using separate spaces for each monitor.  
When 'Black out other monitors while in fullscreen' is checked or unchecked, result is the same: iina blacks out the non-fullscreen monitor.  

In VLC 2.2.4 i am able to enter fullscreen video playback on either monitor and the other monitor desktop remains visible.

**Comment by lhc70000** [comment]
@NexusSix What's the output of `defaults read com.colliderli.iina blackOutMonitor` in terminal?

**Comment by NexusSix** [comment]
@lhc70000 The domain/default pair of (com.colliderli.iina, blackOutMonitor) does not exist

**Comment by lhc70000** [comment]
@NexusSix Does this output change when you check/uncheck the option in preferences?

(Normally, it should output `does not exist` when the option is not checked, and `1` when checked.)

**Comment by NexusSix** [comment]
@lhc70000 Yes, it changes between `1` and `does not exist`.  
But on both settings, it blacks out the other monitor.

**Comment by JohnClay** [comment]
@lhc70000

I've run into this issue myself. It only presents when the option "Displays have separate Spaces" is enabled within the Mission Control pane of System Preferences is enabled. Any application that uses the system fullscreen function will black out other monitors as part of the legacy full screen mode. Unfortunately, for people that dislike having menu bars on external monitors, it's disabling that feature is the only way to go.

Any chance of a work around/fix?

**Comment by whirk** [comment]
> Any application that uses the system fullscreen function will black out other monitors as part of the legacy full screen mode. Unfortunately, for people that dislike having menu bars on external monitors, it's disabling that feature is the only way to go.

> Any chance of a work around/fix?

Same here, would love to go full screen without blacking out my other monitor and not have 2 separate menu bars..

**Comment by NexusSix** [comment]
VLC seems to implement a workaround this limitation.  

I guess it's a only a minor inconvenience to change the spaces configuration before watching a movie.

**Comment by whirk** [comment]
VLC takes care of this nicely. it will go fullscreen on whichever monitor the movie window originates in, or on the monitor selected as the default full screen display if selected in the preferences. it does not black out the other screen(s) unless that is selected as an option in the preferences.

It's more than a minor inconvenience to have to change the default settings in macOS which yields unwanted settings just to play a movie, especially when doing so requires a log-out before the setting is implemented. thus requiring another log-out to change the setting back again. this is a deal breaker. I'll be sticking to VLC until this feature/setting is properly addressed.

really hope you guys get this sorted out, would be great if you do!

**Comment by lhc70000** [comment]
Any app using native full screen has the same issue.

So the only solution would be implementing an optional legacy full screen mode like VLC.

**Comment by JohnClay** [comment]
> I guess it's a only a minor inconvenience to change the spaces configuration before watching a movie.

It's a fairly major inconvenience. I know I'm not going to change a system setting and log out/login in again in order to watch a movie. I'll just use VLC until it's fixed.

Another benefit of a legacy full screen mode is that it wouldn't use that silly full-screen animation that the system transition uses.

**Comment by megadr01d** [comment]
> Another benefit of a legacy full screen mode is that it wouldn't use that silly full-screen animation that the system transition uses.

Word.
