### ISSUE TITLE
Is there any possibility of Windows support?

### ISSUE THREAD

**Issue by RudraSaga** [lhc70000/iina#714]
I am assuming the answer is no but I wanted to double-check. Is there any interest in making IINA work on Windows? Since there aren't many GUIs for mpv that are compatible with Windows and are as feature-rich as IINA, I think it might do very well if IINA was available on Windows. 

I know Swift doesn't officially support Windows but there are third party options like http://www.elementscompiler.com/elements/silver/ and https://github.com/tinysun212/swift-windows that allow you to compile Swift on Windows. Plus Swift itself seems to work under the new Linux sub-system for Windows. I think the Touch Bar/Force Touch stuff might be an issue though.

**Comment by alejx** [comment]
Sorry. IINA, as a native app on macOS, uses Cocoa, which is unusable on any other platform other than macOS.

**Comment by RudraSaga** [comment]
Ahh...hadn't thought about that. 

I'll close this thread for now but I wonder if [GNUstep](http://www.gnustep.org/) would help with that.
