### ISSUE TITLE
cannot install the newest version

### ISSUE THREAD

**Issue by kuang7** [lhc70000/iina#716]
- macOS 10.12.
- IINA 0.0.10

Firstly, really thank for the application you create. it's wonderful and i strongly recommend it to my friends. the problem is the i downloaded from the https://lhc70000.github.io/iina/zh-cn/，but i can't install it. i clicked it but there was no response. i have installed  IINA 0.0.6 successfully. unfortunately, i deleted the old version.

**Comment by lhc70000** [comment]
@kuang7 请确认你将 .app 文件拖到了[

**Comment by lhc70000** [comment]
@kuang7 请确认你将 .app 文件拖到了 /Applications 文件夹。以及，是什么时候无响应？

**Comment by kuang7** [comment]
当我点击dmg.之后才会出现界面，我拖到里面就能安装。现在是点击了根本没反应。我将电脑更新到最新系统了，看看行不行。谢谢您的回复。

发自我的 iPhone

**Comment by lhc70000** [comment]
看看桌面上有没有出现 dmg 的图标？

**Comment by kuang7** [comment]
有的，就是正常的dmg图标，跟别的软件一样。这个情况之前更新0.0.7版本出现过，后来不知道怎么就好了。

发自我的 iPhone

**Comment by lhc70000** [comment]
那双击 dmg 图标不能打开么……

**Comment by kuang7** [comment]
是的，就是双击打不开。系统更新好了，解决了！我的系统是10.12的，现在更新到10.12.5就行了。我看你网站显示10.12就可以了，应该是电脑系统问题。谢谢您百忙之中回复，占用您宝贵的时间了。多谢🙏

发自我的 iPhone
