### ISSUE TITLE
升级后不能播放 .h264 的 ts 格式的文件

### ISSUE THREAD

**Issue by garfield45** [lhc70000/iina#717]
升级后不能播放 .h264 的 ts 格式的文件

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by garfield45** [comment]
勾选了  使用硬件解码  就无法播放.h264 的 TS文件

**Comment by lhc70000** [comment]
请参考 https://github.com/lhc70000/iina/wiki/正确的反馈姿势#iina-无法打开文件 提供更多信息。

**Comment by garfield45** [comment]
能打开播放，但是是解码问题，显示是绿色屏幕

**Comment by lhc70000** [comment]
mpv 默认不使用硬件解码。

如果你用开启了硬件解码（`--hwdec=auto`）的 mpv 0.25.0 测试仍能播放，请给我视频文件测试。

**Comment by lhc70000** [comment]
如果有更新，请 reopen。
