### ISSUE TITLE
Strange fullscreen animation

### ISSUE THREAD

**Issue by anonmonogatari** [lhc70000/iina#719]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
While entering fullscreen video should continue to play and should scale horizontally. Animation should be like quicktime's, smooth and with uninterrupted video playback.

**Actual behavior:**
Video stops while entering fullscreen and scales vertically.

**Steps to reproduce:**
Press F.

**How often does this happen?**
Always.

**Comment by alejx** [comment]
Duplicated with #566.
