### ISSUE TITLE
Pressing keybindings does not update settings section

### ISSUE THREAD

**Issue by anonmonogatari** [lhc70000/iina#720]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
Pressing '[' or ']' to change playback speed should change the pozition of horizontal slider which is the settings>video>speed section.

**Actual behavior:**
Pressing '[' or ']'  does not change the slider's pozition. It will updated once you oped settings again. Same problem also valid for pressing 'x' or 'z' to change subtitle delay.

**Steps to reproduce:**
Look these slider while pressing the keybindings that should effect them.

**How often does this happen?**
Always.

**Comment by alejx** [comment]
Closed. For further info, please follow #837 please.
