### ISSUE TITLE
Apple magic mouse滑动过于灵敏。

### ISSUE THREAD

**Issue by iTZQing** [lhc70000/iina#722]
Apple magic mouse滑动太过于灵敏，基本上导致此功能非常鸡肋。。。

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by iTZQing** [comment]
其实可以通过控制手速（拖动）来达到和QT player一样的效果，但。。太费神了😂

**Comment by lhc70000** [comment]
![07ced15e-3bf8-4c62-b4e4-3f223ef7029b](https://user-images.githubusercontent.com/8478049/26864610-a4c1fca0-4b8b-11e7-93b7-e4349b7077eb.png)
