### ISSUE TITLE
Original mpv options works?

### ISSUE THREAD

**Issue by ztxgeol** [lhc70000/iina#724]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

Just a quick question, I wonder, those original mpv options, like scale, works or not ATM?
I've added:
```
scale=spline36
dither-depth=auto
correct-downscaling=yes
sigmoid-upscaling=yes
deband=yes
```
by enabling adv option, I don't see any errors or effect ?

**Comment by lhc70000** [comment]
You can either
- Add options in `Preference > Advanced`
- Enable mpv config dir in `Preference > Advanced` and use your `mpv.conf`

Some issues on using mpv options are documented in https://github.com/lhc70000/iina/wiki/MPV-Options-and-Properties

**Comment by lhc70000** [comment]
1. These options are equivalent to `profile=opengl-hq`.
2. If you are not sure whether they are working, please [check their values in Inspector](https://github.com/lhc70000/iina/wiki/MPV-Options-and-Properties#inspecting-properties-at-runtime).
3. If they aren't applied, please check the mpv log and let me know.
