### ISSUE TITLE
Goes mute when switching application by sliding

### ISSUE THREAD

**Issue by igululu** [lhc70000/iina#726]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Continue playing without going mute

**Actual behavior:**

goes mute

**Steps to reproduce:**

pause by pressing space when playing full-screen
switch to an another  application (by sliding with 3 fingers)
switch back and play
voila! here comes the mime (can't be solved by pressing the sound on/off icon)
在全屏的时候按空格暂停
滑动三根手指切换到其他的应用
切换回来并播放
没声音了（按静音／非静音那个按钮也没用）

**How often does this happen?**
occasionally when I do this, but it goes right when I switch to another app and then back

**Comment by Miigon** [comment]
Have you tried switching by Alt+Tab?

**Comment by igululu** [comment]
@Miigon Tried, looks good to me. But can't be really sure without adequate rounds of test, I'll try later. Thx

**Comment by Miigon** [comment]
It just simply goes muted？I mean, the volume is still the same as before?

**Comment by igululu** [comment]
@Miigon Yup, checked before I issued this.

**Comment by igululu** [comment]
Occured once again just now, by sliding with 3 fingers.

**Comment by alejx** [comment]
I just confirmed this bug. Are you using EarPods? I can only reproduce it when I'm using EarPods.

I also noticed that while IINA is muted, iTunes is also muted. I don't think it's caused by IINA, so currently mark it upstream.

**Comment by igululu** [comment]
@alejx Not earpods, but Bluetooth speaker.

I agree with you on this. Thx a lot
