### ISSUE TITLE
I found that the version installed by brew cask is still 0.0.10.

### ISSUE THREAD

**Issue by luochengleo** [lhc70000/iina#727]
I found that the version installed by brew cask is still 0.0.10., while the up-to-date version is 0.0.11.

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by Miigon** [comment]
please run `brew update` before you use brew cask to install IINA
IINA 0.0.11 is already on brew cask

**Comment by TimurMisharin** [comment]
just do `brew update`, and after that do `brew cask reinstall iina`.
Enjoy.
