### ISSUE TITLE
iina是否有窗口多开的功能？

### ISSUE THREAD

**Issue by qzmoqzmo** [lhc70000/iina#728]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

由于iina的强大功能卸载了原先的movist。但是iina似乎只有一个窗口，每次打开不同的视频文件后，新打开的视频覆盖原本打开视频的窗口，无法做到同时播放多个视频，好像也没看到相应功能设置项。
想请教下是我自己看漏了呢还是软件本身没有附带这个功能？谢谢

**Comment by Miigon** [comment]
软件目前没有这个功能，多窗口从早前就作为计划中的事项，但是这个功能实现上尚有难点，短期内可能无法完成

**Comment by qzmoqzmo** [comment]
@Miigon 好的，感谢您的解答

**Comment by alejx** [comment]
Duplicate of #79. Closing.
