### ISSUE TITLE
[Feature request] Screenshot file name use video timestamp.

### ISSUE THREAD

**Issue by ebnbin** [lhc70000/iina#729]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Feature request: Use current video timestamp as screenshot file name.

For example: Use "VideoName-01_59_59_789.png" instead of "VideoName-0001.png" as file name of a screenshot. Accurate down to a milisecond.

So we can get a more detailed information of which frame that has been shotted.
I really want this feature!

This can be a preference, not the default config.

And I think it's not hard to work. ^ ^

Thank you very very very much!!!

Apologize for my poor English.

**Comment by lhc70000** [comment]
Please take a look at https://mpv.io/manual/stable/#options-screenshot-template.

You can add this as an extra mpv option in `Preference > Advanced`.

**Comment by ebnbin** [comment]
WOW! Wonderful!!! I haven't notice. Thanks!!!
