### ISSUE TITLE
Issue Related to Playback Rate Incremental Ratio

### ISSUE THREAD

**Issue by li-xinyang** [lhc70000/iina#73]
It starts from `1.0` and follows by `1.1`, `1.21`, `1.33`, `1.46`, ... I believe it is a bug.

![artboard](https://cloud.githubusercontent.com/assets/3349406/21739028/d0eee294-d4ca-11e6-93d1-0bece3190fc4.png)

**Comment by lhc70000** [comment]
It's not a bug.

<kbd>[</kbd> <kbd>]</kbd> are bind to "multiply speed by 1.1".

**Comment by li-xinyang** [comment]
Why don't make it using additional instead of multiplication

**Comment by lhc70000** [comment]
It's mpv's default key binding. You can change it in Preference > Keybindings and set them to anything you want.
