### ISSUE TITLE
[Crash] App crash in Preference > Advanced

### ISSUE THREAD

**Issue by ebnbin** [lhc70000/iina#730]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

I can't find "DiagnosticReports" in "~/Library/Logs/" but I just find a crash.

<img width="592" alt="2017-06-09 02 15" src="https://user-images.githubusercontent.com/8079186/26944111-5153067e-4cba-11e7-9c2e-f0816b1b7651.png">

In this state, the 'name' block is being edited, if I click "-"(remove), the app crashes!

How often: Always. I tried three times.

<img width="535" alt="wx20170609-022347 2x" src="https://user-images.githubusercontent.com/8079186/26944428-30d204e4-4cbb-11e7-8a70-b6495c644b4c.png">

Please fix it thanks!!!

**Comment by saagarjha** [comment]
I don't think this is a crash. Something's wrong, but it's not a crash.

**Comment by ebnbin** [comment]
I don't really know the OC code. If it is sure that this is not a bug of iina, may be something is wrong with my Mac. Thus, just let it go~~

**Comment by saagarjha** [comment]
No, this is most likely a bug in IINA. Just the crash reporter being weird today.
