### ISSUE TITLE
Player doesn't preserve display choice between total time and time remaining

### ISSUE THREAD

**Issue by TempSpas** [lhc70000/iina#731]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

By default, the On Screen Controller displays the time elapsed on the left of the progress bar, and the total time on the right. The user can click the total time to toggle it to display the remaining time. However, this setting is not preserved after the program is closed. Ideally the user's choice for this setting should remain.

**Actual behavior:**

The standard for players like the built-in Quicktime application as well as VLC have this setting preserve the user's previous choice. Currently IINA reverts back to the default total time.

**Comment by lhc70000** [comment]
You need to set it in preferences: UI > On Screen Controller > Show Remaining Time
