### ISSUE TITLE
Does the input box in the preference settings do not support `command v`?

### ISSUE THREAD

**Issue by shaodahong** [lhc70000/iina#732]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
preference settings do support `command v`！

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
I `command  c` a path ready to paste into the input box of youtube-dl,` command  v` no text and no paste into the input box, but I right-click menu can be pasted

**Comment by euf** [comment]
Seems to be connected with #663 issue, since all keyboard shortcuts do not work as expected in dialog boxes and text fields.

**Comment by shaodahong** [comment]
@euf Sure, but obviously it should not be

**Comment by megadr01d** [comment]
And duplicate of https://github.com/lhc70000/iina/issues/180.
