### ISSUE TITLE
Show a wrong subtitle / 显示错误的字幕

### ISSUE THREAD

**Issue by nsFraG** [lhc70000/iina#738]
IINA choose a wrong subtitle file when i played .mp4 video via USB driver.
There are some 'Homeland' episode/subtile and some 'Shameless'  episode (not include subtitles) at root folder.
When I play shameless .mp4 file, IINA always choose a homeland's subtitle automatic. 

我在U盘根目录同时存放着两部剧集和字幕文件，当播放Shameless剧集时，总是错误的显示Homeland的字幕文件

The bug shows in ver 0.0.10 and ver 0.0.11
IINA 版本 0.0.10 和 0.0.11 存在这个问题，之前没注意

![2017-06-11 01 37 28](https://user-images.githubusercontent.com/29339227/27005082-53f5bcf6-4e49-11e7-91d5-1bd50e8f972e.jpg)
![2017-06-11 01 56 05](https://user-images.githubusercontent.com/29339227/27005084-5821727a-4e49-11e7-905e-6c75b9b4ad22.jpg)

**Comment by lhc70000** [comment]
这是 0.0.10 中增加的自动匹配字幕。你可以在 `偏好设置 > 字幕` 中选择「包含媒体文件名的字幕」，就和 0.0.9 之前一样了。

请问
- 这个文件夹中有 Homeland 的视频么（以及文件名以 Homeland 开头么）？
- 能否给我**整个**文件夹内容的截图用来优化算法？

**Comment by nsFraG** [comment]
此问题无论在偏好设置中选择「包含媒体文件名的字幕」还是「由IINA智能选择」都会出现

原po第一张图右边就是根目录的文件
包括：
Homeland的视频文件.mkv及完整文件名的.ass .srt字幕文件
Shameless的视频文件.mp4无字幕文件

上述.mp4文件拷贝到桌面后，问题同样出现，但误读的字幕文件存放在桌面子目录，大致结构如下，中括号为目录名
[desktop]
  |- shameless.mp4
  |- [westworld]
       |- westworld.ts
       |- westworld.ass

如还需要截图，请告知

**Comment by lhc70000** [comment]
能否提供此目录下所有文件名的文字版？

- 在终端中输入 `ls` 加空格
- 将文件夹拖到终端，文件夹的路径会被复制进去
- 回车运行
