### ISSUE TITLE
Video Filter for Sharpness

### ISSUE THREAD

**Issue by bobbyy98** [lhc70000/iina#742]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.11

**Expected behavior:**

Setting `vf=sharpen=60` under Video Filter does not seem to have an effect.

Incidentally, it would be really nice if "Sharpness" can be adjusted under the Quick Settings Panel.

**Comment by lhc70000** [comment]
There's no `sharpen` filter in mpv. You can find a full `vf` list at https://mpv.io/manual/stable/#video-filters.

You can either use `sharpen` property or ffmpeg filters instead.

**Comment by mrelwood** [comment]
I miss this from VLC. How would one use the sharpen property or ffmpeg filters?

**Comment by lhc70000** [comment]
@mrelwood 

Video - Video Filters… - Add (`+` button) - Sharpen

Assign a shortcut to it if you need to toggle it on/off frequently.

**Comment by mrelwood** [comment]
Thanks lhc! Is there a way to make a saved filter active by default, on all videos?
