### ISSUE TITLE
Check the update error

### ISSUE THREAD

**Issue by shaodahong** [lhc70000/iina#743]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
![image](https://user-images.githubusercontent.com/14831261/27035547-50b54270-4fb4-11e7-848e-c6613bff3a4a.png)

Click to check for updates

**Comment by lhc70000** [comment]
请尝试在浏览器里访问 www.iina.io，如果无法访问，请告知地理位置及网络类型（电信/联通/移动）

**Comment by shaodahong** [comment]
@lhc70000 访问不了，上海浦东新区，长城宽带，我尝试下翻墙是可以的，难道被墙了？

**Comment by alejx** [comment]
@shaodahong 在我这里可以正常访问，此外也没其他无法访问的报告。被墙几乎是不可能的，毕竟目前还没多少流量。暂时先用 GitHub 更新吧，我们也会尽量想办法的。
