### ISSUE TITLE
onscreen layout controller

### ISSUE THREAD

**Issue by basavaraj1995** [lhc70000/iina#745]
onscreen layout controller hides while forwarding the media

**Comment by saagarjha** [comment]
FWIW, QuickTime does this as well, so I guess this is intended behavior. Was there any reason why you'd like it to remain on screen?

**Comment by basavaraj1995** [comment]
Yes
On-screen layout is required while forwarding media ...to check how much
length it is forwarded/moved

**Comment by saagarjha** [comment]
If that's all you need, just keep your cursor over the controls. IINA will keep it visible as long as you don't move off of it.

**Comment by megadr01d** [comment]
> to check how much length it is forwarded/moved

Isn't this also visible as an OSD message?

**Comment by basavaraj1995** [comment]
Yes. . but while forwarding media it shouldn't be hiding

**Comment by megadr01d** [comment]
It used to hide when [clicking a button in the OSC](https://github.com/lhc70000/iina/issues/273#issuecomment-287567840) but it was [fixed](https://github.com/lhc70000/iina/issues/273#issuecomment-291847525). Are you forwarding by clicking on the forward button or using the keyboard?
