### ISSUE TITLE
"float on top while playing" can't recover to normal while pause in full screen mode

### ISSUE THREAD

**Issue by bigfat** [lhc70000/iina#746]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

My setting is "Preference - UI - Always float on top while playing".

In normal window (not full screen), the video window stays on top while playing, and if I press spacebar to pause it, and switch to other window, the video window fall behind others. It's my expect. and works okay in normal window mode.

**Actual behavior:**

The problem is, if I press Spacebar to pause the video in full screen mode, and press Esc to quit full screen, the video window still stay on top. I have to play and pause the video one more time to make it not on top. I use this workflow frequently, so it's boring me.

**Comment by fyreswan** [comment]
This bug has come back for me today.
