### ISSUE TITLE
Longer Delay(0.3s) for Mouse Pause/Resume

### ISSUE THREAD

**Issue by genmao** [lhc70000/iina#748]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

Keyboard "Space" can instantly pause/resume, but single-click encounters much longer delay (around 0.3s) to do this.

**Comment by lhc70000** [comment]
@genmao It needs time to check whether you are double-clicking. Please disable double-click action if you really want instant reaction.

**Comment by alejx** [comment]
Actually the time depends on your system setting. You can change the interval in System Preferences > Accessibility > Mouse & Trackpad, change "Double-click speed". Note that this is an universal setting, and will effect the double-click behavior on your system.

![screen shot 2017-06-14 at 9 31 55 pm](https://user-images.githubusercontent.com/20237141/27134697-e642a608-5148-11e7-8f9f-d90d856168d3.png)

**Comment by genmao** [comment]
Thank you @lhc70000 @alejx for your timely reply. And yes, that is the reason for the delay, but I do think there is still some improvement we can make for the design logic. An obvious example is that when playing YouTube videos using chrome on the same machine, there is no such a long delay for either single click--> pause, or double-click-->full screen.

**Comment by saagarjha** [comment]
I'm pretty sure YouTube pauses itself at the first click, then resumes on the second one.

**Comment by genmao** [comment]
@saagarjha Negative. I just double checked, and double-click for YouTube is entering/exit full screen mode. 
Besides, I also performed following test: I set system's double click speed to lowest, and then IINA's single click -> resume/pause delay would be very long (1.5s or so), but youtube's single click still have no delay, and double click-> full screen function still works fine. 
Per this result, I think youtube's response to single click has better user experience, and I hope IINA could make some improvement on the judgement for single/double click. 
Thank you.

**Comment by saagarjha** [comment]
> I just double checked, and double-click for YouTube is entering/exit full screen mode.

Yes, I know that. At least on my system (which might be behaving oddly, since it's in beta), double clicking performs the following:

* First click: Pause the video
* Second click: Resume the video and move into full screen

For IINA:

* First click: Wait for second click with a delay, then pause the video
* Second click: Immediately move into full screen

**Comment by lhc70000** [comment]
It's OK to imitate Youtube's behavior, but there're some technical difficulties:

- IINA will show OSD when pause or resume
- IINA's single click & double click actions are configurable

**Comment by genmao** [comment]
@saagarjha That's the point (and sorry for misunderstanding). And @lhc70000 whether to change this behavior fully depends on your choice~ But at least, it might not meet users' expectation to wait for 2 seconds after single click to pause/resume current video stream just because of their setting of double-click speed. ^_^
