### ISSUE TITLE
字幕的反馈

### ISSUE THREAD

**Issue by zhoubingyi** [lhc70000/iina#75]
1. 字幕文件希望能直接直接拖入载入
2. 字幕显示希望可以显示在画面外，不在视频画面里
3. 字幕背景颜色不小心点到后，没找到怎么改为透明

**Comment by lhc70000** [comment]
感谢反馈。

1. 与 #3 重复
2. 与 #43 重复
3. 与 #9 重复

**Comment by lhc70000** [comment]
1 和 3 已经修复，故关闭此 issue。
对于第二点，请移步至 #43。
