### ISSUE TITLE
请问IINA如何使用SVP4?看到官网写着是支持的！

### ISSUE THREAD

**Issue by varjay** [lhc70000/iina#750]
请问IINA如何使用SVP4?看到官网写着是支持的！

**Comment by xjbeta** [comment]
"requires libmpv built with Vapoursynth support"
from  https://www.svp-team.com/wiki/SVP:Mac
尝试自行编译

**Comment by mozii** [comment]
按照 wiki 操作了，并不好使，而且 wiki 的简明版和长版说明，在填写参数的时候，不一样？

**Comment by HarukaMa** [comment]
@mozii 参数两种都可以，只是简单和复杂的区别。

不好使的话过程中有没有报错一类的？

**Comment by mozii** [comment]
嗯嗯，建议文案稍作修改，我当时是懵了的😳哈。后来反复测试发现可能是因为视频分辨率过高，引起了crash。换了低分辨率的 MP4，好使了。
