### ISSUE TITLE
[Feature] Please add feature to view video info

### ISSUE THREAD

**Issue by jacky0karl** [lhc70000/iina#751]
IINA is a excellent player, the best one I have ever used on macOS. Could you please add a new feature to view video info, which would make IINA more outstanding :)

**Comment by lhc70000** [comment]
Cmd+I

**Comment by jacky0karl** [comment]
Thanks a lot for your reply, good to know that this feature is exist already. But some mkv file will show video bit rate as 0bps, which is using h264 codec, could please check it.

**Comment by alejx** [comment]
> But some mkv file will show video bit rate as 0bps, which is using h264 codec, could please check it.

Can you open another issue about that?
