### ISSUE TITLE
Cannot get "Open in IINA" prompt in Chrome Extension again

### ISSUE THREAD

**Issue by vphong** [lhc70000/iina#754]
I installed Open in IINA for Chrome for the first time, and accidentally ticked "Remember my choice" and "Do not open" for IINA URIs. Now the extension doesn't do anything. I've tested on Youtube, Vimeo, and Twitch (which are supported by youtube-dl) - nothing. 

Now I'm trying to get the protocol request prompt to open again, but no luck. Does anyone have any suggestions?

I've tried:
- uninstalling Open in IINA, quitting Chrome, and reinstalling Open in IINA
- uninstalling, quitting Chrome, deleting ~/Library/Application Support/Google/Chrome/Default/Local State, and reinstalling Open in IINA
- looking for "protocol_handlers" to modify in Local State - none found in the file

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11 build 29

**Steps to reproduce:**
1. Install Open in IINA Chrome extension
2. Attempt to use Open in IINA on a supported website
3. Tick "Remember my choice" on the protocol request
4. Click "Do not open"

**Comment by lhc70000** [comment]
I have no idea about this either - all my searches point to the file `~/Library/Application Support/Google/Chrome/Local State`, and if you can't find `protocol_handlers ` or `iina` in it, perhaps you need to ask the developer or in a Chrome related community.

**Comment by bitfrickler** [comment]
Had the same problem. Just found the solution:

In ~/Library/Application Support/Google/Chrome/Default/Preferences:
Under protocol_handler -> excluded_schemes there is an entry for "iina". Delete that line and the confirmation prompt will appear the next time.

**Comment by vphong** [comment]
Thanks for replying, I tried using Open in IINA again and I got a prompt this time. Works perfectly now. I didn't change anything in `Preferences` or `Local State` since cmd+f "iina" came up with 0 results. I'm gonna guess that an update to Chrome fixed it.
