### ISSUE TITLE
关于播放控制UI的一些建议

### ISSUE THREAD

**Issue by mywp** [lhc70000/iina#755]
系统： macOS 10.12.5
版本： IINA 0.0.11

关于播放控制界面的一些建议：
开始用这个软件的时候我是非常惊讶的，非常强大和好用，不过我有点强迫症啊，喜欢各种设置在显眼的地方，所以我提出一些播放控制的一些建议。第一：能不能在底部播放控制那个UI上面增加播放速度？点击设置再设置播放速度有点繁琐，因为看一些视频习惯了更改播放速度了。第二：还有就是底部播放控制的UI能不能设置成在鼠标一移动到那个区域就显示出来，移走后立即消失呢？因为影响字幕，我外语水平有限...还要瞄一眼字幕，我设置自动消失时间为0到2.5之间都达不到效果，要么鼠标重新移到播放控制区域后播放控制不显示出来，我设置回原来的2.5秒也不行了...不显示播放控制界面了，在播放器界面上鼠标一直闪烁，肯定出问题了。第三个建议：按空格暂停播放的时候能不能显示播放控制界面，相信很多人暂停都是看一下这个来确认一下播放控制的信息的，比如说进度条，左上角显示的那个时间没进度条那么直观。一直喜欢看进度条而不是时间那个数字。原谅我这么任性。

**Comment by iHandle** [comment]
我列出一些我个人的解决方案吧，希望可以帮到你：
一、IINA默认有调节播放速度的快捷键 `[`是减速，`]`是加速，`delete`是原速；
二、为了不挡住字幕，我把控制栏固定在视频窗口的顶部
至于第三个需求的话我暂时没有什么建议了。

**Comment by lhc70000** [comment]
> 第一

大家都想在播放控制条里加各种各样的功能，所以最好的选择是什么都不加（以后会有可选的全屏/pip 等按钮，但是不会把速度这么复杂的东西加进去）。

> 第二

有可能会加入，但更推荐你把播放控制移动一下（鼠标可以拖拽）

> 第三

现在没看到很多人有这样的需求，应该不会实现

**Comment by huanghantao** [comment]
我按暂停是为了截图，显示控制界面不太好
