### ISSUE TITLE
[BUG] CANNOT DISPLAY SUBTITLE!

### ISSUE THREAD

**Issue by adamzjk** [lhc70000/iina#757]
- I posed this issue about a month ago, after uploading my log file, someone said it's encoding problem, and somewhat the subtitle is displaying again( I don't know why) so i closed the issue

- **but now it happens again**, i'm using the latest version of IINA and macOS.  **This is not encoding problem**. Some videos which its subtitle could be displayed now could **NOT** after I opened an video(a movie) that cause the same problem a month ago (I'm not sure it's the reason that cause the problem). 

- anyway the subtitle just suddenly not displaying! 

- `Find Online Subtitle` gives me **unsupported external subtitle** error and this error still happens even when I tried with the video that  `Find Online Subtitle` works fine yesterday.

- subtitle, build-in or external, however, could be displayed in other player(mvp, 暴风影音)

This is the log file.
[2017-6-16-20-19-46_d55lkS.log.zip](https://github.com/lhc70000/iina/files/1080783/2017-6-16-20-19-46_d55lkS.log.zip)

I deem this a very serious BUG since people are reluctant to watch a movie without subtitle, especially in foreign languages.

**Comment by lhc70000** [comment]
The Reason:

You have `sub-visibility=no` in your `watch_later` file. It's saved together with your playback progress so when you resume, it applies automatically. In previous version (~0.0.6), "v" key was bound to `sub-visibility` so you may triggered it by mistake.

---

Solution:

**1. Please run the following command in terminal:**

```
grep sub-visibility ~/Library/Application\ Support/com.colliderli.iina/watch_later/*
```

And then delete all files listed in the output.

 (or you can delete the entire `~/Library/Application\ Support/com.colliderli.iina/watch_later` folder)

---

**2. Please double check that you don't have "v" key bound to "Subtitle visibility". If so, please delete it** (especially if you duplicated a key binding config in older versions).

**Comment by adamzjk** [comment]
Thanks! 

I solved the problem by just
`rm ~/Library/Application\ Support/com.colliderli.iina/watch_later/*`
Maybe it not appropriate but problem solved.
