### ISSUE TITLE
Keyboard shortcuts do not respect current keyboard layout

### ISSUE THREAD

**Issue by unmanbearpig** [lhc70000/iina#759]
I prefer MPV keybindings and I'm using Dvorak, but IINA treats keys as if I had QWERTY layout. For example Always On Top is `Shift-T` in MPV, so when I'm using Dvorak I press the key that used to be `K` in QWERTY, because it's `T` in Dvorak. In IINA I have to press the QWERTY `T`, which is `Y` in Dvorak, not `T`. So for me all keybindings are completely different from MPV. I'd love to have a way to have the same bindings as in MPV.

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11 Build 29

**Expected behavior:**
IINA's "MPV Default" keybindings should be the same as in MPV.

**Actual behavior:**
IINA's "MPV Default" keybindings work as if I'm using QWERTY layout in MPV.

**Steps to reproduce:**
- Use "MPV Default" keybindings
- Switch to Dvorak in macOS
- Press `Shift-<key that is labeled K on standard keyboard>`. 
- It should toggle Always on Top like in MPV, but it does something else instead.

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by sCreami** [comment]
Cross referencing with #191

**Comment by lhc70000** [comment]
Fixed in develop.
