### ISSUE TITLE
头脑风暴，建议增加「彩蛋功能」每次从头播放一部电影时，先播放指定文件作为“伪片头”。

### ISSUE THREAD

**Issue by DearTanker** [lhc70000/iina#763]
我想在播放电影前默认先播放IMAX片头，假装自己在电影院看IMAX。

https://pan.baidu.com/play/video#video/path=/IMAX各种片头/IMAX.Intro.Show.1080p.mkv&t=-1

你们不觉得看IMAX的片头很爽很HIGH很有带入感吗？

设置可以增加一个开关，可以制定本地的某个文件（这样用途变得更个性化了。）

播放的时候也支持任意按键快速跳过即可。

看电影前先播放一下觉得 MindBlowing。体验绝对不一样。

**Comment by csujedihy** [comment]
???

**Comment by DearTanker** [comment]
@csujedihy 是的，这看起来挺无聊的。简单讲就是：

当播放一部电影前，会先播一段片头，然后才真正开始播放电影。
