### ISSUE TITLE
Subtitle not found

### ISSUE THREAD

**Issue by lorenzofanchi** [lhc70000/iina#764]
IINA is not finding subtitles for movies that are definitely available on OpenSubtitles. Maybe a problem with parsing the movie filenames? Often filenames have dots instead of spaces, could that be the problem? Downloaded movies can contain release info etc.

Would be happy to provide additional info, if necessary..

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Comment by lhc70000** [comment]
IINA now searches subtitles only by file hash.

@alejx is working on a fix.

**Comment by gtulga** [comment]
Filename is Split.mp4, but not found movie subtitle. is there any option to find subtitle manually?

**Comment by ruslaniv** [comment]
Still does not work, as confirmed by several threads here. I can see that subtitles are present on the site, but the app still can't find them
