### ISSUE TITLE
Failure to detect and autoload subtitles

### ISSUE THREAD

**Issue by TempSpas** [lhc70000/iina#767]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

IINA should automatically load relevant subtitle files when opening videos.

**Actual behavior:**

IINA does not detect or load any external subtitle files. I generally keep folders that contain only a video file and the corresponding subtitle file, both of which have the same name. With its default setting, "Detect intelligently by IINA," the program would never load the subtitle file, forcing me to drag and drop the file into the playing video for it to appear. I switched the setting to "Subtitles containing media filename," but that does not autoload the subtitles either.

Subtitle files are almost always .srt files, video files vary and I have tested it with .mp4 and .avi files.

**Comment by lhc70000** [comment]
I can't reproduce this issue. Please provide more info:

- The output of `defaults read com.colliderli.iina subAutoLoadSearchPath` and `defaults read com.colliderli.iina subAutoLoadIINA`
- A screenshot of your directory structure and the full filename
- Have you tried some simple cases like the following?
  ```
   folder/
     abc.mp4
     abc.srt
  ```

**Comment by TempSpas** [comment]
Here's a screenshot of a directory that illustrates what's happening.

[Directory screenshot](http://i.imgur.com/dSr4l9T.png)

It contains just two files, in this case I've taken your suggestion and renamed them to the simple names "abc.avi" and "abc.srt." IINA doesn't load the subs at all. As for the outputs:

Input: `defaults read com.colliderli.iina subAutoLoadSearchPath`

Output: `The domain/default pair of (com.colliderli.iina, subAutoLoadSearchPath) does not exist`

Input: `defaults read com.colliderli.iina subAutoLoadIINA`

Output: `1`

Hope that helps.

**Comment by lhc70000** [comment]
![875fc197-c5bf-4645-b095-200a1f52f80a](https://user-images.githubusercontent.com/8478049/27954468-b3b7ca4a-6342-11e7-92df-be7037e08dbc.png)

It works for me. Would you mind if I send you a test build to collect more log?

**Comment by TempSpas** [comment]
Sure, I could give that a shot. What do you need me to do?

**Comment by lhc70000** [comment]
https://drive.google.com/open?id=0B7tEU25gz8nhTmlkOEpScUg3MVk

This build also contains some other new features (thumbnail preview, multiple windows support), but it's a debug build so not recommend for daily use.

Please follow these steps:

1. Open "Console.app", type "IINA" in the search bar and press enter. Not it will only display logs from IINA.
2. Launch the debug build and play a problematic file as usual
3. It should log some details about auto loading. Select all by Cmd+A and then Cmd+C to copy them.
4. Provide me the log either by pasting here or uploading a text file.

Thanks in advance.

**Comment by TempSpas** [comment]
Done, the log is attached. The setting is still "Detect intelligently by IINA" and the files are the ones in the previous screenshot.

[iina_sublog.txt](https://github.com/lhc70000/iina/files/1132372/iina_sublog.txt)

**Comment by lhc70000** [comment]
Thanks for prompt response. Well, seems that it didn't even started loading files and searching for subtitles.

Please try this one again: https://drive.google.com/open?id=0B7tEU25gz8nheTBqS0xybFZ5dzQ, and also please tell me how you open a file (like double clicking from finder, drag-and-drop to dock icon, from menu, etc).

**Comment by TempSpas** [comment]
No problem. Typically I will right-click the file and select "Open with" --> IINA. When I ran on the test builds, I drag-and-dropped the file to the default window both times. Here's the log from the second build (still unsuccessful):

[iina_sublog2.txt](https://github.com/lhc70000/iina/files/1132454/iina_sublog2.txt)

**Comment by lhc70000** [comment]
Found the problem. It will only match subtitles when you enabled "add files to playlist automatically" (because the algorithm needs to search for all files in the folder). I'll fix this.
