### ISSUE TITLE
视频会循环播放

### ISSUE THREAD

**Issue by kunx-edu** [lhc70000/iina#769]
实在抱歉，我并不擅长英文，无法用英语描述问题。

OSX系统，不知道按了什么快捷键，最近发现视频播放完毕会回到视频的某个位置再次播放，退出软件，重装软件，重启系统，都不行，明明列表中有很多视频的。

求帮助，感谢。

**Comment by lhc70000** [comment]
是否不小心开启了 AB 循环？
