### ISSUE TITLE
外接显示器黑屏

### ISSUE THREAD

**Issue by mgdreamingstar** [lhc70000/iina#773]
Mac 使用 iPad 作为外接屏幕（使用 duet display 实现) 时，iPad 无法播放视频（黑屏）。但能够正常播放音频。

**Comment by lhc70000** [comment]
@mgdreamingstar 窗口模式下仍然没有视频？

**Comment by mgdreamingstar** [comment]
是的，窗口模式也一样。

**Comment by alejx** [comment]
Maybe related to #504
