### ISSUE TITLE
Does It Support YouTube Playlists?

### ISSUE THREAD

**Issue by asoksevil** [lhc70000/iina#774]
**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.11

**Expected behavior:**

If you use youtube-dl, with terminal and mpv playlist URL you launch MPV with all the videos in it. Considering IINA is actually using youtube-dl, I thought it supported it but it doesn't.

**Actual behavior:**

It only loads the first video of the playlist and it isn't shown not the chapters menu.

**Comment by lhc70000** [comment]
Yes, and it actually worked in previous versions. I'll have a check.

**Comment by asoksevil** [comment]
Any updates regarding this?

**Comment by lhc70000** [comment]
Confirmed that it works in latest develop branch.

**Comment by pbassham** [comment]
I still can't get this working.

**Comment by donut** [comment]
I'm not seeing how to get this to work with 1.0.2 Build 105. It still just plays the first video of the playlist.
