### ISSUE TITLE
play non-exist file in playback history window, app unexpectedly quits.

### ISSUE THREAD

**Issue by darkbrow** [lhc70000/iina#776]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When play file in playback history window, if file or url is unavailable, show error or warning message.

**Actual behavior:**
App just quits.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
Fixed in 0.0.12.
