### ISSUE TITLE
请问我这是什么问题

### ISSUE THREAD

**Issue by FirstAurora183** [lhc70000/iina#779]
![image](https://user-images.githubusercontent.com/16569751/27668663-0937813e-5cb5-11e7-8858-b5bffab9d33e.png)
![image](https://user-images.githubusercontent.com/16569751/27668667-103701bc-5cb5-11e7-88f8-f7563483a6d5.png)
iina播放器是需要用xcode进行编译的吧，为什么我这编译报错？
或者说我操作的有问题，求解

**Comment by lhc70000** [comment]
没有用自带的 dylib？

**Comment by FirstAurora183** [comment]
我打开的 xcworkspace 编译的，没改东西。用iina.xcodeproj编译好像提示找不到库。

**Comment by FirstAurora183** [comment]
编译iina还需要安装mpv吗？这个我没装。

**Comment by lhc70000** [comment]
`pod install` 了么？

如果按照 readme 来的话理论上不会有问题。就两步，`pod install` 和打开 `.xcworkspace`。

**Comment by FirstAurora183** [comment]
pod install了。mac os 12.12.5  version 0.0.11
![image](https://user-images.githubusercontent.com/16569751/27669179-15c8eda4-5cb8-11e7-81e7-1966f545428e.png)
![image](https://user-images.githubusercontent.com/16569751/27669210-39efb442-5cb8-11e7-86be-79eca5b90c09.png)
确实是就两步操作，下载用的 Github desktop clone的

**Comment by inflation** [comment]
@FirstAurora183 你看看装ffmpeg了么，然后`ls -lr /usr/local/opt/ffmpeg`把结果放上来

**Comment by FirstAurora183** [comment]
ffmpeg 装完编译就能通过啦，不报错了。非常感谢！

**Comment by lhc70000** [comment]
@FirstAurora183 感谢指出，确认这是 IINA 的问题。请删掉 ffmpeg 之后，更新到最新的 `develop` 分支并再次测试。现在应该不需要 ffmpeg 了。
