### ISSUE TITLE
Flic files have playback issues

### ISSUE THREAD

**Issue by DominusExult** [lhc70000/iina#781]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

- I've assigned iina to always open flics (*flc) files. When iina is closed and you doubleclick a flic iina should open and playback the flic.

- Also when playback is finished clicking on play should play the animation again.

- "seeking" in the file, adjusting the playback time slider should change the frame of the playback

**Actual behavior:**

- When iina wasn't open before and played another movie file, iina opens to a black window and does not playback the file (it does though in 1 of 10 tries). Doubleclicking the file again *mostly* starts the proper playback. Sometimes it takes more than three tries.

- When playback is finished, clicking on play should restart the animation.

- seeking doesn't work - the time slider is not acting at all for flc

**Steps to reproduce:**

- Download https://www.dropbox.com/s/tb599e6ebv17quc/01castle.flc.zip?dl=0 and assign iina to always open flx files.
- Close iina
- doubleclick the flc file

(Quicktime player 7 correctly plays flc files for comparison)

- [x] MPV does not have the black screen problem
- latest build of MPV seems to autoclose after playback so, can't test for the play again issue
- in MPV trying to adjust the time slider crashes MPV when playing back flc

**How often does this happen?**
always

**Comment by lhc70000** [comment]
For seeking, it seems like a decoding problem of mpv (You'd better to report this issue to mpv too). Current version of IINA uses mpv 0.25.0, so if you are using a `develop` build, the behavior may be different. Anyway, I'll test it out first.

**Comment by DominusExult** [comment]
Just made a bug report in mpv as well https://github.com/mpv-player/mpv/issues/4564.
MPV version was 0.25.0
