### ISSUE TITLE
Controller fails to hide

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#784]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.11

**Actual behavior:**

- Click and hold a button.
- Move mouse off of the controller.
- Let go of the mouse.
- Controller fails to hide.

**Expected behavior:**

Controller hides properly.

**How often does this happen?**

Every time.

**Comment by lhc70000** [comment]
I don't think it's an issue.

This what you get when trying to do the same on a normal `NSButton`:
- With mouse: the button won't be triggered.
- With trackpad: the behavior is rather strange, like the system still thinks the cursor is on the button, until you click somewhere again. 

IINA is doing nothing wrong here, and if `NSTrackingArea` is not sending us the event, that should be the way how macOS designed to handle it. We are not responsible for unusual user actions like this, and there's even no API to check such a event.
