### ISSUE TITLE
改进建议：字幕源

### ISSUE THREAD

**Issue by keanusun** [lhc70000/iina#790]
shooter只有库存字幕没有更新字幕，opensubtitles中文字幕并不多也跟不上更新。
建议增加sub HD这种现在很火的，能第一时间上各大字幕组新翻译作品的字幕源作为中文字幕源。

**Comment by lhc70000** [comment]
@keanusun subhd 没有 API；我们准备用射手网（伪） assrt.net

**Comment by CatTail** [comment]
@lhc70000 What's the progress of third party subtitle support?
