### ISSUE TITLE
Play/Pause signal from earphones are not captured by IINA

### ISSUE THREAD

**Issue by swj1442291549** [lhc70000/iina#791]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

When IINA is running, the play/pause button from the **earphones** should be able to perform their functions.

**Actual behavior:**

When only IINA is running, the play button would open iTunes.
When iTunes is also in the background, the button on the earphone will control the iTunes.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

Everytime

**Comment by alejx** [comment]
It's a known issue. Stay tuned!
