### ISSUE TITLE
Targa screenshot format won't work 

### ISSUE THREAD

**Issue by alayliercan** [lhc70000/iina#792]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Being able to create video screenshots in Targa image format.

**Actual behavior:**

Having selected TARGA format for screenshots, whenever I open the app I get the following error message:

![alt text](http://i.imgur.com/PizEllX.png "Error Message")

And the app won't take any screenshots any longer unless I change the screenshot format to something like JPEG, or PNG.

**Steps to reproduce:**

1) Go over Preferences > General > Screenshots
2) Change format into _TARGA_ by using dropdown list
3) Close the window and quit the application
4) Next time you open the application you'll see an error message and _S_ key won't work to take screenshots.

**How often does this happen?**

It happens whenever you open the app if the TARGA is the currently active screenshot format.

**Comment by lhc70000** [comment]
The current version of mpv only supports png and jpg. I'll remove the other options from UI.
