### ISSUE TITLE
Last volume setting is not remembered

### ISSUE THREAD

**Issue by atomicsaiko** [lhc70000/iina#795]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Resume with last set volume (100% in my case) from previous IINA session.

**Actual behavior:**

Starts with default set at 50%.

**Context:**

I believe 100% is the only correct 'initial default' setting, regardless whether that is too loud or soft to the ear. In order to achieve maximum sound quality you want to avoid software interfering with volume. The volume knob on the DAC or amplifier does a better job. Hence in software volume set to 100% is preferred. Now if you listen straight away from headphone jack to a pair of headphones, then only adjust volume on the Master audio output in OS. Else we would have IINA doing software volume adjustment, and then the OS doing another software volume adjust on the Master audio output device.

**Comment by xjbeta** [comment]
![img](https://i.imgur.com/Cs7Ywe2.jpg)
Set volume to the value you want.
Restart iina.

**Comment by atomicsaiko** [comment]
I confirm this works. Thanks!

**Comment by lhc70000** [comment]
I think it's a good suggestion. @alejx let's reopen it before fixing the default volume.

**Comment by atomicsaiko** [comment]
Additionally, maybe an option can be added to _map_ the volume slider in IINA to the Master audio output in the OS.
