### ISSUE TITLE
AirPods should pause the playback when taken off

### ISSUE THREAD

**Issue by fabiocody** [lhc70000/iina#799]
**Feature Request**

- macOS 10.12.5
- IINA 0.0.11

My AirPods don't pause the playback when I take them off, and I know this is possible since other apps do it, so I was just asking if this could be added/fixed in some later version. Thanks

**Comment by saagarjha** [comment]
@fabiocody Could you name an app that does this? It will help us figure out how best to add this feature.

**Comment by saagarjha** [comment]
Might also be related to #791.

**Comment by fabiocody** [comment]
Of course iTunes does it, and also Safari when using HTML5 player. At the moment, IINA is the only non-Apple player I have, so I will download and test some other players and see if they do it. I'll let you know

**Comment by PhilSwn** [comment]
I think [MPRemoteCommandCenter](https://developer.apple.com/library/content/samplecode/MPRemoteCommandSample/Listings/README_md.html) is relevant. 

> The ability for media applications to support the automatic pause and play functionality with the AirPods when taking them in and out of the ear.

 
And it's supported in:

> macOS 10.12 SDK or later
> Swift 3.0
