### ISSUE TITLE
Add CI(Continuous Integration) in development flow

### ISSUE THREAD

**Issue by skyline75489** [lhc70000/iina#800]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

https://travis-ci.org/ for starters. It's free for open source project.

**Comment by alejx** [comment]
Someone has issued before. #94 & #277

**Comment by skyline75489** [comment]
Wow, should've searched. My bad.

**Comment by alejx** [comment]
Add your opinions into the existing issue!
