### ISSUE TITLE
播放mkv文件会偶尔卡顿

### ISSUE THREAD

**Issue by applebug007** [lhc70000/iina#805]
在播放mkv文件时候会一会卡一下，掉帧。

**Comment by lhc70000** [comment]
https://github.com/lhc70000/iina/wiki/正确的反馈姿势#iina-在播放文件时有卡顿花屏等现象

**Comment by oscar-c** [comment]
I experienced this issue. It's rare. I think the reason could be leaving the video paused for too long.
The lag lasts for 1~2 second, and occurs every ~20 second. The CPU usage when the lag happens at 40%. Restart IINA fixes the problem.

**Comment by lhc70000** [comment]
请检查 `video-sync` 选项的值（在 `检查器-状态` 中可以添加监视）。

如果是 `audio` 以外的值且你没有主动设置过它，请排查是否有 mpv.conf 或 lua 脚本（目前发现一个修改过的 `vo_battery.lua` 会导致此问题）对它做了修改。

**Comment by suerb** [comment]
`video-sync` 的值是 `auto`。
仍然卡顿。
请问是否不需要安装 mpv，直接安装 https://lhc70000.github.io/iina/ 里面的包就可以使用？

**Comment by inflation** [comment]
@suerb IINA已知问题 #741 

而且，`video-sync`没有`auto`的选项。
