### ISSUE TITLE
AirPlay Support is a Good to Have Feature

### ISSUE THREAD

**Issue by li-xinyang** [lhc70000/iina#81]
This is a feature request. The player could have an option only stream the video to Apple TV or AirPlay support devices without mirroring the system like the player in the screenshot below. 

![screen_shot_2017-01-07_at_6_20_58_pm](https://cloud.githubusercontent.com/assets/3349406/21741054/361bb094-d506-11e6-9aec-f416d08c68cf.png)

The player used above is *WebTorrent* (https://github.com/feross/webtorrent), a torrent streaming video player built using Electron.

**Comment by lhc70000** [comment]
Thanks for feedback.

Duplicate with #63.
