### ISSUE TITLE
怎样另存在线下载的字幕？

### ISSUE THREAD

**Issue by wfwdex** [lhc70000/iina#813]
视频匹配到了一个不错的字幕，想下载回来用ffmpeg集成到视频里。

按照源码找到临时目录(/var/folder/xxx)，只找到从射手网上下载下来的3个字幕文件（字幕面板里有7个想要下载的那一个并不在这3个里面）

请问我想另存的那个字幕文件是在哪个网站里下载到的？需要到哪里找？（我到OpenSubtitles.org里也没搜到）

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Comment by wfwdex** [comment]
多谢，已经解决，功能好强大。😀👍

**Comment by hzx505** [comment]
【下载字幕路径】
/Users/xi/Library/Caches/com.colliderli.iina/fsCachedData

**Comment by xiaosongz** [comment]
> 菜单中 `字幕 > 保存下载的字幕`。你也可以为它设置快捷键。
> 
> > 请问我想另存的那个字幕文件是在哪个网站里下载到的？需要到哪里找？
> 
> 射手网的 API。本站已死，但是现在各大中文字幕站应该都有它的字幕库备份。

请问如何设成快捷键呢？

**Comment by zhjrcc** [comment]
> 【下载字幕路径】 /Users/mynamei/Library/Caches/com.colliderli.iina/fsCachedData

你保存字幕，然后在你当前播放的文件路径中就能找到，不需要到缓存中查找的
