### ISSUE TITLE
More verbose info about video and audio track

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#817]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
![Movist](http://d.pr/i/4TAH5N+)
This could be useful when a file contains multiple audio tracks, and one audio track is 5.1 ch, and the other is the down mixed 2 ch version. My example here isn't perfect.

**Actual behavior:**
![IINA](http://d.pr/i/kZVqWq+)
Most of the space to the right of the brief description is not used anyway.

**Comment by alejx** [comment]
There is more info in the inspector. You can activate it by <kbd>cmd</kbd>+<kbd>i</kbd>.

**Comment by oscar-c** [comment]
This would work, but not ideal.
For example, consider this case:
![Inspector Window Screenshot](http://d.pr/i/R9RdUl+)
In order to find the right audio track, I have to go through each option. Life would be easier if the Movist style could be used.

**Comment by lhc70000** [comment]
Added in develop branch.
