### ISSUE TITLE
Migration to Swift 4

### ISSUE THREAD

**Issue by saagarjha** [lhc70000/iina#819]
Just wanted to open an issue to track the migration to Swift 4. Currently, IINA fails to build even in "Swift 3" mode in Xcode 9 due to its dependencies (will list below as progress continues); I think we'll have to go nag them to update to Swift 4.

**Comment by saagarjha** [comment]
GzipSwift has a bad modulemap, resolved by using the swift4 branch.

**Comment by saagarjha** [comment]
MASPreferences is having issues with `NSUserInterfaceItemIdentifier`: https://github.com/shpakovski/MASPreferences/issues/54
Currently falling back to fork: https://github.com/saagarjha/MASPreferences

**Comment by saagarjha** [comment]
GRMustache needs updating to Swift 4.
Currently falling back to fork: https://github.com/saagarjha/GRMustache.swift

- [X] Pull request filed: https://github.com/groue/GRMustache.swift/pull/46
- [ ] Pull request merged
- [ ] Pod updated

**Comment by saagarjha** [comment]
Just needs updating to Swift 4.
Currently falling back to fork: https://github.com/saagarjha/Just

- [X] Pull request filed: https://github.com/JustHTTP/Just/pull/83
- [ ] Pull request merged
- [ ] Pod updated

**Comment by skyline75489** [comment]
@saagarjha With the help of Swift 4, maybe we can just drop usage of libraries like Just?

**Comment by lhc70000** [comment]
@skyline75489 Maybe AEXML, but not Just please, it's lightweight enough, and we need a networking library for both current and potential need in the future.

**Comment by skyline75489** [comment]
@lhc70000 I should've made my point clear. With the help of Swift 4 and its new `Codable` API, JSON parsing would be easier. `Just` is basically as easy-to-use as an `NSURLSession + NSJSONSerialization` wrapper when it comes to simple HTTP GET. On the other hand, if you want further possibility, `Just` isn't as popular, fully-functional and actively maintained as `Alamofire`. So I wouldn't say using it is a good choice.

**Comment by saagarjha** [comment]
PromiseKit had some compile errors in Swift 3, resolved by using the swift4-beta1 branch.

**Comment by saagarjha** [comment]
IINA compiles in Swift 4! (I'd put some confetti emoji here, but it causes [Safari to crash](https://bugs.webkit.org/show_bug.cgi?id=174404) so I'd thought I'd spare you guys).

**Comment by saagarjha** [comment]
If you'd like to try it out, my work is available on the [swift-4](https://github.com/lhc70000/iina/tree/swift-4) branch. Hopefully, as time goes on, my pull requests are accepted and we don't have to fallback to my repos anymore.

**Comment by saagarjha** [comment]
@lhc70000 Do you want to wait before merging this in, or should I open a pull request?

**Comment by lhc70000** [comment]
Let's wait for a while, as there still may be some breaking changes in the coming beta releases of Swift.

**Comment by alejx** [comment]
Swift scripts in /others are outdated.

**Comment by saagarjha** [comment]
I'll take a look at it. Have we considered adding the script as a command-line tool? This would make it easier to manage.

**Comment by lhc70000** [comment]
@saagarjha I'm afraid that some recent refactors would make rebasing quite difficult. Do you have enough time recently or prefer me to handle the branch updating?

**Comment by saagarjha** [comment]
I’ll take a look in a bit. Did you want to me to make a pull request?

**Comment by saagarjha** [comment]
Done.

**Comment by saagarjha** [comment]
I'm reopening this to track some work I'm doing on updated some Cocoapods. In particular, see https://github.com/mxcl/PromiseKit/issues/728.

**Comment by ErikMinekus** [comment]
I currently only get 4 warnings when building on Xcode 9. Maybe this can be closed, or rolled into #1765?

**Comment by saagarjha** [comment]
I'm closing this issue; I feel like it's been adequately addressed. @ErikMinekus, if you're still having any issues I'd suggest bringing it up in any of the other "updating to Swift X/macOS X" issues we have.
