### ISSUE TITLE
[Feature Request] Fit to screen option on video load

### ISSUE THREAD

**Issue by haniag** [lhc70000/iina#824]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

When IINA opens a video, user can set the Preferences to "Enter fullscreen when media is opened". However, it would enhance the UX if there is also the option to "Enter fit to screen when media is opened".

**Comment by JohnClay** [comment]
This would be fantastic. Right now, if you open multiple files you have to Command + 3 on every file if you don't want to go full screen.
