### ISSUE TITLE
[Esc] should close Open URL dialog window in Cyrillic IINA UI too

### ISSUE THREAD

**Issue by sevenfourk** [lhc70000/iina#835]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
<img width="832" alt="open_url_dialog" src="https://user-images.githubusercontent.com/75213/28140193-2d563ba8-670c-11e7-8909-5263b31afaf8.png">
Open URL dialog window should be closed/hidden by pressing Esc button

**Actual behavior:**
You have to press  on Cancel button to close it. This happens in Cyrillic IINA UI.

I may want to look at this myself. But created firsthand to track that.

**Comment by saagarjha** [comment]
@sevenfourk Would you like me to assign this issue to you?

**Comment by sevenfourk** [comment]
@saagarjha, sure, would be glad to fix this.  Though I'm not very good at Swift or macOS development.  Time to learn.

**Comment by saagarjha** [comment]
@sevenfourk I can't reproduce this, BTW. Are you sure the window is focused before you press escape?

**Comment by sevenfourk** [comment]
@saagarjha yes, the window has focus.

Hm, I'm suspecting this happens when I use my native language UI. Just downloaded build from IINA site, which does not have Ukrainian language yet and it works as expected.

**Comment by sevenfourk** [comment]
Apparently macOS has some predefined 'Cancel' keywords for every language.  You should just the one keyword they provide.
