### ISSUE TITLE
Quick setting panel is not updated when open another video.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#837]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When the quick setting panel is left open, and I open another video, the panel configurations should be refreshed to reflect the settings for the new video.

**Actual behavior:**
The settings for old videos remains on the panel. I have to dismiss and reopen the panel to get it display the correct settings for the new video.

**Steps to reproduce:**
Taking play speed for example:
Assume there're 2 videos `A` and `B`. I have set play speed for `A` to be 1.5x, and `B` is a video I've never opened. Now with the quick setting panel for video open, I open `B` with IINA. The video starts playing, but the speed controller is still showing 1.5x, but in fact it's playing at normal speed.

**How often does this happen?**
Every time I tried to reproduce it.

**Comment by oscar-c** [comment]
Similarly, it's not updated when using keyboard keys to adjust settings.
For example, when I use <kbd>[</kbd>, <kbd>]</kbd>, and, <kbd>Delete</kbd> to adjust the playback speed, the speed slider is not updated.

**Comment by alejx** [comment]
Fixed by bfa47eff4ae3eaa39ebf56385839ac18cdf65a39.
