### ISSUE TITLE
When open a .m3u playlist file, add only the specified files into IINA's playlist.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#839]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When open a `.m3u` playlist, only the files specified in playlist should appear in IINA's playlist.

**Actual behavior:**
IINA will add all the video files in the same folder as the file being played to the playlist.

**Step to reproduce:**
- Have some video files ready,  For example, `1.mp4`, `2.mp4`, `3.mp4`;
- Have a `.m3u` file ready, and it should only contain a strict subset of videos mentioned above. For example, prepare a file `list.m3u` that has following contents;
```
1.mp4
3.mp4
```
- Now open the `.m3u` file with IINA;
- Observe that the List Panel of IINA has far more items than what is in the `.m3u` file.

**How often does this happen?**
Every time.

**Comment by alejx** [comment]
Fixed in 7c9d127c342bcff834885c7da2a315969fa6b1f4.
