### ISSUE TITLE
Rename a subtitle file and IINA complains "Unsupported External Subtitles"

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#841]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
IINA doesn't show error for a "Unsupported External subtitle", after I rename a subtitle file.

**Actual behavior:**
After I renamed the subtitle file, every time I manually open the video file that the subtitle is for, IINA complains "Unsupported External subtitle".

**Steps to reproduce:**

- Have a video file and a subtitle file ready. Assume they're named `vid.mp4` and `vid.ass`, such that IINA can automatically load the subtitle when the video plays;
- Open the video with IINA and begin playing;
- Quit IINA;
- Rename the subtitle to some different name, while IINA can still pick it up for the video, for example, `vid.ass` -> `vid.sc.ass`;
- Open the video with IINA and now it complains for a  "Unsupported External subtitle".

**How often does this happen?**
Every time.

**Comment by oscar-c** [comment]
Removing the subtitle will trigger this bug as well.

**Comment by oscar-c** [comment]
[A video demo](http://d.pr/v/eLtTwV+) for the tag.

**Comment by lhc70000** [comment]
No, this tag is for us to check whether it's reproducible and fixable. If we need more info, we'll use `info needed` and of course let you know. But anyway, thanks for the demo.
