### ISSUE TITLE
On Screen Controller will not show up after some clicking

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#842]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
On Screen Controller shows up whenever I move mouse cursor inside IINA's window.

**Actual behavior:**
After some clicking (demonstrated in the but reproducing section), the OSC will not show up no matter how I move the mouse cursor.

**Steps to reproduce:**
Three slow click on the window before the OSC fades away and move the cursor. As in this [screen recording ](http://d.pr/v/Dg6aU+)

**How often does this happen?**
Sometimes.

**Comment by alejx** [comment]
This should be fixed by #752

**Comment by oscar-c** [comment]
Fixed in 0.0.12.
