### ISSUE TITLE
Bug. App crashes when entering PiP with custom keyboard shortcut.

### ISSUE THREAD

**Issue by pflind** [lhc70000/iina#843]
- macOS 10.12.5
- IINA 0.0.11

I have a custom keyboard shortcut created in macOS preferences to Enter/Exit Picture-in-Picture mode and the app crashes when I invoke the shortcut (cmd + .).

**How often does this happen?**
Every time. But, if I first initiate PiP-mode via the menu bar (Video -> Enter Picture-in-Picture) the app won't crash and I can later use the keyboard shortcut without crashes. 

EDIT: App doesn't crash completely, it is still running, but the video window closes and playback position is reset.

- MPV log:
`[   0.032][v][cplayer] mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[   0.032][v][cplayer]  built on Tue Apr 25 19:22:08 HKT 2017
[   0.032][v][cplayer] ffmpeg library versions:
[   0.032][v][cplayer]    libavutil       55.58.100
[   0.032][v][cplayer]    libavcodec      57.89.100
[   0.032][v][cplayer]    libavformat     57.71.100
[   0.032][v][cplayer]    libswscale      4.6.100
[   0.032][v][cplayer]    libavfilter     6.82.100
[   0.032][v][cplayer]    libswresample   2.7.100
[   0.032][v][cplayer] ffmpeg version: 3.3
[   0.032][v][cplayer] 
[   0.032][v][cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/0.25.0 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/0.25.0/share/mpv --mandir=/usr/local/Cellar/mpv/0.25.0/share/man --docdir=/usr/local/Cellar/mpv/0.25.0/share/doc/mpv --zshdir=/usr/local/Cellar/mpv/0.25.0/share/zsh/site-functions --enable-libbluray
[   0.032][v][cplayer] List of enabled features: 52 apple-remote asm atomics avutil-imgcpy-uc bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer cuda-hwaccel debug-build dlopen encoding fchmod gcc-tls gl gl-cocoa glob gnuc iconv is_ffmpeg jpeg lcms2 libass libass-osd libav libavcodec libavdevice libbluray libdl libm libmpv-shared lua nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads shm stdatomic subprocess termios tv uchardet videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[   0.036][v][bdmv/bluray] Opening /Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/input_conf/IINA Default copy.conf
[   0.037][v][file] Opening /Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/input_conf/IINA Default copy.conf
[   0.037][v][file] Stream opened successfully.
[   0.037][v][input] Parsing input config file /Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/input_conf/IINA Default copy.conf
[   0.037][v][input] Input config file /Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/input_conf/IINA Default copy.conf parsed: 70 binds
[   0.037][v][global] user path: '/Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/log/2017-7-14-19-40-52_blkRtW.log' -> '/Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/log/2017-7-14-19-40-52_blkRtW.log'
[   0.037][v][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.038][v][ytdl_hook] loading mp.defaults
[   0.040][v][ytdl_hook] loading @ytdl_hook.lua
[   0.041][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.041][v][cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[   0.041][v][cplayer] Done loading @ytdl_hook.lua.
[   0.041][v][osx] Exiting...
[   0.041][v][cplayer] Set property: vo="opengl-cb" -> 1
[   0.042][v][cplayer] Set property: keepaspect="no" -> 1
[   0.042][v][cplayer] Set property: opengl-hwdec-interop="auto" -> 1
[   0.263][v][opengl-cb] GL_VERSION='4.1 INTEL-10.25.13'
[   0.263][v][opengl-cb] Detected desktop OpenGL 4.1.
[   0.263][v][opengl-cb] GL_VENDOR='Intel Inc.'
[   0.263][v][opengl-cb] GL_RENDERER='Intel(R) HD Graphics 515'
[   0.263][v][opengl-cb] GL_SHADING_LANGUAGE_VERSION='4.10'
[   0.263][v][opengl-cb] Loaded extension GL_APPLE_rgb_422.
[   0.263][v][opengl-cb] 16 bit texture depth: 16.
[   0.263][v][opengl-cb] Testing FBO format 0x805b
[   0.263][v][opengl-cb] Create FBO: 16x16 (16x16)
[   0.264][v][opengl-cb] Using FBO format 0x805b.
[   0.264][v][opengl-cb] No advanced processing required. Enabling dumb mode.
[   0.264][v][opengl-cb] Loading hwdec driver 'videotoolbox'
[   0.271][v][cplayer] Set property: ontop=true -> 1
[   0.271][v][cplayer] Run command: loadfile, flags=0, args=[/Users/MYUSERNAME/Downloads/movie.avi, replace, ]
[   0.271][v][global] user path: '/Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/watch_later' -> '/Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/watch_later'
[   0.271][i][cplayer] Resuming playback. This behavior can be disabled with --no-resume-playback.
[   0.271][i][cplayer] Loading config '/Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/watch_later/80B6D7C8AC0BECFFFDDBA99C14676222'
[   0.271][v][cplayer] Reading config file /Users/MYUSERNAME/Library/Application Support/com.colliderli.iina/watch_later/80B6D7C8AC0BECFFFDDBA99C14676222
[   0.272][v][cplayer] Setting option 'start' = '315.381733' (flags = 36)
[   0.272][v][cplayer] Setting option 'volume' = '78.250000' (flags = 36)
[   0.272][v][cplayer] Setting option 'ontop' = 'yes' (flags = 36)
[   0.272][i][cplayer] Playing: /Users/MYUSERNAME/Downloads/movie.avi
[   0.272][v][cplayer] Running hook: ytdl_hook/on_load
[   0.272][v][cplayer] Run command: hook-ack, flags=0, args=[on_load]
[   0.272][v][bdmv/bluray] Opening /Users/MYUSERNAME/Downloads/movie.avi
[   0.273][v][file] Opening /Users/MYUSERNAME/Downloads/movie.avi
[   0.273][v][file] Stream opened successfully.
[   0.273][v][demux] Trying demuxers for level=normal.
[   0.277][v][lavf] Found 'avi' at score=100 size=2048.
[   0.389][v][lavf] avformat_find_stream_info() finished after 34724 bytes.
[   0.389][v][demux] Detected file format: avi (libavformat)
[   0.389][v][cplayer] Opening done: /Users/MYUSERNAME/Downloads/movie.avi
[   0.390][v][cplayer] Running hook: ytdl_hook/on_preloaded
[   0.390][v][cplayer] Run command: hook-ack, flags=0, args=[on_preloaded]
[   0.390][i][cplayer]  (+) Video --vid=1 (mpeg4 624x352 29.970fps)
[   0.390][i][cplayer]  (+) Audio --aid=1 (mp3 2ch 48000Hz)
[   0.390][v][vd] Container reported FPS: 29.970030
[   0.391][v][vd] Codec list:
[   0.391][v][vd]     mpeg4 - MPEG-4 part 2
[   0.391][v][vd] Opening video decoder mpeg4
[   0.391][v][vd] Not trying to use hardware decoding: codec mpeg4 is not on whitelist, or does not support hardware acceleration.
[   0.391][v][vd] Using software decoding.
[   0.391][v][vd] Detected 4 logical cores.
[   0.391][v][vd] Requesting 5 threads for decoding.
[   0.391][v][vd] Selected video codec: mpeg4 (MPEG-4 part 2)
[   0.392][v][ad] Codec list:
[   0.392][v][ad]     mp3 - MP3 (MPEG audio layer 3)
[   0.392][v][ad]     mp3float (mp3) - MP3 (MPEG audio layer 3)
[   0.392][v][ad]     mp3_at (mp3) - mp3 (AudioToolbox)
[   0.392][v][ad] Opening audio decoder mp3
[   0.392][v][ad] Detected 4 logical cores.
[   0.392][v][ad] Requesting 5 threads for decoding.
[   0.392][v][ad] Selected audio codec: mp3 (MP3 (MPEG audio layer 3))
[   0.392][v][cplayer] Starting playback...
[   0.392][v][lavf] queuing seek to 315.381733
[   0.392][v][cplayer] hr-seek, skipping to 315.381733
[   0.392][v][lavf] execute seek (to 315.381733 flags 40)
[   0.392][v][lavf] seek done
[   0.393][v][af] Audio filter chain:
[   0.393][v][af]   [in] 48000Hz stereo 2ch s16p
[   0.393][v][af]   [out] 48000Hz stereo 2ch s16p
[   0.393][v][af]   [ao] 48000Hz stereo 2ch s16p
[   0.393][v][ao] Trying audio driver 'coreaudio'
[   0.393][v][ao/coreaudio] requested format: 48000 Hz, stereo channels, s16p
[   0.429][v][ao/coreaudio] selected audio output device: Built-in Output (46)
[   0.430][v][ao/coreaudio] input channel layout:
[   0.430][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   0.430][v][ao/coreaudio]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.430][v][ao/coreaudio]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.430][v][ao/coreaudio] mp chmap: unknown2
[   0.430][v][ao/coreaudio] input channel layout:
[   0.430][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   0.430][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.430][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.430][v][ao/coreaudio] mp chmap: stereo
[   0.430][v][ao/coreaudio] Channel layouts:
[   0.430][v][ao/coreaudio]  - stereo
[   0.430][v][ao/coreaudio]  - mono
[   0.430][v][ao/coreaudio] result: stereo
[   0.461][v][ao/coreaudio] Latency property cntl: 750 frames
[   0.461][v][ao/coreaudio] Latency property zisf: 512 frames
[   0.462][v][ao/coreaudio] Latency property tfas: 93 frames
[   0.462][v][ao/coreaudio] audiounit latency [us]: 354
[   0.462][v][ao/coreaudio] device latency [us]: 28229
[   0.462][v][ao/coreaudio] using soft-buffer of 9600 samples.
[   0.462][i][cplayer] AO: [coreaudio] 48000Hz stereo 2ch s16p
[   0.462][v][cplayer] AO: Description: CoreAudio AudioUnit
[   0.462][v][cplayer] Inserting volume filter.
[   0.462][v][af] Adding filter volume 
[   0.462][v][af] Setting option 'warn' = 'no' (flags = 0)
[   0.462][v][af] Adding filter lavrresample 
[   0.462][v][af] Adding filter lavrresample 
[   0.462][v][af] Audio filter chain:
[   0.462][v][af]   [in] 48000Hz stereo 2ch s16p
[   0.462][v][af]   [lavrresample] 48000Hz stereo 2ch floatp [a]
[   0.462][v][af]   [volume] "softvol" 48000Hz stereo 2ch floatp
[   0.462][v][af]   [lavrresample] 48000Hz stereo 2ch s16p [a]
[   0.462][v][af]   [out] 48000Hz stereo 2ch s16p
[   0.462][v][af]   [ao] 48000Hz stereo 2ch s16p
[   0.462][v][volume] volume gain: 0.479130
[   0.467][v][cplayer] Set property: pause=true -> 1
[   0.470][v][vd] Using software decoding.
[   0.470][v][vd] Decoder format: 624x352 yuv420p auto/auto/auto/auto CL=mpeg2/4/h264
[   0.471][v][vf] Video filter chain:
[   0.471][v][vf]   [in] 624x352 yuv420p bt.601/bt.709/bt.1886/limited CL=mpeg2/4/h264
[   0.471][v][vf]   [out] 624x352 yuv420p bt.601/bt.709/bt.1886/limited CL=mpeg2/4/h264
[   0.511][v][cplayer] Set property: pause=false -> 1
[   0.582][i][cplayer] VO: [opengl-cb] 624x352 yuv420p
[   0.582][v][cplayer] VO: Description: OpenGL Callbacks for libmpv
[   0.582][v][cplayer] set video colors output-levels=0 
[   0.584][v][opengl-cb] Window size: 1336x702
[   0.584][v][opengl-cb] Video source: 624x352 (1:1)
[   0.584][v][opengl-cb] Video display: (0, 0) 624x352 -> (0, 0) 1336x702
[   0.584][v][opengl-cb] Video scale: 2.141026/1.994318
[   0.584][v][opengl-cb] OSD borders: l=0 t=0 r=0 b=0
[   0.584][v][opengl-cb] Video borders: l=0 t=0 r=0 b=0
[   0.584][v][opengl-cb] Testing FBO format 0x805b
[   0.584][v][opengl-cb] Create FBO: 16x16 (16x16)
[   0.584][v][opengl-cb] Using FBO format 0x805b.
[   0.584][v][opengl-cb] No advanced processing required. Enabling dumb mode.
[   0.584][v][opengl-cb] Texture for plane 0: 624x352
[   0.584][v][opengl-cb] Texture for plane 1: 312x176
[   0.584][v][opengl-cb] Texture for plane 2: 312x176
[   0.584][v][opengl-cb] Reported display depth: 8
[   0.584][v][cplayer] first video frame after restart shown
[   0.585][v][opengl-cb] new shader program:
[   0.585][v][opengl-cb] [  1] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[   0.585][v][opengl-cb] [  2] color.g = 1.000000 * vec4(texture(texture1, texcoord1)).r;
[   0.585][v][opengl-cb] [  3] color.b = 1.000000 * vec4(texture(texture2, texcoord2)).r;
[   0.585][v][opengl-cb] [  4] // color conversion
[   0.585][v][opengl-cb] [  5] color = color.rgba;
[   0.585][v][opengl-cb] [  6] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[   0.585][v][opengl-cb] [  7] color.a = 1.0;
[   0.585][v][opengl-cb] [  8] // color mapping
[   0.599][v][opengl-cb] shader link log (status=1): WARNING: Output of vertex shader 'texcoord5' not read by fragment shader
[   0.599][v][opengl-cb] WARNING: Output of vertex shader 'texcoord3' not read by fragment shader
[   0.599][v][opengl-cb] WARNING: Output of vertex shader 'texcoord4' not read by fragment shader
[   0.599][v][opengl-cb] 
[   0.613][v][opengl-cb] Window size: 1284x682
[   0.613][v][opengl-cb] Video source: 624x352 (1:1)
[   0.613][v][opengl-cb] Video display: (0, 0) 624x352 -> (0, 0) 1284x682
[   0.613][v][opengl-cb] Video scale: 2.057692/1.937500
[   0.613][v][opengl-cb] OSD borders: l=0 t=0 r=0 b=0
[   0.613][v][opengl-cb] Video borders: l=0 t=0 r=0 b=0
[   0.655][v][cplayer] starting audio playback
[   0.655][v][cplayer] playback restart complete
[   0.657][v][opengl-cb] Window size: 1216x658
[   0.658][v][opengl-cb] Video source: 624x352 (1:1)
[   0.658][v][opengl-cb] Video display: (0, 0) 624x352 -> (0, 0) 1216x658
[   0.658][v][opengl-cb] Video scale: 1.948718/1.869318
[   0.658][v][opengl-cb] OSD borders: l=0 t=0 r=0 b=0
[   0.658][v][opengl-cb] Video borders: l=0 t=0 r=0 b=0
[   0.713][v][opengl-cb] Window size: 1096x614
[   0.713][v][opengl-cb] Video source: 624x352 (1:1)
[   0.713][v][opengl-cb] Video display: (0, 0) 624x352 -> (0, 0) 1096x614
[   0.713][v][opengl-cb] Video scale: 1.756410/1.744318
[   0.713][v][opengl-cb] OSD borders: l=0 t=0 r=0 b=0
[   0.713][v][opengl-cb] Video borders: l=0 t=0 r=0 b=0
[   0.757][v][cplayer] get video colors hue 
[   0.762][v][cplayer] get video colors contrast 
[   0.762][v][cplayer] get video colors saturation 
[   0.763][v][cplayer] get video colors brightness 
[   0.763][v][cplayer] get video colors gamma 
[   0.764][v][opengl-cb] Window size: 1064x600
[   0.764][v][opengl-cb] Video source: 624x352 (1:1)
[   0.764][v][opengl-cb] Video display: (0, 0) 624x352 -> (0, 0) 1064x600
[   0.764][v][opengl-cb] Video scale: 1.705128/1.704545
[   0.764][v][opengl-cb] OSD borders: l=0 t=0 r=0 b=0
[   0.764][v][opengl-cb] Video borders: l=0 t=0 r=0 b=0
[   0.784][v][cplayer] Set property: ontop=true -> 1
[   1.157][v][cplayer] Run command: stop, flags=0, args=[]
[   1.157][v][cplayer] EOF code: 4  
[   1.182][v][ad] Uninit audio decoder.
[   1.182][v][af] Removing filter lavrresample 
[   1.182][v][af] Removing filter volume 
[   1.182][v][af] Removing filter lavrresample 
[   1.182][v][vd] Uninit video.
[   1.185][v][cplayer] finished playback, success (reason 2)
[   1.185][i][cplayer] 
[   1.187][v][cplayer] Run command: write-watch-later-config, flags=0, args=[]
[   1.187][v][cplayer] Run command: stop, flags=0, args=[]
``

```

**Comment by saagarjha** [comment]
Would you mind attaching the crash log as well? You should be able to find it in `~/Library/Logs/DiagnosticReports/`–the filename will have "IINA" as its prefix.

**Comment by pflind** [comment]
I only get a log-file, no crash file. See my edit in first post.

**Comment by saagarjha** [comment]
Hmm, are you sure IINA is actually crashing, then? You might just be closing the window.

**Comment by pflind** [comment]
It doesn't crash the app completely because it's still running and I can open a new video. But the window is closed and the playback position is also lost when I fire my shortcut. It seems like a part of the app is crashing.

**Comment by pflind** [comment]
I changed my custom shortcut to CMD + Y and it works flawlessly.

Why doesn't CMD + . (dot) work? I can't find a reason.

**Comment by saagarjha** [comment]
Command+. is bound to "Stop and Clear Playlists" normally. I'm guessing that's what's being called.

**Comment by pflind** [comment]
Ah, well I guess that explains it then. I close this.
