### ISSUE TITLE
"Previous / Next Media" button should not reset playback progress

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#845]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When using the "⏪" and "⏩" button on OSC to go to the navigate between medias, IINA should resume the playback position of the previous / next media file.

**Actual behavior:**
When using the"⏪" and "⏩" button on OSC to go to the navigate between medias, the playback progress of current media file and the previous media file are all set to the beginning, and the playback starts from beginning. 

**Steps to reproduce:**
- The "left/right button" is set to "Previous / Next Media"; ![Config](http://d.pr/i/zK2UTB+)
- Have two files in IINA's playlist, for example `1.mp4` and `2.mp4`;
- Watch both videos halfway through and close the window, so that next time they're opened manually, IINA resumes the position for each file respectively;
- Now open the second file `2.mp4`;
- Use the "⏪" on OSC to have IINA go back to the first file `1.mp4`;
- Use the "⏩" on OSC to have IINA go to the second file `2.mp4`;
- Observe that IINA has reset the playback position for both files to the beginning. 

**How often does this happen?**
Every time.

**Comment by oscar-c** [comment]
A similar bug:
Use  "⏩" twice, so IINA does `1.mp4` -> `2.mp4` -> `3.mp4`
And the playback position for both `1.mp4` and `2.mp4` are cleared.

**Comment by lhc70000** [comment]
This should be the intended behavior of mpv.

**Comment by oscar-c** [comment]
How does this behavior make any sense?
Of I do one hop, the progress is preserved. <- OK, no problem with that.
But if I do two hops, the files that are bridged by the oldest hop get their progress reset. <- ???

**Comment by lhc70000** [comment]
mpv only saves playback progress when you quit the app or close the window. Otherwise, it assumes that you are leaving current video **on purpose** and thus don't need to resume.
