### ISSUE TITLE
Add option to go back to previous subtitle line.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#850]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
I want to rewind to the timestamp when previous subtitle line appears.

**Rationale:**
- Sometimes the subtitles contains too much text and is on screen in a short amount of time. Seek is not accurate enough and frame-by-frame is too slow. Being able to go directly back where the previous line begins is very helpful in this situation.
- Movist has this function (in `Playback` -> `Forward Subtitle`).

**Comment by lhc70000** [comment]
option+left/right

Please check the keybindings in Preference in advance.
