### ISSUE TITLE
After rotating a non-square video 90/270 degree, IINA should flip the aspect ratio.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#851]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
After I flip a landscape video to portrait, IINA readjusts the aspect ratio to the reciprocal of the original one.

**Actual behavior:**
The aspect ratio is not changed, and the video looks stretched.

**Steps to reproduce:**
Rotate any non-square video by 90/270 degree.

**How often does this happen?**
Every time.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
