### ISSUE TITLE
不支持的外部字幕

### ISSUE THREAD

**Issue by Su9Tail** [lhc70000/iina#854]
在线匹配字母的时候，多数资源都会提醒不支持的外部字母，但字幕文件就是简单的srt文件啊，怎么会不支持，错误提示消息能不能详细一些，现在的错误信息完全模棱两可的，没有任何参考意义。

另外，还有一个问题，使用过程中，中/英切换键无效，哪怕程序处于后台也一样。除非关掉软件才行，希望早点解决这个问题。

**Comment by lhc70000** [comment]
> 多数资源都会提醒不支持的外部字幕

这是因为射手返回的文件确实是损坏的（前面缺失几个字符）。mpv 对字幕格式要求更严格一些，部分不符合标准的 srt 会加载不了。

> 错误提示消息能不能详细一些 

很抱歉不能。mpv 没有提供更多信息。

> 使用过程中，中/英切换键无效

现在你可以先禁用媒体键。macOS 10.13 会解决这个问题。
