### ISSUE TITLE
keybindings for audio delay

### ISSUE THREAD

**Issue by minusf** [lhc70000/iina#859]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Audio delay for default pre-defined keys `ctrl +` and `ctrl -`

**Actual behavior:**

No audio delay. Furthermore, in the Keybindings part of preferences, these keybindings are not shown correctly (see screenshot). Also doesnt work when changing to MPV keys, also doesnt work when duplicating default configuration. It only works when assigning new keys to it in the duplicated configuration.

<img width="323" alt="screen shot 2017-07-15 at 22 46 50" src="https://user-images.githubusercontent.com/3632883/28242572-a21ac274-69af-11e7-8592-954cdac2e56e.png">

**Steps to reproduce:**

press `ctrl +` or `ctrl -`

- [x] MPV does not have this problem.

**How often does this happen?**

100% reproducable.

**Comment by lhc70000** [comment]
Fixed in develop branch.
