### ISSUE TITLE
Sierra PIP move-away feature

### ISSUE THREAD

**Issue by KimchaC** [lhc70000/iina#86]
<img width="268" alt="screen shot 2017-01-07 at 1 55 47 pm" src="https://cloud.githubusercontent.com/assets/7404004/21741784/2647b7c8-d4e1-11e6-96d6-6f127f5914c3.png">

Sierra's PIP supports moving away the window to the side and then bringing it back by just pressing the error. It would be a great feature to add to IINA!

**Comment by reyder** [comment]
I don't think is possible. PIP.framework is private framework, not documented. However you can use it to display any ViewController.

**Comment by KimchaC** [comment]
I am not suggesting to use the PIP.framework, but instead to just implement similar functionality of moving a float-on-top window to the side and bring it back with 1 click.

**Comment by lhc70000** [comment]
PIP support was added in 0.0.5 :)
