### ISSUE TITLE
Keybinding for next/previous subtitle

### ISSUE THREAD

**Issue by johnsonlegend** [lhc70000/iina#861]
How can I set a shortcut for next/previous subtitle? Sometimes this feature will be really helpful. 

Thanks!

**Comment by oscar-c** [comment]
You can do this by go to Preferences, then Keybindings.
Then add one like this to have "Next Subtitle" bind to <kbd>v</kbd>: ![next sub](http://d.pr/i/Kxlxf9+)

You can replace the "increase" in the third cell with "decrease" to have "Previous Subtitle" function bind to <kbd>v</kbd>.

**Comment by johnsonlegend** [comment]
Thanks! @oscar-c
