### ISSUE TITLE
Show playback history in welcome window

### ISSUE THREAD

**Issue by lhc70000** [lhc70000/iina#864]

**Comment by oscar-c** [comment]
Hi, great work in the new version, I like this welcome window.

However, the welcome window is not updated until the app is relaunched, this is a little bit inconvenient for me.

I'd like to use the welcome window more whenever I feel like to resume watching what I left last time. Usually I just close the playback window, and when I want to resume, I click on IINA's icon on the dock. Them the welcome window shows up, with the outdated washing progress. Not very helpful.

I would be nice if I can see what I just watched and resume in the welcome window.

 A similar behavior to #857 .
