### ISSUE TITLE
add shortcut for changing audio and enable/disable subtitles

### ISSUE THREAD

**Issue by shaizu** [lhc70000/iina#866]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**

**Actual behavior:**
this version does not quit app when all windows are closed it was working fine in previous version

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
please add shortcuts for changing audio and enable/disable subtitles

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by shaizu** [comment]
still not fixed app quitting when all windows are closed

**Comment by lhc70000** [comment]
@shaizu Confirmed that it still happens only when opening files from Finder. However too much updates will be annoying, so please wait for a few days before we can release a new version.

**Comment by shaizu** [comment]
sure I can wait :)
and can you please add shortcuts as I requested?

**Comment by lhc70000** [comment]
@shaizu You can configure them in Preference > Key bindings.

"Cycle audio track" for the former and "Cycle sub track" / "Cycle sub visibility" for the latter. (You may need to input the command "cycle sub-visibility" manually)

**Comment by shaizu** [comment]
@lhc70000 thanks for fixing it 👍 :)
