### ISSUE TITLE
video seek preview has bad constrains 

### ISSUE THREAD

**Issue by SchwiftyLife** [lhc70000/iina#867]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**

video seek preview should be shown under the seek bar .

**Actual behavior:**

it shows on the seek bar like this :

![screen shot 2017-07-17 at 4 05 36 pm](https://user-images.githubusercontent.com/16489849/28266460-419e6d86-6b0a-11e7-8e34-1e27d132e01f.jpg)

**How often does this happen?**
always

**Comment by lhc70000** [comment]
Fixed in build 35. Please check for updates ;)
