### ISSUE TITLE
Build failed with lastest source code

### ISSUE THREAD

**Issue by tuduongquyet** [lhc70000/iina#868]
<img width="1440" alt="screen shot 2017-07-18 at 00 05 26" src="https://user-images.githubusercontent.com/17985027/28280108-df80d8b2-6b4c-11e7-91bc-6135ef4016b9.png">

**System and IINA version:**

- macOS 10.11.6
- IINA 0.0.12
- XCode 8.2.1

**Expected behavior:**
 Build sucessfully

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
Please update to Xcode 8.3. It requires Swift 3.1.

**Comment by saagarjha** [comment]
@lhc70000 Unrelated, but we can phase this method out in Swift 4 due to `Dictionary.subscript(_:default:)`.

**Comment by tuduongquyet** [comment]
Is there any implementation for swift 3.0 ? Because If i want to use Xcode 8.0, i will have to upgrade to Mac 10.12 :(

**Comment by lhc70000** [comment]
@tuduongquyet It also uses a lot of 10.12+ APIs so you **must** build it on 10.12.
