### ISSUE TITLE
Deleting files in the player (key combination)

### ISSUE THREAD

**Issue by imKota** [lhc70000/iina#870]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**
Please add the ability to delete files from the disc in the player itself. For example: when watching a video, press Shift+D or another combination. After that, the file is deleted to the Recycle Bin or irrevocably, and the next file is played.

Thanks!

**Comment by saagarjha** [comment]
This was added in #572. You can find under the File menu.

**Comment by imKota** [comment]
@saagarjha, thanks!
