### ISSUE TITLE
how to communicate with iina by code

### ISSUE THREAD

**Issue by ZSwitch** [lhc70000/iina#875]
I want to add iina to my project.But iina does not generate a framework like ijkplayer.It can only product an 'IINA.app'. So what I only can do is communicate with this app?
If so, what should I do if I want to play a local path or network url.

Finally, I hope I can use it in my app rather than two apps.

**Comment by megadr01d** [comment]
Related to https://github.com/lhc70000/iina/issues/58.

**Comment by ZSwitch** [comment]
@megadr01d   do you mean I should communicate with iina by "you-get"?
But I do not want to load another project to make my project becoming bigger.T_T
Can I communicate with iina by apple's function, just like NSWorkspace's openFile?

**Comment by lhc70000** [comment]
IINA is a fully functional App, not a framework. Please use mpv (as IINA does) if you want to embed a player in your App.

You can pass the file path to IINA's binary, e.g. `.../IINA.app/Contents/MacOS/IINA path/to/file` before we adding more support for terminal/CLI.

**Comment by ZSwitch** [comment]
thank you @lhc70000
