### ISSUE TITLE
Rewinding live streams

### ISSUE THREAD

**Issue by kristofferR** [lhc70000/iina#876]
**Expected behavior:**
A lot of live streams keep the video segments for a predefined period of time, often like 30 minutes. This makes it possible to rewind the stream, which is really useful if you miss the start of a show for example. This is often called DVR mode.

IINA don't support this yet. QuickTime does (although in a stupid way where you must rewind 30 seconds many times). 

Here's a (badly positioned) webcam stream that's rewindable in QuickTime and not in IINA:
http://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8?DVR

**Actual behavior:**
I would really like to use IINA for live streams, but without rewind support it's just not feasible.

**Comment by lhc70000** [comment]
Seems that neither mpv or VLC supports it. As IINA is based on mpv, I'd suggest you reporting this issue to [mpv team](https://github.com/mpv-player/mpv).
