### ISSUE TITLE
Bring IINA to front when exiting PIP

### ISSUE THREAD

**Issue by oskarkrawczyk** [lhc70000/iina#879]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**

When exiting PIP, the app should bring itself to the front – I personally keep have to find INAA after exiting PIP in order to put it in the front.

The only other app I know that uses PIP is the unofficial WWDC.app, and it works as expected: https://v.usetapes.com/jzF6GmpSaf

**Actual behavior:**

Exiting PIP, keeps the app below the currently active window.

**Comment by saagarjha** [comment]
@oskarkrawczyk I'm working on fixing PIP and this is one of the things on my checklist. Stay tuned!

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
