### ISSUE TITLE
Thumbnail preview sometimes display the preview for other video.

### ISSUE THREAD

**Issue by oscar-c** [lhc70000/iina#881]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**
Thumbnail preview shows thumbnails extracted from the video I'm watching.

**Actual behavior:**
Preview contains frames from other video.
[A short demo](http://d.pr/v/XSYfp0+). (Note that the media is an anime episode, but somehow it shows the preview for another non-anime video)

**Steps to reproduce:**
- Clear thumbnail cache;
- uncheck "Always open media in new window";
- Prepare two videos, assume they are called `A.mp4` and `B.mp4`; 
- Open `A.mp4`;
- While the preview for `A.mp4` is being generated, open `B.mp4` with IINA;
- Wait for the preview to appear;
- Observe that the preview for `B.mp4` contains frames from `A.mp4`.

**How often does this happen?**
Sometimes.

**Comment by lhc70000** [comment]
@oscar-c Please clear the thumbnails cache and try again. It’s a known issue and we are investigating it.

**Comment by oscar-c** [comment]
@lhc70000 That works.
And since you mentioned it, I'd like to point out that while I'm watching a video, the clear cache function doesn't reset the preview for the video. Not sure if this is feature or bug.

**Comment by lhc70000** [comment]
@oscar-c It’s a feature (currently).

**Comment by jeanlain** [comment]
I also had this issue. Clearing the cache fixed it, but it occurred nonetheless.

**Comment by lhc70000** [comment]
This should have been fixed in recent versions. Please reopen if the problem persists.

**Comment by anohren** [comment]
@lhc70000 I don't know how to reopen so I'll just say that this problem still exists, though I don't know if the steps to reproduce in the OP are still relevant. Open this issue, or create new issue?
