### ISSUE TITLE
Unable drag & drop folder to player window after upgrade to 0.0.12

### ISSUE THREAD

**Issue by chenjau** [lhc70000/iina#882]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 Build 37 (mpv 0.25.0)

**Expected behavior:**
as title said, after upgrade to 0.0.12, cannot drag & drop folder onto window and play files in folder anymore. which works fine in 0.0.11.

to repro: 
1. open a file, play.
2. drag & drop folder onto window.

expect:
acts like 0.0.11.

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
We'll have a check. Right now you can drag a folder to the welcome window instead.

**Comment by alejx** [comment]
#942

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
