### ISSUE TITLE
Request for separate timing for the primary subtitle and the secondary subtitle 

### ISSUE THREAD

**Issue by liangchen1ce** [lhc70000/iina#884]
**System and IINA version:**

- OS X 10.10.5
- IINA 0.0.11

**Expected behavior:**

As far as I know, when setting subtitle delay, the relative time between two subtitles stays the same. However, subtitles may be produced for videos of different versions, such as a video with advertisement but another without. 

Even for different versions of videos, we still want to see two subtitles at the same time for reasons like comparing translation qualities or comparing translations between several languages. In this case, we need to delay one subtitle but keep the other unchanged.

**Comment by alejx** [comment]
This feature is good, but unfortunately there is no API that mpv provides to adjust any settings about secondary subtitle.
