### ISSUE TITLE
Thumbnail preview dont work when entering fullscreen on media opened

### ISSUE THREAD

**Issue by yukixz** [lhc70000/iina#886]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 build 37

**Expected behavior:**
Thumbnail preview show after opening video.

**Actual behavior:**
Thumbnail preview never display.

**Steps to reproduce:**
1. Select "Enter fullscreen when media is opened'.
2. Open a video
3. IINA will enter fullscreen and thumbnail preview wont show.

**How often does this happen?**
Everytime

**Comment by EngineerMostafa** [comment]
i have the same problem after using clean my mac for cleaning cash and junk files, iina thumbnail cache is always 0B
