### ISSUE TITLE
Needs a new download / update mirror in PRC.

### ISSUE THREAD

**Issue by ShikiSuen** [lhc70000/iina#887]
GitHub is banned by some ISPs among some areas in PRC. Meanwhile, some connections are not stable enough to establish VPN or Shadowsocks connection and the users have no choice of network resources. I personally suggest developers to contact the maintainers of TsingHua University open-source download site for help.

**Comment by HarukaMa** [comment]
We are using an alternative route for downloading / updating etc. for ppl located in China using CloudFlare's data.

It would be great if we could use THU open-source mirror, as it would greatly cut our expenses on it. Do you know how does the mirror work? I'd like to know more about syncing procedures.

**Comment by HarukaMa** [comment]
According to [this issue](https://github.com/tuna/issues/issues/249) we will stick to current plan for a while...

**Comment by shankerwangmiao** [comment]
Hi, thanks for considering TUNA mirror site. Currently, we are not accepting mirror requests until a storage upgrade. However, requests are welcomed and will be processed after the upgrade. Alternatively you can consider mirrors.ustc.edu.cn which accepts mirror request at https://github.com/ustclug/mirrorrequest/

**Comment by shankerwangmiao** [comment]
Available on https://mirrors.tuna.tsinghua.edu.cn/iina/

**Comment by shankerwangmiao** [comment]
Pls close this issue

**Comment by HarukaMa** [comment]
Sorry, forgot about this issue.
