### ISSUE TITLE
Subtitle background opacity

### ISSUE THREAD

**Issue by darlanmendonca** [lhc70000/iina#9]
Hey guys, amazing work!!! really, I loved

using, I feel a litte problem, 
by default, subtitles dont have background, its ok, but in some times, I need a background color, and you offer this.

but when I want back, and remove the background, I cant, because dont have this options.
In apple color pallete dont have this options (or I really not found), but, maybe be a good thing put an option to that in subtitle settings

what you think?

**Comment by lhc70000** [comment]
Hi, thanks for your feedback. I've confirmed the problem.

Seems that `NSColorPanel` has a `showsAlpha` option and I didn't enable it.

It should be fixed in next version.

**Comment by darlanmendonca** [comment]
perfect

waiting the next version :D
