### ISSUE TITLE
[Feature Request] Set default display

### ISSUE THREAD

**Issue by JohnClay** [lhc70000/iina#909]
An option to select the display on which all files are opened.

**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 (build 37)

**Expected behavior:**

An option to set the default display on which all files are opened would be great for multi-display users. If you have to open a bunch of files using the main screen, but want to view them on a secondary screen, you have to drag them over.

Setting a default display, or remember the last used display, would be a great addition.

**Comment by lhc70000** [comment]
![b77d03ef-ce18-4a02-a97c-8bf6780cb785](https://user-images.githubusercontent.com/8478049/28514151-9ffe1c24-708b-11e7-959c-65c350e52811.jpeg)

Is this what you need?

**Comment by JohnClay** [comment]
@lhc70000

Unfortunately not, as that requires every screen to have a separate space. Alternatively, if there's a legacy full screen method implemented that allows you to default a screen (#709), that would likely work too.
