### ISSUE TITLE
字幕突然消失

### ISSUE THREAD

**Issue by orchick** [lhc70000/iina#910]
Hi，

1. 看视频时，字幕突然消失；
2. 部分视频原先可以看到字幕的，重新打开也消失了；
3. 升级到0.0.12之后，问题仍旧存在的。

（字幕非外挂）

**Comment by lhc70000** [comment]
请检查你是否有 V 这个快捷键，绑定到了「字幕可见」。

如果无效，可能之前误触的选项被存到了历史记录中，你可以删掉 watch_later 文件夹（在偏好设置-高级的日志文件夹的旁边）。

**Comment by orchick** [comment]
解决了！感谢！

**Comment by uuunit** [comment]
> 请检查你是否有 V 这个快捷键，绑定到了「字幕可见」。
> 
> 如果无效，可能之前误触的选项被存到了历史记录中，你可以删掉 watch_later 文件夹（在偏好设置-高级的日志文件夹的旁边）。

字幕消失，搜到这里的，感觉应该在菜单里加一个显示字幕的选项。

**Comment by vulgur** [comment]
> > 请检查你是否有 V 这个快捷键，绑定到了「字幕可见」。
> > 如果无效，可能之前误触的选项被存到了历史记录中，你可以删掉 watch_later 文件夹（在偏好设置-高级的日志文件夹的旁边）。
> 
> 字幕消失，搜到这里的，感觉应该在菜单里加一个显示字幕的选项。

附议，还一直以为是字幕文件的问题呢

**Comment by xdtxAM** [comment]
> 请检查你是否有 V 这个快捷键，绑定到了「字幕可见」。
> 
> 如果无效，可能之前误触的选项被存到了历史记录中，你可以删掉 watch_later 文件夹（在偏好设置-高级的日志文件夹的旁边）。

解决了，V隐藏掉了。哎。我还买了infuse，难受这个选项太难找了
