### ISSUE TITLE
[Bug] Weird artifacts show up when the video has high bitrate in m2ts container

### ISSUE THREAD

**Issue by segnoda** [lhc70000/iina#916]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

Every time when I open a video with high bitrate in m2ts container, some artifacts show up. Form my experiment, these weird artifacts won't happen if the exact video stream in mkv container. Therefore, I don't think the high bitrate cause the issue. I also try the same video in mpv player, everything works fine. This might be mpv api's bug or iina's bug.
Not only in this version, actually, all of the releases have this issue. (I tried it all)

**Expected behavior:**
![mkv-1](https://user-images.githubusercontent.com/14884240/28563394-6b28da66-7158-11e7-94dc-c551f9982226.png)
![mkv-2](https://user-images.githubusercontent.com/14884240/28565074-ae9e8688-715d-11e7-9f6b-284dc396ca4f.png)

**Actual behavior:**
![m2ts-1](https://user-images.githubusercontent.com/14884240/28563393-6ad9cd36-7158-11e7-8c25-40e78ae51ff4.png)
![m2ts-2](https://user-images.githubusercontent.com/14884240/28565086-ba5a897c-715d-11e7-9962-214da6f5f404.png)

**Steps to reproduce:**
- From the origin source file `00000.m2ts`, I extract first 35 second long video stream into m2ts and mkv container without re-encoding.
`ffmpeg -i 00000.m2ts -ss 0 -t 35 -map 0:0 -c:v copy Sample.m2ts`
`ffmpeg -i 00000.m2ts -ss 0 -t 35 -map 0:0 -c:v copy Sample.mkv`

- Download and playback those output files in iina, you can see the different.
  - [Sample.m2ts](https://drive.google.com/open?id=0By39Y6PZLpuBMW8yenZELVB0dkE)
  - [Sample.mkv](https://drive.google.com/open?id=0By39Y6PZLpuBam4xZkRXejBzN3c)

- You can also playback those files in mpv player, both videos should works normally.

- [x] MPV does not have this problem.

**Comment by HarukaMa** [comment]
@segnoda Disabling hardware decoding would fix it. I don't know why hw decoding wouldn't work on m2ts files.

This bug is also present in mpv using --hwdec=videotoolbox. You could try reporting this bug to upstream.

**Comment by segnoda** [comment]
@HarukaMa Thanks! That really fixed the issue.
I will try to report this bug to mpv soon.
