### ISSUE TITLE
"Picture-in-picture" Function improvement.

### ISSUE THREAD

**Issue by xjkdev** [lhc70000/iina#918]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 build 37

When entering picture-in-picture mode, if the main window is pinned on top, there will be two player window that is on top. That may not be what user wants.
So here's my suggestion, provide an option that let main window not be pinned on top, or let the main window minimize or hide when entering picture-in-picture mode.

进入画中画功能后，如果主窗口置顶，就会同时有两个置顶的播放器窗口。我觉得用户可能不会想这样。
所以我建议进入画中画后，主窗口取消置顶，或者最小化或隐藏（画中画界面有恢复的按钮）。

**Comment by R-L-T-Y** [comment]
Duplicated with #879 #380

**Comment by xjkdev** [comment]
Sorry, I didn't do search.
