### ISSUE TITLE
[Bug] How to change the location of overlapped main subtitle and secondary subtitle?

### ISSUE THREAD

**Issue by zaazwm** [lhc70000/iina#920]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**

(subtitle file: *.sup)
- The two subtitles should not be stack on each other. 
- No residue after activating the secondary subtitle. 

**Actual behavior:**

- Now they are overlapping completely. 
- The first incoming secondary subtitle sentence is shown right after it is activated, and keep showing until this subtitle is disabled, or until the end of play. 

**Steps to reproduce:**

- Activate main subtitle
- Activate secondary subtitle
- The first incoming secondary subtitle sentence is shown, and won't disappear. The two subtitles are overlapped completely. 

**How often does this happen?**

Can be reproduced every time.

**Comment by R-L-T-Y** [comment]
I wouldn't consider this as a bug.
To my knowledge  SUP files are bitmap image from DVD or Blu-ray, which contain subtitle text graphics  and playback position on the screen(or as you mentioned, location).
When loaded as secondary subtitle, it's only nature for SUP files to displayed at the position set by the movie producers.
I would recommend you to convert the SUP files to SRT or ASS files for your experience.

**Comment by zaazwm** [comment]
But the second issue is still. After activating secondary subtitle, the first incoming sentence remains forever. It only occurs for the secondary subtitle, and no problem for main subtitle.

**Comment by R-L-T-Y** [comment]
Sorry I cannot reproduce.
Does this issue happen to SUP file only or other formats of subtitles? 
Will you upload some snapshots please?

**Comment by lhc70000** [comment]
Configuring position of the secondary subtitle is not supported by mpv.

**Comment by weiweihuanghuang** [comment]
What's the point of the secondary subtitle then if they're just going to overlap?

**Comment by lhc70000** [comment]
Secondary subtitles are rendered as plain text at the top, so all their styles are stripped (because styles can contain position definitions). However bitmap subtitles are exceptions: they must be always displayed at the designated position (say, at the bottom), hence if you set a bitmap subtitle as secondary subtitle, it will surely cause overlap.

**Comment by weiweihuanghuang** [comment]
In my case, both of them are plain text though, I can style primary and secondary subtitles
