### ISSUE TITLE
Can I use hotkey to control video windows float or not?

### ISSUE THREAD

**Issue by qzmoqzmo** [lhc70000/iina#921]
I don't know how to use hotkey to control video windows float, I only can find a selection in setting : start float windows when video playing. But I really want to control float windows free by using hotkey, just like MOVIST, press command+T.

I'm sorry I don't know whether this application have this function, if it have, tell me how to do it please. If not, this just a suggestion.

Thanks, all developers.

- macOS 10.12.5
- IINA 0.0.11

**Comment by lhc70000** [comment]
@qzmoqzmo control+command+T (Video - Float on Top in the menu)

You can also add other key bindings in preferences.

**Comment by qzmoqzmo** [comment]
@lhc70000 
Thanks a lot, I found it. 
I really love this application especially after add multi windows function. 👍
