### ISSUE TITLE
[Bug] Triggering PiP when a video from URL is buffering crashes IINA

### ISSUE THREAD

**Issue by am0** [lhc70000/iina#922]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
When opening a video from a URL and triggering PiP with the keyboard shortcut Command-Control-P, the "Opening stream" buffering UI should continue in IINA window, with a black PiP modal appearing before it starts the video

**Actual behavior:**
When using the Command-Control-P shortcut while the video is buffering, IINA will crash.
However, if you let it buffer and play, trigger PiP and close it again, close the video window, open the URL again via the Open URL window and trigger PiP again while it's buffering, it doesn't crash, plays fine and does the expected behaviour as written above.

- Crash report:
```
Process:               IINA [10058]
Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               0.0.12 (37)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [10058]
User ID:               501

Date/Time:             2017-07-27 10:37:21.616 +0100
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        3EA9FCFD-4DB7-5FC8-CD86-AAE49D10F1CE

Sleep/Wake UUID:       ABB4C39E-44F1-4847-AE46-B6185792BA8F

Time Awake Since Boot: 110000 seconds
Time Since Wake:       3700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Performing @selector(menuTogglePIP:) from sender NSMenuItem 0x6000000b8c60

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.colliderli.iina           	0x000000010a64458b _TFC4IINA20MainWindowController8enterPIPfT_T_ + 2507
1   com.colliderli.iina           	0x000000010a6445b6 _TToFC4IINA20MainWindowController8enterPIPfT_T_ + 22
2   libsystem_trace.dylib         	0x00007fffbf0d03a7 _os_activity_initiate_impl + 53
3   com.apple.AppKit              	0x00007fffa7995721 -[NSApplication(NSResponder) sendAction:to:from:] + 456
4   com.apple.AppKit              	0x00007fffa7468666 -[NSMenuItem _corePerformAction] + 324
5   com.apple.AppKit              	0x00007fffa74683d2 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
6   libsystem_trace.dylib         	0x00007fffbf0d03a7 _os_activity_initiate_impl + 53
7   com.apple.AppKit              	0x00007fffa74671e5 -[NSMenu performKeyEquivalent:] + 367
8   com.apple.AppKit              	0x00007fffa799431c routeKeyEquivalent + 1024
9   com.apple.AppKit              	0x00007fffa7991f39 -[NSApplication(NSEvent) sendEvent:] + 3377
10  com.apple.AppKit              	0x00007fffa720c427 -[NSApplication run] + 1002
11  com.apple.AppKit              	0x00007fffa71d6e0e NSApplicationMain + 1237
12  com.colliderli.iina           	0x000000010a5adf99 main + 9
13  libdyld.dylib                 	0x00007fffbee9e235 start + 1

[SNIP - hundreds more lines here. Let me know if you want the rest.]
```

**Steps to reproduce:**
Open IINA
Command-Shift-O to open the 'Open URL' window
Copy online video (I tested with Youtube and Vimeo) URL into first field
Press OK or hit enter
When the video is buffering, quickly hit Command-Control-P to trigger PiP
IINA will crash

Alternatively to see it working- as above but:
Let video buffer and play correctly after pressing OK
Trigger PiP and close it again
Close video window but don't quit IINA
Open video URL again
Quickly trigger PiP while buffering
It should now behave as it should, buffering in the main window with the PiP showing as blank until it's loaded.

**How often does this happen?**
Every time I trigger PiP while it's buffering.

**Comment by saagarjha** [comment]
Thanks for reporting this; there was a bug where the video's size wasn't available while buffering. Will eventually be fixed by https://github.com/lhc70000/iina/pull/880/commits/9ecfb06a2d9ded3731b99b92948a0d7f4d199a91.
