### ISSUE TITLE
IINA's m3u8 playlist logic fix

### ISSUE THREAD

**Issue by marcan144** [lhc70000/iina#923]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 build 37

**Expected behavior:**
When opening a m3u8 playlist, IINA should only add the items from the playlist, nothing extra

**Actual behavior:**
IINA adds playlist items + whatever is in the directory of a given location (specified through m3u8-file)

**How often does this happen?**
every time one opens a playlist file

**Comment by oscar-c** [comment]
I've reported a similar problem in #839

**Comment by marcan144** [comment]
thanks for letting me know - my bad
