### ISSUE TITLE
Is it possible that don't keep history?

### ISSUE THREAD

**Issue by nasyxx** [lhc70000/iina#924]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 Build 37

**A question.**

I have so many recently played videos on differenced date, how to delete them all? Is it possible that don't keep history?

**Comment by TempSpas** [comment]
If you open preferences, you can select the General tab and uncheck the "Enable Playback History" option.

**Comment by nasyxx** [comment]
Thank you.

I did it that way. But before the record did not disappear, I thought it was useless.

**Comment by oscar-c** [comment]
- Select first entry;
- scroll to last one;
- select last one while holding down <kbd>Shift</kbd>;
- Right click on any highlighted item;
- Select "Delete...".

**Comment by nasyxx** [comment]
@oscar-c Thank you. I've tried it like that, but I play too much record, it is estimated that there are 10 million. Every time I do this will crash (maybe just in an unresponsive state). Is the history file recorded in a file? I can delete the file directly so that the record disappears.

**Comment by lhc70000** [comment]
@nasyxx "~/Library/Application Support/com.colliderli.iina/history.plist"

**Comment by nasyxx** [comment]
Thank you. Solved

**Comment by ErikMinekus** [comment]
It's solved, so this can be closed.
