### ISSUE TITLE
Lack of Build Instruction 

### ISSUE THREAD

**Issue by xu-cheng** [lhc70000/iina#93]
Currently, the build instruction is missing in the readme, as the existing document only focuses on how to install dependencies. 

Moreover, it seems to be nontrivial to build this app. In Xcode, I countered many code sign problems.

Would you mind to update readme and maybe Xcode project file to let us to build this app out-of-box?

**Comment by csujedihy** [comment]
I used my developer account to sign the project and everything works well. When you commit the changes, ignore the project settings files.

**Comment by HarukaMa** [comment]
I would propose to change the default settings to unsigned to prevent further signing problems, especially for those who don't pay Apple for the expensive developer certificates...

Although no code signing would mean no capabilities (nothing used currently) and non-redistributable apps (default system security settings), but I think those who have certificate should know those already.

**Comment by seagle0128** [comment]
I agreed with @HarukaMa . There is no build and development guide for the desired contributors to start up smoothly. For example, I am suffering from this error while building.
```
~/src/iina/iina/iina-Bridging-Header.h:7:9: error: 'MASPreferences/MASPreferencesViewController.h' file not found
#import <MASPreferences/MASPreferencesViewController.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/vincent/src/iina/iina/iina-Bridging-Header.h'
```

Actually I've run `pod install` successfully, and all necessary files are there.

**Comment by lhc70000** [comment]
@seagle0128 

You need to open `.xcworkspace` rather than `.xcodeproj`. (cocoapods should alert you about this after `pod install` in my memory...)

It's written in CONTRIBUTING.md now. I'll add a line in README before next release.

**Comment by seagle0128** [comment]
@lhc70000 Thanks for the quick reply. I found the solution in #11 just now. It works! But it seems many guys experienced the same issue. It would be better if there was a good guide.

**Comment by inflation** [comment]
Close now due to inactivity.
