### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by Deathis** [lhc70000/iina#943]
macOS 10.12.6
IINA 0.0.12

I set a wrong argument to youtube-dl like proxy=127.0.0.1:3553. Application crashes when open it.

I try to delete IINA through AppCleaner and reinstall. Application crashes when open it.

Help.

**Comment by lhc70000** [comment]
@Deathis You’re supposed to use “HTTP proxy”. See https://github.com/lhc70000/iina/wiki/Use-youtube-dl-with-IINA#set-proxy
