### ISSUE TITLE
ObjcUtils functions can possibly corrupt the stack

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#946]
Both
`+ (BOOL)catchException:(void(^)())tryBlock error:(__autoreleasing NSError **)error`
and
`+ (BOOL)silenced:(void(^)())tryBlock`
are marked as having a boolean return value, and indeed under the happy path, all is good. In case the `tryBlock` throws, nothing is returned, causing a stack corruption. This should be fixed in both cases by adding `return NO`.

**Comment by lhc70000** [comment]
Thanks, added.

**Comment by LeoNatan** [comment]
Thanks
