### ISSUE TITLE
Fail on OS X 10.13 DP5

### ISSUE THREAD

**Issue by rocdeng** [lhc70000/iina#948]
**System and IINA version:**

- macOS 10.13 Beta (17A330h)
- IINA 0.0.12

Fail when open video files.
![qq20170809-084147 2x](https://user-images.githubusercontent.com/413922/29100519-aadfe478-7c71-11e7-9195-fe082781f25d.jpg)

**Comment by lhc70000** [comment]
@rocdeng Does it work until dp4?

**Comment by rocdeng** [comment]
Yes.

**Comment by lhc70000** [comment]
@rocdeng Have you tried restarting? Which device are you on?

**Comment by rocdeng** [comment]
Yes, I've tried restart my computer and all the same.
Device is Macbook Pro Retina 15-inch, Mid 2014.

**Comment by alejx** [comment]
@rocdeng Thanks for reporting this; I have the same set up as yours but I did not encounter this issue. Do you have a mpv? If so, can you help us to test out whether your machine can run mpv normally?

**Comment by rocdeng** [comment]
MPV works fine :)

**Comment by CaptainYukinoshitaHachiman** [comment]
I'm using the same OS, and IINA works well here.

**Comment by rocdeng** [comment]
I've downloaded a full install package of DP5 and reinstalled the OS. IINA works fine now 👍
