### ISSUE TITLE
take more time to open URL

### ISSUE THREAD

**Issue by basavaraj1995** [lhc70000/iina#950]
it take long time open URLs and sometimes it crashed!

**Comment by saagarjha** [comment]
Could you provide more information? What version of macOS and IINA are you running? Which URLs are you trying to open? Do you have a crash log?

**Comment by basavaraj1995** [comment]
Mac os sierra

**Comment by basavaraj1995** [comment]
Latest version iina

**Comment by saagarjha** [comment]
Which URLs are you seeing this with?

**Comment by basavaraj1995** [comment]
YouTube

**Comment by saagarjha** [comment]
OK, but which URL exactly? You’re saying that IINA is crashing, so could you find the crash log on `~/Library/Logs/Diagnostic Reports` (it’ll start with “IINA”) and attach it here?

**Comment by basavaraj1995** [comment]
Fixes #950
