### ISSUE TITLE
字幕下载功能失效

### ISSUE THREAD

**Issue by yanzhenyu** [lhc70000/iina#957]
你好，开发者。
因为射手网于2017年夏季关闭。不再提供任何字幕搜索，下载。希望能更换字幕下载源。谢谢。

**Comment by J-Liu** [comment]
直接删了这个功能然后自己手动添加字幕吧，自动下载字幕属于service，需要不断的维护一个server。

**Comment by yanzhenyu** [comment]
@J-Liu 没有听懂，这只是调用字幕网一个接口而已，跟service维护有什么直接关系吗

**Comment by J-Liu** [comment]
没有服务商给你提供service，调用毛？

**Comment by yanzhenyu** [comment]
找个开放的api，需要维护是字幕网的事，跟作者软件有关系？

**Comment by HarukaMa** [comment]
收到并且已经确认了官网有相同的消息。

对此问题有其他补充请开新 issue 或邮件联系。欢迎提供新的字幕源的信息。最好有可以直接调用的 api 以便于集成。
