### ISSUE TITLE
It would be more perfect if the player just add files with the similar name in a folder to the playlist.

### ISSUE THREAD

**Issue by phielsyn** [lhc70000/iina#958]
It would be more perfect if the player just adds files with the similar name(like TV series) into the playlist in the same folder when opening a file.
Now, if you open a file in a folder in which there are hundreds of files, all files will be added to the playlist. 
Maybe provide an option.

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by MuntashirAkon** [comment]
Like the KMPlayer?

**Comment by minimum91** [comment]
I think @phielsyn means Autoloading like VOX does for audio files. ![VOX Settings](http://minims.kontakts.lv/files/pb-SzPWuSt3Kd.png)

**Comment by phielsyn** [comment]
for example, there are 5 videos in a folder, whose name are Harry Potter 01, Harry Potter 02, Harry Potter 03, Lord of the Ring, Harry Potter 04. When I double click to open Harry Potter 02, IINA only adds Harry Potter 01, Harry Potter 02, Harry Potter 03, Harry Potter 04 into the playlist, without Lord of the Ring.
