### ISSUE TITLE
iina cannot capture adobe flash videos

### ISSUE THREAD

**Issue by fwzmhmd** [lhc70000/iina#962]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 Build 37

**Steps to reproduce:**
Playing a video that uses adobe flash plugin

**How often does this happen?**
Everytime i try to play adobe flash videos on iina

**Comment by lhc70000** [comment]
@fwzmhmd Are you trying to play a SWF file, or some online videos that use flash player?

**Comment by fwzmhmd** [comment]
I'm playing an online video that uses flash. I have tried opening that video stream using the google chrome plugin.

**Comment by lhc70000** [comment]
@fwzmhmd IINA/mpv can only load video from websites supported by youtube-dl. Please refer to their website: https://rg3.github.io/youtube-dl/supportedsites.html

**Comment by fwzmhmd** [comment]
The website that I'm trying to view is supported on their website.

**Comment by lhc70000** [comment]
@fwzmhmd Then you may need to update your youtube-dl. See https://github.com/lhc70000/iina/wiki/Use-youtube-dl-with-IINA

**Comment by fwzmhmd** [comment]
I have update youtube-dl, but i still get cannot open file or stream

**Comment by lhc70000** [comment]
@fwzmhmd Could you give me an example link?

**Comment by fwzmhmd** [comment]
I'm using HBO Now to stream but you won't be able to view since it requires a subscription. I have found another site which I get the same error. http://www.dhs.state.il.us/accessibility/tests/flash/video.html

**Comment by lhc70000** [comment]
@fwzmhmd Please try youtube-dl <your link> in terminal. If there's an error, please report to youtube-dl; otherwise you probably missed some configuration in IINA. 

I personally speculate that those videos are protected by copyright and playable only on their webpage.

**Comment by CaptainYukinoshitaHachiman** [comment]
LHC: Then it's not my fault lol

**Comment by fwzmhmd** [comment]
@CaptainYukinoshitaHachiman ?
