### ISSUE TITLE
Bug: Cannot use music control keystrokes when IINA is opened and not playing.

### ISSUE THREAD

**Issue by JunyuKuang** [lhc70000/iina#966]
F7, F8, F9 playback keys on Magic Keyboard are unusable when IINA is opened and not playing.

I have to close IINA when I want to control playback of iTunes.

- macOS 10.12.6
- IINA 0.0.12

**Comment by alejx** [comment]
That's a known issue but it is hard to resolve for now. Currently mpv is capturing the media keys, it blocks all media keys whenever it is running. However, apple make a MediaPlayer framework in macOS 10.13+, and we're going to support it after 10.13 is released. See [this branch](https://github.com/lhc70000/iina/tree/MediaPlayer-framework).

**Comment by ErikMinekus** [comment]
Looks like that branch has already been merged, so this should be resolved?

**Comment by nuynait** [comment]
I encountered this issue in version 1.0.2 Build 105. The media key doesn't work for me. After seeing this ticket I realize that I should try to use the media key when the video is playing and then it works. (file .mp4)
