### ISSUE TITLE
Show audio track name in natural language (e.g. "Deutsch" instead of " #1 [deu]" )

### ISSUE THREAD

**Issue by fabi94music** [lhc70000/iina#968]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
Show audio track name in natural language (e.g. "Deutsch" instead of " #1 [deu]" )

**Comment by fabi94music** [comment]
Same for video tracks :) 

Besides that the app is nearly perfect! I like the interface and supported macOS features a lot! :)

**Comment by AndyChen2005121** [comment]
well, check if the audio track is ALREADY named that way.

**Comment by fabi94music** [comment]
How can I do this? When I play the mp4 file with QuickTime it shows "English" or "Deutsch", but with iina it shows "#1[deu]" or "#2 [eng]".

**Comment by lhc70000** [comment]
Added in develop branch.

**Comment by fabi94music** [comment]
Could there be an option to only have The Language Displayed without the other information? 
<img width="371" alt="bildschirmfoto 2017-10-19 um 11 51 47" src="https://user-images.githubusercontent.com/29753374/31765247-0cea971e-b4c4-11e7-9a99-c43d1cb8e809.png">
Would like to have only "Deutsch" and "English" but not the the additional info. Maybe this can be a turn on/off feature.
