### ISSUE TITLE
Control bar changes to be more consistent with QuickTime

### ISSUE THREAD

**Issue by DrabWeb** [lhc70000/iina#97]
Proposed design

![screen shot 2017-01-07 at 1 58 07 pm](https://cloud.githubusercontent.com/assets/6215387/21743860/549c6c22-d4e1-11e6-8228-bb0c9fee081a.png)

![screen shot 2017-01-07 at 1 59 28 pm](https://cloud.githubusercontent.com/assets/6215387/21743867/88d577a4-d4e1-11e6-9032-6cdf7bb0da7d.png)

![screen shot 2017-01-07 at 2 06 04 pm](https://cloud.githubusercontent.com/assets/6215387/21743922/72093528-d4e2-11e6-9e22-177b33a74d8e.png)

* Fade duration for titlebar and control bar are changed to `0.25` seconds
* Position and duration labels are `10pt` instead of `9pt`
* Labels in the control bar are all 50% opaque to be vibrant
* Icons in the control bar are changed to be consistent with system icons, made templates to adapt to the theme and changed to pdfs so they're crisp on all resolutions
* Control bar corners have `4px` radius instead of `6px`
* Proper titlebar title centering

Layout and interaction are unchanged, meant to be more consistent with QuickTime. If you want to try it yourself you can compile the `control-bar-revamp` branch in my fork. PR is #90 

Looking for some feedback/approval from users before having it merged, so leave your thoughts here if you have any

**Comment by megadr01d** [comment]
I prefer shortcut keys myself, but anyway, I'm not sure why we haven't yet changed the volume bar paradigm and make it circular. Not only fits the size of the other icons (and UI symmetry), but it's also easy to control with a trackpad/mouse.

I think it's way easier to click anywhere on a round icon and move up/down to turn the volume up/down than to aim at a thin bar or small knob. Sometimes it's so badly implemented that moving a bit up or down while we're moving left or right (while holding left click), will take the pointer out of the slider bar, losing focus.

Example Volume Icon

![qjhae](https://cloud.githubusercontent.com/assets/9649385/21933348/f5ed7656-d99c-11e6-8abf-a47659c0a9d0.png)

Example Volume Icon and Mute Icon in one (clicking once would mute/unmute, clicking and holding + moving up/down would change volume)

![minimal_slider_widget___volumes](https://cloud.githubusercontent.com/assets/9649385/21933351/fb86126c-d99c-11e6-8ffa-cd26d41b03b9.png)

**Comment by lhc70000** [comment]
This issue will be closed since it's merged.

@megadr01d Let's move to #217 for your suggestions.
