### ISSUE TITLE
In no work state, power consumption is too high

### ISSUE THREAD

**Issue by huangyangme** [lhc70000/iina#979]
In no work state, power consumption is too high

<img width="244" alt="2017-08-20 9 40 35" src="https://user-images.githubusercontent.com/4213398/29491357-e32397b2-858b-11e7-9f85-96d9acb52fd3.png">

![2017-08-20 at 9 35](https://user-images.githubusercontent.com/4213398/29491359-e9840588-858b-11e7-9a1e-48a8ca1111ae.png)

**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Comment by xiaoken** [comment]
不知所以然，你都把IINA關掉了，功耗是0啊-_-a
平均功耗是App開啟時候的平均，看不出有什麼問題。
