### ISSUE TITLE
Modifiable shortcuts

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [lhc70000/iina#980]
Glad to see this project!
Had tried mpv but stopped using due to lack of GUI.
Still installed because it plays stuff VLC won't, or that is has difficulty with.

I prefer ⌘F as the Fullscreen shortcut as in VLC, but didn't see a way to quickly change it in the prefs - had to add it in the system keyboard prefs.

That's my opinion anyway, I know some (weird) folks prefer ⌃⌘F.

- OS X 10.12.6
- IINA 0.0.12

**Comment by lhc70000** [comment]
You can add a key binding for "Cycle Fullscreen" in Preference > Keybindings.

**Comment by saagarjha** [comment]
> That's my opinion anyway, I know some (weird) folks prefer ⌃⌘F

Just FYI ^⌘F is the standard fullscreen shortcut for full screen. ⌘F is usually bound to "Find".

**Comment by R-L-T-Y** [comment]
I would hope to be able to modify other shortcuts like "Find online subtitles" and "Enter PIP mode".

**Comment by lhc70000** [comment]
@R-L-T-Y You can set shortcut keys for them in Preference > Keybindings.

**Comment by GitTheHellOutaHere** [comment]
I started this thread 5 days ago because of this message posted on the [IINA website:](https://lhc70000.github.io/iina/)

> It's currently a personal project, but please feel free to contribute it by raising a issue, send a feature request or bug report on github or by email.

I don't *want* a video player that is barely functional or that I have to mod myself.
If I did I'd still be using mpv.

IMO most users want a **FULLY FUNCTIONAL GUI**.
One that includes preferences for adjusting settings and the ability to to **QUICKLY AND EASILY** change key commands if necessary.

I had no idea what the term keybinding was until I saw them in the prefs. So I didn't know I could add my own (if I knew how). I don't even understand everything on your [keybinding page.](https://github.com/lhc70000/iina/search?utf8=%E2%9C%93&q=keybindings&type=)

At the top is an entry for VLC keybindings. Is that one simple line supposed to enable IINA's keys to function like VLC's? Because it doesn't look like it, and not all will function in IINA anyway.

"**Note that some of the VLC keybindings are not supported by IINA**"

The rest of the page is mostly other languages. There should at least be an instruction page that shows which keybindings _can_ be enabled, and the instructions to do so.




And while I don't mind altering my hosts file or tinkering with system settings and such, I'm not about to spend time trying to understand a new video player and tweaking its config file.

A video player should be install-and-go, no advanced steps required.
Those who don't like one will just find another, most ending back up at VLC - it seems all roads lead to VLC.



And apparently I'm not the only one who prefer other shortcuts since R-L-T-Y is asking for similar modifications.

I think almost everyone is familiar with VLC. And it's been difficult adjusting to IINA's differing shortcuts. In VLC, ⌘+< and ⌘+> will send you to the beginning or end of the video.
In IINA it scrubs back/forward 5 seconds.

I frequently use ⌘⌥+< and ⌘⌥+> to skip forward/back several seconds in VLC, and that's one of the few shortcuts I use regularly so it's automatic.

Try that in IINA and it _pauses_ the video.
And if you hold all 3 buttons you get a virtually useless frame-by-frame scrub.

Might be good for sports fans or pervs checking for a nip-slip, but it's not something the vast majority would use regularly, and IMO shouldn't be assigned to that easily-accessible location.
It should be in a menu.

I also had to disable volume scrolling because I kept accidentally changing it.
IMO that should only function when the cursor is over the volume control on the controller, else anywhere over the controller. I think seeking should also only work when over the controller.

Enabling it anywhere on the entire screen is unnecessary and invites unintended changes.
My Logitech MX Performance mouse has a very sensitive scroll wheel, and the slightest nudge, (less than a full click in click mode) moves the volume. Jiggling the mouse in my hand makes it change!

I realize this doesn't have a team behind it like VLC does.
And it has taken many years to get VLC to its current state.
Therefore it's preposterous to believe that IINA will ever implement as many features or be as user friendly.


And here's bug that is unrelated to keybinding, but aggravates the hell out of me.
Frequently when Im watching a video in fullscreen, I often switch apps (via  ⌘+tab) to check my email or something.
When I click IINA's Dock icon, **I WANT TO SEE THE PLAYER IMMEDIATELY!!!!!!!!!!!!**

Clicking once only shows IINA's menu. WHAT GOOD IS THAT?!
Every other app shows me its main window when I click its icon, NOT it's menu.

So I forget every time and only click once, expecting to returmn to the player.
But *nooooo*, I gotta scroll back down and click it a second time because IINA thinks I enjoy staring at its menu while the video plays in another window. **WTF?!**


You asked for feature requests, so there's mine (and R-L-T-Y's).

**Comment by saagarjha** [comment]
> WHEN I CLICK IINA'S DOCK ICON, I WANT TO SEE THE PLAYER IMMEDIATELY!!!!!!!!!!!!

This is most likely a bug. We’ll work on it, but I’d recommend splitting it out into a seperate issue so it doesn’t get lost.

**Comment by GitTheHellOutaHere** [comment]
I _KNEW_ you were gonna say that!

But I'm not gonna, so I hereby allow you to post it.

**Comment by saagarjha** [comment]
We have [wiki page](https://github.com/lhc70000/iina/wiki/Manage-Key-Bindings) that might be useful if you’re curious on how to change them.

**Comment by lhc70000** [comment]
> I had no idea what the term keybinding was until I saw them in the prefs. So I didn't know I could add my own (if I knew how). I don't even understand everything on your keybinding page.

It's not "our keybinding page", it merely searches the source code. Unless you're a developer, there'll be nothing useful. The term "Key binding" is being used by mpv and some Apple's Apps, like Xcode, so I think it's appropriate.

> I also had to disable volume scrolling because I kept accidentally changing it.

That's why it's designed to be toggale-able.

---

Seems that you are familiar with VLC's shortcut keys and not interested in learning another keybinding set. That's fine, since most of our users are migrated from other players, and we've noticed the needs. **In the next version**, we'll add VLC, MPlayerX and Movist's shortcuts as built-in configs, so you won't need to set them one by one. And that's why you can see "an entry for VLC keybindings" in the code search - It's in our development branch, but not published and deployed yet.

Please be tolerant. IINA came out only 8 months ago, while VLC is more than 10 years old. But there must be some reason why I start this project from scratch and making it free and open source for no profit, especially when there exist a bunch of alternatives like VLC and Movist. It's user experience. VLC can't even perform smooth animation when you resize the window or enter fullscreen. So **your opinion is valued**. I'll definitely go over your suggestion and try to make it accessible for fresh users. As posted above, here's a [tutorial in our wiki](https://github.com/lhc70000/iina/wiki/Manage-Key-Bindings). Hope you'll find setting key bindings not that difficult after reading it.

The version number now is 0.0.12, which indicates, IINA is still in an early development phase, and that's why I never promoted IINA publicly. But there'll be a stable release, when we finished [all these remaining stuff](https://github.com/lhc70000/iina/issues/898), after 0.0.13. You are free to use any player you like, but welcome checking it out later.

**Comment by GitTheHellOutaHere** [comment]
We're all familiar with the term *shortcut* that we've been using for years.

But if Apple said it, it **MUST** be the correct term, huh?

**Comment by HarukaMa** [comment]
@GitTheHellOutaHere Yeah, we like this way. You can always fork if you like it otherwise, nothing is stopping you, of course.

**Comment by GitTheHellOutaHere** [comment]
> nothing is stopping you


O'RLY?

How about coding skills, a lack of desire and a shortage of time?

**Comment by saagarjha** [comment]
@GitTheHellOutaHere Please be civil. You're literally arguing over the choice of "Key bindings" over "Shortcuts".

**Comment by lhc70000** [comment]
Sigh. mpv uses the word "key binding", and IINA is based on mpv. That's all. Just want to add some technical note about the difference: In mpv, you bind a key code to **an** arbitrary command; in VLC, you set **the** shortcut key to one of some predefined operations.

**Comment by GitTheHellOutaHere** [comment]
Who's being uncivilized?
My requests were submitted.

Then saagarjha suggested I go fork (it) myself.

Please show me where I've used obscenities or vulgaities, attacked someone or otherwise been "uncivil."


Didn't think so.

**Comment by GitTheHellOutaHere** [comment]
And I was simply trying to make the point that I think most average users are familiar with the term *shortcut,* not keybinding.


So when you tell someone unfamiliar with the term to add a keybinding, they're like **SAY WHAT?**

**Comment by saagarjha** [comment]
While you may not have used obscenities or vulgarities, your tone certainly appeared argumentative. If that was not your intention, I'd suggest reducing your usage of CAPS and **bolded** text.

**Comment by GitTheHellOutaHere** [comment]
Well I would **MUCH** prefer to use **UNDERLINES** in many cases, but this forum does **NOT** offer that option.

In grammar, bolded text is used to express *emphasis*, not purely to represent it as a combative assertion.


>Emphasis:
special importance, value, or prominence given to something

>stress laid on a word or words to indicate special meaning or particular importance.

**Comment by HarukaMa** [comment]
Please use email to continue discuss this issue.

Please read all replies above first.
