### ISSUE TITLE
I can not run it in macOS 10.13

### ISSUE THREAD

**Issue by ZSwitch** [lhc70000/iina#982]
![qq20170821-204553 2x](https://user-images.githubusercontent.com/16774273/29519925-c233b308-86b1-11e7-951a-630fcf3e3796.jpg)

**Comment by lhc70000** [comment]
It's a problem with GzipSwift in Xcode 9. You can either try the `swift-4` branch or comment out `pods/GzipSwift/zlib/module.modulemap` temporarily.
