### ISSUE TITLE
YouTube视频打不开

### ISSUE THREAD

**Issue by SecondhandRose** [lhc70000/iina#986]
![image](https://user-images.githubusercontent.com/18202375/29595272-104a1c0c-87e9-11e7-883d-f272429af361.png)
![image](https://user-images.githubusercontent.com/18202375/29595279-1834865a-87e9-11e7-98d0-cd9c3d67ce29.png)

已经配置了youtube-dl
![image](https://user-images.githubusercontent.com/18202375/29595250-f10b0ff4-87e8-11e7-973f-691df7701a83.png)

播放YouTube视频时提示：
![image](https://user-images.githubusercontent.com/18202375/29595344-6b89b230-87e9-11e7-8009-c7bf02e50729.png)

**Comment by lhc70000** [comment]
参见 [wiki](https://github.com/lhc70000/iina/wiki/使用-IINA-和-youtube-dl-观看网页视频)：

> 如果用 homebrew 的默认安装，你应该填入：
> ```
> /usr/local/bin/
> ```

**Comment by SecondhandRose** [comment]
通过homebrew安装的
![image](https://user-images.githubusercontent.com/18202375/29595742-0491e360-87ec-11e7-9643-2aa8736a1a66.png)

![image](https://user-images.githubusercontent.com/18202375/29595699-c1366bd6-87eb-11e7-9e61-6aa069f6d128.png)
修改了，也重启了，还是不可以。。

**Comment by lhc70000** [comment]
@SecondhandRose 请参考 wiki，在需要的情况下设置代理

**Comment by SecondhandRose** [comment]
真瘠薄麻烦，不用了！

**Comment by hufengxiao** [comment]
同样的问题，现在解决了吗？
