### ISSUE TITLE
Jagged edges can be observed when IINA plays a low resolution video in full screen mode

### ISSUE THREAD

**Issue by guoyf** [lhc70000/iina#987]
英语不好，写中文吧。IINA播放低分辨率视频，全屏后画面可见锯齿，但mpv没有此现象。以下截图对比：

测试视频：
链接: https://pan.baidu.com/s/1qYVwRnA 密码: d3k4
视频分辨率704x534，全屏播放，取 00:04:38.879 时间的截图。
IINA全屏播放截图：
https://imgly.net/img/CGh.png
mpv全屏播放截图：
https://imgly.net/img/CGz.png
可以看出来mpv的截图看起来比较清晰，而IINA的看起来比较模糊。
以上IINA截图在Photoshop中放大到3倍：
https://imgly.net/img/CGl.png
以上mpv截图在Photoshop中放大到3倍：
https://imgly.net/img/CGK.png
可以看到IINA的截图有明显锯齿，而mpv平滑无锯齿。

以上截图mpv版本都是0.26，发现IINA 0.0.12是基于mpv 0.25，于是又使用mpv 0.25测试了一下，也是平滑无锯齿的。另外，IINA设置中的“在Retina屏幕上使用物理分辨率”，无论是否选中都有此问题。

**System and IINA version:**
- MacBook Pro (Retina, 13-inch, Mid 2014)
- macOS 10.12.6
- IINA 0.0.12
- mpv 0.26 (built by stolendata)

**Comment by lhc70000** [comment]
请问是否在使用 mpv 的配置文件？

如果你的配置文件中有 `vo=opengl-hq`，即使你设置了 IINA 的 mpv 配置目录，也需要在 IINA 中单独指定 `profile`（参见 #587）

**Comment by guoyf** [comment]
锯齿的问题确实是因为`vo=opengl-hq`选项引起的，我在mpv中禁用这个选项后，mpv也产生了跟IINA同样的锯齿。

不过我在IINA中并没有使用mpv的配置文件。我尝试在IINA中配置`profile `选项，却遇到问题，跟这个帖子中描述的一样：https://github.com/lhc70000/iina/issues/587#issuecomment-318700043 ，重启IINA后提示`无法设置选项 --profile=opengl-hq （返回值 -5）。 请在「设置>高级」中检查你的额外 mpv 选项。`并且播放视频仍然有锯齿，说明配置没有生效。是否我配置的方式不对？

**Comment by guoyf** [comment]
我又试了一下，mpv配置文件中有`profile=opengl-hq`，只要在IINA中设置mpv配置目录就可以生效，IINA中单独配置`profile`选项反而会出错。

**Comment by lhc70000** [comment]
目前看来是 mpv 的 API 不支持 `profile`。建议先使用配置文件。
