### ISSUE TITLE
加载字幕 bug

### ISSUE THREAD

**Issue by weqopy** [lhc70000/iina#990]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12

**Expected behavior:**

涉及字幕 Sherlock 第三季
1. 打开 IINA，然后通过‘打开...’选项播放 Sherlock S03E01, E02等时，只有声音，无画面，弹窗显示字幕错误，且‘好’按钮无法点击以关闭提示，只能强制退出，如图
<img width="636" alt="2017-08-27 19 50 08" src="https://user-images.githubusercontent.com/10494196/29749530-f77294d6-8b60-11e7-9c86-7d862131ea06.png">
2. 首先播放其他可正常播放的视频，如 Sherlock S02E03, 然后在播放列表中选择 S03E01，可以正常播放，仍然有弹窗提示错误，但提示可点击以关闭。此时 app 字幕、副字幕均显示为空，无法识别同一文件夹下的字幕文件，点击‘加载字幕’后手动选择，可以识别、正常播放。

**How often does this happen?**
Alaways.

**Comment by lhc70000** [comment]
我们会在近期切换字幕源并优化下载字幕的逻辑。有待观察更新后是否可以解决此问题。
