### ISSUE TITLE
movie recording and audio recording

### ISSUE THREAD

**Issue by basavaraj1995** [lhc70000/iina#996]
this is feature request !
IINA is amazing media player if you add these feature it will awesome

**Comment by oscar-c** [comment]
Isn't this feature already provided by Quicktime Player?

**Comment by basavaraj1995** [comment]
Yeah, but it will be nice if you add these features

**Comment by lhc70000** [comment]
Sorry but currently we want to put more effort in playback related features.

Duplicate with #110. Please continue the discussion there if necessary.

**Comment by basavaraj1995** [comment]
Okay 😎

On Aug 30, 2017 8:07 AM, "Collider LI" <notifications@github.com> wrote:

Sorry but currently we want to put more effort in playback related features.

Duplicate with #110 <https://github.com/lhc70000/iina/issues/110>. Please
continue the discussion there if necessary.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lhc70000/iina/issues/996#issuecomment-325861862>, or mute
the thread

**Comment by getsmarted** [comment]
Do hope you will add in future. Quicktime can lag badly when recording from phone and sometimes has issues playing external external sound while recording. Ability to record from devices and streams directly from IINA app windows would be great.

**Comment by HarukaMa** [comment]
@getsmarted My best guess is recording from iOS devices are parts of private API and not documented anywhere.

**Comment by saagarjha** [comment]
Hasn't stopped us before :)
