### ISSUE TITLE
Volume control bug

### ISSUE THREAD

**Issue by kashx** [lhc70000/iina#998]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
When I set the maximum volume value higher than 100 in the Codec tab at Preferences it should let me control the volume to my set value with both keyboard (up/down arrow keys) and vertical mouse scroll.

**Actual behavior:**
I can control the volume over 100 with my keyboard (up/down arrow keys) just fine, but the vertical mouse scroll volume control is limited to 100 max.

**Comment by lhc70000** [comment]
Duplicate with #365, #463, #683, #694, #699
